### ISSUE TITLE
prerequisites.sh wrong ssl

### ISSUE THREAD

**Issue by suminus** [AirenSoft/OvenMediaEngine#100]
hey devs,

please consider updating the **OvenMediaEngine-0.10.1/misc/prerequisites.sh** with

`OPENSSL_VERSION=1.1.1f`

to prevent the script to fail.

thx

**Comment by getroot** [comment]
We fixed the problem by changing the OPENSSL link to GITHUB 10 days ago. Are you still having problems?

Of course we will upgrade OPENSSL someday.

**Comment by suminus** [comment]
oh, ok.  issues are gone in OvenMediaEngine-0.10.1.
had the error in a previous install 2 weeks ago.

sorry for bothering you.

stay healthy!
