### ISSUE TITLE
LLHLS potentially unstable when receiving streams from VMIX

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenMediaEngine#1002]
Greetings

I've just noticed that the timestamp in the #EXT-X-PROGRAM-DATE-TIME tags are ok when the stream is sent from OBS, but completely wrong when it's from Vmix.

Is it possible for OME to overwrite these tags when re-encoding?

Thanks in advance

Regards

**Comment by getroot** [comment]
What does it mean that #EXT-X-PROGRAM-DATE-TIME is wrong? Please tell me how it depends on OBS and Vmix. Note that #EXT-X-PROGRAM-DATE-TIME in the spec is not a value that must represent the wall clock time.

**Comment by gregfr** [comment]
Thanks for your answer.

I'm not familiar enough with the HLS spec to really understand it, but when using the demo page of Theo player, I noticed than a stream sent from OBS shows a correct time, but when sent from Vmix the time is several hours ahead in time. Oven Player plays fine the OBS stream and has erratic behavior with the VMix stream (maybe because it gives negative latency).
Looking at the HLS manifests, I see than the #EXT-X-PROGRAM-DATE-TIME tags are correct for the OBS stream, and bogus with the Vmix one.
I was really surprised to see the encoding software has this effect on the final stream.
So I inferred that the sending steamer softwares inject theses values and OME relays them. Of course I might be wrong :)
BTW I checked that the clock and time zone of the sending computer are correctly set.

Regards

**Comment by getroot** [comment]
Ah... did you think encoders like OBS and VMIX send LLHLS streams and OME just relays them? Then I get what you mean by your previous question. (Before that, I didn't understand the question.)

OBS and VMIX send streams over RTMP. OME parses the raw media data from it, re-encodes it, and packages it for LLHLS and WebRTC. LLHLS playlists, segments and chunks are all generated by OvenMediaEngine. Also EXT-X-PROGRAM-DATE-TIME is a value generated by OME directly.

VMIX's PTS/DTS values may be completely different from what we expect. It may make LLHLS streams unstable when receiving streams from VMIX.

Please change the title of this post to LLHLS is unstable when receiving streams from VMIX, and let me know what your VMIX settings are so I can reproduce the problem.

**Comment by gregfr** [comment]
Thanks for your answer. 

I didn't think OME is just a relay ^^ and that's why I was so puzzled to see that the encoding software has an impact on the delivered stream (BTW we tend to use SRT instead of RTMP).
I'll dedicate most of this week to set up a stable streaming chain so I will do many tests and report to you what I find.

Regards and thanks again!

**Comment by gregfr** [comment]
Here is a quick screenshot:
![image](https://user-images.githubusercontent.com/361582/217601825-c879b9ea-4ce2-4028-8d23-2b49eec4df85.png)

On the left is Theo player, it shows a weird timestamp and is quite late (about 1 min) compared to Oven Player on the right.

The stream is from Vmix and OvenMedia Engine.

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/217703391-5c2856b1-78fd-42fd-a959-e37eed1f01e1.png)

In my environment, I could not reproduce the problem. Please share your vmix configuration so that I can reproduce the problem.

**Comment by gregfr** [comment]
I see you're using RTMP, did you try SRT?

**Comment by getroot** [comment]
No I didn't know vmix supports srt and your problem is from srt with vmix. How can I enable srt on vmix?

**Comment by gregfr** [comment]
It's different from RTMP stream, it's an ouput:

![Image](https://user-images.githubusercontent.com/361582/217897949-4813a742-db6c-4dc0-9c7d-308d64d5c887.jpeg)

**Comment by getroot** [comment]
I updated the time value to display well in THEO player. You can test this with master branch.

**Comment by gregfr** [comment]
Thanks! I'll test that ASAP. What was the problem? (I guess it's inside this commit: https://github.com/AirenSoft/OvenMediaEngine/commit/2ebc6a08f9d09063b6335c6a03fabccb99156550 ?)

**Comment by gregfr** [comment]
It's working perfectly; also the issue I mentioned in https://github.com/AirenSoft/OvenPlayer/issues/327 is fixed, thanks a million!! :+1:
