### ISSUE TITLE
OvenRtcTester not working?

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenMediaEngine#1009]
**Describe the bug**
I tested OvenRtcTester.go but it can't get an offer. I remember using this tool almost 2 years ago. 

**To Reproduce**
1. compile OvenRtcTester.go after commenting out the line with PayloadOffet (because it is not there anymore)
2. ./OvenRtcTester -n 10 -url "ws://fr.xxxx.com:3333/app/murat"
client_0 failed to run (reason - invalid offer message received : ws://fr.xxx.com:3333/app/murat ({"code":404,"error":"Cannot create offer"}))
<Summary>
Number of clients : 0
^CTest stopped by user
***************************
Reports
***************************
<Summary>
Number of clients : 0
<Details>

**Expected behavior**
It should get a valid offer and publish webrtc streams

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.

**Server (please complete the following information):**
 - OS: Debian 10 Linux
 - OvenMediaEngine Version: [e.g. v0.14.18]
 - Branch: [e.g. master]

**Additional context**

**Comment by getroot** [comment]
> ws://fr.xxx.com:3333/app/murat ({"code":404,"error":"Cannot create offer"}))

Check that the ws://fr.xxx.com:3333/app/murat stream is really working.

**Comment by mpisat** [comment]
It's my bad, for some reason I remembered this tester for publishing benchmark, not playback. I'll start stream and test playback accordingly.
