### ISSUE TITLE
Transcode pulled RTSP stream

### ISSUE THREAD

**Issue by ruifigueirinha** [AirenSoft/OvenMediaEngine#101]
Is it possible to transcode a pulled H264 RTSP stream to VP8 and make it available through the signalling port?

**Comment by getroot** [comment]
Unfortunately, the RTSP Pull feature is still an experimental feature. We will fully support this feature in the next version.

**Comment by ruifigueirinha** [comment]
Thank you for the response.

**Comment by getroot** [comment]
The feature has released as Beta in version 0.10.4.
