### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by umeshshende** [AirenSoft/OvenMediaEngine#1010]
Doing performance testing with Standard B2s (2 vcpus, 4 GiB memory) azure VM and running for 10users

Manual - Currently im opening same 5-10 connection in single browser for testing 
using RTCTester - i also tried RTCtester but its same result Delay or packet loss is high 

CPU and Memory wasn't high even delay and packet loss is high 

**URL**
broadcast - wss://ourserverurl:3334/app/stream1234?direction=send&transport=tcp
viewer- wss://ourserverurl:3334/app/stream1234?transport=tcp

**Expectation** 
It should allow 10 connection in lower configuration 

**Actual** 
It Delay in video and most of them are automatically close even broadcast is running 

**CPU and Memory during the testing** 
![image](https://user-images.githubusercontent.com/18421798/215970598-387d665b-8d95-4b41-a707-1b5e12d9b6bf.png)
[Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10553954/Server.txt)

**Comment by getroot** [comment]
Unfortunately no one will be able to help you with the information you provide. It is essential to provide at least the information required by the template.

For reference, in our environment, OvenMediaEngine outputs well over 5Gbps.

- What version of OvenMediaEngine are you using?
- Upload /var/log/ovenmediaengine/ovenmediaengine.log file.
- How many connections are normally operated? Does it play normally when there is only one connection?
- Is the network speed between the server and the client fast enough? Is your client speed enough?
- Packet loss does not occur in TCP transmission. Why do you think it is packet loss? If so, capture that information and post it.
- View the input/output graphs in chrome at chrome://webrtc-internals. Are there any odd numbers?
- See https://airensoft.gitbook.io/ovenmediaengine/troubleshooting.
- see https://airensoft.gitbook.io/ovenmediaengine/performance-tuning

**Comment by umeshshende** [comment]
**What version of OvenMediaEngine are you using?** 
14.18
**Upload /var/log/ovenmediaengine/ovenmediaengine.log file.**

[Log_1_Feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10554384/Log_1_Feb_2023.txt)

**How many connections are normally operated? Does it play normally when there is only one connection?**
One connection play normally , Doing performance Testing using rtc tester 1min for 15 users

**Is the network speed between the server and the client fast enough? Is your client speed enough?**
yes using   Standard B2s (2 vcpus, 4 GiB memory) azure VM

**Packet loss does not occur in TCP transmission. Why do you think it is packet loss? If so, capture that information and post it.**

Not packet loss but delay in video and some connection getting closed 
broadcast - wss://ourserverurl:3334/app/stream1234?direction=send&transport=tcp
viewer- wss://ourserverurl:3334/app/stream1234?transport=tcp
![image](https://user-images.githubusercontent.com/18421798/215979592-78c6e005-4f27-4586-a908-27de35e430fd.png)



**View the input/output graphs in chrome at chrome://webrtc-internals. Are there any odd numbers?**
I have capture one of connection closed details
![image](https://user-images.githubusercontent.com/18421798/215979381-820363de-c72f-4bf8-b779-5735a2154df9.png)

**Comment by getroot** [comment]
WebRTC input in 0.14.18 may work unstable, so please test with 0.15.0.

And type chrome://webrtc-internals into Chrome's address bar. It is different from the developer web console.

Azure VMs do not guarantee your network speed. You would have sent a stream from your PC or Mobile to Azure's OvenMediaEngine to input the stream. What I want to check is the Azure server from your PC. If you are unsure of this, it is a good idea to stream to the OME server over RTMP using ffmepg from another server in Azure.

**Comment by umeshshende** [comment]
You meant to say my PC to azure VM(OME server) network is cause of this delay and failed connection?

**Comment by getroot** [comment]
If the network between your PC and the VM server is slow, there will of course be delays. I just told you that this is one of the many factors to check.

Just install 0.15.0 the same way you installed 0.14.18. server.xml is not overwritten. I don't know if you are using docker or just installed it on the server. If you are using docker, you can use airensoft/ovenmediaengine:0.15.0.

**Comment by umeshshende** [comment]
i have installed using manual installation not docker. Okay then i will follow the same way.

**Comment by umeshshende** [comment]
Getting below error when reinstalling same for 15

$ (curl -LOJ https://github.com/AirenSoft/OvenMediaEngine/archive/master.tar.gz && tar xvfz OvenMediaEngine-0.15.0.tar.gz)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 13.1M    0 13.1M    0     0  3977k      0 --:--:--  0:00:03 --:--:-- 5931k
curl: Saved to filename 'OvenMediaEngine-master.tar.gz'
tar (child): OvenMediaEngine-0.15.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
$ OvenMediaEngine-0.15.0/misc/prerequisites.sh^C

**Comment by umeshshende** [comment]
**And where is OvenRtcTester running?**
Window machine my current local machine 

Okay I ll install and retest using rtctester will tell you know the result

**Comment by getroot** [comment]
Ah... OvenRtcTester was running on your PC. It is recommended to run it on another server on the same network as the OvenMediaEngine server to remove network variables from the home network. Also OvenRtcTester is also very resource intensive. (Of course, with about 15 instances, this is not a problem in most cases.)

Then I think the first thing you should do is to measure the network speed between your PC and VM with a tool like iperf.

**Comment by umeshshende** [comment]
Thank you, I will use seprate Azure VM for RTCTester after upgrading to 15 and will let you know the result

**Comment by getroot** [comment]
Yes... of course. If the network between your pc and the VM is slow, the open ovenplayer instance on your pc is also slow. And your PC's broadcaster slows down as well. There is no difference between ovenrtctester and ovenplayer...
ovenrtctester is just a tool for testing tens/hundreds of instances at once in the cli environment, and the internal operation is the same as ovenplayer.
