### ISSUE TITLE
Adaptive Bitrates Streaming not able to enable in ovenplayer

### ISSUE THREAD

**Issue by umeshshende** [AirenSoft/OvenMediaEngine#1014]
Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

**PROBLEM**
Im trying to enable ABR using https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing ABR section but it not able to enable even in [ovenplayer ](https://demo.ovenplayer.com/demo_input.html) not working im not able to view quality section under setting (ovenplayer)

![image](https://user-images.githubusercontent.com/18421798/216560701-e7a2225c-db97-49a6-968b-27434f4ca955.png)

**EXPECTATION**

Quality setting should display under oveplayer->setting 

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
OME 15
Linux  ubuntu 20

- Encoder information

WEBRTC streaming 
Using online ovenplayer and as well as implemented ovenplayer in machine 
- Player information

issue also present in  https://demo.ovenplayer.com. 

- URL

**broadcast**
wss://demo.ovenplayer.com:3333/app/test-input-stream?direction=send&transport=tcp/abr
wss://ourserver:3334/app/stream1234?direction=send&transport=tcp/abr

**view**
wss:demo.ovenplayer.com:3333/app/test-input-stream?transport=tcp/abr
wss:ourserver:3334/app/stream1234?transport=tcp/abr

- Operating system and version

Ubuntu 20.04

**SETUP INFORMATION AND LOGS**

[Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10577482/Server.txt)
[log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10577523/log.txt)
please check log file details date from [2023-02-03 08:16:44.709]

**OTHER HELPFUL INFORMATION**

[Please write any information that anyone viewing this issue can reference.](https://demo.ovenplayer.com/demo_input.html)
Demo ovenplayer also not showing quality

**Comment by getroot** [comment]
In the HTTP URL, the query string must be written with a ? at the end of the resource. playlist file name is a resource.

ws[s]://domain[:port]/<app name>/<stream name>/<playlist file name>?query-string

**Comment by umeshshende** [comment]
I dont understand.  Im using below

**broadcast**
wss://demo.ovenplayer.com:3333/app/test-input-stream?direction=send&transport=tcp/abr
wss://ourserver:3334/app/stream1234?direction=send&transport=tcp/abr

**view**
wss:demo.ovenplayer.com:3333/app/test-input-stream?transport=tcp/abr
wss:ourserver:3334/app/stream1234?transport=tcp/abr

**Comment by getroot** [comment]
Broadcast does not require the use of a playlist.

For viewers, configure the url as follows.

`wss://ourserver:3334/app/stream1234/abr?transport=tcp`

**Comment by getroot** [comment]
And demo.ovenplayer.com server does not have abr encoding settings. Don't use it for that purpose. Test using your server.

**Comment by umeshshende** [comment]
Thanks @getroot  it work issue in the url 
wss://ourserver:3334/app/stream1234/abr?transport=tcp
![image](https://user-images.githubusercontent.com/18421798/216579945-084d6fa7-ecb2-4a06-96cc-a1b8e7e38b0e.png)
