### ISSUE TITLE
ABR - Depending on incoming stream quality

### ISSUE THREAD

**Issue by Pernifloss** [AirenSoft/OvenMediaEngine#1018]
Hello !

Can I configure ABR depending on incoming stream resolution?

For example, if the incoming stream is in 1080p I want to transcode it in 720p and 576p
But if it is in 720p, I just want to transcode it in 576p.

Is there some configuration that automatically transcode “only when necessary”.

Or do I have to define 2 application and the streaming client have to choose on which one to stream, depending on its streaming resolution?

Thanks in advance  !

**Comment by Pernifloss** [comment]
I found this : https://github.com/AirenSoft/OvenMediaEngine/issues/437
Is there any documentation on how to configure it? Does `<DoNotUpscale>true</DoNotUpscale>` is correct?

Thanks.

**Comment by getroot** [comment]
This feature has been released.
https://github.com/AirenSoft/OvenMediaEngine/issues/1053

**Comment by Pernifloss** [comment]
Amazing, thanks !
