### ISSUE TITLE
Testing clustering

### ISSUE THREAD

**Issue by umeshshende** [AirenSoft/OvenMediaEngine#1022]
Im new to this concept.  I have followed https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering and implemented below scenario using WEBRTC

**Origin ->** wss://ovenmedia.origin.com:3334/app/stream1234?direction=send&transport=tcp
**Edge1 ->**  wss:ovenmediaedge.edge.com:3334/edge/stream1234/abr?transport=tcp

Above scenario working well and it also stream from Origin. I have some question 

1. If multiple request (500 request users) to edge machine then load will be on edge machine only or Origin + edge machine?
2. If OriginMapStore use, Do we need to update origin setting in edge server.xml when edge server increase? if that yes then what does this mean [This means that existing settings do not need to be updated when extending Origin servers and Edge servers](https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering#originmapstore)?

**Comment by umeshshende** [comment]
I got the 2 question answer and also tried https://github.com/AirenSoft/OvenMediaEngine/issues/343#issuecomment-1228059804 this help me

**Comment by umeshshende** [comment]
Also I want to know how load balancer (Azure) work in OME in below scenario 
2000 request for edge1 app  
![image](https://user-images.githubusercontent.com/18421798/218244294-281f1a55-18fc-44fb-82ba-0e40fc036360.png)

Is it automatically redirect to edge2 if edge1 unable to handle it? if yes then how edge2 will get traffic from edge1 because user requesting using edge1

**Comment by getroot** [comment]
Ask the azure load balancer for that.  In this case, typically the user is making a request to the load balancer.  And I'm sorry but please don't tag me in a technical support request.
