### ISSUE TITLE
Not able to play Live rewind in MAC systems and Ipad

### ISSUE THREAD

**Issue by kk-karankatyal10** [AirenSoft/OvenMediaEngine#1024]
We are not able to successfully play **live rewind** feature in mac systems in **safari** browser,
It is playing for starting not from live section even if stream is live, also sometimes stream got struck in safari browser.
we tried in ovenmedia player as well in video js player and akamai hls player but find issue on every platform.

Kindly suggest with solution so that we can overcome this bug.

**Comment by getroot** [comment]
If you think this is a bug, please describe the steps to reproduce this issue.
Please write the encoder you use, encoder settings, OME version, and upload OME's Server.xml file and OME's ovenmediaengine.log file.
And please let me know if the problem is not reproduced in chrome on PC but only in Safari.

**Comment by kk-karankatyal10** [comment]
We are using latest version of Ovenmedia..
Steps to reporduce:
while we are playing hls on safari it is playing from starting not from live section.
It is only occuring in Safari on mac but not in chrome.
Server.xml is as follow:
<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.ovenmediaengine.com:13478</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		

		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>1936</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>4000/udp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>

				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<LLHLS>
				
				<Port>80</Port>
				
				<TLSPort>443</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				                                <TLS>
                                        <CertPath>/MTVSSL/a1d8f365164952f1.crt</CertPath>
                                        <KeyPath>/MTVSSL/multitv.key</KeyPath>
                                        <ChainCertPath>/MTVSSL/gd_bundle-g2-g1.crt</ChainCertPath>
                                </TLS>
				
			</Host>

			

			

			
			
			
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Playlist>
								<Name>Paid</Name>
								
								<FileName>master</FileName>
								<Options>
									<WebRtcAutoAbr>false</WebRtcAutoAbr> 
								</Options>
			                                        <Rendition>
                                                                        <Name>v144</Name>
                                                                        <Video>v144</Video>
                                                                        <Audio>bypass_audio</Audio>
                                                                </Rendition>
                                                                <Rendition>
                                                                        <Name>v240</Name>
                                                                        <Video>v240</Video>
                                                                        <Audio>bypass_audio</Audio>
                                                                </Rendition>
                                                                <Rendition>
                                                                        <Name>v360</Name>
                                                                        <Video>v360</Video>
                                                                        <Audio>bypass_audio</Audio>
                                                                </Rendition>
																<Rendition>
                                                                        <Name>v480</Name>
                                                                        <Video>v480</Video>
                                                                        <Audio>bypass_audio</Audio>
                                                                </Rendition>
                                                                <Rendition>
                                                                        <Name>v720</Name>
                                                                        <Video>v720</Video>
                                                                        <Audio>bypass_audio</Audio>
                                                                </Rendition>
																<Rendition>
                                                                        <Name>v1080</Name>
                                                                        <Video>v1080</Video>
                                                                        <Audio>bypass_audio</Audio>
                                                                </Rendition>
							</Playlist>
							

							<Encodes>
								
								 <Audio>
                                                                        <Name>bypass_audio</Name>
                                                                        <Codec>aac</Codec>
                                                                        <Bitrate>128000</Bitrate>
                                                                        <Samplerate>48000</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>
                                                                <Video>
                                                                        <Name>v1080</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>1500000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1920</Width>
                                                                        <Height>1080</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
																<Video>
                                                                        <Name>v720</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>950000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
																<Video>
                                                                        <Name>v480</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>800000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>854</Width>
                                                                        <Height>480</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
                                                                <Video>
                                                                        <Name>v360</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>700000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>640</Width>
                                                                        <Height>360</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
                                                                <Video>
                                                                        <Name>v240</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>500000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>432</Width>
                                                                        <Height>243</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
                                                                <Video>
                                                                        <Name>v144</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>300000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>256</Width>
                                                                        <Height>144</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							
							<ChunkDuration>0.5</ChunkDuration>
							
							<PartHoldBack>1.5</PartHoldBack>
							<SegmentDuration>3</SegmentDuration>
							<SegmentCount>4800</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by getroot** [comment]
We need to know the requested encoder information and the ovenmediaengine.log file so we can analyze the problem. (This issue is not reproducible in my production environment, so I'm asking for more information.)

Also setting SegmentCount to 4800 will use excessive memory. Refer to the information below to turn on the DVR.
https://airensoft.gitbook.io/ovenmediaengine/streaming/low-latency-hls#live-rewind

What is the latest version of OvenMediaEngine? Is this the master branch or the 0.15.0 release? Exact version information is required.

Also, does your system have enough power to encode 7 output tracks? Does the issue reproduce when configured with only bypass audio/bypass video without using ABR?

**Comment by kk-karankatyal10** [comment]
We are using for OBS studio for streaming content using bitrate around 2 mbps and our system has enough power to encode this tracks issue is reproducible with all settings. we are using version 0.15.0

Log file is attached as follow:
[ovenmediaengine_log_20230209.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10696024/ovenmediaengine_log_20230209.txt)

**Comment by getroot** [comment]
your log say you are using OvenMediaEngine 0.14.16

**Comment by kk-karankatyal10** [comment]
ok cool, please check out and suggest on this

**Comment by getroot** [comment]
I don't know what you are asking me to check and suggest.
 
Anyway, it looks like you have another system in front of OvenMediaEngine. Is that correct? If there is such a thing, you must tell me everything.

**Comment by getroot** [comment]
Please send your OvenMediaEngine origin LLHLS URL to support@airensoft.com. That seems like the quickest way to find your problem.

**Comment by getroot** [comment]
I'm closing this issue as it has been inactive for a long time. Don't hesitate to reopen this issue if you think it needs further discussion.
