### ISSUE TITLE
Unable to fetch thumbnail via edge when there is no active viewer

### ISSUE THREAD

**Issue by Alex4386** [AirenSoft/OvenMediaEngine#1028]
**Describe the bug**
The edge server does not fetch thumbnail from origin when there is no active viewers watching the stream in OME Edge server

**Server Configuration**
* [server.xml](https://gist.github.com/Baw-Appie/0b887cf5916f9b615997660b693e34ec)

**To Reproduce**
1. Enable Thumbnail publisher on edge OME server
2. Fetch Thumbnail from Edge OME Server
3. Edge OME Server does not fetch thumbnail from origin OME Server

**Expected behavior**
Edge OME Server should fetch thumbnail from origin OME Server

**Logs**
* [log](https://gist.github.com/Alex4386/abe9448b1503a083b9370650ba8e50ec)

**Server (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS (Kernel: 5.15.0-53)
 - OvenMediaEngine Version: 0.14.18
 - Branch: master (deployed via docker-compose)

**Player (please complete the following information):**
Not Applicable.

**Comment by getroot** [comment]
This is not a bug and is intentionally not implemented.
It is common to extract thumbnails on the origin side. And to deploy this in bulk over HTTP, it's better to use an http reverse proxy like nginx or a CDN like CloudFront than using OvenMediaEngine as edge.
Of course, implementing this isn't difficult, but I didn't think there were many use cases. Please let me know if you have use cases.

**Comment by Alex4386** [comment]
Closing issue as alternative solution proposed.
