### ISSUE TITLE
ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by umeshshende** [AirenSoft/OvenMediaEngine#1029]
**PROBLEM**

Load testing using  ovenrtctester but its not connecting to server. the same url work in ovenplayer 
I was using load balancer (Azure) but using VM DNS name it work on ovenplayer.
**client_0 failed to run (reason - could not connect signaling server : wss:edgeserverurl:3334/edge/stream1234?transport=tcp (reason : tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config))**

**EXPECTATION**

Load test work

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

latest version 15.0

- Encoder information

- Player information

 ovenplayer working well issue in rtc_tester 

- URL

go run OvenRtcTester.go -life 600 -url wss:ouredgeserver:3334/edge/stream1234/abr?transport=tcp -n 200 // not working rtc tester
 file: 'wss:ouredgeserver:3334/edge/stream1234/abr?transport=tcp' // working in ovenplayer

- Operating system and version

Ubuntu 20.04

**SETUP INFORMATIO
[Server_11_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10712980/Server_11_feb_2023.txt)
[Log_11_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10712989/Log_11_feb_2023.txt)

**OTHER HELPFUL INFORMATION**
I have added loadbalancer (Azure) was testing loadbalancing 
![image](https://user-images.githubusercontent.com/18421798/218249333-43bc199e-9ab8-42a9-b197-3d12abfb1413.png)

It works in ovenplayer but failed in rtc_tester

**Comment by getroot** [comment]
Why do you use URLs like `wss:ouredgeserver:3334/edge/stream1234/abr?transport=tcp` ?

The correct HTTP URL format is `wss://ouredgeserver:3334/edge/stream1234/abr?transport=tcp`.

**Comment by umeshshende** [comment]
Thank you, wss://ouredgeserver:3334/edge/stream1234/abr?transport=tcp it was url issue
