### ISSUE TITLE
how to turn on th P2P?

### ISSUE THREAD

**Issue by oldstorm** [AirenSoft/OvenMediaEngine#103]
hello, i add the configure like this :

```
<WebRTC>
	<P2P>
		<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
	</P2P>
	<Timeout>30000</Timeout>
</WebRTC>
```

but the log still tell me P2P is disabled, please tell me how to sove this problem ? thanks 
i run the OME version is OvenMediaEngine-0.10.1

[2020-04-18 11:22:03.294] I 28598 Signalling | rtc_signalling_server.cpp:63   | P2P is disabled in the configuration

**Comment by getroot** [comment]
Oh, that is our mistake.
P2P is still an experimental feature, and we often try to update it without worrying about it. We will return the P2P function to normal as soon as possible and inform you through this thread.
Thank you!

**Comment by oldstorm** [comment]
ok, thanks!

**Comment by getroot** [comment]
I solved this problem. Please refer to the following URL. If you want to continue the discussion, please do not hesitate to reopen this issue.

https://airensoft.gitbook.io/ovenmediaengine/p2p-delivery
