### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by umeshshende** [AirenSoft/OvenMediaEngine#1031]
**PROBLEM**

Im doing performance testing but delay or packet loss is high even we have 16vcpu and 32ram on where tester running 
and edge and edge1 utlilization also normal 

**scenario below** 
**Origin**  1

**request  600**
**load balancer**
[ 

**edge**                        
**edge1**

] 

![image](https://user-images.githubusercontent.com/18421798/218972187-46ac7ca2-efdc-4bd3-9367-3f18b7d48b8b.png)

**EXPECTATION**

It should take 600 user for 1080p /bitrate 2.2mb  

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

using version 15.0

- Encoder information
ovenplayer for broadcast

- Player information

ovenplayer 

- URL
wss://originurl:3334/app/stream1234?direction=send&transport=tcp // for broadcast 
go run OvenRtcTester.go -cint 100 -life 1000 -url wss://loadbalanceurl:8888/edge/stream1234/abr?transport=tcp -n 600 // for testing

- Operating system and version
 Ubuntu 20.04
 F16s_v2                         | RTC TESTER
 Standard F4s v2 (4   vcpus, 8 GiB memory) | ORIGIN
 Standard D2s v3 (2 vcpus, 8 GiB memory) | EDGE
 Standard D2s v3 (2 vcpus, 8 GiB memory)| EDGE1

**SETUP INFORMATION AND LOGS**

[origin_log_15_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10741068/origin_log_15_feb_2023.txt)
[edge1_log_15_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10741069/edge1_log_15_feb_2023.txt)
[edge_log_15_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10741070/edge_log_15_feb_2023.txt)
[edge_config_15_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10741071/edge_config_15_feb_2023.txt)
[edge1_config_15_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10741072/edge1_config_15_feb_2023.txt)
[origin_config_15_feb_2023.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10741074/origin_config_15_feb_2023.txt)

**OTHER HELPFUL INFORMATION**
300 connection   PASSED

**<Summary>** 
Running time :                   7m20s 

Number of clients :                   300 

ICE   Connection State : New(0), Checking(0) Connected(300) Completed(0)   Disconnected(0) Failed(0) Closed(0)
Avg Video   Delay(33.57 ms) Max Video Delay(232.00 ms) Min Video Delay(0.00 ms)
Avg Audio   Delay(31.43 ms) Max Audio Delay(256.00 ms) Min Audio Delay(0.00 ms)
Avg   GOP(29.98) Max GOP(30.05) Min GOP(30)
Avg   FPS(30.00) Max FPS(30.04) Min FPS(29.99)
Avg BPS(2.2   Mbps) Max BPS(2.2 Mbps) Min BPS(2.2 Mbps)
Total   Bytes(25.1 GBytes) Avg Bytes(83.6 MBytes)
Total   Packets(27644164) Avg Packets(92147)
Total Packet   Losses(0) Avg Packet Losses(0)

![image](https://user-images.githubusercontent.com/18421798/218990687-2a397815-eac5-46b5-8012-fcf206831fa0.png)

**Comment by mpisat** [comment]
Standard D2s v3 (2 vcpus, 8 GiB memory)| EDGE1

This one has 6.x system load on the screenshot, maybe that's why? :)

**Comment by umeshshende** [comment]
@mpisat :) i dont know why this happening  @getroot do you know why this happening?

**Comment by umeshshende** [comment]
Im closing this issue i was wrongly calculated CPU % 


<Summary> 

Running time : 19m58s 

Number of clients : 600 

ICE   Connection State : New(0), Checking(0) Connected(600) Completed(0)   Disconnected(0) Failed(0) Closed(0)
Avg Video   Delay(33.74 ms) Max Video Delay(369.00 ms) Min Video Delay(0.00 ms)
Avg Audio   Delay(46.62 ms) Max Audio Delay(374.00 ms) Min Audio Delay(1.00 ms)
Avg   GOP(29.99) Max GOP(30.01) Min GOP(30)
Avg   FPS(30.00) Max FPS(30.01) Min FPS(30.00)
Avg BPS(2.2   Mbps) Max BPS(2.2 Mbps) Min BPS(2.2 Mbps)
Total   Bytes(151.1 GBytes) Avg Bytes(251.8 MBytes)
Total   Packets(167557558) Avg Packets(279262)
Total Packet   Losses(0) Avg Packet Losses(0)

I used htop for analysis Load and also upgrade size according load
![image](https://user-images.githubusercontent.com/18421798/219337425-302eb8b5-101e-45e8-bfce-f8adf9df83fd.png)

![image](https://user-images.githubusercontent.com/18421798/219337008-e36a708d-4dc8-42e9-84b7-d450305b2039.png)
