### ISSUE TITLE
Server.xml is missing when docker run 

### ISSUE THREAD

**Issue by umeshshende** [AirenSoft/OvenMediaEngine#1034]
I need to update server.xml but not able to find it I have install using docker 
docker run -d \
-p 1935:1935 -p 4000:4000/udp -p 3333:3333 -p 3334:3334 -p 3478:3478 -p 9000:9000 -p 9999:9999/udp \
airensoft/ovenmediaengine:0.15.0

# Expected

 For Origin mode
/opt/ovenmediaengine/bin/origin_conf/Server.xml
 For Edge mode
/opt/ovenmediaengine/bin/edge_conf/Server.xml

# Actual

![image](https://user-images.githubusercontent.com/18421798/220094704-33875ec4-3cca-41d4-a2ba-1ae4fbac6ee5.png)
![image](https://user-images.githubusercontent.com/18421798/220094992-b353b4fb-7327-41a3-bb90-c9ee9f3bd0d8.png)

**Comment by naanlizard** [comment]
When running in docker, iirc one of the first things it does is copy server.xml to /tmp/

**Comment by getroot** [comment]
@umeshshende Isn't the folder you're looking at the host's folder? Check inside the docker container.
