### ISSUE TITLE
/opt/ovenmediaengine/bin/origin_conf/Server.xml` and `/opt/ovenmediaengine/bin/edge_conf/Server.xml which file to edit if I want to configure Edge server?

### ISSUE THREAD

**Issue by un-hongly** [AirenSoft/OvenMediaEngine#1038]
Running media engine in docker, the configurations file is a bit confusing there are two configuration files `/opt/ovenmediaengine/bin/origin_conf/Server.xml` and `/opt/ovenmediaengine/bin/edge_conf/Server.xml`. I was trying to configure an edge server so I added `OriginMapStore` to `/opt/ovenmediaengine/bin/edge_conf/Server.xml` and expected it to work but it didn't then I tried enabling `OriginMapStore` in `/opt/ovenmediaengine/bin/origin_conf/Server.xml` and surprisingly it works.

**Comment by getroot** [comment]
With docker-compose you can easily enable edge mode.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/docker-compose.yml

If you run it with the command below, it will be executed while loading edge_conf/Server.xml.
/opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf

**Comment by un-hongly** [comment]
I see!!
I followed the instruction from DockerHub and by default it take /opt/ovenmediaengine/bin/origin_conf/Server.xml as configurations.
