### ISSUE TITLE
6 video streams?

### ISSUE THREAD

**Issue by Rajan** [AirenSoft/OvenMediaEngine#104]
Does it support 6 video streams in a few-to-many (6 to 100s) format? What percentage of the data will be relayed via P2P?

**Comment by getroot** [comment]
Currently, our P2P is an experimental feature.
As of our code, <Server>-<Master Player>-<2 Slave Players> are configured.

What exactly does "Does it support 6 video streams in a few-to-many (6 to 100s) format?" Mean? The maximum number of streams supported depends on the performance and configuration of the server. Players that can be connected at the same time also depend on network performance.

**Comment by getroot** [comment]
I solved this problem. Please refer to the following URL. If you want to re-discuss, please do not hesitate to reopen this issue.

https://airensoft.gitbook.io/ovenmediaengine/p2p-delivery
