### ISSUE TITLE
Admission Webhook returns 404

### ISSUE THREAD

**Issue by Thunder80** [AirenSoft/OvenMediaEngine#1045]
**PROBLEM**

Admission Webhooks return 404 but the endpoint works with other tools like Postman and cURL.

**EXPECTATION**

Should allow the stream to be published or subscribed.

**ENVIRONMENTAL INFORMATION**

- OME - v0.14.18 docker image and dev image.

- Encoder information -OBS latest.

- URL - rtmp://<DOMAIN>:1935/app/<KEY>?policy=eyJ1cmxfZXhwaXJlIjoxODkzNDU2MDAwMDAwfQ&signature=ismtaRL4QdLSa_s-kIlTDHV2YkI

- Operating system and version - Ubuntu 20.4

**SETUP INFORMATION AND LOGS**
I am providing the ovenmediaengine.log and Server.xml [here](https://gist.github.com/Thunder80/8acdea73bc889db94550705dbc39177c)

**OTHER HELPFUL INFORMATION**

Admission webhooks have worked for me in the past. But this time I am trying with AWS AppRunner and I am using a CNAME record to point the AWS URL to my custom domain, maybe that's causing issues?

Working curl request:
```
curl -H 'Content-Type: application/json' -d '{ "request":{"url": "rtmp://<DOMAIN>/app/<KEY>?policy=eyJ1cmxfZXhwaXJlIjoxODkzNDU2MDAwMDAwfQ&signature=9bzXfNUFgQfa9ryu7Sa9zi-aQlI"}}' -X POST https://<URL><api/utils/admission
```

**Comment by getroot** [comment]
Isn't your control server responding a 404? I guess you need to check your control server's logs to find out why it responds with a 404. Is there something OME is doing wrong with the request?

**Comment by Thunder80** [comment]
The control server responds with 404 only in OME logs. With the same URL mentioned in the OME logs if you do a cURL request it responds correctly. So I am not sure what OME is doing with the request.

**Comment by getroot** [comment]
To analyze this problem, I think the only way I can test it with your control server url. If you can provide a URL, please send it to support@airensoft.com.

**Comment by Thunder80** [comment]
Thanks, I have sent you the details. Please let me know if something else is needed.

**Comment by Thunder80** [comment]
Thanks for pointing me in the right direction. I will investigate how to get it working.
