### ISSUE TITLE
Docker closes after a few seconds of streaming

### ISSUE THREAD

**Issue by ReeceKetley** [AirenSoft/OvenMediaEngine#105]
Hi, when i start the docker i can connect via obs and stream but the second i try using the demo player and WS the docker closes and i have to start again.

**Comment by getroot** [comment]
Please upload /opt/ovenmediaengine/bin/log/OvenMediaEngine.log inside docker container.
Which Docker version are you using? Is it airensoft/ovenmediaengine: latest? Or is it airensoft/ovenmediaengine:dev?

**Comment by ReeceKetley** [comment]
I've managed to install it on a Vultr server using docker using the higest CPU/Ram i can and it seems to be using 147% of the cpu. 

> 
[2020-04-20 20:46:25.915] W 42 LLDASH | cmaf_packetizer.cpp:253  | [#default#app/stream_o] Jitter has been reduced, but playback may not be possible (2020-04-20T20:42:11.724Z => 2020-04-20T20:42:10.724Z, 0ms)
[2020-04-20 20:46:30.590] E 42 LLDASH | cmaf_packetizer.cpp:249  | [#default#app/stream_webrtc] Because the jitter is too high, playback may not be possible (2020-04-20T20:43:01.486Z => 2020-04-20T20:43:02.486Z, 52000ms)

**Comment by getroot** [comment]
please upload full log file.

**Comment by getroot** [comment]
And the Docker image we provided works fine?

https://hub.docker.com/r/airensoft/ovenmediaengine

docker run -d -p 1935:1935 -p 3333:3333 -p 80:80 -p 9000:9000/udp -p 10000-10005:10000-10005/udp airensoft/ovenmediaengine

**Comment by kennethlimcp** [comment]
```
root@ubuntu-s-1vcpu-1gb-sgp1-01:~# docker ps -a
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                        PORTS               NAMES
621d5a23cfc7        airensoft/ovenmediaengine:latest   "/opt/ovenmediaengin…"   2 hours ago         Exited (139) 20 minutes ago                       stream
```

root@ubuntu-s-1vcpu-1gb-sgp1-01:~# docker cp stream:/var/log/ovenmediaengine/ovenmediaengine.log  .

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/4515163/ovenmediaengine.log)

**Comment by getroot** [comment]
I solved this problem. Would you please try again? If the problem occurs again, please reopen this issue.
