### ISSUE TITLE
Installation is failing while "make release"

### ISSUE THREAD

**Issue by pream912** [AirenSoft/OvenMediaEngine#1054]
**Bug**
Installation is failing while "make release"

**To Reproduce**
1. (curl -LOJ https://github.com/AirenSoft/OvenMediaEngine/archive/v0.15.1.tar.gz && tar xvfz OvenMediaEngine-0.15.1.tar.gz)
OvenMediaEngine-0.15.1/misc/prerequisites.sh
2. sudo apt-get update
cd OvenMediaEngine-0.15.1/src
make release
3. [See error](make: *** [core/build_executable.mk:9: bin/RELEASE/OvenMediaEngine] Error 1)
(Same error with docker build as well)

**Expected behavior**
OvenMediaEngine start running

**Logs**
......
#11 272.0 Linking pugixml
#11 272.0 [455/461| 98%] [static] Linking libmediarouter.a... => intermediates/RELEASE/static/libmediarouter.a
#11 272.1 make[1]: Leaving directory '/tmp/ome/src/projects/third_party/pugixml-1.9/scripts'
#11 272.1 [456/461| 98%] [prebuilt] Copying prebuilt library projects/third_party/pugixml-1.9/scripts/gmake/libpugixml.a to intermediates/RELEASE/prebuilt/libpugixml.a
#11 288.7 [457/461| 99%] [static] Linking libfile_provider.a... => intermediates/RELEASE/static/libfile_provider.a
#11 290.3 [458/461| 99%] [static] Linking liborchestrator.a... => intermediates/RELEASE/static/liborchestrator.a
#11 291.1 [459/461| 99%] [static] Linking libaccess_controller.a... => intermediates/RELEASE/static/libaccess_controller.a
#11 291.3 [460/461| 99%] [executable] Linking OvenMediaEngine... => bin/RELEASE/OvenMediaEngine
#11 310.9 make: *** [core/build_executable.mk:9: bin/RELEASE/OvenMediaEngine] Bus error
------
error committing efzp7kwblrinhlg2b4npo0rhm: write /var/lib/docker/buildkit/metadata_v2.db: read-only file system

**Server:**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: 0.15.1

**Comment by getroot** [comment]
Your storage doesn't seem to be enough to compile

**Comment by pream912** [comment]
> Your storage doesn't seem to be enough to compile

Thanks for a quick reply. Let me try it with a bigger instance.

**Comment by pream912** [comment]
> Your storage doesn't seem to be enough to compile

It works now. Thank you!
