### ISSUE TITLE
Streaming cost

### ISSUE THREAD

**Issue by kennethlimcp** [AirenSoft/OvenMediaEngine#107]
Hello!

Wondering if there is a good way to understand roughly what streaming cost will look like using OvenMediaEngine. 

Will CDN integration be introduced as part of the roadmap to make things more cost effective?

eg. 5000 viewers for a 2 hour live stream. How can we go about estimating the cost?

Thanks! Good work :)

**Comment by getroot** [comment]
Configure OME as Cluster.

For 5000 viewers I think you should use 1 Origin and 4 or more Edges. Edge performance depends on the video quality, CPU, network, and memory, so the required number may vary.

If you are doing such an event with OME, I would like you to tell us your experience.

The network traffic cost would be calculated as 5000 viewers * (video bitrates + audio bitrates).

**Comment by kennethlimcp** [comment]
> Configure OME as Cluster.

The bandwidth usage will be rather high, right?

> If you are doing such an event with OME, I would like you to tell us your experience.

Happy to share but first need to understand if the cost if feasible. :D

**Comment by getroot** [comment]
Clustering is usually because one server cannot accommodate 5000 viewers. The output bandwidth is the same. Please refer to the following URL.

https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering

**Comment by kennethlimcp** [comment]
Assuming we are using DigitalOcean for cost effective bandwidth setup:

- Traffic between `Origin` and `Edge` will be through `Private Network` at no cost
- 1 x Load Balancer at `USD10/month`
- Let's say the `Live RTMP Source` is:
  - Video bitrate: 4Mbps
  - Audio bitrate: 0.128Mbps 
  - Total bitrate: ~ 4.2Mbps

> The network traffic cost would be calculated as 5000 viewers * (video bitrates + audio bitrates).

- (5000 viewers * 4.2Mbps / 8bits) * $0.10/GB
- 21,000/8 Mbps * $0.10/GB
- ~2.6 GBps * $0.10/GB
- $0.26 per second

For a 120mins stream, $0.26 * (60*60) = $936

Pretty costly

**Comment by vitragmehta** [comment]
Apologies for jumping in the conversation;
We have been running OME 0.9 since quite some time for about 1500 users and total 4 different streams on our website (we really dont know the exact user count as we dont know how to, any inputs here will surely help)

how we have achieved this is as follows:
we had our origin server and OBS (source content is from a computer screen) on AWS. OBS to Origin server in internal traffic; hence bw costs are zero.

we have set up 3 edge servers on cheap unmanaged servers (we used 1 from dedispec.com and 2 servers from wholesaleinternet.net). they are as cheap as they come with decent bandwidth and self setup.

since there were 3 edge servers (3 ips’) we used dns round robin and used one single dns name pointing to all 3 edge servers.

oven player is simply connecting to dns name for playing the stream. This has been working great for us since last few months.

total cost of 1500~2000 estimated viewers with appx 5 hours content streamed daily is less than 500 usd per month.

hope this helps; please do ping back if you need more details or assistance

-Vitrag

**Comment by kennethlimcp** [comment]
Hey @vitragmehta,

Thanks for sharing! It's great to hear that there are folks using this in production. Gives me more confidence to trial it out.

Some questions:

1. How did you estimate the number of viewers when it cannot be measured?
2. How is the streaming quality so far? Does it buffer often?
3. Have you seen seamless failover when one of the edge server goes offline?
4. Is the bulk of your infra cost coming from the monthly server cost? Seems like the dedicated server have a lot of bandwidth as you shared! (100TB)

**Comment by vitragmehta** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Hello, Happy to help as much as possibleAnswers as follows1. The users vieweing the stream ar from known references, and we do speak to them on the feedback of their experience, hence the estimated number. If there is any way to password protect the stream and also to get some analytic report, please do help share the same.2. Stream has q delay in starting playback (about 2 seconds, not accurately measured) but once the playback starts, the only reason of buffering is end users own bandwidth (yes we have mobile broswer viewers too). Regular broadband users have reported good feedback with no buffering issues.3. Unfortunately no, while we havent faced any such outage, we did to these testings for our own inquisitive bug. When the edge fails, the users connected to that edge will have to restart playback before the stream resumes. This may be resolved by doing some code changes at the player end (to kind of auto reconnect), but we are a core network onfra team and have very limited coding skills, hence left player at default settings only.4. True, bulk is from the monthly server costs, as the bandwidth they offer is 100tb per month, most ofnthe times we get 200-300mbps plus upload speeds from these servers, some times it drops to 100 mbps uploas per server. Well given the cost, we cant demand much and hence we overprovisioned our edge servers (required 2 but kept 3).                                                                                                                                             Sent from Mobile device, Please excuse brevity and typos                                                                                                                                                                           From: notifications@github.comSent: 22 April 2020 07:56To: OvenMediaEngine@noreply.github.comReply to: reply@reply.github.comCc: vitragm@gmail.com; mention@noreply.github.comSubject: Re: [AirenSoft/OvenMediaEngine] Streaming cost (#107)  
Hey @vitragmehta,
Thanks for sharing! It's great to hear that there are folks using this in production. Gives me more confidence to trial it out.
Some questions:
How did you estimate the number of viewers when it cannot be measured?How is the streaming quality so far? Does it buffer often?Have you seen seamless failover when one of the edge server goes offline?Is the bulk of your infra cost coming from the monthly server cost? Seems like the dedicated server have a lot of bandwidth as you shared! (100TB)

**Comment by getroot** [comment]
@vitragmehta Thank you for sharing your valuable experience!

Starting with version 10.1, the ability to log the total number of viewers when a viewer accesses and exits has been added. And when the stream ends, it outputs Input / Output Traffic.

We want to hear the needs of people who use it in real world like you.

Thank you.

**Comment by getroot** [comment]
@vitragmehta OME has many improvements in the latest version.

Your q dealy in starting playback is probably improved.

OME 0.10.1 has had a number of performance improvements, and a bypass profile has also been added. If you use bypass transcoding, you will be able to stream with better quality and lower resources.

WebRTC's A-V synchronization has also been improved.

Origin-Edge's structure has also changed completely. Previously, Origin and Edge were always strongly connected, but now when the user asks, edge fetches and serves only that stream from origin.

Players have also improved a lot in terms of stability, such as retry logic.

We will support you a lot if you want to use the latest version.

Thank you.

**Comment by kennethlimcp** [comment]
@getroot that's really good to hear!

Side track a little, for potential buffering issues (seen using another solution to simulcast to YouTube), is it possible to induce latency? Or does this not make sense dealing with network issue when the source is delayed?

I understand that sub-latency is a goal of this solution, hence the question.

**Comment by getroot** [comment]
When the source is delayed, there is nothing OME can do to reduce latency. So, we recommend the following options for the most used source, OBS.
https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder

Am I right to understand your question?

**Comment by kennethlimcp** [comment]
Understand that we cannot control source delay.

My question is more on whether we can delay stream (eg. 5 seconds) so that
we have some buffer in case the source is delayed.

Eg. User will see a video that is 5 seconds slower than the source.

**Comment by getroot** [comment]
Oh sorry, I misunderstood the question.

In WebRTC Streaming, it is not possible for OME to control delay.

Instead you can use a low-latency dash for it.
https://airensoft.gitbook.io/ovenmediaengine/hls-mpeg-dash

The player for low-latency DASH can control the delay as follows.
https://airensoft.gitbook.io/ovenmediaengine/test-player#delay-option-for-low-latency-dash

**Comment by kennethlimcp** [comment]
Thanks everyone! Shall close this now we have a good understanding of the rough costing.

**Comment by getroot** [comment]
We have released a tool to test OvenMediaEngine's WebRTC streaming load and performance. This is currently a very low quality code. We suggest that we all work together to improve this. We ask for help. Thank you.

https://github.com/AirenSoft/OvenWebRTCTester
