### ISSUE TITLE
want to ask something

### ISSUE THREAD

**Issue by ivashkinvonmephisto** [AirenSoft/OvenMediaEngine#108]
my log file say: "...RTMP server has started listening on 0.0.0.0:1935..." i have no idea whats wrong. Im trying to run OME on virtualbox centos 7 just because need spend more time, to learn how to run it. so everithing go well the server is active with default  server.xml   my rtmp source is wirecast. virtualbox settings are in bridge mode . my vitrual machine is with the same netmask and accessible ip

**Comment by getroot** [comment]
Sorry, I can't understand what is your problem.

**Comment by ivashkinvonmephisto** [comment]
OME is installed on a virtualbox  centos 7 (host windows 7) with a bridge network connection
My server is active, but (according my log file)   listening to 0.0.0.0:1935, not to 192.168.0.104: 1935 (as it should be). why? My IP is 192.168.0.103. Im sending to rtmp://192.168.0.104:1935     no respond and any actyvities from the input server. Cannot establish connection, at all.

**Comment by getroot** [comment]
We haven't used OME and wirecast together. Would you please upload all of OvenMediaEngine.log when you tried to connect with wirecast?

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
