### ISSUE TITLE
cmake support

### ISSUE THREAD

**Issue by xeonye** [AirenSoft/OvenMediaEngine#110]
when using  clion or other IDE , how to change the makefile to cmake? gdb debugging is poor!

**Comment by dimiden** [comment]
@xeonye 
When I was developing with CLion, I used the following config to debug it. (Now, I'm using [Visual Studio Code](https://code.visualstudio.com))

```SOURCES``` was set using ```GLOB_RECURSE``` to be able for IntelliSense feature, and ```add_custom_target()``` was added to be built through the OME build system.

Since the header location is different for each OS, please refer to it only.

```
cmake_minimum_required(VERSION 3.9)

project(OvenMediaEngine)

set(CMAKE_CXX_STANDARD 14)

add_definitions(-DDEBUG=1)

set(PROJECT_SOURCE_DIR "${PROJECT_SOURCE_DIR}/src")
set(CMAKE_CURRENT_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/src")

set(DEFAULT_INCLUDE_PATH ../includes)

include_directories(
        ${LINUX_HEADER_PATH}
        ${DEFAULT_INCLUDE_PATH}
      src/
      src/projects
        src/projects/third_party
)

file(GLOB_RECURSE SOURCES src/projects/*.cpp src/projects/*.c)

add_executable(OvenMediaEngine2 ${SOURCES})

find_package(PkgConfig REQUIRED)

set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:/usr/local/Cellar/openssl/1.0.2q/lib/pkgconfig")
pkg_check_modules(SRT REQUIRED srt)

target_include_directories(OvenMediaEngine2 PUBLIC ${SRT_INCLUDE_DIRS})

add_custom_target(OvenMediaEngine COMMAND make -C ${PROJECT_SOURCE_DIR} -j8 bin/DEBUG/OvenMediaEngine)
```

**Comment by xeonye** [comment]
great, thx!

**Comment by DarkSherlock** [comment]
> great, thx!

你好，两年前你有fork了一个我的工程，关于这个我有一个非常重要的问题想要和你沟通，但是我找不到你的联系方式，只能在这里给你发个消息不好意思，希望你看到的时候可以尽快+我QQ:627669608，先这里谢谢了，拜托
