### ISSUE TITLE
Authentification HTTPCallback? /  Edge WebRTC ? / automatic vhost ?

### ISSUE THREAD

**Issue by IIPoliII** [AirenSoft/OvenMediaEngine#111]
Hey,
I am working on OSSRS/SRS since a few days and i just saw OvenMediaEngine that looks better for my use. Now three questions.

Is it possible to do authentification. At SRS it's possible by calling a auth server that returns a reply of yes or not. Like On_Publish = test.com/auth.php. And i do it via the publish link like test.com/live/livestream?key=38128391.
If the key is right it let it enter or not.

It's the same idea for the player.

So is it possible to have authentification? (Could you provide an example for me please c: )

-----------------------------------------------------------------------------------------------
My second question is about WebRTC
Does the WebRTC flux goes through the edge server or is it possible to choose it i would love it because it will make my config way easier.

-----------------------------------------------------------------------------------------------
My third question is to know if it's possible to have automatic vhost i mean it in this way.

Someone create a stream at rtmp://ballal.com/live/livestream1 and somone else watch it at the same URL but the livestream1 was not written as existing in the vhost. Meaning that it's considered as "default vhost".

Thanks in advance for the answers and this project really looks nice !

**Comment by IIPoliII** [comment]
Also I saw about Audio Only streams that it will be supported soon I am as well really interested.
So if Auth / Audio stream only is possible here I am :P

**Comment by frhnfrq** [comment]
I want to know about authentication as well. And SRS doesn't support token authentication, it would be better if OME supported token authentication like nginx-rtmp-module does.

**Comment by getroot** [comment]
1. 
OME supports "SignedURLs"(Same as token authentication) like CloudFront. But it is still an experimental feature. It is only supported in limited environments. It will be released as a full version in 0.11.x.

2. 
What is WebRTC flux? Refer to the URL below for clustering.
https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering

3.
I think I don't fully understand the question.
Setting the VirtualHost's Domain to *, it can handle all input. 
VirtualHosts are processed in the order you set them first, so set * last.

4.
Audio Only and Video Only features will also be released in 0.11.x.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
