### ISSUE TITLE
Docker compose error

### ISSUE THREAD

**Issue by deepsurvey** [AirenSoft/OvenMediaEngine#113]
**Describe the bug**

docker-compose up -d fails out of the box. 
Before changing settings and modifying any edge.xml and origin.xml config settings, I wanted to simply run the standard YML and Dockerfile. 

**To Reproduce**

git clone https://github.com/AirenSoft/OvenMediaEngine.git
cd OvenMediaEngine
docker-compose up -d

3. See error

[144/252| 57%] [static] libtranscoder.a: C++ projects/transcode/codec/transcode_codec_dec_avc.cpp => intermediates/RELEASE/objs/transcode/codec/transcode_codec_dec_avc.o
projects/providers/rtspc/rtspc_stream.cpp: In member function 'virtual int pvd::RtspcStream::GetFileDescriptorForDetectingEvent()':
projects/providers/rtspc/rtspc_stream.cpp:333:10: error: 'av_get_iformat_file_descriptor' was not declared in this scope
   return av_get_iformat_file_descriptor(_format_context);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/providers/rtspc/rtspc_stream.o] Error 1
make: *** Waiting for unfinished jobs....
ERROR: Service 'origin' failed to build: The command '/bin/sh -c DIR=/tmp/ome5 &&         mkdir -p ${DIR} &&         cd ${DIR} &&         curl -sLf https://github.com/AirenSoft/OvenMediaEngine/archive/${OME_VERSION}.tar.gz | tar -xz --strip-components=1 &&         cd src &&         make release' returned a non-zero code: 2

**Expected behavior**
Expected docker-compose to compile a default OME

**Server (please complete the following information):**

 - OS:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

 - OvenMediaEngine Version: [e.g. v0.10.1]
 - Branch: [e.g. dev]

####################################################
#                                                  #
#           AirenSoft Make System v0.63            #
#                                                  #
####################################################
   - Operating system        : linux
   - Core count              : 8
   - GCC version             : 8.3.0
   - Build option            : RELEASE
   - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
   - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig
   - Total Projects count    : 34

**Additional context**

**Comment by getroot** [comment]
Some Dockerfiles have been fixed (changed ffmpeg). The code in the dev branch and the Dockerfile in the master branch are incompatible. Dockerfile is now built by downloading the dev branch. Would you like to use the Dockerfile of the dev branch? Or modify the Dockerfile to change the OME version to master branch.
We will fix this problem soon.

**Comment by getroot** [comment]
I solved this problem. Would you please try again?

**Comment by deepsurvey** [comment]
Hi,

I solved the problem by means of checking out the dev branch. I still am a bit of a noob, so initially I did not know how to switch to the dev branch.

git clone -b dev https://github.com/AirenSoft/OvenMediaEngine.git

Once I figured that out and docker-compose worked without errors. Getting a 2 computer Origin-Edge cluster working was a walk in the park.

For all who are interested, it is realy easy. I simply cut the whole origin section out the docker-compose.yml; changed the DEFAULT_ORIGIN_SERVER ip address to my origin server and set the command to run OME as Edge:

version: '3.7'

services:
  edge:
    build:
      context: .
    image: airensoft/ovenmediaengine:latest
    ports:
    - "3333:3333/tcp"
    - "80:80/tcp"
    - "10000-10005:10000-10005/udp"
    environment:
    - DEFAULT_ORIGIN_SERVER=172.26.134.111
    - OME_HLS_STREAM_PORT=80
    - OME_DASH_STREAM_PORT=80
    - OME_SIGNALLING_PORT=3333
    - OME_ICE_CANDIDATES=*:10000-10005/udp
    - SIGNED_URL_CRYPTO_KEY=
    - SIGNED_URL_QUERY_KEY=
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf

At the Origin I have the following docker compose:
version: '3.7'

services:
  origin:
    build:
      context: .
    image: airensoft/ovenmediaengine:latest
    ports:
      - "1935:1935/tcp"
      - "3333:3333/tcp"
      - "9080:8080/tcp"
      - "9000:9000/tcp"
      - "10006-10010:10006-10010/udp"
    environment:
      - OME_ORIGIN_PORT=9000
      - OME_HLS_STREAM_PORT=8080
      - OME_DASH_STREAM_PORT=8080
      - OME_SIGNALLING_PORT=3333
      - OME_ICE_CANDIDATES=*:10006-10010/udp
      - OME_VIDEO_WIDTH=640
      - OME_VIDEO_HEIGHT=360
      - OME_VIDEO_BITRATE=500000
      - OME_VIDEO_FRAMERATE=30
      - OME_AUDIO_BITRATE=128000
      - OME_AUDIO_SAMPLERATE=48000
      - OME_AUDIO_CHANNEL=2
    command: /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf

simply start both OME's with: docker-compose up -d
and set your filewall settings to allow the used TCP and UDP ports.

**Comment by getroot** [comment]
Thank you for sharing your experience.
