### ISSUE TITLE
0.15.4 API reports framerate of 0 with SRT provider

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1139]
**Describe the bug**
I noticed that when using an SRT provider, 0.15.4 API reports a **0.0** value for the framerate. Could this be a regression due to the recent changes in framerate calculations?

**To Reproduce**
With example app 'live' and stream 'helloWorld', GET API /v1/vhosts/default/apps/live/streams/helloWorld.

On 0.15.3 the response includes the correct framerate:

```
{"bitrate":"4049994","bypass":false,"codec":"H264","framerate":30.016481399536133,"height":1080,"width":1920}}
```

On 0.15.4 the framerate shows as 0.0:

```
{"bitrate":"4054885","bypass":false,"codec":"H264","framerate":0.0,"height":1080,"width":1920}}
```

**Additional context**

Interestingly, the issue does not occur with RTMP provider. Also, if you use RTMP provider then change to SRT provider sometimes it comes back with the correct framerate. Is this something you are able to reproduce? I hope there are enough clues here, thank you!

**Comment by Keukhan** [comment]
Thank you for the report.

As you said, it was a regression that occurred while improving the framerate handling.

v0.15.5 has been released, which fixed that issue.

Thanks.

**Comment by bchah** [comment]
Thank you @Keukhan for the prompt resolution!
