### ISSUE TITLE
RTSP-Pull not working with Panasonic surveillance camera

### ISSUE THREAD

**Issue by jonas-resch** [AirenSoft/OvenMediaEngine#1143]
Hi,

when configuring OME to use RTSP-Pull as the input, providing the RTSP stream of a Panasonic surveillance camera doesn't work. The RTSP SETUP request fails with a 400 (Bad Request) due to an empty session header.
I already did a bit of debugging (see "Additional context" section). But I'm not able to fix the issue by myself.

I can provide the public RTSP url of the camera, please let me know to which email I should send it to.

Regards
Jonas

**To Reproduce**
1. Install OME with Docker (airensoft/ovenmediaengine:dev image)
2. [Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/11016470/Server.txt)
 (I'll provide the RTSP url via mail, please let me know where I should send it to)
3. Access the stream via demo.ovenplayer.com: wss://OME-URL/live/stream

**Expected behavior**
The stream of the camera shows

**Logs**
[_ovenmediaengine_logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/11016442/_ovenmediaengine_logs.txt)

**Server (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - OvenMediaEngine Version: 0.15.5, using Docker
 - Branch: dev, image airensoft/ovenmediaengine:dev

The issue also appears when compiling OME from source and installing it on a fresh Ubuntu Server 22.04.

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox
 - Version: 111.0

**Additional context**
The issue lies in [rtspc_stream.cpp](https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/providers/rtspc/rtspc_stream.cpp#L418) on line 418. An empty session header gets sent with the setup request which causes the camera to respond with a 400 Bad Request.
I compiled OME from source and added an if around the line but it causes another error to appear which I don't know how to fix ("Could not find track info for track ID" in [rtp_rtcp.cpp](https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/modules/rtp_rtcp/rtp_rtcp.cpp#L334)).

**Comment by getroot** [comment]
If the value of the Session header is empty, the camera seems to respond with a 400 error. Could you patch the code below and test it?

```
diff --git a/src/projects/providers/rtspc/rtspc_stream.cpp b/src/projects/providers/rtspc/rtspc_stream.cpp
index 4e5f6717..432605f9 100644
--- a/src/projects/providers/rtspc/rtspc_stream.cpp
+++ b/src/projects/providers/rtspc/rtspc_stream.cpp
@@ -328,7 +328,7 @@ namespace pvd
                auto session_field = reply->GetHeaderFieldAs<RtspHeaderSessionField>(RtspHeaderField::FieldTypeToString(RtspHeaderFieldType::Session));
                if (session_field == nullptr)
                {
-                       _rtsp_session_id = 0;
+                       _rtsp_session_id = "";
                }
                else
                {
@@ -414,8 +414,10 @@ namespace pvd
                        // The chennel id can be used for demuxing, but since it is already demuxing in a different way, it is not saved.
                        setup->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Transport,
                                                                                                                                        ov::String::FormatString("RTP/AVP/TCP;unicast;interleaved=%d-%d;ssrc=%X", interleaved_channel, interleaved_channel + 1, ov::Random::GenerateUInt32())));
-
-                       setup->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Session, _rtsp_session_id));
+                       if (_rtsp_session_id.IsEmpty() == false)
+                       {
+                               setup->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Session, _rtsp_session_id));
+                       }
                        setup->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::UserAgent, RTSP_USER_AGENT_NAME));
 
                        if (SendRequestMessage(setup) == false)
@@ -447,7 +449,7 @@ namespace pvd
                        auto session_field = reply->GetHeaderFieldAs<RtspHeaderSessionField>(RtspHeaderField::FieldTypeToString(RtspHeaderFieldType::Session));
                        if (session_field == nullptr)
                        {
-                               _rtsp_session_id = 0;
+                               _rtsp_session_id = "";
                        }
                        else
                        {
@@ -605,7 +607,11 @@ namespace pvd
 
                        play->AddHeaderField(_authorization_field);
                }
-               play->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Session, _rtsp_session_id));
+
+               if (_rtsp_session_id.IsEmpty() == false)
+               {
+                       play->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Session, _rtsp_session_id));
+               }
                play->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::UserAgent, RTSP_USER_AGENT_NAME));
 
                if (SendRequestMessage(play) == false)
@@ -658,7 +664,11 @@ namespace pvd
 
                        teardown->AddHeaderField(_authorization_field);
                }
-               teardown->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Session, _rtsp_session_id));
+
+               if (_rtsp_session_id.IsEmpty() == false)
+               {
+                       teardown->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::Session, _rtsp_session_id));
+               }
                teardown->AddHeaderField(std::make_shared<RtspHeaderField>(RtspHeaderFieldType::UserAgent, RTSP_USER_AGENT_NAME));
 
                if (SendRequestMessage(teardown) == false)
```

**Comment by getroot** [comment]
If it still doesn't work, please send the RTSP URL to support@airensoft.com. I'm busy these days, so it may take some time, but I'll analyze it. thank you

**Comment by jonas-resch** [comment]
Thank you for the quick reply. I tested the above code changes. The SETUP request now works but there is another error:
``rtp_rtcp.cpp:334  | Could not find track info for track ID 20``

Log file: [ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/11020985/ovenmediaengine.log)

I also sent the rtsp url to the email above.

**Comment by getroot** [comment]
I have committed patches to be able to ingest RTSP streams from Panasonic surveillance cameras.
You can test this with the master branch. thank you

**Comment by jonas-resch** [comment]
Works perfectly. Thank you for fixing it so quickly!
