### ISSUE TITLE
Unable to install OME version 1.10.2

### ISSUE THREAD

**Issue by swedishdeveloper** [AirenSoft/OvenMediaEngine#115]
Unable to install the latest version 1.10.2 of OME, because it fails in middle of the command "**make release**".

I get this error code: 
**projects/providers/rtspc/rtspc_stream.cpp: In member function ‘virtual int pvd::RtspcStream::GetFileDescriptorForDetectingEvent()’:
projects/providers/rtspc/rtspc_stream.cpp:334:10: error: ‘av_get_iformat_file_descriptor’ was not declared in this scope
   return av_get_iformat_file_descriptor(_format_context);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/providers/rtspc/rtspc_stream.o] Error 1**

**To Reproduce**
1. Follow the installation guide at https://airensoft.gitbook.io/ovenmediaengine/getting-started
2. When you come to down to type "make release" you will get the error when the script is near complete.

**Expected behavior**
It should not fail in the middle of the installation.

**Server (please complete the following information):**
 - OS: [Centos 7]
 - OvenMediaEngine Version: [v0.10.2]
 - Branch: [Master]

Do you not provide any better and simplier way to update OME from e.g 1.10.1 to 1.10.2 or to you need to delete all "OME" files before you can install the new version, do you not have any "UPDATE" command?

Another TIP:
You are using old version of e.g. SRT in the prerequisites file. The libraries have release much newer versions and I think It can make OME more stable?

**Comment by swedishdeveloper** [comment]
I fixed the problem of deleting all "OME related files" and then I ran the installation script again. Then it worked fine.

**Comment by getroot** [comment]
Yes, Some external libraries have been changed and added, so you have to run prerequisites.sh again.

refer this, https://github.com/AirenSoft/OvenMediaEngine/releases
