### ISSUE TITLE
Is there any admin panel 

### ISSUE THREAD

**Issue by Mohammedalasaad** [AirenSoft/OvenMediaEngine#116]
Hi,
Is there any admin panel we can access it? how if we use docker. ? I test it using all ports and It does not work.. 1935 .. 8080.. etc
Is there any API as well ?

Thanks

**Comment by getroot** [comment]
OME does not yet provide an admin panel.
If the port is not open, the firewall is most likely the cause. See https://airensoft.gitbook.io/ovenmediaengine/getting-started.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
