### ISSUE TITLE
OME soft locking after some time

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1166]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1160

<div type='discussions-op-text'>

<sup>Originally posted by **naanlizard** March 30, 2023</sup>
I'm not 100% sure this isn't our stream forwarding method from nginx-rtmp to OME, but I am pretty confident it is OME because when it happens, if I restart our forwarder, it doesn't fix it, but restarting OME does fix it.

Essentially, this screenshot shows the problem, but I'm not sure if it is cause or effect. CPU usage drops to almost nothing, nobody can play streams, no crash dump is created.

<img width="709" alt="Screenshot 2023-03-30 at 8 31 23 AM" src="https://user-images.githubusercontent.com/7061721/228762409-ee25eb88-bdd6-444d-9b8e-9397dbcf960b.png">

CPU usage doesn't match inside/outside the docker either. When I run `docker exec omedocker ps aux` I get 223% CPU, but `docker stats` reports .33%

Those examples were from a time this happened on the 26th of March. Today it happened again just now, hence the discussion.

Here is the relevant info

[Server.xml](https://gist.github.com/naanlizard/8b5745c02dc82cb2f21ae6b1e3512ef0)

[Dockerfile](https://gist.github.com/naanlizard/821de93ba7653aad981f7d83080aa6cf)

[Logger.xml](https://gist.github.com/naanlizard/d16ded99ed1d2fd2769428d211f88cce)

[EdgeConfig.xml](https://gist.github.com/naanlizard/b61020b7397202ecf8dc1addd596429d)

[Logs from today](https://gist.github.com/naanlizard/cb19bb1c4794b0335d033f06f2862543) - crash happened around 05:3X in the timestamps there. - 05:33:45 on my grafana instance, but I'm unsure how accurate that is</div>

**Comment by getroot** [comment]
https://github.com/AirenSoft/OvenMediaEngine/commit/02876e43c137b75b57aee81cfa6be6b011def27c has been committed to fix this bug, currently in testing

**Comment by naanlizard** [comment]
So far, no crashes. But they were never very frequent, so we will have to wait several weeks I think to be sure

**Comment by naanlizard** [comment]
Bad news, we had a similar event recently even with the updated code. 

The soft lock was at approximately 2:59 in the log timestamps

https://gist.github.com/naanlizard/8f997c7de0fcb62b21bf7afe30231051

**Comment by getroot** [comment]
thank you I'll take a closer look at this.

**Comment by naanlizard** [comment]
[crash_20230403.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/11235271/crash_20230403.dump.txt)
[crash_20230410.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/11235272/crash_20230410.dump.txt)

Some crash dumps I found which I think relate to previous instances of this problem. They were in /opt/ovenmediaengine/bin/dumps - I didn't realize dumps had a subfolder now

**Comment by naanlizard** [comment]
Another log from another crash

https://gist.github.com/naanlizard/7d159d31c475f67e3322782d3eb096a8

This *may* be related to the new ssl cert reload api call, which we are now using, but I'm skeptical (as we had this problem before ever using that api call of course). Just reporting everything I can think of. We have stopped our cron script that reloaded the ssl cert periodically, just in case.

**Comment by naanlizard** [comment]
Should we update to the latest master? We can run that while you investigate further

Also I hope you had a good time in Vegas :)

**Comment by getroot** [comment]
Yes, it will be of great help in resolving this issue if you return the latest master branch while I do further analysis. I just added a log for debugging as well.
I look forward to seeing you in person at NAB next year. :)

**Comment by naanlizard** [comment]
Unfortunately, another soft lock after updating.

Logs included around the event, here https://gist.github.com/naanlizard/6f6321d942692556e6422cb0f02ca03c

<img width="713" alt="Screenshot 2023-04-25 at 11 04 13 PM" src="https://user-images.githubusercontent.com/7061721/234414566-06a62a8d-2466-48e6-bcc2-7faaeccbaeea.png">

**Comment by getroot** [comment]
@naanlizard 
It's very likely that I finally solved this problem by taking great hints from the logs you provided recently. I would like to ask you to test with the last master branch. 
Thanks a lot for your contributions as always.

**Comment by naanlizard** [comment]
It happened again while I was sleeping :( No log file this time unfortunately.

I've deployed the update, fingers crossed!

**Comment by naanlizard** [comment]
So far, no more crashes, maybe we can close this. I'll reopen if it happens again

**Comment by getroot** [comment]
Thank you!

**Comment by naanlizard** [comment]
I am sorry to have to reopen this :(

Log file  https://gist.github.com/naanlizard/bf9e0c4c673830094ef8adf8ad023c34

https://i.imgur.com/gtzbryG.png

We added another application "nodvr" which may explain the weird memory usage.

Anything else we can offer to help?

**Comment by getroot** [comment]
Deadlocks are no longer observed in logs. What problem are you having specifically? If you are having problems please create a new issue.

**Comment by naanlizard** [comment]
It was the same symptoms as the previous times - WebRTC and llhls could not connect. We are now proxying through an nginx instance as well, for caching, but I don't think that would be the source of the problem

Approximately 01:20:00 in this log file https://gist.github.com/naanlizard/d9469fd4f5ef707c91e942cdafdb0ed3

**Comment by getroot** [comment]
Throughout the log, including around 1:20, I don't see any deadlock symptoms like before. Rather, I observe a lot of 404 responses in logs. Note that in a deadlock situation like before, OME will not even send a 404 response. The reason it responds with a 404 error is because the player is requesting to play a stream that has already been deleted.
Please let me know if there is anything else I didn't catch.

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/236377886-f1d6e5de-fc20-4f0d-ab88-ddff55b364f8.png)
Even after 1:20, new connections continued to occur.

**Comment by naanlizard** [comment]
I should have said approximately that timestamp, apologies. Check ten minutes after, that should be firmly within the broken time.

It's possible it was only one of the applications too - I was only able to test the regular (live) application, not the nodvr application.

It's possible it's a new problem, if it happens again I will investigate more thoroughly

**Comment by naanlizard** [comment]
This happened again - the exact same symptoms as the first time this happened, I can open a new ticket if you prefer but I think this is the same sort of problem

At a little bit after 05:00:00 in the logs here https://gist.githubusercontent.com/naanlizard/6cfa3ceca4ffdd7721ce8e30bacc85b6/raw/1dfb37711ac001dcdf0fdc74ba02317601722d24/may15clean.log OME stops accepting new inputs (rtmp directly to the server), and stops serving any streams (presumably because they are disconnected).

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/f42bd6bc-c2cd-40fa-8787-20478ee77063)

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/e31b943a-8fd7-4113-8223-16323055e15f)

I checked and there are no dump files in OME's docker

If this isn't enough info to find the bug, please tell me what you need for the next time this happens, and I will get it.

**Comment by getroot** [comment]
This is a different issue. Checking the log, the cause is the live/73966 stream, which is trying to create a whopping 28775 second segment. This means that the keyframe has never come before. (A bug in the encoder? Or a deliberate attack? Or a mistake?) I couldn't handle an exception in this situation either.

Please create a new issue and I will analyze and resolve it.

```
[37m[2023-05-15 05:04:22.192] I [SPRTMP-t1951:30] RTMPProvider | rtmp_provider.cpp:216  | The RTMP client has disconnected: [#default#live/73966], remote: <ClientSocket: 0x7f94a6399810, #239, Disconnected, TCP, Nonblocking, x.x.x.x:5274>[0m
[33m[2023-05-15 05:04:22.193] W [AW-LLHLS6:85] FMP4 Packager | fmp4_storage.cpp:307  | LLHLS stream(#default#live/73966_audio) is creating segments that are too large(28775789.000000 ms). It seems that the keyframe interval is longer than the configured segment size.[0m
[37m[2023-05-15 05:04:22.193] I [SPRTMP-t1951:30] Provider | stream.cpp:63   | #default#live/73966(1602) has been stopped playing stream[0m
[37m[2023-05-15 05:04:22.193] I [SPRTMP-t1951:30] MediaRouter | mediarouter_application.cpp:472  | [#default#live/73966(1602)] Trying to delete a stream[0m
[37m[2023-05-15 05:04:22.193] I [SPRTMP-t1951:30] Monitor | application_metrics.cpp:69   | Delete StreamMetrics(73966/06fba6ba-54a0-468e-87ee-ac48c94b0c09/default/#default#live/73966/i) for monitoring[0m
[33m[2023-05-15 05:04:22.193] W [AW-LLHLS10:89] FMP4 Packager | fmp4_storage.cpp:307  | LLHLS stream(#default#live/73966) is creating segments that are too large(28775789.000000 ms). It seems that the keyframe interval is longer than the configured segment size.[0m
[37m[2023-05-15 05:04:22.193] I [SPRTMP-t1951:30] Monitor | stream_metrics.cpp:31   | 
[Stream Info]
id(1602), msid(0), output(73966), SourceType(Rtmp), RepresentationType(Source), Created Time (Sun May 14 21:03:50 2023) UUID(06fba6ba-54a0-468e-87ee-ac48c94b0c09/default/#default#live/73966/i)

	Video Track #0: Public Name(Video_0) Variant Name(Video) Bitrate(4.00Mb) Codec(1,H264,Auto) BSF(H264_AVCC) Resolution(1280x720) Framerate(30.00fps) KeyInterval(61) BFrames(0) timebase(1/1000)
	Audio Track #1: Public Name(Audio_1) Variant Name(Audio) Bitrate(128.00Kb) Codec(6,AAC,Auto) BSF(AAC_RAW) Samplerate(44.1K) Format(fltp, 32) Channel(mono, 1) timebase(1/1000)
	Data  Track #2: Public Name(Data_2) Variant Name(Data) Codec(0,Unknown,Auto) BSF(ID3v2) timebase(1/1000)

	>> Statistics
	Last update time : Mon May 15 05:04:22 2023, Last sent time : Sun May 14 22:35:04 2023
	Bytes in : 9.49MB, Bytes out : 5.42MB, Concurrent connections : 0, Max connections : 1 (Sun May 14 21:03:57 2023)

		>>>> By publisher
		- Unknown : Bytes out(0B) Concurrent Connections (0)
		- WebRTC : Bytes out(0B) Concurrent Connections (0)
		- MPEGTSPush : Bytes out(0B) Concurrent Connections (0)
		- RTMPPush : Bytes out(0B) Concurrent Connections (0)
		- HLS : Bytes out(0B) Concurrent Connections (0)
		- DASH : Bytes out(0B) Concurrent Connections (0)
		- LLDASH : Bytes out(0B) Concurrent Connections (0)
		- LLHLS : Bytes out(5.42MB) Concurrent Connections (0)
		- OVT : Bytes out(0B) Concurrent Connections (0)
		- File : Bytes out(0B) Concurrent Connections (0)
		- Thumbnail : Bytes out(0B) Concurrent Connections (0)
[0m
[37m[2023-05-15 05:04:22.194] I [AW-LLHLS10:89] FMP4 Packager | fmp4_storage.cpp:173  | Try to create directory for LLHLS DVR: /tmp/ome_dvr//#default#live/73966/1[0m
[37m[2023-05-15 05:04:22.194] I [AW-LLHLS6:85] FMP4 Packager | fmp4_storage.cpp:173  | Try to create directory for LLHLS DVR: /tmp/ome_dvr//#default#live/73966_audio/4[0m
[33m[2023-05-15 05:04:22.194] W [SPRTMP-t1951:30] FFmpeg | third_parties.cpp:115  | [AVCodecContext: 0x7f94ef43b400] 1 frames left in the queue on closing[0m
[33m[2023-05-15 05:04:22.194] W [Decaac:230386] Transcoder | transcoder_filter.cpp:104  | Timestamp has changed abnormally.  57097 -> 28829447[0m
[33m[2023-05-15 05:04:22.194] W [AW-LLHLS10:89] FMP4 Packager | fmp4_storage.cpp:307  | LLHLS stream(#default#live/73966) is creating segments that are too large(967.000000 ms). It seems that the keyframe interval is longer than the configured segment size.[0m
[33m[2023-05-15 05:04:22.194] W [AW-LLHLS6:85] FMP4 Packager | fmp4_storage.cpp:307  | LLHLS stream(#default#live/73966_audio) is creating segments that are too large(967.000000 ms). It seems that the keyframe interval is longer than the configured segment size.[0m
```
