### ISSUE TITLE
Is it possible to receive webrtc stream as input

### ISSUE THREAD

**Issue by mightZhong** [AirenSoft/OvenMediaEngine#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by getroot** [comment]
OME doesn't support WebRTC input yet. We will develop that feature in the future.

**Comment by mightZhong** [comment]
thanks，I am looking forward to this feature

**Comment by getroot** [comment]
Can you tell me how to use this feature? If it is a feature that many people need, we can prioritize it.

**Comment by swedishdeveloper** [comment]
It sounds like a very good improvement. It should work as when you using webrtc to play the stream and you should be able to also push from e.g. android via webrtc to the server. It should make the latency much lower.

**Comment by mpisat** [comment]
@getroot 
> Can you tell me how to use this feature? If it is a feature that many people need, we can prioritize it.

It may be possible to allow people to send WebRTC broadcast from their browser to OME and then the others can watch the stream via WebRTC / HLS / Dash etc. Like, you can create a mini page similar to zoom where 3-4 people can make a conference call using only browsers.

**Comment by getroot** [comment]
Yes, I agree that there is such utility.
We are interested in this feature. We plan to support this once the highest priority task is completed.
Thank you.

**Comment by getroot** [comment]
This is being developed in #29
