### ISSUE TITLE
RTMPPush, Recording does not work after update

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#1177]
**Describe the bug**
After updating from my more-av-opts #782 branch to upstream master, RTMPPush and Recording do not work.

**To Reproduce**
1. Begin with Debian Proxmox container with working build and config from #782
2. Delete my custom branch
3. Clone from https://github.com/AirenSoft/OvenMediaEngine
4. Run `misc/prerequisites.sh --enable-nvc`
5. Make and install, restart ovenmediaengine.service
6. Stream from OBS with SRT (6 audio tracks if that makes a difference)
7. Observe error spam in console and non-functioning RTMPPush & Recording

**Expected behavior**
RTMPPush publishes a stream to twitch/youtube, file recording records a file.

**Logs**
[Server.xml.log](https://github.com/AirenSoft/OvenMediaEngine/files/11174943/Server.xml.log)
[ovenmediaengine.log.zip](https://github.com/AirenSoft/OvenMediaEngine/files/11174921/ovenmediaengine.log.zip)

**Server (please complete the following information):**
 - OS: Debian 11
 - OvenMediaEngine Version: 53312d3ed8200ae9ef9f259b3dadf4cb9f9f9f52

**Additional context**
I am hoping that this is a simple setup/configuration issue because it only seems to be happening to me.  I waited for a couple weeks to see if updates would resolve the issue but it has not.  Whatever is happening is beyond my understanding so I need help to get it running.
- Starting recording does create the `tmp_6XANPYjmIZeVtbnsC2icpwMu9yTo4la7` video file, but it only contains a single video frame.
- WebRTC and LLHLS do work.
- The journal is overflowing with errors like these if it helps you know what the issue is from a glance:

```
Mar 16 19:27:31 ovenmediaengine OvenMediaEngine[240]: [2023-03-16 19:27:31.007] E [Dech264NV:462] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7fcebc609400] non-existing PPS 0 referenced
Mar 16 19:27:31 ovenmediaengine OvenMediaEngine[240]: [2023-03-16 19:27:31.050] E [AW-HLS2:430] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7fcea8a01000] pts (184320) < dts (185820) in stream 1
Mar 16 19:27:31 ovenmediaengine OvenMediaEngine[240]: [2023-03-16 19:27:31.050] E [AW-HLS2:430] Writer | writer.cpp:721  | [0x7fcebaeb3430] Could not write the frame: Invalid argument
```

**Comment by getroot** [comment]
I haven't analyzed this in detail yet, but I suspect something.

Could you try putting `<KeyFrameInterval>60</KeyFrameInterval>` or `<KeyFrameInterval>120</KeyFrameInterval>` in your `<Encodes><Video>` settings?

And is OBS's Keyframe Interval set to 1 or 2?

**Comment by getroot** [comment]
One more thing I suspect is that you are sending HEVC to SRT.

Recording HEVC is not yet supported and RTMP transport is not supported at the protocol level. What tracks are you trying to record and retransmit?

But one strange thing is that stream ${OriginStreamName}_1440p60 and ${OriginStreamName}_1080p60 are not created. This may be a bug related to Keyframe Interval.

**Comment by getroot** [comment]
And I found something I didn't understand in the logs.

```
Video Track #0: Public Name(Video_256) Variant Name(video_0) Bitrate(185.02Mb) Codec(2,H265,Passthrough) BSF(H265_ANNEXB) Resolution(2560x1440) Framerate(133.33fps) KeyInterval(60) BFrames(0) timebase (1/90000)
```

185Mbps / about 120fps / GOP(60) about 0.5 seconds is what you intended? Or is this a bug in OME?

**Comment by krakow10** [comment]
> Could you try putting `<KeyFrameInterval>60</KeyFrameInterval>` or `<KeyFrameInterval>120</KeyFrameInterval>` in your `<Encodes><Video>` settings?

I will try this when I end my stream.

> One more thing I suspect is that you are sending HEVC to SRT.

Correct, but the same thing was happening on March 16th streaming in H.264.  I was excited by the HEVC commits I saw you making and wanted to try it out to see if it would change anything.

> 185Mbps / about 120fps / GOP(60) about 0.5 seconds is what you intended?

Yes!  I play a fast paced game so I like to record at 120fps, and 1440p is my screen resolution.  To make a near-perfect quality transmission to OME I use an extremely high bitrate which goes directly to the recording to be offline transcoded later.  GOP can be changed if this is a problem.

**Comment by getroot** [comment]
I was surprised at the video bitrate of around 200Mbps. Can you actually feel the difference with 60Mbps? And is OME handling it well? (I'm very curious as I have no experience with it.)

HEVC is still under development, so please test it later.

And your logs show that stream ${OriginStreamName}_1440p60 and ${OriginStreamName}_1080p60 are not created (probably the cause of this problem) and stream ${OriginStreamName} is passthrough so only H.265 exists in the stream. Weird that this worked with the WebRTC publisher and the LLHLS publisher. They don't handle H.265 yet.

Which stream do you use for playback, and which stream do you record and push?

Could you elaborate a bit more on your reproduction path so that we can find the problem faster?

**Comment by krakow10** [comment]
> I was surprised at the video bitrate of around 200Mbps. Can you actually feel the difference with 60Mbps? And is OME handling it well? (I'm very curious as I have no experience with it.)

I can see encoding artifacts at around 60mbps, but it's probably not too useful beyond 120mbps.  The purpose is to create an "original quality" stream recording to be transcoded into AV1 later for permanent storage.

> And your logs show that stream ${OriginStreamName}_1440p60 and ${OriginStreamName}_1080p60 are not created

These log files should only try to create a 1440p60 OutputProfile under the "youtube" Application.  I did attempt to stream to YouTube in this log, "rtmp://a.rtmp.youtube.com/live2/" shows up 10 times assuming I uploaded the correct file.  I am now streaming to twitch using OBS's built-in streaming functionality which includes support for twitch vod audio tracks.

> Which stream do you use for playback, and which stream do you record and push?

When I tested WebRTC and LLHLS today I was streaming to the "youtube" application and using the 1440p60 OutputProfile which is in H.264.  Indeed, LLHLS did not fully work with HEVC (it showed up in MPV as 7 audio tracks), but the 1440p60 H.264 transcoded OutputProfile did work.  I am trying to push 1440p60 to YouTube and use the bypass stream for recording.

> Could you elaborate a bit more on your reproduction path so that we can find the problem faster?

Is it possible that cloning new code and rebuilding prerequisites and installing OME over and over (for a year) could leave lingering files which cause these issues?  I wrote in step 1 because I wasn't sure if it was relevant.  I can't think of the reason why I don't see anyone else with this issue.  Here is some log files from #782 when I tested this with H.264 on Mar 16th:
[Server.xml](https://github.com/AirenSoft/OvenMediaEngine/files/10995051/Server.xml.log)
`sudo journalctl -u ovenmediaengine.service --no-tail > OMEJournal.log`
[OMEJournal.log.zip](https://github.com/AirenSoft/OvenMediaEngine/files/10995047/OMEJournal.log.zip)

**Comment by krakow10** [comment]
Note that the `pts (184320) < dts (185820) in stream 1` and `Could not write the frame: Invalid argument` errors that appear in `sudo journalctl -fu ovenmediaengine.service` start spamming immediately after I start the stream ingest, before any playback, recording, or RTMPPush is attempted.

**Comment by Keukhan** [comment]
First, let's solve the proIf you are transmitting at SRT + H.264 40Mbps, and do not record or Rtmp Push, does the log below occur?

pts (184320) < dts (185820) in stream 1 and Could not write the frame: Invalid argumentblems one by one.

**Comment by krakow10** [comment]
> First, let's solve the problems one by one. If you are transmitting at SRT + H.264 40Mbps, and do not record or Rtmp Push, does the log below occur?
> 
> pts (184320) < dts (185820) in stream 1 and Could not write the frame: Invalid argument
> 
> What application are you sending it to? Please tell me the input streaming address.

Streaming to the "youtube" Application with this URL `srt://10.0.0.8:9999?streamid=srt%3A%2F%2F10.0.0.8%3A9999%2Fyoutube%2Fquat&latency=20000`
using these OBS settings:
![Screenshot_2023-04-07_00-06-58](https://user-images.githubusercontent.com/3529698/230559840-f949e3ec-7657-44c6-b2f8-7a2aa629b1d1.png)
Does indeed reproduce the log errors for me:
```
Apr 07 07:04:42 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:42.985] E [AW-HLS3:462] Writer | writer.cpp:734  | [0x7f79532ea430] Could not write the frame: Invalid argument
Apr 07 07:04:42 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:42.985] E [AW-HLS2:461] Writer | writer.cpp:734  | [0x7f770ae8f430] Could not write the frame: Invalid argument
Apr 07 07:04:42 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:42.985] E [AW-HLS3:462] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f78d0000000] pts (1554750) < dts (1556250) in stream 0
Apr 07 07:04:42 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:42.985] E [AW-HLS3:462] Writer | writer.cpp:734  | [0x7f79532ea430] Could not write the frame: Invalid argument
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.006] E [AW-HLS2:461] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f769f96f000] pts (1553280) < dts (1554780) in stream 1
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.006] E [AW-HLS3:462] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f78d0000000] pts (1553280) < dts (1554780) in stream 1
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.006] E [AW-HLS2:461] Writer | writer.cpp:734  | [0x7f770ae8f430] Could not write the frame: Invalid argument
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.006] E [AW-HLS3:462] Writer | writer.cpp:734  | [0x7f79532ea430] Could not write the frame: Invalid argument
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.007] E [AW-HLS3:462] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f78d0000000] pts (1557000) < dts (1558500) in stream 0
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.007] E [AW-HLS3:462] Writer | writer.cpp:734  | [0x7f79532ea430] Could not write the frame: Invalid argument
Apr 07 07:04:43 ovenmediaengine OvenMediaEngine[206]: [2023-04-07 07:04:43.019] W [SPSRT-s9999:301] Socket | socket.cpp:764  | [#1040533630] [0x7f79954d3210] Could not get option: 4 (result: -1)
```

**Comment by Keukhan** [comment]
Let's solve this problem first. I will try to reproduce it and give you a reply. Please wait a moment.

**Comment by Keukhan** [comment]
This is an error that occurs in the old HLS module. No more maintenance. Only LLHLS will be continuously maintained. 
Could you please delete Bind->Publishers->HLS from your XML?
Then the above error does not occur.

```
			<HLS>
				<Port>80</Port>
				<!-- If you want to use TLS, specify the TLS port -->
				<!-- <TLSPort>443</TLSPort> -->
				<WorkerCount>1</WorkerCount>
			</HLS>
```

**Comment by naanlizard** [comment]
What is the error with legacy hls? For those of us that use it

**Comment by Keukhan** [comment]
@naanlizard  
HLS can still be used. However, in the current version, an error occurs when using the SRT protocol. I need to fix this to make it work normally. It seems that this should be patched so that the error does not occur.  
It was the opinion that maintenance is gradually reduced because LLHLS is compatible with HLS.

**Comment by naanlizard** [comment]
I'm aware of hls being end of life, don't worry, I just wanted to know if it was a bug we'd need to worry about

**Comment by krakow10** [comment]
I removed the HLS publisher(s) from Server.xml and the spam of errors has stopped :tada:  It is now much clearer when the other errors occur.
Error when I begin recording:
```
Apr 07 07:41:03 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:41:03.659] W [SPAPISvr-t8081:829] FILE | file_session.cpp:177  | mpegts format does not support the codec(0)
Apr 07 07:41:03 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:41:03.812] E [StreamWorker:858] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f4fc003c500] pts (-3360) < dts (-1860) in stream 1
Apr 07 07:41:03 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:41:03.813] E [StreamWorker:858] FileWriter | file_writer.cpp:406  | error = -22
```
Error when I start push to youtube:
```
Apr 07 07:42:26 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:26.627] E [SPAPISvr-t8081:829] Orchestrator | orchestrator.cpp:754  | Could not find Origin for the stream: [#default#youtube/quat_1440p60]
Apr 07 07:42:27 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:27.056] E [StreamWorker:895] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f4fc003c000] pts (131669) < dts (131686) in stream 1
Apr 07 07:42:27 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:27.056] E [StreamWorker:895] RTMPWriter | rtmp_writer.cpp:395  | Send packet error(-22:Invalid argument)
Apr 07 07:42:27 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:27.056] E [StreamWorker:895] RTMPPush | rtmppush_session.cpp:193  | Failed to send packet
Apr 07 07:42:32 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:32.298] E [StreamWorker:895] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f4f16e39000] pts (137387) < dts (137403) in stream 1
Apr 07 07:42:32 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:32.298] E [StreamWorker:895] RTMPWriter | rtmp_writer.cpp:395  | Send packet error(-22:Invalid argument)
Apr 07 07:42:32 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:32.298] E [StreamWorker:895] RTMPPush | rtmppush_session.cpp:193  | Failed to send packet
Apr 07 07:42:35 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:35.051] W [SPRtcSig-t3333:707] HttpServer | http_request_parser.cpp:28   | Invalid space index: first: -1, last: -1, line: 
Apr 07 07:42:35 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:35.051] E [SPRtcSig-t3333:707] HttpServer | http_transaction.cpp:163  | Invalid parse status: 400
Apr 07 07:42:35 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:35.878] E [SPRtcSig-t3333:707] HttpServer | http_transaction.cpp:163  | Invalid parse status: 400
Apr 07 07:42:36 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:36.751] E [StreamWorker:895] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f4f16e39280] pts (142400) < dts (142417) in stream 1
Apr 07 07:42:36 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:36.751] E [StreamWorker:895] RTMPWriter | rtmp_writer.cpp:395  | Send packet error(-22:Invalid argument)
Apr 07 07:42:36 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:36.751] E [StreamWorker:895] RTMPPush | rtmppush_session.cpp:193  | Failed to send packet
Apr 07 07:42:41 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:41.528] E [StreamWorker:895] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f4f16e39500] pts (147392) < dts (147409) in stream 1
Apr 07 07:42:41 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:41.528] E [StreamWorker:895] RTMPWriter | rtmp_writer.cpp:395  | Send packet error(-22:Invalid argument)
Apr 07 07:42:41 ovenmediaengine OvenMediaEngine[703]: [2023-04-07 07:42:41.528] E [StreamWorker:895] RTMPPush | rtmppush_session.cpp:193  | Failed to send packet
```

**Comment by Keukhan** [comment]
Can you send me the full log? Also, please share the record and push request API body.

**Comment by krakow10** [comment]
Here are the commands I use for the rest api:
recording:
`curl -d '{ "id" : "vod", "stream": { "name": "quat" } }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://10.0.0.8:8081/v1/vhosts/default/apps/youtube:startRecord`
youtube:
`curl -d '{ "id" : "youtube", "stream": { "name": "quat_1440p60", "tracks": [8,9] }, "protocol": "rtmp", "url":"rtmp://a.rtmp.youtube.com/live2/'"${YOUTUBE_STREAM_KEY}"'" }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://10.0.0.8:8081/v1/vhosts/default/apps/youtube:startPush`
This is run from bash, the stream key and auth key is filled in by environment variables.
Here is the full log:
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/11177155/ovenmediaengine.log)
I will also query the streams on the youtube application so you can see:
`curl -H 'Authorization: Basic '"${OME_AUTH_KEY}" http://10.0.0.8:8081/v1/vhosts/default/apps/youtube/streams/quat`
Here is the response formatted to be more readable:
[youtube-streams-quat.json.log](https://github.com/AirenSoft/OvenMediaEngine/files/11177175/youtube-streams-quat.json.log)

**Comment by Keukhan** [comment]
In case of using SRT protocol, I have found some problems and will fix them. 
Try the guide below to avoid this problem now

**1) How to avoid the recording failure problem**
When using the SRT input protocol, AAC codec passthrough (bypass) causes file recording failure. Please encode with AAC codec.


```
<OutputProfile>
        <Name>1440p60</Name>
        <OutputStreamName>${OriginStreamName}_1440p60</OutputStreamName>
        <Encodes>
                <Video>
                        <Name>video_1440</Name>
                        <Codec>h264</Codec>
                        <Bitrate>10000000</Bitrate>
                        <Framerate>60</Framerate>
                        <Width>2560</Width>
                        <Height>1440</Height>
                        <Preset>slower</Preset>
                        <Profile>high</Profile>
                        <!--<Tune>hq</Tune>-->
                        <ThreadCount>8</ThreadCount>
                </Video>
                <Audio>
                          <Bypass>true</Bypass>
                </Audio>
        </Encodes>
</OutputProfile>
```
to 
```
<OutputProfile>
        <Name>1440p60</Name>
        <OutputStreamName>${OriginStreamName}_1440p60</OutputStreamName>
        <Encodes>
                <Video>
                        <Codec>h264</Codec>
                        <Bitrate>10000000</Bitrate>
                        <Framerate>60</Framerate>
                        <Width>2560</Width>
                        <Height>1440</Height>
                        <Preset>slower</Preset>
                        <Profile>high</Profile>
                        <!--<Tune>hq</Tune>-->
                        <ThreadCount>8</ThreadCount>
                </Video>
                <Audio>
                        <Name>audio_aac</Name>
                        <Codec>aac</Codec>
                        <Bitrate>128000</Bitrate>
                        <Samplerate>48000</Samplerate>
                        <Channel>2</Channel>
                </Audio>
        </Encodes>
</OutputProfile>
```

**2. How to avoid Youtube push failure problem**
The bitrate of the video codec you set is 80Mbps. In Youtube, if the bitrate is very high, it is forcibly blocked. When encoding video, if you change the bitrate to a relatively low (10Mbps), Streaming will be sent to YouTube without any problems.

Please test and reply

**Comment by krakow10** [comment]
I edited the 1440p60 OutputProfile to encode the audio tracks.  RTMPPush successfully streams the OutputProfile to YouTube at 40mbps :tada: it is able to start streaming at 80mbps but every few seconds the video drops out and the result is that 1/3rd of the video is dropped on YouTube.  As for recording, I could not get it to work.  Attempting to record the passthrough OutputProfile gives this error message which we have seen before:
```
Apr 07 09:26:51 ovenmediaengine OvenMediaEngine[1867]: [2023-04-07 09:26:51.948] W [SPAPISvr-t8081:1993] FILE | file_session.cpp:177  | mpegts format does not support the codec(0)
Apr 07 09:26:53 ovenmediaengine OvenMediaEngine[1867]: [2023-04-07 09:26:53.091] E [StreamWorker:2040] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f0b4a63b280] pts (750) < dts (2250) in stream 0
Apr 07 09:26:53 ovenmediaengine OvenMediaEngine[1867]: [2023-04-07 09:26:53.091] E [StreamWorker:2040] FileWriter | file_writer.cpp:406  | error = -22
```
Attempting to record the 1440p60 OutputProfile with audio encoding enabled gives only this error message:
```
Apr 07 09:30:07 ovenmediaengine OvenMediaEngine[1867]: [2023-04-07 09:30:07.397] W [SPAPISvr-t8081:1993] FILE | file_session.cpp:177  | mpegts format does not support the codec(0)
````

**Comment by Keukhan** [comment]
A possible option currently available is to enable AAC encoding when recording.

Apr 07 09:30:07 ovenmediaengine OvenMediaEngine[1867]: [2023-04-07 09:30:07.397] W [SPAPISvr-t8081:1993] FILE | file_session.cpp:177  | mpegts format does not support the codec(0)

The log above is a warning, but it is normal.
Data type tracks are ignored as unsupported codecs when recording in TS files.

We plan to improve the passthrough(bypass) AAC codec so that there is no problem during recording.

Thanks

**Comment by krakow10** [comment]
> Attempting to record the 1440p60 OutputProfile with audio encoding enabled gives only this error message:

I forgot that recording a different output profile goes to a different folder by default.  Recording like this is working, but I will not be using it like that.

> A possible option currently available is to enable AAC encoding when recording.

This is how I tested recording the passthrough OutputProfile, the result is the three errors in my last comment.

> I was surprised at the video bitrate of around 200Mbps. Can you actually feel the difference with 60Mbps?

I also wanted to provide more information on this.  Here is a pixel peeping screenshot comparison website where you can use the arrow keys to flick between screenshots of hevc_nvenc at 40mbps vs 60mbps vs 200mbps:
https://slow.pics/c/svDculna
The compression is particularly noticeable in the lower middle area of the screenshot near the edge of the grey block texture.  Using a high bitrate in the intermediate representation helps to stave off generation loss from encoding multiple times.

**Comment by Keukhan** [comment]
Fixed a problem that caused an error in the HLS, RtmpPush and File publishers when passthrough (Bypass). I committed this to the master branch. A new release will be coming soon.

Thanks.

**Comment by getroot** [comment]
> I also wanted to provide more information on this. Here is a pixel peeping screenshot comparison website where you can use the arrow keys to flick between screenshots of hevc_nvenc at 40mbps vs 60mbps vs 200mbps:
> https://slow.pics/c/svDculna
> The compression is particularly noticeable in the lower middle area of the screenshot near the edge of the grey block texture. Using a high bitrate in the intermediate representation helps to stave off generation loss from encoding multiple times.

Thank you. This is a great experience.

**Comment by krakow10** [comment]
I can confirm that both RTMPPush and File Recording are working with stream copying.  I will reopen the issue if I find something related to this doesn't work new time I stream.  Thank you for the fix!
