### ISSUE TITLE
'Could not get a playlist for HLS Publisher' in cluster environment

### ISSUE THREAD

**Issue by mauriziocarella** [AirenSoft/OvenMediaEngine#118]
**Describe the bug**
I've setup a cluster environment with 2 edges and 1 origin server. WebRTC playback works fine from the two edges but HLS/DASH playback is not working, giving the following error 

`edge_1  | [2020-05-18 14:14:02.222] W 68 HTTPPublisher | segment_publisher.cpp:178  | Could not get a playlist for HLS Publisher [(nil), #default#app/live_o, playlist.m3u8]`

If I try to play from origin server everything works fine. 

**Server (please complete the following information):**
 - OS: CentOS Linux release 7.7.1908
 - OvenMediaEngine Version: v0.10.1
 - Branch: master (latest)

**Player (please complete the following information):**
 - Device: Macbook PRO
 - OS: MacOS 10.15.4
 - Browser: Google Chrome
 - Version: 81.0.4044.138

**Comment by getroot** [comment]
To analytics the problem, I need full logs of the edge server and origin server and also need Server.xml of origin/edge servers.

**Comment by mauriziocarella** [comment]
Here it is a zip file with origin & edge configurations, logs and docker files

[Archive.zip](https://github.com/AirenSoft/OvenMediaEngine/files/4645564/Archive.zip)

**Comment by getroot** [comment]
Thank you for contributing to finding the bug.
This bug will be fixed in 0.10.3. If you want to test this now, test it with the Dev branch.

**Comment by getroot** [comment]
Can you tell me how to use this feature? If it is a feature that many people need, we can prioritize it.

**Comment by mauriziocarella** [comment]
Fetching HLS/MPD playlists from first edge now works fine with _dev_ image from docker hub. But on the second edge the result is the same error. Configurations are (really) the same (same Server.xml, same environment) on the two edges

**Comment by getroot** [comment]
Thank you for sharing your test results.
