### ISSUE TITLE
"stunnel" RTMPS proxy workaround and OME 0.15.9

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1188]
This workaround for RTMPS I mentioned in #1133 has worked perfectly for some time, but with OME 0.15.9 I get a new error from OME like this:

`[2023-04-14 23:19:18.543] E [SPRTMP-t1935:397] RTMPProvider | rtmp_stream.cpp:414  | Invalid publish URL: rtmps://mywebsite:1936/live/482c41c327109?p=eyJ1cmxfZXhwaXJlIjo3MjQ1NTk0MTMwMDAwfQ&s=8nuDmePyJsBXstTtPWj_ymyHHqA`

This is weird because stunnel is definitely listening on port 1936 and rerouting the requests to 1935... Any ideas or clues why it would have stopped working between 0.15.8 to 0.15.9? 🙏🏻

**Comment by getroot** [comment]
I just committed a fix for this problem. The validator added in 0.15.9 was rather ruining compatibility with stunnel. Please check.

**Comment by bchah** [comment]
Perfect success! Thank you very much @getroot 🎉
