### ISSUE TITLE
Unable to play live stream,

### ISSUE THREAD

**Issue by dengwoadeng** [AirenSoft/OvenMediaEngine#12]
Hello,I Trying to runing OME problem appear : Nothing is displayed

![image](https://user-images.githubusercontent.com/34929719/51234233-21dee780-19a7-11e9-8062-7b191f55f540.png)
![image](https://user-images.githubusercontent.com/34929719/51234248-2efbd680-19a7-11e9-822c-b5c45520c55f.png)

**Comment by sfreet** [comment]
Hello dengwoadeng.

Currently, OME only supports H264 baseline profile for some reasons.
Try to change your OBS studio (I guess you are using it) encoding profile option as follows
[Profile] - baseline, [Cpu Usage Preset] - ultrafast (higher than fast)

If this does not work, please tell me again :)

**Comment by dengwoadeng** [comment]
Thanks ,According to your method Solved my problem
