### ISSUE TITLE
WebSocket connection. Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by Barahten** [AirenSoft/OvenMediaEngine#121]
Google Cloud Platgorm is used for the test. Port 3333 is open. For the stream, OBS studio is used. Broadcast goes to RTMP stream. When using a native OvenPlayer player with receiving a stream through WebSockets, an error is issued in the console  

> WebSocket connection to 'ws://ip:3333/app/test_o' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by getroot** [comment]
Check your firewall or public IP.
This doesn't seem to be a problem with OvenMediaEngine.

Upload Server.xml and OvenMediaEngine.log for further analysis. The information you provided is too short for analysis.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
