### ISSUE TITLE
No audio transcoding when RTSP-Pulling

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#122]
**Hi everyone!**
Im using RTSP Pull (h264/aac), but I can't transcode audio to opus. While when I use RTMP it works fine. So audio is not working on player with WebRTC (not using HLS or DASH)

Encoding profile configuration is same for both. Transcoding is not active with RTSP Pull on logs.

*PS: Im using the server and it works really fine! Thanks a lot!* 👍

**Comment by kwonkeukhan** [comment]
Hi nagavar . 

The RTSP Pull stream requires the name of the rtsp_live specific application.  Therefore, you need to configuration the application to use transcoding.   please refer to the configuration below.

Have a good day. 

`
...
<Application>
	<Name>rtsp_live</Name>
	<Type>live</Type>
	<Encodes>
		<Encode>
			<Name>default_bypass</Name>
				<Video>
				<Bypass>true</Bypass>
			</Video> 
			<Audio>
				<Bypass>true</Bypass>
			</Audio>							
		</Encode>			
		<Encode>
			<Name>default_opus</Name>
			<Audio>
				<Codec>opus</Codec>
				<Bitrate>128000</Bitrate>
				<Samplerate>48000</Samplerate>
				<Channel>2</Channel>
				<Bypass>false</Bypass>
			</Audio>
		</Encode>
	</Encodes>
	<Streams>
		<Stream>
			<Name>${OriginStreamName}</Name>
			<Profiles>
			   <Profile>default_bypass</Profile> 
			   <Profile>default_opus</Profile> 
			</Profiles>
		</Stream>																								
	</Streams>
	<Providers>
		<RTMP />
		<RTSPPull />
	</Providers>
	<Publishers>
		<ThreadCount>16</ThreadCount>
		<HLS>
			<SegmentDuration>5</SegmentDuration>
			<SegmentCount>3</SegmentCount>
			<CrossDomain>
				<Url>*</Url>
			</CrossDomain>
		</HLS>
			<DASH>
			<SegmentDuration>5</SegmentDuration>
			<SegmentCount>3</SegmentCount>
			<CrossDomain>
				<Url>*</Url>
			</CrossDomain>
		</DASH>  
		<LLDASH>
			<SegmentDuration>5</SegmentDuration>
			<CrossDomain>
				<Url>*</Url>
			</CrossDomain>
		</LLDASH> 	 		
		<WebRTC>
			<Timeout>30000</Timeout>
		</WebRTC>
	</Publishers>
</Application> 
...
`

**Comment by kwonkeukhan** [comment]
Hi nangavar. 

Encoding options should be configure for the application as the webrtc output application name.
If the WEBRTC playback address is the same as ws:///<address>:3333/**app**/stream, encoding options should be set in the **app** application. 

If not, please explain about your test environment(confgiruation, playback url etc). Let's find out what the problem is.

Have a nice day.  

```xml
<Application>
	....
	<Name>app</Name>
	<Type>live</Type>
	<Encodes>
		<Encode>
			<Name>default_bypass</Name>
				<Video>
				<Bypass>true</Bypass>
			</Video> 
			<Audio>
				<Bypass>true</Bypass>
			</Audio>							
		</Encode>			
		<Encode>
			<Name>default_opus</Name>
			<Audio>
				<Codec>opus</Codec>
				<Bitrate>128000</Bitrate>
				<Samplerate>48000</Samplerate>
				<Channel>2</Channel>
				<Bypass>false</Bypass>
			</Audio>
		</Encode>
	</Encodes>
	<Streams>									
		<Stream>
			<Name>${OriginStreamName}</Name>
			<Profiles>
			 <Profile>default_bypass</Profile> 
			 <Profile>default_opus</Profile> 
			</Profiles>
		</Stream>																			
	</Streams>
    ....
</Application>
```

I recommend you to test with the latest version of OME.

**Comment by nangavar** [comment]
Hi kwonkeukhan!
Thanks a lot!

I was running v0.10.2 that's why it was not working. 
Now running v0.10.3 transcoding is working fine with RTSP pulling! 

Thanks again! :)
