### ISSUE TITLE
OME will not ingest SRT from OBS 29.1.x

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#1229]
**Describe the bug**
OvenMediaEngine throws errors when I try to stream SRT from OBS 29.1.0 and 29.1.1, but it works perfectly fine from OBS 29.0.2.

**To Reproduce**
1. Set Server.xml as follows [Server.xml.log](https://github.com/AirenSoft/OvenMediaEngine/files/11449610/Server.xml.log)
2. Tested with OBS h264_nvenc and hevc_nvenc over SRT streaming to URL `srt://10.0.0.8:9999?streamid=srt%3A%2F%2F10.0.0.8%3A9999%2Fhw60%2Fquat&latency=20000`
3. See repeated error
`[2023-05-09 20:43:12.092] E [SPSRT-s9999:312] MPEGTS_DEPACKETIZER | mpegts_depacketizer.cpp:555  | Unsupported codec has been received. (pid : 257 stream_type : 6)`

**Expected behavior**
OME receives the stream without errors

**Logs**
[ovenmediaengine.log.20230510.zip](https://github.com/AirenSoft/OvenMediaEngine/files/11449603/ovenmediaengine.log.20230510.zip)

**Server (please complete the following information):**
 - OS: Debian 11 Proxmox container
 - OvenMediaEngine Version: 9db7db1429c1f60a160ebace77765120c61e8904
 - Branch: master

**Additional context**
Can you reproduce the issue?  If this is an OBS bug I can report it there instead.

**Comment by pkviet** [comment]
OBS maintainer for srt here. What's your obs log ? Which codec are you using ? We didn't change anything in the code for SRT in the various versions you quote. Are you sure you tested against identical OME versions ?

**Comment by getroot** [comment]
@krakow10 
Did you set FFmpeg Opus to Audio Encoder? I can't reproduce this issue with OBS 29.1.1.

**Comment by krakow10** [comment]
I just realized the problem and it seems obvious in hindsight considering what changed in OBS 29.1, but I was having this issue because the [srtmultiaudio](https://github.com/pkviet/obs-studio/tree/srtmultitrackaudio) code uses the recording audio encoder and ignores the stream audio encoder selection (which didn't exist at the time).  Selecting AAC as the recording audio track fixes the issue.  I should have known from the start because I [patched it up myself](https://github.com/krakow10/obs-studio/tree/29.1.0-multi-audio) renaming the aacTrack variables to recordTrack.

Thank you both for investigating my issue

**Comment by pkviet** [comment]
@krakow10 i had rebased last week the multitrack audio code in my repo. Feel free to test it. It'll be the basis for my pr. I haven't tested it with opus btw. But i tested it extensively during srt plugfest against several vendors.
