### ISSUE TITLE
REST API for stream key and other settings

### ISSUE THREAD

**Issue by johnlanz** [AirenSoft/OvenMediaEngine#123]
Hello Guys,
Is there an existing api where you can control who is allowed to use stream key?

if it isn't available at the moment i think @getroot mention this on closed stream key issue:
"You can directly modify the source code and query the stream key to the http-based api server to accept the connection if you receive 200 or reject it if you receive 404."
Can you give as a hint on where is the file to modify? is the source code based on makefile c program?

**Comment by getroot** [comment]
Do you want stream key authentication in RTMP?

I think it is better to handle it in **PublishInterleavedChannel** function in **src/project/base/provider/push_provider/provider.cpp** file. Processing the authentication here will apply not only to RTMP in the future but also to other PUSH providers such as RTSP.

**Comment by getroot** [comment]
Ah, my explanation above is based on the source of the dev branch.

**Comment by johnlanz** [comment]
@getroot how to add cpprestsdk library? just needed to add this on build: -lboost_system -lcrypto -lssl -lcpprest

**Comment by dimiden** [comment]
@johnlanz 
Please add the following to ```AMS.mk``` in the path where the module using ```cpprestsdk``` is located:

```
LOCAL_LDFLAGS := -lboost_system -lcrypto -lssl -lcpprest
```

For example, if you use ```cpprestsdk``` in the ```main.cpp```, modify the ```src/projects/main/AMS.mk``` file as shown below.

```
...
ifeq ($(MAKECMDGOALS),release)
	# Enable jemalloc 
    $(call add_pkg_config,jemalloc)
endif

LOCAL_LDFLAGS += -lboost_system -lcrypto -lssl -lcpprest # <========== Add this line to line 67

LOCAL_TARGET := OvenMediaEngine
...
```

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
