### ISSUE TITLE
OME stops accepting new streams

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#1234]
At a little bit after 05:00:00 in the logs here https://gist.githubusercontent.com/naanlizard/6cfa3ceca4ffdd7721ce8e30bacc85b6/raw/1dfb37711ac001dcdf0fdc74ba02317601722d24/may15clean.log OME stops accepting new inputs (rtmp directly to the server), and stops serving any streams (presumably because they are disconnected).

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/f42bd6bc-c2cd-40fa-8787-20478ee77063)

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/e31b943a-8fd7-4113-8223-16323055e15f)

I checked and there are no dump files in OME's docker

If this isn't enough info to find the bug, please tell me what you need for the next time this happens, and I will get it.

_Originally posted by @naanlizard in https://github.com/AirenSoft/OvenMediaEngine/issues/1166#issuecomment-1547773782_

**Comment by naanlizard** [comment]
I've contacted the streamer you mentioned to see if I can get a copy of their encoder settings, I will update if/when they respond.

**Comment by getroot** [comment]
> I've contacted the streamer you mentioned to see if I can get a copy of their encoder settings, I will update if/when they respond.

That will be of great help. thank you

**Comment by naanlizard** [comment]
![image](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/0454ce98-91d5-48b2-8b56-e5165704b408)


Here is a screenshot of the stream in question, which goes online and then offline far before the issue occurs.

I believe the screenshots are 4 hours ahead of the log file e.g. in the log file, 12:00 is 16:00 in the screenshot(s)

**Comment by naanlizard** [comment]
Sorry, I was off in the wrong direction for times - in the log, timestamps are 4 hours ahead. So 12:00 in the log file is 8:00 in the screenshots. Or 5:00 in the log file is 1:00 in the screenshots (toward the right)

**Comment by naanlizard** [comment]
They're using Streamlabs on an iPad, 
![photo_2023-05-15_17-17-18](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/96aea392-7169-4bf7-9e80-4bf2550eff9e)
![photo_2023-05-15_17-13-41](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/b6628762-5763-455a-86dc-a41bd60f83b5)


I'm assuming they haven't changed many of the defaults.

**Comment by getroot** [comment]
Thanks for the detailed information. My guess so far is that that encoder hasn't sent any packets since the connection was open at some point. (Perhaps the app was in the background) And that encoder sent packets again around 05:00 and at the same time terminated the connection. At this time, OME was attempting to create a segment that was approximately 8 hours long, while simultaneously processing the deletion of the stream. OME seems to be malfunctioning under these conditions.
I'll get the app and try to reproduce the problem.

**Comment by naanlizard** [comment]
I've asked the user and we'll see - I suspect they weren't doing anything around the time of the crash, but perhaps.

**Comment by naanlizard** [comment]
Just realized an important detail

Ome might not see the stream, when testing it was only forwarded from our Nginx rtmp instance to ome for a short while, then disconnected for some reason. Ome continues to let you request the llhls playlist but it loops and is broken. I'm not sure if webrtc worked

**Comment by Keukhan** [comment]
@naanlizard 

Thank you for reporting
Analyzing your log, I found that a race condition occurred during the deleting the stream and recreating the audio resampling filter. The problem has been fixed as below, so please test it on the master branch.

https://github.com/AirenSoft/OvenMediaEngine/commit/e7d79c4aad28dbb2cc832e242844dec641ea6439

Thanks

**Comment by naanlizard** [comment]
Thank you, we have updated ome and will reopen or make a new ticket if we have any more problems
