### ISSUE TITLE
RTSP mobile consumption

### ISSUE THREAD

**Issue by a7medo778** [AirenSoft/OvenMediaEngine#124]
hey guys
i am moving away from red5pro, and now considring setting up my whole infra around OME.

there is 1 key component missing form the documentation: the mobile SDK 
my ultra-low latency streams are meant for a gaming mobile app, the current stream is consumed with RTSP format from red5pro SDK

whats the current stats of the SDK for ios/android, is it ready for production consumption? webview is not an option sadly

and another side questions: a 16 vcpu with 32gb of ram should land me around 3500 subscribers over 1 mbps resolution right ??

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
