### ISSUE TITLE
SIGSEGV/SIGABRT Pure Virtual Function Called crash

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#1243]
Sorry to be the bearer of bad news again, but another crash.

Server.xml etc like #1235 

Log of just the end of the crash

https://gist.github.com/naanlizard/05ea90d63dc30bbbde08de6a22982169

Longer log, missing some of the end it seems

[newerror3.txt.gz](https://github.com/AirenSoft/OvenMediaEngine/files/11512405/newerror3.txt.gz)

Crash dump

[crash_20230519.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/11512407/crash_20230519.dump.txt)

**Comment by getroot** [comment]
Are you using 0.15.10? Fortunately(?), this crash has already been patched in 0.15.11.

**Comment by naanlizard** [comment]
Yes, 0.15.10. I'll update to 0.15.11

**Comment by naanlizard** [comment]
Closing, updated and hopefully won't see this one again. Have I previously reported this one or did someone else get one?
