### ISSUE TITLE
Broadcast sound is missing in a few hours after server startup

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1244]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1232

<div type='discussions-op-text'>

<sup>Originally posted by **bigsssss** May 15, 2023</sup>
Video stream is transmitted by SRT, video transcoding is disabled, only OPUS audio transcoding is used. Video viewing only via WebRTC. After some time after starting the server, the sound on the video stream disappears completely, while the video continues to work.  Cannot solve the problem for several months. We use Nimble Streamer for SRT streaming to Oven, the same problem occurred when streaming from Epiphan Pearl Nano encoder

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/11474146/ovenmediaengine.log)
</div>

**Comment by getroot** [comment]
@bigsssss
I solved the timestamp issue in SRT (MPEG2-TS). You can test it with the latest master branch. Could you please confirm that your problem is solved?

**Comment by bigsssss** [comment]
Thank you. I'll be sure to test it and let you know.

**Comment by getroot** [comment]
@bigsssss 
I'm sorry. I have found another error in the code I modified this time. I will comment again after the correction.

**Comment by bigsssss** [comment]
Thanks for the message, I'll be waiting.

**Comment by getroot** [comment]
I just made a few changes and committed them. Please check if your problem is solved!

**Comment by bigsssss** [comment]
Ok, thank you very much.

**Comment by bigsssss** [comment]
Hello. The problem with mute is probably fixed, but now after a couple of days the video broadcast does not start at all and the size of the logs becomes very large. I can't upload the log file here because of the large size, so I'll leave a link to it. 
https://1storage.ams3.cdn.digitaloceanspaces.com/ovenmediaengine.log.20230529.log

**Comment by getroot** [comment]
The audio freezing issue appears to have been resolved. Thank you for your confirmation.

Another issue you reported, a quick analysis of the logs seems to be very bad network conditions. Could you please close this issue and create a new discussion about it?
