### ISSUE TITLE
RTMP Push (for re-streaming)

### ISSUE THREAD

**Issue by borderlander19** [AirenSoft/OvenMediaEngine#125]
Hi, I've just discovered OME, and I must say I am very impressed, both with the performance/latency and ease of deployment with or without docker.

One thing that would be really useful is to re-stream/push the incoming RTMP to other destinations such as social media sites.

Currently I can work around this by streaming to an NGINX docker which re-streams to both OME and other destinations, but it would be great to have the functionality within OME. 

On a related note, is it possible to publish(pull) the incoming RTMP? It doesn't seem to be possible with the default config to view the source stream (e.g. in VLC) with rtmp://<Server IP>[:<RTMP Port>]/<Application name>/<Stream name> which is always useful for troubleshooting.

Thank you for the work so far, and all the best with the project!

**Comment by getroot** [comment]
Hello, 
We plan to develop RTMP Push for re-streaming. It will probably be released later this year. Thank you for your attention and praise.

**Comment by cesarandreslopez** [comment]
Hey guys. I've been enjoying this project immensely! Thank you for this!

On the same note that RTMP push, It would be useful for my application if I could also pull the same RTMP URL that I am pushing, as would be the standard behavior in nginx-rtmp module where if I push to say:

rtmp://IP:1935/app/stream-0

I could also be able to pull from the same URL (to relay the same stream).

**Comment by cesarandreslopez** [comment]
@getroot was this just resolved here?
https://github.com/AirenSoft/OvenMediaEngine/commit/250713683d308b91d7b038c56b2e1ef048b74930

**Comment by getroot** [comment]
It is still under development. We are developing a REST API and the RTMP Push Publisher will be controlled by the REST API.

**Comment by cesarandreslopez** [comment]
@getroot sounds exciting!

**Comment by yoyomule** [comment]
> It is still under development. We are developing a REST API and the RTMP Push Publisher will be controlled by the REST API.

Hi，has it been completed?

**Comment by getroot** [comment]
It is already completed in the master branch.
We are writing the manual, and the feature will be included in the 0.11.0 release this month.

**Comment by IanMitchell77** [comment]
@getroot - will RTMP pull be included in the next release too?

**Comment by getroot** [comment]
@IanMitchell77 no. RTMP Pull is still in the backlog.

**Comment by devnulldevzero** [comment]
> It is already completed in the master branch.
> We are writing the manual, and the feature will be included in the 0.11.0 release this month.

What about? About API server, or RTMP Push feature? 
Sorry for stupid question :)))

**Comment by getroot** [comment]
@devnulldevzero 

Both API and RTMP Push have been completed. All of the code has recently been updated in the master branch and internal testing has been completed. Right now we are working on both manuals.

In addition, in 0.11.0 the thumbnail publisher and recording functions will be updated as well. :-)

**Comment by getroot** [comment]
RTMP PUSH was released in 0.11.0.
https://airensoft.gitbook.io/ovenmediaengine/push-publishing

**Comment by techno-club** [comment]
How do you configure this. The docs link provided:
https://airensoft.gitbook.io/ovenmediaengine/push-publishing

Only indicate that you add  
<RTMPPush>
    	</RTMPPush>

so how will OME know my Facebook or YouTube credentials?  How do you configure this?

**Comment by ali-khani** [comment]
> @IanMitchell77 no. RTMP Pull is still in the backlog.

would you please inform us about RTMP pull  ?

**Comment by devnulldevzero** [comment]
> would you please inform us about RTMP pull ?

It works right now (used on production three times).

**Comment by IanMitchell77** [comment]
> > @IanMitchell77 no. RTMP Pull is still in the backlog.
> 
> would you please inform us about RTMP pull ?

@ali-khani - I just want to be able to configure or tell(via the API) OME to pull a RTMP stream.

**Comment by IanMitchell77** [comment]
> > would you please inform us about RTMP pull ?
> 
> It works right now (used on production three times).

@devnulldevzero how do you do it?

**Comment by ali-khani** [comment]
> > would you please inform us about RTMP pull ?
> 
> It works right now (used on production three times).
Great but how ?
