### ISSUE TITLE
Document OVT protocol / add ovt<->srt tools

### ISSUE THREAD

**Issue by vixns** [AirenSoft/OvenMediaEngine#126]
We plan to create a middleware between origin and edge servers. As these components communicate using the OVT protocol, it would be convenient to :

- Document the OVT protocol ( I couldn't find it in the official documentation, I may miss a link )
- Add some binary helpers to translate OVT to/from SRT

**Comment by getroot** [comment]
What is the role of middleware?
OVT is OME's own protocol for Origin-Edge communication and is very simple.

The comments from the sources below may help you.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/modules/ovt_packetizer/ovt_packet.h

**Comment by vixns** [comment]
What is the role of middleware?
> source compositing/mixing, add watermarks, overlays, monitor streams, ...

according to https://static.wixstatic.com/media/a9e07d_4913dfd391c8412395fa8b5ec51fa05b~mv2.png/v1/fill/w_978,h_261,al_c,q_95/OME_FLOW1.webp , OVT packets are sent over SRT, I misread, my bad.

So, what we would like is more or less a proxy library/API keeping connection and OVT encoding/decoding in OME project. We'll use this API as a shared lib to build middlewares.
This way any change in the OVT protocol will not require code change in third party tools.

**Comment by getroot** [comment]
I missed this.
Have you solved this problem?

OVT is designed to be transmitted over TCP, UDP and SRT.
Currently, we are only testing transmissions over TCP. SRT will work with minor modifications to the code, but hasn't been tested much.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
