### ISSUE TITLE
Best Hardware Architecture for OME

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#127]
Hi all!

We're running OME and we are really happy with how it is working. So we decided to buy a new hardware after the tests. My question is which architecture do you recommend to run OME. Regarding my environment we have to manage about 18/24 different streams (2/4 Mbps each) but with not too much viewers (maybe 10 by stream), we are using it to remote production due to the low latency (amazing).

Im not sure wich architecture, Xeon or i9, fits better for OME, having in mind that probably an i9 has better performance with ffmpeg.

My options:
1x or 2x i9 (8 or 16 core) 32GB RAM
2x Xeon (32 core) 32GB RAM

May I have a hint from you guys in order to decide this?

Many thanks, OME is working really fine for us! :)

**Comment by getroot** [comment]
Thank you. If your time allows someday, tell us your use-case.

I haven't tried various tests on hardware. If you're running a live transcoder, encoding performance is paramount, so in your opinion FFMPEG works well with hardware that works well.

**Comment by mpisat** [comment]
If you bypass video transcoding, that setup is overkill. I always transcode video at the client (me, OBS!) so you don't need a transcode at the server level (except Opus for audio)

**Comment by nangavar** [comment]
Hi getroot and mpisat!
OK, thanks a lot! Will try, and let you know.

My case of use is related to a sports production center. Since the pandemic we had to start working from home (directors, producers, sound guys, etc), but we had to deal with huge latencies, so the operators had to wait some seconds between their actions and what they see.

Since we are using OME, the operators are able to see almost live what they are doing. Of course in our center we use a lot of hardware encoders, so we reach between 100/200mseg latency, what is perfect for them.

In fact I found some FPGA encoders that are having some problems with OME trough RTMP, so we are using RTSP Pull for them. Maybe I can open an issue for that since these encoders work perfectly with Youtube, Facebook, etc by RTMP. It could be interesting to run a test from my encoders to debug.

Regarding transcoding, by the moment Im bypassing video and converting audio to opus, but in that way i get a few mSegs of lipsync. So my idea is to turn on video transcoding in order to get zero lip-sync, but I would need more hardware for that.

Many thanks you all guys
Bests,

**Comment by getroot** [comment]
Good morning. nangavar.

I am interested in an encoder that works well with Youtube but does not work with OME. I would like to analyze it. Please tell me more information about it.

Bypassing video transcoding and transcoding audio to opus should not cause lipsync issues. This is because the browser makes corrections for it (originally it gets better over time). It may be our bug. Can I hear more information about it?

**Comment by mpisat** [comment]
@nangavar can you tell us how do you pull video to OME?
Via FFMPEG? with -re or without -re? 

When buffering happens in WebRTC, OvenPlayer or WebRTC itself changes playback speed (decrease or increase) to keep it realtime but it is temporary and it is great for live streaming.

**Comment by nangavar** [comment]
Hi guys!

I've opened the issue #133 to continue with the encoders issue.

Regarding lip-sync, I always get about 50mSeg of delay in opus audio on the player side, I assumed that it was because I was transcoding only audio so it gets delay. I will test transcoding video too and let you know. If you're interested I can open a new issue to run tests and see what's happening. 

Regarding RTSP Pulling I simply declare my RTSP encoders within the origin map as an Origin passing the scheme as RTSP and the URL of the encoder. It works fine. What I like most is that after 60 seconds if there is no viewer OME closes the connection. When I use RTMP-push OME uses CPU even when no viewers are connected. I prefer this configuration for my fixed encoders. You should enable RTSP Pull in the provider list within the application.

Many thanks. I will close this issue. I will let you know how OME goes running on i9 architecture.
