### ISSUE TITLE
Regression: No Audio/Low Pitched Glitchy Audio Streaming With Multiple Audio Tracks

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#1272]
**Describe the bug**
I am streaming to OME via SRT with 6 audio tracks, restreaming with RTMPPush sending the first audio track to YouTube and the second audio track to Twitch.  Twitch receives silent audio while YouTube receives pitched-down glitchy audio.

**To Reproduce**
1. [Server.xml.log](https://github.com/AirenSoft/OvenMediaEngine/files/11739965/Server.xml.log)
2. Encoder is multi-audio patched OBS 29.1.2 streaming H.264 + AAC over SRT
3. Glitchy/silent audio on stream

**Expected behavior**
Clear audio

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/11739966/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Debian Proxmox Container
 - OvenMediaEngine Version: tested on v0.15.12 bca0da14529afc6b3321a83d1ee3e4548ed416e5, tested on git master 2ebaf7c92eea93d75406418bef8574e8dcce820b
 - Branch: master

**Additional context**
The issue does not occur using v0.15.11 2847595215f09904360ee21453c763f15b9b6e43
The patch I'm using to stream with multiple audio tracks is being upstreamed into OBS!  The feature [pull request](https://github.com/obsproject/obs-studio/pull/9028), the [CI build artifacts](https://github.com/obsproject/obs-studio/actions/runs/5191672359) so you can reproduce the issue

**Comment by getroot** [comment]
Can you confirm if the issue is reproduced when you play each audio track in LLHLS?

https://github.com/AirenSoft/OvenMediaEngine/discussions/1131

**Comment by krakow10** [comment]
I built and tested v0.15.2: the audio does not work on Twitch, but all the tracks I tested work perfectly from LLHLS when I record the stream to a file with ffmpeg.

**Comment by getroot** [comment]
You mean 0.15.12 and 0.15.11? (not 0.15.2)

What I want to know is if there is a problem with OME's RTMP Push, or if the problem is somewhere else. If it plays without problems in the audio multi track (multilingual audio) function provided by OME's LLHLS, we should check the RTMP push side.

Also, if you share the Json Request you used for RTMP Push, it will be more helpful to reproduce the problem.

**Comment by krakow10** [comment]
Yes, v0.15.12 I had typed it in wrong.  Here is the bash commands I use to start the streams:
```
curl -d '{ "id" : "youtube", "stream": { "name": "quat_1440p60", "tracks": [8,9] }, "protocol": "rtmp", "url":"rtmp://a.rtmp.youtube.com/live2/'"${YOUTUBE_STREAM_KEY}"'" }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://10.0.0.8:8081/v1/vhosts/default/apps/hw60:startPush
curl -d '{ "id" : "twitch", "stream": { "name": "quat_1080p60", "tracks": [16,18] }, "protocol": "rtmp", "url":"rtmp://sea.contribute.live-video.net/app/'"${TWITCH_STREAM_KEY}"'" }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://10.0.0.8:8081/v1/vhosts/default/apps/hw60:startPush
```

**Comment by getroot** [comment]
I found some strange code on the RTMP Push side and fixed it. Could you please check if your problem is solved with the master branch?

**Comment by krakow10** [comment]
I built b8c82464478271bfacfa1d5a343a98a54a5840a0 and the issue seems to have been resolved.  Thanks for the fix!
