### ISSUE TITLE
infoFile created by HLS Dump API always shows status "Running"

### ISSUE THREAD

**Issue by ArturLinnik** [AirenSoft/OvenMediaEngine#1279]
Hi again!

I'm using the version 0.15.10 of OME and it looks like the <Status> tag of the infoFile is not working as expected. It's always "Running".

This happens when I stop the dumping making stopHlsDump POST request and also when the stream finishes.

I have checked the releases and the only thing related I could find was the 0.15.11 release, but I understand those changes were to recordings not to hls dumping.

I hope you can help me.

Thank you!

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/11712863/ovenmediaengine.log)

_Originally posted by @ArturLinnik in https://github.com/AirenSoft/OvenMediaEngine/discussions/1073#discussioncomment-6140830_

**Comment by getroot** [comment]
I fixed this issue and committed it to the master branch. Please check if your problem is solved. thank you.

**Comment by getroot** [comment]
The fix for this bug is part of the 0.15.14 release.
