### ISSUE TITLE
WebRTC on TCP Transport

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenMediaEngine#128]
I've tested this env variable to see if OME could deliver video using TCP with WebRTC.
--env OME_ICE_CANDIDATES=*:10000-10005/tcp

I also set up docker port forwarding to TCP. SDP gives TCP ICE candidates but I can't get it to work. I'm assuming it doesn't support TCP transport for WebRTC.

Is it possible to add this feature? With UDP, I get lost frames despite perfect connectivity (even on a local setup).

**Comment by getroot** [comment]
I don't know of browsers and standards that support WebRTC/TCP. So we didn't support that feature either. Do you have any new information about WebRTC/TCP? Please give me that information.

For environments with high packet loss, we plan to implement NACK. It will probably be released later this year.

**Comment by mpisat** [comment]
I didn't know it was a limitation by browsers? There is an adult cam site called myfreecams and when you choose WebRTC from the player, it uses TCP transport for WebRTC and works pretty well for me. I verified it is TCP by WireShark and not UDP. They are using NxServer (nomachine.com) for their WebRTC implementation.

**Comment by getroot** [comment]
Maybe it is using TURN.
Using TURN, you can configure Browser -> (TCP) -> TURN -> (UDP) OvenMediaEngine.

**Comment by mpisat** [comment]
so if I announce TURN server with ICE candidates and install & configure a TURN server, it will work out of the box this way?

from myfreecams:
![image](https://user-images.githubusercontent.com/52810975/84476397-446a5280-acb8-11ea-8779-b7127675f7e5.png)

wireshark capture:
![image](https://user-images.githubusercontent.com/52810975/84476450-5c41d680-acb8-11ea-8aae-60445cbf7cb8.png)

Thank you for taking your time and answering questions. I appreciate it.

**Comment by mpisat** [comment]
> Maybe it is using TURN.
> Using TURN, you can configure Browser -> (TCP) -> TURN -> (UDP) OvenMediaEngine.

Is there an example of how I can make the TURN server work with OME on default UDP ports?
I can install the TURN server no problem, but how do I announce it with OME using ICE candidates or other settings?

**Comment by getroot** [comment]
The setting for TURN is to set it on the player.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by getroot** [comment]
We have completed the development of NACK and RTP retransmission and released it to the master branch. If you are still interested in this issue, you can test it with the master branch.
