### ISSUE TITLE
Pool of Urls - RTSP Pulling

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#129]
Hi All!
Im trying to set up a pooling of Urls in order to lookup for the encoder that matches with the stream key. I've tried declaring many Urls as origin for RTSP pulling. But OME only looks up in the first Url, and if not success it rejects the seeking "Cant find stream". I've tried to declare one origin for each Url with the same location but same thing happens, OME only search in the first URL

What I did was to let the stream keys fixed. So I have one origin for each stream key and it worked fine. But the idea is to be able to change the stream keys for each event without modifying the Server.xml file.

Below, my Origins declaration. OME will try to match the stream key only in the first URL. May I have a hint of how to do it? I wouldn't like to have fixed stream keys. In the webpage I have an input to write the stream key in order to let watch the stream to only who has the key.

			<Origins>
				<Origin>
					<Location>/app/</Location>
					<Pass>
						<Scheme>rtsp</Scheme>
						<Urls>
							<Url>10.71.15.20:550/</Url>
							<Url>10.71.15.21:550/</Url>
						  	<Url>10.71.15.22:550/</Url>
							<Url>10.71.15.23:550/</Url>
							<Url>10.71.15.24:550/</Url>
							<Url>10.71.15.25:550/</Url>
							<Url>10.71.15.26:550/</Url>
							<Url>10.71.15.27:550/</Url>
						</Urls>
					</Pass>
				</Origin>
			</Origins>

Thanks a lot in advance!
Bests,

**Comment by getroot** [comment]
RTSP Pulling is still an experimental feature. Only the action for the first URL is still implemented. The second URL is a function that automatically failovers when the first URL fails, but it has not been implemented yet. It will be implemented within this year.

**Comment by nangavar** [comment]
Hi getroot!
Thanks, understood!

So, do you think is there any way to look up within my posible Origins (encoders in my LAN) for a specific stream key?

**Comment by getroot** [comment]
What about the following settings?

<Origins>
	<Origin>
		<Location>/app/20</Location>
		<Pass>
			<Scheme>rtsp</Scheme>
			<Urls>
				<Url>10.71.15.20:550/</Url>
			</Urls>
		</Pass>
	</Origin>
	<Origin>
		<Location>/app/21</Location>
		<Pass>
			<Scheme>rtsp</Scheme>
			<Urls>
				<Url>10.71.15.21:550/</Url>
			</Urls>
		</Pass>
	</Origin>

	...
</Origins>

**Comment by nangavar** [comment]
Hi!
Yeap, this is the way I have it implemented until today, but the stream key on the player side is fixed. Im looking a way, as in RTMP, that only sender and viewer know the stream key without letting it fixed on the server side. But for that I would need that OME checks if the stream key is present in any encoder. 
Maybe, as an idea, if the stream key format is XX/#####, XX may select the encoder and #### act as the stream key, and stream will become active only if #### matches the key on the selected encoder.
I will keep trying. Will let you know if I find a solution.

**Comment by nangavar** [comment]
> RTSP Pulling is still an experimental feature. Only the action for the first URL is still implemented. The second URL is a function that automatically failovers when the first URL fails, but it has not been implemented yet. It will be implemented within this year.

Maybe if OME looks the stream key within the whole pool of URLs, the failover will work fine too. OME will play the first URL that matches the stream key and in case of a failure OME will failover to the second URL that matches the same stream key too. In this way will cover both cases of use. Either just looking up for a stream key, or if there are two sources with the same stream key you will have automatic failover.

**Comment by getroot** [comment]
@nangavar We will also review your comments. Thank you for a good suggestion.

RTSP Pull has been released as beta from 0.10.4. But, MULTIPLE URLs are not yet supported. :-(
