### ISSUE TITLE
Bypass issues with Bframes > 1

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenMediaEngine#130]
I'm very happy with OME and the new Bypass transcoding option. However, when there are more than 1 Bframes it stutters video and makes it unusable. I've tested NodeMediaServer with the same input using Bframes = 3 and WS-FLV worked just fine without any transcoding but it's nowhere near as good as WebRTC.

Is there a way to fix this problem? Do you have plans to fix this known issue? If I transcode with FFmpeg, it works but then the quality suffers and CPU resources lost during the process.

Thank you very much.

**Comment by getroot** [comment]
That is the browser limitation. Most browsers I know of, including Chrome, do not support B-Frame in WebRTC.

**Comment by mpisat** [comment]
I understand, thank you for the explanation. Is it possible to update bypass video transcoding to satisfy this requirement?
For example, bypass if there are no B-frames or only 1 b-frames, and if more than 1 b-frames used, transcode video input using same bitrate (or defined bitrate)

For those who broadcast from WebRTC, it's not a problem but OME doesn't have WebRTC as input as of yet and it would be great if you could support it in the future.

**Comment by getroot** [comment]
Determining the transcoding option based on the existence of a B-Frame is very difficult. That means OME needs to reset all the pipelines in real time when the input changes. Inputs with and without B-Frame can be changed at any time. Transcoding must always be turned on if you cannot control multiple unspecified inputs. In this case, we strongly deliver the message to the broadcaster. Set the "B-Frame" option to 0. B-Frame is one of the biggest causes of increased latency.

**Comment by mpisat** [comment]
I understand. Thank you for the details.
