### ISSUE TITLE
Local reproduction

### ISSUE THREAD

**Issue by enigmathion** [AirenSoft/OvenMediaEngine#131]
Good morning, I have a query, is there a way to work through webrtc broadcast and at the same time that I read videos hosted on the server when I am not broadcasting the stream? Thank you!

**Comment by getroot** [comment]
I can't understand this question. Please ask a specific example.

**Comment by enigmathion** [comment]
The question is: Is it possible for the player to display the obs video and then stop it and continue to output local source videos hosted on the vps?

**Comment by getroot** [comment]
This seems to be a function at the application (Web or App) level, not at the normal server or player level. Make the application work by integrating the player's API.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
