### ISSUE TITLE
Cross compiling OvenMedia engine for custom arm board

### ISSUE THREAD

**Issue by deekshithkv** [AirenSoft/OvenMediaEngine#1310]
Is it possible to cross compile OvenMedia engine open source for custom arm board? or is there any version you provide to do so? If it can be installed in cross platform can you provide the commands/methods to cross compile.

**Comment by getroot** [comment]
This is only a place to post issues.
https://github.com/AirenSoft/OvenMediaEngine/issues/1071

You've already posted on the Discussions board.
