### ISSUE TITLE
Adaptive bitrate streaming for HLS, (LL-)MPEG-DASH

### ISSUE THREAD

**Issue by marcelmeulemans** [AirenSoft/OvenMediaEngine#132]
In the documentation it is mentioned that OME does currently not support adaptive streaming for HLS, MPEG-DASH but that it may be updated soon. Can you give an indication where this is on your list of priorities? Is this a something that will happen this year?

This is probably not a small feature to add, but is it something you would accept pull requests for or other collaboration on?

**Comment by getroot** [comment]
We are almost ready to support ABR on HLS and DASH. It's all done by updating only the last Playlist and Manifest. Perhaps we expect this feature to be updated before the third quarter of this year. (Of course, if there is no urgent issue)

**Comment by marcelmeulemans** [comment]
Thanks for the update!

**Comment by jmartincufre** [comment]
Hello! Is there any change on this? We could really use it!

**Comment by getroot** [comment]
Sorry, this task hasn't been completed yet because of a more urgent task. But we changed the configuration structure for this. If there is an update, I'll comment again here!

**Comment by cub33** [comment]
+1

**Comment by jmartincufre** [comment]
Following on this

**Comment by IanMitchell77** [comment]
Presumably your implementation of WebRTC does do ABR? What is a good way of testing this?

**Comment by kitobelix** [comment]
Hi, still following.

**Comment by kitobelix** [comment]
bump!

**Comment by fcqpl** [comment]
bump :)

**Comment by gregmsanderson** [comment]
This would be good to have

**Comment by techno-club** [comment]
following

**Comment by kitobelix** [comment]
Bump!

**Comment by wastemaster** [comment]
+

**Comment by nums** [comment]
For hls, you can generate adaptive a m3u8 file on your web server with the streams  urls transcoded on ovenmedia

**Comment by getroot** [comment]
Because OME uses the GPL project like the x264 codec, we can't open this project under the LGPL license.

**Comment by kitobelix** [comment]
Shouldn't be a problem though, as using GPL is better to keep the project free.
Are you accepting merge requests?

**Comment by techno-club** [comment]
> For hls, you can generate adaptive a m3u8 file on your web server with the streams urls transcoded on ovenmedia

Can you detail this further?

**Comment by nums** [comment]
@techno-club 

OvernMedia can transcode livestream and generate HLS url like that :

=>Without transcoding :
`https://OVEN_MEDIA_SERVER/app/stream/playlist.m3u8`

=> With transcoding
`https://OVEN_MEDIA_SERVER/app/stream_360p/playlist.m3u8`

To have a HLS stream with ABR, the simple way is to generate your own playlist.m3u8 file on a web server (apache, nginx, express js anything you want), the file looks like this with 2 streams :
> #EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=200000,RESOLUTION=640x360
https://OVEN_MEDIA_SERVER/app/stream_360p/playlist.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2000000,RESOLUTION=1280x720
https://OVEN_MEDIA_SERVER/app/stream/playlist.m3u8

Then you just have to put this url `https://MY_WEB_SERVER/playlist.m3u8` in your HTML5 HLS favorite player

**Comment by genofire** [comment]
It is a nice workaround - but i would like that OVE such ABR HLS Manifests generate it on his own if there are multiple `Video` of `Encodes` in one `OutputProfil`.

**Comment by techno-club** [comment]
> @techno-club
> 
> OvernMedia can transcode livestream and generate HLS url like that :
> 
> =>Without transcoding : `https://OVEN_MEDIA_SERVER/app/stream/playlist.m3u8`
> 
> => With transcoding `https://OVEN_MEDIA_SERVER/app/stream_360p/playlist.m3u8`
> 
> To have a HLS stream with ABR, the simple way is to generate your own playlist.m3u8 file on a web server (apache, nginx, express js anything you want), the file looks like this with 2 streams :
> 
> > #EXTM3U
> > #EXT-X-VERSION:3
> > #EXT-X-STREAM-INF:BANDWIDTH=200000,RESOLUTION=640x360
> > https://OVEN_MEDIA_SERVER/app/stream_360p/playlist.m3u8
> > #EXT-X-STREAM-INF:BANDWIDTH=2000000,RESOLUTION=1280x720
> > https://OVEN_MEDIA_SERVER/app/stream/playlist.m3u8
> 
> Then you just have to put this url `https://MY_WEB_SERVER/playlist.m3u8` in your HTML5 HLS favorite player

Excellent, I will give this a try.  on Wowza, we created a smil file:

<?xml version="1.0" encoding="UTF-8"?>
<smil title="SMIL file for live streaming">
    <body>
        <switch>
            <video height="240" src="myStream_200" systemLanguage="eng" width="424">
                <param name="videoBitrate" value="200000" valuetype="data"></param>
                <param name="audioBitrate" value="44100" valuetype="data"></param>
            </video>
            <video height="360" src="myStream_350" systemLanguage="eng" width="640">
                <param name="videoBitrate" value="350000" valuetype="data"></param>
                <param name="audioBitrate" value="44100" valuetype="data"></param>
            </video>
            <video height="720" src="myStream_700" systemLanguage="eng" width="1272">
                <param name="videoBitrate" value="700000" valuetype="data"></param>
                <param name="audioBitrate" value="44100" valuetype="data"></param>
            </video>
        </switch>
    </body>
</smil>

and it would create the m3u8 file automatically... when you went to this URL:
http://[address]:1935/myApplication/smil:myStream.smil/playlist.m3u8

or you could install a jar file that would do it for you.   I'll implement this until an automatic version is available.

Thanks!

**Comment by techno-club** [comment]
Care to share an example transcoding profile? I just tried to add 2nd Output and OvenMediaEngine won't startup.  I don't see any examples of Server.xml  multiple transcoding profiles.    so for the above m3u8 what would be the associated Server.xml Output?

I tried this:
`                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}_1080p</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                <Audio>
                                                                        <Codec>opus</Codec>
                                                                        <Bitrate>320000</Bitrate>
                                                                        <Samplerate>44100</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>
                                                                
                                                        </Encodes>
                                                <OutputProfile>
                                                        <Name>720p_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}_720p</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Bypass>false</Bypass>
                                                                </Video>
                                                                <Audio>
                                                                        <Codec>opus</Codec>
                                                                        <Bitrate>320000</Bitrate>
                                                                        <Samplerate>44100</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>
                                                                
                                                                <Video>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>3000000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
                                                        
                                                        </Encodes>
                                                </OutputProfile>
`

Anything you see wrong with that?   This is what it's reporting

[root@disko ~]# journalctl -xe
Nov 13 11:16:26 disko OvenMediaEngine[1146]: [2021-11-13 11:16:26.661] E [OvenMediaEngine:1146] OvenMediaEngine | main.cpp:299  | An error occurred while creating daemon
Nov 13 11:16:26 disko systemd[1]: ovenmediaengine.service: control process exited, code=exited status=1
Nov 13 11:16:26 disko systemd[1]: Failed to start OvenMediaEngine.
-- Subject: Unit ovenmediaengine.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit ovenmediaengine.service has failed.
--
-- The result is failed.

=============================

The configuration example doens't provide any transcoding example:
https://airensoft.gitbook.io/ovenmediaengine/configuration#configuration-example

Appreciate it!

Thanks.

**Comment by techno-club** [comment]
I'll answer my own question, you have to create an Output Profile for each transcoded rendition, like this:

						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>aac</Codec>
									<Bitrate>320000</Bitrate>
									<Samplerate>44100</Samplerate>
									<Channel>2</Channel>
								</Audio>
							 	
							</Encodes>
						</OutputProfile>
						
				
					 <OutputProfile>
                                                        <Name>live_720p</Name>
                                                        <OutputStreamName>${OriginStreamName}_720p</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Codec>aac</Codec>
                                                                        <Bitrate>320000</Bitrate>
                                                                        <Samplerate>44100</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>

                                                                <Video>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>1500000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>

                                                        </Encodes>
                                                </OutputProfile>
					        <OutputProfile>
                                                        <Name>live_360p</Name>
                                                        <OutputStreamName>${OriginStreamName}_360p</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Codec>aac</Codec>
                                                                        <Bitrate>256000</Bitrate>
                                                                        <Samplerate>44100</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>

                                                                <Video>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>800000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>640</Width>
                                                                        <Height>360</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>

                                                        </Encodes>
                                                </OutputProfile>
						        <OutputProfile>
                                                        <Name>live_240p</Name>
                                                        <OutputStreamName>${OriginStreamName}_240p</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Codec>aac</Codec>
                                                                        <Bitrate>128000</Bitrate>
                                                                        <Samplerate>44100</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>

                                                                <Video>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>400000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>426</Width>
                                                                        <Height>240</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>

                                                        </Encodes>
                                                </OutputProfile>

**Comment by getroot** [comment]
LLHLS is now supported, and LLHLS supports ABR.

The following issue is for LLHLS.

https://github.com/AirenSoft/OvenMediaEngine/issues/766

For ABR in LLHLS, please refer to the following issues.

https://github.com/AirenSoft/OvenMediaEngine/issues/777

The newly developed LLHLS is superior to DASH and LLDASH in all aspects of compatibility, performance, and functionality, and it also supports legacy HLS players. So we have decided not to update legacy HLS, DASH and LLDASH. Because these dissipate our energy. We will focus on more cool features in the future.

**Comment by getroot** [comment]
Closing this issue now that LLHLS has released ABR. For further discussion of ABR in LLHLS, please visit https://github.com/AirenSoft/OvenMediaEngine/issues/777 or create a new issue.
