### ISSUE TITLE
Soft lock(s?)

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#1325]
Multiple different soft locks, similar to previous bugs we've found. The following screenshot shows both, one after another, the top graph is CPU usage and the bottom graph (orange) is OME memory usage

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/7061721/71c88cfc-5122-4103-b11d-50dfeecd4fb8)

First, on the left. This one which was very odd. CPU usage stayed constant, rather than dropping as usual. Begins around 11:05 on the X axis there, and ends at 15:31. In the logs, 15:05 on 2023-07-20 to 19:31 or so. Ended when we restarted the OME docker instance, no dump file created. We can't rule out the forwarding solution we use to copy streams from nginx-rtmp to OME as the source of the problem, but I think it is unusual.

Second, on the right in that graph, the typical drop to ~0 CPU usage from OME, from ~23:32 to 00:48 (on the 21st), or in the logs, 2023-07-21 03:32 to 04:48 if I've done my math right. Also no dump file, also fixed by us restarting OME

**NOTE THE LOG FILE TIMESTAMPS ARE +4 HOURS FROM THE GRAPH**

Using the airensoft/ovenmediaengine:0.15.12 docker container
[Server.xml](https://gist.github.com/naanlizard/c6c8f5b4940c3eaf47d414e8e89a6412)
[omelogclean.zip](https://github.com/AirenSoft/OvenMediaEngine/files/12137092/omelogclean.zip)

**Comment by getroot** [comment]
Again, thank you very much for finding and reporting hard-to-find issues.

Looking at your logs, it's very clear that the lock is being taken while deleting the LLHLS stream. Unfortunately, we've been diligently reviewing the source code based on your logs for the past two days to find the cause of this problem, but we haven't been able to pinpoint anything definitive yet. We've also scripted an environment similar to yours (creating/deleting RTMP, looping LLHLS multiple session playback) and running it for two days and still haven't been able to reproduce the problem.

Instead, I patched some suspects and added logs to pinpoint them. If you can test and reproduce with the dev version and provide logs, it will really help us find this deeply hidden bug. Thank you so much. 

I will continue to look for the cause of the problem.

**Comment by naanlizard** [comment]
Is it possible to push a release or docker image to the hub to use? I can try updating to master but it seems unreliable, from previous tests (or maybe I am unreliable at updating properly!)

Either way in a few days (monday or tuesday) I should be able to update to master and test for you.

This is the first soft lock in a very long time, so OME is pretty reliable! And such a friendly dev team :)

**Comment by getroot** [comment]
The development version, the master branch, is automatically built whenever a new commit is discovered and uploaded as airensoft/ovenmediaengine:dev tag. You can use the dev tag. thank you so much.

**Comment by naanlizard** [comment]
For some reason I thought dev wasn't usable, but I don't remember why. I'll try it

**Comment by naanlizard** [comment]
A hard crash today with dump!

Trimmed the log file of a lot of lines like 

[37m[2023-07-31 00:39:01.035] I [SPLLHLS-t799:22] HTTP.Server | http_server.cpp:149  | Client(<ClientSocket: 0x7ff3c2522410, #138, Connected, TCP, Nonblocking, {ip redacted}:30514>) is connected on *:799[0m

if you need those, let me know and I can upload the full thing but it was huge so I didn't.

[OMElogtrim.zip](https://github.com/AirenSoft/OvenMediaEngine/files/12210814/OMElogtrim.zip)

**Comment by naanlizard** [comment]
https://i.imgur.com/HgCNuYO.png CPU and memory usage if it is helpful, you can clearly see the restart after the crash

**Comment by getroot** [comment]
This is a dump file that is of great help to me. I have found the cause of the problem. I will fix and commit soon. Thank you very much.

**Comment by getroot** [comment]
We fixed the hard crash issue you reported. And it is presumed that the stopping problem (infinite loop) you reported in the first place was also the same cause. We had a really hard time finding the cause of this problem but your dump file saved us.

You can test with :dev tag. thank you.

**Comment by naanlizard** [comment]
Updated, I'll close the ticket for now and reopen or make a new one if there's another crash
