### ISSUE TITLE
RTMP problems with LYNX encoders "Invalid message is received" rtmp_import_chunk.cpp

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#133]
** Continuing from #127  **

Hi getroot,

I found a problem using LYNX encoders by RTMP. No problems with same encoders by RTSP. So I suppose it is not an encoding issue.

I have a pool of 8 of this encoders wired on my lan that we normally use to stream to Youtube and Facebook, we hadn't any problem with them. With OME they connect well but after a few seconds of play the connection is aborted by OME after a "Invalid message is received: Offset: ####" within rtmp_import_chunk.cpp. Attached a chunk of the log starting with the new rtmp client connection. [RTMP issue LYNX Encoders.log](https://github.com/AirenSoft/OvenMediaEngine/files/4783428/RTMP.issue.LYNX.Encoders.log)

Below will find the website of these FPGA encoders. LYNX is a German brand that is standard for stream to Youtube and others in our industry.
https://www.lynx-technik.com/products/yellobrik/video-conversion/pec-1864-3gbit-sdihdmi-h264-streamer-and-recorder/#

It would be a pleasure to contribute if you want to run a test streaming from an encoder to a server you want in order to analyse what could be happening.  You can send me an email to mravagnan@mediapro.tv and we can arrange a test.

Many thanks again!
Bests, 

The error I get:

[2020-06-15 19:50:44.219] E 18210 RtmpProvider | rtmp_import_chunk.cpp:356  | Invalid message is received: offset: 12899
expected:
========== Memory dump of 0xE2C1B621 (1/1 bytes) ==========
0 | D4                                              | .
but:
========== Memory dump of 0xE2D68E23 (1/1 bytes) ==========
0 | 02                                              | .
[2020-06-15 19:50:44.219] E 18210 RtmpProvider | rtmp_chunk_stream.cpp:411  | An error occurred while parse RTMP data: -1
[2020-06-15 19:50:44.220] E 18210 RtmpProvider | rtmp_server.cpp:204  | An error occurred while process the RTMP packet: [#default#app/test7] (0/102), remote: <ClientSocket: 0x7f3105067810, #37, state: 4, TCP, 10.71.15.26:48036>, Disconnecting...

**Comment by getroot** [comment]
Thank you very much for your contribution.
It seems that the encoder has RTMP messages that we didn't expect. We will fix this soon. To address this, the RTMP developer may request additional information.

**Comment by nangavar** [comment]
Thanks a lot!
Remember, it would be a pleasure if I can help with any test you need.

**Comment by nangavar** [comment]
Hi all!
I have tested three more brands of encoders with RTMP protocol. And all have worked fine! Below the brands I have tested:
- ELEMENTAL LIVE
- ATEME TITAN
- TERADEK

By the moment the only encoder I found problems with RTMP is the LYNX PEC-1864.

**Comment by nangavar** [comment]
Hi!
May I have your recommendation about a cheap SDI RTMP encoder (is just for monitoring purposes) that you have tested to work with OME. Like BlackMagic, or something like that. Latency is mandatory.
We are near to buy some more to use with OME and would be great your recommendation.

Many thanks!

**Comment by getroot** [comment]
In fact, we are only using FFMPEG and OBS. The external equipment we use sends streams through FFMPEG and OBS.

**Comment by getroot** [comment]
Hello. nangavar!

We solved that problem by purchasing a device for this issue at https://github.com/AirenSoft/OvenMediaEngine/issues/161.

I am wondering if the compatibility problem with the LYNX encoder has also been solved. If not, can you stream LYNX to our server when you're okay?

**Comment by nangavar** [comment]
Many Thanks!!!!

Will try and let you know, by the moment OME is on production, so I will have to wait a gap to try.

Of course that it would be a pleasure to tests with our encoder to your servers in case it still failing.

**Comment by nangavar** [comment]
Finally I was able to run the test right now and it is working perfectly!

As always many thanks! you're the best!
I found some other issues but had no time to sit down and open them here. I hope to be able to soon

Many thanks!
