### ISSUE TITLE
SRT not configuring as UDP on ome_docker_launcher.sh

### ISSUE THREAD

**Issue by krisdahl** [AirenSoft/OvenMediaEngine#1339]
**Describe the bug**
First off, the ome_docker_launcher is really cool.

But in my configuration it parses my config file and picks up my SRT port (9999).  However, it doesn't look like the parser sets up everything as TCP, and launches the docker image with 9999 instead of 9999/udp.

**To Reproduce**
1. Set Server.xml as follows under Bind -> Providers

```
<SRT>
                                <Port>${env:OME_SRT_PROV_PORT:9999}</Port>
                                <WorkerCount>1</WorkerCount>
                        </SRT>
```
3. Run ome_docker_launcher.sh
4. This is what container ports are configured 

`137e66614a59   airensoft/ovenmediaengine:latest   "/opt/ovenmediaengin…"   13 seconds ago   Up 11 seconds   0.0.0.0:1935->1935/tcp, :::1935->1935/tcp, 0.0.0.0:3333-3334->3333-3334/tcp, :::3333-3334->3333-3334/tcp, 80/tcp, 0.0.0.0:3478->3478/tcp, :::3478->3478/tcp, 8080/tcp, 0.0.0.0:8081->8081/tcp, :::8081->8081/tcp, 0.0.0.0:9000->9000/tcp, :::9000->9000/tcp, 4000-4005/udp, 0.0.0.0:9999->9999/tcp, :::9999->9999/tcp, 8090/tcp, 0.0.0.0:20080->20080/tcp, :::20080->20080/tcp, 10005-10010/udp, 0.0.0.0:10000-10004->10000-10004/udp, :::10000-10004->10000-10004/udp   ovenemediaengine`

**Expected behavior**
It should have picked up that SRT protocol would be UDP.  The documentation uses "${env:OME_SRT_PROV_PORT:9999}" as the example setup.   The docker script however needs it to be in "${env:OME_SRT_PROV_PORT:9999/udp}"

**Logs**
Debug log included

[log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/12318053/log.txt)

**Comment by dimiden** [comment]
Thank you for the bug report!
As you mentioned, some Providers/Publishers should default to UDP when no protocol is specified. Currently, it's using TCP which will be fixed soon.

**Comment by dimiden** [comment]
@krisdahl 
I've just fixed the issue where the SRT port was being opened as TCP. Additionally, I've also addressed the problem where it wasn't working when specifying multiple port ranges. https://github.com/AirenSoft/OvenMediaEngine/commit/5cbceacd2b28c5104e01973e11b1ee27e8ebb6c8

**Comment by krisdahl** [comment]
@dimiden thanks for the hard work!
