### ISSUE TITLE
The video stopped, so I checked the log.  [Epoll] EPOLLIN | EPOLLERR | EPOLLHUP | EPOLLRDHUP (-1)

### ISSUE THREAD

**Issue by kkwangeun** [AirenSoft/OvenMediaEngine#137]
Hello~

The video stopped, so I checked the log.

If you restart the server !!  It is normal again

error ~
 **[0x7f5175eca890] [#23] [Epoll] EPOLLIN | EPOLLERR | EPOLLHUP | EPOLLRDHUP (-1)**

and 

***** Crash dump *****
OvenMediaEngine v0.10.1 (pid: 16206, tid: 16331)
Signal 11 (SIGSEGV) 2020-06-25T09:28:35-0700
#0   /lib/x86_64-linux-gnu/libpthread.so.0 0x7f517a268890 ? + 0x12890
#1   /opt/ovenmediaengine/lib/libavcodec.so.57 0x7f51797083e8 ? + 0x16e3e8
#2   /opt/ovenmediaengine/lib/libavcodec.so.57 0x7f51796661bc ? + 0xcc1bc
#3   /opt/ovenmediaengine/lib/libavcodec.so.57 0x7f5179666e8d ? + 0xcce8d
#4   /opt/ovenmediaengine/lib/libavcodec.so.57 0x7f5179701741 ? + 0xc1
#5   /usr/bin/OvenMediaEngine            0x556a57a268e3 ? + 0x13c8e3
#6   /usr/bin/OvenMediaEngine            0x556a57a1c871 ? + 0x132871
#7   /usr/bin/OvenMediaEngine            0x556a57a1d3d0 ? + 0x1333d0
#8   /usr/lib/x86_64-linux-gnu/libstdc++.so.6 0x7f51780556df ? + 0xbd6df
#9   /lib/x86_64-linux-gnu/libpthread.so.0 0x7f517a25d6db ? + 0x76db
#10  /lib/x86_64-linux-gnu/libc.so.6     0x7f517771288f ? + 0x3f

os : ubuntu 18.0

**Comment by getroot** [comment]
To analyze the problem, we need the full log and your SERVER.XML. And you need to know what version of OME you are using. (Are you using a master branch?)
And if possible, attaching the crash log generated after running OME in debug mode will help us more.

**Comment by kkwangeun** [comment]
OME version is 0.10.2


server.xml 

<?xml version="1.0" encoding="UTF-8" ?>

<Server version="6">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>

	
	<Bind>
		<Providers>
			<RTMP>
				<Port>1935</Port>
			</RTMP>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
			</OVT>
			<HLS>
				<Port>80</Port>
				
				
			</HLS>
			<DASH>
				<Port>80</Port>
				
				
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Domain>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Domain>
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<Encodes>
					      <Encode>
					            <Name>HD</Name>
					            <Audio>
					                 <Codec>aac</Codec>
					                 <Bitrate>64000</Bitrate>
					                 <Samplerate>48000</Samplerate>
					                 <Channel>2</Channel>
					             </Audio>
					             <Video>
					                 <Codec>h264</Codec>
					                 <Width>1280</Width>
					                 <Height>720</Height>
					                 <Bitrate>2000000</Bitrate>
					                <Framerate>30.0</Framerate>
					             </Video>
					      </Encode>

					    <Encode>
					            <Name>SD</Name>
					            <Audio>
					                 <Codec>aac</Codec>
					                 <Bitrate>64000</Bitrate>
					                 <Samplerate>48000</Samplerate>
					                 <Channel>2</Channel>
					             </Audio>
					             <Video>
					                 <Codec>h264</Codec>
					                 <Width>720</Width>
					                 <Height>360</Height>
					                 <Bitrate>1000000</Bitrate>
					                <Framerate>30.0</Framerate>
					             </Video>
					      </Encode>
					</Encodes>

					<Streams>
						<Stream>
							<Name>${OriginStreamName}_hd</Name>
							<Profiles>
								<Profile>HD</Profile>
							</Profiles>
						</Stream>


						<Stream>
    					<Name>${OriginStreamName}_sd</Name>
    					<Profiles>
        				<Profile>SD</Profile>
    					</Profiles>
						</Stream>
				</Streams>


					<Providers>
						<OVT />
						<RTMP />
						<RTSPPull />
					</Providers>
					<Publishers>
						<ThreadCount>4</ThreadCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>


log
--------
http://45.58.2.146/oven_log.log

**Comment by kkwangeun** [comment]
I did it with the master branch version .
It seems to be okay !! 
thank you~
