### ISSUE TITLE
WebRTC H264 playback issues

### ISSUE THREAD

**Issue by burakguder** [AirenSoft/OvenMediaEngine#138]
When transcoded with V8 codec, the system runs fluently on all devices  but when it doesn't transcode the broadcast from rtmp, oven player fails to play the H264 live stream in all browsers

**Comment by getroot** [comment]
It may be that the input h.264 codec is not browser compatible.

If you are using OBS, please refer to the article below. Browsers may not support B-frame or too high level of h.264.
https://airensoft.gitbook.io/ovenmediaengine/getting-started#hello-ultra-low-latency-streaming

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
