### ISSUE TITLE
Bitrates changes are not detected

### ISSUE THREAD

**Issue by hardcpp** [AirenSoft/OvenMediaEngine#1380]
How to reproduce:
Start a stream with 8000kbps as video bitrate
Few seconds later change it to 9000 kbps

The REST route http://192.168.10.1:8081/v1/vhosts/default/apps/app/streams/STREAM_NAME still report start bitrate in the input section

**Comment by hardcpp** [comment]
For context, i'm streamming using RTMP protocol

**Comment by getroot** [comment]
In the case of RTMP, bitrate information is received as metadata upon initial connection. And we keep using it. This is the intended implementation.

**Comment by hardcpp** [comment]
thanks for the reply, then in that case could we just look the troughpout on the incomming socket? because right now, anyone can override a bandwidth limit

**Comment by hardcpp** [comment]
Also i noticed something else weird about metadata

- Make a rtmp stream at 1080p**60** to a OME instance
- From the OME  instance receiving the stream push it using rtmp still to any OME instance (can be self)

The pushed stream will appear as 1080p**30** but with the corect bitrate

**Comment by basisbit** [comment]
You could try using the [alert feature](https://airensoft.gitbook.io/ovenmediaengine/alert) to get notified when the bitrate limit is surpassed and then do the api call to disconnect the streamer. However beware of it sometimes being a bit spammy with alerts flapping between okay and not-okay-state, even when OBS is set to CBR.

**Comment by hardcpp** [comment]
That doesn't work if you apply different bandwidth limit to different users

**Comment by basisbit** [comment]
Maybe have it always alert, and then use the reported value in your external application to decide if it is within allowed limits or not?

**Comment by getroot** [comment]
I will look into this further and see if there are any improvements.
