### ISSUE TITLE
Docker Container Crashes with "Could not find track info for track ID 2" Error for Some RTSP Streams

### ISSUE THREAD

**Issue by dongeorge77** [AirenSoft/OvenMediaEngine#1394]
Description
-------------
I am using the OvenMediaEngine within a Docker container, and I've encountered a problem when creating multiple RTSP streams using the API (nearly 20 RTP streams). Specifically, when I try to play some of these streams, I receive a "Could not find track info for track ID 2" error, and eventually, the Docker container crashes.

Steps to Reproduce
---------------------
1. Start OvenMediaEngine in a Docker container.
2. Use the API to create multiple RTSP streams with different names and URLs.
3. Attempt to play some of these streams.

Expected Behavior
--------------------
1. All RTSP streams should play without errors, as they can be streamed successfully using VLC media player.

Actual Behavior
-----------------
1. Some RTSP streams generate a "Could not find track info for track ID 2" error, leading to the Docker container crashing.

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/47071838/9f631e3b-4319-4594-aaaf-9160431fcdec)

Please let me know if there is any additional information or logs required to investigate and resolve this issue.

**Comment by getroot** [comment]
Thanks for the report.
1. Which version of OvenMediaEngine are you using?
2. Full logs are helpful for analysis.
3. Please provide the RTSP URL to help with analysis. (If you cannot disclose it, please send it to support@airensoft.com.)

**Comment by dongeorge77** [comment]
OvenMediaEngine version: 0.15.16

Sorry @getroot , I can not provide a complete log file since it contains potential RTSP URLs.

Attaching some of the log screenshots below,

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/47071838/0d2466d3-c173-4cd1-bf0a-ed9feaa56e5d)

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/47071838/3f41106a-ddc5-4548-bcf1-ab7a29f29157)

![image](https://github.com/AirenSoft/OvenMediaEngine/assets/47071838/f3d29473-e79c-4ad5-8e65-5dfd47672dfb)

**Comment by getroot** [comment]
I cannot reproduce this issue, so if you could provide the RTSP URL, we can help resolve the problem. Would you be able to provide your RTSP URL to [support@airensoft.com](mailto:support@airensoft.com)?

Additionally, there should be a crash log file located in the directory where OvenMediaEngine binary is (`/opt/ovenmediaengine/bin`). Providing that would be helpful.

**Comment by getroot** [comment]
Is it impossible to provide an RTSP URL?

The message "Could not find track info for track ID 2" is not a clue. This is a log that occurs because the RTSP server is not sending data on the initially agreed channel, and it is not the cause of the crash. Furthermore, this log is unrelated to the publisher (playback) and is specific to the RTSP input. Therefore, I cannot analyze this issue further based on the logs you provided.

It is suspected that the crash is occurring elsewhere, and to analyze it, I need access to your RTSP server. Therefore, I require your RTSP access permissions.

Also, could you please specify whether you are attempting to play using WebRTC or LLHLS?

**Comment by dongeorge77** [comment]
During the time when the server crashed, there was no WebRTC streaming taking place.

please note that, The server didn't crash because of a single stream failure; it crashed due to multiple stream failures. This led to a situation where the container became chocked and eventually crashed. I observed this by using **htop** within the container, and I noticed a significant number of processes being created, which likely contributed to the issue.

**Comment by the-real-rusty-shackleford** [comment]
I have seen this happen for IP cameras that have audio enabled, but that are using the `G.711` codec, which is a common codec for IP cameras. This codec is not currently supported by OvenMediaEngine.

For some camera brands, I was able to disable audio or change the codec to AAC and the errors went away. For others, I could not disable audio or change the codec and so my logs are flooded with that error message every few milliseconds... it would be nice if there were a way to prevent that. Perhaps an option to ignore audio tracks for an incoming stream. I saw there was a PR for this (#1246) but it was rejected. Or maybe OME could detect the codec and if it's unsupported, it could ignore the track.

@dongeorge77 Which audio codecs do your streams use?

**Comment by getroot** [comment]
@the-real-rusty-shackleford Thank you for providing good information.
The ability to reject unsupported codecs is already included in the code, but if it doesn't work, it's a bug. I will check it out.

#1246 is a function that disables the entire audio, and I will check whether the function that rejects unsupported codec is working properly.

**Comment by getroot** [comment]
@the-real-rusty-shackleford 
This is a really great bug report. I will resolve this issue soon. thank you

**Comment by the-real-rusty-shackleford** [comment]
Bump.

**Comment by getroot** [comment]
@the-real-rusty-shackleford 
I improved it so that unsupported codecs are not negotiated during the rtsp nego process. You can test it with the latest master branch. thank you.

**Comment by getroot** [comment]
This patch made it into the 0.16.5 release. If the issue reproduces, please reopen the issue. Thank you.
