### ISSUE TITLE
Following the "Getting started" documentation yields error message

### ISSUE THREAD

**Issue by Bjorn-Slettemark** [AirenSoft/OvenMediaEngine#1400]
**Describe the bug**
https://airensoft.gitbook.io/ovenmediaengine/getting-started

Installing depencies in the documentation have a typo: 
curl -LOJ https://github.com/AirenSoft/OvenMediaEngine/archive/v0.15.16.tar.gz && \
tar xvfz OvenMediaEngine-0.15.16.tar.gz && \
**_OvenMediaEngine-0.15.14/misc/prerequisites.sh_**

I had to run: 
chmod +x OvenMediaEngine-0.15.16/misc/prerequisites.sh

Then:
./OvenMediaEngine-0.15.16/misc/prerequisites.sh

**Logs**
N/A

**Comment by getroot** [comment]
Thank you
