### ISSUE TITLE
SRT support from OME Pulisher for sending OBS low latency

### ISSUE THREAD

**Issue by alex-jhones** [AirenSoft/OvenMediaEngine#141]
Hello !
SRT support has started in OBS. I wonder if OME is interested in adding Publisher's SRT.

https://obsproject.com/wiki/Streaming-With-SRT-Protocol

**Comment by getroot** [comment]
We are interested in enabling SRT input.
When we complete our high priority task, we will work on it next.

**Comment by nxtreaming** [comment]
What's your high priority task list?

I am interested in it and want to contribute to your project.

**Comment by getroot** [comment]
Below is our future plan.
We most want to reproduce the crash in various environments and get a PR for its solution.

- REST API (Statistics, Manage application, and so on)
- Support HEVC
- File Publisher for recording
- Signed URL
- RTMP push publisher for retransmission to social media services
- PhysicalPort performance improvement
- Test and increase the maximum number of simultaneous viewers
- Test and increase the maximum number of streams
**- Increased stability (stress test and crash bug fix)**

Thank you very much.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
