### ISSUE TITLE
Install FFMPEG err

### ISSUE THREAD

**Issue by jys923** [AirenSoft/OvenMediaEngine#143]
Install FFMPEG
`PREFIX=/opt/ovenmediaengine && \
FFMPEG_VERSION=3.4.2 && \
DIR=/tmp/ffmpeg && \
mkdir -p ${DIR} && \
cd ${DIR} && \
curl -sLf https://www.ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz | tar -xz --strip-components=1 && \
PKG_CONFIG_PATH="/opt/ovenmediaengine/lib/pkgconfig" ./configure \
--prefix="${PREFIX}" \
--enable-gpl \
--enable-nonfree \
--extra-cflags="-I${PREFIX}/include"  \
--extra-ldflags="-L${PREFIX}/lib -Wl,-rpath,${PREFIX}/lib" \
 --extra-libs=-ldl \
--enable-shared \
--disable-static \
--disable-debug \
--disable-doc \
--disable-programs \
--disable-avdevice --disable-dct --disable-dwt --disable-error-resilience --disable-lsp --disable-lzo --disable-rdft --disable-faan --disable-pixelutils \
--disable-everything \
--enable-zlib --enable-libopus --enable-libvpx --enable-libfdk_aac --enable-libx264 \
--enable-encoder=libvpx_vp8,libvpx_vp9,libopus,libfdk_aac,libx264 \
--enable-decoder=aac,aac_latm,aac_fixed,h264 \
--enable-parser=aac,aac_latm,aac_fixed,h264 \
--enable-filter=asetnsamples,aresample,aformat,channelmap,channelsplit,scale,transpose,fps,settb,asettb && \
make -j 4 && \
sudo make install && \
sudo rm -rf ${PREFIX}/share && \
rm -rf ${DIR}`

https://www.ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz

**Comment by getroot** [comment]
Please provide details of the platform on which you installed OME, installation instructions, and error messages.

**Comment by jys923** [comment]
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting
Install FFMPEG
FFMPEG_VERSION=3.4.2 && \
curl -sLf https://github.com/AirenSoft/FFmpeg/archive/ome/${FFMPEG_VERSION}.tar.gz | tar -xz --strip-components=1 && \

FFMPEG_VERSION=3.4.7 && \
curl -sLf https://github.com/AirenSoft/FFmpeg/archive/ov${FFMPEG_VERSION}.tar.gz | tar -xz --strip-components=1 && \

Install JEMALLOC
PREFIX=/opt/ovenmediaengine && \
JEMALLOC_VERSION=5.2.1 && \
DIR=${TEMP_PATH}/jemalloc && \

DIR=/tmp/jemalloc && \

**Comment by getroot** [comment]
So what is the error message?

**Comment by jys923** [comment]
https://github.com/AirenSoft/FFmpeg/archive/ome/3.4.2.tar.gz
expire

**Comment by getroot** [comment]
https://www.ffmpeg.org/releases/ffmpeg-3.4.2.tar.gz
or
https://github.com/AirenSoft/FFmpeg/archive/ome/3.4.tar.gz
