### ISSUE TITLE
Troubleshooting / Linux perfs tuning sysctl conflicting element

### ISSUE THREAD

**Issue by zguig52** [AirenSoft/OvenMediaEngine#1438]
**Describe the bug**
On the documentation page Troubleshooting, some advices are given to improve throughput:
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting
==> Section 5-2. Tuning your Linux kernel
The parameter net.ipv4.tcp_max_syn_backlog is present twice with different values:
```
[...]
net.ipv4.tcp_max_syn_backlog = 3240000
[...]
net.ipv4.tcp_max_syn_backlog = 30000
[...]
```

**To Reproduce**
N/A

**Expected behavior**
Wich value is the best? The bigger or the smallest?

**Logs**
N/A

**Server (please complete the following information):**
N/A

**Player (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by getroot** [comment]
Thanks, I'll update this in the documentation.
