### ISSUE TITLE
Push Publishing timeouts delaying pushes API

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1443]
**Describe the bug**
If a push publisher encounters a timeout-related error (i.e. endpoint does not exist), it seems to take two different behaviours. With SRT it will simply fail and not begin pushing. However with RTMP it will keep trying to connect every 5 seconds, indefinitely. During this reconnection time API responses appear to be stuck for the ":pushes" endpoint e.g. v1/vhosts/default/apps/live:pushes

**To Reproduce**
Try pushing RTMP to a non-existent endpoint, then send many requests to the pushes API and you should be able to reproduce the delay.

**Expected behavior**
API responses should not be delayed.

**Logs**
First I started a successful push to SRT, then an unsuccessful push to SRT which stopped and removed itself from the :pushes endpoint, then finally an unsuccessful push to RTMP which caused the API delay issue:
[filtered_log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/13367394/filtered_log.txt)

**Server (please complete the following information):**
Tested in Docker on macOS but reproduced elsewhere.

**Additional context**
There are possibly other related issues with the API response time but I was not able to immediately reproduce those on other endpoints, so :pushes is probably a good place to look first.

**Comment by Keukhan** [comment]
@bchah , it’s been a while. how are you?  I have been busy these days. i have been late in checking issues.  requesting a recoonect every 5 seconds in rtmp push is the  intended policy. 
It seems that the :pushes response was delayed due to the synchronization code at the moment of rtmp push reconnection. I will reproduce it and patch it. i will let you know when the patch is done. 

Thank you for reporting. Always be happy.

**Comment by Keukhan** [comment]
https://github.com/AirenSoft/OvenMediaEngine/compare/ed9acb52a72c...001c8da81726


@bchah  Fixed an issue where a delay occurred when using the Pushes action API. It has been patched in the master branch and will be reflected in the next release. happy new year :)

**Comment by bchah** [comment]
@Keukhan it is a holiday miracle! We now have 5 more seconds of life to enjoy every time we call the pushes API, since we don't have to wait anymore :) Thank you for the patch and happy new year!! 🥳
