### ISSUE TITLE
Safari playback issues when switching tabs

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1446]
**Describe the bug**
Hello! For a couple of years now there has been a problem playing back streams over WebRTC in Safari. If you minimize the window, switch to another tab, or background the browser in some other way, playback begins to stutter badly and only recovers if you reload the stream or the page itself.

**To Reproduce**
1. Start any stream playing back in Safari browser
2. Move to another tab and wait 1 minute (quick switches don't seem to trigger the problem)
3. Switch back to the original tab and you should see the video start to stutter on every keyframe

**Expected behavior**
Video playback should continue smoothly.

**Logs**
Not including logs yet as this has been reproducible on all versions and configurations of OME / OvenPlayer since 2021. If there are particular tests I can run to help troubleshooting, I will be happy to provide logs from those tests.

**Server (please complete the following information):**
 - OS: All
 - OvenMediaEngine Version: All

**Player (please complete the following information):**
 - Device: Mac
 - OS: any recent version of macOS
 - Browser: any recent version of Safari

**Additional context**
I am posting this here because it may not be an OvenPlayer issue exclusively. I have been working around the issue in my application by re-connecting the stream when the user returns to the page in Safari, but it is not ideal.

**Comment by naanlizard** [comment]
Can confirm, just tested on our implementation

I also notice a similar problem but not quite as frequent (every third keyframe or so, kf int 2s) on chrome on my macbook

**Comment by getroot** [comment]
I don't think this is something that can be solved on the OvenMediaEngine side. But I will look into this from many angles.
