### ISSUE TITLE
Installation Dependacy issue in Centos7

### ISSUE THREAD

**Issue by BubbaSWalter** [AirenSoft/OvenMediaEngine#146]
**Describe the bug**
When trying to install the dependencies for OME

I get this issue

ERROR You need to update rpm to handle:
rpmlib(PayloadIsZstd) <= 5.4.18-1 is needed by nasm-2.15.02-0.fc31.x86_64
RPM needs to be updated

Installing on CentOS7 Core

**Comment by getroot** [comment]
We also noticed this problem a while ago. It seems that something has changed on the CentOS side. The way to solve this now is to download and install the source code of nasm, except yum install nasm in prerequisites.sh.

For nasm installation, refer to the following URL.
http://www.linuxfromscratch.org/blfs/view/svn/general/nasm.html

We will solve this problem quickly.

**Comment by getroot** [comment]
The 0171ee4b81cd0de4ce235e5712fc5acaf05dc480 commit resolved this issue. Let me know if your problem continues to reproduce.
