### ISSUE TITLE
Can't start OME with <P2P> configured

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1466]
**Describe the bug**
If you have P2P enabled in your server configuration, OME will not start up:

```
[2023-11-29 22:06:03.913] I [OvenMediaEngine:498] Config | config_manager.cpp:239  | Trying to set logfile in directory... (/log/engine)
[2023-11-29 22:06:03.914] E [OvenMediaEngine:498] OvenMediaEngine | main.cpp:293  | An error occurred while load config: [Config] Unknown item found: Server.P2P in /opt/ovenmediaengine/bin/conf/Server.xml
```

I haven't tested this feature in a while but it worked well in the past.

**Comment by getroot** [comment]
This feature hasn't been tested in a very long time. I'll take a look soon. Thank you

**Comment by getroot** [comment]
I haven't tested it yet, but P2P config was moved here. Could you modify your Server.xml to `<Server><Modules><P2P>`

https://github.com/AirenSoft/OvenMediaEngine/blob/594c55580cd2443cbe3d1bc2915dc2dc7f53fa72/misc/conf_examples/Server.xml#L33

**Comment by bchah** [comment]
Thank you @getroot, that prevents the crashing. I notice that with the feature enabled, the websocket connection is established but no messages are exchanged. The logs show these clues while the P2P negotiation is attempted:

```
W [SPICE-t10010:7337] ICE | ice_port.cpp:690  | Could not find agent() information. Dropping... [Packet type : DTLS GateType : SEND_INDICATION]
W [DQICETmout:7334] ICE | ice_port.cpp:527  | Agent [Unknow, 0] has expired
```

Does this give a good clue? I can dive deeper as needed 🤓

**Comment by getroot** [comment]
I actually have my mind turned off from the p2p traffic distribution feature (experimental feature). First, I'll put reviving the existing p2p functionality on the backlog and look into it when I have time.
Are you planning to apply this to your service?

**Comment by bchah** [comment]
Thank you @getroot - it is not a high priority, I just discovered it during some routine testing. However it would be an interesting option to enable for users with constrained networks, since it works like magic with not much change to the config.
