### ISSUE TITLE
TLS Port issue

### ISSUE THREAD

**Issue by BubbaSWalter** [AirenSoft/OvenMediaEngine#147]
When trying to start OME I get this error.

Jul 14 09:10:27 localhost.localdomain systemd[1]: Starting OvenMediaEngine...
Jul 14 09:10:27 localhost.localdomain OvenMediaEngine[27832]: [2020-07-14 09:10:27.355] E 27833 Config | item.cpp:346  | Unknown configuration found: <Server>.<Bind>.<Publishers>.<WebRTC>.<Signalling>.<TLSPort>
Jul 14 09:10:27 localhost.localdomain OvenMediaEngine[27832]: [2020-07-14 09:10:27.355] E 27833 OvenMediaEngine | main.cpp:313  | An error occurred while load config
Jul 14 09:10:27 localhost.localdomain OvenMediaEngine[27832]: [2020-07-14 09:10:27.356] E 27832 OvenMediaEngine | main.cpp:298  | An error occurred while creating daemon
Jul 14 09:10:27 localhost.localdomain systemd[1]: ovenmediaengine.service: control process exited, code=exited status=1
Jul 14 09:10:27 localhost.localdomain systemd[1]: Failed to start OvenMediaEngine.
Jul 14 09:10:27 localhost.localdomain systemd[1]: Unit ovenmediaengine.service entered failed state.
Jul 14 09:10:27 localhost.localdomain systemd[1]: ovenmediaengine.service failed.

<?xml version="1.0" encoding="UTF-8" ?>

<Server version="7">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>

	
	<Bind>
		<Providers>
			<RTMP>
				<Port>1936</Port>
			</RTMP>
			<MPEGTS>
				
				<Port>4000-4001,4004,4005/udp</Port>
			</MPEGTS>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
			</OVT>
			<HLS>
				<Port>82</Port>
				
				
			</HLS>
			<DASH>
				<Port>82</Port>
				
				
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					<TLSPort>3334</TLSPort>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Domain>
				<Names>
					<Name>stream.wizardsrwe.com</Name>
				</Names>
				<TLS>
					<CertPath>/etc/letsencrypt/live/stream.wizardsrwe.com/cert.pem</CertPath>
					<KeyPath>/etc/letsencrypt/live/stream.wizardsrwe.com/privkey.pem</KeyPath>
					<ChainCertPath>/etc/letsencrypt/live/stream.wizardsrwe.com/fullchain.pem</ChainCertPath>
				</TLS>
			</Domain>
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<Encodes>
						<Encode>
							<Name>bypass</Name>
							<Audio>
								<Bypass>true</Bypass>
							</Audio>
							<Video>
								<Bypass>true</Bypass>
							</Video>
						</Encode>
						<Encode>
							<Name>opus</Name>
							<Audio>
								<Codec>opus</Codec>
								<Bitrate>128000</Bitrate>
								<Samplerate>48000</Samplerate>
								<Channel>2</Channel>
							</Audio>
						</Encode>
					</Encodes>
					<Streams>
						<Stream>
							<Name>${OriginStreamName}</Name>
							<Profiles>
								<Profile>bypass</Profile>
								<Profile>opus</Profile>
							</Profiles>
						</Stream>
					</Streams>
					<Providers>
						<RTMP />
					</Providers>
					<Publishers>
						<RTMP />
						<ThreadCount>4</ThreadCount>
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by getroot** [comment]
Please refer this URL, it is knwon issue, we will fix it soon
https://github.com/AirenSoft/OvenMediaEngine/issues/144#issuecomment-657977851

**Comment by getroot** [comment]
Fixed in version 0.10.5.
