### ISSUE TITLE
Origin OME does not pull from RTSP provider when an OVT edge requires a stream

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#148]
Hi all!

Testing Origin-Edge configuration I found that if a stream is required from edge to origin, the origin does not try to pull from RTSP provider. So the stream will be delivered from origin to edge only if the stream is active at origin (for example if a viewer is watching that stream).

Conf seems to be ok, the system works when the stream at origin is active.

Any idea? Im not using RTMP provider since there is a bug with my RTMP encoders (#133)

My setup:
Encoders (RTSP) --> Origin OME Server --> OVT (VPN) --> Edge OME Server (Cloud Server) --> WebRTC Viewers

Version: 0.10.4
Many thanks in advance! :)

**Comment by getroot** [comment]
This is the "Origin-Origin-Edge" configuration.
This will only work if we upgrade OVT Publisher.
We will work on this with high priority.

Thanks for the suggestion.

**Comment by getroot** [comment]
26f0772a81bc46244ca936551914f46e46aa1341

I have completed this function and committed it. Check it out.

**Comment by nangavar** [comment]
Wow! 
MANY thanks! Will try and let you know!
You are the best guys! :)

**Comment by nangavar** [comment]
Origin-Origin-Edge is working perfectly! 

Thanks a lot1 You're the best!
I will close this issue!

**Comment by nangavar** [comment]
Hi all!
I'm reopening this issue, because I found that if a RTSP-Pull stream at origin is opened by a OVT edge, this stream is deleted after 60sec by origin so edge stops playing. In other words the stream at Edge does not persist if it is created through a OVT edge, it will be deleted.
I think that the modification of issue #150 is related with the problem. Im running master branch at both sides. I don't remember to have this problem before with 0.10.4 or 0.10.5

**Comment by getroot** [comment]
I fixed this. (a3f7824554f741a4e75b6ac5a1c83c7f6eb7e5ec)

Test with the master branch.

When playing from edge to "(rtsp)-origin-(ovt)-edge" structure, origin pulls rtsp and provides it as ovt. The stream is not deleted while playing continues at the edge. If there are 0 viewers on the edge, the stream is deleted from the edge after 60 seconds. And again, after 60 seconds, the stream is deleted from origin.

**Comment by nangavar** [comment]
Hello Getroot!
Sorry for my delay.
Now it is OK, both are closing connections well. And the origin relay edge is working fine too.

Many thanks!
