### ISSUE TITLE
Oven Media Engine not starting , Build using Dockerfile.cuda.local to enable hardware acceleration

### ISSUE THREAD

**Issue by chandrashekar-nallamilli** [AirenSoft/OvenMediaEngine#1508]
**Describe the bug**
I am using srt ingest to webrtc playback on ovenmedia  using docker . Trying to enable Hardware acceleration 

**To Reproduce**
1. Set Server.xml as follows '<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	<Type>origin</Type>
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>
	<StunServer>stun.ovenmediaengine.com:13478</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>false</Enable>
		</LLHLS>
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		<Managers>
			<API>
				<Port>${env:OME_API_PORT:8081}</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>
		<Providers>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
				<WorkerCount>2</WorkerCount>
			</SRT>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_WEBRTC_SIGNALLING_PORT:3333}</Port>
					<TLSPort>${env:OME_WEBRTC_SIGNALLING_TLS_PORT:3334}</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>${env:OME_HOST_IP:*}:${env:OME_WEBRTC_CANDIDATE_PORT:10000-10004/udp}</IceCandidate>
					<TcpRelay>${env:OME_HOST_IP:*}:${env:OME_WEBRTC_TCP_RELAY_PORT:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_WEBRTC_SIGNALLING_PORT:3333}</Port>
					<TLSPort>${env:OME_WEBRTC_SIGNALLING_TLS_PORT:3334}</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>${env:OME_WEBRTC_CANDIDATE_IP:*}:${env:OME_WEBRTC_CANDIDATE_PORT:10000-10004/udp}</IceCandidate>
					<TcpRelay>${env:OME_WEBRTC_CANDIDATE_IP:*}:${env:OME_WEBRTC_TCP_RELAY_PORT:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>
	<Managers>
		<API>
			<AccessToken>Demo</AccessToken>
		</API>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
		</Host>
	</Managers>
	<VirtualHosts>
		<VirtualHost>
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<HWAccels>
							<Decoder>
									<Enable>true</Enable>
									<Modules>nv</Modules>
							</Decoder>
							<Encoder>
									<Enable>true</Enable>
									<Modules>nv</Modules>
							</Encoder>
						</HWAccels>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>

							<Encodes>
								<Video>
									<Name>bypass_video</Name>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Name>aac_audio</Name>
									<Codec>aac</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
									<BypassIfMatch>
										<Codec>eq</Codec>
									</BypassIfMatch>
								</Audio>								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<WebRTC>
							<Timeout>30000</Timeout>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</WebRTC>
						<SRT />
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
'
2. With Encoder 'Vmix [e.g. Use OBS Version] 
3. See error

**Expected behavior**
The gpu should be used for hardware acceleration but i cant start the images 

**Logs**
/opt/ovenmediaengine/bin/OvenMediaEngine: error while loading shared libraries: libnppig.so.11: cannot open shared object file: No such file or directory
/opt/ovenmediaengine/bin/OvenMediaEngine: error while loading shared libraries: libnppig.so.11: cannot open shared object file: No such file or directory
/opt/ovenmediaengine/bin/OvenMediaEngine: error while loading shared libraries: libnppig.so.11: cannot open shared object file: No such file or directory

**Server (please complete the following information):**
 - OvenMediaEngine Version: [e.g. v0.10.1]
 - Branch: [e.g. dev]

**Player (please complete the following information):**
 - Docker 23.0.4, build f480fb1 on Ubuntu 22.04.2 LTS

**Comment by d-uzlov** [comment]
I also see this error.

My system specs:

- OS: Debian 12
- `Linux p40 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux`
- Nvidia driver version: 545.23.08
- CUDA version: 12.3
- GPU: NVIDIA Tesla P40
- OvenMediaENgine version: 1.16.4

I built the container like this:

```bash
docker build https://github.com/AirenSoft/OvenMediaEngine/raw/v0.16.4/Dockerfile.cuda \
    --build-arg OME_VERSION=v0.16.4 \
    -t docker.io/$docker_username/$docker_repo:ome-official-v0.16.4-cuda11
```

I also see that my system doesn't have `libnppig.so.11` anywhere, but there is `/usr/local/cuda-12.3/targets/x86_64-linux/lib/libnppig.so.12`.
So I tried building the container with CUDA 12 (I modified the Dockerfile to use CUDA 12.2.0 instead of 11.4.3):

```bash
docker build - < ./video/ome/nvidia/Dockerfile.cuda \
    --build-arg OME_VERSION=v0.16.4 \
    -t docker.io/$docker_username/$docker_repo:ome-official-v0.16.4-cuda12
```

Unfortunately, the error is the same, except the file name is a bit different:

```log
/opt/ovenmediaengine/bin/OvenMediaEngine: error while loading shared libraries: libnppig.so.12: cannot open shared object file: No such file or directory
```

Version 1.16.3 didn't have this issue.

**Comment by Keukhan** [comment]
Thank you for reporting. I'm sorry for my late reply.

Recently, I changed the code to use the libnpp library in OME.

If you have time, could you test it by changing the CUDA build script as shown below and let me know the results?


Dockerfile.cuda
````
ENV     NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,compat32

=>

ENV     NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,compat32,graphics
````

The above code binds the NVIDIA library on the host when running Docker Image. 
It is expected that the CAPABILITIES property value called graphics will bind the libnppig.so file.

Then I'll wait for good news. Thanks for your help.

**Comment by d-uzlov** [comment]
> could you test it by changing the CUDA build script as shown below and let me know the results?

Unfortunately, it doesn't seem to change anything.

```bash
root@ovenmediaengine-7958d6df66-8s22j:/opt/ovenmediaengine/bin# env | grep NVIDIA_DRIVER_CAPABILITIES
NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,compat32,graphics
root@ovenmediaengine-7958d6df66-8s22j:/opt/ovenmediaengine/bin# /opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf
/opt/ovenmediaengine/bin/OvenMediaEngine: error while loading shared libraries: libnppig.so.12: cannot open shared object file: No such file or directory
```

**Comment by d-uzlov** [comment]
I tried to check what `NVIDIA_DRIVER_CAPABILITIES` actually does to a container.
It doesn't seem to change the list of available libraries.

<details>
<summary>A few examples</summary>

```bash
root@ovenmediaengine-7cdf5d7c9b-cm275:/opt/ovenmediaengine/bin# env | grep NVIDIA_DRIVER_CAPABILITIES
NVIDIA_DRIVER_CAPABILITIES=
root@ovenmediaengine-7cdf5d7c9b-cm275:/opt/ovenmediaengine/bin# ls -la /usr/local/cuda/targets/x86_64-linux/lib/ /usr/local/cuda/compat/
/usr/local/cuda/compat/:
total 145576
drwxr-xr-x 2 root root     4096 Nov 10 04:57 .
drwxr-xr-x 4 root root     4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root       12 Oct 19 23:47 libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       21 Oct 19 23:47 libcuda.so.1 -> libcuda.so.535.129.03
-rw-r--r-- 1 root root 29372496 Oct 19 19:06 libcuda.so.535.129.03
lrwxrwxrwx 1 root root       29 Oct 19 23:47 libcudadebugger.so.1 -> libcudadebugger.so.535.129.03
-rw-r--r-- 1 root root 10188744 Oct 19 18:31 libcudadebugger.so.535.129.03
lrwxrwxrwx 1 root root       19 Oct 19 23:47 libnvidia-nvvm.so -> libnvidia-nvvm.so.4
lrwxrwxrwx 1 root root       28 Oct 19 23:47 libnvidia-nvvm.so.4 -> libnvidia-nvvm.so.535.129.03
-rw-r--r-- 1 root root 86140736 Oct 19 19:49 libnvidia-nvvm.so.535.129.03
lrwxrwxrwx 1 root root       38 Oct 19 23:47 libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.535.129.03
-rw-r--r-- 1 root root 23348992 Oct 19 19:12 libnvidia-ptxjitcompiler.so.535.129.03

/usr/local/cuda/targets/x86_64-linux/lib/:
total 680
drwxr-xr-x 2 root root   4096 Nov 10 04:57 .
drwxr-xr-x 3 root root   4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root     20 May  1  2023 libcudart.so.12 -> libcudart.so.12.2.53
-rw-r--r-- 1 root root 687456 May  1  2023 libcudart.so.12.2.53
```

```bash
root@ovenmediaengine-665476f9cf-5cx4w:/opt/ovenmediaengine/bin# env | grep NVIDIA_DRIVER_CAPABILITIES
NVIDIA_DRIVER_CAPABILITIES=video
root@ovenmediaengine-665476f9cf-5cx4w:/opt/ovenmediaengine/bin# ls -la /usr/local/cuda/targets/x86_64-linux/lib/ /usr/local/cuda/compat/
/usr/local/cuda/compat/:
total 145576
drwxr-xr-x 2 root root     4096 Nov 10 04:57 .
drwxr-xr-x 4 root root     4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root       12 Oct 19 23:47 libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       21 Oct 19 23:47 libcuda.so.1 -> libcuda.so.535.129.03
-rw-r--r-- 1 root root 29372496 Oct 19 19:06 libcuda.so.535.129.03
lrwxrwxrwx 1 root root       29 Oct 19 23:47 libcudadebugger.so.1 -> libcudadebugger.so.535.129.03
-rw-r--r-- 1 root root 10188744 Oct 19 18:31 libcudadebugger.so.535.129.03
lrwxrwxrwx 1 root root       19 Oct 19 23:47 libnvidia-nvvm.so -> libnvidia-nvvm.so.4
lrwxrwxrwx 1 root root       28 Oct 19 23:47 libnvidia-nvvm.so.4 -> libnvidia-nvvm.so.535.129.03
-rw-r--r-- 1 root root 86140736 Oct 19 19:49 libnvidia-nvvm.so.535.129.03
lrwxrwxrwx 1 root root       38 Oct 19 23:47 libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.535.129.03
-rw-r--r-- 1 root root 23348992 Oct 19 19:12 libnvidia-ptxjitcompiler.so.535.129.03

/usr/local/cuda/targets/x86_64-linux/lib/:
total 680
drwxr-xr-x 2 root root   4096 Nov 10 04:57 .
drwxr-xr-x 3 root root   4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root     20 May  1  2023 libcudart.so.12 -> libcudart.so.12.2.53
-rw-r--r-- 1 root root 687456 May  1  2023 libcudart.so.12.2.53
```

```bash
root@ovenmediaengine-5cbf748884-l8tgl:/opt/ovenmediaengine/bin# env | grep NVIDIA_DRIVER_CAPABILITIES
NVIDIA_DRIVER_CAPABILITIES=compute,utility,video,compat32,graphics
root@ovenmediaengine-5cbf748884-l8tgl:/opt/ovenmediaengine/bin# ls -la /usr/local/cuda/targets/x86_64-linux/lib/ /usr/local/cuda/compat/
/usr/local/cuda/compat/:
total 145576
drwxr-xr-x 2 root root     4096 Nov 10 04:57 .
drwxr-xr-x 4 root root     4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root       12 Oct 19 23:47 libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       21 Oct 19 23:47 libcuda.so.1 -> libcuda.so.535.129.03
-rw-r--r-- 1 root root 29372496 Oct 19 19:06 libcuda.so.535.129.03
lrwxrwxrwx 1 root root       29 Oct 19 23:47 libcudadebugger.so.1 -> libcudadebugger.so.535.129.03
-rw-r--r-- 1 root root 10188744 Oct 19 18:31 libcudadebugger.so.535.129.03
lrwxrwxrwx 1 root root       19 Oct 19 23:47 libnvidia-nvvm.so -> libnvidia-nvvm.so.4
lrwxrwxrwx 1 root root       28 Oct 19 23:47 libnvidia-nvvm.so.4 -> libnvidia-nvvm.so.535.129.03
-rw-r--r-- 1 root root 86140736 Oct 19 19:49 libnvidia-nvvm.so.535.129.03
lrwxrwxrwx 1 root root       38 Oct 19 23:47 libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.535.129.03
-rw-r--r-- 1 root root 23348992 Oct 19 19:12 libnvidia-ptxjitcompiler.so.535.129.03

/usr/local/cuda/targets/x86_64-linux/lib/:
total 680
drwxr-xr-x 2 root root   4096 Nov 10 04:57 .
drwxr-xr-x 3 root root   4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root     20 May  1  2023 libcudart.so.12 -> libcudart.so.12.2.53
-rw-r--r-- 1 root root 687456 May  1  2023 libcudart.so.12.2.53
```

```bash
root@ovenmediaengine-7f8fb6d678-bdzdd:/opt/ovenmediaengine/bin# env | grep NVIDIA_DRIVER_CAPABILITIES
NVIDIA_DRIVER_CAPABILITIES=utility
root@ovenmediaengine-7f8fb6d678-bdzdd:/opt/ovenmediaengine/bin# ls -la /usr/local/cuda/targets/x86_64-linux/lib/ /usr/local/cuda/compat/
/usr/local/cuda/compat/:
total 145576
drwxr-xr-x 2 root root     4096 Nov 10 04:57 .
drwxr-xr-x 4 root root     4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root       12 Oct 19 23:47 libcuda.so -> libcuda.so.1
lrwxrwxrwx 1 root root       21 Oct 19 23:47 libcuda.so.1 -> libcuda.so.535.129.03
-rw-r--r-- 1 root root 29372496 Oct 19 19:06 libcuda.so.535.129.03
lrwxrwxrwx 1 root root       29 Oct 19 23:47 libcudadebugger.so.1 -> libcudadebugger.so.535.129.03
-rw-r--r-- 1 root root 10188744 Oct 19 18:31 libcudadebugger.so.535.129.03
lrwxrwxrwx 1 root root       19 Oct 19 23:47 libnvidia-nvvm.so -> libnvidia-nvvm.so.4
lrwxrwxrwx 1 root root       28 Oct 19 23:47 libnvidia-nvvm.so.4 -> libnvidia-nvvm.so.535.129.03
-rw-r--r-- 1 root root 86140736 Oct 19 19:49 libnvidia-nvvm.so.535.129.03
lrwxrwxrwx 1 root root       38 Oct 19 23:47 libnvidia-ptxjitcompiler.so.1 -> libnvidia-ptxjitcompiler.so.535.129.03
-rw-r--r-- 1 root root 23348992 Oct 19 19:12 libnvidia-ptxjitcompiler.so.535.129.03

/usr/local/cuda/targets/x86_64-linux/lib/:
total 680
drwxr-xr-x 2 root root   4096 Nov 10 04:57 .
drwxr-xr-x 3 root root   4096 Nov 10 04:57 ..
lrwxrwxrwx 1 root root     20 May  1  2023 libcudart.so.12 -> libcudart.so.12.2.53
-rw-r--r-- 1 root root 687456 May  1  2023 libcudart.so.12.2.53
```

Running `docker.io/alpine:3.17.3` with nvidia container runtime:

```bash
/ # env | grep NVIDIA_DRIVER_CAPABILITIES
NVIDIA_DRIVER_CAPABILITIES=all
/ # ls -la /usr/local/cuda/targets/x86_64-linux/lib/ /usr/local/cuda/compat/
ls: /usr/local/cuda/targets/x86_64-linux/lib/: No such file or directory
ls: /usr/local/cuda/compat/: No such file or directory
/ # ls -la /usr/local/
total 24
drwxr-xr-x    5 root     root          4096 Mar 29  2023 .
drwxr-xr-x    1 root     root          4096 Feb 12 20:15 ..
drwxr-xr-x    2 root     root          4096 Mar 29  2023 bin
drwxr-xr-x    2 root     root          4096 Mar 29  2023 lib
drwxr-xr-x    2 root     root          4096 Mar 29  2023 share
/ # nvidia-
nvidia-cuda-mps-control  nvidia-cuda-mps-server   nvidia-debugdump         nvidia-persistenced      nvidia-smi
/ # nvidia-smi
sh: nvidia-smi: not found
```

</details>

The list of CUDA libraries stays the same regardless of `NVIDIA_DRIVER_CAPABILITIES`.
`nvidia-smi` is not available when env doesn't contain `utility`. Maybe there are some other changes but I don't see them in the file system.
Also, when I tried running pure `alpine` container, libraries are not injected at all. I guess they are only present in OME container because it is using `nvidia/cuda:12.2.0-base-ubuntu20.04` as base.

I can't quite find any details on this in google.
I'm not sure, maybe there is something wrong with my container runtime setup? I can't tell.
I did setup the container runtime using instructions from nvidia website, and I re-checked that everything is still alright.
OME 1.16.3 runs just fine with hardware acceleration.
Also, `nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2`, which nvidia suggests to use to test if CUDA is available in container runs without any issues.

**Comment by Keukhan** [comment]
@d-uzlov 

I've finally solved it due to my busy work schedule.
The problem of not finding the libnppig.so file has been corrected as follows.

https://github.com/AirenSoft/OvenMediaEngine/compare/f38d3c1a180e...4b297cc97fbc

You can change Docker's base image from **base -> runtime** in the Dockerfile.cuda and Dockerfile.cudal.ocal scripts. Please test it and let me know the results.

I hope you have a nice day.

**Comment by chandrashekar-nallamilli** [comment]
Thank you @Keukhan for looking into the issue , @d-uzlov for testing it . I can confirm its is working after making the suggested  changes from our side 
Have a nice day

**Comment by d-uzlov** [comment]
The problem is solved when using `runtime` cuda images.
It's a bit unfortunate that image size goes from ~500 MB to ~2500 MB (uncompressed). I guess it's not too big of a deal but maybe it would be possible to optimize it in the future.
Thank you for solving this.
