### ISSUE TITLE
I want Recording

### ISSUE THREAD

**Issue by jys923** [AirenSoft/OvenMediaEngine#151]
Here's the schema I'd like to follow :

OBS -> RTMP -> Nginx(recording) -> RTMP -> OME  -> player.

my nginx rtmp setting
rtmp {
	server {
		listen 1936;
		chunk_size 4096;
		application app {
			live on;
	#		push 0.0.0.0:1935/$app/$name;
			push 0.0.0.0:1935/app/stream;
	#		on_publish "rtmp://0.0.0.0:1935/app/stream";
			record all;
			record_path /tmp/av/;
			record_max_size 1M;
			record_unique on;
			record_append on;
			exec_publish bash -c "echo 0.0.0.0:1935/$app/$name >> /tmp/av/clients";
			exec_record_done bash -c printf "file '%s'\n" /tmp/av/stream* >> /tmp/av/mylist.txt;
		}	    
	}
}

This is work find push 0.0.0.0:1935/app/stream;
This is not work push 0.0.0.0:1935/$app/$name; 

I can't not understand???

what's problem

**Comment by getroot** [comment]
We cannot provide technical support for NGINX.
If NGINX requests as /$app/$stream as it is, I am not sure if OME can handle it. URLs will not allow you to use $ without url encoding.
