### ISSUE TITLE
Stream not working when P2P is enabled

### ISSUE THREAD

**Issue by germanbuchmuller** [AirenSoft/OvenMediaEngine#1526]
**Describe the bug**
Streaming not working when P2P Enabled. When P2P is disabled, streaming works perfect, but when enabling P2P in xml, then player keeps on loading. Sometimes it starts playing, but most of the time not.

**To Reproduce**
1. Set Edge Server.xml as follows 
`<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
    <Name>OME</Name>
    
    <Type>edge</Type>
    
    <IP>*</IP>
    <PrivacyProtection>false</PrivacyProtection>

    
    <StunServer>stun.ovenmediaengine.com:13478</StunServer>

    <Modules>
        
        <HTTP2>
            <Enable>true</Enable>
        </HTTP2>

        <LLHLS>
            <Enable>false</Enable>
        </LLHLS>

        
        <P2P>
            
            <Enable>true</Enable>
            <MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
        </P2P>
    </Modules>

    
    <Bind>
        

        <Managers>
            <API>
                <Port>${env:OME_API_PORT:8085}</Port>
                <TLSPort>${env:OME_API_TLS_PORT:8086}</TLSPort>
                <WorkerCount>1</WorkerCount>
            </API>
        </Managers>

        <Providers>
            
            <OVT>
                <WorkerCount>2</WorkerCount>
            </OVT>
        </Providers>

        <Publishers>

            

            <WebRTC>
                <Signalling>
                    <Port>${env:OME_SIGNALLING_PORT:3333}</Port>
                    <TLSPort>${env:OME_SIGNALLING_TLS_PORT:3334}</TLSPort>
                    <WorkerCount>12</WorkerCount>
                </Signalling>
                <IceCandidates>
                    <IceCandidate>${env:OME_HOST_IP:*}:${env:OME_WEBRTC_CANDIDATE_PORT:10005-10009/udp}</IceCandidate>
                    <TcpRelay>${env:OME_HOST_IP:*}:${env:OME_WEBRTC_TCP_RELAY_PORT:3478}</TcpRelay>
                    <TcpForce>true</TcpForce>
                    <TcpRelayWorkerCount>12</TcpRelayWorkerCount>
                </IceCandidates>
            </WebRTC>

        </Publishers>
    </Bind>

    
    

    <Managers>
        <Host>
            <Names>
                <Name>*</Name>
            </Names>
            
        </Host>
        <API>
            <AccessToken>root:PASS</AccessToken>
            <CrossDomains>
                <Url>*</Url>
            </CrossDomains>
        </API>
    </Managers>

    <VirtualHosts>
        
        <VirtualHost include="VHost*.xml" />
        <VirtualHost>
            <Name>default</Name>
            
            <Distribution>ovenmediaengine.com</Distribution>

            
            <Host>
                <Names>
                    
                    <Name>*</Name>
                </Names>
                <TLS>
                    <CertPath>/certs/signed.crt</CertPath>
                    <KeyPath>/certs/domain.key</KeyPath>
                </TLS>
            </Host>

            

            <AdmissionWebhooks>
                <ControlServerUrl>https://api.HOST.com/stream/admission</ControlServerUrl>
                <SecretKey>PASS</SecretKey>
                <Timeout>20000</Timeout>
                <Enables>
                    <Publishers>webrtc</Publishers>
                </Enables>
            </AdmissionWebhooks>

            

            <Origins>
                <Properties>
                    <NoInputFailoverTimeout>10000</NoInputFailoverTimeout>
                    <UnusedStreamDeletionTimeout>120000</UnusedStreamDeletionTimeout>
                </Properties>
            </Origins>

            
            <OriginMapStore>
                <RedisServer>
                    <Host>HOST:6379</Host>
                    <Auth>PASS</Auth>
                </RedisServer>
            </OriginMapStore>

            
            <CrossDomains>
                <Url>https://DOMAIN.com</Url>
                <Url>https://DOMAIN.com</Url>
                <Url>https://DOMAIN.com</Url>
                <Url>https://DOMAIN.com</Url>
            </CrossDomains>

            <Applications>
                <Application>
                    <Name>livestream</Name>
                    <Type>live</Type>
                    <OutputProfiles>
                        <OutputProfile>
                            <Name>passthrough</Name>
                            <OutputStreamName>${OriginStreamName}</OutputStreamName>
                            <Encodes>
                                <Video>
                                    <Bypass>true</Bypass>
                                </Video>
                                <Audio>
                                    <Bypass>true</Bypass>
                                </Audio>
                            </Encodes>
                        </OutputProfile>
                    </OutputProfiles>
                    <Providers>
                        <OVT />
                    </Providers>
                    <Publishers>
                        <AppWorkerCount>${env:OME_APP_WORKER_COUNT:1}</AppWorkerCount>
                        <StreamWorkerCount>${env:OME_STREAM_WORKER_COUNT:6}</StreamWorkerCount>

                        <WebRTC>
                            <Timeout>30000</Timeout>
                            <Rtx>false</Rtx>
                            <Ulpfec>false</Ulpfec>
                            <JitterBuffer>false</JitterBuffer>
                        </WebRTC>

                    </Publishers>
                </Application>
            </Applications>
        </VirtualHost>
    </VirtualHosts>
</Server>
`
2. With Encoder OBS, bypass in Origin'

**Expected behavior**
Stream to show, and when new instances connect, play either from edge or p2p.

**Server (please complete the following information):**
 - OS: [Ubuntu 20]
 - OvenMediaEngine Version:0.16.2
 - Branch: release
 - Running Docker

**Player: OvenPlayer**
 - Device: [PC]
 - OS: [Windows]
 - Browser [chrome]

**Additional context**
Network messaging in chrome:
![image](https://github.com/AirenSoft/OvenMediaEngine/assets/56135081/381e41b7-982b-4d0f-957e-a47694d0fdad)

**Comment by getroot** [comment]
Yes this is a duplicate issue #1466 so I am closing it.
