### ISSUE TITLE
RTMP Input resulting in Memory Dump error

### ISSUE THREAD

**Issue by SanskarP** [AirenSoft/OvenMediaEngine#1541]
**Describe the bug**
When receiving RTMP input from a Blackmagic ATEM Television Studio HD8, the stream seems to play for a few second and then completely stops after a few seconds. I've tried to change the keyframe intervals and also tried setting the bitrate to a lower setting, but still just getting the same errors. 

I already have a successful setup with an ATEM Mini Pro which works perfectly fine with the exact same config file I attached, but not sure what could be causing the issue with the Television HD8 Studio. 

Not too knowledgeable about networks, but could a lot of routing and firewalls contribute to this?

**To Reproduce**
1. Set Server.xml as attached in ZIP
2. Live stream from a Blackmagic Television Studio HD8 using streaming config as attached in ZIP
3. See errors as shown in logs in ZIP

**Expected behavior**
When using my existing ATEM Mini Pro setup, its as each as just providing the destination IP for the stream in the config, and hitting start for the stream and I'm able to view the stream using OvenPlayer as normal. 

**Logs**
See attached log file in ZIP
[OME_RTMP_ERROR.zip](https://github.com/AirenSoft/OvenMediaEngine/files/14468387/OME_RTMP_ERROR.zip)

**Server:**
 - OS: Ubuntu 22.04.4 LTS
 - OvenMediaEngine Version: OvenMediaEngine-0.16.4
 - Branch: Main

**Player (please complete the following information):**
 - Device: Apple MacBook Pro M1 2020
 - OS: MacOS Sonoma 14.2.1
 - Browser: Chrome
 - Version: 121.0.6167.184

**Additional context**
The setup has also been tested with default settings in OBS and ATEM Mini Pro and it works fine, just not sure what's causing the memory issues as seen in the error logs.

**Comment by getroot** [comment]
It appears to be an RTMP protocol compatibility issue. We will look into this.

**Comment by dimiden** [comment]
@SanskarP 
There was an issue with the processing of the chunked header, and I've addressed this by committing the fix.
Could you please verify if the issue has been resolved? 1c9e65a188f6101b54b92637884f9c32efd70d0c

**Comment by getroot** [comment]
This patch made it into the 0.16.5 release. Thank you.

**Comment by SanskarP** [comment]
> @SanskarP There was an issue with the processing of the chunked header, and I've addressed this by committing the fix. Could you please verify if the issue has been resolved? [1c9e65a](https://github.com/AirenSoft/OvenMediaEngine/commit/1c9e65a188f6101b54b92637884f9c32efd70d0c)

Issue seems to be resolved. Haven't tested it extensively but stream is running smoothly and without any noticeable performance drops. Thanks for the fix!
