### ISSUE TITLE
Queue size exceeded

### ISSUE THREAD

**Issue by jaullo** [AirenSoft/OvenMediaEngine#155]
**Describe the bug**
After HD video injection using clustered environment with transcoding, origin server show the message "WebRTC Publisher Application/#default#app/stream StreamWorker Queue Size has exceeded threshold: queue:100, threshold: 100

**To Reproduce**
1. Create a clustered environment (origin, edge, web)
2. Obs Studio push a 1080 HD video to origin
3. Enable transcoding in origin server
4. Start origin server 

**Expected behavior**
After starting origin server, must be no errors 

**Server (please complete the following information):**
 - OS: ubuntu 18

**Player (please complete the following information):**
 - Device: PC
 - OS: Win 10
 - Browser Latest Chrome

**Comment by getroot** [comment]
If it doesn't increase at 100 anymore, it is normal. I will modify that log.
Thank you

**Comment by getroot** [comment]
This issue has not been updated for a long time, so I close the issue. If you would like to continue discussing this issue, please reopen it.
