### ISSUE TITLE
Admission Webhook not called when forcefully closing RTMP client

### ISSUE THREAD

**Issue by bartvp1** [AirenSoft/OvenMediaEngine#1570]
**Describe the bug**
The admission webhook for closing RTMP streams is not called when a it closes unexpectedly

**To Reproduce**
1. Set up OME with RTMP ingress & admission webhooks
2. Start a RTMP stream using Larix
3. Disable the internet connection on the broadcasting device

**Expected behavior**
The admission webhook should be called with the information of the cancelled RTMP stream

**Server**
 - OS: Ubuntu
 - OvenMediaEngine Version: 0.16.5

**Comment by getroot** [comment]
OME may not be aware that the RTMP session has been disconnected. If TCP keepalive is working, OME will notice the tcp connection termination after several tens of seconds. Admission webhooks aren't being called even though the log shows the stream has been deleted?

**Comment by bartvp1** [comment]
The logs don't show anything in regard to the disconnected RTMP client. After some amount of time however, the stream ID disappears from the response of GET `/v1/vhosts/default/apps/app/streams`

**Comment by bartvp1** [comment]
Any updates on this issue?

I need this feature because I need to keep track of active streams in a separate, realtime database. 
I investigated whether syncing the redis server (origin map store) would fix this issue, but OME keeps sending SET and EXPIRE commands to the Redis server, despite not receiving any new frames. This results in streams still remaining while they are not.

**Comment by getroot** [comment]
The server doesn't notice that the TCP connection between the RTMP client and the server has been lost. You might want to look into setting up TCP Keepalive on the server.
