### ISSUE TITLE
Cant get WebRTC working with Testplayer

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenMediaEngine#159]
Hi together,

i have found this project today and was excited to try it and its latency while using the WebRTC.

So i started the docker version and connected to it via OBS with the settings you provided.

It is connecting fine and HLS is working like DASH too but WebRTC doesnt. If i use your test-player (with http because i dont use https for my test) it tries to load something for about 5sec but without getting a picture it responds with something like "connection was terminated unexpected"
No Firewall is active on this test-server.

What can i do?

I tried to install it without docker on Ubuntu 20.04 but no chance. The prerequisites.sh is dropping errors, the steps of the manual-installation too.

**Comment by getroot** [comment]
To analyze the problem we need to know the version of docker you used, the docker run command and /var/log/ovenmediaengine/ovenmediaengine.log inside docker.

**Comment by getroot** [comment]
Also, please tell us the URL you tried to play.

**Comment by morbificagent** [comment]
@getroot Hello and thanks for the response.

i am trying to play this stream:

http://meet.bit-link.de:8080/app/12345678/manifest_ll.mpd

As i wrote i have tested HLS, DASH and so on... My VLC can play all of them as you can see on the screenshot. But at the moment i cant get any of them played on your test-player.

![Anmerkung 2020-07-27 085414](https://user-images.githubusercontent.com/50199132/88512387-c6070d00-cfe6-11ea-9958-29af4114dddc.png)

![Anmerkung 2020-07-27 085542](https://user-images.githubusercontent.com/50199132/88512518-fcdd2300-cfe6-11ea-8159-befe07c3af30.png)


I was installing and i am running the docker image with the command you provided on your website:

docker run -d \
-p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 8080:8080 -p 9000:9000 -p 10000-10005:10000-10005/udp \
airensoft/ovenmediaengine:latest

>To analyze the problem we need to know the version of docker you used, the docker run command and /var/log/ovenmediaengine/ovenmediaengine.log inside docker.

Could you write how i can get the files which are inside the Docker? I am new in this as i wasnt using docker before

**Comment by getroot** [comment]
I think you may be using an option that your web browser cannot support.

https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder
Are you using the settings recommended in the article above? Capture and upload your OBS settings.

**Comment by getroot** [comment]
When I analyzed your stream, I found this could be a bug on our server. We will analyze this a little more. First, upload your OBS settings.

**Comment by getroot** [comment]
You can access your Docker container in the following ways.

$ docker exec -ti [container_name/container_id] /bin/bash

**Comment by getroot** [comment]
http://meet.bit-link.de:8080/app/12345678/manifest.mpd does not play properly.

http://meet.bit-link.de:8080/app/12345678/playlist.m3u8 plays normally.

Perhaps there is a problem with MPEG-DASH Packetizing.

But ws://meet.bit-link.de:3333/app/12345678/ is not playing because the UDP port is not connected. (Mistake in our manual)

Please do as follows.

docker run -d
-p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 8080:8080 -p 9000:9000 -p 10000-10010:10000-10010/udp
airensoft/ovenmediaengine:latest

**Comment by morbificagent** [comment]
Ok, one problem found: Using the IP instead of the fqdn let me use hls an dash in your test-player again.... 

But it doesnt solve the WebRTC-Problem:

![Anmerkung 2020-07-27 094408](https://user-images.githubusercontent.com/50199132/88516669-f00ffd80-cfed-11ea-9a90-10feaaba36b8.png)

Here are my OBS-Settings:

![asdasd](https://user-images.githubusercontent.com/50199132/88516801-251c5000-cfee-11ea-9d8d-4541232ae099.png)
![sadsdg](https://user-images.githubusercontent.com/50199132/88516807-277eaa00-cfee-11ea-84b1-8c092784fdbe.png)

Will no try out your changed docker command...

**Comment by morbificagent** [comment]
Jeeehaaaaa, now its working with WebRTC and really great latency! :-)

**Comment by getroot** [comment]
We will continue to analyze the problem with MPEG-DASH streams. Please use WEBRTC and HLS first. :-)
