### ISSUE TITLE
line 1: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by voipcall** [AirenSoft/OvenMediaEngine#16]
trying start ./OvenMediaEngine (Server.xml in same directory)

But receiving error:

./OvenMediaEngine: line 1: syntax error near unexpected token `newline'
./OvenMediaEngine: line 1: `<?xml version="1.0" encoding="UTF-8"?>'

**Comment by sfreet** [comment]
Hello @voipcall.
Thank you very much for your reporting.

The Server.xml file must be in the sub directory(conf), not in the same directory as the OvenMediaEngine. (But the issue you're posting right now is not the issue.)

Could you give me some additional information?
1. Check your system
```
$ uname -a
Linux Benjamin 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
2. Check OvenMediaEngine binary
```
$ file OvenMediaEngine 
OvenMediaEngine: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=b4ef2fb1a878d64ca68d253231ca73ebf3a1266d, with debug_info, not stripped
```
3. Check files 
```
$ pwd && ls -l
/OvenMediaEngine/src/bin/DEBUG
-rwxrwxr-x 1 benjamin benjamin 44675520  4월 18 17:19 OvenMediaEngine
drwxr-xr-x 3 benjamin benjamin     4096  4월 19 10:13 conf
```

**Comment by voipcall** [comment]
I clean, then rebuild project
it works 
thnx
