### ISSUE TITLE
SSL Cert inside of docker?

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenMediaEngine#160]
Hi again,
as my docker container is running now i have to get ssl for OME... but inside of the docker config there is no ssl configured per default for sure.

No im not sure which is the best way for getting ssl to ome... doing changes inside of the docker isnt the right way i think as if i update it they would be gone right?

So better use nginx (which i am using on my host) as a reverse proxy for the docker container? But is it possible for ome and if yes does anyone have an config-example?

Many thanks for your help

**Comment by VTFLAB** [comment]
You can use the nginx RTMP module
This allows for authentication and relaying
Here is a sample setup for your reference

```
rtmp {
    server {
        listen 1935;

        application app {
            live on;
            #*required*　Without it, the OME will not be able to receive the Stream successfully
            meta copy;
            # No RTMP playback
            #deny play all;

            # POST authentication process body contains information such as StreamKey
            on_publish http://localhost:3001/stream;
            notify_method post;

            # Push this stream to the local OME server
            push rtmp://192.168.1.17:1935;
        }
    }
}
```

You'll also need to use relays such as WSS, which we'll skip as they can be done in the usual way

**Comment by getroot** [comment]
Using NGINX is also a good idea, but we also recommend creating your own Docker image.

You can create your own Docker image in just a few lines: Isn't this the Docker's strength?

FROM airensoft/ovenmediaengine:latest
COPY Server.xml /opt/ovenmediaengine/bin/origin_conf/...
COPY Cert...

**Comment by morbificagent** [comment]
@VTFLAB Great, i have implemented this and changed it a little bit to get a simple auth-mechanism for me so not everybody can stream to our server.
It works good!

@getroot Yes you are right... i have changed and commited the config inside of the docker and only have to remember changing the certs inside of it when they are running out of time.

**Comment by getroot** [comment]
I close this issue. If you want to discuss again, don't hesitate to reopen this issue.
