### ISSUE TITLE
60GB RAM after 20s of Streaming

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenMediaEngine#161]
Hi @ all,
I was testing OME with an hardware h264 streaming-device which sends to ome via rtmp and ome was exploding ;-)

It was consuming more and more ram and the whole server became problems as ome was using 60GB ram after 20s of the stream...  Does anyone had such a problem before?

Streaming from OBS is working without a problem.

And what log-files would you need to take a look on this problem?

**Comment by getroot** [comment]
Which H264 hardware streaming device do you use? Perhaps there is a problem with the compatibility of the RTMP protocol. (I have recently received a report on it.) We are going to look at this in depth.

**Comment by getroot** [comment]
문제가 재현된 후 /var/log/ovenmediaengine/ovenmediaengine.log 파일을 올려주십시오. 우리에게 도움이 될 것입니다.

**Comment by getroot** [comment]
After the problem has been reproduced, upload the /var/log/ovenmediaengine/ovenmediaengine.log file. It will help us.

**Comment by morbificagent** [comment]
@getroot It is the AVC-2K from www.ddmalltech.com
I will try to reproduce this and send you the logs...

**Comment by getroot** [comment]
It seems very useful equipment. We will also buy it for use at the exhibition and see why it is not compatible with OME.
(This year the event was canceled with COVID19, but we started participating in NAB and IBC from 2019.)

**Comment by morbificagent** [comment]
Yes its really useful as you can preconfigure the streaming url, take it with you, plug it in and your stream is up and running :-) And no software which can crash or windows clients which want to update when you need the stream ;-)

**Comment by getroot** [comment]
We purchased the equipment you gave us.
This is Seoul (Korea), so it will take a long time to receive equipment. When we receive the equipment, we will analyze the problem.

**Comment by dimiden** [comment]
@morbificagent 
Finally we got this equipment, and we found the cause.
I analyzed the RTMP timestamp sent by this device and corrected something wrong in OME's algorithm. (1592695d1adca0a2e7785d8c40d1ef8c503f99f9)

I hope this modification works fine.

**Comment by morbificagent** [comment]
Many thanks :-)
