### ISSUE TITLE
StreamWorker deadlock issue in LLHLS

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1633]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1627

<div type='discussions-op-text'>

<sup>Originally posted by **mbakumenkov** May 29, 2024</sup>
Recently I have the message in server logs:
`[2024-05-28 17:23:31.225] W [AW-LLHLS0:19] ManagedQueue | managed_queue.h:444  | [4051] mngq:v=#default#live:s=stream:p=pub:n=streamworker_llhls size has exceeded the threshold: queue: 937, threshold: 500, peak: 937`

All outgoing traffic from server just got stopped (dropped to zero), and queue size continue rising until I restarted ome docker container. 
Please help me understand what could be wrong and how this can be avoided.</div>

**Comment by dimiden** [comment]
@mbakumenkov
I discovered a scenario where a deadlock could occur at an extremely low probability and have fixed and committed it.
You can use the `airensoft/ovenmediaengine:dev` image before the next version is released.
Thank you!

**Comment by mbakumenkov** [comment]
Thank you, @dimiden for your work!
I'll try out the new version as soon as I can
