### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#1639]
**Describe the bug**
Today, our OME instance crashed after quite a long uptime without issue. Apologies, but I may not have logs for this one, though I will keep trying to recover them. I also don't really have any information about what might've triggered it as we were away

[Server.xml](https://gist.github.com/naanlizard/3b9ac92ffd78cc7e8afec77e62304941)

[Dockerfile](https://gist.github.com/naanlizard/d22ff42c156fb6879ce7a43ba4e712e4)

[crash.dump.txt](https://github.com/user-attachments/files/15776502/crash.dump.txt)

 - OS: Ubuntu 22.04.4 LTS, kernel 6.5.0-1018-oracle
 - OvenMediaEngine Version: 0.16.5

I'm not sure what else might be helpful, so please feel free to ask

**Comment by getroot** [comment]
Thanks for reporting.
This is a bug that we just discovered and fixed. It's a problem where OME crashes when the RTMP client sends a message that we don't expect.

This is scheduled to be released within the next week.

**Comment by dimiden** [comment]
@naanlizard 
For now, I have fixed the issue where OME was crashed in the https://github.com/AirenSoft/OvenMediaEngine/commit/eb72d658fcc5d0c12626c6559b3860da568abcf2. The compatibility with some encoders are still being worked on, and an update will be provided soon.

**Comment by dimiden** [comment]
Since this issue is the same as #1631, I will post future updates on #1631.
