### ISSUE TITLE
OvenMediaEngine | signals.cpp:119  | OME received signal 11 (SIGSEGV), interrupt.

### ISSUE THREAD

**Issue by alex-jhones** [AirenSoft/OvenMediaEngine#164]
**Describe the bug**
The problem occurs within 1 hour of starting OME, and "SIGSEGV, SIG-11" continues to happen even if there are few users.

**To Reproduce**
1. ./OvenMediaEngine
2. Start OBS RTMP
3. Repeat starting and ending Oven Player (Usually, the server is stopped after a while after the player is shut down.)
3. See error

**Expected behavior**
I confirmed that it works fine until the version below.
- master/ v0.10.1
- 4/22
- Short log: Added timeout to RTSPPull provider
- "a872b513e9148571765c3f831de5c47e234d151b"

However, as the version continued to rise, I was still able to find this, but I thought it was just a setting issue. If you have any problems with my operation, please comment.

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/4992792/ovenmediaengine.log)
[crash_20200728.dump.log](https://github.com/AirenSoft/OvenMediaEngine/files/4992795/crash_20200728.dump.log)

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - OvenMediaEngine Version: 0.10.3 - 0.10.4 - 0.10.5 - 0.10.6 - master branch

**Player (please complete the following information):**
 - Device: Android or PC
 - OS: Android and windows 10
 - Browser:  chrome
 - Version: 0.9

**Additional context**

**Comment by dimiden** [comment]
@alex-jhones 
Thank you for the reporting. I think it's a problem related to #163. We're investigating this problem and will let you know when it is solved.

**Comment by alex-jhones** [comment]
Yeah, I know. I hope additional reporting of similar cases will help in solving the problem. Thank you.

**Comment by getroot** [comment]
I reproduced this problem and found and solved the possibility of the problem. (4d90c66eb4312aa672f033ca39fef5b50abaa948)
It was no longer reproduced in my environment.
Please check in your environment.

**Comment by getroot** [comment]
This issue has been reported as being resolved.
If the problem is reproduced, please reopen this issue.
Thanks for your contribution.

**Comment by alex-jhones** [comment]
Hello.
Again the problem has been reproduced. I will attach the error log.

[crash_20200805.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5041805/crash_20200805.dump.txt)
[ovenmediaengine.log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/5041806/ovenmediaengine.log.txt)
