### ISSUE TITLE
Adding OME support in OBS-Studio-WebRTC for WebRTC publish

### ISSUE THREAD

**Issue by loupaw** [AirenSoft/OvenMediaEngine#165]
Is it possible to add OME to OBS-Studio-WebRTC? https://github.com/CoSMoSoftware/OBS-studio-webrtc

And what would be required to do so? [This](https://github.com/CoSMoSoftware/OBS-studio-webrtc/wiki/Media-Pipeline-design) looks like it might provide some insight, but I'm not a dev so can't work it out. 

It is of course possible to stream RTMP from OBS and RTMP from OBS-Studio-WebRTC and playback WebRTC in OvenPlayer, but I would like to stream WebRTC from OBS-Studio-WebRTC and playback WebRTC in OvenPlayer.

**So it would be:** 
Publish WebRTC from OBS-Studio-WebRTC to OME --> playback WebRTC in OvenPlayer. 
(Passthrough only, no transcoding.)

Also - is there any news on the OME API and when it might be ready for release? 

Thanks

**Comment by dimiden** [comment]
@loupaw 
It's not possible because OME cannot receive WebRTC input.
If this is to reduce the cost of transcoding from AAC to OPUS, then you need to look for another solution.

Additionally, the OME API is currently being designed and will be developed within this year.

**Comment by loupaw** [comment]
Ok, thank you for the info.
It was more an attempt to reduce latency even further (sub 500ms) though we
are getting very good results with OME using RTMP.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by getroot** [comment]
This is being developed in #29
