### ISSUE TITLE
Issues with OBS WHIP stream in OME 0.16.6

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#1658]
**Describe the bug**
When sending a WHIP stream from OBS to OME 0.16.6 the incoming video resolution and frame rate are reported as 0, and the stream disconnects after about 1 minute in this idle state. This appears to be a regression compared to 0.16.5 where the same stream works fine.

**To Reproduce**
1. Send OBS H264 WHIP over HTTPS
2. OME 0.16.5 recognizes the correct incoming video
3. OME 0.16.6 recognizes 0 frame rate and resolution

**Logs**
Successful stream to OME 0.15.5: 
[0.16.5 WHIP.txt](https://github.com/user-attachments/files/16177461/0.16.5.WHIP.txt)

Failed stream to OME 0.16.6:
[0.16.6 WHIP.txt](https://github.com/user-attachments/files/16177465/0.16.6.WHIP.txt)

Server.xml:
[Server.xml.txt](https://github.com/user-attachments/files/16177499/Server.xml.txt)

**Comment by getroot** [comment]
Thank you for reporting. What is your OBS version? 
My OME's WHIP works well with my OBS (30.0.0)

**Comment by bchah** [comment]
OBS 30.1.2 - latest public release. Also confirmed the issue on 30.2 RC. Let me see if I can run 30.0.0 and reproduce it there.

**Comment by getroot** [comment]
Ok I'll try with OBS 30.1.2

**Comment by bchah** [comment]
Sorry @getroot, this is a false report. The issue was that I didn't have the UDP IceCandidate port open 😖

**Comment by getroot** [comment]
Oh, thanks for letting me know so quickly!
