### ISSUE TITLE
how to protect video

### ISSUE THREAD

**Issue by jys923** [AirenSoft/OvenMediaEngine#166]
I want to protect real time video (web socket video).
Is there any way ome supports it?
I think you only need to make certain URLs (service URLs) accessible to ome...
If there is no way to apply, please give me an idea or hint.

**Comment by nangavar** [comment]
Hi jys923, 
I can tell you what I did, but maybe it does not apply for your case.

I've  allowed in my firewall the connection to OME to certain public IPs. In this way Im able to control who is able to stream to OME. Only my clients can. But this is useful for my situation.

**Comment by getroot** [comment]
What you want is a Signed URL?
This feature is currently only applied to HLS, MPEG-DASH, and plans to be applied to WebRTC in the near future.

Take a look at the source code below and if you want, apply this feature to WebRTC.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/publishers/segment/segment_publisher.cpp#L108

**Comment by getroot** [comment]
This issue has not been updated for a long time, so I close the issue. If you would like to continue discussing this issue, please reopen it.
