### ISSUE TITLE
Problem with HLSDump's playlist not including old segments

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1669]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1668

<div type='discussions-op-text'>

<sup>Originally posted by **TheTurkeyDev** July 19, 2024</sup>
I am working with the HLS Dump feature and I am experience some issues with it's functionality. For context my use case is that I have some cameras that are streaming 24/7. I would like to "restart" the HLS Dump every 24 hours so that I can have vods of individual days and make cleaning up the vods after a day or two a more simple process.

1. After stopping a dump, you are not able to make a new dump with the same ID. Is it possible to have the ID's freed up once they are stopped so a new dump can be made?
2. Tied in with the one above, I could make a new ID for each dump, but there is no endpoint to get a list of all the dumps for a stream to more easily track the dumps that are active.
3. More a general question, but with the HLS dump for the usage as a VOD, the dumped llhls.m3u8 file only contains the last 10 or so segments making it impossible to have a vod for the entire day (or even a vod more than like 2 minutes long). Am I doing something wrong here? Do I need to make a separate playlist for the dump that has all the segments in it's playlist? All the segments files are preserved in the dumped folder, but the segment playlist file only contains around the last 10 segments.

Let me know if there are any further details or files that you'd like me to provide to help out.</div>

**Comment by getroot** [comment]
@TheTurkeyDev 

Thanks to your help I was able to fix this issue. It was related to long DVR setup.
Could you please test with `airensoft/ovenmediaengine:dev` image?

**Comment by TheTurkeyDev** [comment]
12 Minutes in and I can still see the whole VOD. I'd call that fixed! Thank you!
