### ISSUE TITLE
Process freezed if WebRTC thread received signal 11 (SIGSEGV) and won't terminate itself

### ISSUE THREAD

**Issue by billy-sung** [AirenSoft/OvenMediaEngine#1672]
**Describe the bug**
if this log is shown, all clients cannot create websocket connection.

**To Reproduce**
1. create 4 origin with originMapStore
2. create 1 edge with dynamic application
3. create 80+ rtmp streams to origin
4. view all stream one by one via WebRTC with OvenPlayer
5. edge would stop working if `C [AW-WebRTC0:32] OvenMediaEngine | signals.cpp:124  | OME v0.16.8 ((From archive)) received signal 11 (SIGSEGV), interrupt.` printed.
**Expected behavior**
edge should terminate itself, and let it restart itself

**Logs**
[20240730-edge.log](https://github.com/user-attachments/files/16426075/20240730-edge.log)

Please upload the entire OvenMediaEngine.log. You may delete important personal information.

**Server (please complete the following information):**
 - OS: [Container-Optimized OS](https://cloud.google.com/container-optimized-os/docs)
 - OvenMediaEngine Version: v0.16.8
 - Branch: master

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Chrome
 - Version 127

**Additional context**
(empty)

**Comment by dimiden** [comment]
@billy-sung 
Container-Optimized OS is not officially supported, so I would like to request a few things to analyze this issue.

1. `Dockerfile` file
- We need the `Dockerfile` used to build OME to obtain the non-stripped binary.
- Please attach the `Dockerfile` used for the build here.

2. Crash Dump file
- A crash dump is needed to trace where the crash occurred.
- Crash dump files are created in `<OME executable>/dumps`, so you can copy them from the running container using `cp` or mount(`-v`) that path to external storage to extract the dump files generated when the crash occurs.
- Please attach the extracted dump files here.

3. `Server.xml` files
- To reproduce the issue, we need the `Server.xml` files for both Origin and Edge.
- Please upload the `Server.xml` files for both Origin and Edge here.

**Comment by longcurisa** [comment]
when have whep
