### ISSUE TITLE
Unhandled ffmpeg errors

### ISSUE THREAD

**Issue by nangavar** [AirenSoft/OvenMediaEngine#168]
**Is your feature request related to a problem? Please describe.**
Sometimes I start getting FFMPEG error on a stream (below the log). At this point the audio of the stream becomes unavailable until the last viewer disconnects from this stream and the stream is turned off (RTSP Pulling). In addition the log file starts growing without control.
Im not sure the reason why it happens. My perception is that if I switch the video input of the encoder of an active stream, and the new video has a different audio sample-rate the FFMPEG error is triggered, but I switch the input most of the times without issues. Or maybe there is a drop on the audio stream since sometimes it happens in the middle of a show. Im trying to recreate the problem to isolate it.

The FFMPEG error:
```log
[2020-07-31 21:37:32.769] E 26425 TranscodeCodec | transcode_codec_dec_aac.cpp:195  | Error sending a packet for decoding : ERROR(Unknown -1094995529)
[2020-07-31 21:37:32.788] E 26425 FFmpeg | third_parties.cpp:111  |  [AVCodecContext] Input buffer exhausted before END element found
```

**Describe the solution you'd like**
I would like that in this case OME  restarts the transcoding instance for this stream, or simply restarts the stream. And should handle correctly the log file in order to not getting thousands of errors.

**Describe alternatives you've considered**
It would be great to be able to restart a single stream manually instead of restart the app.
Using a frame-sync on the encoders input seems that solves the problem.

It is not really critical, but just to leave some feedback of using OME 24x7 hehe.
You're the best guys!
Many Thanks!
nangavar

**Comment by getroot** [comment]
OvenMediaEngine's RTSP Pulling feature is not yet complete. If the audio samplerate or other options change during streaming, OvenMediaEngine still has no ability to handle it.

That is why RTSP Pulling and MPEGTS are still BETA versions.

We will develop a dynamic input stream processing function that can handle even if the input stream changes this year.

Maybe your problem is probably due to this?

**Comment by nangavar** [comment]
Not always happen when I change format. I think is more related with simply switching input or even any disrupt in the encoders input. Could be a problem having streams of different formats (50p and 60p) on a same app?
 
I tried to handle this restarting the encoder (RTSP Pulling) in order to restart the stream at OME side. But, the problem I found is that when I stop streaming OME says "Provider has stopped playing" but the stream is never deleted and becomes unavailable even when I start streaming again. At this point I have to restart OME in order to reset the stream.

Is there anyway to restart a stream if there are viewers connected to? Like when I use RTMP that I can simply stop streaming and start again. 

Many thanks! :)

**Comment by getroot** [comment]
When the encoder is stopped, the stream is deleted by the RTSP pull provider. And when the viewer requests a connection again, it connects a new one. If it doesn't work, it's a bug. We received a report about this bug a while ago and fixed it.

Are you using the master branch version? Nevertheless, if you have a problem not to try RTSP pulling again, please let me know in detail about it.

There is currently no way to restart RTSP pulling. (The only way is to restart the encoder or 30 seconds elapse without viewers.)

**Comment by nangavar** [comment]
I have tested it right now. And it is not working. Im running master branch.

After stoping the encoder I get:
```log
[2020-08-03 02:05:17.516] I 26879 Provider | stream.cpp:55   | #default#rtsp/stream1(114) has been stopped playing stream
```
But the stream is never deleted by OME, so the viewer is never disconnected and the stream becomes unavailable until I restart OME. When the viewer tries to connect again video never starts.

**Comment by getroot** [comment]
The stream is deleted after that log (stopped playing...) is what we expect. We will fix this soon.

**Comment by getroot** [comment]
Fixed RTSP Pull Provider not deleting streams when disconnected from server (a6c9a7f64f93e5bc50e9c70411552ecb06c47de8)

Please check if this solved your problem.

**Comment by nangavar** [comment]
You are THE BEST.
I can confirm that it is working right!

Many thanks!

**Comment by nangavar** [comment]
Just for feedback. 
When I get these ffmpeg errors the log starts growing without control. I can get 700MB in a single log.
