### ISSUE TITLE
OME Docker Launcher broken. 

### ISSUE THREAD

**Issue by tdrone993** [AirenSoft/OvenMediaEngine#1683]
./ome_docker_launcher.sh start

 ▄██████▀███▄ 
█████▀ ▄██████  OvenMediaEngine Launcher v0.3
███▄▄▄▄▀▀▀▀███
██████▀ ▄█████  https://github.com/AirenSoft/OvenMediaEngine
 ▀███▄██████▀ 

• Starting OvenMediaEngine...
• Obtaining the port list from /usr/share/ovenmediaengine/conf/Server.xml
awk: line 55: syntax error at or near ,

**Comment by dimiden** [comment]
The current script is written based on `gawk`, so the issue you mentioned occurs when using `awk`. Therefore, until this issue is resolved, I recommend installing and running `gawk` if possible.

**Comment by dimiden** [comment]
@tdrone993 
I have updated the script to work in environments without `gawk`. Please let me know if it doesn't function properly. Thank you!
