### ISSUE TITLE
Webgui

### ISSUE THREAD

**Issue by suricloud** [AirenSoft/OvenMediaEngine#169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Hi,

Is there a webui availbe to login and to manage all the settings and create rtmp stream accounts?
**Additional context**

**Comment by getroot** [comment]
Unfortunately, OvenMediaEngine does not yet offer a web console. However, we are going to develop a REST API this year, so you can use it to develop it.
