### ISSUE TITLE
Problem with playing streams

### ISSUE THREAD

**Issue by voipcall** [AirenSoft/OvenMediaEngine#17]
When i publishing streams from different sorces  i see errors on server:
[04-19 23:42:41.122] I 27536 TranscodeStream | transcode_stream.cpp:405  | Queue(decoded) is full, please check your system
[04-19 23:42:41.122] I 27536 TranscodeStream | transcode_stream.cpp:405  | Queue(decoded) is full, please check your system
[04-19 23:42:41.122] I 27536 TranscodeStream | transcode_stream.cpp:405  | Queue(decoded) is full, please check your system
[04-19 23:42:41.122] I 27536 TranscodeStream | transcode_stream.cpp:405  | Queue(decoded) is full, please check your system
[04-19 23:42:41.130] I 27536 TranscodeStream | transcode_stream.cpp:405  | Queue(decoded) is full, please check your system

or

[04-19 23:42:41.142] E 27536 TranscodeCodec | transcode_codec_dec_avc.cpp:86   | DecodeFrameNoDelay failed, state=2,len=4813

And cant play:

hls: http://10.110.7.96:8080/app/stream_o/playlist.m3u8   Can not load due to unsupported media.

dash: http://10.110.7.96:8080/app/stream_o/manifest.mpd   Some of the media could not be downloaded due to a network error

webrtc wss://10.110.7.96:3333/app/stream_o                 Connection with low-latency(OME) server failed.

Player connection to server seems normal:

[04-20 00:32:27.439] I 28176 HttpServer | http_server.cpp:111  | Client(<ClientSocket: 0x7fd880000b70, #13, state: 4, TCP, [v4] 10.110.9.26:60570>) is connected on [v4] 0.0.0.0:3333
[04-20 00:32:27.442] I 28176 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 6, 0, 0x7fd880018f40
[04-20 00:32:27.467] I 28176 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 11, 0, (nil)
[04-20 00:32:27.471] I 28176 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 11, 0, (nil)
[04-20 00:32:27.471] I 28176 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 7, 0, 0x7fd880018f40
[04-20 00:32:27.471] I 28176 HttpServer | https_server.cpp:119  | Accepted
[04-20 00:32:27.471] I 28176 HttpServer | http_server.cpp:230  | Client([v4] 10.110.9.26:60570) is disconnected from [v4] 0.0.0.0:3333

**Comment by JehoenHan** [comment]
Basically, this happens when the performance of the server is insufficient.  Please write your server performance (cpu, memory, os version), your server.xml and obs(or your encoder) setting values to provide more detailed guide.

**Comment by voipcall** [comment]
Changed server, don't see any error  on server side.
But still cant play streams with player.
My server
Xeon E5520
8 Cores 16 threads 
8 Gb RAM
Ubuntu 18.04.2 LTS 

Desktop
Intel I7 4790 
CPU utilization during streaming ~30%
OBS 23.1
Output: rtmp://10.110.1.243:1935/app/ 
Stream key: stream

x264
bitrate 2000
Buser size0
zerolatency
bframes=0











<?xml version="1.0" encoding="UTF-8"?>

<Server version="1">
        <Name>OvenMediaEngine</Name>
        <Hosts>
                <Host>
                        <Name>default</Name>
                        
                        <IP>10.110.1.243</IP>
                        <Applications>
                                <Application>
                                        <Name>app</Name>
                                        <Type>live</Type>
                                        
                                        <Relay />
                                        <RelayPort>9000</RelayPort>
                                        <Encodes>
                                                <Encode>
                                                        <Name>FHD_VP8</Name>
                                                        <Audio>
                                                                <Codec>opus</Codec>
                                                                <Bitrate>128000</Bitrate>
                                                                <Samplerate>48000</Samplerate>
                                                                <Channel>2</Channel>
                                                        </Audio>
                                                        <Video>
                                                                
                                                                <Codec>vp8</Codec>
                                                                <Width>1280</Width>
                                                                <Height>720</Height>
                                                                <Bitrate>2000000</Bitrate>
                                                                <Framerate>30.0</Framerate>
                                                        </Video>
                                                </Encode>
                                                <Encode>
                                                        <Name>FHD_H264</Name>
                                                        <Video>
                                                                <Codec>h264</Codec>
                                                                <Width>1280</Width>
                                                                <Height>720</Height>
                                                                <Bitrate>2000000</Bitrate>
                                                                <Framerate>30.0</Framerate>
                                                        </Video>
                                                </Encode>
                                        </Encodes>
                                        <Streams>
                                                <Stream>
                                                        <Name>${OriginStreamName}_o</Name>
                                                        <Profiles>
                                                                <Profile>FHD_VP8</Profile>
                                                                <Profile>FHD_H264</Profile>
                                                        </Profiles>
                                                </Stream>
                                        </Streams>
                                        <Providers>
                                                <RTMP>
                                                        <MaxConnection>10</MaxConnection>
                                                        <Port>1935</Port>
<OverlapStreamProcess>reject</OverlapStreamProcess>
                                                </RTMP>
                                        </Providers>
                                        <Publishers>
                                                <ThreadCount>2</ThreadCount>
                                                <RTMP />
                                                
                                                <WebRTC>
                                                        
                                                        
                                                        <IP>10.110.7.96</IP>
                                                        <MaxConnection>10</MaxConnection>
                                                        <Port>10000/udp</Port>
                                                        
                                                        <Timeout>30000</Timeout>
                                                        <Signalling>
                                                                <Port>3333</Port>
                                                                <TLS include="TLS.xml" />
                                                        </Signalling>
                                                </WebRTC>
                                        </Publishers>
                                </Application>
                        </Applications>
                </Host>
        </Hosts>
</Server>
                                                                               

OBS 23.1

**Comment by voipcall** [comment]
WebRTC

On server:

[04-22 17:37:29.937] I 10984 HttpServer | http_server.cpp:111  | Client(<ClientSocket: 0x7f4a34000b70, #14, state: 4, TCP, [v4] 10.110.9.26:52472>) is connected on [v4] 0.0.0.0:3333
[04-22 17:37:29.942] I 10984 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 6, 0, 0x7f4a34002400
[04-22 17:37:29.974] I 10984 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 11, 0, (nil)
[04-22 17:37:29.978] I 10984 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 11, 0, (nil)
[04-22 17:37:29.978] I 10984 HttpServer | https_server.cpp:52   | [TLS] Ctrl: 7, 0, 0x7f4a34002400
[04-22 17:37:29.978] I 10984 HttpServer | https_server.cpp:119  | Accepted
[04-22 17:37:29.979] I 10984 HttpServer | http_server.cpp:230  | Client([v4] 10.110.9.26:52472) is disconnected from [v4] 0.0.0.0:3333

On player: 
Connection with low-latency(OME) server failed.

===========
hls: http://10.110.1.243:8080/app/stream_o/playlist.m3u8   Can not load due to unsupported media.

dash: http://10.110.1.243:8080/app/stream_o/manifest.mpd   Some of the media could not be downloaded due to a network error

**Comment by sfreet** [comment]
Good Morning @voipcall 

1. Your Server.XML configuration shows that the <HOST> and <WebrRTC> IP are different.
Please check the correct IP. (Unless you intentionally set it differently)
```
<Host>
...
IP>10.110.1.243</IP>
```
```
WebRTC
...
<IP>10.110.7.96>/IP>
```
2. HLS and Dash settings are commented out.
To make it work, remove the comment mark (this is an XML comment symbol <! - ->)

Feedback or questions are welcome at any time.

**Comment by voipcall** [comment]
XML fixed 
same problem, same errors

**Comment by sfreet** [comment]
Hello @voipcall 

For now, it is difficult to guess the exact reason.

One possibility is that your TLS settings are wrong.
If possible, it is recommended that you remove the TLS settings from the XML and test again using the ws URL instead of wss.

If the problem is still not resolved, we can provide remote support.
If you want to get remote support, please send time and connection information to dev@airensoft.com.

Thank you.

**Comment by voipcall** [comment]
guys, thank you for remote support
