### ISSUE TITLE
OBS Streaming Settings

### ISSUE THREAD

**Issue by 5UP3RR3D** [AirenSoft/OvenMediaEngine#170]
Ich have an issue with the streaming/encoder settings in OBS.
RTMP Streaming from a mac does connect to the OME server but does not let me pick up the stream. Wether WebRTC nor dash, hls works. Streaming off a windows OBS does let me receive the stream vie webRTC.

**Comment by getroot** [comment]
Do you think it is the same issue as #157 ?
If so, we will solve this problem this week.

**Comment by 5UP3RR3D** [comment]
Yes! Indeed - it was an issue with the audio bitrate. everything but 128k won't work.

**Comment by getroot** [comment]
https://github.com/AirenSoft/OvenMediaEngine/issues/157#issuecomment-669105730

Please check this issue. This problem seems to have been fixed.
Has your problem been solved? Please check.

**Comment by kwonkeukhan** [comment]
👍 I hope your problem is solved.

**Comment by getroot** [comment]
I am closing this issue now. If this problem is reproduced, do not hesitate to reopen this issue.
