### ISSUE TITLE
Record Api working with stream properties unusedStreamDeletionTimeoutMs question

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#1708]
### Discussed in https://github.com/AirenSoft/OvenMediaEngine/discussions/1706

<div type='discussions-op-text'>

<sup>Originally posted by **ziheng-dev** October  1, 2024</sup>
I am using OME latest Docker image to pull a rtsp and publishers is WebRTC, live video is working well with the ovenplayer.

I am trying to use record Api now,  after I post record start request, I found that recod will auto stop if I configu the persistent to false and set unusedStreamDeletionTimeoutMs when create the stream.  I would like to use the record stop api to contral the video length. 

The stream properties when created:
```
"properties":{
	"persistent": false,
	"noInputFailoverTimeoutMs": 3000,
	"unusedStreamDeletionTimeoutMs": 30000,
	"ignoreRtcpSRTimestamp": false
 }
```

I don't want to change the persistent to true because that I need to manage and delete stream by myself, Is there any way to keep the stream when recording?</div>

**Comment by Keukhan** [comment]
@ziheng-dev
Thanks for the good idea. I'll include it in my next plan to make sure the Pull Stream doesn't stop during recording. :)

**Comment by KeukhanKwon** [comment]
@ziheng-dev

Improved to pull stream does not stop during recording.
Please test it and feel free to contact me if you have any questions.
Thanks

https://github.com/AirenSoft/OvenMediaEngine/commit/7d1a985be219c8d5410c4dc0b3e0264c962bcb27

**Comment by Keukhan** [comment]
@ziheng-dev

Improved to pull stream does not stop during recording.
Please test it and feel free to contact me if you have any questions.
Thanks.

https://github.com/AirenSoft/OvenMediaEngine/commit/7d1a985be219c8d5410c4dc0b3e0264c962bcb27

**Comment by ziheng-dev** [comment]
@Keukhan 

I have tested the dev version of the Docker image, it can record stream when persistent is false, and statistics shows the file in connections now. 

Thanks
