### ISSUE TITLE
Question : i am sorry to ask, but can you pls tell why one should not use nginx for video streaming.

### ISSUE THREAD

**Issue by Dhua-v** [AirenSoft/OvenMediaEngine#176]
I was kindof trying out the project and kindof stuck on feature list to choose between nginx and ovenmedia. Can i do live stream here?

**Comment by Dhua-v** [comment]
Can I change video quality on the fly? Like youtube.

**Comment by VTFLAB** [comment]
> Can I change video quality on the fly? Like youtube.

You can. What did you see?
You should know more about the project before you ask
official website：[https://airensoft.gitbook.io/ovenmediaengine/transcoding](https://airensoft.gitbook.io/ovenmediaengine/transcoding)

**Comment by Dhua-v** [comment]
Yes but we want to make available the different qualities of video already. Instead of converting them onto the fly.

This would drastically increase performance. 
Like we have videos of all versions and switch to one-another based on requests  from client.

**Comment by Dhua-v** [comment]
Also for live streaming,  multiple quality variants would be written and consumer may be given based on choice.

**Comment by VTFLAB** [comment]
The server can provide multiple qualities in advance (like Youtube)
Clients can choose their preferred quality in the player to watch
Isn't this what you want?
If so, it's already possible.

**Comment by Dhua-v** [comment]
Yes i git that

**Comment by getroot** [comment]
OME does not yet support Adaptive Bitrates Streaming. Currently, only "Multiple Bitrates URLs" (like YouTube) is supported.
We are working on various specifications that can support ABR in WebRTC, but the priority is still low due to more important tasks.

**Comment by Dhua-v** [comment]
Thank @getroot. IMHO, Youtube's infra relies on Adaptive Bitrate Streaming. Multiple bitrate urls are however also what they offer when we manually change the video quality. I am not a c++ dev, otherwise I was getting the vibes to start contributing to get this humble feature.
