### ISSUE TITLE
rtmp -> dash_ll quality bad

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenMediaEngine#179]
Hi once more,

at the moment we are using an rtmp stream as input for ome and looking the dash_ll output in ovenplayer.

The input fullHD is at 4Mbit/sec and the ome server (docker) settings are at fullHD 4Mbit h264 too. The ovenplayer is using lowLatencyMpdLiveDelay : 2 and everything is working good except of the image quality on fast camera moves.

The artifacts are very massive at the ovenplayer-end.
The Quality of the rtmp-input is much better.

Changing the ome-settings to 8Mbit results in massive problems by the ovenplayer as it stops every 5 sec and resumes the stream after it... Dont know why because nothing is on load at the server (17% cpu load) and the client internetconnection is free too.
Changing lowLatencyMpdLiveDelay : 2 to 4 doesnt change this.

So we dont know what to do to get better quality results.

Any Ideas?

**Comment by morbificagent** [comment]
OK, i have to row back a little bit... Changing the settings to 8Mbit helps. We had packetloss on the wire which was used for streaming. Im sorry.

But the Question of "why is 4Mbit RTMP input much better in quality as the 4Mbit Dash-LL Output" remains ;-)

**Comment by getroot** [comment]
There are many encoding options. We focus on latency among them, so the quality may seem low. 
Try setting the encoding option to the bypass option(https://airensoft.gitbook.io/ovenmediaengine/transcoding#bypass-transcoding). Then you can play with the same quality as the RTMP input.

**Comment by getroot** [comment]
Not working with bypass transcoding means that the browser cannot play the stream from OBS. Please refer to the URL below to adjust the options of OBS. Maybe it can be solved by adjusting the B-Frame or H.264 Profile.

https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder

It is also a good idea to modify the following function to adjust the transcoding quality. As you can see from the code below, we are using an ultrafast preset. This reduces latency, but lowers the quality.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/transcode/codec/transcode_codec_enc_avc.cpp#L25

**Comment by morbificagent** [comment]
Hm, cant get it working with bypass and OBS.

I can see that you are using "ultrafast" but i am not experienced enough to change this in cpp and compile it again. I am using your docker at the moment.

Because higher bitrates are giving me a good result at the moment i am trying to use something like an "autobitrateselection" (dont know the right word for that) with defining more than one profile like that:

                                               <Stream>
                                                        <Name>${OriginStreamName}_dash</Name>
                                                        <Profiles>
                                                                <Profile>8Mbit</Profile>
                                                                <Profile>2Mbit</Profile>

                                                        </Profiles>
                                                </Stream>

But it seems that i only get the last Profile (2Mbit) at OvenPlayer.
Is it possible to get something described so the client autoselects the highest possible bitrate for him?

I am asking because i can use a profile with 20Mbit and great quality for some users of course but others wont be able to play it. And manual selections in the player arent possible for most of the endusers ;-)

**Comment by getroot** [comment]
the OBS and bypass setting with OME, it should work. If it doesn't work, you can fix it by changing the OBS setting.

For now, you have to create multiple Streams and select them in the player. Does not support ABR. ABR is discussed in #132.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
