### ISSUE TITLE
Transcoding

### ISSUE THREAD

**Issue by voipcall** [AirenSoft/OvenMediaEngine#18]
When i am sending RTMP stream server by default start transcoding.
Is it possible disable transcoding ?
I comment out <Encode> form config, in this case i cant see video

**Comment by sfreet** [comment]
Nomally, incoming source from rtmp is H264, AAC. 
WebRTC uses H.264/VP8, OPUS, so transcoding is required.

OvenMediaEngine supports the origin-edge architecture.
Edge receives the transcoding result of origin-server and sends it out, so there is no transcoding on the edge.

**Comment by voipcall** [comment]
thank you
