### ISSUE TITLE
Password-protect stream?

### ISSUE THREAD

**Issue by loupaw** [AirenSoft/OvenMediaEngine#181]
Hi there, is it possible to password-protect a stream using OME, or OvenPlayer?

I have OvenPlayer embedded on a webpage. I would like viewers to need to enter a password when they visit my page. Once the password is entered, the stream loads / plays. 

Can someone tell me how I can accomplish this? 

Thank you

**Comment by getroot** [comment]
I still think it is a function that will be implemented in your web page It is not a feature implemented at the ome or ovenplayer level.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by lee-hammer99** [comment]
@loupaw 

Hello!
I'm the PR manager of OvenMediaEngine.

I want to know how well users are using OvenMediaEngine.
So, I collect the stories and introduce them to people.
Could you please email me at hammer99@airensoft.com?

Thank you for using OvenMediaEngine.
