### ISSUE TITLE
nginx conflict

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenMediaEngine#183]
i have a nginx proxy server mmmm into VESTACP packet and the OME does not start until stop nginx.
nginx version: nginx/1.18.0
Centos 7
What could be the problem?
thanks

**Comment by getroot** [comment]
There is too little information to analyze the problem.
Upload ovenmediaengine.log file

**Comment by peterpetrov** [comment]
@alnux probably you have default configuration of nginx to bind to port 80. By default OME uses port 80. Maybe you want to configure OME and nginx to bind to different IP addresses or hostnames and change ports so they are not in conflict?

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
