### ISSUE TITLE
OVT can't get url paramater.

### ISSUE THREAD

**Issue by huukhuongnguyen** [AirenSoft/OvenMediaEngine#184]
I have origin and edge oven config as follows:
Origin:
```
<Origins>
	<Origin>
		<Location>/</Location>
		<Pass>
			<Scheme>rtsp</Scheme>
			<Urls>
				<Url>admin:admin@14.xx.xx.xx:554/</Url>
			</Urls>
		</Pass>
	</Origin>
</Origins>

```

Edge:
```
<Origin>
	<Location>/</Location>
	<Pass>
		<Scheme>ovt</Scheme>
		<Urls>
			<Url>originIP:9000/</Url>
		</Urls>
	</Pass>
</Origin> 

```
When I call "ws://edgeIP:3333/cam/realmonitor?channel=2&subtype=0" in browser
Origin error:
**[2020-08-26 14:16:05.281] I 11326 Orchestrator | orchestrator.cpp:1280 | Trying to pull stream [#default#cam/realmonitor] from provider using origin map: PullProvider
[2020-08-26 14:16:05.281] I 11326 RtspcStream | rtspc_stream.cpp:163  | Requested url[55] : rtsp://admin:admin@14.xx.xx.xx:554/cam/realmonitor
[2020-08-26 14:16:05.386] E 11326 FFmpeg | third_parties.cpp:111  |  [AVFormatContext] method DESCRIBE failed: 404 Not Found**

When I call ws://edgeIP:3333/cam/realmonitorchannel=2&subtype=0 not character "?"
**[2020-08-26 14:16:05.281] I 11326 Orchestrator | orchestrator.cpp:1280 | Trying to pull stream [#default#cam/realmonitorchannel=2&subtype=0] from provider using origin map: PullProvider**

Thank your watching !

**Comment by getroot** [comment]
It seems that we are removing the query string from the WebRTC URL. This will be fixed soon. Thanks for reporting the problem.

**Comment by getroot** [comment]
I've analyzed this.
We were not using the query string that was requested when making a request to the Origin server. This needs some time because it needs some structural improvement. We will improve this.

**Comment by dimiden** [comment]
@huukhuongnguyen 
I just solved the problem where URL parameter is not passed. Thank you!
