### ISSUE TITLE
TURN / STUN required?

### ISSUE THREAD

**Issue by Edulcorate** [AirenSoft/OvenMediaEngine#185]
I have read a lot about TURN and STUN servers and how they relate to WebRTC, BUT I cannot work out if they are definitely needed when the application is a one-to-many broadcast, or only needed if the application includes peer to peer connections ie. video conferencing? 

My use case is stream rtmp to OME server hosted on DigitalOcean, WebRTC playback (with HLS fallback) of that stream by a maximum of 20 viewers from various locations.

**Comment by getroot** [comment]
If OvenMediaEngine is running on PUBLIC IP, there is no need to connect stun and turn to the player.
