### ISSUE TITLE
Can't access stream via Cable Internet. VDSL / LTE works just fine...

### ISSUE THREAD

**Issue by risingSilence** [AirenSoft/OvenMediaEngine#188]
All my mates who have Cable connection can't load the stream. They get occasional stand-still images, but that's it.
LLDASH Stream.
Tried normal DASH, same issue...

When I setup an LLDASH Stream via ffmpeg, there are no issues (as expected)
But I can't get OvenMediaEngine to work with Cable connections (provider is Vodafone Germany)...

I have Cable as a second connection as well, with an Ipv4 address.

Might that be an ipv6 issue?
Or is my config faulty?

//edit: I tried different (also the standard) ports as well. That's not the cause.

Config:

`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="7">
        <Name>OvenMediaEngine</Name>
        
        <Type>origin</Type>
        
        <IP>*</IP>

        
        <Bind>
                <Providers>
                        <RTMP>
                                <Port>1935</Port>
                        </RTMP>
                </Providers>

                <Publishers>
                        <DASH>
                                <Port>8082</Port>
								<TLSPort>8083</TLSPort>
                                
                                
                        </DASH>
                </Publishers>
        </Bind>

        
        

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>

                        
                        <Domain>
                                <Names>
                                        
                                        <Name>*</Name>
                                        <Name>private.de</Name>
                                        <Name>www.private.de</Name>
                                </Names>
                                <TLS>
                                        <CertPath>/etc/letsencrypt/live/private.de/fullchain.pem</CertPath>
                                        <KeyPath>/etc/letsencrypt/live/private.de/privkey.pem</KeyPath>
                                </TLS>
                                
                        </Domain>
                        
                        
                        <Applications>
                                <Application>
                                        <Name>app</Name>
                                        
                                        <Type>live</Type>
                                        <Encodes>
                                                <Encode>
                                                        <Name>bypass</Name>
                                                        <Audio>
                                                                <Bypass>true</Bypass>
                                                        </Audio>
                                                        <Video>
                                                                <Bypass>true</Bypass>
                                                        </Video>
                                                </Encode>
                                                <Encode>
                                                        <Name>opus</Name>
                                                        <Audio>
                                                                <Codec>opus</Codec>
                                                                <Bitrate>192000</Bitrate>
                                                                <Samplerate>48000</Samplerate>
                                                                <Channel>2</Channel>
                                                        </Audio>
                                                        <Video>
                                                                <Bypass>true</Bypass>
                                                        </Video>
                                                </Encode>
                                        </Encodes>
                                        <Streams>
                                                <Stream>
                                                        <Name>${OriginStreamName}</Name>
                                                        <Profiles>
                                                                <Profile>bypass</Profile>
                                                        </Profiles>
                                                </Stream>
                                        </Streams>
                                        <Providers>
                                                <RTMP>
                                                        <BlockDuplicateStreamName>true</BlockDuplicateStreamName>
                                                </RTMP>
                                        </Providers>
                                        <Publishers>
                                                <ThreadCount>16</ThreadCount>
                                                <LLDASH>
                                                        <SegmentDuration>4</SegmentDuration>
                                                        <CrossDomain>
                                                                <Url>*</Url>
                                                        </CrossDomain>
                                                </LLDASH>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>`

Runs on Ubuntu 18.04.
Everything works like a charm except for this weird issue...
Awesome to stream with in general btw. Managed an End-to-End-Latency of just 0.8s stable. Just VDSL / LTE though :D

**Comment by getroot** [comment]
OvenMediaEngine is not the cause of this problem. Maybe your mates are using a network with very high packet loss.
Check how high the packet loss is via chrome://webrtc-internals.

I am also curious about the cause of this problem. Once you know the cause, please share your experience.

**Comment by risingSilence** [comment]
My mistake. WEBRTC works flawlessly, also HLS and streaming basically anything with other tools. Its only OvenMediaEngine Dash and Dash-LL which we cant view with Vodafone Cable Internet. I tell you everyone provided by Vodafone Cable cant view the stream.

This is clearly strange. Im not saying its OME itself but what else can it be? Our internet works just fine...

**Comment by getroot** [comment]
We are aware that there is a problem with the MPEG-DASH streaming function. We know that issues like #162 may be the same. We are constantly looking for the source of the problem to make MPEG-DASH even more complete.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
