### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by marciocamello** [AirenSoft/OvenMediaEngine#19]
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

   - Operating system        : linux
   - Core count              : 2
   - GCC version             : 7.4.0
   - Build option            : RELEASE
   - Total Projects count    : 26

/usr/local/lib/libsrtp2.a(hmac_ossl.o): In function `srtp_hmac_dealloc':
hmac_ossl.c:(.text+0xd9): undefined reference to `HMAC_CTX_cleanup'
/usr/local/lib/libsrtp2.a(hmac_ossl.o): In function `srtp_hmac_alloc':
hmac_ossl.c:(.text+0x296): undefined reference to `HMAC_CTX_init'
collect2: error: ld returned 1 exit status
core/build_executable.mk:7: recipe for target 'bin/RELEASE/OvenMediaEngine' failed

**Comment by sfreet** [comment]
Hello @marciocamello 

Could you run the following command and show me the result?
```
benjamin:~$ openssl version 
OpenSSL 1.1.0g  2 Nov 2017
```
```
benjamin:~$ strings /usr/local/lib/libsrtp2.a | grep HMAC_CTX
HMAC_CTX_free
HMAC_CTX_new
```
```
benjamin:~/Work/OvenMediaEngine/src/bin/RELEASE$ ldd OvenMediaEngine | grep ssl
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f6a939b8000)
```

**Comment by marciocamello** [comment]
Hi sfreet 

OpenSSL 1.1.0g  2 Nov 2017

HMAC_CTX_cleanup
HMAC_CTX_init

**Comment by sfreet** [comment]
Did you installed libressl instead of libssl-dev?

**Comment by marciocamello** [comment]
no, i am install libssl-dev 

libssl-dev is already the newest version (1.1.0g-2ubuntu4.3).
Os seguintes pacotes foram instalados automaticamente e já não são necessários:
  g++-5 javascript-common libass5 libboost-filesystem1.58.0 libboost-system1.58.0 libcapnp-0.5.3 libegl1-mesa libfdk-aac0 libgles2-mesa libjs-excanvas libllvm6.0 libprotobuf-lite9v5 libprotobuf9v5 libpython3.5
  libtxc-dxtn-s2tc0 libva-drm1 libva-egl1 libva-glx1 libva-tpi1 libva-wayland1 libva-x11-1 libva1 libvpx3 libwayland-egl1-mesa x11proto-dri2-dev x11proto-gl-dev

**Comment by sfreet** [comment]
The message shows that the srtp library refers to a previous version of the ssl library or libressl.

I get the following message now in the following.
(install libressl -> install libsrtp -> uninstall libressl -> install libssl-dev -> compile OvenmediaEngine)
```
/usr/local/lib/libsrtp2.a(hmac_ossl.o): In function `srtp_hmac_dealloc':
hmac_ossl.c:(.text+0xd9): undefined reference to `HMAC_CTX_cleanup'
/usr/local/lib/libsrtp2.a(hmac_ossl.o): In function `srtp_hmac_alloc':
hmac_ossl.c:(.text+0x235): undefined reference to `HMAC_CTX_init'
collect2: error: ld returned 1 exit status
core/build_executable.mk:7: recipe for target 'bin/DEBUG/OvenMediaEngine' failed
```

In this situation, I solved it as follow. (recompile and reinstall libsrtp)
```
$ sudo apt-get install libssl-dev => Try it again to make sure. 
$ (curl -OL https://github.com/cisco/libsrtp/archive/v2.2.0.tar.gz && tar xvfz v2.2.0.tar.gz && cd libsrtp-2.2.0 && ./configure --enable-openssl && make && sudo make install)
```
If libsrtp installation is finished and the output is as follows, it will work. 
```
$ strings /usr/local/lib/libsrtp2.a | grep HMAC_CTX
HMAC_CTX_free
HMAC_CTX_new
```
(Try to run again "make clean" and "make"  OvenMediaengine source)

If the issue is not resolved, please let me know again.

**Comment by marciocamello** [comment]
Thanks, i am create a Dockerfile :D and resolve that
