### ISSUE TITLE
2020-09-11T09:45:29.266334289Z [2020-09-11 09:45:29.266] E 79 RtmpProvider | rtmp_stream.cpp:962  | Input create fail -  stream(#default#app/stream)

### ISSUE THREAD

**Issue by jys923** [AirenSoft/OvenMediaEngine#192]
Describe the bug
While streaming to rtmp, the transmission was stopped due to a network problem.
I tried to connect again with the same stream key
2020-09-11T09:45:29.266334289Z [2020-09-11 09:45:29.266] E 79 RtmpProvider | rtmp_stream.cpp:962 | Input create fail-stream(#default#app/stream)
An error occurs.

To Reproduce

Set Server.xml as follows '...'
With Encoder '...' [e.g. Use OBS Version]
See error
Server.xml.txt
I tested ThreadCount:48,8,16
Obs setting is x264 without GPU As posted in the tutorial
I only changed the bit rate.

Expected behavior
Can be transmitted with the same stream key.

Logs
Please upload the entire OvenMediaEngine.log. You may delete important personal information.
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/5208150/ovenmediaengine.log)
[ovenmediaengine_webrtc_stat.log](https://github.com/AirenSoft/OvenMediaEngine/files/5208151/ovenmediaengine_webrtc_stat.log)

Server (please complete the following information):

OS: [e.g. iOS] ubuntu 18.04
OvenMediaEngine Version: [e.g. v0.10.1] 0.10.7 docker
Branch: [e.g. dev] release
Cpu
-AMD EPYC 7402 24-Core Processor
24core 48 thread
-Mem
125G
-Network
1879.85Mbps
Player (please complete the following information):

Device: pc windows 10
OS: windows 10
Browser chrome
Version [e.g. 22] 85.0.4183.102 latest
network-150Mbps
There is an intermittent freeze in webrtc.
Player (please complete the following information):

Device: mobile
OS: android,ios
Browser chrome
Version
network-90.51Mbps
There is more intermittent freeze than pc.
Additional context

**Comment by getroot** [comment]
This seems to be the same problem as #175. Let's continue discussing this at #175. So this issue is closed.
