### ISSUE TITLE
For production setup do you recommend to wait for a Release or use master?

### ISSUE THREAD

**Issue by cesarandreslopez** [AirenSoft/OvenMediaEngine#194]
I do understand that you tend to create a separate branch when you are testing stuff out. I am just wondering if for this project the rule of thumb it wiser to build and update my dockerfile on:

OME_VERSION=(latest released version)
or
OME_VERSION=master

Any comments will be appreciated.

**Comment by getroot** [comment]
I recommend that you use "OME_VERSION=(latest released version)" when building Docker. Master is a version under development, so it is a branch that has not been fully tested.

**Comment by lee-hammer99** [comment]
@cesarandreslopez 

Hello!
I'm the PR manager of OvenMediaEngine.

I want to collect your story about the use of OvenMediaEnigne because it's helpful to our users.
Would you please email me at [hammer99@airensoft.com](mailto:hammer99@airensoft.com)?

Thank you for using OvenMediaEngine.
