### ISSUE TITLE
5.1+ audio channel support

### ISSUE THREAD

**Issue by S3-sim** [AirenSoft/OvenMediaEngine#199]
Hi,

I am checking to see if it is possible to have more than 2 channels of audio in a single webrtc stream. I see that in the server config that you can set the number of audio channels in the encoding section and when i set it to a number greater than two, there does not appear to be any errors.

I am unable to verify in any way if there are more than 2 audio channels in the stream on the client end as the webrtc statistics pages in both chrome and firefox do no appear to give you an audio channel count.

I know at the moment browsers do no support multi channel audio beyond stereo well, if at all. The end goal is the development of an Android based player that can support multi channel audio.

**Comment by getroot** [comment]
Here's a great article on WebRTC Audio. Please refer to this.

http://webrtcbydralex.com/index.php/2020/04/08/surround-sound-5-1-and-7-1-in-libwebrtc-and-chrome/

**Comment by getroot** [comment]
If you develop an Android player and improve OPUS' RTP packetizer in OME, this is possible. (I don't know yet about RTP packetizing for surround OPUS.) If you are interested in modifying OME, let me know again.

**Comment by S3-sim** [comment]
Sounds good. We will look into this and see if this is something that we can contribute.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
