### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by sorrowhill** [AirenSoft/OvenMediaEngine#2]
In previous pull request(#1 ), there are some requirements for docker support.

- Requirements
  - The container for deployment must be alpine Linux.
  - The container must have C++14 full-support(based on gcc 7).  
  - The size of the image should as small as possible.

I propose that the image should be split by the two purpose. one is for development and continuous integration, another is for deployment(with optimized binary).

**Comment by JehoenHan** [comment]
It's a good idea. If you help this, it will be a great help to our project.

**Comment by sorrowhill** [comment]
I managed to build the image for building the binary from scratch.

    ome_core            0.2                 e379f7814642        Less than a second ago   564MB

Note that it contains a lot of build tools so the image is not ready for the deployment yet. I'm expecting that the estimated size of the deployment image will not be more than 40MB. 

The total size of the below files is 20-25MB. and the size of the base image is 5MB.

    bash-4.4# ldd main 
      /lib/ld-musl-x86_64.so.1 (0x7ffab7cd5000)
      libavfilter.so.6 => /usr/local/lib/libavfilter.so.6 (0x7ffab772c000)
      libavcodec.so.57 => /usr/local/lib/libavcodec.so.57 (0x7ffab635b000)
      libavutil.so.55 => /usr/local/lib/libavutil.so.55 (0x7ffab60dc000)
      libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x7ffab5e6c000)
      libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x7ffab59ed000)
      libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7ffab569b000)
      libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7ffab5489000)
      libc.so => /lib/ld-musl-x86_64.so.1 (0x7ffab7cd5000)
      libswscale.so.4 => /usr/local/lib/libswscale.so.4 (0x7ffab5200000)
      libswresample.so.2 => /usr/local/lib/libswresample.so.2 (0x7ffab4fe3000)
      libvpx.so.5 => /usr/local/lib/libvpx.so.5 (0x7ffab4ba1000)
      libopus.so.0 => /usr/local/lib/libopus.so.0 (0x7ffab4953000)
      libz.so.1 => /lib/libz.so.1 (0x7ffab473c000)

Before continuing, there are few things that you might want to know.

1. `OpenSSL`: `no-async` must be specified while building the library. I don't know the project is currently using the library's async operation, but musl-libc does not support the several functions that are used in async operation because they are marked as deprecated. 

2. `libvpx`: verifying the version of diff failed. because diff does not support the version option in Alpine Linux. I'm working around by injecting a code(`sed -i 's/die "diff missing*/echo "skip the diff verification/g'`) before building the library.

I'll let you know when the image is ready to publish, but you will need a deployment system, to make the generated binary downloadable.

**Comment by marciocamello** [comment]
My first contribution :D

docker-compose.yml

version: "3.1"

services:
  ovenmediaEngine:
    image: ovenmedia-engine:1.0
    container_name: ovenmedia-engine
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    privileged: true
    restart: always
    ports:
      - "1935:1935/tcp"
      - "9000:9000/udp"
      - "8086:80/tcp"
      - "3333:3333/tcp"
      - "10000-10005:10000-10005/udp"

Dockerfile

FROM ubuntu:bionic

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    apt-utils \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    apt-transport-https \
    dialog

RUN apt-get upgrade -y

RUN apt-get install nano htop rsync git build-essential nasm autoconf libtool zlib1g-dev libssl-dev libvpx-dev libopus-dev pkg-config libfdk-aac-dev tclsh cmake -y

RUN curl -OL https://github.com/cisco/libsrtp/archive/v2.2.0.tar.gz && tar xvfz v2.2.0.tar.gz && cd libsrtp-2.2.0 && \
    ./configure --enable-openssl && make && make install

RUN curl -OL http://ciscobinary.openh264.org/libopenh264-1.8.0-linux64.4.so.bz2 && \
    bzip2 -d libopenh264-1.8.0-linux64.4.so.bz2 && mv libopenh264-1.8.0-linux64.4.so /usr/lib && \
    ln -s /usr/lib/libopenh264-1.8.0-linux64.4.so /usr/lib/libopenh264.so && \
    ln -s /usr/lib/libopenh264-1.8.0-linux64.4.so /usr/lib/libopenh264.so.4

RUN curl -OL https://github.com/Haivision/srt/archive/v1.3.1.tar.gz && \
    tar xvf v1.3.1.tar.gz && cd srt-1.3.1 && \
    ./configure && make && make install

RUN curl -OL https://www.ffmpeg.org/releases/ffmpeg-3.4.2.tar.xz && \
    xz -d ffmpeg-3.4.2.tar.xz && tar xvf ffmpeg-3.4.2.tar && cd ffmpeg-3.4.2 && ./configure \
    --disable-static --enable-shared \
    --extra-libs=-ldl \
    --enable-ffprobe \
    --disable-ffplay --disable-ffserver --disable-filters --disable-vaapi --disable-avdevice --disable-doc --disable-symver --disable-debug --disable-indevs --disable-outdevs --disable-devices --disable-hwaccels --disable-encoders \
    --enable-zlib --enable-libopus --enable-libvpx --enable-libfdk_aac \
    --enable-encoder=libvpx_vp8,libvpx_vp9,libopus,libfdk_aac \
    --disable-decoder=tiff \
    --enable-filter=asetnsamples,aresample,aformat,channelmap,channelsplit,scale,transpose,fps,settb,asettb && \
    make && make install && ldconfig

RUN apt-get install --reinstall systemd bc -y

RUN git clone "https://github.com/AirenSoft/OvenMediaEngine" && \
    cd OvenMediaEngine/src && \
    make release && \
    make install

CMD ["/usr/share/ovenmediaengine/OvenMediaEngine"]

**Comment by sfreet** [comment]
Thanks for your contribution @marciocamello.
We will be updating soon to reflect your code. :)

**Comment by JehoenHan** [comment]
We will make a docker image based on alpine linux in version 1.0.

**Comment by JehoenHan** [comment]
This is a Dockerfile from alpine linux. Docker version is not stable yet. 
https://github.com/AirenSoft/OvenMediaEngine/blob/temp/alpine/Dockerfile

And DockerHub link is follow
https://hub.docker.com/r/airensoft/ovenmediaengine

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
