### ISSUE TITLE
Chrome and Safari WebRTC Stereo Audio Downmix To Mono

### ISSUE THREAD

**Issue by S3-sim** [AirenSoft/OvenMediaEngine#203]
Hi,

During testing, we noticed that WebRTC stereo audio is being downmixed to mono within chrome and safari. Firefox is working as expected. It appears that the issue is related to this open issue (https://bugs.chromium.org/p/webrtc/issues/detail?id=8133). I believe they also outline a potential work around in the thread.

I took a look at the SDPs in both Chrome and Firefox and here are the results:

**Firefox**:

**Remote SDP (Offer)**
v=0
o=OvenMediaEngine 185 2 IN IP4 127.0.0.1
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 46:49:BF:FE:6D:2B:F4:9E:9E:D9:66:26:74:C2:EB:32:7E:4A:EE:E5:BE:D6:B9:E8:B4:F7:75:6E:99:20:22:73
a=group:BUNDLE zXH0iB RdVpcH
a=group:LS zXH0iB RdVpcH
a=ice-options:trickle
a=ice-pwd:SeMpaG7VzfD9oKwC34yLUrli2Q0XhcNd
a=ice-ufrag:RnYSO2
a=msid-semantic:WMS *
m=video 9 UDP/TLS/RTP/SAVPF 100 123 124
c=IN IP4 0.0.0.0
a=candidate:0 1 UDP 50 206.223.175.46 10000 typ host
a=candidate:0 1 UDP 50 tor-streaming1.simgroup.com 10000 typ host
a=candidate:0 1 UDP 50 206.223.175.46 10001 typ host
a=candidate:0 1 UDP 50 tor-streaming1.simgroup.com 10001 typ host
a=candidate:0 1 UDP 50 206.223.175.46 10002 typ host
a=candidate:0 1 UDP 50 tor-streaming1.simgroup.com 10002 typ host
a=candidate:0 1 UDP 50 206.223.175.46 10003 typ host
a=candidate:0 1 UDP 50 tor-streaming1.simgroup.com 10003 typ host
a=candidate:0 1 UDP 50 206.223.175.46 10004 typ host
a=candidate:0 1 UDP 50 tor-streaming1.simgroup.com 10004 typ host
a=candidate:0 1 UDP 50 206.223.175.46 10005 typ host
a=candidate:0 1 UDP 50 tor-streaming1.simgroup.com 10005 typ host
a=sendonly
a=fmtp:100 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=mid:zXH0iB
a=rtcp-mux
a=rtpmap:100 H264/90000
a=rtpmap:123 red/90000
a=rtpmap:124 ulpfec/90000
a=setup:actpass
a=ssrc:2777717003 cname:59yJn3EKFtsBdoPI
m=audio 9 UDP/TLS/RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=sendonly
**_a=fmtp:101 maxplaybackrate=0;stereo=1;useinbandfec=1_**
a=mid:RdVpcH
a=rtcp-mux
a=rtpmap:101 OPUS/48000/2
a=setup:actpass
a=ssrc:2186315321 cname:oSkaJiXyQnM3VNtf

**Local SDP (Answer)**
v=0
o=mozilla...THIS_IS_SDPARTA-81.0.2 6764951583310796830 0 IN IP4 0.0.0.0
s=-
t=0 0
a=sendrecv
a=fingerprint:sha-256 CB:B2:8E:FD:34:14:5A:FD:60:C1:D4:4E:08:54:47:92:D6:12:32:CA:BD:E1:05:22:42:F5:1E:7F:A2:7F:E6:AD
a=group:BUNDLE zXH0iB RdVpcH
a=ice-options:trickle
a=msid-semantic:WMS *
m=video 65197 UDP/TLS/RTP/SAVPF 100
c=IN IP4 158.247.84.36
a=candidate:0 1 UDP 2122252543 192.168.1.13 57279 typ host
a=candidate:2 1 UDP 2122121471 25.43.42.25 60666 typ host
a=candidate:4 1 UDP 2122187007 2620:9b::192b:2a19 60667 typ host
a=candidate:6 1 TCP 2105524479 192.168.1.13 9 typ host tcptype active
a=candidate:7 1 TCP 2105393407 25.43.42.25 9 typ host tcptype active
a=candidate:8 1 TCP 2105458943 2620:9b::192b:2a19 9 typ host tcptype active
a=candidate:1 1 UDP 1686052863 158.247.84.36 57279 typ srflx raddr 192.168.1.13 rport 57279
a=recvonly
a=fmtp:100 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1
a=ice-pwd:5f2bb6a0a3c38c3dbdc13ce7b11630f7
a=ice-ufrag:22e0b246
a=mid:zXH0iB
a=rtcp-mux
a=rtpmap:100 H264/90000
a=setup:active
a=ssrc:2054236217 cname:{40fb2a01-17dd-da4c-a06e-1dfa57e1684c}
m=audio 65197 UDP/TLS/RTP/SAVPF 101
c=IN IP4 158.247.84.36
a=recvonly
**_a=fmtp:101 maxplaybackrate=48000;stereo=1;useinbandfec=1_**
a=ice-pwd:5f2bb6a0a3c38c3dbdc13ce7b11630f7
a=ice-ufrag:22e0b246
a=mid:RdVpcH
a=rtcp-mux
a=rtpmap:101 opus/48000/2
a=setup:active
a=ssrc:332544955 cname:{40fb2a01-17dd-da4c-a06e-1dfa57e1684c}

**Chrome:**

**Remote SDP:**
type: offer, sdp: v=0
o=OvenMediaEngine 184 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE zXH0iB RdVpcH
a=group:LS zXH0iB RdVpcH
a=msid-semantic:WMS *
a=fingerprint:sha-256 46:49:BF:FE:6D:2B:F4:9E:9E:D9:66:26:74:C2:EB:32:7E:4A:EE:E5:BE:D6:B9:E8:B4:F7:75:6E:99:20:22:73
a=ice-options:trickle
a=ice-ufrag:l8d5w0
a=ice-pwd:SeMpaG7VzfD9oKwC34yLUrli2Q0XhcNd
m=video 9 UDP/TLS/RTP/SAVPF 100 123 124
c=IN IP4 0.0.0.0
a=sendonly
a=mid:zXH0iB
a=setup:actpass
a=rtcp-mux
a=rtpmap:100 H264/90000
a=fmtp:100 packetization-mode=1;profile-level-id=42e01f;level-asymmetry-allowed=1
a=rtpmap:123 red/90000
a=rtpmap:124 ulpfec/90000
a=ssrc:2777717003 cname:59yJn3EKFtsBdoPI
m=audio 9 UDP/TLS/RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=sendonly
a=mid:RdVpcH
a=setup:actpass
a=rtcp-mux
a=rtpmap:101 OPUS/48000/2
**_a=fmtp:101 stereo=1;useinbandfec=1;_**
a=ssrc:2186315321 cname:oSkaJiXyQnM3VNtf

**Local SDP:**
type: answer, sdp: v=0
o=- 198535782674667087 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE zXH0iB RdVpcH
a=msid-semantic: WMS
m=video 9 UDP/TLS/RTP/SAVPF 100 123 124
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Dtkl
a=ice-pwd:wrj/3ldHemyllPO4DK0nRuW4
a=ice-options:trickle
a=fingerprint:sha-256 07:C0:29:E9:20:DF:1B:BC:98:32:B8:89:D2:7E:44:8A:4E:B9:25:FB:01:55:F9:EF:B4:0D:B4:28:46:98:2B:C1
a=setup:active
a=mid:zXH0iB
a=recvonly
a=rtcp-mux
a=rtpmap:100 H264/90000
a=fmtp:100 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:123 red/90000
a=rtpmap:124 ulpfec/90000
m=audio 9 UDP/TLS/RTP/SAVPF 101
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Dtkl
a=ice-pwd:wrj/3ldHemyllPO4DK0nRuW4
a=ice-options:trickle
a=fingerprint:sha-256 07:C0:29:E9:20:DF:1B:BC:98:32:B8:89:D2:7E:44:8A:4E:B9:25:FB:01:55:F9:EF:B4:0D:B4:28:46:98:2B:C1
a=setup:active
a=mid:RdVpcH
a=recvonly
a=rtcp-mux
a=rtpmap:101 OPUS/48000/2
**_a=fmtp:101 minptime=10;useinbandfec=1_**

It looks like Chrome is dropping the stereo=1 flag on its response while Firefox is keeping it. Also, it seems like audio playback in firefox has pops more often than Chrome. I monitored the jitter and packet loss and the pops did not seem to always correspond with network errors. Could this be a byproduct of firefox not setting minptime=10 like chrome does?

Not sure if this belongs in the player repo or the ovenmediaengine repo. Please let me know if you want me to move this issue.

**Server (please complete the following information):**
 - OS: ubuntu
 - OvenMediaEngine Version: 0.10.2
 - Branch: main

**Player (please complete the following information):**
 - Device: Mac and Windows
 - OS: High Sierra / Windows 10
 - Browser: Safari and Chrome
 - Version: Chrome: 86.0.4240.75

I am working on updating our OME server to 0.10.8, but our system is currently in production and I need to spinup a test environment to run it in.

**Comment by getroot** [comment]
Thank you for providing good information.
I haven't thought deeply about this issue yet. What do you think OvenMediaEngine should do? (Maybe I should wait for a bug patch from Chrome?)

**Comment by S3-sim** [comment]
You'll have to forgive me for I am not a developer and I'm teaching myself this as I go.

It looks like there is a work around that was posted in the thread https://bugs.chromium.org/p/webrtc/issues/detail?id=8133#c28

Comments 25 and 28 detail that get around the issue, though it is non-spec for webrtc. The more I read into the issue, the more it looks like fix actually needs to be applied on the client end via the ovenmediaplayer and not the server side since the server is working as expected. 

I'm not sure if waiting for chrome to patch the issue would be a good idea as it looks like this has been an on going issue for several years without any indication that they are actively working on it.

Should i post this information in the OvenMediaPlayer repo?

**Comment by getroot** [comment]
Thank you for providing very good information.
This is what OvenMediaEngine has to handle. I will go into more detail on this after completing the task in progress now.

**Comment by getroot** [comment]
I've tried a lot of different attempts to fix chrome's weird behavior, but in the end no success. Firefox now plays stereo very well on OME. I no longer have any ideas to solve the problem in chrome.

Please let me know if anyone has a way to fix this.

**Comment by S3-sim** [comment]
Hey,

I was looking at Millicast and it looks like their player may have a role in enabling stereo.

https://github.com/millicast/millicast_javascript_demo/blob/master/viewer.html

Specifically these lines here looks like they have to manually change the sdp to force stereo.

`//create a WebRTC offer to send to the media server
      let offer = pc.createOffer({ offerToReceiveAudio: true, offerToReceiveVideo: true })
        .then(desc => {
          console.log('createOffer Success!');
          //support for stereo
          desc.sdp = desc.sdp.replace("useinbandfec=1", "useinbandfec=1; stereo=1");
          //try for multiopus (surround sound) support
          try {
            desc.sdp = setMultiopus(desc);
          } catch(e){
            console.log('create offer stereo',offer);
          }`


Hope this helps!

**Comment by getroot** [comment]
@S3-sim I've tried this before, but in the end it didn't output as stereo. chrome is behaving weird.

**Comment by dbContext** [comment]
@getroot Have you attempted to alter the SDP to include multi OPUS? 

https://github.com/millicast/millicast_javascript_demo/blob/master/viewer.html#L418

**Comment by getroot** [comment]
@dbContext 
I've tested it on the URL below for multiopus.

https://sgmedooze.cosmosoftware.io/multiopus/

In my chrome, AAC 5.1 worked fine, but OPUS 5.1 didn't. So I was thinking this was still unfinished.

**Comment by dbContext** [comment]
@getroot 

Seems there is a Javascript Error regarding the OPUS 5.1 player, within multiopus.js:57

![image](https://user-images.githubusercontent.com/55065793/99376972-8c238480-28bd-11eb-96db-bae46a47948a.png)

captureStream() doesn't seem to be a function that exists.

Keep me updated, and if it isn't resolved by the time i've completed the works on #201 then i'll take a look.

**Comment by Dave3o3** [comment]
Seems like there is a [possible workaround](https://bugs.chromium.org/p/webrtc/issues/detail?id=8133#c53) until [this is fixed in Chrome v89](https://bugs.chromium.org/p/webrtc/issues/detail?id=8133#c54) (which is currently the dev channel).

**Comment by S3-sim** [comment]
Thanks David,

I wonder when this fix will also hit Safari. I have not checked recently, but it was also broken there as well.



[https://www.siminternational.com/siglogo/simlogo/sim144dpi135x69.jpg]

siminternational.com

[https://www.siminternational.com/wp-content/uploads/2020/12/Linkedin.png]<https://www.linkedin.com/company/simcomplete/>  [https://www.siminternational.com/wp-content/uploads/2020/12/instagram.png] <https://www.instagram.com/simcomplete/?hl=en>   [https://www.siminternational.com/wp-content/uploads/2020/12/Facebook.png] <https://www.facebook.com/Simcomplete>



Sean Burt | Technician
260 King St East, Suite A-102 Toronto ON M5A 4L5
T (416) 703-7555


Studios  |  Camera  |  Lighting + Grip  |  Post

Sim is a proud supporter of the Creative Industries Pact for Sustainable Action<https://creativeindustriespact.com/>









________________________________

**Comment by getroot** [comment]
@Dave3o3 Thank you!

**Comment by S3-sim** [comment]
Hey,

The following appears to fix the issue in the Ovenplayer code:

        //Set remote description when I received sdp from server.
        peerConnection.setRemoteDescription(new RTCSessionDescription(sdp)).then(function () {
            peerConnection.createAnswer().then(function (desc) {
              desc.sdp = desc.sdp.replace("useinbandfec=1", "useinbandfec=1; stereo=1");
                OvenPlayerConsole.log("create Host Answer : success");

**Comment by getroot** [comment]
@S3-sim 
Forcing stereo=1 I've tried before, but it doesn't output stereo in chrome. Do you mean this attempt was successful on the latest chrome?

**Comment by S3-sim** [comment]
@getroot 

yeah, I’ve confirmed it works on a couple of versions of chrome. I can confirm the exact versions tomorrow when I’m at work.

**Comment by fcqpl** [comment]
@getroot
Chrome 91.0.4472.77 - OvenPlayer downloaded from https://github.com/AirenSoft/OvenPlayer/tree/master/dist/production/ovenplayer - without stereo audio

When I made patch to "ovenplayer.provider.WebRTCProvider.js" file like this comment - https://github.com/AirenSoft/OvenMediaEngine/issues/203#issuecomment-762334945 it's works correctly - i have stereo audio.

Could You change it in OvenPlayer?
https://github.com/AirenSoft/OvenPlayer/issues/155

**Comment by getroot** [comment]
@fcqpl Thanks for providing good information. I'm going to run some tests and apply this!

**Comment by SangwonOh** [comment]
Confirmed that "Forcing stereo = 1" works well. Applied to OvenPlayer. thank.
