### ISSUE TITLE
HLS and DASH file locations

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#205]
Hello,

This is a great piece of software! Thank you for all your hard work.

Currently I've got nginx-rtmp setup to take in RTMP and output HLS, dash, and RTMP for playing. I'd like to add OME as a client to nginx-rtmp to serve WebRTC and LL-Dash players.

We've also got a separate nginx reverse proxy to handle http->https and to serve HLS and Dash manifests. I'd like to add LLDash in a similar manner, where OME simply generates the manifest files and they are served by our nginx proxy.

To that end, where does OME store the manifest_ll.mpd files for each incoming stream? (And the associated chunk files, of course)

Thanks

**Comment by getroot** [comment]
OvenMediaEngine does not write to a file. It only writes to memory and can only be accessed with a URL like this: http://domain/app/stream/manifest_ll.mpd

**Comment by naanlizard** [comment]
Thank you.

What is the behavior of OME if the SSL cert is updated while it is running? Does it need to restart to see and use the new certificate? 

I believe I can reverse proxy in the normal fashion to translate public HTTPS requests to internal http requests to OME for LLDash, but I am concerned about how webrtc connections are handled, and if they can be proxied in the same way with nginx.

Thanks again for your hard work, OME is excellent software in my testing so far.

**Comment by getroot** [comment]
There is currently no function to dynamically load SSL certificates. To do that, you need to restart the server.

Unfortunately I only have very little experience with nginx, so I don't know how it works. Let us know later about your use-case and integration with nginx, which will be of great help to our project. That would be a great contribution to the OvenMediaEngine open source.

**Comment by naanlizard** [comment]
Will do, I'll try and write some documentation on using nginx as an SSL proxy, I suspect it will work well.

**Comment by naanlizard** [comment]
One more question I couldn't find in the docs, I'm sorry but I don't know where to put little questions (is there an IRC channel, slack, Discord, anything?)

With only 5 available ports for WebRTC (10000-10005), is there a viewer limit, either per-stream or overall? Will I need to open more ports to support more viewers, and if so, how many ports per viewer? Hopefully not 1:1

Thanks

**Comment by getroot** [comment]
don’t worry about that, not 1:1,
see benchmark page on  https://www.ovenmediaengine.com/

**Comment by naanlizard** [comment]
Hmm, is the benchmark for an RTMP input stream, WebRTC output? That is the primary use case I'll have, along with LLDash.

**Comment by getroot** [comment]
RTMP input WEBRTC output benchmark is correct.
However, it was tested a long time ago, so it is not up to date.
We will do this test once more later this year.

If there is no problem with this issue, please close the issue.

**Comment by lee-hammer99** [comment]
@naanlizard 

Hello!
I'm the PR manager of OvenMediaEngine.
Did our answers help you get started with OvenMediaEngine?

I'd love to hear more about your story using OvenMediaEngine.
Would you please email me at [hammer99@airensoft.com](mailto:hammer99@airensoft.com)?

I hope that OvenMediaEngine will always support your project nicely!
