### ISSUE TITLE
Unable to stream rtmp

### ISSUE THREAD

**Issue by bhanuc** [AirenSoft/OvenMediaEngine#206]
**Describe the bug**
I am running a default installation using docker-compose but I am unable to publish a stream using OBS or the OvenStreamEncoder android app.

**To Reproduce**
1. git clone https://github.com/AirenSoft/OvenMediaEngine
2. cd OvenMediaEngine
3. docker-compose up -d

URL in use - rtmp://45.77.241.8:1935/app/stream

**Expected behavior**
Should be able to stream but the origin seems to be dropping the connection

**Logs**

origin_1  | [2020-10-26 08:42:21.655] W 83 RtmpPush | rtmppush_publisher.cpp:108  | There is no such stream. (#default#app/stream)
origin_1  | [2020-10-26 08:42:22.304] I 107 Provider | stream.cpp:49   | Unknown/(35) has been started stream
origin_1  | [2020-10-26 08:42:22.304] I 107 RtmpProvider | rtmp_provider.cpp:93   | A RTMP client has connected from 35 - <ClientSocket: 0x7f25d8000b90, #35, state: 4, TCP, 27.63.60.179:1740>
origin_1  | [2020-10-26 08:42:22.551] E 94 RtmpProvider | rtmp_stream.cpp:217  | #default#_default_app/stream application does not exist
origin_1  | [2020-10-26 08:42:22.551] I 94 RtmpProvider | rtmp_provider.cpp:118  | The RTMP client has disconnected: [Unknown/], remote: <ClientSocket: 0x7f25d8000b90, #35, state: 4, TCP, 27.63.60.179:1740>
origin_1  | [2020-10-26 08:42:22.551] I 94 Provider | stream.cpp:55   | Unknown/(35) has been stopped playing stream
**Server (please complete the following information):**
 - OS: Debian 10
 - OvenMediaEngine Version: latest master
 - Branch: master(also tried release branch)

**Player (please complete the following information):**
Not relevant

**Comment by getroot** [comment]
I installed a clean ubuntu 18.04 with VirtualBox and tried to reproduce this problem. But I failed to reproduce. Works well. I need more information. Maybe delete docker rmi airensoft/ovenmediaengine:latest and try again.



![image](https://user-images.githubusercontent.com/17779085/97167655-88bf4080-17ca-11eb-9186-803697add4f8.png)

**Comment by bhanuc** [comment]
I tried the same in base ubuntu server hosted in vultr.
Still getting same error for trying to stream from obs or the mobile app. Kindly let me know what else should I share. As per the error stack, it seems the error originates from - rtmp_stream.cpp:217 which gets triggered when app_info.IsValid() returns false. Which if I am able to backtrace properly, just means that _application_id != InvalidApplicationId .

Not sure if we need to change anything when building from the repo.
@getroot kindly let me know what information you would want from my end, I can share access to the instance as well if required. 
Thanks in advance

**Comment by bhanuc** [comment]
When trying to run using command - docker run -d \
-p 1935:1935 -p 3333:3333 -p 8080:8080 -p 9000:9000/udp -p 10000-10005:10000-10005/udp \
airensoft/ovenmediaengine:latest

I am getting another error 
`2020-10-26 13:02:19.198] I 1 Provider | application.cpp:46   | RtspcProvider has created [#default#app] application
[2020-10-26 13:02:58.205] I 104 Provider | stream.cpp:49   | Unknown/(34) has been started stream
[2020-10-26 13:02:58.206] I 104 RtmpProvider | rtmp_provider.cpp:93   | A RTMP client has connected from 34 - <ClientSocket: 0x7f6ca5801010, #34, state: 4, TCP, 47.9.187.129:34336>
[2020-10-26 13:02:58.476] E 90 RtmpProvider | rtmp_stream.cpp:212  | Could not obtain app information
`  and obs is stuck in connecting

**Comment by bhanuc** [comment]
@getroot 
Getting same error when I am running the engine without docker -
[2020-10-26 13:44:09.825] I 1055 RtmpProvider | rtmp_server.cpp:149  | A RTMP client has connected from <ClientSocket: 0x7f6667e01010, #4, state: 4, TCP, 47.9.187.129:44036>
[2020-10-26 13:44:10.105] E 1043 RtmpProvider | rtmp_chunk_stream.cpp:697  | Could not obtain app information
[2020-10-26 13:44:22.974] W 1056 RtmpProvider | rtmp_server.cpp:370  | RTMP input stream has timed out: [#default#app/stream/] (0/0), elapsed: 13, threshold: 10
[2020-10-26 13:44:22.975] W 1056 RtmpProvider | rtmp_server.cpp:383  | RTMP stream <ClientSocket: 0x7f6667e01010, #4, state: 4, TCP, 47.9.187.129:44036> is timed out. Disconnecting...
[2020-10-26 13:44:22.975] I 1056 RtmpProvider | rtmp_server.cpp:230  | The RTMP client is disconnected: [#default#app/stream/] (0/0), remote: <ClientSocket: 0x7f6667e01010, #4, state: 4, TCP, 47.9.187.129:44036>

Kindly share what can be done to debug the same.

**Comment by getroot** [comment]
Could you give me access to your instance?  Please send your ssh access information to support@airensoft.com.  And would you please capture and upload your obs settings?  The cause of the problem seems to be outside the ovenmediaengine.

**Comment by bhanuc** [comment]
@getroot shared access as well obs settings on the email. Thanks for looking into the issue.

**Comment by bhanuc** [comment]
Thanks for the support. The url that needed to be entered was rtmp://45.77.241.8:1935/app not rtmp://45.77.241.8:1935/app/stream
