### ISSUE TITLE
OvenMediaEngine & OvenMediaPlayer on Synology

### ISSUE THREAD

**Issue by kpdillon** [AirenSoft/OvenMediaEngine#209]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kpdillon** [comment]
I just wanted to post that I have been successful in getting both OvenMediaEngine and OvenMediaPlayer to run as dockers on a Synology and it works great!  I do experience some occasional stuttering but I think that has more do do with either the network or OBS configuration.  This is truly remarkable!

**Comment by lee-hammer99** [comment]
@kpdillon 

Hello!
I'm the PR manager of OvenMediaEngine.

I'd love to hear more about your experience with OvenMediaEngine.
Could you please email me at [hammer99@airensoft.com](mailto:hammer99@airensoft.com)?

Thank you for using OvenMediaEngine.

**Comment by getroot** [comment]
Thank you! 
If you allow, please help @lee-hammer99  publish his blog. Your use-case will help other OME users.

**Comment by zcolor** [comment]
@kpdillon I'm interested in setting up OME with Docker on my synology. is there a guide you followed and were there any pitfalls?

**Comment by kpdillon** [comment]
It is still in use every day by a school who does local livestreams where all the teachers access the livestream with a browser on their Smartboard.  I think it broke when I applied upgrades so I had to downgrade to an older version.  I never took the time to troubleshoot why it broke, could have been an issue with the html customizations I did or something else.

**Comment by kpdillon** [comment]
yes I believe I just used container manager and downloaded it through the GUI.

**Comment by zcolor** [comment]
Ok! did you set it as host or as brigde?
