### ISSUE TITLE
Support h265 for push input streams

### ISSUE THREAD

**Issue by OlegGavrilov** [AirenSoft/OvenMediaEngine#210]
Hello! Thanks for your work on this amazing project. I just wanted to check that is there any possibility to support h265 input streams? As I understood from the docs, only h264 is supported now. Currently I am transcoding RTMP stream with ffmpeg and pass it to OME as h264. but I have to set up separate ffmpeg instances for each stream. It would be great if OME could do that for me =)

So, is there any plans for h265 to be supported? 

Thanks!

**Comment by getroot** [comment]
It's an experimental feature (it's only being tested internally), but we already support HEVC.
Currently we support HEVC input of MPEG-2 TS, HEVC encoding, and HEVC output of WebRTC. (HEVC in WebRTC is only available in the preview version of Safari browser. There is no officially supported browser yet.)

And RTMP does not support HEVC in the protocol. Do you mean H265/RTMP? it is impossible. It doesn't support it at the protocol level.

We will support HEVC in HLS and MPEG-DASH in the future and release it as a Beta version.

**Comment by OlegGavrilov** [comment]
@getroot mpeg-ts HEVC is totally ok for me. Any specific instructions about how I can use it? Do I need any configuration settings to make OME accept HEVC?

**Comment by getroot** [comment]
The feature is still being tested internally and has not been disclosed in the manual.

However, you can test as follows using version OME 0.10.8. (Currently the master branch has to consider this as the Server.xml structure has changed. It may be difficult to use as we haven't opened the information yet.)

./ffmpeg -re -stream_loop -1 -i <file>.<ext> -vcodec libx265 -vf scale=1280:720 -b:v 1500k -preset ultrafast -x265-params bframes=0:no-opengop=1: no-scenecut=1:keyint=100 -acodec copy -f mpegts udp://<ip>:4000?pkt_size=1316

For MPEG-2 TS input, refer to the following URL.

https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta

Please note that H.265 publishing on OME is currently only available for WebRTC. HLS and DASH are not supported yet. The only browser that supports H.265 in WebRTC is the preview version of Safari.

https://webrtcbydralex.com/index.php/2020/04/28/how-to-enable-hevc-h265-and-av1-in-webrtc-in-your-browser/

**Comment by OlegGavrilov** [comment]
@getroot tried to test it with the latest source and ffmpeg command you sent, but had this error in logs:

```
[2020-11-03 08:24:25.592] E 84 TranscodeCodec | transcode_decoder.cpp:95   | Codec not found: hevc (174)
[2020-11-03 08:24:25.592] E 84 TranscodeStream | transcode_stream.cpp:705  | Decoder allocation failed
```

Is there anything that I missed?

**Comment by getroot** [comment]
If you ran prerequisites.sh a long time ago, run this again. It will install the HEVC codec.

Sorry, but as I said before, HEVC is still in the internal testing stage. There is no manual. And even if a problem occurs, it is difficult to provide technical support because it is still under development. Please understand it.

**Comment by OlegGavrilov** [comment]
> If you ran prerequisites.sh a long time ago, run this again. It will install the HEVC codec.
> 
> Sorry, but as I said before, HEVC is still in the internal testing stage. There is no manual. And even if a problem occurs, it is difficult to provide technical support because it is still under development. Please understand it.

I will check the libs then. Thank you for helping me with this, hopefully my testing of this feature will be useful for you too - I will just post here my findings, in case anyone else will be interested in this topic.

**Comment by OlegGavrilov** [comment]
Just wanted to confirm that it is working as you said, after I fixed the dockerfile with missing H265 library and updated OpenSSL version to 1.1.0k, it all worked just fine. Thank you and looking forward for next release!
