### ISSUE TITLE
Different value in WebRTC/Stream total/App total

### ISSUE THREAD

**Issue by vova-zush** [AirenSoft/OvenMediaEngine#211]
The stream initially WebRTC/Stream total/App total had almost the same value, and then these values began to differ greatly. This is normal?
Some logs:
Monitor | stream_metrics.cpp:119  | A new session has started playing #default#app/7flag603982710 on the WebRTC publihser. WebRTC(191)/Stream total(191)/App total(198)
WebRTC(203)/Stream total(203)/App total(799)
I 35 Monitor | stream_metrics.cpp:119  | A new session has started playing #default#app/7flag603982710 on the WebRTC publihser. WebRTC(11)/Stream total(11)/App total(796)

**Comment by getroot** [comment]
app total is the sum of users who have accessed all streams in the app.  Stream total is the sum of users who are connected to hls, dash, and webrtc.  OME may not be perfect, but it is difficult to determine whether the log is normal or not.
