### ISSUE TITLE
Docker file config

### ISSUE THREAD

**Issue by Alexufo** [AirenSoft/OvenMediaEngine#216]
In docs https://airensoft.gitbook.io/ovenmediaengine/configuration

    "If you run it in Docker container, the path to the configuration file is:"
    /opt/ovenmediaengine/bin/origin_conf/Server.xml

I run 

```
docker run -d \
-p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 8080:8080 -p 9000:9000 -p 10000-10010:10000-10010/udp \
airensoft/ovenmediaengine:latest
```

But I have not `ovenmediaengine` folder in /opt/ on Ubuntu20

**Comment by getroot** [comment]
"/opt/ovenmediaengine" is a folder inside the Docker container.

**Comment by naanlizard** [comment]
@Alexufo you can either mount /opt/ovenmediaengine/bin/origin_conf/Server.xml in the docker-compose file (or in your docker run command) or make your own image with your custom configuration via the dockerfile

just make a dockerfile like 

```
FROM airenSoft/ovenmediaengine:latest

COPY ./Server.xml /opt/ovenmediaengine/bin/origin_conf/Server.xml```

where Server.xml is in the same folder as the Dockerfile.

You then build the image with something like `docker build . -t mycustomovenmediaengine`

**Comment by Alexufo** [comment]
than you guys.
