### ISSUE TITLE
web-rtc opus mono break stream

### ISSUE THREAD

**Issue by Alexufo** [AirenSoft/OvenMediaEngine#219]
```
	 <Audio>
		 <Codec>opus</Codec>
		 <Bitrate>128000</Bitrate>
		 <Samplerate>48000</Samplerate>
		 <Channel>2</Channel>
	 </Audio>
```
Channel =1 break a webrtc. Webrtc opus support stereo only. It strange case and should be documented. Maybe inside flie config.

https://www.wowza.com/community/t/webrtc-opus-stereo-downmixed-to-mono/91915/2

**Comment by getroot** [comment]
Ok, I will check it, thank you!
