### ISSUE TITLE
can support real-time audio and video chat?

### ISSUE THREAD

**Issue by oldstorm** [AirenSoft/OvenMediaEngine#220]
Can the real-time audio and video call function similar to wechat video chat function be realized? 
It supports one-to-one audio and video calls, and many to many audio and video calls, 
and supports one-to-one sending of text, files, pictures, etc

thanks!

**Comment by getroot** [comment]
No, we are developing a low-latency "streaming" server. It has the purpose of broadcasting to hundreds of thousands of people. There are products for video conference such as Janus, and we are developing these servers for different purposes.
Thank you!
