### ISSUE TITLE
impossible to hide video input endpoint

### ISSUE THREAD

**Issue by Alexufo** [AirenSoft/OvenMediaEngine#221]
I test stream key from obs and find that there is no posibble to hide input endpoint from public.

					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>

Name 'app' should be public, 
OutputStreamName - equals to obs stream key.

Enyone who have public stream url can get input endpoint. If I set OutputStreamName as any constant string, I able to use ANY string in stream key in OBS.

my expectations: we must have an a secret endpoint for obs and public endpoint. Now anyone can stream on my server who have public url.

**Comment by getroot** [comment]
We developed SignedPolicy for that.
Please refer to the following manual.

https://airensoft.gitbook.io/ovenmediaengine/signedpolicy

**Comment by Alexufo** [comment]
ok thank you

**Comment by Alexufo** [comment]
@getroot policy is not about hiding input enpoint. It is about how to prevent public access? I am right? I dont find chapter how to prevent access to encode point.

**Comment by getroot** [comment]
If you turn on SignedPolicy, no one can access it without Signature. If a user knows the address http://ome-host/app/stream?signature=19231ejf, he cannot access http://ome-host/app/stream2. This is because he cannot create a Signature. Since Signature is encoded in HMAC-SHA1, you need to know the secret key to create Signature. This is confidential information.

**Comment by getroot** [comment]
This is similar to AWS or Google's SignedURL. If you understand it, you will be able to understand SignedPolicy easily. Users can only access your OME through a URL containing the Signature you provide.
