### ISSUE TITLE
Signedpolicy not working as expected

### ISSUE THREAD

**Issue by vova-zush** [AirenSoft/OvenMediaEngine#222]
When I set url_expire timestamp + 1 min, player connect to webrtc url and work only 1 min and after 1 min it stop showing the stream. But in docs "url_expire means the time the URL is valid, so if you connect before the URL expires, you can continue to use it, and sessions that have already been connected will not be deleted even if the time expire".

**Comment by getroot** [comment]
Thanks to your report, I found my mistake.
You can test it in the master branch.
