### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenMediaEngine#223]
hi,
it is very nice software, but could someone help me on how to upgrade from v0.10.8  to v0.10.9 version i will really apreciate

thanks

**Comment by getroot** [comment]
There is no special way to upgrade OME. 
Turning off the old OvenMediaEngine and installing 0.10.9 will overwrite the binaries with the new version. Modify Server.xml to match the changed specifications. Please note that Server.xml format has changed a lot from 0.10.8 to 0.10.9.
And restart OvenMediaEngine. 

Install it by referring to the URL below,
https://airensoft.gitbook.io/ovenmediaengine/getting-started

For Server.xml, refer to the URL below.
https://airensoft.gitbook.io/ovenmediaengine/configuration

**Comment by alnux** [comment]
Bye the way, i have to rerun prerequisites.sh ??????

**Comment by getroot** [comment]
Yes it is better to do it when upgrading. This is because external libraries are often added with each version upgrade.

**Comment by alnux** [comment]
hi there, im using nginx as web server (vestacp) i have stream.domain.com domain and i want to use it on ovenmediaengine, 2 questions how use stream.domain.com on both nginx and ome and , can i use ssl certificate generated by vesta on ome ???

thanks for your help
