### ISSUE TITLE
Using GPU

### ISSUE THREAD

**Issue by sehadnassim** [AirenSoft/OvenMediaEngine#224]
Hi, I want to use H264_Nvenc encoder is this possible ? And where to configure this ? I also want to know what does OME use for encoding or to relay rtmp to rtp is it ffmpeg ?

**Comment by getroot** [comment]
The video encoding acceleration is covered in #23 . It's not done yet.

OME currently uses the x264, x265, libvpx, libopus, fdkaac libraries for encoding. RTMP protocol and RTP packetizer do not use external library.

See the source code for details.
