### ISSUE TITLE
Hardware accelerated video encode and decode

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#23]
We will support hardware acceleration using Intel's Quicksync and Nvidia's NVENC / NVDEC.

**Comment by OlegGavrilov** [comment]
Any news on this feature?

**Comment by zeyrektechnology** [comment]
> Any news on this feature? 

Yeah, I am also waiting for the GPU based acceleration

**Comment by getroot** [comment]
This feature is still in the backlog. However, we will start working on ABR soon, and I think this is essential for ABR functionality.

**Comment by sehadnassim** [comment]
any news on this ?

**Comment by IanMitchell77** [comment]
The v0.20 OME config file has this:




So, does that mean this is now working? What GPU's are supported?

**Comment by getroot** [comment]
@IanMitchell77 It is being tested internally. After some time it will be open.

**Comment by getroot** [comment]
The first version of this feature has been launched. https://github.com/AirenSoft/OvenMediaEngine/issues/429 thread has more details. Thank you!
