### ISSUE TITLE
Low Latency DASH problem with new Dash.js release

### ISSUE THREAD

**Issue by manuelcua** [AirenSoft/OvenMediaEngine#231]
**Describe the bug**
There´s a problem with LLDASH when using updated Dash.js libraries, I was having trouble getting a stable buffer with LLDASH and thought maybe that upgrading the Dash.js library on OvenPlayer  (Dash.js v2.9.3) might help with stability but found out that it breaks completly. 

**To Reproduce**
Configure server for LLDASH and test with player using Dash.js v2.9.3 and then update the library or just try latest library using the reference player: 
https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html 
Normal DASH works and activating low latency on normal DASH also works, but with LLDASH it finds the data, but never starts showing the image.

**Expected behavior**
Should start showing image almos right away with low latency

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/5657714/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - OvenMediaEngine Version:  v0.10.9
 - Branch: release

**Player (please complete the following information):**
 - Device: PC, Phone
 - OS: Windows 10, Android 10
 - Browser Chrome
 - Version 87.0.4280.88 (Build oficial) (64 bits)

**Additional context**
I guess that it might be a new protocol for presenting the LLDASH information, it seems to be searching for something all the time when trying to play with the new Dash.js library. 

By the way I´ve been using this server for about two weeks, love it! Can´t wait to try the next release and I will try to help as much as I can.

**Comment by dimiden** [comment]
@manuelcua 
Thank you for your report.
I are aware of the problem that LL-DASH is not working in the latest version of DASH.js. However, I recently changed the packetizer for DASH/HLS, and I need to stabilize them first, so it will take some time to resolve the LL-DASH problem.

**Comment by manuelcua** [comment]
@dimiden 
I´m glad to help, if you need form me to do some testing, just let me know.

So for now it´s not recomended to use LL-DASH? It stutters a lot with any configuration.

**Comment by dimiden** [comment]
@manuelcua 
Yes. I don't recomment using LL-DASH until I stabilize it.

**Comment by Alexufo** [comment]
agree. New versions are not work. OME works with Dash.js v2.9.3

**Comment by dimiden** [comment]
@manuelcua @Alexufo 
There was an issue with the latest version of dash.js that failed to handle the manifest of OME.
I modified this and committed it to d1fa9d8b7b3a3d7d874f43f97a92a25d70b5dd1.
