### ISSUE TITLE
Is LL-HLS going to be implemented?

### ISSUE THREAD

**Issue by cub33** [AirenSoft/OvenMediaEngine#232]

**Comment by getroot** [comment]
It's still in our backlog.
We are waiting for more spread of LL-HLS. (Player compatibility, CDN support, etc.)

**Comment by Alexufo** [comment]
@cub33 did you see LL-HLS in other open source solutions?

**Comment by cub33** [comment]
player side hls.js is currently implementing it https://github.com/video-dev/hls.js/projects/7

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by nums** [comment]
Hello,

do you have any news about implementation of ll hls ?

Specs seem to be more stable now. (https://developer.apple.com/documentation/http_live_streaming/enabling_low-latency_hls)

Thanks
