### ISSUE TITLE
Is RTSP source now supported ?

### ISSUE THREAD

**Issue by sehadnassim** [AirenSoft/OvenMediaEngine#234]
Is RTSP push from a camera supported ? if yes could you please add it to the config example ?

**Comment by getroot** [comment]
OvenMediaEngine only supports RTSP pull (pulling stream from RTSP server) yet.

**Comment by IanMitchell77** [comment]
How do you configure RTSP pull? I have the below in my Server.xml - it fails to start and says "[Config] Unknown configuration found: <Server>.<VirtualHosts>.<VirtualHost>.<Domain>"

<VirtualHost>
                        <Name>default</Name>

                        <Domain>
                                <Names>
                                        <Name>*</Name>
                                </Names>
                        </Domain>

                        <Origins>
                                <Origin>
                                        <Location>/app_name/rtsp_stream_name</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url><URL not including rtsp://?></Url></Urls>
                                        </Pass>
                                </Origin>
                        </Origins>
                </VirtualHost>

**Comment by getroot** [comment]
@IanMitchell77 
From version 0.10.9, some settings have been changed.
Domain is no longer used and changed to Host.
Please refer to the following URL:
https://airensoft.gitbook.io/ovenmediaengine/configuration#virtual-host

Refer to the URL below for RTSP Pull settings.

https://airensoft.gitbook.io/ovenmediaengine/live-source/rtsp-pull-beta#configuration

**Comment by IanMitchell77** [comment]
Ill attach my complete config file but 

when I start it says:
 ```
[Config] Unknown configuration found: 
<Server>.<VirtualHosts>.<VirtualHost>.<>
```

This is the virtual hosts section:

```
        <VirtualHosts>
                <!-- You can use wildcard like this to include multiple XMLs -->
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>

                        <Host>
                                <Names>
                                        <Name>*</Name>
                                </Names>
                        </Host>

                        <Origins>
                                <Origin>
                                        <Location>/app_name/rtsp_stream_name</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>192.168.0.200:554/</Url></Urls>
                                        </Pass>
                                </Origin>
                        </Origins>
                </VirtualHosts>
[Server.zip](https://github.com/AirenSoft/OvenMediaEngine/files/5710588/Server.zip)

```

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/102566904-c6ce4600-4123-11eb-92dd-d15ab492b44c.png)
When I opened the file in my editor, I found a strange character between <Name> and <Host>. It is neither space nor enter, but something invisible. When I erased it, it worked normally.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
