### ISSUE TITLE
Compile error: 'numeric_limits' is not a member of 'std'

### ISSUE THREAD

**Issue by andreymal** [AirenSoft/OvenMediaEngine#235]
I tried to build OvenMediaEngine in Arch Linux but got this error:

```
[static] libovlibrary.a: C++ projects/base/ovlibrary/stl.cpp => intermediates/RELEASE/objs/base/ovlibrary/stl.o
In file included from projects/base/ovlibrary/stl.cpp:1:
projects/base/ovlibrary/stl.h: In function 'bool Stoi(const string&, T&)':
projects/base/ovlibrary/stl.h:41:47: error: 'numeric_limits' is not a member of 'std'
   41 |         if (int_value > 0 && int_value > std::numeric_limits<T>::max()) return false;
      |                                               ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/base/ovlibrary/stl.o] Error 1
```

I added `#include <limits>` to `stl.h` and then this file was successfully compiled.

It seems this inclusion is just forgotten?

**Comment by getroot** [comment]
The platforms we are testing are Ubuntu, CentOS and Fedora. I've never used Arch Linux. 
However, as a result of your information, OvenMediaEngine is also available on Arch Linux. Thank you.

**Comment by andreymal** [comment]
Not sure it really works (didn't test it yet), but at least https://github.com/AirenSoft/OvenMediaEngine/commit/ad83e1d2226445d649e4b7e0c75106e31af4940d makes OvenMediaEngine compileable. Thank you!

**Comment by genofire** [comment]
@andreymal i also try to compile it on Archlinux - do you have some steps/help for me:
```
projects/modules/file/file_writer.cpp: In member function ‘bool FileWriter::AddTrack(cmn::MediaType, int32_t, std::shared_ptr<FileTrackInfo>)’:
projects/modules/file/file_writer.cpp:213:33: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘display_aspect_ratio’; did you mean ‘sample_aspect_ratio’?
  213 |                         stream->display_aspect_ratio = AVRational{1, 1};
      |                                 ^~~~~~~~~~~~~~~~~~~~
      |                                 sample_aspect_ratio
compilation terminated due to -Wfatal-errors.
projects/modules/rtmp/rtmp_writer.cpp: In member function ‘bool RtmpWriter::AddTrack(cmn::MediaType, int32_t, std::shared_ptr<RtmpTrackInfo>)’:
projects/modules/rtmp/rtmp_writer.cpp:225:33: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘display_aspect_ratio’; did you mean ‘sample_aspect_ratio’?
  225 |                         stream->display_aspect_ratio = AVRational{1, 1};
      |                                 ^~~~~~~~~~~~~~~~~~~~
      |                                 sample_aspect_ratio
```

I try to create an AUR: https://aur.archlinux.org/packages/ovenmediaengine/

**Comment by ghostnumber7** [comment]
> @andreymal i also try to compile it on Archlinux - do you have some steps/help for me:
> 
> ```
> projects/modules/file/file_writer.cpp: In member function ‘bool FileWriter::AddTrack(cmn::MediaType, int32_t, std::shared_ptr<FileTrackInfo>)’:
> projects/modules/file/file_writer.cpp:213:33: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘display_aspect_ratio’; did you mean ‘sample_aspect_ratio’?
>   213 |                         stream->display_aspect_ratio = AVRational{1, 1};
>       |                                 ^~~~~~~~~~~~~~~~~~~~
>       |                                 sample_aspect_ratio
> compilation terminated due to -Wfatal-errors.
> projects/modules/rtmp/rtmp_writer.cpp: In member function ‘bool RtmpWriter::AddTrack(cmn::MediaType, int32_t, std::shared_ptr<RtmpTrackInfo>)’:
> projects/modules/rtmp/rtmp_writer.cpp:225:33: error: ‘AVStream’ {aka ‘struct AVStream’} has no member named ‘display_aspect_ratio’; did you mean ‘sample_aspect_ratio’?
>   225 |                         stream->display_aspect_ratio = AVRational{1, 1};
>       |                                 ^~~~~~~~~~~~~~~~~~~~
>       |                                 sample_aspect_ratio
> ```
> 
> I try to create an AUR: https://aur.archlinux.org/packages/ovenmediaengine/

I saw that same issue when using ffmpeg 4.4, and got it working by using 4.3.2 instead. Maybe check that in case it's the same.

**Comment by genofire** [comment]
Thankyou @ghostnumber7 - it compiles after downgrading ;)

**Comment by kwonkeukhan** [comment]
👍
