### ISSUE TITLE
Firefox playback video stuttering

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#237]
**Describe the bug**
On a fully updated firefox browser, playing a stream encoded in obs with the following settings leads to choppy video (though sound works fine)

**To Reproduce**
![download (2)](https://user-images.githubusercontent.com/7061721/102528231-4698d980-406c-11eb-93e3-6a6ca747aef8.png)

Using ome 0.10.9 and 

**Expected behavior**

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.

**Server (please complete the following information):**
 - OS: ubuntu 20.04 5.10rc6
 - OvenMediaEngine Version: 0.10.9 (via docker)

**Player (please complete the following information):**
 - Device: computer
 - OS: windows 10
 - Browser firefox
 - Version 

**Additional context**
Chrome with the same settings plays fine, the only difference between the settings used for our test and the recommended in the faq are the cpu preset (very fast vs ultrafast) and profile (baseline vs high). Is one of those required for firefox to play well? They cause far higher bandwidth usage at the same quality is why we try and avoid them.

**Comment by naanlizard** [comment]
After further testing, it appears that the `ultrafast` preset is required - from [here](http://dev.beandog.org/x264_preset_reference.html) I can find a list of what differences there are between ultrafast and superfast, do we know which causes poor playback in firefox?

Thanks, sorry this is a bit of a non-standard ticket.

**Comment by naanlizard** [comment]
I'll put this question here too:

The threads=8 parameter is suggested in the docs because chrome can't play back content encoded with too many threads. That sounds weird to me, and my testing does not back that up - not setting threads, or setting it to a very large number (80) doesn't make a difference in the latest chrome as far as I can tell. Is that still needed?

**Comment by getroot** [comment]
You seem to use the setting to pass-through the encoder's stream in OME (Bypass on). If so, this is an issue between the Encoder (probably OBS?) and the Player. So this is not a bug of OME as it is not a controllable area in OME. Transcoding in OME to avoid encoder configuration issues. Putting both VP8 and H264 in the encoding settings can provide stable playback in most browsers.

- Most browsers cannot handle H.264 b-frames in WebRTC.
- Some browsers can't handle H.264 high profile or main profile. So set it as the base profile.
- OBS(x264) increases the number of threads when real-time processing is impossible due to various reasons such as large bitrates. This will create more NAL Units, and Chrome will not be able to process it if it exceeds a certain number, so it will not play. In your case, you don't have a thread problem because your OBS is doing it in real time.
- If the key frame interval is long, the initial playback start is delayed. It is recommended to set it to 1.
- Firefox will probably work fine with bframes=0 and base profile

**Comment by naanlizard** [comment]
Correct, I believe we are just doing pass-through with webrtc. Encoder is OBS Studio, 26.1.0 on Windows.

Currently with the following settings firefox does not load at all, actually, which is new - before it just stuttered. https://i.imgur.com/paCqz0P.png

How can we debug a constant buffering circle in OMP? I think this is probably related to OMP

Here is a relevant section of log file 

```2020-12-18T03:04:56.182717593Z [2020-12-18 03:04:56.182] I 39 Monitor | stream_metrics.cpp:119  | A new session has started playing #default#lowlatency/1 on the WebRTC publihser. WebRTC(1)/Stream total(1)/App total(180)
2020-12-18T03:04:56.230693356Z [2020-12-18 03:04:56.230] W 39 Signalling | rtc_signalling_server.cpp:655  | [Host -> OME] The host peer sents an empty candidate
2020-12-18T03:05:03.997491994Z [2020-12-18 03:05:03.997] W 94 ov.Queue | queue.h:179  | [0x55f749d12f00] Transcoder application indicator. app(#default#lowlatency) (0/1) size has exceeded the threshold: queue: 100, threshold: 100
2020-12-18T03:05:03.997664197Z [2020-12-18 03:05:03.997] W 88 ov.Queue | queue.h:179  | [0x55f749d07060] #default#lowlatency - Mediarouter inbound indicator (0/1) size has exceeded the threshold: queue: 100, threshold: 100
2020-12-18T03:05:03.997691920Z [2020-12-18 03:05:03.997] W 94 ov.Queue | queue.h:179  | [0x7ff2380bc648] #default#lowlatency/47335 - TranscodeStream input Queue size has exceeded the threshold: queue: 100, threshold: 100
2020-12-18T03:05:03.997745190Z [2020-12-18 03:05:03.997] I 94 TranscodeStream | transcode_stream.cpp:180  | Queue(stream) is full, please check your system: (queue: 101 > limit: 100)
```

There are lots of the "Please check your system" lines.

Is that a configuration variable we need to adjust?

**Comment by getroot** [comment]
That queue log is not the cause of Firefox's replay failure. It doesn't matter unless the queue size is constantly increasing. This can occur when many packets are input at once.

Is there any reason not to use the profile we suggest in the manual? It takes a lot of time for me to explain the limitations of Firefox's codec support.

https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder

**Comment by naanlizard** [comment]
The recommended encoder settings use far more bandwidth. Specifically, ultrafast instead of veryfast uses more than 5x the bandwidth in some cases. Many of our users have limited upload speed, not to mention we prefer to limit bandwidth usage for our server, and keep streams low bandwidth for viewers with slow internet.

**Comment by getroot** [comment]
OBS' encoding profile that plays well in Firefox seems to require various trials and errors. Please share anything you find out.

Not playing on all browsers may be a problem with OBS, but if stuttering occurs only in firefox, it is an issue with codec settings. As far as I know firefox is using openh264 when decoding WebRTC.

**Comment by naanlizard** [comment]
I'll keep experimenting.

I'm concerned by the refusal of OvenMediaPlayer to load the stream, which seems to happen mostly with firefox but occasionally with chrome - is the "host peer sent an empty candidate" warning above possibly related? I'm not sure when this started but I've just noticed it

**Comment by getroot** [comment]
Currently, OvenMediaEngine communicates in a different way, ignoring all candidates sent by the Player. Specifically, when the webrtc client sends a stun request first, OME responds to it regardless of the candidate. So that log doesn't affect the current player's playback.

**Comment by naanlizard** [comment]
I'll try and reproduce the buffering circle then somehow. Thanks!

**Comment by alnux** [comment]
i saw that your keyframe is on 4, maybe if you change it with 1

**Comment by naanlizard** [comment]
The keyframe interval only seems to control how long it takes for the stream to start, otherwise it doesn't cause trouble I don't think.

Similar to the other settings I'm trying to avoid, a keyframe interval of 1 causes massively increased bandwidth usage.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
