### ISSUE TITLE
About HLS ts file size

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenMediaEngine#238]
Hi, how can i make of ts files be less than 1.4MB becouse i change 

`<SegmentDuration>5</SegmentDuration>
<SegmentCount>3</SegmentCount>`

but the size of ts files are allways the same, i would like that them be of 500KB or 800KB

thanks for your help

**Comment by getroot** [comment]
Lower the bitrates of the encoder, or lower the `<SegmentDuration>`. It is recommended to set the key frame to 1 second.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
