### ISSUE TITLE
about P2P Delivery (Experiment)

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenMediaEngine#239]
Hi, it is just a question.... 

1.- can use P2P Delivery with just my OME server ???... i mean right now i dont scaling my network with origin or edge server, just one OME server.

2.- And what i have to do for enabling this function on ovenplayer

thanks, and great job

**Comment by getroot** [comment]
P2P traffic distribution is not yet officially supported. We are applying this feature to very specific sites.

**Comment by nangavar** [comment]
Hi alnux!

I've tried and it worked perfectly using webrtc. Have in mind that it works only with one hop and by browser, that means that a user that receives directly from OME is able to share the stream, no user receiving from p2p will share. And it works by browser, safari with safari and chrome with chrome, no crossed browsers.

Hope it helps. I suggest you try it.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
