### ISSUE TITLE
Recommended OBS settings inaccurate (according to OBS devs)

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#251]
Hello, small documentation bug (or oversight)

According to the [configuration recommendations](https://airensoft.gitbook.io/ovenmediaengine/getting-started#hello-sub-second-latency-streaming) for x264 OBS, streamers should set bframes=0

However, [OBS maintainers say](https://github.com/obsproject/obs-studio/pull/3913#issuecomment-758566689) that the tune=zerolatency option already sets bframes=0

They also disapprove of setting a static threads=8 parameter, and are skeptical of whether or not it does anything for playback. In my own testing, increasing the threads value to arbitrarily large numbers (8, 16, 32, 64, 128 which is the max value) does not appear to affect playback that I could tell.

**Comment by getroot** [comment]
Yes, I know the tune=zerolatency option already sets bframes=0. Also, setting the profile as the baseline also makes bframes=0. However, people often do not set it to zerolatency or set the main profile. We've got so many bframes related inquiries from users, so we've specified it in the manual.

What we recommend setting threads=8 is specifically related to webrtc playback quality. The x264 encoder uses too many threads (default threads=0) when encoding at high bitrates or when the PC is running poorly, which causes Chrome to discard those frames when the number of NALs exceeds 10. This is a very difficult problem for users to solve, so we recommend limiting to threads=8. (This is the simplest way we solve our users' problems.)

Check out the code below.
https://chromium.googlesource.com/external/webrtc/trunk/webrtc/+/f54860e9ef0b68e182a01edc994626d21961bc4b/modules/video_coding/codecs/h264/include/h264_globals.h#62

**Comment by naanlizard** [comment]
Ah, I definitely understand users making those mistakes haha.

What is the webrtc playback problem when there are too many threads? Choppy playback? I didn't experience any trouble watching my high-thread OBS stream in chrome

**Comment by getroot** [comment]
Chrome discards the frame when H.264's NAL Unit exceeds 10. Therefore, it is reproduced by setting bypass transcoding in OME.
I don't know the exact conditions, but when sending a high bitrates video (about 10~20Mbps) from a low-performance PC to OBS, 10 or more NAL units are generated. In that case, if threads=8 is given, the number of NAL units is created below 10.

**Comment by naanlizard** [comment]
Does that only occur with high bitrate video like that?

As I said, when I manually set threads=64 (but with a lower bitrate, around 2mbps) I don't see any problems in chrome. If it is only a problem for very high bitrate streams that is very good news

**Comment by getroot** [comment]
I don't know exactly the internal implementation of OBS or x264, but it was often reproduced when I encoded the video at a high bitrates and the PC's performance was insufficient.

**Comment by getroot** [comment]
I close this issue. If you want to discuss more about this, please reopen the issue.
