### ISSUE TITLE
HLS not working on safari 11.1.2

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenMediaEngine#253]
Hi there i just upgrade to v0.10.11 and HLS on Mac safari does not working, does You upgrade ovenplayer too??? Becouse un other browsers over Mac works normally but not with safari. 
I have OME 0.10.11 and ovenplayer 0.9.0.2020112616-rev-11a2498

**Comment by getroot** [comment]
We will check this issue. However, it is difficult to check quickly because we are too busy these days. If there is any updated news, I will comment again.

**Comment by dimiden** [comment]
@alnux 
I tested in El Capitan + Safari 11.1.2, but I didn't find any problem.
Please give me more detailed information to find the problem you are facing.

![image](https://user-images.githubusercontent.com/4264558/106296551-2e37f380-6295-11eb-8356-849b059df685.png)
