### ISSUE TITLE
API Server does not support TLSPort

### ISSUE THREAD

**Issue by command-tab** [AirenSoft/OvenMediaEngine#259]
While enabling the API server in `Server.xml`, I expected it to support TLS in the same way that `<Publishers>` do, using `<TLSPort>` instead of `<Port>`, but it does not appear to. In this example, I already have my `<Publishers>` working with a TLS key and cert/cert chain.

1. Set Server.xml as follows:

        <Server version="8">
            <Name>OvenMediaEngine</Name>
            <Type>origin</Type>
            <IP>*</IP>
            <Bind>
                <Managers>
                    <API>
                        <TLSPort>48082</TLSPort>
                    </API>
                </Managers>
                ...
            </Bind>
            <Managers>
            <Host>
                <Names>
                    <Name>*</Name>
                </Names>
                <TLS>
                    <CertPath>/a/real/path/to/file.crt</CertPath>
                    <KeyPath>/a/real/path/to/file.key</KeyPath>
                    <ChainCertPath>/a/real/path/to/file.crt</ChainCertPath>
                </TLS>
                ...

2. Restart OME — `systemctl restart ovenmediaengine.service`
3. Observe the following in the log at `/var/log/ovenmediaengine/ovenmediaengine.log`:

        E [OvenMediaEngine:88625] APIServer | api_server.cpp:83   | Could not initialize HttpsServer

**Server:**
 - OS: RHEL 7.9
 - OvenMediaEngine Version: v0.10.11
 - Branch: `master`

**Player:**
N/A

**Comment by dbContext** [comment]
There is a <Manager> XML Node (outside the <Bind> Node) like the below:

Placement example in Config:

`
<Server version="8">
      <Bind>
       ....
       </Bind>
       <Managers>
        ... Full snippet below ....
       </Managers>
       <VirtualHosts>
        .....
        </VirtualHosts>
</Server>
`

Full <Managers> Config:
`	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			<TLS>
				<CertPath>/usr/share/ovenmediaengine/ssl/xxx.crt</CertPath>
				<KeyPath>/usr/share/ovenmediaengine/ssl/xxx.key</KeyPath>
				<ChainCertPath>/usr/share/ovenmediaengine/ssl/xxx.crt</ChainCertPath>
			</TLS>
		</Host>
		<API>
			<AccessToken>abc123</AccessToken>
		</API>
	</Managers>`

If you require any further info, let me know.

**Comment by command-tab** [comment]
Hmm, I follow what you wrote, but after adding that to my config, updating the TLS children to be the same TLS paths as what my working Publishers use, and restarting OME, OME logs:

    E [OvenMediaEngine:124229] APIServer | api_server.cpp:83   | Could not initialize HttpsServer

Here's my complete config: https://gist.github.com/command-tab/8b5b5d7144d5c37193f56fd368e9a462

Thank you!

**Comment by command-tab** [comment]
https://github.com/AirenSoft/OvenMediaEngine/blob/ceacdc7d32d4b251f1e4432ec52e330888798b6e/src/projects/api_server/api_server.cpp#L71-L76
Should `address` on line 76 be `tls_address`?

**Comment by dbContext** [comment]
Good catch, Yes it should be utilising the `tls_address` variable, instead of the `address` variable which is for the Http API Endpoint.

As a quick work-around without recompiling, just add `<Port>48083</Port>` to the API Bindings and it'll use the `<TLSPort></TLSPort>` to attempt to initialise the Https API while binding to the Http Port.

I can update that in the morning and submit a PR, or you're more than welcome too. Simply update the variable as instructed above.

Thanks.
