### ISSUE TITLE
Unable to play live stream from OME - Connection with low-latency(OME) terminated unexpectedly

### ISSUE THREAD

**Issue by bdr99** [AirenSoft/OvenMediaEngine#263]
**Describe the bug**
I'm running OME in Docker and streaming with OBS. I have the WebRTC publisher enabled in my `Server.xml`, and I have the Caddy web server pointed at the signalling port. When I try to access the stream using OvenPlayer in Firefox, it spins for a few seconds and then fails with the error `Connection with low-latency(OME) terminated unexpectedly`. Then it tries again over and over, failing with the same message each time. When I try in Chrome, I just get a black screen. At the end of `OvenMediaEngine.log` you can see the client is repeatedly connecting and disconnecting.

Here is my `docker-compose.yml`:
```yaml
version: "3.3"
services:
  ome:
    image: airensoft/ovenmediaengine:0.10.11
    network_mode: host
    volumes:
      - ./Server.xml:/opt/ovenmediaengine/bin/origin_conf/Server.xml:ro
```
Here is my `Server.xml`:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<Server version="8">
	<Name>OvenMediaEngine</Name>
	<Type>origin</Type>
	<IP>*</IP>
	<Bind>
		<Providers>
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
			</RTMP>
		</Providers>
		<Publishers>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
				</Signalling>
				<IceCandidates>
					<IceCandidate>[My public IP]:10006-10010/udp</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>
	<VirtualHosts>
		<VirtualHost>
			<Name>default</Name>
			<Host>
				<Names>
					<Name>[Local IP of server running OME]</Name>
					<Name>[Public DNS name for websocket signaling port]</Name>
				</Names>
			</Host>
			<Applications>
				<Application>
					<Name>app</Name>
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<RTMP />
					</Providers>
					<Publishers>
						<SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
```
Here is my OvenPlayer configuration:
```javascript
player = OvenPlayer.create("player", {
    sources: [
        {
            "file": "wss://[Public DNS name for websocket signaling port]/app/stream",
            "type": "webrtc"
        }
    ]
});
```
**To Reproduce**
1. Set `Server.xml`, `docker-compose.yml` as above
2. Start docker container
3. Attempt to play stream using OvenPlayer

**Expected behavior**
Client should be able to successfully connect and play the live stream.

**Logs**
Log from Chrome:
[OvenMediaEngine.log](https://github.com/AirenSoft/OvenMediaEngine/files/5897414/OvenMediaEngine.log)
Log from Firefox:
[OvenMediaEngine_Firefox.log](https://github.com/AirenSoft/OvenMediaEngine/files/5897451/OvenMediaEngine_Firefox.log)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: v0.10.11
 - Branch: latest

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox 85 / Chrome 87

**Additional context**
Ports `10006-10010/udp` are forwarded to the server running OvenMediaEngine. The client access the signalling websocket through the Caddy web server which provides TLS. The issue only happens when I try to connect over the internet using the public IP as the ICE candidate.

if I change the ICE candidate to `<IceCandidate>*:10006-10010/udp</IceCandidate>` and connect using my local IP, then everything works fine. The issue only happens when I try to connect over the internet using the public IP as the ICE candidate.

**Comment by getroot** [comment]
OBS seems to have set a codec option that is not compatible with WebRTC.  Please refer to the URL below or upload your OBS encoding settings.

https://airensoft.gitbook.io/ovenmediaengine/getting-started

**Comment by bdr99** [comment]
I actually already followed those instructions when I was setting up OBS. Here are my OBS settings:
![image](https://user-images.githubusercontent.com/2292715/106349693-144ede80-629e-11eb-9428-d8f341a664f1.png)
I forgot to mention this in my original post, but if I change the ICE candidate to `<IceCandidate>*:10006-10010/udp</IceCandidate>` and connect using my local IP, then everything works fine. The issue only happens when I try to connect over the internet using the public IP as the ICE candidate.

**Comment by dbContext** [comment]
Could you clarify your last paragraph in the above comment please? 

If it works when binding the Ice Candidate to all available network interfaces and successfully playing through a LAN address, then there is an issue with the public IP (host node firewall).

I'd suggest hard-setting the public facing IP within the `<IceCandidate>` XML node, and ensuring that you have the relevant port ranges open on the docker host node. 

If I have misinterpreted the above paragraph, please let me know and i'll assist further.

**Comment by getroot** [comment]
If the public IP address cannot be extracted from local, such as AWS or Docker, IceCandidate with public IP may not be delivered to the player. In this case, try setting <IceCandidate>{public IP}:10006-10010/udp</IceCandidate> instead of <IceCandidate>*:10006-10010/udp</IceCandidate>.

In order to solve this problem automatically, we extracted the public IP from the signaling address in OvenPlayer (this is possible because the signaling IP address and the candidate IP address are the same in the case of OME) and put the logic to force the candidate. However, you may not be able to extract the candidate from the player because the signaling IP address is passed through the caddy web server.

As mentioned above, specifying the public IP of the OME server in IceCandidate will solve the problem.

**Comment by bdr99** [comment]
Thank you @dbContext and @getroot for your replies.

@dbContext, your interpretation is correct. When I bind the ICE candidate to all interfaces, it successfully plays through my local IP.

@dbContext and @getroot, my apologies if this wasn't clear in my original issue report, but in my Server.xml, I already have the ICE candidates bound to my public IP. My `<IceCandidate>` node currently looks like this:

```xml
<IceCandidate>[My public IP]:10006-10010/udp</IceCandidate>
```

I also have my Docker container in "host" network mode, so all ports are open in the container, with no need to manually forward ports in Docker.

**Comment by getroot** [comment]
Is it possible to access the udp 10006-10010 port of public IP from outside? It is better to check it first.

**Comment by bdr99** [comment]
@getroot I just did a test. I ran `nc -u -l 10006` on my server running OvenMediaEngine, and `nc -u [My public IP] 10006` on an external VPS server. I was able to successfully send messages and receive them on the server running OvenMediaEngine. So we know the port is open.

**Comment by getroot** [comment]
I don't know exactly what your network configuration is so I can't figure out if this will help you.
In some DSR (Direct Server Return) network configurations, after entering Public IP into IceCandidate, the player must be set as follows to operate. Try this.

```
player = OvenPlayer.create("player", {
    sources: [
        {
            "file": "wss://[Public DNS name for websocket signaling port]/app/stream",
            "type": "webrtc"
        }
    ],
    webrtcConfig: {
        generatePublicCandidate: false
    }
});
```

If this doesn't work, please send your server access information to dev@airensoft.com and we'll take a look at your configuration when we have time.

**Comment by bdr99** [comment]
@getroot Thanks for the suggestion to try adding `generatePublicCandidate: false` to the player! Unfortunately it didn't help with my issue. Still the same behavior. I'll send an email.

**Comment by bdr99** [comment]
In the end, I wasn't able to figure out why the stream wasn't working when hosted on my home network. I have since switched to hosting OME on a DigitalOcean server, and this has resolved my issue. I can only assume it must have been some issue with the way my home network is configured.

If anyone else encounters this issue, I recommend hosting OME outside of the network from which you are attempting to play the stream.
