### ISSUE TITLE
OvenMediaEngine Docs on GitHub

### ISSUE THREAD

**Issue by command-tab** [AirenSoft/OvenMediaEngine#265]
Are the OvenMediaEngine docs (the ones published here: https://airensoft.gitbook.io/ovenmediaengine/) available on GitHub? I'd like to open some PRs to improve the documentation, but I can't find the repo.

Thanks!

**Comment by dbContext** [comment]
2nd this, I've seen a few issues on the documentation that I've had to spend countless hours figuring out myself. 

If the documentation can be opened up, so we can create PR's - that would be great, for everyone invovled.

**Comment by getroot** [comment]
@command-tab @dbContext 
Thank you for your active contribution.
We are using gitbook(https://www.gitbook.com/) for the manual. Thankfully, gitbook supports open source for free.
I can invite you to gitbook with writer privileges. Could you please give me your email address? Thank you sincerely. This will be of great help to OvenMediaEngine's open source.

**Comment by command-tab** [comment]
Thanks! I'm collin@commnd-tab.com

**Comment by dbContext** [comment]
You're most welcome, it's a great open source project.

me@joec.xyz

**Comment by getroot** [comment]
I have emailed you an invitation link. Thank you again.
