### ISSUE TITLE
How to broadcast OvenMediaEngine to website video player.

### ISSUE THREAD

**Issue by XaniMander** [AirenSoft/OvenMediaEngine#272]
Hello OME devs,

I am trying to use OME to broadcast a video stream on my website (virtualcst.com). Whenever I enter the WebRTC link for my OBS stream to http://demo.ovenplayer.com I get "Connection with low-latency(OME) server failed". I have tried several times to follow the OME documentation and reinstall OME on my Ubuntu VPS to no avail.  Before OME I've been able to accomplish video streaming with a Nginx RTMP streaming server and HLS video player so I must have some lack of understanding, however the docs and one blog post were not enough for me to get this to work.

Could you help explain to me how I should set up my OME streaming server and Ovenplayer website from a fresh Ubuntu VPS? I know some things about configuring Nginx from my first attempt but at this but honestly I am quite confused and lost at what to do next.

Cheers,
Xanimander

**Comment by naanlizard** [comment]
Are you allowing connections to the ports OME uses? Typically 10000-10010 IIRC and 3333 or 3334 depending on if you've set it up to use SSL. Check your Server.xml file

**Comment by XaniMander** [comment]
Darn my luck, I got this to work almost right after posting 😂😂. Anyways thanks for the tip I've opened all ports, I'll close the issue now.
