### ISSUE TITLE
Firefox won't play WebRTC streams without aq-strength=0

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#273]
**Describe the bug**
Using a standard OME server and OMP setup, with OBS set to the default x264 stream options + tune=zerolatency, chrome will play the WebRTC stream fine, but Firefox will never start playing (endlessly buffering). By adding the argument "aq-strength=0" in OBS' x264 options input, Firefox can now play the WebRTC stream as well.

This isn't a typical bug report, apologies, I'm just trying to share this information with anyone else who might use it.

aq-strength=0 affects quality slightly but by using (for example) the `veryfast` encoder preset with aq-strength=0, a streamer uses far less bandwidth than the standard `ultrafast` preset.

**Comment by getroot** [comment]
This is very good information. Thank you.
In the future, we will add this information to the manual.

**Comment by naanlizard** [comment]
If you tell me where it will be added, I can draft a paragraph for the manual. I just wasn't sure where it should be put, or if these would be better settings than the current recommended settings for x264, and didn't want to assume :)

**Comment by getroot** [comment]
We are using the gitbook service as a manual. I would like to invite you here as a writer. If you accept, please let me know your email address. I will send you an invitation. Thanks for your contribution.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
