### ISSUE TITLE
How to get reliable viewers statistics out of OME ?

### ISSUE THREAD

**Issue by Arzar** [AirenSoft/OvenMediaEngine#276]
I'm struggling to get reliable statistics out of an OME server. 
I'm trying to get some basics information:

Total number of applications
Total number of streams
Total number of viewers

(Of course detailed information like number of viewers per application / per stream / per protocol would be nice too)

About number of viewers, I think we are supposed to see the total number of viewers, refreshed every second, in logs like webrtc_rtsp_viewers.log. (WEBRTC.SS,CONN_COUNT). But that number always stays at 0. Looking at the code, it looks like it's because only the default application with a specific stream name get logged, so we can't use it.

The only way I found so far is to directly monitor ovenmediaengine.log (with the tool swatchdog), and try to match string like "createClientSession" or "has been stopped playing stream" then increment or decrement my own counter of viewers. But it's fairly unreliable, when too many viewers come at once or leave at once it's easy for the monitoring tool to miss an update, and then the counter goes out of sync. 

In any case, it seems a bit dodgy for me to try to keep track of the viewers by analyzing the logs. Surely OME itself must have this kind of information anyway and could dump it in the logs from time to time.

Did I miss any other way ? Is the only solution so far is to modify the source code of OME ?

**Comment by command-tab** [comment]
Have you taken a look at the REST API? The docs are not quite yet ready, but the details are in the source code. Once enabled, you can make an HTTP GET request to a URL like http://hostname:apiport/v1/stats/current/vhosts/default/apps/appname/streams/stream1234 and get a response like this:

```json
{
"createdTime": "2021-01-29T10:55:26.834-0800",
"lastRecvTime": "2021-01-29T11:04:08.803-0800",
"lastSentTime": "2021-01-29T11:04:07.680-0800",
"lastUpdatedTime": "2021-01-29T11:04:08.803-0800",
"maxTotalConnectionTime": "2021-01-29T11:03:34.761-0800",
"maxTotalConnections": 30,
"totalBytesIn": 204063278,
"totalBytesOut": 43471342,
"totalConnections": 4
}
````

For this stream (`stream1234`) under this app (`appname`), `maxTotalConnections` is the peak/high water mark, and `totalConnections` is the current number of viewers.

**Comment by Arzar** [comment]
> Have you taken a look at the REST API? 

I discovered it this morning while looking at the release note of yesterday's v0.11.0 :)
Looks amazing !

And thanks for the example, I had some trouble following the tree-structure like in src/projects/api_server/controllers/v1/ but now it's clearer. 

But just one question, I think the only way to get all the statistics is to query the list of all the applications, then query the list of all the streams per application, and the query the statistics of each stream one by one. But I think it would be very nice to have one API that aggregate all of that and send a consolidated report. It doesn't exist for now, right ?

For example, here is the statistics API from the videobridge of the Jitsi project (a webRTC video-conference). A videobridge is somewhat similar to an OME edge node:
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md

We get some nice high-level information like current number of stream, current total number of participant, current total bitrate, current total loss rate etc. It's very easy to query that single API and send the data to a time-series database like promotheus or influxdb. The community also created grafana dashboard based on it. All in all, it's super quick to set up a dashboard and monitor a fleet of server.

Anyway, thanks a lot for the pointer !

**Comment by command-tab** [comment]
To get the list of active streams, query something like `/v1/vhosts/default/apps/appname/streams`.

For more aggregate stats, you can also hit URLs like `/v1/stats/current/vhosts/default/apps/appname` and `/v1/stats/current/vhosts/default` to get the same stat names but at the higher levels of abstraction (i.e. across a whole vhost or app).

**Comment by Arzar** [comment]
Thanks for the help, it's working great !
![ome_stats](https://user-images.githubusercontent.com/316408/107935418-b5d76f00-6fc4-11eb-962e-9a1c88a42e94.png)

Also the new rest API documentation is very nice. 
I'm closing this bug.

**Comment by basisbit** [comment]
@Arzar could you maybe write a short tutorial for how you set up Grafana with the OME stats? What did you use as exporter for network usage and cpu usage? Would like to reproduce this for an OME demo setup and create a pull request for the OME documentation...

**Comment by genofire** [comment]
Do you write an own Prometheus-Exporter which scrape the REST-API ?
Where could find it?
(Or should i / we write one - or write somebody else an exporter included in OvenMediaEngine?)

**Comment by genofire** [comment]
Okay here it is: https://github.com/genofire/oven-exporter <- first version really hacky - PRs are welcome
