### ISSUE TITLE
Compatibility with Wirecast Go on iOS

### ISSUE THREAD

**Issue by command-tab** [AirenSoft/OvenMediaEngine#278]
I'm attempting to stream from [Wirecast Go](http://www.telestream.net/wirecast-go/overview.htm) on iOS 14.4 using its support for RTMP destinations:

![image](https://user-images.githubusercontent.com/3069/107606944-8e5f5b80-6bec-11eb-86b5-3708919ac061.png)

But when I point it at my 0.11.0 OME server and start the broadcast, OME only logs the following:

    [2021-02-10 21:58:53.466] I [PhyPortSerSock:66301] Provider | stream.cpp:49   | Unknown/(42) has been started stream
    [2021-02-10 21:58:53.466] I [PhyPortSerSock:66301] RTMPProvider | rtmp_provider.cpp:107  | A RTMP client has connected from 42 - <ClientSocket: 0x7f6ee8000960, #42, state: 4, TCP, redacted:61680>
    [2021-02-10 21:59:08.889] I [PhyPortSerSock:66301] RTMPProvider | rtmp_provider.cpp:132  | The RTMP client has disconnected: [Unknown/], remote: <ClientSocket: 0x7f6ee8000960, #42, state: 4, TCP, redacted:61680>

None of the publishers ever start producing output. Any idea why that might be? Wirecast Go has very few options, so there's no way to try other encoder settings. If I stop and switch to streaming from OBS Studio to the same RTMP destination, the publishers work and I can view the streams, so I know my OME setup works when given the proper input.

I had the same issue with the previous 0.10.11 release, as well.

**Comment by getroot** [comment]
I'll try installing Wirecast Go and look for compatibility issues with OME.

**Comment by getroot** [comment]
Works fine in my environment.
My iOS is 14.3 and it is an iPhone 7. There may be a problem with Wirecast Go.

I paid $7 to test this. Please give me a beer when we meet later. :-)
![image](https://user-images.githubusercontent.com/17779085/108043850-ed0d5500-7084-11eb-9256-1c37f362de75.png)

**Comment by command-tab** [comment]
Wild! Is your Server.xml doing bypass, or encode? I'm not sure if that would make a difference.

Thank you for investigating! Would you consider adding GitHub Sponsors to your organization? I'd be happy to support.
https://github.com/sponsors

**Comment by getroot** [comment]
@command-tab 

I tested it with default configuration. That means, video is bypass and audio is opus encoding.

Github sponsors do not accept Korean accounts yet. 
It's the thought that counts. :-)

**Comment by command-tab** [comment]
I rebuilt my OME installation from `master` (it was 0.11.0) using the same host and procedure as before, and Wirecast Go works now 🙌🏻 

Thank you so much! LMK if you're ever in the California Bay Area, and I'll buy you a drink 🍻
