### ISSUE TITLE
Bypass Profile

### ISSUE THREAD

**Issue by getroot** [AirenSoft/OvenMediaEngine#28]
Add a Bypass profile that streams directly through WebRTC without transcoding.

WebRTC is supported by various browsers and devices. However, each devices may support different codecs. Therefore, OvenMediaEngine requires transcoding to support all platforms. This makes it easier for users to use.

However, there is a requirement to stream directly without transcoding. In this case, some devices will not be able to play WebRTC. When the input signal is VP8 for Video and Opus for Audio, WebRTC will be played on the most devices. Since RTMP only supports H.264 and AAC, we are going to support the Bypass Profile after supporting MPEGTS/UDP or MPEGTS/SRT input. 

This enhancement is derived from issue #27.

**Comment by swinsey** [comment]
my rtmp inpurt is h264/aac, can you support video bypass and transcode aac to opus in the meantime.
thanks!

**Comment by AskAlice** [comment]
it seems that it's possible to set encode to bypass but the playback seems to error out even when setting all the OBS settings right

**Comment by getroot** [comment]
This is supported by version 0.10.0.
https://github.com/AirenSoft/OvenMediaEngine/releases/tag/v0.10.0
