### ISSUE TITLE
Grey screen/artifacts in chrome playback on occasion

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#283]
**Describe the bug**
Occasional grey screen/grey artifacts on WebRTC streams 
![image](https://user-images.githubusercontent.com/7061721/107851796-97158480-6dda-11eb-848d-ec0aa30be31b.png)

**To Reproduce**
Stream with OBS with the following settings 
![image](https://user-images.githubusercontent.com/7061721/107851806-a563a080-6dda-11eb-88df-5f4646316e37.png)

Watch with latest release of OMP in Chrome, wait some time. It appears to be random or at least I cannot predict when it will happen.

**Expected behavior**
No grey screens

**Logs**
Unfortunately I can't share logs at the moment, but I believe this is an encoder problem of some sort, not something OME is doing.

**Server (please complete the following information):**
 - OvenMediaEngine Version: [e.g. v0.10.1]
 - Branch: [e.g. dev]

**Player (please complete the following information):**
 - Device: Desktop
 - OS: Windows 10
 - Browser Chrome
 - Version 88.0.4324.150

**Additional context**
The grey rectangle in the middle is a censor, not part of the artifact. The grey portion can be any part of the stream but always starts from the top and goes down. It appears to reset when a keyframe is sent. Usually the grey section is more than half the screen.

This might be a question for ffmpeg devs or something, but I figured I'd post it here first just in case

**Comment by naanlizard** [comment]
I will test with the recommended ultrafast settings, but I would be surprised if changing the cpu preset IMPROVED quality, typically in my experience quality goes down the lower the cpu usage preset

**Comment by naanlizard** [comment]
Tune=zerolatency already sets bframes to 0.

Forcing a profile is bad practice and I can't see why that would improve things (if anything, profile baseline would tend to look worse).

CBR vs VBR I haven't tried, but will and will report back.

Keyframe interval helps reset things (every 1s there's a full frame, instead of every 4s) but that doesn't solve the issue to begin with.

**Comment by naanlizard** [comment]
CBR does not change the artifacting/grey screens, in any way I can tell

**Comment by getroot** [comment]
Most browsers only support H.264 Baseline Profile in webrtc. Therefore, it is recommended to specify the Baseline profile in OBS as well.

And I'm not sure, but isn't aq-strength=0 causing the gray screen? If you are bypassing transcoding in OvenMediaEngine, this is a compatibility problem with the browser's decoder and OBS's encoder. OvenMediaPlayer is also not involved in the decoder.

**Comment by naanlizard** [comment]
I've tried with Profile: Baseline - no noticeable change (except increased bandwidth usage of course, under VBR)

It might be aq-strength causing it, but I would be surprised since the recommended CPU Preset in the docs is ultrafast, which includes aq-strength=0. 

aq-strength=0 is required for firefox playback, in my testing. 

I'll try a shorter keyframe interval next, perhaps it is some sort of P frame error that is more likely the more p frames.

**Comment by naanlizard** [comment]
Shorter keyframe interval does not change anything, at this point I'm confused. Perhaps there is another setting difference between superfast and ultrafast, I'll try some more changes and report in again.

**Comment by naanlizard** [comment]
Ok even with settings exactly as recommended, grey screens still occur occasionally with the latest version of OBS.

Presumably it's some sort of ffmpeg/chrome bug - I'll keep investigating to see if I can trigger them on demand somehow

**Comment by getroot** [comment]
I've never seen a gray screen so far. Maybe there is an issue with your Chrome hardware decoder. If you find something new, please share it. Thank you!

**Comment by naanlizard** [comment]
Interesting. I'll be trying nvenc next, and maybe disabling chrome hardware acceleration will fix it on the viewer side

**Comment by naanlizard** [comment]
So with hardware acceleration *dis*abled in firefox, I no longer get the grey artifacting.

NVENC (new) on a 1080ti does not improve the artifacting on chrome.

So it seems it's a problem with the viewer's GPU. @getroot what browser/GPU do you use?

**Comment by getroot** [comment]
I always test with chrome, firefox, safari and edge. And my chrome and gpu info is as follows:
(For reference, OME currently operates without problems in commercial services targeting thousands of users.)

```

Data exported | 2021-04-12T02:28:49.068Z
-- | --
Chrome version | Chrome/89.0.4389.114
Operating system | Windows NT 10.0.19041
Software rendering list URL | https://chromium.googlesource.com/chromium/src/+/1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6/gpu/config/software_rendering_list.json
Driver bug list URL | https://chromium.googlesource.com/chromium/src/+/1ea76e193b4fadb723bfea2a19a66c93a1bc0ca6/gpu/config/gpu_driver_bug_list.json
ANGLE commit id | f25a0b5b404b
2D graphics backend | Skia/89 109bfc9052ce1bde7acf07321d605601d7b7ec24
Command Line | "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=SecurePaymentConfirmation


```

**Comment by basisbit** [comment]
> (For reference, OME currently operates without problems in commercial services targeting thousands of users.)

Are those users all in the same region as the stream source and the servers / in just one country and all with very low latency and very low packet loss? It seems like the OME testing is mostly done in local networks or similar - I'd suggest using something like [clumsy](https://github.com/IntouchHealth/clumsy) with 300ms additional lag, 1.5% packet drop chance and 2% chance for packets out of order, to test how OME streaming behaves over the internet with not so good connections.

**Comment by getroot** [comment]
@basisbit 

OME is streaming with WebRTC to more than 3000 concurrent users in Korea. The media source is hundreds of CCTVs and it streams on RTSP.

Korea( yes, of course, South Korea :-) ) has a better network environment than other countries, but not all of them are, and this is a paid service and a security service, so no exceptions should occur. So we developed WebRTC/TCP earlier this year. And it's working fine right now. This solves both problems in environments where user network has enough bandwidth but UDP packet loss and out of order are high.

**Comment by naanlizard** [comment]
Does the webrtc stream from ome to viewers use tcp or UDP by default, or has that changed recently?

Even with exactly the recommended settings we're still getting these artifacts, I tried massively increasing the bandwidth cap in OBS, no change. Maybe a bit less frequent?

**Comment by getroot** [comment]
@naanlizard 

WebRTC/tcp was recently added.
If you didn't do anything in the configuration, you are using UDP as before. Check out the link below!

https://github.com/AirenSoft/OvenMediaEngine/issues/287

https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#webrtc-over-tcp

I think it's worth checking if UDP packet loss is the cause of such artifacts.

**Comment by bchah** [comment]
Transport is UDP by default but can be changed to use the built-in TURN server and TCP.

In my experience this is a silver bullet that fixes playback issues in places where we don’t have the same internet strength as South Korea :)

It’s very easy to test, all you need to do is add one line to the OME config, open one additional port for TCP relay, and add “?transport=tcp” to your WebRTC playback URL. I also reduced the ICE port range to a single port, but I can’t confirm if that has any real effect or is just placebo.

Docs on TCP transport are here:

https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing <https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing>

**Comment by naanlizard** [comment]
Thank you two, does that seriously change the load on the ome server to use tcp instead of UDP? 

As long as it isn't like 50%+ increase it would be fine, I'd just worry it will scale with viewers

Will try it soon and report back - thank you! 

Eventually I'll start helping build or improve an admin panel for ome and we can switch to ome exclusively instead of ome and nginx

**Comment by bchah** [comment]
I don’t fully have a handle on how the UDP transport function works behind the scenes, since it still uses stream bandwidth * viewer count in terms of required throughput. In my experience changing to TCP did not affect the amount of network traffic or CPU load in a noticeable way.

**Comment by getroot** [comment]
Since the TURN server is very efficient built-in, the load on OME has barely increased. Only packets that exist only in TCP are added (for example, packets like syn/ack) and I think this is a small difference compared to the total traffic in a modern network environment.

Let me share one of my experiences.
We have confirmed that 3450 RTSP inputs and 3450 WebRTC/tcp outputs work stably in a 20core/40thread CPU, 32MB memory, video only, 500Kbps video source environment. (At this time, CPU usage was about 2000%, Memory usage was about 10%. WebRTC RTX and FEC were off) And this was similar to WebRTC/udp. Of course, to achieve 3500 inputs and outputs, OME's thread settings must be fine-tuned. This will be documented later if I have a chance.

**Comment by basisbit** [comment]
UDP usually needs one port per concurrent client, because it doesn't have connections.
Afaik, doing WebRTC video over TCP would need a TURNS like coturn server as relay (or does OME now have its own TURN server which supports DTLS, SRT and so on?), which you'll want to listen to TCP/443/TLS and TCP/3478 to be able to get through usually firewalls. It might be helpful to add a Docker container config to the docker-compose.yml so it is easier for people to evaluate and test it?

**Comment by getroot** [comment]
@basisbit 

Even in the case of UDP, the client's ip/port is used to distinguish them, so the server can handle multiple clients with a single port. And OME still works that way.

We have built in TURN function instead of using external server like coturn. I wrote the details in the comment above, but check the link below.

#287 

https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#webrtc-over-tcp

It operates very efficiently because it has a built-in TURN function. As you can see from #287, I hope to fully test this. And now I think the test is almost complete and I will put this as the default function of docker and Server.xml soon.

**Comment by getroot** [comment]
OME cannot allocate the same port number to HTTP, RTMP, or TURN servers due to its design structure. Improving to use the same port is registered as a task in our backlog, but the priority is low yet.
