### ISSUE TITLE
Allow multiple Signed Policies

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#284]
The signed policy is a significant feature for access control and works very well. However there is a vulnerability in it, because there can only be one signed policy which must allow both providers and publishers. Please consider allowing use of multiple signed policies, each differentiated by different query terms as in the example below:

```
...
<SignedPolicies>

  <SignedPolicy>

                                <PolicyQueryKeyName>p1</PolicyQueryKeyName>
                                <SignatureQueryKeyName>s1</SignatureQueryKeyName>
                                <SecretKey>PolicyForStreamCreatorsButNotPlayback</SecretKey>

                                <Enables>
                                        <Providers>rtmp</Providers>
                                </Enables>

      </SignedPolicy>

      <SignedPolicy>

                                <PolicyQueryKeyName>p2</PolicyQueryKeyName>
                                <SignatureQueryKeyName>s2</SignatureQueryKeyName>
                                <SecretKey>PolicyForPlaybackOnly</SecretKey>

                                <Enables>
                                        <Publishers>webrtc</Publishers>
                                </Enables>

                        </SignedPolicy>
</SignedPolicies>
...
```

This would greatly increase the security of OME, because currently the single signed policy could be used to send a stream in when the original stream is not active. Thank you for your wonderful creation!

**Comment by getroot** [comment]
Since the signature is created using the entire url (rtmp://~~, http://~~), I think that an unauthorized user cannot transmit the stream unless the secret key is exposed. Could you please tell me in more detail?

**Comment by bchah** [comment]
My friend, you are correct - I am sorry I did not think of this! There is no vulnerability then, since the keys are different. Thank you so much for your contributions on OME.

 Maybe this helps the community, an example of signing the stream key in PHP: 

```
$policy_term = "yourPolicyQueryTermHere";
    $signature_term = "yourPolicySignatureTermHere";
    $base64_encoded_policy = "yourEncodedPolicyHere";
    $hmac_private_key = "yourSecretKeyHere";

    $hmac_string = $base_url . "/" . $stream_key . "?" . $policy_term . "=" . $base64_encoded_policy;
    $signature = pack('H*', hash_hmac("sha1", $hmac_string, $hmac_private_key));
    $base64_encoded_signature = str_replace(['+', '/', '='], ['-', '_', ''], base64_encode($signature));

    $final_stream_key = $stream_key . "?" . $policy_term . "=" . $enc_policy . "&" . $signature_term . "=" . $signature;

```

**Comment by getroot** [comment]
If you give PR of the PHP version like the NODEJS version below, it will help a lot to open source.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/signed_policy_url_generator.js

Thank you.

**Comment by bchah** [comment]
Yes I would be happy to @getroot, I will convert it to use similar variable names. Happy to help.
