### ISSUE TITLE
List issues when building for Raspberry Pi, with gcc 8.3

### ISSUE THREAD

**Issue by leoheck** [AirenSoft/OvenMediaEngine#288]
**Describe the bug**

Hello folks. I am trying to build this on Raspberry Pi 3.
I am using gcc 8.3 as you can see on logs here.

```
➜ make release                           
####################################################
#                                                  #
#           AirenSoft Make System v0.63            #
#                                                  #
####################################################
   - Operating system        : linux
   - Core count              : 4
   - GCC version             : 8.3.0
   - Build option            : RELEASE
   - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
   - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig
   - Total Projects count    : 44

[  1/296|  0%] Preparing directories...
[  2/296|  0%] [static] libovlibrary.a: C++ projects/base/ovlibrary/string.cpp => intermediates/RELEASE/objs/base/ovlibrary/string.o
projects/base/ovlibrary/string.cpp: In member function ‘size_t ov::String::Format(const char*, ...)’:
projects/base/ovlibrary/string.cpp:298:27: error: invalid types ‘va_list {aka __va_list}[int]’ for array subscript
   VFormat(format, &(list[0]));
```

**Server (please complete the following information):**
 - OS: `Raspbian GNU/Linux 9.13 (stretch)`
 - OvenMediaEngine Version: `latest`
 - Branch: `master (770c2e4396f825406b6c4afae8cc886f58b129e9)`

**Additional context**

So, I am seeing errors like this
```
[  2/296|  0%] [static] libovlibrary.a: C++ projects/base/ovlibrary/string.cpp => intermediates/RELEASE/objs/base/ovlibrary/string.o
projects/base/ovlibrary/string.cpp: In static member function ‘static ov::String ov::String::FormatString(const char*, ...)’:
projects/base/ovlibrary/string.cpp:340:34: error: invalid types ‘va_list {aka __va_list}[int]’ for array subscript
   buffer.VFormat(format, &(list[0]));
```

I am was to compile by replacing, this
```
buffer.VFormat(format, &(list[0]));
```
with this
```
buffer.VFormat(format, list);
```
But I am not sure it is the same thing. How do I fix this in the right way?

**Comment by dimiden** [comment]
@leoheck 
It's correct to use the ```va_list``` as you modified it. (I don't know why I used the pointer.)
I fixed it right away and pushed it!

**Comment by leoheck** [comment]
there are other issues that are preventing it from building.. I will share a diff later, they are mostly some castings when using min/max both parameters have to be the same type.

I was able to build this on my Raspberry Pi, but I saw a segfault when I tried to execute it. I will try to debug this later too.

**Comment by getroot** [comment]
@leoheck 
After successful installation of OME on Rasberry Pi, it can be a very big contribution if you PR about it. Thank you.

**Comment by leoheck** [comment]
Interesting. I am curious if this runs on ARM processors, and Raspberry has one, then it is a good start.
