### ISSUE TITLE
Issue Building on Raspberry Pi the Debug version

### ISSUE THREAD

**Issue by leoheck** [AirenSoft/OvenMediaEngine#290]
Somethings has happened building this as debug. 
I am building this on a RPi 3, with GCC 8.3
I was able to build the Release, from the master branch. 
Since it was segfaulting I am building the Debug version.. and something has happened here, just sharing this. I didn't have time to investigate yet

![image](https://user-images.githubusercontent.com/1277920/108517725-88c9db80-72a6-11eb-8588-ae6dcc8cb8fe.png)

**Comment by basisbit** [comment]
Afaik, you need at least 8GB of RAM to compile OvenMediaEngine.

**Comment by leoheck** [comment]
This is interesting since I was able to compile the Release build. It completed fine.
So. maybe the Debug build needs more RAM.  I will check if I can increase the swap file to overcome this.

**Comment by getroot** [comment]
This issue has not been updated for a long time, so I close the issue. If you would like to continue discussing this issue, please reopen it.
