### ISSUE TITLE
OutOfMemory error hours after streaming stopped

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#291]
**Describe the bug**
It seems there is a memory leak when a client tries to HTTP GET a HLS playlist file which an OME edge server with OVT uplink does not have available yet.

**To Reproduce**
1. origin server sends the stream to the edge servers over ovt
2. clients watch the stream (500Kb/s low resolution stream in this case, clients are a free/libre open source game within webbrowser)
3. the streamer stops the stream
4. clients continue polling the m3u8 file every few seconds from the edge server (or much more often if you want to reproduce the bug)

**Expected behavior**
Used memory should stay constant, and not grow with each request for a not existing playlist

**Additional context**
- used memory grows constantly and does not get freed up when the clients all closed their webbrowser windows.
- disk free space does not grow much
- should be easy to reproduce by having a client continuously poll a stream playlist file with a not used playlist name (random stream key in obs)
- this allows for a very easy denial of service attack
- Origin only has RTMP and OVT configured, no other provider
- Edge server only has OVT as source and HLS as provider configured

**Comment by getroot** [comment]
Please upload your Server.xml file

**Comment by basisbit** [comment]
here is the server.xml: https://gist.github.com/basisbit/0633b3b2eab02263bc3f243b0d9daa83

**Comment by getroot** [comment]
@basisbit 
I found a fatal memory leak in OVT Provider and fixed it. Thanks for the report. Please check if the problem is resolved in your environment.

**Comment by basisbit** [comment]
wow, that was a super fast fix! Thank you!
My next opportunity to test this with a bigger number of users in production should be the upcoming weekend. I'll close this issue after confirming that the problem is resolved.

**Comment by basisbit** [comment]
I did some preliminary testing and it seems that either the problem is resolved thanks to your code improvements, or at least there is much less amounts of memory leaking. Thank you again!
