### ISSUE TITLE
Origin server with rtmp and ovt enabled is leaking threads until OOM

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#293]
**Describe the bug**
OME seems to not correctly close/stop threads when running as an origin server which is configured to distribute incoming rtmp streams to edge servers which pull over OVT. This eventually causes the linux kernel to close the process with return code 6 or with OOM error, depending on if it hit threads count limit or memory limit first.

**To Reproduce**
1. Set up an origin server with rtmp inbound and ovt outbound, nothing else.
2. Set up an edge server with ovt inbound and HLS outbound.
3. Have many clients watch a video livestream (using hls.js and infinite recovery/retry with 5s delay) and one video streamer send an rtmp stream from OBS (the typical 2s keyframe, 0 b-frames, 30fps, CBR)
4. Have the OBS streamer stop the stream.
5. Watch threads count on the origin server increase steadily while there are also many log entries of the origin stream not being found.

**Expected behavior**
Threads count should not grow, memory usage should not grow over time.

**Logs**
Lots and lots of entries like `E [PhyPortWorker:14] Orchestrator | orchestrator.cpp:478  | Could not find Origin for the stream: [#default#something/streamkey42]`

![image](https://user-images.githubusercontent.com/10870269/108639121-24b83a80-7493-11eb-8fe2-1078ab1593e1.png)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04 + current docker
 - OvenMediaEngine Version: v0.11.0
 - Server.xml see https://gist.github.com/basisbit/1b704329404273ecd91f2a529242d8a1

**Player (please complete the following information):**
 - any, using hls.js configured to infinite retries on fatal errors.

**Additional context**

**Comment by getroot** [comment]
Unfortunately this doesn't reproduce in my environment. Could you test again with the latest master branch version? The problem addressed earlier may be related to this. (This can happen when the Edge keeps making new connections without disconnecting)

**Comment by basisbit** [comment]
The problem seems to be mostly resolved now. However, because of your answer, I'd like to ask if an attacker could still use this for a denial of service attack by directly sending requests to the OVT port if they get to know the public IP address of the origin server? 

If yes, besides firewall-filtering access from not trusted IP addresses, are there any other suggestions for production environments or ways to further improve resilience of the OVT publisher?

**Comment by getroot** [comment]
The previous issue seems to be that the thread did not terminate due to a memory leak. There is also a fix on the Origin side and that may have fixed the problem. (To be exact, OVT Packetizer and Depacketizer) So there will be no related problems now.

In addition, it is the best security method to allow Origin server only IP of edge server. It would be good not only for this issue but also for many other aspects.

There seem to be several ways to fundamentally solve this problem.

1. Control access to Edge in Origin's settings (IP or authentication, etc.)
2. If the Edge connected to Origin doesn't do anything, timeout is applied (but it cannot be a complete solution to DoS attack)

**Comment by lee-hammer99** [comment]
@basisbit 

Hello!
I'm PR manager at OvenMediaEngine.

I'd love to hear your story and experience about using OvenMediaEnigne!

Your story is one of the ways to check whether our open-source is headed in the right direction, and it will make a huge contribution to the open-source development and community.

Could you please email me at [hammer99@airensoft.com](mailto:hammer99@airensoft.com)?

Thank you for using OvenMediaEngine.

**Comment by basisbit** [comment]
@lee-hammer99 I am quite busy at the moment because of the datacenter burndown at OVH yesterday, but will gladly write down the story as soon as I have some free time again
