### ISSUE TITLE
feature: add version tags on dockerhub for 0.10 and 0.11

### ISSUE THREAD

**Issue by f1-outsourcing** [AirenSoft/OvenMediaEngine#299]
Maybe easier for people to get updates.
tags on dockerhub for 0.10 that is linked to the latest 0.10.x

**Comment by getroot** [comment]
We still want people to always use only the latest version. We will consider your comments when the major version is updated (1.x.x, 2.x.x).

You just need to update it to your own personal Docker Hub. Luckily we keep all release versions on the docker hub.
