### ISSUE TITLE
Adding new VHost without restarting the service

### ISSUE THREAD

**Issue by ed96win** [AirenSoft/OvenMediaEngine#300]
**Is your feature request related to a problem? Please describe.**
I need to add new VHosts without restarting the ovenmediaengine. (aka reloading the configuration). could that be a possible feature?

**Comment by getroot** [comment]
Unfortunately OME doesn't support it yet. We will support it in the REST API in the future.
https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/virtualhost
