### ISSUE TITLE
"Unsupported Codec has been received"

### ISSUE THREAD

**Issue by pascalmatthaeus** [AirenSoft/OvenMediaEngine#301]
Good Day AirenSoft-Team,

I am writing you in hope of some assistance for testing your software, the Oven Media Engine, on Arch Linux (Linux Kernel 5.11 on a modern desktop machine with dGPU).
Beside the docker container, on bare metal, I am running an nginx server. Previously, I ran this nginx server to receive a video stream from a custom Java application, create a m3u8 playlist along with HLS-segments and host my HTMLs including the video player for clients.
After discovering that pure RTMP is not an option and any HTTP-based method is not fit for sub-second latency streaming, I started to research further on this topic and found out about WebRTC and your software.
Then I disabled the RTMP server within nginx and started running the docker version of your Oven Media Engine. I keep hosting the demo page of your Oven Player on the nginx for playback though. The content of my Server.xml you can find at the bottom of this mail.
Streaming from OBS to rtmp://x.x.x.x:1935/app/stream works perfectly smooth and actually yields sub-zero latencies in my local network. 
Streaming my smartphone camera/display via Oven Media Encoder app has worked flawlessly as well. 
Unfortunately, streaming from ffmpeg to the RTMP address is not possible for me. Whenever I start streaming, the client's player keeps looping infinitely, trying to load the stream and then resetting.
Looking at the docker logs, I noticed that whenever ffmpeg is streaming to the RTMP address, the log of the OME container will be filled with the following message:

E [PhyPortWorker:54] Provider | stream.cpp:78   | The packet type must be specified. #default#app/stream(32)

As I lack low-level knowledge of OMEs implementation and have "just started" working with videos a few months ago, I do not understand this message.

This is my ffmpeg command (I have tried several variations of switches and formats):

ffmpeg -y -re -stream_loop -1 -i sample-mp4-file.mp4 -c:v libx264 -profile:v main -bf 0 -tune zerolatency -f flv rtmp://127.0.0.1/app/stream

Trying to provide the video file to UDP port 4000 yields the following log message:

MPEGTS_DEPACKETIZER | mpegts_depacketizer.cpp:552  | Unsupported codec has been received. (pid : 256 stream_type : 6)

ffmpeg command for UDP:

ffmpeg -y -re -stream_loop -1 -i sample-mp4-file.mp4 -c:v libx264 -f mpegts udp://127.0.0.1:4000/

I hope you can help with my issue and send you best regards.

Server.xml content:

<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
<Name>OvenMediaEngine</Name>

<Type>origin</Type>

<IP>*</IP>

<Bind>
<Providers>
<RTMP>
<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
</RTMP>
<MPEGTS>

<Port>4000-4001,4004,4005/udp</Port>
</MPEGTS>
</Providers>

<Publishers>

<OVT>
<Port>${env:OME_ORIGIN_PORT:9000}</Port>
</OVT>
<HLS>
<Port>${env:OME_HLS_STREAM_PORT:8080}</Port>

</HLS>
<DASH>
<Port>${env:OME_DASH_STREAM_PORT:8080}</Port>

</DASH>
<WebRTC>
<Signalling>
<Port>${env:OME_SIGNALLING_PORT:3333}</Port>

</Signalling>
<IceCandidates>
<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>
</IceCandidates>
</WebRTC>
</Publishers>
</Bind>

<VirtualHosts>

<VirtualHost include="VHost*.xml" />
<VirtualHost>
<Name>default</Name>

<Host>
<Names>

<Name>*</Name>
</Names>

</Host>

<Applications>
<Application>
<Name>app</Name>

<Type>live</Type>
<OutputProfiles>
<OutputProfile>
<Name>bypass_stream</Name>
<OutputStreamName>${OriginStreamName}</OutputStreamName>
<Encodes>
<Audio>
<Bypass>true</Bypass>
</Audio>
<Video>
<Bypass>true</Bypass>
</Video>
<Audio>
<Codec>opus</Codec>
<Bitrate>128000</Bitrate>
<Samplerate>48000</Samplerate>
<Channel>2</Channel>
</Audio>
</Encodes>
</OutputProfile>
</OutputProfiles>
<Providers>
<OVT />
<RTMP>
<BlockDuplicateStreamName>true</BlockDuplicateStreamName>
</RTMP>
<RTSPPull />
<MPEGTS>
<StreamMap>

<Stream>
<Name>stream_${Port}</Name>
<Port>4000-4001,4001,4004</Port>
</Stream>
<Stream>
<Name>stream_4005</Name>
<Port>4005</Port>
</Stream>
</StreamMap>
</MPEGTS>
</Providers>
<Publishers>
<SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
<OVT />
<WebRTC>
<Timeout>30000</Timeout>
</WebRTC>
<HLS>
<SegmentDuration>5</SegmentDuration>
<SegmentCount>3</SegmentCount>
<CrossDomains>
<Url>*</Url>
</CrossDomains>
</HLS>
<DASH>
<SegmentDuration>5</SegmentDuration>
<SegmentCount>3</SegmentCount>
<CrossDomains>
<Url>*</Url>
</CrossDomains>
</DASH>
<LLDASH>
<SegmentDuration>5</SegmentDuration>
<CrossDomains>
<Url>*</Url>
</CrossDomains>
</LLDASH>
</Publishers>
</Application>
</Applications>
</VirtualHost>
</VirtualHosts>
</Server>

**Comment by getroot** [comment]
Perhaps the audio codec in the sample-mp4-file.mp4 file is a codec that OME does not support. Try the following:

https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta#publish

**Comment by pascalmatthaeus** [comment]
Thanks for the quick answer!

I now tried using exactly the command for streaming video & audio in your link. That worked, no errors in the logs and the stream is visible for the client.
If I use the same command but omitting the audio (-an switch and without the -pes_payload_size option), it still doesn't work and yields the error "Unsupported codec has been received." from the MPEGTS depacketizer.

Also, using the same command but instead of UDP, publishing via RTMP, still doesn't work for me. 

This is my command:

ffmpeg -re -stream_loop -1 -i rec.mkv -c:v libx264 -bf 0 -x264-params keyint=30:scenecut=0  -acodec aac -pes_payload_size 0 -f flv rtmp://127.0.0.1:1935/app/stream

Instead of the sample-mp4-file, now I am using a screen recording of about 20 seconds created with OBS studio. The logs derived from docker tell me this:

[2021-03-11 00:20:17.492] E [AppWorker:73] LLDASH | cmaf_packetizer.cpp:275  | Could not parse SPS (SPS: -1--1, PPS: -1--1) from LLDASH frame for [#default#app/stream]

Best regards.

**Comment by getroot** [comment]
This is the FFMPEG command for RTMP that I use mainly when testing. Please refer to this and compare it with your ffmpeg command. In RTMP, pes_payload_size 0 does not apply.

# Video / Audio
$ ffmpeg -re -stream_loop -1 -i <file.ext> -vcodec libx264 -preset ultrafast -threads 6 -b:v 1500k -acodec aac -b:a 256k -ar 96000 -f flv rtmp://<IP> :1935/app/stream
# Video Only
$ ffmpeg -re -stream_loop -1 -i <file.ext> -vcodec libx264 -preset ultrafast -threads 6 -b:v 1500k -an -f flv rtmp://<IP>:1935/app/stream
# Audio Only
$ ffmpeg -re -stream_loop -1 -i <file.ext> -vn -acodec aac -b:a 256k -ar 96000 -f flv rtmp://<IP>:1935/app/stream

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
