### ISSUE TITLE
Segfault when stopping recordings via API

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#302]
**Describe the bug**
Sometimes OME abruptly stops with a SIGSEGV after sending the stopRecord command.

**To Reproduce**
Issue a ":stopRecord" API command to a current recording. The segfault mentions [FilePubWorker:31] if this helps your investigation.

**Expected behavior**
The recording should stop and the API should return a response with the details of the stopped recording.

**Logs**
Log is uploaded. 
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6116738/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Docker
 - OvenMediaEngine Version: 0.11.x
 - Branch: dev

**Additional context**
I wonder if it is an issue with open handles on the recording file. Currently my process is to issue the API command, wait 1 second, then issue a system command to FFMPEG to remux the file into MP4. But as the log shows, the segfault occurs before 200ms have passed, therefore I don't think my process is causing interference.

**Comment by getroot** [comment]
Thanks for the reporting. We'll look into this soon.

**Comment by bchah** [comment]
@getroot Just an update that this has not happened again since I changed from the release build to the latest dev build. I will close this for now and re-open it if I can reproduce the issue again. Thanks!
