### ISSUE TITLE
Stream Key in url

### ISSUE THREAD

**Issue by kmzz** [AirenSoft/OvenMediaEngine#303]
Cannot start streaming if streaming key in URL like follow:
rtmp://streamer.mynet.local:1935/app/livestream

1. Start OBS 2.6.11
2. Click Settings -> Stream
3. In Service drop-down list select: Custom
4. In Server field enter: rtmp://streamer.mynet.local:1935/app/livestream
5. Stream key field left empty
6. Click OK
7. Click Start Streaming
8. Get Error: Failed to connect. Could not access the specified channel or stream key, please double-check your stream key. If it is correct, there may be a problem connecting to the server.
9. See in log OME next:

[37m[2021-03-11 18:33:38.377] I [PhyPortSerSock:61] Provider | stream.cpp:49   | Unknown/(36) has been started stream
[37m[2021-03-11 18:33:38.377] I [PhyPortSerSock:61] RTMPProvider | rtmp_provider.cpp:107  | A RTMP client has connected from 36 - <ClientSocket: 0x7fea78000b90, #36, state: 4, TCP, 172.30.254.108:60316>
[37m[2021-03-11 18:33:38.423] I [PhyPortSerSock:61] RTMPProvider | rtmp_provider.cpp:132  | The RTMP client has disconnected: [Unknown/], remote: <ClientSocket: 0x7fea78000b90, #36, state: 4, TCP, 172.30.254.108:60316>

If remove stream key from the URL and enter it in field "Stream key" OBS and try start streaming - works fine. 

 - OS: Docker
 - OvenMediaEngine Version: v0.10.1

**Comment by basisbit** [comment]
In the Server field put ´rtmp://streamer.mynet.local:1935/app/´ and in the key field put ´livestream´. You are welcome.

Please close this issue if it answered your question.

**Comment by kmzz** [comment]
> In the Server field put ´rtmp://streamer.mynet.local:1935/app/´ and in the key field put ´livestream´. You are welcome.
> 
> Please close this issue if it answered your question.

I know that this is so, but I need the stream key to be exactly part of the URL.

In [manual pages](https://airensoft.gitbook.io/ovenmediaengine/live-source/rtmp) :
> Moreover, some encoders can include a stream key in the URL, and if you use these encoders, you need to set it as follows:
> URL RTMP://OvenMediaEngine IP:RTMP Listen Port/App Name/Stream Name

I think it should work, but in fact it doesn't

**Comment by basisbit** [comment]
afaik, that should only be a configuration issue for your streaming software, not for OME.

**Comment by kmzz** [comment]
> afaik, that should only be a configuration issue for your streaming software, not for OME.

Perhaps I agree, but in fact I'm trying to use another software (paid) that does not have the ability to separately give stream_key, only as part of the stream url.

I reproduced the same bug on OBS for an example.

**Comment by basisbit** [comment]
does there exist a demo version or similar of that software, so we can test it?

**Comment by kmzz** [comment]
> does there exist a demo version or similar of that software, so we can test it?

Software: Cisco Meeting Server 2.9 
I think the demo does not exist.  

Currently I use nginx + rtmp and it works, but I would like to use OME.

**Comment by getroot** [comment]
@kmzz 
It is not an RTMP specification to extract the stream key from the url and use it. But of course we can implement it. (Function to extract stream key from URL when stream key is not input)
Do you mean there is an encoder that works like this?

**Comment by kmzz** [comment]
> @kmzz
> It is not an RTMP specification to extract the stream key from the url and use it. But of course we can implement it. (Function to extract stream key from URL when stream key is not input)
> Do you mean there is an encoder that works like this?

In software Cisco Meeting Server (CMS) 2.9, you cannot specify the stream key separately.
Maybe CMS separates stream key during RTMP call. How can I check this?

**Comment by getroot** [comment]
@kmzz 
Sorry, but I have no experience with Cisco Meeting Server. But I think I can't push RTMP to OME because it's a Server.
If that is possible, what is the scenario where you want to push RTMP from Cisco Meeting Server to OME? I think you should contact Cisco Meeting Server for any issues related to Stream key.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
