### ISSUE TITLE
Browser repeatedly loads the Manifest and OvenPlayer shows a black screen

### ISSUE THREAD

**Issue by Reilaen** [AirenSoft/OvenMediaEngine#304]
**Describe the bug**
I configured OME to only serve Dash and sendt a Stream via RTMP from OBS to it.
I opened the OvenPlayer and tryed to play the stream in Chrome but the screen stayed black. According to the Developer Toolbar the Manifest gets loaded infinitly and nothing more happens.

**To Reproduce**
1. Set Server.xml as follows:
https://pastebin.com/cXdXb5pS
2. Start a basic stream with OBS sending the RTMP to the OvenMediaEngine.
3. Open the site with OvenPlayer pointing to the dash manifest and start the stream.

**Expected behavior**
I expected that the stream loads and plays normally.

**Server:**
 - OS: Ubuntu Server 20.04
 - OvenMediaEngine Version: v0.11.0
 - Branch: I used the installation script from your getting started page.

**Player:**
 - OS: Windows 10
 - Browser: Chrome 88.0.4324.190
 - OvenPlayer: 57fec71
 - DashJs: v3.2.1

**Comment by basisbit** [comment]
Does DASH playback work for you when using dash.js 2.9.3 ?

**Comment by Reilaen** [comment]
I checked it. Yes, with dash.js 2.9.3 it works fine. It seems they did changes that broke something in combination with OvenPlayer.

**Comment by dimiden** [comment]
@Reilaen 
The compatibility with DASH 3.2.1 has improved in the latest version of OME.
(There are still known issues that do not play on FireFox, but I have fixed other playback issues)
And I checked that the ```Port``` and ```TLSPort``` of DASH are pointing to the same ```8080```. It will work well if you specify a different port.
