### ISSUE TITLE
A way to know when a manifest is available and playable

### ISSUE THREAD

**Issue by Reilaen** [AirenSoft/OvenMediaEngine#305]
I stream to OME via RTMP from my program and send a signal to my player that the stream started and it should load and play the manifest of the started stream.

My problem is that when i let my player load right after the stream starts the manifest isn't available.

I tried to use the API's current stream statistic to let the player load when the statistics returns a status of 200. That solved atleast trying to access a file that didn't exist yet. But i found out, that the manifest is empty at that point.

So for my purpose it would be nice to have some way to know when a manifest is available and playable.

**Comment by dimiden** [comment]
@Reilaen 
If you make a HTTP request while DASH/HLS segment is being created, ```202 Accepted``` will be responsed.
When OvenPlayer receives ```202``` status code, it retries the request so that the user can wait until manifest is created.

This is a non-standard one, so I will improve it if there is a better way.

**Comment by Reilaen** [comment]
Thank you for your reply, that is a good tip. I use VideoJS, but i will lookout for that 202 and use a retry to solve the issue.
