### ISSUE TITLE
Not a bug, but OSX doesn't support sys/epoll.h.

### ISSUE THREAD

**Issue by ahlininv** [AirenSoft/OvenMediaEngine#311]
Since last release it's totally impossible to build on OSX. Even if you want very much.
Maybe it will be more comfortable to use some portable wrapper for epoll.

**Comment by basisbit** [comment]
As a workaround, I'd suggest running OME in a docker container. That works great for development and for production environments.

**Comment by getroot** [comment]
@ahlininv 
We don't officially support OSX. (Sometimes a hero appears and is uploading a PR so that it can be compiled on OSX.) As in the basisbit's comment, using docker can be an alternative.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
