### ISSUE TITLE
Multiple streams

### ISSUE THREAD

**Issue by enigmathion** [AirenSoft/OvenMediaEngine#314]
Good morning, is it possible to transmit several streams on the same server? How would the configuration be if possible? Is there a way to insert an administration panel? Thanks a lot!

**Comment by basisbit** [comment]
Yes, this is supported. Just use different stream keys.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
