### ISSUE TITLE
RTMPS Provider Support

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#315]
**Is your feature request related to a problem? Please describe.**
Building secure deployments is limited if the RTMP stream we send to OME cannot be encrypted.

**Describe the solution you'd like**
Please consider implementing RTMPS provider support, to accept RTMPS streams (typically port 1936).

**Describe alternatives you've considered**
It might be possible to receive RTMPS from another server and push RTMP to OME, but this adds significant complexity and could impact the latency too.

**Additional context**
Please also consider adding RTMPS support to the Push Publishing feature, as it is now a requirement for some destinations. Thank you for your amazing work and for building OME.

**Comment by getroot** [comment]
Since the RTMP protocol is losing its share, we are hesitant to strengthen RTMP. As an alternative, I think it's a better choice to focus on protocols like WebRTC or SRT. What do you think?

**Comment by basisbit** [comment]
SRT would be very nice indeed, as that resolves lots of typical issues regarding internet connection / peering quality, packet loss and high latency. See https://castr.io/blog/srt-vs-rtmp/#:~:text=Testing%20for%20end-to-end%20latency&text=The%20end-to-end%20latency,12%20times%20faster%20than%20RTMP.

**Comment by bchah** [comment]
Hi @getroot and thank you for the response. You are correct that newer protocols like SRT are gaining popularity. However there are many existing programs and hardware deployments which will never be updated to these newer protocols. I understand there are only 24 hours in the day though 😀 So I will try changing my application to use SRT in the back-end.

**Comment by getroot** [comment]
@bchah That's great. I will start developing the SRT Ingest function soon.

**Comment by bchah** [comment]
@getroot SRT is excellent for ingest but RTMPS push functionality would be useful in a lot of cases. For example Facebook does not accept RTMP streams, only RTMPS.

**Comment by getroot** [comment]
Since we believe that RTMP is a protocol that will soon be completely deprecated, we have decided not to add support for RTMPS. Thanks for the good suggestion.

**Comment by getroot** [comment]
I open this again.
We will support RTMPS. However, it may take a long time because there are many higher priority tasks left.

**Comment by davemevans** [comment]
Please reopen this - contribution to Facebook requires RTMPS and it would be useful for OME to support this.

Whilst in the past it did appear RTMP might be going way, https://github.com/veovera/enhanced-rtmp is gaining traction and I think it's likely that RTMP will retain relevance for some time.

**Comment by bchah** [comment]
I think you can already do this with OME. RTMPS push works fine in my testing, and you can use an SSH tunnel on port 1936 for RTMPS inputs (See #1133). Still I agree it would be nice to have a *proper* RTMPS provider.

And @davemevans was RTMPS push not working for you?

**Comment by getroot** [comment]
Of course we will support Enhanced RTMP. However, it will probably take quite a while as we are too busy with commercial projects to survive for the rest of the year.

**Comment by davemevans** [comment]
RTMPS Push output didn't work for me but I'm fairly new to OME - I'll try again.

I just noticed that this issue is about _Provider_. Apologies for hijacking the thread.
