### ISSUE TITLE
Continue publishing when Provider is down

### ISSUE THREAD

**Issue by steve-o** [AirenSoft/OvenMediaEngine#317]
**Is your feature request related to a problem? Please describe.**
A live publisher disconnects, OME shuts down the Publisher, and all clients stop playing.  Can the Publisher continue emitting a signal to keep the clients connected?

**Describe the solution you'd like**
A configuration parameter, or default operation, that Publishers will not disconnect clients when the Provider disconnects.

**Describe alternatives you've considered**
Alternative is to have the OvenPlayer more resilient and be able to reconnect upon error.  There are parameters for HLS/DASH errors on connect, but nothing for errors during streaming, especially for webRTC clients which are just presented with an error message and the player stops attempting to resume.

**Comment by getroot** [comment]
Creating persistent streams makes resource management difficult. As in your opinion, a good alternative would be to try to reconnect in the player.

If you test at demo.ovenplayer.com, if webrtc is disconnected, the player tries to reconnect indefinitely, and when reconnected, you can see that it plays well again.

**Comment by basisbit** [comment]
You'll want to make your player resilient against playback errors anyways, so that it reconnects if the internet was down or a edge server died or similar, thus personally, I'd suggest favoring lower CPU requirements on the server instead.

**Comment by steve-o** [comment]
Thanks, I tested this again, and appears to reconnect successfully.
