### ISSUE TITLE
Multicast MPEG-TS Publisher support

### ISSUE THREAD

**Issue by steve-o** [AirenSoft/OvenMediaEngine#318]
**Is your feature request related to a problem? Please describe.**
Feeding a Haivision Makito encoded multicast feed into OME requires proxying through an external FFMPEG instance that copies UDP payload into TCP payload.

```MULTICAST_PORT=2000
MULTICAST_NETWORK=225.6.7.8

ffmpeg \
	-i udp://$MULTICAST_NETWORK:$MULTICAST_PORT \
	-c:v copy \
	-c:a copy \
	-f mpegts \
		udp://127.0.0.1:4000?pkt_size=1316
```

**Describe the solution you'd like**
Support configuration of MPEG-TS Publishers to include a multicast address for receiving UDP video.

**Describe alternatives you've considered**
As above, workaround is to proxy with an additional process.

**Comment by getroot** [comment]
I wonder how many OME users need Multicast MPEG-TS. And it is difficult to develop because I do not have a multicast network to develop this function. If you or someone else can help with this, I think it will be very helpful.

**Comment by steve-o** [comment]
Thanks, the code side for the networking is simple for IPv4, one simply requires a `setsockopt` call on a UDP socket with the multicast address and option `IP_ADD_MEMBERSHIP`, e.g.  https://github.com/steve-o/openpgm/blob/master/openpgm/pgm/sockaddr.c#L666

Testing is simple, use the following command line with an MPEG-TS file called `capture.ts`:
```
ffmpeg \
	-re -stream_loop -1 \
	-i capture.ts -c:v copy -c:a copy -f mpegts udp://225.6.7.8:2000
```
For me, the issue is largely over updating the configuration to support multicast addresses, something like this?
```
<Providers>
   <MPEG-TS>
      <MulticastGroup>225.6.7.8</MulticastGroup>
      <Port>4000</Port>
   </MPEG-TS>
</Providers>
```

**Comment by terafirmanz** [comment]
This would be helpful for us as we also have Makito boxes and can't send RTMP (as pretty much nothing else int he world will talk RTMP to a Makito box) and SRT won't work due to the URL encoding requirements as these boxes only support IP:port

Alt for us would be simple IP:Port SRT support or Makito RTMP compatibility (still testing TS over UDP as an option)

**Comment by mclayton7** [comment]
I would also be interested in multicast support. There are lots of use cases for receiving multicast MPEG-TS streams and sending those out over the web.

**Comment by mclayton7** [comment]
@getroot I'd be interested in contributing multicast support to the project. Any thoughts on what a good API would look like in the configuration? Maybe something like @steve-o suggested?

**Comment by nerijus** [comment]
@mclayton7 I'd suggest to create a PR, API can be easily modified later if needed.
