### ISSUE TITLE
how to record during the live casting？

### ISSUE THREAD

**Issue by xeonye** [AirenSoft/OvenMediaEngine#32]
thanks for your good solution！I appreciate to hear how to record during the live casting。

**Comment by JehoenHan** [comment]
OvenMediaEngine does not yet support recording.
We will develop DVR feature in the future, but there are many higher-priority things, so we can't tell you the exact schedule right now.

Until we add the feature, you can record OvenMediaEngine's HLS output or MPEGDASH output URL with ffmpeg.

Thank you.

**Comment by xeonye** [comment]
Thank you
