### ISSUE TITLE
Transcoding the streams got on Edge via OVT from Origin.

### ISSUE THREAD

**Issue by davidghukasyan** [AirenSoft/OvenMediaEngine#320]
is there a way to get via OVT one stream and transcode(different OutputProfile-s) into different bit rates in the same application on Edge ?
(I rather not consume bandwidth on Origin that's why i dont want to transcode on Origin and than get all transcoded streams on Edge via OVT)

**Comment by getroot** [comment]
You can set the application on the edge in the same way as the origin. Put OutputProfiles in your application and you can use whatever you want.

**Comment by davidghukasyan** [comment]
> You can set the application on the edge in the same way as the origin. Put OutputProfiles in your application and you can use whatever you want.

Thanks for the answer, won't it affect my origin's network bandwidth  ?

**Comment by getroot** [comment]
If you set it that way, it doesn't affect the origin because edge encodes the stream.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
