### ISSUE TITLE
Audio Streaming and OpenWRT

### ISSUE THREAD

**Issue by AMargeri** [AirenSoft/OvenMediaEngine#321]
Hello my name is Angus from UK,
I am a bit of a novice so I am asking some naive questions.
I am wanting to take the output of a microphone and create a live audio stream which can be accessed from a smart phone browser on a WiFi Hotspot...can OME do that, does it need a separately installed web server like Nginx to serve the webpage to to the phone.
Additionally has anybody had success installing OME on OpenWrt?
thanks....

Angus

**Comment by getroot** [comment]
Grab the mic output with an encoder like OBS and send the stream to OvenMediaEngine. (If the encoder supports one of RTMP, MPEG-TS, WebRTC, RTSP Server, it can be linked) And embed OvenPlayer in your web page and play the output of OvenMediaEngine in the player as you want among webrtc, hld, dash.

For more information on OvenMediaEngine, refer to the manual.

https://airensoft.gitbook.io/ovenmediaengine/

Unfortunately I don't know OpenWrt so I can't comment about it.

**Comment by AMargeri** [comment]
Many thanks

Angus
