### ISSUE TITLE
Audio only OutputProfile?

### ISSUE THREAD

**Issue by GregOriol** [AirenSoft/OvenMediaEngine#325]
Hi,

We are currently deploying OvenMediaEngine for our streaming purposes and it works very well.

However, we are facing issues with people having very low bandwidths, and since we can't change their bandwidth, and it's also not very nice to send them some very low quality video (we tried down to 240p but it has a "there are technical issues" feeling for the non-technical user), I was wondering if it could be possible to have an OutputProfile in the Server.xml that specifies an audio only stream? Then, when the player switches to that source, we could replace the player's video display by a static image and let them just listen to a good audio, while the others still enjoy audio+video.

Best regards,

**Comment by getroot** [comment]
Leave only <Audio> in OutputProfile like below.

```
<OutputProfile>
	<Name>bypass_stream</Name>
	<OutputStreamName>${OriginStreamName}_audio</OutputStreamName>
	<Encodes>
		<Audio>
			<Bypass>true</Bypass>
		</Audio>
		<!--
		<Audio>
			<Codec>opus</Codec>
			<Bitrate>128000</Bitrate>
			<Samplerate>48000</Samplerate>
			<Channel>2</Channel>
		</Audio>
		-->
	</Encodes>
</OutputProfile>
```

This way you can play audio only by accessing ws[s]://<host>[:port]/<App Name>/<Stream Name>_audio.

**Comment by GregOriol** [comment]
Thanks, it works! I'll make a PR to the docs to add a word about that possibility :-)
