### ISSUE TITLE
I've installed OvenMediaEngine on a rPi4 (64bit), any way to output a stream to the pi HDMI port?

### ISSUE THREAD

**Issue by BrianGilbert** [AirenSoft/OvenMediaEngine#326]
I'm trying to replicate the functionality of the BlackMagic Streaming Bridge using open source software, first I tried https://aaronparecki.com/2020/09/07/7/raspberry-pi-streaming-server but latency is about 2-3 seconds

I've managed to install OvenMediaEngine using steps at https://github.com/AirenSoft/OvenMediaEngine/issues/316#issuecomment-812832271

I'm wondering if there would be any way to output an incoming stream via the Pi HDMI port?

**Comment by basisbit** [comment]
This is not anything OvenMediaEngine specific. You could use VLC media player or any similar software and have it play the stream on your raspberry pi.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
