### ISSUE TITLE
(question) how to access stats while running OME with docker?

### ISSUE THREAD

**Issue by ed96win** [AirenSoft/OvenMediaEngine#327]
I'm running the OME inside a docker container but I don't see any option to enable the API server, specify its port and specify the api key. can you guide me through that?

I'm new to docker containers. sorry if the question sounds silly.

**Comment by basisbit** [comment]
Please see https://github.com/AirenSoft/OvenMediaEngine/issues/276

**Comment by ed96win** [comment]
> Please see #276

Thanks. I know how to access the API (once enabled). but as a previously mentioned, while running it as a docker container the API Server is disabled 
`[2021-04-05 04:42:48.173] I [OvenMediaEngine:1] APIServer | api_server.cpp:30   | API Server is disabled`
and in neither of configuration files edge_config/origin_config there is a place where I can enable the api server.

**Comment by getroot** [comment]
@ed96win 
Please refer to the URL below to set.
https://airensoft.gitbook.io/ovenmediaengine/rest-api

**Comment by command-tab** [comment]
You may be able to inject a custom `Server.xml` config file at container runtime with [volumes](https://docs.docker.com/storage/volumes/). I'm planning to run OME under Kubernetes, and am thinking I'll use ConfigMaps to store my `Server.xml`, then mount it at runtime with `volume`/`volume_mount`.

**Comment by ed96win** [comment]
> @ed96win
> Please refer to the URL below to set.
> https://airensoft.gitbook.io/ovenmediaengine/rest-api

Thank you so much. I manually specified the API settings in the origin config and it worked. you rock!
