### ISSUE TITLE
"/opt/ovenmediaengine/" does not exist in docker install

### ISSUE THREAD

**Issue by ellitedev** [AirenSoft/OvenMediaEngine#329]
**Describe the bug**
I've installed OvenMediaEngine on a fresh docker server from digitalocean, through the docker command that's included in the quick start. Now I try to edit the config, but the directory /opt/ovenmediaengine/ does not exist, only containerd is in my /opt/ folder

**To Reproduce**
Install through docker command provided in quick start in wiki, on a digitalocean docker one click server.

**Expected behavior**
I expect the directory to exist in the location provided in the wiki.

**Logs**
I can't find these

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: 0.11.2
 - Branch: I imagine release?

**Additional context**
I used this `docker run -d \
-p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 3478:3478 -p 8080:8080 -p 9000:9000 -p 10000-10010:10000-10010/udp \
airensoft/ovenmediaengine:latest` command from your [wiki](https://airensoft.gitbook.io/ovenmediaengine/getting-started)

**Comment by getroot** [comment]
Find the folder inside of the docker container. You are probably looking for it in the host.
