### ISSUE TITLE
Can push stream but can't play

### ISSUE THREAD

**Issue by zw12579** [AirenSoft/OvenMediaEngine#33]
![image](https://user-images.githubusercontent.com/33717789/61195359-1f610e80-a6fa-11e9-84a6-965918f23e1b.png)
![image](https://user-images.githubusercontent.com/33717789/61195368-2ab43a00-a6fa-11e9-8ff5-9eae8b5fc404.png)
![image](https://user-images.githubusercontent.com/33717789/61195397-41f32780-a6fa-11e9-8136-480a2ce1a10c.png)
![image](https://user-images.githubusercontent.com/33717789/61195410-5e8f5f80-a6fa-11e9-9afe-4943590a21bc.png)

**Comment by JehoenHan** [comment]
Please provide the following information:

Server.xml
The version of the Browser that try to play
/var/log/ovenmediaengine.log (the log at the time the error occurred)

**Comment by zw12579** [comment]
I used the default configuration on the document.

![image](https://user-images.githubusercontent.com/33717789/61259072-2a27ac00-a7ab-11e9-8314-6a009a4feee7.png)

![image](https://user-images.githubusercontent.com/33717789/61259106-52afa600-a7ab-11e9-8aca-d1cd6eaad50a.png)

**Comment by dimiden** [comment]
This issue is related to [OpenH264](https://github.com/cisco/openh264), and we recently switched to libx264 because we found that there are some issues with OpenH264.
So, check out ```dev``` branch and it may resolve this problem. (Please don't forget to run ```misc/prerequisites.sh``` after checkout.)

The 500 error is side-effect from "Encode Frame Error" error and will be improved in the next version.

**Comment by zw12579** [comment]
I switched to the dev branch and still reported this error. Looking forward to your next version
![image](https://user-images.githubusercontent.com/33717789/61448862-551a2780-a986-11e9-800b-287d5e62bfae.png)

![image](https://user-images.githubusercontent.com/33717789/61448829-416ec100-a986-11e9-9701-43032364fc94.png)

**Comment by dimiden** [comment]
I think it's not built with the source code of ```dev``` branch. Please run ```make``` to rebuild the source code. :)

**Comment by zw12579** [comment]
thanks
I rebuilt them,but I got the same result

**Comment by dimiden** [comment]
Because the ```"Encode Frame Error"``` log was deleted from ```dev``` branch, if the result is same, it is not built properly.
Therefore, please clone OME again with the following command and build it again.

```git clone -b dev "https://github.com/AirenSoft/OvenMediaEngine"```

If you still have the same problem despite the rebuild, try reinstalling OME by running ```sudo make install``` command.
