### ISSUE TITLE
Sound very choppy and cutting with webrtc streaming

### ISSUE THREAD

**Issue by Arzar** [AirenSoft/OvenMediaEngine#334]
I'm using the latest stable docker version airensoft/ovenmediaengine:0.11.2

I have an Origin server accepting an rtmp h264 aac stream and an edge server delivering webrtc vp8 streaming. The user connect to the edge server using OvenPlayer. 

The video is fine and remain smooth during the entire streaming.
However the sound occasionally get very bad, extremely choppy, to the point we can hear only brief snippet of sound every few seconds. After 30 seconds/1 minute the sound get back to normal.

I noticed it occurs often when a speaker speaks continuously for 10/20 seconds then stop talking completely. One or two seconds later the choppiness start.

If I record on the origin server with the REST API, using a bypass stream (bypass audio, bypass video), then the resulting .mpg4 file have the same sound issue, at the same moment I heard them in the player.

But I if redirect the rtmp stream to an nginx/rtmp server instead of OME, then I can watch HLS output without trouble, the video and sound is fine, no issue.

Any idea what is going on ? Please advice how I can debug more, I'm a bit out of my depth here.

More details about my config :

This is how my rtmp stream is generated (it's coming from jibri, the recording system of jitsi meet)

`ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i plug:bsnoop -acodec aac -strict -2 -ar 44100 -b:a 128k -af aresample=async=1 -c:v libx264 -preset veryfast -maxrate 2976k -bufsize 5952k -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f flv rtmp://<ome origin url>.com:1935/app/test`

My origin server is configured to generate a vp8 stream and a bypass stream.
Also please see the full server.xml file of my edge and origin server in the attached zip
[server_config.zip](https://github.com/AirenSoft/OvenMediaEngine/files/6276898/server_config.zip)

```
                     <Name>vp8_stream</Name>
                     <OutputStreamName>${OriginStreamName}</OutputStreamName>
                     <Encodes>
                        <Video>
                           <Codec>vp8</Codec>
                           <Width>1280</Width>
                           <Height>720</Height>
                           <Bitrate>2000000</Bitrate>
                           <Framerate>30.0</Framerate>
                        </Video>
                        <Audio>
                           <Codec>opus</Codec>
                           <Bitrate>128000</Bitrate>
                           <Samplerate>48000</Samplerate>
                           <Channel>2</Channel>
                        </Audio>
                     </Encodes>
                  </OutputProfile>
                  <OutputProfile>
                     <Name>bypass_stream</Name>
                     <OutputStreamName>${OriginStreamName}_bypass</OutputStreamName>
                     <Encodes>
                        <Audio>
                           <Bypass>true</Bypass>
                        </Audio>
                        <Video>
                           <Bypass>true</Bypass>
                        </Video>
                     </Encodes>
                  </OutputProfile>
               </OutputProfiles>
```

The track declared in the log of the origin server are: 

```
Video Track #0: Bypass(false) Bitrate(2.00Mb) codec(1, H264) resolution(1280x720) framerate(30.00fps) timebase(1/90000)
Audio Track #1: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(s16, 16) channel(stereo, 2) timebase(1/48000)

Video Track #2: Bypass(true) Bitrate(0b) codec(1, H264) resolution(1280x720) framerate(30.00fps) timebase(1/1000)
Audio Track #3: Bypass(true) Bitrate(125.00Kb) codec(6, AAC) samplerate(1.0K) format(s16, 16) channel(mono, 1) timebase(1/1000)
```

But l also tried to set the vp8_stream Video to Bypass (so the keep the original x264) and get the same choppiness issue.
And If I set the Audio to bypass (so it should keep the original AAC), then there is no sound at all (with vp8 or h264) and I see in the edge log the following error : Unsupported codec(Audio/AAC) is being input from media track.

**Comment by basisbit** [comment]
Can you reproduce the problem when using for example OBS to stream something to the server and using a client in the same network as the server? (just to make sure it is not a congested network peering issue or an issue with your streaming source)

**Comment by Arzar** [comment]
Thanks.
Sorry I forgot to mention it. When I test streaming with OBS to my origin server there is no sound issue whatsoever.  
About network, My jibri (server producing the stream9 and OME origin and edge server are all in the same AWS region,  VPC and even subnet so I don't expect any network issue.

Also I have this sound issue even when I record on the origin server (with the REST API POST vhosts/default/apps/app:startRecord)  so I don't think my webbrowser or ovenplayer version matters. Already at the OME origin stage something is going on. But it anyway it's chrome 89.

**Comment by Arzar** [comment]
Also here are the ovenmediaengine.log with obs (no sound issue) and jibri(sound issue)

[jibri.log](https://github.com/AirenSoft/OvenMediaEngine/files/6282613/jibri.log)
[obs.log](https://github.com/AirenSoft/OvenMediaEngine/files/6282615/obs.log)

**Comment by getroot** [comment]
@Arzar 

Thanks for the detailed analysis.
It seems that OME's RTMP meta analyzer is not compatible with it. I'll take a closer look at this soon. I will reproduce it with the ffmpeg command above.

`ffmpeg -y -v info -f x11grab -draw_mouse 0 -r 30 -s 1280x720 -thread_queue_size 4096 -i :0.0+0,0 -f alsa -thread_queue_size 4096 -i plug:bsnoop -acodec aac -strict -2 -ar 44 100 -b:a 128k -af aresample=async=1 -c:v libx264 -preset veryfast -maxrate 2976k -bufsize 5952k -pix_fmt yuv420p -r 30 -crf 25 -g 60 -tune zerolatency -f flv rtmp://<ome origin url>.com:1935/app/test`

**Comment by Arzar** [comment]
Thanks !
Do you have any recommendation of parameters for ffmpeg to generate a RTMP stream that are know to work well with OME ?
There is an example of publishing mpeg-2-ts with ffmpeg in the documentation (https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta) it would be nice to also have an example for RTMP.

**Comment by getroot** [comment]
@Arzar 

When I test with ffmpeg, I mainly use the following basic commands.

`./ffmpeg -re -stream_loop -1 -i <file.ext> -vcodec libx264 -preset ultrafast -threads 6 -b:v 1500k -acodec aac -b:a 256k -ar 96000 -f flv rtmp://<IP >:<Port>/<App>/<Stream>`

**Comment by Arzar** [comment]
I finally found the source of my sound issue and it was not in OME, it was some wrong configuration of ALSA loopback in the jibri component...

About the mono/audio discrepancy described earlier in OME logs, I still find it a bit odd, but it's probably at best just a display error, anyway it doesn't affect the webrtc streaming.

Thanks for your help and sorry for creating a bogus github issue. I'm closing it.
