### ISSUE TITLE
Automatic make stream avaible at edge without request of client

### ISSUE THREAD

**Issue by KingHorse2015** [AirenSoft/OvenMediaEngine#335]
**Is your feature request related to a problem? Please describe.**
I have sync issues between quality levels, when I am trying to have a origin - edge configuration. This because most clients play the high bit variant. And so the low bit variant sometimes doenst have viewers for a couple of minutes, but when a new client comes in, it starts play the version of the low bit variant. But then my HLS playlist arent in sync anymore.

**Describe the solution you'd like**
Abilty to say to the edge, or the origin to push a stream forward, so both streams are created at the same time, removing the hls sync issue, or a setting to make the timeout high, say like 5-12 hours orso.

**Describe alternatives you've considered**
I currently have solved the issue with a javascript program, that polls both streams every 10 seconds on every server. To let OME think it has active viewers all the time.

**Additional context**
I have HLS with mutiple quality levels. One is source, one is 1024x576 1,5mbit transcoded version by OME. It works perfect on 1 on server, but would be nice to have a origin-edge infrastructure to scale to more users.

**Comment by getroot** [comment]
Currently, the function of pulling an external stream in OME (OVT, RTSP Client) automatically deletes the stream after 60 seconds if there is no user watching the stream. This is a resource-saving feature.

Your suggestion to be able to set that timeout value (currently fixed at 60 seconds) seems very useful. I'll work on it soon.

If you want to apply this function in advance, change the #define MAX_UNUSED_STREAM_AVAILABLE_TIME_SEC 60 value in src/projects/base/provider/pull_provider/application.h to the value you want.

**Comment by KingHorse2015** [comment]
Thanks in advance. I am sorry that I haven't replied earlier. I have been very busy.

**Comment by getroot** [comment]
I recently finished developing this feature.

https://airensoft.gitbook.io/ovenmediaengine/v/master-1/origin-edge-clustering#less-than-properties-greater-than

Added `UnusedStreamDeletionTimeout `setting.

If the feature doesn't work, please reopen this issue.
