### ISSUE TITLE
Controller not found 404 when api calling : GET -  v1/vhost

### ISSUE THREAD

**Issue by catapop84** [AirenSoft/OvenMediaEngine#336]
**Describe the bug**
I'm playing with the API, and I get this error when I call http://localhost:8081/v1/vhost with Basic Authorisation
```
{
  "message": "Controller not found (404)",
  "statusCode": 404
}
```
The streaming server is running ok.

**To Reproduce**
I enabled api from Server.xml
```
    <Managers>
        <Host>
            <Names>
                <Name>*</Name>
            </Names>
<!--            <TLS>-->
<!--                <CertPath>path/to/file.crt</CertPath>-->
<!--                <KeyPath>path/to/file.key</KeyPath>-->
<!--                <ChainCertPath>path/to/file.crt</ChainCertPath>-->
<!--            </TLS>-->
        </Host>
        <API>
            <AccessToken>ome-access-token</AccessToken>
        </API>
    </Managers>
```

**Expected behavior**
a 200 response

**Comment by dimiden** [comment]
@catapop84
The API for obtaining the vhost list is ```/v1/vhosts```, not ```/v1/vhost``` (```s``` is important). Please let me know again if there is an error even though you have called this API.

**Comment by catapop84** [comment]
ok. I'll reopen this to notify an error in documentation: https://airensoft.gitbook.io/ovenmediaengine/rest-api
```
Request Example:
- Method: GET
- URL: http://1.2.3.4:8081/v1/vhost
- Header:
  authorization: Basic b21ldGVzdA==
```

This is where I got the vhost (without ending s)

**Comment by dimiden** [comment]
@catapop84 
Oh, thanks! You found my mistake.
That's an example of API structure, so I didn't think about reviewing it. I just finished modifying it. If you want to refer to the API, please look at the subpages such as [VirtualHost](https://app.gitbook.com/@airensoft/s/ovenmediaengine/rest-api/v1/virtualhost)
