### ISSUE TITLE
(question) custom port mapping?

### ISSUE THREAD

**Issue by ed96win** [AirenSoft/OvenMediaEngine#337]
Hey. it's me, again. I hope that my questions won't bother you much.
Is it possible to use custom ports for the docker container in a situation where the default ports are being used by another application?
like, mapping 20000-20005 instead of 10000-10005 (udp) for ice candidates? 
I made a container using custom ports for that range, with the other ports being set on default, but the video doesn't play.
my assumption is that OvenPlayer is likely still trying to reach the default ports.

in that case, is it possible to specify ports to the player like that or it's kinda hardcoded?

**Comment by getroot** [comment]
This docker-compose.yml file might give you a hint.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/docker-compose.yml

Modify the following 2 lines.

-"10006-10010:10006-10010/udp"
-OME_ICE_CANDIDATES=*:10006-10010/udp

Alternatively, you can directly modify the following part of Server.xml: And when running Docker, open the port with -p 20000-20005/udp.

<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>

**Comment by ed96win** [comment]
Thanks for the reply. so, just like that, there's no modifying needed on the player side? it'll know what port to look for?

**Comment by basisbit** [comment]
because ome otherwise doesn't know the correct port which it should announce to clients.

**Comment by getroot** [comment]
To explain more specifically what the @basisbit said,
OME notifies the player that the stream is being sent using the 10006-10010/udp port set in Server.xml. (In the signaling phase to websocket 3333/tcp port) Then the player will request 10006-10010/udp for a stream.

**Comment by getroot** [comment]
The flow of WebRTC is well explained in the following URL.

https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Signaling_and_video_calling

**Comment by ed96win** [comment]
Thank you so much. the issue is solved and now I'm running it on my custom ports.
