### ISSUE TITLE
Clustering with more than 2 origin

### ISSUE THREAD

**Issue by Antoine1535** [AirenSoft/OvenMediaEngine#34]
Hello,
Is it possible to add the possibility to put more than 2 origin?

Indeed we can not perform the server adjustment because we are stuck with the declaration of origin in the configuration of the Edge.

It's quite problematic if we want to build an infrastructure with thousands of users.

**Comment by JehoenHan** [comment]
One application of OvenMediaEngine supports only two Origin for failover. When a problem occurs with the Primary Origin, the Edge automatically attempts to connect to the Secondary Origin.
If you want to build the infrastructure for thousands of users, you can deploy multiple Edges. Thousands of users connect to multiple Edge (distributed via GSLB like AWS Route53) to distribute Origin traffic.
