### ISSUE TITLE
Server statistics viewer count ignores LL-DASH viewers

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#341]
**Describe the bug**
The statistics do not correctly show concurrent viewer numbers if they are watching the LL-DASH stream - it seems these users are not counted.

**To Reproduce**
1. Build current code of branch `master`
2. Build the container
3. Set up a basic setup using OBS -> RTMP -> OME origin -> OVT -> OME edge -> LL-DASH where the management API is enabled
4. connect an LL-DASH viewer using for example the DASH reference client in low-latency mode
5. wait a minute or so and then query the statistics from for example https://edge.server.address:8081/v1/stats/current/vhosts/default
6. See the current concurrent viewer number show `0`.

**Expected behavior**
LL-DASH viewers should show up in the statistics numbers

**Logs**
Nothing unusual found in the logs and statistics with the same config plus HLS provider shows HLS viewers just fine. Playback also works good in Chromium based web browsers. 

**Additional context**
I tried to find and fix the problem myself, but it looks like counting the viewers is implemented in code and thus should work. There are a few null checks without any logging which could cause the problem to be hidden, but I do not know how to run OME with a debugger connected to follow the code execution. Would be nice if some documentation / best practices could be added to the `CONTRIBUTING.md`.
https://github.com/AirenSoft/OvenMediaEngine/blob/a46aa95f1691ce2443e0c02efdaf7edef8e3f843/src/projects/publishers/segment/segment_publisher.cpp#L438

**Comment by getroot** [comment]
@basisbit 
I resolved the problem that the number of concurrent users of LLDASH was incorrectly calculated and committed to the Master branch. Could you please check if your problem is resolved?

**Comment by basisbit** [comment]
I'd like to wait for the Connection-Keep-Alive to be supported for HLS, and then build + deploy + test both features. I saw that Keep-Alive already got implemented within the last day or so, but only is applied for LLDASH yet. Thank you for this amazing progress!

**Comment by getroot** [comment]
@basisbit 
We decided to develop HTTP keepalive and apply it to HLS, MPEG-DASH, LL-DASH. But when we redesigned the structure for this, we found that it required a lot of structural changes. Therefore, it takes a period of several months. (Because we are developing OME while working on various commercial projects), please refer to your plans.

**Comment by basisbit** [comment]
thanks for the feedback. I'll test the viewer count early next week.

**Comment by basisbit** [comment]
Sorry, I can't properly test this with a decent amount of viewers because LL-DASH is still too unstable for international streaming.
However, the main issue that LL-DASH viewers were not counted at all seems to be resolved now.
