### ISSUE TITLE
The server CPU is loaded more than necessary

### ISSUE THREAD

**Issue by IlMatveev** [AirenSoft/OvenMediaEngine#344]
Hi!
The server CPU is loaded more than necessary, but bypass transcoding is true.

Server config:
CPUs: 6
Memory: 8 GB
Swap: 1 GB

Why this might be happening?

**Comment by IlMatveev** [comment]
It feels like transcoding is still happening.

**Comment by getroot** [comment]
Please upload your Server.xml

**Comment by IlMatveev** [comment]
@getroot
**OvenMediaEngine.log**
[https://pastebin.com/kQ5pjupC](url)
**Server.xml**
[https://pastebin.com/Fb1CJDG8](url)

**Comment by getroot** [comment]
Take a look at your settings. Your server is decoding AAC and encoding with OPUS.
The reason this is the default setting is that most OME users put streams in RTMP and play them in WebRTC. And RTMP only supports AAC as audio and WebRTC only supports OPUS. Audio transcoding can also be bypassed if you put the input stream into WebRTC. Please refer to the manual for details.

```
<OutputProfile>
<Name>bypass_stream</Name>
<OutputStreamName>${OriginStreamName}</OutputStreamName>
<Encodes>
	<Video>
		<Bypass>true</Bypass>
	</Video>
	<Audio>
		<Codec>opus</Codec>
		<Bitrate>128000</Bitrate>
		<Samplerate>48000</Samplerate>
		<Channel>2</Channel>
	</Audio>
</Encodes>
```

**Comment by IlMatveev** [comment]
@getroot

If you bypass audio transcoding, then the processor is loaded even more.

``` 
<OutputProfile>
<Name>bypass_stream</Name>
<OutputStreamName>${OriginStreamName}</OutputStreamName>
<Encodes>
	<Video>
		<Bypass>true</Bypass>
	</Video>
	<Audio>
		<Bypass>true</Bypass>
	</Audio>
</Encodes>
</OutputProfile>
```

**Comment by IlMatveev** [comment]
The essence of the question is that when you bypass the transcoding of video or sound the load on the processor increases. Although it should be the other way around.

**Comment by getroot** [comment]
@IlMatveev 

Hmm, I've never encountered such a problem while using OME. Is there any additional information I need to know in order to reproduce?

Looking at your Server.xml and log, I found something weird. Only RTMP and WebRTC were enabled in Server.xml, but I found that DASH, HLS, LLDASH are all enabled. You seem to be running OME in Docker. Is it correct to replace /opt/ovenmediaengine/origin_conf/Server.xml inside docker?

**Comment by bchah** [comment]
@IlMatveev I agree with @getroot, it looks from your log file like you are using the default config. 

Please check that either: you have connected the directory on your Docker host which contains your modified Server.xml to your docker container (e.g. -v /path/to/myconfig:/opt/ovenmediaengine/bin/origin_conf) OR if you placed/edited the Server.xml in the container directly, check that it is at the correct path of /opt/ovenmediaengine/bin/origin_conf/Server.xml

Note that a containerized instance of OME stores the log in a different default location than if you compile it yourself on Linux.

**Comment by basisbit** [comment]
Also, what hardware / vServer from which provider are you using? Does the docker container get hardware accelerated AES encryption passed through? Are you using a VPS using shared CPUs? What traffic per second network upload does the server have while it is having those 150% of CPU usage? What does `htop` show?

**Comment by IlMatveev** [comment]
The problem was indeed docker related. Thank you very much for your answers.

**Comment by getroot** [comment]
@IlMatveev 
Would you like to share the exact cause and solution of the problem for all of us?
Also I'd like to know the precautions when using OME in Docker.
