### ISSUE TITLE
Inaccurate value in 'totalBytesOut'

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#345]
**Describe the bug**
I suspect the OvenMediaEngine API is not returning the proper value for 'totalBytesOut'.

**To Reproduce**

Start providing a stream to OME and call the API at
/v1/stats/current/vhosts/{vhost_name}/apps/{app_name}/streams/{stream}

The 'totalBytesOut' value of the response should be very low, or 0.

Then open the stream as a viewer, and call the API again on intervals.

You will see that the 'totalBytesOut' is increasing at a rate far faster than the input of the stream, even though it is not being transcoded.

Checking the 'totalBytesOut' value in MB against the _iftop_ command measure of output in MB also reveals a suspicious discrepancy:

![Discrepancy](https://user-images.githubusercontent.com/33604674/115761452-57d25980-a370-11eb-85b6-5ea795ef2593.png)

Adding more streams causes the behaviour to worsen, where the discrepancy between what is reported by OME and the system continue widen even faster. I hope there is a clue in all of this information!

**Expected behavior**
The 'totalBytesOut' should be accurate. Sorry if I am missing something but it seems way too high.

**Logs**
[engine-8.log](https://github.com/AirenSoft/OvenMediaEngine/files/6360321/engine-8.log)

**Server (please complete the following information):**
 - OS: Ubuntu 18.04 running in Docker Image
 - OvenMediaEngine Version: 0.11.2
 - Branch: Dev (Built from Source 2021-04-03)

**Player (please complete the following information):**
Not player-related

**Comment by getroot** [comment]
I'll check this out. Thank you for rereporting.

**Comment by getroot** [comment]
I haven't been able to reproduce this in the end. However, if the session is connected and dropped repeatedly, it may be included in bytesOut even if it is not actually playing. I fixed that problem. (In the first place, this was coded that way for performance reasons, but I modified it to calculate it more accurately.)

Could you please check if this solves your problem? (Committed to the latest master)

**Comment by bchah** [comment]
Sorry I forgot to close this - since some recent commits, the calculation is now perfectly accurate 👍
