### ISSUE TITLE
Prerequisites script has started failing

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#346]
**Describe the bug**
Sorry about this but it looks like there is a new issue with the Prerequisites script, around a missing libva module. I tried manually installing libva but the public repo does not seem to deliver the version you need.

**To Reproduce**

On Ubuntu 18.04, run the prerequisites.sh script from the latest commits. It will fail with an output like: 

```
--   No package 'libva' found
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:593 (_pkg_check_modules_internal)
  cmrtlib/linux/CMakeLists.txt:67 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/tmp/build/CMakeFiles/CMakeOutput.log".
(intel_media_driver) installation has failed.
```

If you roll back a few commits to before the changes with the Intel drivers, the script passes no problem. But I am scared to make a build from this, in case some prerequisites have changed.

**Logs**
Please find two examples from the same image, one running and able to make a release as normal and the other failing. I hope this gives good clues :)
[Pass prerequisites.log](https://github.com/AirenSoft/OvenMediaEngine/files/6372699/Pass.prerequisites.log)
[fail prerequisites.log](https://github.com/AirenSoft/OvenMediaEngine/files/6372700/fail.prerequisites.log)

**Server (please complete the following information):**
 - OS: Docker Ubuntu 18.04 / Also tested on "real" Ubuntu 20.04 with same result
 - OvenMediaEngine Version: Latest 
 - Branch: dev

**Coffee**
Thank you guys for the hard work, here is a cup of coffee for you!
![coffee](https://user-images.githubusercontent.com/33604674/116004734-10e39e80-a5d2-11eb-8e49-62763ebbec5a.jpg)

**Comment by dimiden** [comment]
@bchah 
Thank you for reporting the issue, and we will begin to investigate this issue.

I'll enjoy the coffee, too. :)

**Comment by kwonkeukhan** [comment]
@bchah 

Thank you for reporting. It was a problem that occurred libva library was not referenced when building intel media sdk. I modified the script and committed it.
Please check when you have time.

I should stop drinking and have coffee. However, I love alcohol~ 😍

**Comment by bchah** [comment]
Thank you guys, I am running it now and the prerequisites script passed no problem, now making release 👍
