### ISSUE TITLE
Incompatible RTMP stream - Could not parse H264 Nal unit header

### ISSUE THREAD

**Issue by hastarin** [AirenSoft/OvenMediaEngine#348]
I'm trying to setup OME via Docker and was going great with a test source from OBS but as soon as I tried sending it a stream from our old Digital Rapids hardware encoder I have hit errors I can't get around.

**Server**
OS Docker on Gentoo
OvenMediaEngine v0.11.2

**Logs**
Relevant logs attached.
[logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6382944/logs.txt)

**Additional context**
I've attached a dump of a few seconds of the stream from rtmpdump in the hope it may help.

[dump.zip](https://github.com/AirenSoft/OvenMediaEngine/files/6382925/dump.zip)

**Comment by getroot** [comment]
To solve this problem, I think I need to receive and analyze the data sent by the Digital Rapids hardware encoder directly to my OME. It is difficult to analyze the cause with flv dump.

And could you test it with airensoft/ovenmediaengine:dev image? 

If that doesn't work, can you temporarily issue us permission to access your server, or send it to our OME server with your encoder?

**Comment by hastarin** [comment]
@getroot thanks for the prompt reply I was not expecting that.  I'm not used to developers being in a similar time-zone to me. 

Unfortunately the dev image has the same issue.

I can't provide access to the server but I will check with my manager if we can arrange for a test stream to be pushed to your OME server.

**Comment by kwonkeukhan** [comment]
@hastarin 

We installed OME on the public network for debugging.
Please set the Digital Rapids encoder to automatically reconnect.
The RTMP address will be emailed to you.

**Comment by hastarin** [comment]
@kwonkeukhan Thanks I have emailed you my details in a reply to @getroot with subject: "Re: DigitRapids Stream incompatibility"

**Comment by kwonkeukhan** [comment]
@hastarin 

I figured out the cause of the parsing error, and patched it

- AVCC Bitstream : NALU length + NALU

- Digital Rapids : NALU Length + Start Code + NALU

In general, rtmp+h264 payload does not include Start Code[4byte], but Rapids encoder does.
So, I did an exception handling.

please check with master version.

Thank you.

**Comment by hastarin** [comment]
@kwonkeukhan That is great thank you! I can confirm I have things up and running using the dev Docker container.

At least with LL-DASH and will work on WebRTC now (I need to get OME configured for WSS)
