### ISSUE TITLE
Recorded Video Rotation

### ISSUE THREAD

**Issue by forChin** [AirenSoft/OvenMediaEngine#351]
It gonna be very helpful if Recording has some configuration to add rotating video (like logrotate, but with video). Video file may be handled daily, weekly, monthly, or when it grows too large.

I know that logic can be done by starting and stopping recording video via REST API, but it would be very convenient if the project supported this functionality.

**Comment by kwonkeukhan** [comment]
@forChin 

Split recording is possible in Interval or Schedule method.

Please refer to the linked API documentation.

https://airensoft.gitbook.io/ovenmediaengine/v/master/rest-api/v1/virtualhost/application/recording/@drafts

Thank you.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
