### ISSUE TITLE
TLS/OpenSSL doesn't seem to support ECC SSL P-256 certs

### ISSUE THREAD

**Issue by hastarin** [AirenSoft/OvenMediaEngine#352]
**Describe the bug**
When using an ECC (see https://www.digicert.com/faq/ecc.htm) certificate clients are unable to establish a secure connection.

**To Reproduce**
1. Configure Server.xml for TLS using an ECC certificate
2. Setup a stream and try to connect to it via TLS
3. See error

**Logs**
[logs_ssl_error.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6402572/logs_ssl_error.txt)

**Server (please complete the following information):**
 - OS: Docker (on Gentoo Linux)
 - OvenMediaEngine Version: v0.11.3
 - Branch: dev

**Workaround**
- Obtain an RSA certificate via LetsEncrypt and use that.

**Comment by basisbit** [comment]
Could you please try if changing the line `HTTP_FAST_NOT_VERY_SECURE);` in `src/projects/modules/http_server/https_server.cpp` to `HTTP_INTERMEDIATE_COMPATIBILITY);` and then recompiling and deploying OvenMediaEngine solves the problem for you? I think there it is planned to make this configurable in the future, as this is somewhat setup dependent.

**Comment by basisbit** [comment]
For why RSA-AES128-CBC-SHA was chosen, please see https://github.com/AirenSoft/OvenMediaEngine/pull/313 - in our use case here, this got us almost double the throughput and helped significantly reduce our streaming costs when using OME.

I'd suggest using RSA-AES128-CBC-SHA if that is okay for your use case, until HTTP 1.1 Keep-Alive support is fully implemented, then there will be significantly less amounts of TLS negotiations and then ECDHE-RSA(or ECDSA)-AES128-GCM-SHA256 should be favored.

**Comment by hastarin** [comment]
@basisbit  Thanks I'll take a look on Monday. I've just been using your Docker container so I'll have to explore building things myself, hopefully the VS Code C++ Remote Container does the job.

Thanks for the clarification, your note about throughput is quite interesting!

In our case we've got NGINX in front of OME and using that for LL-DASH, DASH and HLS only as fallback. Direct connection to OME is only made for WSS and it's our preferred connection method for obvious reasons.

Just to be sure I understand correctly the impact on WebRTC would be minimal as just the initial handshake would involve the overhead?

**Comment by basisbit** [comment]
I don't know how the WebRTC signaling is implemented (can't use it yet in my use case), but if it is WSS, it should only use one connection per client and keep that open, so the performance difference should be close to none.

I'd suggest you to do performance tests using jmeter or some WebRTC service load tester or another performance testing thing (or just have many users watch a video) to get to know what load your service will be able to handle. Better to figure that out yourself than playing the guessing game and having users find out the issues.

**Comment by dimiden** [comment]
@hastarin 
For WebRTC, the first time you connect, the connection is still there, so the cost for TLS negation is relatively low. 
Therefore, you can change the encryption strength according to @basisbit's guide. (I'll have to make this set up later.)

We've used [JMeter](https://jmeter.apache.org) for performance test, but the default setting of JMeter is to use Keep-alive, we need to modify it to return HTTP/1.0 instead of HTTP/1.1 to test the current version of OME.
Since this is a temporary solution, it can cause other side-effects, so please let me know if you think it's worth a try and if you need a guide on where to modify it.

**Comment by basisbit** [comment]
For how to turn off http keep-alive in JMeter, see https://stackoverflow.com/questions/24547512/jmeter-turn-off-keep-alive-option-for-all-http-sampler-from-one-place

**Comment by dimiden** [comment]
@basisbit 
The setting worked well with regular HTTP requests, but did not work with the [HLS Plugin](https://github.com/Blazemeter/HLSPlugin) used to test HLS.
It's been about a year since I last tested it, so I don't know if it's been patched since then.

**Comment by hastarin** [comment]
Apologies I will follow up on this at some point but haven't had time as yet and now have a more urgent issue to address first where the server is crashing when a new stream starts, which I'll raise a separate bug for once I determine how to get the data that will be needed to diagnose that.

**Comment by hastarin** [comment]
@basisbit I have tried the suggested change and receive the same error:
```
[2021-05-06 01:47:43.768] E [SPRtcSignalling:15] OpenSSL | tls.cpp:393  | An error occurred while accept SSL connection: [OpenSSL] error:1417A0C1:SSL routines:tls_post_process_client_hello:no shared cipher (0x1417a0c1) (337092801)
[2021-05-06 01:47:43.768] E [SPRtcSignalling:15] OpenSSL | tls_data.cpp:197  | An error occurred while accept TLS connection
```

**Comment by basisbit** [comment]
@hastarin can you please provide a command / instructions, on how to create a certificate so that this problem occurs? I'd like to try to reproduce it and then hopefully fix it.

**Comment by hastarin** [comment]
@basisbit We've been using a Letsencrypt certificate to work around this.

I'm afraid I don't know a command to produce a comparable certificate. The details for the certificate we were trying to use is here:
https://www.ssllabs.com/ssltest/analyze.html?d=www.championdata.com&hideResults=on

I'll try to follow up on this next week if time permits.
