### ISSUE TITLE
Safari WebRTC playback issues

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#356]
**Describe the bug**
Since the commits on April 21st (iHD Drivers, FFMPEG Change, MPEG-4 Audio), there are new issues in Safari with WebRTC playback. Already the experience in Safari is poor because with WebRTC and OME, the audio and video are badly out of sync.

Now the new problem is, if the encoder does not use exactly compatible settings then video does not display in the player, even if it is receiving the data no problem. In particular the issue is with the OBS 'zerolatency' preset, and encoders where you do not have control over the profile / keyframe interval.

This was not an issue in earlier versions of OME, where you could send almost any encoding and it would play back.

**To Reproduce**
With a recent build of OME from April 21st or later, try to play back WebRTC in Safari on macOS with less optimized encoding settings, specifically using the 'zerolatency' x264 preset. Also you can try some services like Zoom which allow you to push RTMP - in my testing the Zoom RTMP push no longer plays back in Safari at all (and there are no options).

Now if you go back to OME 0.11.2 or a master build from April 20 or earlier, these problems do not exist. I would really appreciate if somebody else can test and confirm what I'm seeing here.

**Expected behavior**
I think it is worth investigating to make sure the experience across all browsers is good, especially since so many mobile devices run Safari.

**Logs**
There are a mix of playbacks in this log, with different settings. Ignore the many lines of wrong SRT URL please! 😅
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6427846/ovenmediaengine.log)

I also am including a screen recording showing the player in the strange state, where the debug seems to think everything is okay:

https://user-images.githubusercontent.com/33604674/117159005-ea6df200-ad8d-11eb-9b3e-244e4f4210c2.mp4

**Server (please complete the following information):**
 - OS: Ubuntu in Docker
 - OvenMediaEngine Version: latest

**Player (please complete the following information):**
 - Device: Mac / iOS
 - OS: 11.3.1 / 14.5.x
 - Browser Safari
 - Version 14.1

**Additional context**
Of course Chrome always starts playback perfectly, no matter what. But it is not an option to tell users they must use Chrome only, since it cuts off many Mac and iOS users. I reported the general Safari playback issues to the OvenPlayer project 3 months ago but they are not as active as this project, so hopefully this will help to get this improved.

**Comment by getroot** [comment]
Thanks for the detailed report. I'll try to reproduce this issue first and then find out the cause.

**Comment by getroot** [comment]
I still can't reproduce the problem. Please refer to the video I just took. Maybe running OBS on a Mac will be different, so I'll try this later. (Mac is not in my place right now.) However, if the Keyframe interval is set to 0, OBS may set the Keyframe interval too long (120 seconds or more) depending on the CPU or various conditions. Player may be waiting for the keyframe because it can play from the keyframe.

https://user-images.githubusercontent.com/17779085/117256109-38195600-ae85-11eb-8cea-a19e1f9f3249.MOV

**Comment by getroot** [comment]
If you cannot control the keyframe interval or other options of any encoder, it is a good idea to use OME's transcoder to control the output.

**Comment by VTFLAB** [comment]
Hello.
The OVE I'm running now seems to be having the same problem.
Build Master(commit e858496cc3e934f62e3985ae0123bd10ba979a63)
However, I don't own a Mac, so I can't reproduce the problem.
Users have told me that it reproduces on MacOS (since Big Sur?). It didn't happen with Safari on IOS.

**Comment by VTFLAB** [comment]
The following is a list of versions that have been confirmed to have the problem

- macOS big sur:11.3.1
- safari:14.1
The problem seemed to occur in an environment equivalent to the one already reported.
Again, we are unable to confirm the problem on IOS.（IOS 14.4.2）

**Comment by getroot** [comment]
I have reproduced the problem on MAC. I have reproduced it, so it will be resolved soon. Thank you all!

**Comment by bchah** [comment]
Thank you @getroot ! I'm glad I am not crazy and imagining things 😝

Ready to test whenever you bring the fix. Thank you again and good luck 😎

**Comment by getroot** [comment]
Found that Safari couldn't handle multiple SPS/PPS and added prevention code. It should work for now.

But still I don't know why it is only affected by OBS' zerolatency tune.

**Comment by bchah** [comment]
Thank you @getroot, you are an excellent bug solver! Building now and will follow up after testing 👍

**Comment by bchah** [comment]
Works excellent! You are the champion, @getroot 

![tenor](https://user-images.githubusercontent.com/33604674/117297230-f7e5b380-ae43-11eb-9433-91f764211dc4.gif)
