### ISSUE TITLE
Crash (SIGSEGV) on start of new stream 

### ISSUE THREAD

**Issue by hastarin** [AirenSoft/OvenMediaEngine#357]
**Describe the bug**
When starting a new stream from a Digital Rapids encoder (see #348 for possibly related information) the server crashes but the streams all work on the restart.

Streams sent from OBS do NOT cause the crash.

**Logs**
[crashinfo.zip](https://github.com/AirenSoft/OvenMediaEngine/files/6432267/crashinfo.zip)
Contains debug level logs and a `crash_20210506.dump` file

**Server (please complete the following information):**
 - OS: Docker
 - OvenMediaEngine Version: v0.11.3
 - Branch: dev

**Additional context**
- I created a custom docker image in order to gather the crash dump based on information found in other tickets. 
- Streams are being relayed from a Digital Rapids encoder (see #348 ) via nginx using configuration similar to the following:
```     
   application ome {
            live on;
            record off;
            meta copy;
            wait_key on;
            push rtmp://ome-server:1935/app;
        }
```

**Comment by getroot** [comment]
Please let me know what I can do to reproduce this problem.

**Comment by hastarin** [comment]
@getroot I'm not sure there is an easy way to do so without access to the encoder.  😞 

NOTE: I have ruled out the change related to #352 being related so removed it from the description.

I am open to suggestions on to how to diagnose further? 
Perhaps I can capture the stream somehow (ffmpeg) and play it back?

I could push a test stream to your server again, but as the crash only happens when a stream starts and I'd have to manually do that it doesn't seem practical.

**Comment by getroot** [comment]
@hastarin 
Is it not reproduced with FFMPEG or OBS, only with DigitalRapid encoder?
What is the probability of reproduction? Does it always happen when DigitalRapid starts a stream? Or does it happen intermittently?
Can you build OME on linux in debug mode and provide OME binaries with crash log? This allows us to spot problems without reproducing.

**Comment by getroot** [comment]
The best way to do this is if you use DigitalRapid to send the stream as before. 
If the crash occurs intermittently, please set the encoder to infinite retry. And we just have to put the server up and down.

**Comment by hastarin** [comment]
@getroot I haven't tried with FFMPEG but OBS does not cause the crash, only with Digital Rapids encoder.

I have just tested and I can't even start the Digital Rapids encoder sending direct to OME it only works via nginx.

It is 100% reproducible. Starting any new stream causes the crash.

I have built a custom docker container by commenting out the line to strip symbols:
> #        strip ./bin/RELEASE/OvenMediaEngine && \

I included the crash dump and logs in the zip attached.  If you can point me to any details on what else I might need to do I'm more than happy to do so.

**Comment by hastarin** [comment]
> Can you build OME on linux in debug mode and provide OME binaries with crash log? This allows us to spot problems without reproducing.

If what I've done so far is not sufficient can you provide more guidance on how to do this?  I'm afraid I am a C# developer so I'm in foreign territory here.

**Comment by hastarin** [comment]
NOTE: I have updated the original comment with debug logs enabled in case that's what you needed.

**Comment by getroot** [comment]
In the crash log you uploaded, all symbols have been deleted as shown below. Could it be that the cached docker image was used?

```
***** Crash dump *****
OvenMediaEngine v0.11.3 received signal 11 (SIGSEGV)
- Time: 2021-05-06T06:22:49+0000, pid: 1, tid: 79
- Stack trace
#0   /lib/x86_64-linux-gnu/libpthread.so.0 0x7f650ebef980 ? + 0x12980
#1   /opt/ovenmediaengine/bin/OvenMediaEngine 0x55defec3c280 ? + 0x23c280
#2   /opt/ovenmediaengine/bin/OvenMediaEngine 0x55defec3ece9 ? + 0x23ece9
#3   /opt/ovenmediaengine/bin/OvenMediaEngine 0x55defec34a82 ? + 0x234a82
#4   /usr/lib/x86_64-linux-gnu/libstdc++.so.6 0x7f650c6976df ? + 0xbd6df
#5   /lib/x86_64-linux-gnu/libpthread.so.0 0x7f650ebe46db ? + 0x76db
#6   /lib/x86_64-linux-gnu/libc.so.6     0x7f650bd5471f clone + 0x3f
- Module maps
55defea00000-55defede7000 r-xp 00000000 ca:11 34384841                   /opt/ovenmediaengine/bin/OvenMediaEngine
55defefe6000-55deff001000 r--p 003e6000 ca:11 34384841                   /opt/ovenmediaengine/bin/OvenMediaEngine
55deff001000-55deff002000 rw-p 00401000 ca:11 34384841                   /opt/ovenmediaengine/bin/OvenMediaEngine
55deff002000-55deff006000 rw-p 00000000 00:00 0 
55deffd69000-55defffe0000 rw-p 00000000 00:00 0                          [heap]
7f6478000000-7f64780fd000 rw-p 00000000 00:00 0 
7f64780fd000-7f647c000000 ---p 00000000 00:00 0 
7f647c000000-7f647c021000 rw-p 00000000 00:00 0 
7f647c021000-7f6480000000 ---p 00000000 00:00 0 
7f6480000000-7f6480021000 rw-p 00000000 00:00 0 
7f6480021000-7f6484000000 ---p 00000000 00:00 0 
7f6488000000-7f6488021000 rw-p 00000000 00:00 0 
7f6488021000-7f648c000000 ---p 00000000 00:00 0 
7f648c000000-7f648c021000 rw-p 00000000 00:00 0 
```

**Comment by hastarin** [comment]
I don't think so I've rebuilt using --no-cache and tore down the container, forced a pull of the newly built image etc.

I have just managed to get NGINX to record a stream which when played back reproduces the crash.
[vision02-1620283177.zip](https://github.com/AirenSoft/OvenMediaEngine/files/6432344/vision02-1620283177.zip)

`ffmpeg -re -i vision02-1620283177.flv -acodec copy -vcodec copy -f flv rtmp://ome-server:1935/ome2/hastarin`

**Comment by getroot** [comment]
@hastarin 
vision02-1620283177.flv seems to be very helpful. That's a good way. I'll reproduce the problem with this.

**Comment by getroot** [comment]
f6658993f4fe6c0ac31fd25dee2fb8aaa264f013

We have found and fixed this issue. Please check if your problem is solved.

**Comment by hastarin** [comment]
@getroot I tried using a recent dev Docker image and it is indeed fixed. Thank you again for your prompt response!

**Comment by bchah** [comment]
I am seeing this issue with all streams, since this latest commit 5651c10

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6435828/ovenmediaengine.log)
