### ISSUE TITLE
Mobile Player

### ISSUE THREAD

**Issue by rtcnerd** [AirenSoft/OvenMediaEngine#36]
Is there an ultra low latency webrtc player sdk available for android and ios that works with oven media engine?

**Comment by dimiden** [comment]
We recommend OvenPlayer for WebRTC playback.

Right now, it only offers web-based players, so if you want to use it in a native app, you can use it in the form of WebView.

**Comment by rtcnerd** [comment]
Any plans on when the native app will be available?

**Comment by dimiden** [comment]
If you only want to play WebRTC, it is best to use the native code provided by https://webrtc.org/

- Android: https://webrtc.org/native-code/android/
- iOS: https://webrtc.org/native-code/ios/

You can build the WebRTC source code by referring to the guide shown above and link the and  write your own WebSocket client that can communicate with the OME Signalling Server.

If you want not only WebRTC but also HLS/DASH playback and fallback features, please wait for [OvenPlayer](https://github.com/AirenSoft/OvenPlayer) to be released in the first half of next year.

**Comment by rtcnerd** [comment]
Thank you. Do you have any sample code to wrap the OvenPlayer in webview?

**Comment by dimiden** [comment]
I don't have WebView-based samples, but I don't think it will be difficult to make with reference to the following steps.

First, you should download the required files by referring to the [OvenPlayer page](https://github.com/AirenSoft/OvenPlayer/tree/0.9/dist/production/ovenplayer), copy them as resource in iOS/Android project. Then, loads the files in WebView and it will work.

**Comment by Allan-Nava** [comment]
Is there sdk android and iOS?

**Comment by dimiden** [comment]
@Allan-Nava 
We do not have the Android/iOS SDK and we recommend using the code provided by https://webrtc.org as mentioned above.

**Comment by Allan-Nava** [comment]
> @Allan-Nava
> We do not have the Android/iOS SDK and we recommend using the code provided by https://webrtc.org as mentioned above.

Ah neither in beta?

**Comment by dimiden** [comment]
@Allan-Nava 
The source code provided by webrtc.org is the code used by [Google Chrome](https://www.google.com/chrome), so I don't think it's a beta version.

**Comment by Allan-Nava** [comment]
> @Allan-Nava
> The source code provided by webrtc.org is the code used by [Google Chrome](https://www.google.com/chrome), so I don't think it's a beta version.

Okay @dimiden , but in the future do u implement any ovenplayer sdk for iOS or Android?

**Comment by dimiden** [comment]
@Allan-Nava 
We plan to implement the iOS/Android native player after developing more important features.

**Comment by Allan-Nava** [comment]
> @Allan-Nava
> We plan to implement the iOS/Android native player after developing more important features.

Okay let me know. 
Thanks for the support

**Comment by dstuecken** [comment]
Is there any update on the iOS player implementation?

**Comment by Martad2010** [comment]
I write to ask how far about the Andriod /iOS 
SDK's for  OvenPlayer . 

Would appreciate a feedback.

Thanks 



> > @Allan-Nava
> > We plan to implement the iOS/Android native player after developing more important features.

**Comment by sridhard** [comment]
Is there any sdk for ios and android for playing LLHLS?

**Comment by getroot** [comment]
You can exchange SDP with WebSocket according to OME's signaling protocol and implement it with WebRTC Native Library.

The Signaling Protocol is as follows.
https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#signalling-protocol

This can be easily implemented by looking at our OvenPlayer or performance testing tool.

https://github.com/AirenSoft/OvenPlayer

https://github.com/AirenSoft/OvenMediaEngine/blob/4fb4af2a646f053886908d4cd754756d9fb29bf9/misc/oven_rtc_tester/OvenRtcTester.go

In fact, there are many people who have implemented a Native WebRTC player that directly plays OME's stream using our signaling protocol and WebRTC Native, and it's not that difficult.
