### ISSUE TITLE
OVT broken

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#363]
**Describe the bug**
Some commit within the last few days broke OVT transport between origin and edge server. Older instances of OME edge can still connect to the current OME origin and pull the stream, only current OME edge can not connect to the OVT server.

**To Reproduce**
1. Set up OBS -> RTMP -> OME origin -> OVT -> OME edge -> HLS
2. start the stream in OBS
3. wait a bit
4. request the playlist file from the OME edge and look at the OME edge log

**Expected behavior**
Edge server should get the stream from origin server without a problem.

**Logs**
Both servers are logging with warning level.
```
docker-compose up
Recreating ovenmediaengine_edge_1 ... done
Attaching to ovenmediaengine_edge_1
edge_1  | [2021-05-07 16:10:18.292] I [OvenMediaEngine:1] Config | config_manager.cpp:195  | Trying to set logfile in directory... (/var/log/ovenmediaengine)
edge_1  | [2021-05-07 16:10:49.583] E [SegWorker:16] OvtStream | ovt_stream.cpp:209  | Cannot connect to origin server (Connection timed out (1500 ms elapsed, SO_ERROR: 0)) : origin.domain.tld:9000
edge_1  | [2021-05-07 16:10:49.584] E [SegWorker:16] Provider | provider.cpp:152  | OVTProvider Application could not create [test] stream.
edge_1  | [2021-05-07 16:10:49.584] E [SegWorker:16] Orchestrator | orchestrator.cpp:591  | Could not pull stream [#default#sampleapp/test] from provider: PullProvider
edge_1  | [2021-05-07 16:10:49.584] E [SegWorker:16] HLS | hls_stream_server.cpp:58   | Could not find a HLS Publisher playlist for [#default#sampleapp/test], playlist.m3u8 : 404
```

OME Origin server shows nothing except for the normal container startup log.

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: current master
 - Branch: master

**Additional context**

**Comment by getroot** [comment]
Thanks for the detailed bug reporting.
I have tried to reproduce this problem but it does not reproduce on the latest master. Perhaps it was due to recently resolved socket related issues. Could you please check again with the latest master?

**Comment by getroot** [comment]
I reproduced a similar problem by looping through the connection and disconnection. I am further analyzing this issue.

**Comment by basisbit** [comment]
>  Perhaps it was due to recently resolved socket related issues. Could you please check again with the latest master?

Seems to work again with current master Thanks for the quick fix!
