### ISSUE TITLE
About StreamKey

### ISSUE THREAD

**Issue by VTFLAB** [AirenSoft/OvenMediaEngine#365]
I'd like to know if it's possible.
Is it possible to separate the stream key of the distributor from the stream key of the viewer (video player)?
Or is there a similar method?
Currently, I'm using the same stream key for the player as well, so anyone who understands how it works can hijack the broadcast.
If there are any alternatives, I'd love to hear them!

**Comment by bchah** [comment]
If you use SignedPolicy, the signed key is different for access to publishers versus providers.

Have a look at:

https://airensoft.gitbook.io/ovenmediaengine/signedpolicy <https://airensoft.gitbook.io/ovenmediaengine/signedpolicy>

**Comment by VTFLAB** [comment]
Thanks for the suggestion!
I knew this feature existed, but I hadn't implemented it in the backend yet.
If you want to use this policy, from the documentation it looks like you need to put a time limit on the stream.
I basically don't want to put a time limit on the stream, so if you know if this is possible (is it 0?), I'd appreciate it.
I'll try it out when I have time.

Let me check again to make sure I'm not mistaken.
In this case, the viewer can use the video player
ws://192.168.100.1:3333/app/stream
and can connect from
The Streamer can use
rtmp://192.168.100.1:1935/app/stream?policy=ey...
Is this correct?

**Comment by bchah** [comment]
I think you need to go all-in with SignedPolicy, i.e. if it’s active you need it everywhere.

To solve the time limit issue, use this encoded policy:

`eyJ1cmxfZXhwaXJlIjo3MjQ1NTk0MTMwMDAwfQ`

It expires sometime in 2199 and I apply it as the default policy unless another condition is met.

**Comment by VTFLAB** [comment]
Thanks for the specific example!
I'll make sure to specify 100 years later when generating the policy on the backend side too!
I've tried everything and I understand, I'll give it a shot, thanks a lot!
