### ISSUE TITLE
Error on Chrome

### ISSUE THREAD

**Issue by rtcnerd** [AirenSoft/OvenMediaEngine#37]
When i use http://demo.ovenplayer.com/

I get the following error on Chrome.

<img width="544" alt="Screenshot 2019-08-05 at 13 10 01" src="https://user-images.githubusercontent.com/53658893/62460566-a5fd8e80-b782-11e9-96b0-017dff08a863.png">

**Comment by underdoggg** [comment]
@rtcnerd 
Thank you very much for your interest in this product.
I checked the screenshot you sent.
It was my mistake. So I improved it.
Please check the last version.
