### ISSUE TITLE
Thumbnail CORS Policy error

### ISSUE THREAD

**Issue by caveman444** [AirenSoft/OvenMediaEngine#371]
Hello,
I am getting CORS policy error when i am trying to access the thumbnail from a webpage.

I am using ffmpeg to encode the stream and send to ovenmedia engine using mpegts and distribute to clients using webrtc.This is working fine and i have setup the thumbnail also in Server.xml and image is also coming in the http url.But when i try to access the url from another webpage i got cors policy error.
This is my Server.xml,
 
`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	
	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		<Providers>
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
			</RTMP>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000-4003,4004,4005/udp}</Port>
			</MPEGTS>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
			</OVT>
			<HLS>
				<Port>${env:OME_HLS_STREAM_PORT:8080}</Port>
				
				
			</HLS>
			<DASH>
				<Port>${env:OME_DASH_STREAM_PORT:8080}</Port>
				
				
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					
					
				</Signalling>
				<IceCandidates>
					
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
			<Thumbnail>
				<Port>20080</Port>
				
				<TLSPort>20081</TLSPort>
				
				
			</Thumbnail>
		</Publishers>
	</Bind>

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								<Image>
									<Codec>png</Codec>
									<Framerate>1</Framerate>
									<Width>640</Width>
									<Height>480</Height>
								</Image>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<RTMP />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000,4001-4004</Port>
								</Stream>
								<Stream>
									<Name>stream_4005</Name>
									<Port>4005</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLDASH>
						<Thumbnail>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>	
						</Thumbnail>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>`
and this is my request on client side,

`$.ajax({

        url: "http://localhost:20080/app/stream_4000/thumb.png",

        type: "GET",

               success: function (result) {

            console.log(result);

          },
        error: function (xhr, ajaxOptions, thrownError) {

        console.log(xhr.status);

        }

    });`

**Comment by getroot** [comment]
Is there a log on the client side that says CORS policy errors occur? Please capture it and upload it.

**Comment by caveman444** [comment]
Hello thank for the response here is the picture,

![Screenshot from 2021-05-20 16-08-25](https://user-images.githubusercontent.com/64684068/118965264-20ae9280-b986-11eb-9f26-383ef086fe00.png)

**Comment by getroot** [comment]
I have reproduced this problem. This will be resolved soon. Thanks for reporting.

**Comment by caveman444** [comment]
yes that works.thanks.
