### ISSUE TITLE
Compilation error: string_view is not a member of std

### ISSUE THREAD

**Issue by lizardpeter** [AirenSoft/OvenMediaEngine#375]
**Describe the bug**

When trying to compile on Ubuntu's latest version, I am getting an error.

<img width="753" alt="Screen Shot 2021-05-21 at 7 51 26 PM" src="https://user-images.githubusercontent.com/53446060/119207897-f0422380-ba6d-11eb-8f1d-c8510304ee2a.png">

My compiler versions seem to be up to date. I am really not sure how to proceed.

**Comment by getroot** [comment]
Your compiler version is low.  It's just that it doesn't support c++17.  Capture your gcc version.  Did you run prerequisite.sh beforehand as in the manual?  https://airensoft.gitbook.io/ovenmediaengine/getting-started

**Comment by lizardpeter** [comment]
My gcc version is 10.2.0. Yes, I ran the prerequisite.sh script.

**Comment by getroot** [comment]
This is an issue I've never seen before.
I need the information below. Please capture as below. And I need your exact Ubuntu version to reproduce this problem.

![image](https://user-images.githubusercontent.com/17779085/119246918-75d5e880-bbc0-11eb-8781-8f6244711059.png)

**Comment by lizardpeter** [comment]
My Ubuntu version is 20.10.

<img width="881" alt="Screen Shot 2021-05-23 at 2 43 10 PM" src="https://user-images.githubusercontent.com/53446060/119272698-35349a00-bbd5-11eb-9a36-76bb75f025c9.png">

**Comment by dimiden** [comment]
@lizardpeter 
Thank you for the detailed information.
In the previous version of ```g++```, ```string``` header file was included elsewhere, so it was built without inclusion in ```ovlibrary/string.h```, but it seems to have changed from ```g++``` 10.2.0. It was solved by inserting ```#include <string>``` directly from ```ovlibrary/string.h```. 2cbd869e14237db9c4b62f1bae86deea444c4ecd

**Comment by lizardpeter** [comment]
Thank you!
