### ISSUE TITLE
LL-DASH publisher ignores CrossDomains configuration

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#377]
**Describe the bug**
The CrossDomains configuration for a LL-DASH publisher / HTTP server seems to be ignored. Clients don't get the headers which tell the browser which website may have requested this data. This is a bit of a problem when trying to limit usage of the stream to your own website.

**To Reproduce**
1. Set up a minimal OBS -> RTMP -> origin -> OVT -> edge -> LL-DASH config
2. specify a couple of CrossDomains for LL-DASH Publisher
3. Request the stream using the reference-player and take a look at the segment response headers.

**Expected behavior**
CORS headers should be set to only allow the content to be played in the requested domain. See https://airensoft.gitbook.io/ovenmediaengine/streaming/hls-mpeg-dash#crossdomain

**Logs**
Nothing unusual.

**Server (please complete the following information):**
 - OS: Linux
 - OvenMediaEngine Version: current master
 - Branch: master

**Player (please complete the following information):**
 - Device: current Chromium
 - OS: Windows 10

**Comment by ANDREY0214** [comment]
same problem
any news?

**Comment by basisbit** [comment]
LL-DASH is still unusable because of other bugs.

**Comment by getroot** [comment]
We're sorry, but with the release of LLHLS, we have decided to no longer update LLDASH. Because LLHLS has better performance and compatibility, we decided it was a better decision for everyone to focus more of our energy on it.

Instead, we will continue to focus more on LLHLS and WebRTC. Thanks for your contribution.

**Comment by getroot** [comment]
@basisbit Yes, of course!  LLHLS works well with crossdomain config. And it handles the PREFLIGHT Option as well.
