### ISSUE TITLE
SignedPolicy Bug when using WebRTC Signaling Port 443 

### ISSUE THREAD

**Issue by Morpheus235** [AirenSoft/OvenMediaEngine#378]
**Describe the bug**
So I am currently testing the SignedPolicy Feauture in Ome and while using Port 443 as TLS Port in WebRTC Provider I am getting wrong Signature Errors. This does not occur while using any other Port and when using the Signature being stated in the logs the Stream does work with Port 443.  The generated Signatures do work on other Ports so I dont think this is an Issue with my Signed URLs being wrong. 

**To Reproduce**
1. Set TLSPort of WebRTC Provider in Server.xml as 443
2. Generate Signature for the Stream URL 
3. https://demo.ovenplayer.com/demo_input.html and setup with generated Signature URL

**Expected behavior**
The Websocket / WebRTC Provider should accept the Signature on any Port 

**Logs**
Only Signature Errors being thrown.

**Server:**
 - OS: Ubuntu 18.04
 - OvenMediaEngine Version: [v0.12.0]
 - Branch: [release]

**Player:**
 - Device: [Asus Zephyrus G15]
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [90.0.4430.212]

**Comment by Morpheus235** [comment]
So just to add this Information. I found out that omitting the Port from any Url using wss or https while using Port 443 does result in a valid URL. This contradicts the Information in the Documentation (see: [Signature](https://airensoft.gitbook.io/ovenmediaengine/signedpolicy#signature)), a clarification or an update to the Documentation would be appreciated.

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/119430920-93d05400-bd4c-11eb-88ae-2d1a9cab56d5.png)

The information that the port number MUST NOT be omitted has already been emphasized in the manual. If this is not clear, could you please publicize the clear phrase in the manual repository below?

**Comment by Morpheus235** [comment]
Yes it states it must not be omitted but it only works while omitting the Port.
So signing:
`wss://192.168.0.100:443/app/stream?policy=eyJ1cmxfZXhwaXJlIjoxMzk5NzIxNTgxfQ `
would not work while signing:
`wss://192.168.0.100/app/stream?policy=eyJ1cmxfZXhwaXJlIjoxMzk5NzIxNTgxfQ `
does work perfectly.

**Comment by getroot** [comment]
If that is true then this is a bug. I will investigate this and correct it soon. Thank you.

**Comment by getroot** [comment]
I solved this problem. (6ccff16140062e1f04856504fcc24cd04e4ca2e3) Could you please check if your problem is solved?
Thank you for your contribution.

**Comment by Morpheus235** [comment]
Sorry for the late reply. Tested the fix and it seems to work perfectly fine now.
