### ISSUE TITLE
va/va_dricommon.h: No such file or directory

### ISSUE THREAD

**Issue by HackPB** [AirenSoft/OvenMediaEngine#379]
**Describe the bug**
In the new version (0.12.0) when runing the script prerequisites.sh it fails with error: .../media_libva_putsurface_linux.h:31:10: fatal error: va/va_dricommon.h: No such file or directory. 

**To Reproduce**
1. In a clean Ubuntu install just run: OvenMediaEngine-0.12.0/misc/prerequisites.sh, as described in the "Getting Started" guide.

**Expected behavior**
The prerequisites.sh should complete correctly without the user have to install other dependencies. 

**Server (please complete the following information):**
 - OS: Ubunto 20.04
 - OvenMediaEngine Version: 0.12.0

**Possible solution**
To make it work, in my case, I have only added `sudo apt install -y libva-dev` after line 313 of prerequisites.sh;

**Comment by kwonkeukhan** [comment]
@HackPB 

It was a problem that occurred in an environment where x11 was not installed.
I have updated the prerequisites.sh script to the latest version, so please try again.
It will be applied to the 0.12.0 release version soon.

Thanks

**Comment by HackPB** [comment]
@kwonkeukhan 
The updated prerequisites.sh is working correctly now. 
Your approach to install everithing related to x11 is better than only the libva-dev.
In my opinion this issue is closed (if you agree please close it).
Thanks

**Comment by kwonkeukhan** [comment]
@HackPB 

Thank you for checking quickly

I wanted to make it simple with libva-dev.
When using Intel Media Driver, versions of Libva and GmmLib are important. (https://github.com/intel/media-driver/releases)
So, I installed all x11 related libraries.

I'll close the issue.

Thanks
