### ISSUE TITLE
0.12.0 WebRTC Issue

### ISSUE THREAD

**Issue by ryan77627** [AirenSoft/OvenMediaEngine#385]
**Describe the bug**
As other have mentioned, I have been having stability issues with WebRTC streaming with version 0.12.0. Specifically, some clients will connect fine and other will get stuck loading

**To Reproduce**
I have an RTMP input stream getting pushed to HLS and WebRTC over UDP. HLS works as intended. WebRTC is intermittent. A specific is I have a port range specified (30000-30015/udp)

**Expected behavior**
A connection is established every time

**Server (please complete the following information):**
 - OS: OpenSUSE Leap
 - OvenMediaEngine Version: 0.12.0
 - Branch: Docker latest

**Player (please complete the following information):**
 - Device: Laptop AMD64
 - OS: OpenSUSE Tumbleweed
 - Browser: Brave (Chromium 90.0.4430.212)

**Example Screenshots**
0.11.3 Candidates:
![example1](https://user-images.githubusercontent.com/16727971/119758642-dc832c80-be74-11eb-8efc-6d80552cab2e.png)
0.12.0 Candidates:
![example2](https://user-images.githubusercontent.com/16727971/119758670-e573fe00-be74-11eb-9d6c-a89ede4cdb47.png)

**Additional context**
One thing I have noticed that may be of interest is that the WebRTC offer messages from 0.11.3 will list all candidates I specify for ICE Servers (all 16 ports), however 0.12.0 will only ever list one candidate, and the port is always random.

**Comment by getroot** [comment]
Yes, since 0.11.13 sends all candidates, it only communicates with the first candidate, so there was no effect of distributed processing. From 0.12.0, random candidates are sent and distributed to ports. Because OME allocates threads per port internally, this allows a larger number of players to be accommodated.

Would you like to review your system's firewall settings? In 0.11.3, it would have worked fine even if only port 30000 was open in the firewall. From 0.12.0, all ports 30000 ~ 30005 should be open.

**Comment by ryan77627** [comment]
Oh gotcha, glad to know it was expected behavior. My firewall (firewalld) is configured to allow 1935 (RTMP), 8090 (My HLS provider), 30000-30015/udp (ICE Candidates), and 37649 (Signalling). This is reflected on my router as well, so the ports *should* all be working. I'll keep working on this to see if I notice anything. I've checked and I have applied it to the correct zone/interface.

I have this running in docker, so I've also specified my public IP address instead of * for the ICE Candidate IP to make sure 172.?.?.? isn't specified, as I don't know whether that would be an issue or not.

**Comment by getroot** [comment]
I will create the same environment as yours and check OME again. Thank you for your confirmation.

**Comment by ryan77627** [comment]
I think I found my issue. The issue wasn't in my firewall settings, I overlooked a setting in my docker configuration from some other troubleshooting. Sorry for that!

**Comment by getroot** [comment]
This is a possible issue for some of us, so would you like to share the exact cause of the problem and how to fix it?

**Comment by ryan77627** [comment]
I was doing some other troubleshooting and forgot to re-forward the ports in my docker-compose.yml

**Comment by getroot** [comment]
Thanks for sharing your experience!
