### ISSUE TITLE
Prevent RTMP ingest based on stream key

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#386]
Is there a way to reject an RTMP stream if the stream key is not 'recognised'?

At the moment anyone is able to stream to our OME server if they have the RTMP url, regardless of what stream key they enter.

I think the most effective way to do this might be to allow the ability to specify stream keys in Server.xml via the Rest API.

**Comment by getroot** [comment]
SignedPolicy can be the solution for that.

https://airensoft.gitbook.io/ovenmediaengine/signedpolicy

**Comment by llspalex** [comment]
@getroot Thank you for the fast reply. I looked into SignedPolicy earlier but it wasn't clear to me that if it I enable SignedPolicy in Server.xml, does it mean all incoming streams need to use a signed url?

**Comment by getroot** [comment]
Yes, if RTMP SignedPolicy is on, all incoming RTMP streams must use SignedPolicy.
You can control the stream by setting the expire_time to a very distant future (e.g. January 1, 2100), then creating several URLs with only different stream names, and distributing those URLs to your customers.

**Comment by llspalex** [comment]
Does that mean that if we used the same expiry time for all streams, the stream URLs would all be the same except for the stream name? And therefore allow someone to send a stream just by changing the stream name within a SignedPolicy URL?

**Comment by getroot** [comment]
No, the signatures are all different. You can issue multiple urls created with signedurl, and only those who receive them can send RTMP.

**Comment by llspalex** [comment]
Great, thank you.

**Comment by llspalex** [comment]
I can contribute this info to the SignedPolicy documentation page if you like?

**Comment by Thunder80** [comment]
> No, the signatures are all different. You can issue multiple urls created with signedurl, and only those who receive them can send RTMP.

Suppose we have the default Application, "app" and we add the
```xml
<SignedPolicy>
        <PolicyQueryKeyName>policy</PolicyQueryKeyName>
        <SignatureQueryKeyName>signature</SignatureQueryKeyName>
        <SecretKey>aKq#1kj</SecretKey>

        <Enables>
            <Providers>rtmp</Providers>
            <Publishers>webrtc,hls,dash,lldash</Publishers>
        </Enables>
    </SignedPolicy>
```

SignedPolicy to the "default" VirtualHost. As mentioned in the docs the Signature is created with HMAC-SHA1 so if we keep all the parameters the same(i.e. url_expire) then the same URL will be generated every time? How are different URLs generated?

**Comment by getroot** [comment]
If the stream name is different, the base url is different, so the signature is different.

**Comment by Thunder80** [comment]
O thanks that clears it.
