### ISSUE TITLE
Server performance when running multiple applications vs one application

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#387]
Is there a performance benefit to running one application vs multiple applications in Server.xml? 

Our application settings would be the same for all users, so in those terms there's no real need to have multiple applications. 

But for ease of separation / monitoring / admin, there's a benefit to having a separate application for each user.

**Comment by basisbit** [comment]
> Is there a performance benefit to running one application vs multiple applications

Yes there is. However, it greatly depends on how you use the software and what streaming protocol you use and what topology you use. For example if you have hundreds of users all request the same HLS/DASH/LL-DASH stream, then that stream only has to be processed once and then packaged into the chunks/slices only once. However if every client request their video stream from a different application, then you'll need a lot more CPU and RAM for that. I hope this is not what you actually meant to ask...

> Our application settings would be the same for all users, so in those terms there's no real need to have multiple applications.

What do you mean by "user"? Do you want an application for each client who requests the stream or for each streamer who send their stream to OME for distribution?

**Comment by llspalex** [comment]
Our use case relies on RTMP and SRT ingest with ultra low latency playback, so we would rely on WebRTC for playback and not HLS/DASH/LL-DASH. 

> What do you mean by "user"? Do you want an application for each client who requests the stream or for each streamer who send their stream to OME for distribution?

By user I mean streamer. A streamer can create multiple 'rooms' in our app and send one or more streams to a room. Viewers then connect to the room to watch the stream. I was thinking of having a) an OME application for each streamer, or b) even further separation by having an OME application for each 'room' - to assist in monitoring, admin etc in the backend.

The application settings would be the same for all applications and configured only for SRT + RTMP ingest and WebRTC playback (with AAC -> OPUS transcode as necessary). I wondered if, taking into our account our use case, there would be a performance hit or anything else to consider if we were to create dozens and dozens of applications on OME Origin vs just one application for all streamers.

**Comment by getroot** [comment]
There are several threads assigned to the application. Since several applications each operate as an independent thread, there is an effect of distributing processing. But as you can see, an excessive number of threads can degrade performance due to context switching. We have experience creating 3500 streams in 1 application on 20Core/40Thread CPU. There is also a thread inside the application that allocates to streams, so if you don't need other OutputProfiles, I recommend using 1 applicaiton. It is recommended to use the application when the settings of OutputProfiles, Providers, and Publishers need to be different.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
