### ISSUE TITLE
Docker error Server.xml

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#388]
I am having a problem running OME in Docker using a docker-compose.yml file. 

My docker-compose file looks like this:
services:
   ovenmediaengine

  ovenmediaengine:
    image: "airensoft/ovenmediaengine:latest"
    ports:
      - "1935:1935"
      - "3333:3333"
      - "3478:3478"
      - "8080:8080"
      - "9000:9000"
      - "9999:9999"
      - "4000-4005:4000-4005/udp"
      - "10006-10010:10006-10010/udp"
    volumes:
      - "./origin:/opt/ovenmediaengine/bin/origin_conf"
      - "./edge:/opt/ovenmediaengine/bin/edge_conf"
    restart: always

**This returns an error in the docker container's console:**

`ovenmediaengine_1 | [2021-05-27 16:10:09.231] I [OvenMediaEngine:1] Config | config_manager.cpp:195 | Trying to set logfile in directory... (/var/log/ovenmediaengine)`

`ovenmediaengine_1 | [2021-05-27 16:10:09.232] I [OvenMediaEngine:1] Config | config_manager.cpp:93 | Trying to load configurations... (origin_conf/Server.xml)`

`ovenmediaengine_1 | [2021-05-27 16:10:09.232] I [OvenMediaEngine:1] Config.DataSource | data_source.cpp:42 | Trying to load data source from ./origin_conf/Server.xml`

`ovenmediaengine_1 | [2021-05-27 16:10:09.235] E [OvenMediaEngine:1] OvenMediaEngine | main.cpp:301 | An error occurred while load config: [Config] Unknown item found: Server.StunServer in ./origin_conf/Server.xml`

If I comment out the `volumes` lines of the docker-compose file, it works. 

`Server.xml` file looks fine and can be seen [here](https://gist.github.com/llspalex/078a5e8e18b7a5633d3d2c3c5829753d). I even tried with the default `Server.xml` files and still faced the same issue.

**Comment by basisbit** [comment]
What version of OME are you running in your docker setup? Try it grabbing the newest one fixes the problem.

**Comment by llspalex** [comment]
I was using `airensoft/ovenmediaengine:latest` in the docker-compose file but I just changed it to `airensoft/ovenmediaengine:0.12.0` and that has solved the issue. Thank you for the suggestion.

**Comment by basisbit** [comment]
`docker pull airensoft/ovenmediaengine:latest` should have worked too. However, in production I'd suggest always using version tags, and only updating those after having tested the new version on a testing machine.
