### ISSUE TITLE
Deny or close unwanted Streams

### ISSUE THREAD

**Issue by genofire** [AirenSoft/OvenMediaEngine#391]
**Is your feature request related to a problem? Please describe.**
If somebody find out the ingress/origin OME, he could missuse the infrastructure

**Describe the solution you'd like**
Stop / Close the stream by ManagementAPI (and we could write an own guardy watchdog)

**Describe alternatives you've considered**
- use a way of auth (on rtmp basic auth)
- lets check by an API, if stream is legal (nginx-rtmp module has also a redirect function - to hide the live source stream name from edge streaming)

**Additional context**
Hope this issue is not duplicated

**Comment by basisbit** [comment]
What endpoint are you referring to? If you refer to pushing streams to the server, there already exists this which provides all you need to be able to write your own stream key generator frontend: https://airensoft.gitbook.io/ovenmediaengine/signedpolicy

**Comment by getroot** [comment]
SignedPolicy may solve your problem. However, some authenticated broadcaster passed the SignedPolicy, but the operator may want to close this stream. We plan to develop it so that operators can DELETE streams with APIs. The API is still under development!

**Comment by genofire** [comment]
You are totally right, this should solves everything.
Sorry for opening this issue

**Comment by llspalex** [comment]
> However, some authenticated broadcaster passed the SignedPolicy, but the operator may want to close this stream. We plan to develop it so that operators can DELETE streams with APIs. The API is still under development!

We already use SignedPolicy but would be _very_ interested in being able to delete streams using the API as described 😃

**Comment by llspalex** [comment]
#401 I think deals with the same issue.
