### ISSUE TITLE
RTMP Publisher for WebRTC & SRT Provider

### ISSUE THREAD

**Issue by regstuff** [AirenSoft/OvenMediaEngine#393]
For reliability's sake, it is becoming common to want to use SRT to send a stream from OBS to a cloud server, and then convert SRT into RTMP and push RTMP out to YouTube or Facebook etc. Similarly, to ensure lowest latency, it is also a common requirement to stream from PC to server with WebRTC, and then want to stream to YouTube and Facebook with RTMP.

Currently, there are no reliable or straightforward ways to achieve this. At the minimum, we need to use Ffmpeg separately and run our own process. This could still work for SRT, but not for WebRTC.  If Oven were able to create a RTMP publisher for SRT & WebRTC providers, it would solve this problem.

Please consider adding such a feature. 

Thanks for the rest of the work though. Oven looks really wonderful and feature-full.

**Comment by regstuff** [comment]
Wow. I saw this and thought it would only push RTMP Providers. But you mean this would work for any kind of provider?

**Comment by getroot** [comment]
Any "publisher" in OME can handle whatever stream comes in through any "provider". As with the manual, the push publishing (re-stream) function requires an API command to work.
