### ISSUE TITLE
SignedPolicy: stream_after

### ISSUE THREAD

**Issue by genofire** [AirenSoft/OvenMediaEngine#394]
**Is your feature request related to a problem? Please describe.**
It would be really nice, to have the control - that nobody starts to stream, before it is allowed.

**Describe the solution you'd like**
I really whould like to have a `stream_after` like in Certificates with there:
- Not Before
- Not After

**Comment by getroot** [comment]
I think the functions you want are the same as `url_activate` and `url_expire`, is there anything else?

https://airensoft.gitbook.io/ovenmediaengine/signedpolicy#policy

**Comment by genofire** [comment]
Is `url_activate` and `url_expire` not for Viewers of the Publishers?
I need something equal for the Providers / Live Sources.

**Comment by getroot** [comment]
SignedPolicy works the same for both providers and publishers.

**Comment by genofire** [comment]
Or do you just mean the naming, that it should be `stream_activate` ??

**Comment by getroot** [comment]
url_activate means that the url can be used after that time. What is the difference between the stream_activate you said and this?
url_expire and url_activate are different policies as described in the manual. However, url_activate and stream_activate cannot be different.

**Comment by genofire** [comment]
Great, i believe to understand the handling of Publishers and Providers, now.

If you like to give a policy just to the Providers for viewers, you have just parameters like url_*, but not an `stream_expire` parameter?
A Policy for a Publisher has always the possibility to be a also a Viewer on the providers.

Or i am wrong?

**Comment by getroot** [comment]
I don't understand what you mean by "Providers for viewers". I think you are probably misunderstanding SignedPolicy. Please read the manual carefully.

see the manual url_expire and stream_expire are different kinds of policies and can be used by both Provider and Publisher.

https://airensoft.gitbook.io/ovenmediaengine/signedpolicy

I really don't know what you want.

You seem to be misunderstanding Provider and Publisher. The encoder sends the stream to OME's Provider, and the player receives and plays the stream through OME's Publisher. So there is no "Providers for viewers".
