### ISSUE TITLE
Documentation: minimal example for WebRTC client

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#395]
**Is your feature request related to a problem? Please describe.**
I am currently looking at the WebRTC APIs for integrating WebRTC stream displaying into a canvas/WebGL based app. Does there exist documentation for how to use the OvenMediaEngine WebRTC connections for signalling and connecting a web browser with WebRTC support to OvenMediaEngine edge?

**Describe the solution you'd like**
Does there maybe already exist a minimal light-weight example or documentation of how to implement the client side for a plain empty HTML5 page somewhere with maybe only a start and a play button? I put the emphasis there on light-weight especially regarding CPU overhead and 

**Describe alternatives you've considered**
I have looked at OvenPlayer, but that seems rather heavyweight and is not easily readable enough to quickly allow for integrating OME WebRTC playback in a custom website or 3rd party app.

**Comment by getroot** [comment]
Hope the url below is helpful to you.
Please let me know if you need more information.

https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#signalling-protocol

**Comment by basisbit** [comment]
that little amount of documentation is bare usable to get started and misses a bunch. Guess I'll have to read the server code and just try stuff

**Comment by getroot** [comment]
It seems that you have addressed this topic recently in your project. Do you have any specific examples that you can advise us on?

**Comment by zapf2k** [comment]
Why not use ovenplaver?

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>mystream</title>
</head>
<body>
    <div id="player_id"></div>
    <script src="https://cdn.jsdelivr.net/npm/ovenplayer/dist/ovenplayer.js"></script>
    <script>
            const player = OvenPlayer.create('player_id', {
            sources: [
                {
                    label: 'mystream',
                    type: 'webrtc',
                    file: 'wss://servername:3334/app/live'
                }
            ]
        });
    </script>
</body>
</html>`

Simple enough?

**Comment by basisbit** [comment]
@ zapf2k Thank you for that not helpful reply. You obviously have not read my issue start message at all.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
