### ISSUE TITLE
Thumbnail not working with TLSPort

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#396]
Hello,

**Describe the bug**
Thumbnail not working with TLSPort

**To Reproduce**
1. Set Server.xml as follows https://airensoft.gitbook.io/ovenmediaengine/thumbnail-experiment
2. Uncomment TLSPort and set it to HLS/Dash port
3. Try to download thumbnail (https://test-hls2.?.pl/app/test/thumb.jpg) and see error:
Request URL: https://test-hls2.?.pl/app/test/thumb.jpg
Request Method: GET
Status Code: 404 Not Found

**Logs**
Log when TLSPort = HLS/Dash TLSPort:
[2021-05-31 15:38:42.436] W [SPSegPub:51] HttpServer | http_server.cpp:223  | No module could be found to handle this connection request : [https://test-hls2.?.pl/app/test/thumb.jpg]

Log when TLSPort is diffrent than HLS/Dash TLS Port:
[2021-05-31 15:31:10.680] E [SPThumbnailPubl:79] OpenSSL | tls.cpp:134  | Invalid TLS certificate
[2021-05-31 15:31:10.680] E [SPThumbnailPubl:79] OpenSSL | tls_data.cpp:78   | Could not initialize TLS: [OpenSSL] error:00000000:lib(0):func(0):reason(0) (0x0) (0)

**Server (please complete the following information):**
 - OS: Debian 10
 - OvenMediaEngine v0.12.0 is started on [83fab4eba67a] (Linux x86_64 - 4.19.0-16-amd64, #1 SMP Debian 4.19.181-1 (2021-03-19))

Best regards from Poland!

**Comment by getroot** [comment]
What value did you set TLSPort to? It looks like you left out the port in your URL.
https://test-hls2.?.pl[:port]/app/test/thumb.jpg

Also, OME failed to load your certificate, so check your certificate.

When writing an issue, please upload your entire Server.xml and ovenemdiaengine.log.

**Comment by fcqpl** [comment]
Hello,
Connecting to:
http://test-hls2.?.pl:8080/app/test/thumb.jpg - works
https://test-hls2.?.pl:443/app/test/thumb.jpg - Error 404
https://test-hls2.?.pl:20081/app/test/thumb.jpg - Error in log: "Invalid TLS certificate"

TLS Certificate is OK - HTTPS streaming (DASH/HLS) and wss:// WebRTC working without problems.

```
<DASH>
	<Port>8080</Port>
	<TLSPort>443</TLSPort>
</DASH>
<Thumbnail>
	<Port>8080</Port>
	<TLSPort>443</TLSPort>
</Thumbnail>
```

[Server_clear.xml.md](https://github.com/AirenSoft/OvenMediaEngine/files/6575496/Server_clear.xml.md)

**Comment by Morpheus235** [comment]
Can confirm also ran into this issue a few days ago. Using Port 443 aka TLS with the Thumbnail provider results in the httpsserver/provider log throwing Errors about not finding a usable module for the requested URL. Other TLSPort configurations seem to work fine.

**Comment by getroot** [comment]
@kwonkeukhan is checking this issue. Thanks for the bug report.

**Comment by kwonkeukhan** [comment]
@fcqpl @Morpheus235 

You've been waiting for a long time.
I checked the TLS problem of the thumbnail publisher and corrected it.
Test it with the latest version.

**Comment by Morpheus235** [comment]
@kwonkeukhan  I have tested with the latest changes and it seem to work now as expected when using Port 443 as Port for the Thumbnail publisher.
