### ISSUE TITLE
SRT Signed Policy for Publish

### ISSUE THREAD

**Issue by Thunder80** [AirenSoft/OvenMediaEngine#397]
I am trying to use SRT publish with SignedPolicy to publish from OBS.
Steps taken to generate the Publish URL :-

1. I generated signed policy with srt://localhost:9999/app/stream
2. URL encoded the SignedPolicy
3. Final URL is like srt://localhost:9999?streamid=<PERCENT_ENCODED(SignedPolicy)>
Eg: - srt://localhost:9999?streamid=srt%3A%2F%2Flocalhost%3A9999%2Fapp%2Fstream%3Fpolicy%3DeyJ1cmxfZXhwaXJlIjoxODkzNDU2MDAwMDAwfQ%26signature%3DjzLEhn2ZoIdn1_9beSM8mrDgcCM

The OBS Publish works without the SignedPolicy so I think I am making some mistake generating the SignedPolicy.

**Comment by getroot** [comment]
You have to upload the ovenmediaengine.log file so I can more accurately analyze the cause.

Does generating signedpolicy urls with misc/signed_policy_url_generator.sh have the same problem?

For example, try this:

```
getroot@OME-Dev:~/project/OvenMediaEngine/misc$ ./signed_policy_url_generator.sh 12345 srt://localhost:9999/app/stream signature policy '{"url_expire":1604377520178}'
[URL] srt://localhost:9999/app/stream?policy=eyJ1cmxfZXhwaXJlIjoxNjA0Mzc3NTIwMTc4fQ&signature=Ry0JOBMYGkwm9i-dzzNM1IOfDP0
[Percent encoded URL] srt%3A//localhost%3A9999/app/stream%3Fpolicy%3DeyJ1cmxfZXhwaXJlIjoxNjA0Mzc3NTIwMTc4fQ%26signature%3DRy0JOBMYGkwm9i-dzzNM1IOfDP0
```
Then, put the generated [Percent encoded URL] into your streamid.

srt://localhost:9999?streamid=[generated url by script]

**Comment by Thunder80** [comment]
The signed policy is generated by the misc/signed_policy_url_generator.js

Here is the ovenmediaengine.log 
https://gist.github.com/Thunder80/6d034e134f8fd5af179655e2e4752662

**Comment by getroot** [comment]
The uploaded log file seems to be corrupted. The log file is truncated and duplicated.

**Comment by Thunder80** [comment]
Sorry just updated it I think last time I duplicated two logs.

**Comment by bchah** [comment]
This log only shows the server starting up. If you are sure you started the SRT stream then the request does not appear to be making it to the server. Check your port forwarding perhaps?

**Comment by Thunder80** [comment]
The ports are mapped correctly. Actually, I just noticed that the SRT Publish works with only the default docker run command given in the docs. I am using this docker file and Server.xml maybe I think I am missing something in the Server.xml?

https://gist.github.com/Thunder80/fe144a8a9acbb6600d4496b58bf848dc
(I have the SRT Tag in the Providers with the default 9999 port)

**Comment by getroot** [comment]
SRT works based on UDP, so it should be "9999:9999/udp".

**Comment by Thunder80** [comment]
O thanks a lot. That was it. Pretty silly on my part.
