### ISSUE TITLE
Crash reporting system

### ISSUE THREAD

**Issue by sorrowhill** [AirenSoft/OvenMediaEngine#4]
This is a high priority issue because there is no crash reporting system.

Actually, I've been using google-breakpad(https://github.com/google/breakpad) to gather information when the application is crashed. It creates a minidump file that recognizable on CentOS/Ubuntu, even Widows, and OS X. you will be able to see call stack in gdb, and even can be converted to pdb format in Windows.

Also implementing `backtrace()` will be useful in the same situation.

**Comment by JehoenHan** [comment]
It's a good idea. We will study Breakpad.

**Comment by dimiden** [comment]
We are benchmarking various solutions to use Crash reporting system in OME, and we will apply it if we find a light-weight solution.

**Comment by sfreet** [comment]
This issue has been fixed in d2090aec663daaf1abaf407a1b6ba7be6b3a4257 by [Benjamin](https://github.com/AirenSoft/OvenMediaEngine/commits?author=sfreet).
