### ISSUE TITLE
WEBRTC play is not smooth

### ISSUE THREAD

**Issue by venkat0708** [AirenSoft/OvenMediaEngine#405]
**Describe the bug**
When palying WERTC in Oven Player, Video pay is not smooth It gets struck
**To Reproduce**
1. OS : Unbuntu 18.0.4 LTS
1. OvenMediaEngine: 0.12.0
2. OBS : 26
3.  Server.xml(which is basic that one gets while installing Oven Media Engine)  :
`<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>

	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		

		<Providers>
			<RTMP>
				<Port>1935</Port>
				
			</RTMP>
			<SRT>
				<Port>9999</Port>
				
			</SRT>
			<MPEGTS>
				
				<Port>4000-4004,4005/udp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					
					
				</Signalling>

				<IceCandidates>
					
					<TcpRelay>*:3478</TcpRelay>
					<IceCandidate>*:10000-10005/udp</IceCandidate>

					
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				
			</OVT>
			<HLS>
				<Port>80</Port>
				
				
				
			</HLS>
			<DASH>
				<Port>80</Port>
				
				
				
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					
					
				</Signalling>

				<IceCandidates>
					
					<TcpRelay>*:3478</TcpRelay>
					<IceCandidate>*:10000-10005/udp</IceCandidate>

					
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			

			

			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						

						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000,4001-4004</Port>
								</Stream>
								<Stream>
									<Name>stream_4005</Name>
									<Port>4005</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>true</Rtx>
							<Ulpfec>true</Ulpfec>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							
							<UTCTiming>
								<Scheme>urn:mpeg:dash:utc:http-xsdate:2014</Scheme>
								<Value>/time?iso&amp;ms</Value>
							</UTCTiming>
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							
							<UTCTiming />
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>`

**Expected behavior**
WEBRTC play should have taken place smoothly, but video was getting struck. Where as HLS play was smooth

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.
021.06.02-04.07.19.150,WEBRTC.SS,SESSION,INFO,,,createClientSession,stream,100
2021.06.02-04.07.19.150,WEBRTC.SS,SESSION,INFO,,,Live:0,Playback:0,stream,100
2021.06.02-04.14.17.143,WEBRTC.SS,SESSION,INFO,,,createClientSession,stream,101
2021.06.02-04.14.17.144,WEBRTC.SS,SESSION,INFO,,,Live:0,Playback:0,stream,101
2021.06.02-04.16.47.5,WEBRTC.SS,SESSION,INFO,,,deleteClientSession,stream,101
2021.06.02-04.16.47.5,WEBRTC.SS,SESSION,INFO,,,Live:0,Playback:0,stream,101
2021.06.02-04.17.44.536,WEBRTC.SS,SESSION,INFO,,,deleteClientSession,stream,100
2021.06.02-04.17.44.537,WEBRTC.SS,SESSION,INFO,,,Live:0,Playback:0,stream,100
2021.06.02-04.17.44.646,WEBRTC.SS,SESSION,INFO,,,createClientSession,stream,102
2021.06.02-04.17.44.646,WEBRTC.SS,SESSION,INFO,,,Live:0,Playback:0,stream,102

**Server (please complete the following information):**
 - OS: [Ubuntu 18]
 - OvenMediaEngine Version: [v0.12.0]
 - Branch: [dev]

**Player (please complete the following information):**
 - Device: [Laptop]
 - OS: [Ubuntu 18]
 - Browser [Chrome]

**Comment by Morpheus235** [comment]
Have you looked at the getting started guide?
Setting bframes to 0 and threads to 8 is crucial and is also explained why in the guide
![OBS Config](https://user-images.githubusercontent.com/40322103/120939614-2e4f7080-c719-11eb-8393-3d96a9234e92.png)

excerpt from the [getting started](https://airensoft.gitbook.io/ovenmediaengine/getting-started) guide:

> If Hardware Encoder isn't installed on your PC, it's recommended to set x264 as follows: We highly recommend setting "bframes = 0" to reduce latency. Then set the "threads" option to 8 or less. Chrome doesn't handle more than 10 Nal Units. The best way to avoid this is to set "thread = 8".

**Comment by getroot** [comment]
Suspect UDP packet loss unless it is a problem with the codec settings mentioned by @Morpheus235. Try testing with transport=tcp.

**Comment by venkat0708** [comment]
Thanks @Morpheus235 , It worked after adding bframes and threads in OBS. but I have one more doubt what if I want to use Flash Media encoder 3.2 which is pretty old and doesn't have enough options.

Thanks @getroot TCP transport mode is very smooth than UDP, in UDP I could observe some drops

**Comment by getroot** [comment]
@venkat0708 If the encoder cannot control the b-frame or select the H264 baseline profile, the stream must be re-encoded using the OME transcoder. Not supporting b-frame is a limitation of WebRTC Player (browser).
