### ISSUE TITLE
Help me. make release error.

### ISSUE THREAD

**Issue by KIM-IN-KYUM** [AirenSoft/OvenMediaEngine#406]
####################################################
#                                                  #
#           AirenSoft Make System v0.63            #
#                                                  #
####################################################
   - Operating system        : linux    <- CentOS7
   - Core count              : 32
   - GCC version             : 7.3.1
   - Build option            : RELEASE
   - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
   - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig
   - Total Projects count    : 47
start make release.....

[ 61/384| 15%] [static] libovlibrary.a: C++ projects/base/ovlibrary/regex.cpp => intermediates/RELEASE/objs/base/ovlibrary/regex.o
projects/base/ovlibrary/regex.cpp:15:10: fatal error: pcre2.h: No such file or directory
 #include <pcre2.h>
          ^~~~~~~~~
compilation terminated.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/base/ovlibrary/regex.o] Error 1

**Comment by getroot** [comment]
Run misc/prerequisites.sh again
