### ISSUE TITLE
Tracking Statistics of Individual Streams

### ISSUE THREAD

**Issue by Thunder80** [AirenSoft/OvenMediaEngine#407]
**Is your feature request related to a problem?**
Currently, as I read from the documentation, the statistics of a stream can be tracked by the OME API but the stream statistics are only available when the stream is live. As soon as the stream stops the statistics cannot be accessed anymore. So it will be very helpful if we have something with which we can track statistics of a stream by the stream name even if the stream is stopped.

**Describe the solution you'd like**
I think a solution to this could be another API endpoint to return this info. OME can store the data in a file, in json format of each session of the stream with the stream name as the key and an array of sessions as its value. 
E.g.:-
```json
{
"stream1": [
  {
  "start_time": "Date",
  "end_time": "Date",
  "inbounds": "number",
  "outbounds": "number",
  "other_stats": "stats"
  }],
"stream2": [
  {
  "start_time": "Date",
  "end_time": "Date",
  "inbounds": "number",
  "outbounds": "number",
  "other_stats": "stats"
  }]
}
```

**Describe alternatives you've considered**
I have a crappy solution with the existing API, which is to ping the Application statistics endpoint of OME every minute or so via a cronjob and just upsert the data of the streams in a database or a file as I described above. 

Another solution that came to me is probably to use different Application for each stream but the Input/Output profiles could be same and thus as suggested by OME for these cases we should use one Application. So this is also not a good solution I guess.

I am not sure if I am missing something. Any help will be appreciated. Thanks!!!!

**Comment by getroot** [comment]
It is recommended to use specialized statistical solutions for this. Statistics require another expertise. There are many very good solutions for this in the world. For example prometheus, telegraf, influxdb, kafka, spark, elastic search, grafana, kibana, etc. It handles collection/queue/filter/process/visualization nicely.

To provide statistical functions in OvenMediaEngine, db or storage must be used, which makes the structure very complex, which increases the probability of failure. And most users who need statistics want to consolidate information from multiple OME servers. This is not solved by extending OME's API. OME provides presence data through its API. We recommend that you collect and process this information with a specialized statistical solution.

**Comment by Thunder80** [comment]
Thanks, @getroot for the suggestion. But I was wondering if OME had an endpoint like :-
`http://<OME_HOST>:<API_PORT>/v1/stats/current/vhosts/{vhost_name}/apps/{app_name}/streams`, which will return the data of the currently live streams maybe. That reduces the number queries it will take to scrape the data from OME to one query. Otherwise we need to query all the streams separately which can a lot of queries.

**Comment by getroot** [comment]
The REST API is still under development. We will continue to add various features to the API, such as bulk functionality. Thanks for the good suggestion.
