### ISSUE TITLE
Safari not loading stream, other browsers work (ICE error)

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#408]
We are ingesting RTMP and SRT streams and playing back over WebRTC. The streams load fine on Chrome and Firefox, but not on Safari. 

On Safari (macOS and iOS), gathering ICE candidates fails every time:
![Screenshot 2021-06-09 at 08 04 33](https://user-images.githubusercontent.com/67900507/121308775-55fd2f00-c8f9-11eb-8f93-ef12bc3bb2dd.png)

We are setting a STUN server both in the OME Server config and in our javascript.

Safari connects successfully to Janus WebRTC and a to WebRTC stream from a different (non-OME) server without any issues, so we think we've narrowed this down to an OME-Safari specific issue. 

Tested on macOS Catalina with Safari 13 and macOS Big Sur with Safari 14, and iOS 14 - same issue. 

Does anyone know why this might be happening and what can be done to fix it?

Server.xml [here](https://gist.github.com/llspalex/1af5188a0d9a387380894a141095934f)
ovenmediaengine.log [here](https://gist.github.com/llspalex/de988ffeec1159a32b89b3d3006cd7d7)

**Comment by getroot** [comment]
- Did you use the latest master branch?

- Have you tested on http://demo.ovenplayer.com/ome_demo.html? On my iOS it plays fine.

- The ovenmediaenigne.log you uploaded seems to be connected to the OVT port by someone (and it doesn't seem to be Edge's OVTProvider). Please upload the full log after reproducing it.

**Comment by getroot** [comment]
I just confirmed that it plays fine on Catalina Safari 14.0.2. Please describe what you expect your environment to be different from demo.ovenplayer.com.

**Comment by llspalex** [comment]
Thank you @getroot I just tested the OME hosted demo and it is working on Safari for me too. So it must be something in our implementation which is only affecting Safari. 

- We are using the OME docker image `airensoft/ovenmediaengine:latest`
- We are using Origin server for ingest and playback (not Edge for playback)
- We are using the standard html5 video player and not OvenPlayer

We will get back to you shortly with more details and a proper log as requested.

**Comment by getroot** [comment]
airensoft/ovenmediaengine:latest is not the latest image. Try airensoft/ovenmediaengine:dev.

**Comment by Thunder80** [comment]
This was an implementation fault from our side, we tried to send all the ICE candidates after the ICE gathering is 'completed' but for some reason in Safari ICE gathering is not completed thus the connection failed. In the docs, it said that we can send all the ICE candidates at once thus the above implementation was done, maybe add a "recommended" tag in the docs beside sending the ICE candidates when found will help others. Thanks for the quick replies.

**Comment by getroot** [comment]
I didn't understand which part of which document you were referring to. It would be very helpful if you could PR on the article below.

https://github.com/AirenSoft/OvenMediaEngineDocs

**Comment by Thunder80** [comment]
![image](https://user-images.githubusercontent.com/43901109/121472950-8d460b80-c9df-11eb-931b-d94f17a2ee3b.png)
I was talking about this part, from the `(SDP + Candidates)` I thought that we can send the ICE candidates after gathering all the candidates OR we can send the ICE candidates after sending the SDP answer. But now looking at the docs I think it was just me😂. I was just talking about changing the `SDP (if available)` to `SDP (if available, recommended)`.
