### ISSUE TITLE
RTMP stream in new Version

### ISSUE THREAD

**Issue by Handonghuang** [AirenSoft/OvenMediaEngine#410]
**Describe the bug**
in old version 0.10.x when we push a RTMP into the OvenMediaEngine. we can using same URL as player URL。
Since update to 0.11.x version with new RTMP push/publishing option, as I understood it same as OBS pusher to another server.
How can I get same functions using  OvenMediaEngine as RTMP publish source ?

**To Reproduce**
1. in 0.10.x version  push  a RTMP to server RTMP://xxxxx/app/stream     
2. using any player can play RMTP with same RTMP address
3. it should play same as ther push 

**Server (please complete the following information):**
 - OS: ubuntu 18.04
 - OvenMediaEngine Version: [e.g. v0.10.1]
 

**Player (please complete the following information):**
any rtmp player 
**Additional context**

**Comment by getroot** [comment]
OvenMediaEngine does not support RTMP playback.  The 0.10.x version didn't support it either.
