### ISSUE TITLE
Server crash with Hls and SignedPolicy 0.12.1

### ISSUE THREAD

**Issue by nums** [AirenSoft/OvenMediaEngine#414]
Hello

I tested the latest version 0.12.1 and the server crashes when I use the "SignedPolicy" option when I want to read the stream in HLS.
I have downgraded with version 0.12.0 and I have no problem, the configuration file is strictly identical

`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>

	
	<Bind>
		
		

		<Providers>
			<RTMP>
				<Port>1935</Port>
			</RTMP>
			<MPEGTS>
				
				<Port>4000-4004,4005/udp</Port>
			</MPEGTS>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
			</OVT>
			<HLS>
				<TLSPort>80</TLSPort>
			</HLS>
			<DASH>
				<TLSPort>80</TLSPort>
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Host>
				<Names>
					<Name>*</Name>
				</Names>
				<TLS>
					<CertPath>XXX</CertPath>
					<KeyPath>XXX</KeyPath>
					<ChainCertPath>XXXX</ChainCertPath>
				</TLS>
			</Host>
			<SignedPolicy>
				<PolicyQueryKeyName>XX</PolicyQueryKeyName>
				<SignatureQueryKeyName>XX</SignatureQueryKeyName>
				<SecretKey>XXXX</SecretKey>
				<Enables>
					<Providers>rtmp</Providers>
					<Publishers>webrtc,hls,dash,lldash</Publishers>
				</Enables>
			</SignedPolicy>

			

			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								
							</Encodes>
						</OutputProfile>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}_360p</OutputStreamName>
							<Encodes>
								<Audio>
								<Bypass>true</Bypass>
								</Audio>
								<Video>
								<Codec>h264</Codec>
								<Bitrate>224000</Bitrate>
								<Framerate>30</Framerate>
								<Width>640</Width>
								<Height>360</Height>
								</Video>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<RTMP />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000,4001-4004</Port>
								</Stream>
								<Stream>
									<Name>stream_4005</Name>
									<Port>4005</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
					</Providers>
					<Publishers>
						<SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>`

**Comment by getroot** [comment]
Thanks for reporting. This problem is solved. Please check if your problem is also resolved.

**Comment by nums** [comment]
I confirm.
Thanks
