### ISSUE TITLE
Make install failing on latest commits

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#415]
I have used the same environment for many months to do OME builds and today the build script started failing with this error:

```
core/main.mk:114: recipe for target 'install' failed
make: *** [install] Error 1
```

The environment is the base Ubuntu 18.04 Docker image. This is the .sh I use to create and ZIP a build, has worked perfect for many months:

```
apt-get update 
apt-get install sudo
git clone https://github.com/AirenSoft/OvenMediaEngine.git
OvenMediaEngine/misc/prerequisites.sh
cd OvenMediaEngine/src
apt-get update
make release
make install
mkdir -p /opt/ovenmediaengine/bin
cp bin/RELEASE/OvenMediaEngine /opt/ovenmediaengine/bin/OvenMediaEngine
zip -r /ome.zip /opt/ovenmediaengine
rm -rf /OvenMediaEngine
rm -rf /opt/ovenmediaengine
cp /ome.zip /build/ome-`date '+%s'`.zip
```

Any idea what the problem is? 😅

**Comment by dimiden** [comment]
@bchah 
It was successfully built about an hour ago on our Jenkins build server.
This is also built with Ubuntu 18.04 as the base (using OME's ```Dockerfile```) and I think there might be another problem.

Could you attach the entire build log?

**Comment by dimiden** [comment]
@bchah 
Yes, that's right. There was a problem during the execution of prerequisites script.
I found the following error in the log you sent me:
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
(nasm) installation has failed.
```
And, I checked that ```nasm``` repository is not working on another server.
```
$ sudo yum install nasm
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
http://www.nasm.us/pub/nasm/stable/linux/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:7c80:54:e::136: Network is unreachable"
Trying other mirror.
http://www.nasm.us/pub/nasm/stable/linux/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2607:7c80:54:e::136: Network is unreachable"
Trying other mirror.
...
$ curl -v 'http://www.nasm.us/pub/nasm/stable/linux/repodata/repomd.xml'
* About to connect() to www.nasm.us port 80 (#0)
*   Trying 198.137.202.136...
* No route to host
*   Trying 2607:7c80:54:e::136...
* Failed to connect to 2607:7c80:54:e::136: Network is unreachable
* Failed connect to www.nasm.us:80; Network is unreachable
* Closing connection 0
curl: (7) Failed to connect to 2607:7c80:54:e::136: Network is unreachable
$ ping www.nasm.us
PING www.nasm.us (198.137.202.136) 56(84) bytes of data.
From core1-g-5-13.fmt2.kjsl.com (64.62.206.98) icmp_seq=1 Destination Host Unreachable
^C
--- www.nasm.us ping statistics ---
4 packets transmitted, 0 received, +1 errors, 100% packet loss, time 2999ms
```

Our Jenkins server seems to have been lucky enough to build, and in an unfortunate environment, we'll have to wait until we get access to the nasm repository.

**Comment by bchah** [comment]
Thanks for clarifying. It seems like the nasm.us <http://nasm.us/> site is unreliable and maybe not maintained.

But I did find the recent repository here: https://repo.or.cz/nasm.git <https://repo.or.cz/nasm.git>

And it looks like other groups have forked and improved it e.g. yasm https://yasm.tortall.net <https://yasm.tortall.net/>

Maybe one of this could be a more reliable option to get it during the prerequisites script?

**Comment by dimiden** [comment]
@bchah 
Yes, I'll check if I can modify the script using the repository you sent me. Thank you for the information!

**Comment by nums** [comment]
nasm.us is alive but it might be better to manage the fallback url.

I managed to install OvenMedia by doing a simple `apt install nasm` and commenting out the line `install_nasm` in the `prerequisite.sh`

**Comment by kwonkeukhan** [comment]
@nums 

Thanks for the reporting.
I was replacing nasm installation with a github url.... but the old url was alive.........omg!  I wasted my time. T_T
After checking the nasm installation and working test using apt or yum repository, I will change the script.

Thanks.

**Comment by getroot** [comment]
It is recommended to avoid installing packages using apt or yum. Because OME installs all packages in /opt/ovenmediaengine, conflicts with existing packages are prevented, and the direct installation method is used so that the same version can be used in various os.
