### ISSUE TITLE
Blackmagic Web presenter HD connection issue with OME

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#419]
Hello, 

I tried using a blackmagic web presenter HD to connect to OME, and it didn't work. I found a similar issue posted a while ago from someone using an atem mini pro and the behavior is the same, checking the logs shows the same behavior of a sort of loop, where the web presenter HD connects, attempts to create a stream, disconnects and repeats it all over again.

 - OS: Ubuntu 18
 - OvenMediaEngine Version: 0.12.1

here is the link to the other post:
https://github.com/AirenSoft/OvenMediaEngine/issues/366

I'd be happy to send any reports do do further testing to help fix this!

**Comment by getroot** [comment]
Thanks for the bug report.
I would appreciate it if you could send your RTMP stream to the following URL.

rtmp://dev2.airensoft.com/app/stream

This is linked to the page below.

http://demo.ovenplayer.com/ome_demo.html

**Comment by zcolor** [comment]
Hi Jeheon,

I just tried it connecting to your server. It exhibited the same behaviour as with mine. Let me know if there’s anything I can do to help.

Best
Zé Maria Abreu Santos
e-mail: ***@***.*** ***@***.***>
tel: +49 (0) 173 876 00 33
web: zemariacolor.com <http://zemariacolor.com/>

**Comment by zcolor** [comment]
Also,

Here’s the config. xml that’s needed to set which url the web-presenter HD should connect to. That is the xml I loaded to test the connection to your server.


Zé Maria Abreu Santos
e-mail: ***@***.*** ***@***.***>
tel: +49 (0) 173 876 00 33
web: zemariacolor.com <http://zemariacolor.com/>

**Comment by getroot** [comment]
@zcolor 
Could you set your device to keep trying to reconnect? This is because we have to start/stop the server and analyze the packets. And it takes a lot of time.

**Comment by zcolor** [comment]
Sure! It’s on, trying to connect. 

I’m not feeding it any image right now so if you manage to get it to connect and it’s all black that’s why 

Best
Zé Maria Abreu Santos
***@***.***
+49 (0) 173 876 00 33
zemariacolor.com

**Comment by getroot** [comment]
@zcolor 
Thank you. I have confirmed that your encoder is trying to connect. We would be very grateful if you could keep this up as the reps are still working on other things. I will comment again when the analysis is complete.

**Comment by dimiden** [comment]
@zcolor 
The RTMP client (Blackmagic Web presenter HD) is disconnecting after sending ```Type 0``` data after the handshake is completed.
Could you check the log of the RTMP client?

**Comment by dimiden** [comment]
@zcolor
I think the client is waiting for something and a timeout occurs.
Since I don't have that device, could you dump the packet when sending it to another RTMP server with a tool such as TCP dump or Wireshark and attach it?
If you could upload the dump file, it would be very helpful to solve the problem.
(I don't think packet dumping is possible in Blackmagic Web presenter HD. So, I think you need to create a 'simple proxy server' with a tool like ```netcat``` to do this.)

**Comment by zcolor** [comment]
@dimiden 
I'd love to help, but I'm way out of my depth on this. Any chance you could give me a hand with it?

**Comment by dimiden** [comment]
@zcolor
I realize you don't have to do anything. I'm going to setup another RTMP server on dev2 and capture the RTMP packet from the server side.
If possible, could you change the RTMP port from 1935 to 41935? I think other people who are testing at port 1935 on dev2 can be disturbed.

**Comment by dimiden** [comment]
@zcolor 
Also, I would appreciate it if you could keep publishing RTMP.

**Comment by zcolor** [comment]
Sure! Thanks for the help,

I’m now publishing to: rtmp://dev2.airensoft.com:41935/app <rtmp://dev2.airensoft.com:41935/app>

Let me know if you are receiving.

Best
Zé Maria Abreu Santos
e-mail: ***@***.*** ***@***.***>
tel: +49 (0) 173 876 00 33
web: zemariacolor.com <http://zemariacolor.com/>

**Comment by Handonghuang** [comment]
hi, there 

same issue when we using network video recorder (NVR)  push RTMP to OME. 
H.264 1080P 30FPS , no audio.
Ubuntu18   /  V0.11.3  
Memory leakage

**Comment by dimiden** [comment]
@zcolor 
I found the reason why RTMP client disconnected from server with your help.
However, while fixing and testing this problem, I found another problem that was not being played smoothly, I think it needs a little more analysis.
I think it is caused by the failure to parse SPS/PPS information from H.264 frame, so could you please keep publishing for 1~2 more days?

@Handonghuang 
Yes. I think it could be the same problem. What equipment are you using for publishing?

**Comment by zcolor** [comment]
@dimiden

That's great to know, glad it heped.

I'd have to check until when I can return the device . I'll let you know.

**Comment by dimiden** [comment]
@zcolor
Did you change the encoding option? The problem that happened last night (here is GMT+9) is not happening now, and it seems to be playing well now. Please check if it can be played well in your environment.

http://demo.ovenplayer.com/#sources=%5B%7B%22id%22%3A0%2C%22label%22%3Anull%2C%22file%22%3A%22ws%3A%2F%2Fdev2.airensoft.com%3A3332%2Fapp%2Fstream_o%22%2C%22type%22%3A%22webrtc%22%7D%5D&lowLatency=false&liveDelay=false

![image](https://user-images.githubusercontent.com/4264558/123037758-2afef900-d42a-11eb-967e-cf270a363128.png)

**Comment by zcolor** [comment]
@dimiden no I just turned it off by mistake. I turned it on and started streaming again, and it just connected. I thought that had been you, since you said you had discovered the issue.

I tried connecting to my server, and it didn't work.

The only thing that's different is that I specified the port (41935) on the URL in the xml file of the device. I opened the player link you sent, although it can connect, it wasn't playing back smoothly, it jumped every couple seconds to a new frame. That's probably the issue you mentioned earlier, right?

**Comment by dimiden** [comment]
@zcolor
Could you upgrade your OME to the latest version (master branch) and test if RTMP client connects well?

In addition, the issue I mentioned above was that the streaming did not start at all, but the problem you are experiencing now seems to be the "stuttering" issue.
These two issues are different, and the issue that did not start was not reproduced, and the "stuttering" issue was not properly tested because only the black screen played. Could you please publish a moving video?

If we had the equipment, we would try various things, but we can't. Please understand that we are bothering you, and thank you for contributing to the development of OME.

**Comment by zcolor** [comment]
It's no bother at all, I'm more than happy to help! I love what you are doing and want to do my part! I'm using the computer I have connected to it at the moment, so I can't publish a moving image, but I'll do it once I'm done with work and will let you know 👍

**Comment by zcolor** [comment]
@dimiden I'll test it on my server on the weekend, until then, I'm publishing a time code countdown (25fps base) in a loop to your server if you want to have a look at the playback smoothness.

**Comment by getroot** [comment]
@zcolor 
Changing to CBR and turning off b-frame will help reduce latency.

We've seen that the audio packets in the stream you're sending come in very late compared to the video. And perhaps the network between your encoder and dev2.airensoft.com isn't fast enough, so I've seen the input stream keep getting slow (Your encoder was probably sending the stream at a few mbps, but our server was receiving the stream at 400kbps. How many mbps is your encoder sending the stream at?) This makes OME very busy, and it It's causing problems.

We are discussing whether there is a way for OME to mitigate the problem even in this situation.

**Comment by zcolor** [comment]
@dimiden I just asked BMD support if it's possible to even set those settings on the device and if so, how. Also asked, if it's possible to disable the audio output, so that doesn't add to the latency.

I have a 35mbit/s upload link, should be more than enough.

I set the bit rate to 6.5mbit/s, but apparently that's merely the limit at which the device will publish at when needed. It has a small UI display which shows the current bit rate and that value is always changing depending on the content. A simple time code in all black background  will stream at 0.5mbit/s and a moving image from a video will be anywhere between  1.5mbit/s if not moving all the way up to whichever limit I set.

**Comment by getroot** [comment]
@zcolor 
You have a 35mbps upload link, but it probably isn't fast enough because dev2.airensoft.com is installed on a slow IDC in Seoul and the distance is very far.

We are thinking about a way to handle streams that input a lot differently from A/V.

Thank you for your continued contribution.

**Comment by zcolor** [comment]
Alright, 

my pleasure, happy to help! 

Let me know if you want me to publish to your server again.

**Comment by getroot** [comment]
I looked through the manual to get information about the blackmagic web presenter. Linking with OBS is an example of how to stream to Youtube, and if you use this method, it also will work well with OME. I couldn't find anything about encoding settings in the manual.

https://documents.blackmagicdesign.com/UserManuals/BlackmagicWebPresenterManual.pdf

**Comment by zcolor** [comment]
I never heard back from blackmagic support regarding the playback issues when streaming with the Web Presenter, so I'm returning it. Thanks for solving the issue anyway, maybe it will be better supported in the future...
