### ISSUE TITLE
Audio/Video Not synced - when recording (and sometimes in live)

### ISSUE THREAD

**Issue by HackPB** [AirenSoft/OvenMediaEngine#428]
**Describe the bug**
The recorded video has audio/video unsynced, when we use `<Encodes>` without `<Bypass>` in configs. If we do only `<Bypass>` the recorded video is fine. The encode feauture is importante so we can save smaller files. 
Sometimes even in live streaming  the stream is unsynced, but here I cound't find a away to reproduce it allways. This happens more frequently in OME v0.11.3 than in OME v0.12.0.  

**To Reproduce**
1. In Server.xml -> Application -> OutputProfile if we have: 
`<OutputProfile>
          <Name>webrtc_360</Name>
          <OutputStreamName>${OriginStreamName}_360</OutputStreamName>
          <Encodes>
                  <Audio>
                          <Bypass>true</Bypass>
                  </Audio>
                  <Audio>
                          <Codec>opus</Codec>
                          <Bitrate>128000</Bitrate>
                          <Samplerate>48000</Samplerate>
                          <Channel>2</Channel>
                  </Audio>
                  <Video>
                          <Codec>h264</Codec>
                          <Bitrate>1000000</Bitrate>
                          <Framerate>30</Framerate>
                          <Width>640</Width>
                          <Height>360</Height>
                  </Video>
          </Encodes>
  </OutputProfile>`
**The recorded file of this stream is unusable.**
Although if we have:
`<OutputProfile>
          <Name>webrtc_360</Name>
          <OutputStreamName>${OriginStreamName}_360</OutputStreamName>
          <Encodes>
                  <Audio>
                          <Bypass>true</Bypass>
                  </Audio>
                  <Video>
                          <Bypass>true</Bypass>
                  </Video>
          </Encodes>
  </OutputProfile>`
**The file is saved correctly.**
2. Tried with OBS(v27.0.0) and StreamLabs OBS(v1.1.2) (with sofware and NVENC), and with the above configs in Server.xml. Didn't tried with other codec, only with h264.

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.
After making the request to start record when the `<Encodes>` part is present without `<Bypass>` this is generated in log:

> [2021-06-29 11:45:23.712] W [FilePubWorker:1600] FILE | file_session.cpp:158  | mp4 format does not support the codec(8)  
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | Output #0, mp4, to '/srv/academia/pt/soccer/filipe/tmp_cB48ebS0jEMwl15y9fqWTU76mNxQOVYu':  
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  |   Metadata:  
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  |     encoder         :   
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | Lavf58.45.100  
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  |   
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  |     Stream #0:0  
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | : Video: h264, 1 reference frame (avc1 / 0x31637661), none, 640x360 (0x0) [SAR 1:1 DAR 16:9], 0/1, q=2-31, 1000 kb/s  
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | ,   
> [2021-06-29 11:45:23.713] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | 90k tbn  
> [2021-06-29 11:45:23.714] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  |   
> [2021-06-29 11:45:23.714] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  |     Stream #0:1  
> [2021-06-29 11:45:23.714] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | : Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, 160 kb/s  
> [2021-06-29 11:45:23.714] I [FilePubWorker:1600] FFmpeg | third_parties.cpp:118  | 

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version:  v0.12.0

**Player (please complete the following information):**
 - LiveStream Player:  OvenPlayer
 - Browser: Chrome v91.0.4472.114

**Comment by kwonkeukhan** [comment]
@HackPB 

Thanks for reporting.

In order to analyze the cause, please send the **full OME log** in a situation where the sync is not matched.

Log file output should be built in DEBUG mode and the MediaRouter tag set to debug level.

Then I will wait for your reply.

Thanks.

**Comment by HackPB** [comment]
Hello @kwonkeukhan, first off all sorry for the late reponse.

As you requested today I have made a new build with `make -j $(nproc)` and then added the `<Tag name="MediaRouter" level="debug" />` in the Logger.xml file.
I don't know if I missed something, if so please let me know.

The log is as cleas as possible, because I have cleaned all previous logs, then started OME, then start transmiting with OBS and after made the request to API to start recording. The recorded OutputProfile was the `<Name>webrtc_360</Name>` stated in the previous message.
The generated mp4 video is totally out of sync.

In attachments there is the  ovenmediaengine.log.
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6739667/ovenmediaengine.log)

**Comment by nuguya18** [comment]
@HackPB 

Sorry for the late reply.

The log you sent is not an accurate judgment.
However, when recording as an mp4 file, audio is bypassed and video is transcoding. 
When transcoding is performed, PTS is accumulated and recalculated.
When packets are dropped in a live environment, there is a problem that the gap between the PTS of untranscoded audio and transcoded video gradually increases.

Recently, it has been improved in a way that maintains the original PTS even if it is transcoded.

Download the latest master version, test it, and let us know the result :)

Thanks.

**Comment by HackPB** [comment]
Hi @nuguya18

Thanks for that info. During this week I will try out the latest version and will report back.

Meanwhile can You tell me what steps should I do to improve the logs? 

Thanks

**Comment by Keukhan** [comment]
@HackPB 

There is no log with special added.
Just build in debug mode and set the MediaRouter tag to debug level.

If you look at the log below, you can check the sync value.

`[08-10 17:05:42.845] D [InboundWorker:1455267] **MediaRouter** | mediarouter_stream.cpp:825  | 
 - MediaRouter Stream | type: Inbound, name: #default#app/stream, uptime: 70050ms, queue: 0, sync: 37ms
        [  0] type: video( 1/H264), pts: 70000ms, tb: 1/1000,  delay:     8ms, pkt_cnt:   2101, pkt_siz: 44.0MB
        [  1] type: audio( 6/ AAC), pts: 70037ms, tb: 1/1000,  delay:    -7ms, pkt_cnt:   3284, pkt_siz: 42.9KB
[08-10 17:05:42.876] D [OutboundWorker:1455270] **MediaRouter** | mediarouter_stream.cpp:825  | 
 - MediaRouter Stream | type: Outbound, name: #default#app/stream_o, uptime: 70079ms, queue: 0, sync: 77ms
        [  0] type: video( 3/ VP8), pts: 69933ms, tb: 1/90000,  delay:   -12ms, pkt_cnt:   2099, pkt_siz: 18.1MB
        [  1] type: audio( 8/OPUS), pts: 70010ms, tb: 1/48000,  delay:    23ms, pkt_cnt:   7002, pkt_siz: 21.0KB
`

Thanks

**Comment by HackPB** [comment]
First thank you guys for your support.
Finally I had some time to test this. In the newer versions this problem seems to be resolved so I will close this issue.

Thanks.
