### ISSUE TITLE
Is is possible to do hls/dash/webrtc no-transcode streaming?

### ISSUE THREAD

**Issue by wnpllrzodiac** [AirenSoft/OvenMediaEngine#43]
I cannot found config sample to do streaming without transcode.
Is it possible?

**Comment by dimiden** [comment]
Hi, @wnpllrzodiac 

Currently, OvenMediaEngine does not support bypass feature. But the bypass feature is in our plan, so we will add it later.

**Comment by getroot** [comment]
This feature was developed in dev branch. Details and configuration will be updated in the documentation soon after merging into the master branch.

**Comment by getroot** [comment]
New information will be updated in the future at #28 .
