### ISSUE TITLE
Stream is not viewable with ip adress

### ISSUE THREAD

**Issue by etwasmitbaum** [AirenSoft/OvenMediaEngine#432]
**Describe the bug**
I can stream from OBS to OME. When trying to view the stream with the OvenPlayer demo, only an error is shown when using the servers IP Adress. The Stream works if I view the stream with `localhost` (not the IP adress) on my device with OME Server.
I am Testing the stream on https://demo.ovenplayer.com/
with this as stream URL: ws://192.168.178.77:3333/app/stream.

As said `ws://localhost:3333/app/stream` works on the machine itself but not `192.168.178.77`  instead of `localhost`.
`192.168.178.77` is the correct ip adress of my local Server.

**To Reproduce**
1. Connect OBS from a different device and start streaming
2. Make sure the stream is connected
3. Try to view the stream with the OvenPlayer Demo on the same or different device with this URL: `ws://192.168.178.77:3333/app/stream`

**Expected behavior**
The stream works when using `ws://192.168.178.77:3333/app/stream` as URL

**Actual behavior**
The player shows an error: `Connection with low-latency(OME) server failed.`

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/6770416/ovenmediaengine.log)
[webrtc_rtsp_viewers.log](https://github.com/AirenSoft/OvenMediaEngine/files/6770417/webrtc_rtsp_viewers.log)
Chrome console log when trying to view the stream:
[chrome_console.log](https://github.com/AirenSoft/OvenMediaEngine/files/6770418/chrome_console.log)

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: v0.12.1
 - Branch: release
 
**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10 21H1 / Ubuntu 20.04(Server)
 - Browser: Chrome
 - Version 91

**Comment by getroot** [comment]
You should test on http://demo.ovenplayer.com/ instead of https://demo.ovenplayer.com/. Because your OME doesn't have TLS enabled.

**Comment by etwasmitbaum** [comment]
It's working now. Thank you so much.
Chrome was automatically redirecting to `https://`. That was the problem.
