### ISSUE TITLE
API Record

### ISSUE THREAD

**Issue by cl84** [AirenSoft/OvenMediaEngine#433]
How can I use the sequence macro in the "filePath" field via the Record API?

**Comment by kwonkeukhan** [comment]
Hi. @cl84 

You can refer to the link below for API.

- https://airensoft.gitbook.io/ovenmediaengine/v/master/rest-api/v1/virtualhost/application/recording

See the link below for macros used for filePath, infoPath. It can be set the same as the xml setting file.

- https://airensoft.gitbook.io/ovenmediaengine/v/master/recording-experiment#macro-definition

Thanks.

**Comment by cl84** [comment]
if I use the macro with API as in the xml file the macro doesn't work, just write $Sequnce in the filename

**Comment by kwonkeukhan** [comment]
@cl84 

Thank you for your excellent report.

I solved the problem and updated it to the latest source. Please test it.

Please share any ideas that need to be improved regarding the recording feature.

Thanks.

**Comment by getroot** [comment]
Please run prerequisites.sh again. Recently, UUID-related external libraries have been added.

**Comment by cl84** [comment]
ok thanks, I'll try and update you

**Comment by cl84** [comment]
> @cl84
> 
> Thank you for your excellent report.
> 
> I solved the problem and updated it to the latest source. Please test it.
> 
> Please share any ideas that need to be improved regarding the recording feature.
> 
> Thanks.

perfect, macros work fine now via API

**Comment by cl84** [comment]
> @cl84
> Please run prerequisites.sh again. Recently, UUID-related external libraries have been added.

the compilation was successful after running prerequisites.sh

Thank you

**Comment by cl84** [comment]
Hello, I noticed a problem with the stop recording, the fields [recordBytes], [recordTime], [sequence], [totalRecordBytes], [totalRecordTime] in the json response are always 0.

Thank you

I attach json response

Array
(
    [message] => OK
    [response] => Array
        (
            [0] => Array
                (
                    [app] => app
                    [createdTime] => 2021-07-09T11:53:19.996+0200
                    [id] => camera1
                    [recordBytes] => 0
                    [recordTime] => 0
                    [sequence] => 0
                    [state] => ready
                    [stream] => Array
                        (
                            [tracks] => Array
                                (
                                )

                        )

                    [totalRecordBytes] => 0
                    [totalRecordTime] => 0
                    [vhost] => Oven_Test
                )

        )

    [statusCode] => 200
)

**Comment by kwonkeukhan** [comment]
@cl84 

Recording is being terminated asynchronously when requested to stop recording. currently, there is a problem with stopping recording and not getting statistical information at the end of the recording process.

Please refer to the XML (FileInfo) file for details of the file that has been recorded.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
