### ISSUE TITLE
use of Ulpfec and Rtx when using ?transport=tcp

### ISSUE THREAD

**Issue by basisbit** [AirenSoft/OvenMediaEngine#439]
Is there any advantage of using Ulpfec and Rtx when using `?transport=tcp` / WebRTC over TURN while also using playoutDelay of for example 1.5 seconds?
I noticed that WebRTC outbound stream to clients is roughly 50% more bits per second than RTMP inbound or HLS outbound. For when using UDP transport, I understand the goal of it (although RED might yield much better results there instead?). But for TCP from my understanding, the stream will only continue playing once the data is transmitted including early/fast retransmit and similar tcp mechanisms? Does anyone of you have tested if disabling Ulpfec and Rtx for tcp transport results in better stability (because one third less network traffic and possibly less CPU load)? Thanks in advance!

**Comment by getroot** [comment]
ULPFEC and RTX have no effect if only transport=tcp is used. Rather, it will only use more memory. So you can turn that feature off as below.

```
<Publishers>
	<WebRTC>
		<Timeout>30000</Timeout>
		<Rtx>false</Rtx>
		<Ulpfec>false</Ulpfec>
	</WebRTC>
```
