### ISSUE TITLE
Pull RTSP source

### ISSUE THREAD

**Issue by vitragmehta** [AirenSoft/OvenMediaEngine#44]
Can we also have a way to be able to pull rtsp source such as cctv / ip camera?

**Comment by dimiden** [comment]
RTSP-related features will be added soon.
I don't have a schedule yet, but I'll tell you again when it's decided.

**Comment by getroot** [comment]
This feature was developed in dev branch. Details and configuration will be updated in the documentation soon after merging into the master branch.

**Comment by getroot** [comment]
The feature has released as Beta in version 0.10.4.
