### ISSUE TITLE
Connection failed when trying to get stream with signed policy

### ISSUE THREAD

**Issue by LittleMoon215** [AirenSoft/OvenMediaEngine#440]
Hello.
I am trying to get signed policy working.
I have next OutputProfiles in Server.xml. 

```
                                         <OutputProfiles>
						<OutputProfile>
							<Name>stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
							</Encodes>
						</OutputProfile>
						<OutputProfile>
							<Name>720_60</Name>
							<OutputStreamName>${OriginStreamName}_720_60</OutputStreamName>
							<Encodes>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								<Video>
									<Codec>h264</Codec>
									<Width>1280</Width>
       									<Height>720</Height>
        								<Bitrate>5096000</Bitrate>
        								<Framerate>60.0</Framerate>
									
								</Video>
							</Encodes>
						</OutputProfile>
						<OutputProfile>
							<Name>720_60</Name>
							<OutputStreamName>${OriginStreamName}_720_30</OutputStreamName>
							<Encodes>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								<Video>
									<Codec>h264</Codec>
									<Width>1280</Width>
       									<Height>720</Height>
        								<Bitrate>4096000</Bitrate>
        								<Framerate>30.0</Framerate>
									
								</Video>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
```
It was working fine until i enabled signed policy. Keys was generated using sh script and streaming throw OBS works fine. But ovenplayer gives me connection error, when i'm trying to switch on any quality different from 1080.

![изображение_2021-07-15_215915](https://user-images.githubusercontent.com/45228162/125810123-6db8f903-d2b0-43f3-bc9c-545e137322c0.png)

![изображение_2021-07-15_220212](https://user-images.githubusercontent.com/45228162/125810547-88f5615e-2d05-4a0f-aa50-168c9a245827.png)

![изображение_2021-07-15_220257](https://user-images.githubusercontent.com/45228162/125810670-89df6d57-fcca-4e95-bd66-e29bdb934537.png)

Here is ovenplayer's sources 
![изображение_2021-07-15_220417](https://user-images.githubusercontent.com/45228162/125810895-e71317a5-c560-42f5-b57a-52d7a64896b2.png)
 How to fix that?

**Comment by getroot** [comment]
Please upload your ovenmediaengine.log file

**Comment by LittleMoon215** [comment]
[logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6824743/logs.txt)

**Comment by getroot** [comment]
The Server.xml you posted here and the Server.xml actually loaded are different.

`[2021-07-15 16:17:31.065] I [OvenMediaEngine:1] Config | config_manager.cpp:93 | Trying to load configurations... (origin_conf/Server.xml)`

You have to edit origin_conf/Server.xml in docker container to your Server.xml.

**Comment by LittleMoon215** [comment]
Oh, sorry. It seems I made a mistake when copied the file in docker. Thanks you a lot.
One more question: How to give every user its own link for stream? I need to add OutputProfile in Server.xml every time when new user register?

**Comment by getroot** [comment]
You can set url_expire short to generate a URL and then deploy it.

**Comment by LittleMoon215** [comment]
This will give them the opportunity to stream at the same time? The link will direct to one profile, or i misunderstanding something?

**Comment by getroot** [comment]
Do you want to give a stream to the sender? If so, issue a different stream name.

rtmp://domain:1935/app/stream?~
rtmp://domain:1935/app/stream1?~
rtmp://domain:1935/app/stream2?~

Do you want to issue a URL to anyone who wants to play? And do you want to issue a different URL to each one? If so, in SignedPolicy, issue expire as current time + 5 seconds. If you don't play within 5 seconds, the URL will be discarded.

Please explain in detail exactly what you want something.

**Comment by LittleMoon215** [comment]
I want to give a unique rtmp address for each user. For example: you register a new account, in your profile you get signed stream key, and its become yours until you delete your account.
As far as I understand, the broadcast address is the OutputProfile. So, should I add a new OutputProfile when the new user register?

**Comment by getroot** [comment]
I recommend that you read the OvenMediaEngine manual first. (https://airensoft.gitbook.io/ovenmediaengine/)

As in my first answer, issue the stream name differently.
rtmp://domain:1935/app/stream
rtmp://domain:1935/app/stream2
rtmp://domain:1935/app/stream3

These will all be different streams.
The WebRTC output stream will be as follows depending on your settings.

ws://domain:3333/app/stream
ws://domain:3333/app/stream_720_60
ws://domain:3333/app/stream_720_30

ws://domain:3333/app/stream2
ws://domain:3333/app/stream2_720_60
ws://domain:3333/app/stream2_720_30

ws://domain:3333/app/stream3
ws://domain:3333/app/stream3_720_60
ws://domain:3333/app/stream3_720_30

**Comment by LittleMoon215** [comment]
Oh, I tested this now and now everything is clear. 
It looks like I just misunderstood this paragraph.
![изображение_2021-07-16_151509](https://user-images.githubusercontent.com/45228162/125915608-9c8d51dd-b27e-4ca8-b62b-52c35d1a092a.png)

Thanks you a lot!

**Comment by getroot** [comment]
Yes, Input Stream and Output Stream should be considered separately. One Input Stream can create multiple Output Streams according to OutputProfiles. I wish your project success.
