### ISSUE TITLE
Option to keep original for transcoding

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#441]
Our Output profiles are currently configured like this:

`<OutputProfiles>
<OutputProfile>
<Name>bypass_stream</Name>
<OutputStreamName>${OriginStreamName}</OutputStreamName>
<Encodes>
<Audio>
<Bypass>true</Bypass>
</Audio>
<Video>
<Bypass>true</Bypass>
</Video>
<Audio>
<Codec>opus</Codec>
<Bitrate>128000</Bitrate>
<Samplerate>48000</Samplerate>
<Channel>2</Channel>
</Audio>
</Encodes>
</OutputProfile>
</OutputProfiles>`

So we have Audio Bypass enabled _and_ Audio set to transcode to Opus. We use RTMP, SRT and WebRTC for ingest and only WebRTC for playback (hence the need to transcode non-Opus audio). 

Using the above config, does the audio of an incoming WebRTC stream get encoded to Opus 128kbps, or does it get bypassed because it is already Opus? 

Ideally incoming streams that already have Opus audio would be bypassed, and only incoming streams that do not have Opus audio (like RTMP which has AAC audio) would be transcoded to Opus.

**Comment by getroot** [comment]
Even if the same OPUS codec is input, it is encoded now because it can output in different quality (Bitrates, Samplerates, Channel).

We will add "Keep Original" settings to "Bitrates", "Samplerates", and "Channel" in the future. Through it, when the Opus codec is input, it can be pass-through without encoding.

**Comment by llspalex** [comment]
Thank you - "Keep Original" would be a very welcome feature 😃

**Comment by llspalex** [comment]
Reopening as this issue might be useful for other people to see or discuss. Please close if need be.

**Comment by llspalex** [comment]
@getroot We have done some testing, and it seems that we are experiencing "keep original" functionality already in our implementation...

When using WebRTC Input, we send 48khz, 2-channel audio at 384kbps from Chrome to an OME server with the configuration mentioned in my [first post](https://github.com/AirenSoft/OvenMediaEngine/issues/441#issue-945774699) which is set to 128kbps Opus audio. 

I expected that OME would transcode the incoming stream from 384kbps to 128kbps, but it doesn't seem to - in Chrome webrtc-internals we are seeing 384kbps on the RTCOutbound and RTCInbound stats:
![Screenshot 2021-07-19 at 15 17 07](https://user-images.githubusercontent.com/67900507/126174784-1012d6d4-6df9-4f34-b467-d754001f469c.png)
![Screenshot 2021-07-19 at 15 17 21](https://user-images.githubusercontent.com/67900507/126174796-7df250e7-b175-4f82-b16a-7803d0da2986.png)

I have tested streaming audio from the browser at 64kbps, 128kbps, 256kbps and 384kbps and in all cases the outbound bitrate matches the inbound bitrate, regardless of the OME config. 

Is the above behaviour what you expected? If it is performing as we think it is - then that's not what we expected, BUT it is what we wanted, so that's cool 😀

With RTMP ingest and WebRTC playback, the behaviour is as expected: we receive 128kbps Opus audio from our OME servers that are configured at 128kbps, and we receive 384kbps Opus audio from our OME servers that are configured at 384kbps - regarldess of what the audio bitrate is in the RTMP stream.

**Comment by kwonkeukhan** [comment]
@llspalex 

My guess is that the transcoded OPUS track doesn't play, it plays the bypassed opus track. If you send the server.xml file and log file, you can find out the exact cause.

Thanks

**Comment by getroot** [comment]
@llspalex 
This is not the intended behavior, but WebRTC Publisher sends the first opus track of audio, so `<Audio> <Bypass>true</Bypass> </Audio>` is playing in your settings. This can also be a great way to meet your needs. :-)

**Comment by llspalex** [comment]
@kwonkeukhan @getroot Thank you very much for the info. I will send the server.xml and log file as soon as I can.

**Comment by basisbit** [comment]
In your first post you mentioned this config:
```
<OutputProfiles> 
	<OutputProfile>
		<Name>bypass_stream</Name>
		<OutputStreamName>${OriginStreamName}</OutputStreamName>
		<Encodes> 
			<Audio> 
				<Bypass>true</Bypass> 
			</Audio> 
			<Video> 
				<Bypass>true</Bypass> 
			</Video> 
			<Audio> 
				<Codec>opus</Codec> 
				<Bitrate>128000</Bitrate> 
				<Samplerate>48000</Samplerate> 
				<Channel>2</Channel> 
			</Audio> 
		</Encodes> 
	</OutputProfile> 
</OutputProfiles>
```

Because of the order of the bypass being above the opus audio, the client will first try to play the bypass, and only if that fails, then fallback to playing the reencoded audio track.

**Comment by llspalex** [comment]
@Keukhan Thank you! This looks great.
