### ISSUE TITLE
OME crash when trying to get page.

### ISSUE THREAD

**Issue by LittleMoon215** [AirenSoft/OvenMediaEngine#444]
**Describe the bug**
OME crash when trying to get thumbnail.

**To Reproduce**
1. Set Server.xml as follows
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6841087/Server.xml.txt)
2. With Encoder OBS 26.1.1
3. Try to get page with not signed url like http://*.*.*.*:8080/moony_preview/thumb.png
3. See error

**Expected behavior**
404 or can't connect to server and OME continue to work

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.
[logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6841175/logs.txt)

**Server (please complete the following information):**
 - OS: Ubuntu 21.04
 - OvenMediaEngine Version: v0.12.1
 - Branch: docker:latest

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser Opera GX
 - Version LVL2 (core: 76.0.4017.208)

**Additional context**
not signed url like http://*.*.*.*:8080/moony_preview/thumb.png crashes OME, but signed url like 
http://*.*.*.*:8080/app/moony_preview/thumb.png?policy=eyJ1cmxfZXhwaXJlIjo3OTU1MDg5MzQ1MDAwfQ==&signature=Zk7Ra5-JcLNut1rjYLCo76EZz0w=
works fine

**Comment by kwonkeukhan** [comment]
@LittleMoon215 

Thanks for the reporting.

First of all, the application name was excluded when you called with a non-signed URL.

Nevertheless, there is a problem with crashing, so we handled an exception. updated to the latest version. if you have time, please test it.

additional information, we plan to signed url in thumbnail requests soon. please take a moment to look at the update log.

Thanks.

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.
