### ISSUE TITLE
question: how secure webrtc stream

### ISSUE THREAD

**Issue by vitragmehta** [AirenSoft/OvenMediaEngine#45]
Apologies if this seems to be a simple question. i am very new to media streaming. Here is the case related to the question.
Using OBS to stream my screen to Oven Media Engine.
Created a html file and related files to use oven media player to play the stream on other pc
this means basically any one who has the following can access the media stream
1. url to the media stream
2. ovenmedia player (or any other player)

if i put the oven media player url on my web server; this will expose(i am assuming) the url to any one accessing the website. is there any way where i can add some username / password ro any other security for users who can view the stream?

**Comment by dimiden** [comment]
In general, create a service page and make the player page visible only when you log in from that page.
(This requires an understanding of web application development.)

If you want to prevent the logged-in user from extracting the streaming URL and exposing it to other users, you should use a one-time URL or a streaming URL with TTL (Time To Live). Unfortunately, OME does not currently support these features.

**Comment by vitragmehta** [comment]
Many thanks for the insight.
