### ISSUE TITLE
Cordova/Ionic WebRTC plugin

### ISSUE THREAD

**Issue by DanielnetoDotCom** [AirenSoft/OvenMediaEngine#451]
I can see you guys have some SDK for mobile but do you guys already have something for Cordova?

Also, do you guys only have it for Android? do you have for iOS?

**Comment by getroot** [comment]
No, we have no experience with cordova.
For SDK for mobile native app, refer to https://webrtc.googlesource.com/src/+/refs/heads/main/docs/native-code/index.md.
