### ISSUE TITLE
Multiple Inputs SRT to Origin "No room to store incoming packet" 

### ISSUE THREAD

**Issue by mithrand1rr** [AirenSoft/OvenMediaEngine#452]
Hi there trying to pipe in multiple streams into the origin over local host. The streams are SRT and up to 3-4 work as expected but once we go over the 4-5 number on the input side we  start to get the folioing  

`W [SRT:RcvQ:w1:6533] SRT | core.cpp@SRT:9626 | @779869:No room to store incoming packet: offset=1 avail=0 ack.seq=1574014853 pkt.seq=1574014854 rcv-remain=8191 drift=0`

Tried to disable all the unnecessary publishers that and noise but the system resources are well under 50% across the board. No encoding is happening, everything should be bypassed on the Audio and video side of things. 

Also tested multiple inputs from sources other than local host and still only seem to be able to get around 3-4 stable. 

Origin config is below. The goal we are trying to get to is 20+ incoming streams. Again they are all being piped in via local host (127.0.0.1:9998) 

As always thanks in advanced for any tips/ tricks! 

`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	
	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		
		<Managers>
			<API>
				<Port>${env:OME_API_PORT:48081}</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>
		
		<Providers>
			
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9998}</Port>
			</SRT>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000-4003,4004,4005/udp}</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					
					
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
			</OVT>
			 
				
				
				
			
				
				
			
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					
					
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			

			
			<Applications>
				<Application>
					<Name>TEST</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>main</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000,4001-4004</Port>
								</Stream>
								<Stream>
									<Name>stream_4005</Name>
									<Port>4005</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<SessionLoadBalancingThreadCount>12</SessionLoadBalancingThreadCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
						 
						
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>`

**Comment by getroot** [comment]
This seems to be related to the recv buffer of SRT.

https://github.com/Haivision/srt/issues/409

We will find out if there is an option in the SRT to solve this and apply it.

Thanks for reporting.

**Comment by dimiden** [comment]
The "No room to store.." error can be resolved by adjusting the size of ```SRTO_RCVBUF```.
You can refer to [srt-socket-options](https://airensoft.gitbook.io/ovenmediaengine/live-source/srt-beta#srt-socket-options) for instruction on how to set SRT option.

For more information, please refer to https://github.com/Haivision/srt/issues/642.
