### ISSUE TITLE
Stress test / load test

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#453]
Hello,
How to stress test OME WebRTC? Do you have any internal tool/script?

I would like to test OME for e.g. 1000 simultaneous viewers.

**Comment by getroot** [comment]
One of our customers has experience making a simulator using GStreamer and testing it with us. (20 core CPU / 32M memory / 3000 rtsp input / 3000 webrtc output tested in 10Gbps network, 1M video only)

Unfortunately, however, we do not have the rights to distribute that simulator.

We also want to make and distribute a simulator, but time doesn't allow it. :-(

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
