### ISSUE TITLE
Simpler SRT URL

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#454]
Hello,
Could you make simpler URL for SRT with this options, something like this:
- `srt://ip:port?s=test` or
- `srt://ip:port?s=app/test`

`srt://ip:port?streamid=srt%3A//{domain or IP address}[%3APort]/{App name}/{Stream name}%3Fquery%3Dvalue` looks very long, complicated for user and needs to be generated by script

And maybe add default options for SRT provider such as default vhost or app:
```
<SRT>
	<Port>9999</Port>
	<DefaultVhost>default</DefaultVhost>
	<DefaultApp>app</DefaultApp>
</SRT>
```

**Comment by getroot** [comment]
This is what the SRT client should do. 

OME needs to know the domain the client is trying to connect to in order to handle the VHost.
If OME does not receive a domain through streamid, there is no way for OME to find out which domain the client is using.

**Comment by basisbit** [comment]
I'd guess the main issue here is, that OME documentation is currently written for people who already know a lot about video streaming protocols and OME configuration and so on. It might be helpful to change the basic structure to be more targeted for people who want to get started quickly without having to understand all of OME configuration before doing so.
Most samples that are mentioned are not complete (or contain everything / way too much other stuff) and then people easily get frustrated because they don't know what they are missing to get it to work.

**Comment by IanMitchell77** [comment]
I dont think this is the correct way but where do Fquery and Dvalue come from?

**Comment by mpisat** [comment]
> I dont think this is the correct way but where do Fquery and Dvalue come from?

%3Fquery is encoded params, it is query and value.

**Comment by IanMitchell77** [comment]
Yes but where did the actual values come from, the config xml?

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by basisbit** [comment]
Please reopen. There is still an unanswered question and the issue was last active only 3 days ago

**Comment by getroot** [comment]
query=value seems to have been referenced from the documentation.

https://airensoft.gitbook.io/ovenmediaengine/live-source/srt-beta#obs-studio

When I wrote this article, I wrote an example of using querystring when users use SignedPolicy in SRT in the same way as query=value.

**Comment by basisbit** [comment]
so, when not using SignedPolicy, one would just remove that `%3Fquery%3Dvalue`, correct?
Also, something like `&latency=1000000` should probably be added to OME SRT documentation, because that seems to be necessary for srt to work properly in typical use cases where SRT is used. From OBS docs:
> The most important option is latency in microseconds (μs). It has a default value of 120 ms = 120 000 μs and should be at least 2.5 * (the round-trip time between encoder and ingest server, in ms).
Ex: for a latency of 1 sec, set latency=1000000 .

I'll test this and then create a PR for the documentation repository.

**Comment by getroot** [comment]
@basisbit Yes, you are right. I haven't studied the options of the SRT client in detail yet. If the &latency=1000000 option works well, please PR. thank you.

**Comment by alnux** [comment]
hi, im trying to stream with SRT but OBS connect and desconnect? my url is the next:

srt://{my_ip}:9999?streamid=srt%3A//{my_ip}%3A9999/app/stream

is it ok???

on my Server.xml's application is enable 

```
<SRT>
           <Port>9999</Port>
            <!-- <WorkerCount>1</WorkerCount> -->
</SRT>
```

and  

```
<Providers>
          <OVT />
           <WebRTC />
           <RTMP />
          <SRT />
          <MPEGTS>
           ........
          .........
```

**Comment by alnux** [comment]
Solved, the docs srt code is wrong the correct streamid is:

`srt%3A%2F%2F{domain or ip}%3A9999%2Fapp%2Fstream`

**you have to put %2F instead of "/"**

**Comment by basisbit** [comment]
As stream server address in OBS, we suggest using something like `srt://server1.yourselver.com:9999?streamid=srt%3A//server1.yourselver.com%3A9999/appNamw/aStreamKey&latency=40000`, where latency should be at least 2.5 times of the latency between your server and the streamer. If in doubt, put 1000000 for 1 second.

**Comment by alnux** [comment]
The reason I replaced / with %2F is because OBS ( the vmix too ) was not connecting and strangely freezing. By the way in VMIX> 23.0.0 v. Also works

**Comment by 3dcandy** [comment]
I'm still a little confused on the correct syntax here. For example I want to send a stream from OBS to my livestream server with something like
srt://myserver.com:9999/appname/streamkey&latency=2000000

So what would that be percent encoded as I've tried a few and cannot get it to connect. Can get an OBS to OBS srt stream working across my network fine...but not into OME

**Comment by basisbit** [comment]
@3dcandy see my previous response and enter your app name streamkey and server dns name

**Comment by 3dcandy** [comment]
@basisbit I shall give it a go later today or tomorrow. Just updated OME to latest release so I have some config to do. I wish there was a web interface to make it easier like AMS that would help me greatly when I'm away from my liveserver
