### ISSUE TITLE
adding rtmp_tcurl directive to ffmpeg for rtmppush

### ISSUE THREAD

**Issue by mpisat** [AirenSoft/OvenMediaEngine#458]
I'm trying to perform a RTMP PUSH to some RTMP endpoint where it works with OBS but it doesn't work with OME because it requires the following parameters: 
-rtmp_flashver FMLE12345 -rtmp_tcurl $RTMPURI -f flv $RTMPURI

OME sends -f flv $RTMPURI part but there is no tcUrl directive. I tried to find parameters in .cpp and .h files but failed to do so.

If you can point me to which file(s) and lines to add, I appreciate it. Right now, I'm using a workaround like this, which adds another step and latency. It would be great if I can avoid this step. Maybe you can also make it so that we can choose ffmpeg parameters AND/OR preset and quality in the future?

```
export RTMPURI=rtmp://blablabla.com/appname/username/username.keynumber
./ffmpeg -hide_banner -f flv -listen 1 -i rtmp://0.0.0.0:19350/app/murat -c:v libx264 -c:a copy -b:v 1200k -preset veryfast -r 30 -tune zerolatency -g 30 -keyint_min 30 -rtmp_flashver FMLE12345 \
-rtmp_tcurl $RTMPURI -f flv $RTMPURI
```

Thank you.

**Comment by basisbit** [comment]
ffmpeg parameters can be adjusted here:
https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/transcoder/codec/encoder/encoder_avc.cpp#L77

**Comment by mpisat** [comment]
> ffmpeg parameters can be adjusted here:
> https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/transcoder/codec/encoder/encoder_avc.cpp#L77

Thank you. I wonder where I can add rtmp_tcurl parameter for bypass profile (no transcoding) to RtmpPush?

**Comment by Keukhan** [comment]
@mpisat 

If you want to add parameters when connecting RTMP, you can change it here.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/modules/rtmp/rtmp_writer.cpp#L118

**and,** please refer to the code below for calling RtmpWriter.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/publishers/rtmppush/rtmppush_session.cpp#L45

**Below** is an example of setting parameters.

> std::unique_lock<std::mutex> mlock(_lock);
> 
> AVDictionary *options = nullptr;
> 
> // Examples
> av_dict_set(&options, "rtmp_flashver", "FMLE12345", 0);
> av_dict_set(&options, "rtmp_tcurl", _format_context->url, 0);
> 
> 	
> if (!(_format_context->oformat->flags & AVFMT_NOFILE))
> {


If the test is successful, Please make a PR.
I think it will be very helpful for this project.

Thanks.

**Comment by mpisat** [comment]
Hi,

I've added the following to
https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/modules/rtmp/rtmp_writer.cpp#L128
av_dict_set(&options, "rtmp_flashver", "FMLE12345", 0);
av_dict_set(&options, "rtmp_tcurl", _format_context->url, 0);

And it worked. I also changed ffmpeg settings to my taste and preferences as my main usage is to make a WebRTC to RTMP gateway and it worked.

The only problem is CPU usage. I got I7-9700K server with intel gpu but I can't get hardware encoder to work. The only way I can ever get qsv to work is using docker image: jrottenberg/ffmpeg:4.4-vaapi2004 with VAAPI option.

**Comment by Keukhan** [comment]
That's great.

Then, I will close this issue.
