### ISSUE TITLE
ABR for WebRTC

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#460]
Will OME have support for adaptive bitrate in WebRTC? When?

**Comment by getroot** [comment]
We will develop Simulcast for WebRTC ABR. I also want to develop this function quickly, but it is not easy to develop quickly because recently we have to do a commercial project for our survival.

Anyway, WebRTC ABR as well as HLS/DASH ABR are the highest priority tasks.

**Comment by getroot** [comment]
@IanMitchell77 I'm working on LLHLS right now, and I'll do ABR right after that.

**Comment by davidghukasyan** [comment]
> @IanMitchell77 I'm working on LLHLS right now, and I'll do ABR right after that.

Man, the whole world's waiting for you to do the ABR on Webrtc to everyone could switch from HLS to WebRTC  :) and your doing HLS

**Comment by davidghukasyan** [comment]
> @IanMitchell77 I'm working on LLHLS right now, and I'll do ABR right after that.

Are you on it now ? Are you going to use dynamic fps for WebRTC ABR ?

**Comment by fcqpl** [comment]
> > @IanMitchell77 I'm working on LLHLS right now, and I'll do ABR right after that.
> 
> Are you on it now ? Are you going to use dynamic fps for WebRTC ABR ?

Something is coming :)
https://github.com/AirenSoft/OvenMediaEngine/commit/6e7e0ffeb15bc5fabd007fa4bb7f6534edfc69d1

**Comment by getroot** [comment]
@davidghukasyan 
Hey, "the whole world" seems to be sleeping. The WebRTC ABR you've been waiting for has arrived. Please give me feedback.

**Comment by fcqpl** [comment]
Hi,
I didn't have much time for testing, but total video + audio bandwidth is taken into the rendition selection?
While limiting the internet connection speed, it seemed to me that the quality change is based on bitrate of the video stream itself.

360p - 500kbps / 480p - 2000kbps / 720p - 5000kbps
When I set bandwidth limit to max 2000kbps, playback goes to 480p and it stutters. It should go to 360p.

**Comment by davidghukasyan** [comment]
> @davidghukasyan Hey, "the whole world" seems to be sleeping. The WebRTC ABR you've been waiting for has arrived. Please give me feedback.

@getroot  We are testing it. The scenario is to ingest : 1920x1080 3 Mbit/s stream and output
High quality: 1920x1080 3072 Kbit/s 
Medium quality: 852x480 800 Kbit/s
Low quality: 640x360 400 Kbit/s  
We'll share some details later.

**Comment by getroot** [comment]
@fcqpl @davidghukasyan 
Please continue the discussion at #805

**Comment by getroot** [comment]
I close this issue because WebRTC ABR has been released with version 0.14.3. Thank you for your contributing!

**Comment by Wanghaha2333** [comment]
Hi, as a freshman for WebRTC, I wanna ask, in which folder of src could we find the code of ABR?

**Comment by getroot** [comment]
@Wanghaha2333 You can start here.
https://github.com/AirenSoft/OvenMediaEngine/blob/7976d7cac69bfeed3b27fb7dbb6a51c094ef8453/src/projects/publishers/webrtc/rtc_session.cpp#L839

**Comment by Wanghaha2333** [comment]
@getroot  Thank you for your response! However, is this repository different from the one downloaded by 'fetch-- nohooks webrtc'? I can't find this file in my downloaded webrtc source code. I would be very grateful if you could help to solve this, thank you!

**Comment by getroot** [comment]
@Wanghaha2333 What you downloaded is probably the native webrtc library. We have nothing to do with it.
