### ISSUE TITLE
[recording] DTS in TS files all start from 0

### ISSUE THREAD

**Issue by cmiller-nflux** [AirenSoft/OvenMediaEngine#461]
**Describe the bug**
When starting a recording of a stream via recording api, the resulting ts files DTS start from 0.  This causes a failure when trying to make an HLS m3u8 manifest using said ts files.  I would expect them to increase from file to file...Is there a missing setting?

The process works like this:
1. record 10 second ts files
2. create hls playlist
3. play on video.js

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-TARGETDURATION:10
#EXTINF:10.167,
20210803201553_20210803201603.ts
#EXTINF:10.101,
20210803201603_20210803201613.ts
#EXT-X-ENDLIST
```

 and the resulting error when running `ffplay playlist.m3u8` is:

```
[ffmpeg/demuxer] mpegts: Packet corrupt (stream = 0, dts = 988028).
[ffmpeg/demuxer] mpegts: DTS 0 < 988028 out of order
[ffmpeg/demuxer] hls: DTS 0 < 988028 out of order
``` 

**To Reproduce**
`
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
        <Name>OvenMediaEngine</Name>
        
        <Type>origin</Type>
        
        <IP>*</IP>

        <Managers>
            <Host>
                <Names>
                    <Name>*</Name>
                </Names>
                
            </Host>
            <API>
                <AccessToken>confidential</AccessToken>
            </API>
        </Managers>

        
        <StunServer>stun.l.google.com:19302</StunServer>

        
        <Bind>
                
                <Managers>
                    <API>
                        <Port>8081</Port>
                    </API>
                </Managers>
                <Providers>
                        <RTMP>
                                <Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
                        </RTMP>
                        <MPEGTS>
                                
                                <Port>${env:OME_MPEGTS_PROV_PORT:4000-4003,4004,4005/udp}</Port>
                        </MPEGTS>
                </Providers>

                <Publishers>
                        
                        <OVT>
                                <Port>${env:OME_ORIGIN_PORT:9000}</Port>
                        </OVT>
                        <Thumbnail>
                            <Port>20080</Port>
                            
                        </Thumbnail>
                        <HLS>
                                <Port>${env:OME_HLS_STREAM_PORT:8080}</Port>
                                
                                
                        </HLS>
                        <DASH>
                                <Port>${env:OME_DASH_STREAM_PORT:8080}</Port>
                                
                                
                        </DASH>
                        <WebRTC>
                                <Signalling>
                                        <Port>${env:OME_SIGNALLING_PORT:3333}</Port>
                                        
                                        
                                </Signalling>
                                <IceCandidates>
                                        
                                        <TcpRelay>192.128.200.153:3478</TcpRelay>
                                        <IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>
                                </IceCandidates>
                        </WebRTC>
                </Publishers>
        </Bind>

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>

                        <Origins>
                            <Origin>
                                <Location>confidential</Location>
                                <Pass>
                                    <Scheme>rtsp</Scheme>
                                    <Urls><Url>confidential</Url></Urls>
                                </Pass>
                            </Origin>
                        </Origins>

                        
                        <Host>
                                <Names>
                                        
                                        <Name>*</Name>
                                </Names>
                                
                        </Host>

                        
                        <Applications>
                                <Application>
                                        <Name>live</Name>
                                        
                                        <Type>live</Type>
                                        <OutputProfiles>
                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>
                                                        <Encodes>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                <Image>
                                                                        <Codec>jpeg</Codec>
                                                                        <Framerate>1</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                </Image>
                                                        </Encodes>
                                                </OutputProfile>
                                        </OutputProfiles>
                                        <Providers>
                                                <OVT />
                                                <RTMP />
                                                <RTSPPull />
                                                <MPEGTS>
                                                        <StreamMap>
                                                                
                                                                <Stream>
                                                                        <Name>stream_${Port}</Name>
                                                                        <Port>4000,4001-4004</Port>
                                                                </Stream>
                                                                <Stream>
                                                                        <Name>stream_4005</Name>
                                                                        <Port>4005</Port>
                                                                </Stream>
                                                        </StreamMap>
                                                </MPEGTS>
                                        </Providers>
                                        <Publishers>
                                                <SessionLoadBalancingThreadCount>64</SessionLoadBalancingThreadCount>
                                                <StreamLoadBalancingThreadCount>64</StreamLoadBalancingThreadCount>
                                                <OVT />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                                <HLS>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </HLS>

                                                <Thumbnail>
                                                        <CrossDomains>
                                                            <Url>*</Url>
                                                        </CrossDomains>
                                                </Thumbnail>
                                                <FILE>
                                                        <RootPath>/usr/data/files/livestreams</RootPath>
                                                        <FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
                                                        <InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
                                                </FILE>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>
`

**Server (please complete the following information):**
 - OS: ubuntu linux
 - 0.12.1
 - 0.12.1

**Player (please complete the following information):**
 - Device: laptop
 - OS: windows
 - Browser chrome
 - Version 22

**Additional context**

**Comment by Keukhan** [comment]
@cmiller-nflux 

Thanks for the reporting.

Can you upload the stream information of the recorded ts file using ffprobe?

Because the video encoding option is Bypass, the pts and dts created by the encoder are saved as the same value in the recorded ts file. 

Possible cause
- Problems caused by jpeg-encoded streams in ts files
- Problem passing dts incorrectly from encoder (like OBS)

Thanks

**Comment by Keukhan** [comment]
@cmiller-nflux 

When split recording in TS, the timestamp of each file is initialized to 0, so there is a problem that it is difficult to use in HLS. 
so, we added a function to save timestamp as passthrough without initializing it.
Please uncomment the code below and try rebuilding and testing.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/publishers/file/file_session.cpp#L173
`
//  _writer->SetTimestampRecalcMode(FileWriter::TIMESTAMP_PASSTHROUGH_MODE);
`

Config file and API application will be added later.

Thanks.

**Comment by cmiller-nflux** [comment]
Thank you!
