### ISSUE TITLE
Got stuck on Getting started tutorial

### ISSUE THREAD

**Issue by rudyryk** [AirenSoft/OvenMediaEngine#467]
**Describe the bug**

I'm following the Getting started instructions but unable to get HLS output.

**To Reproduce**

1. Start OvenMediaEngine with Docker, with default configurations

```bash
docker run \
-p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333:3333 -p 3478:3478 -p 8080:8080 -p 9000:9000 -p 9999:9999/udp -p 10006-10010:10006-10010/udp \
airensoft/ovenmediaengine:latest
```

2. Send a test RTMP stream with FFMPEG:

```bash
ffmpeg -re -i sample.mp4 -c:a aac -c:v libx264 -preset fast -pix_fmt yuv420p -f flv rtmp://192.168.1.101:1935/app/stream
```

3. Wait for a while and try HLS url

```bash
curl -v http://192.168.1.101:8080/app/stream/playlist.m3u8
```

See 404 error:

```
> GET /app/stream/playlist.m3u8 HTTP/1.1
> Host: 192.168.1.101:8080
> User-Agent: curl/7.73.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Content-Type: text/html
< Server: OvenMediaEngine
```

**Expected behavior**

I'd expect to get actual playlist, according to documentation.

**Logs**
[ovenmediaengine-20210812-logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6973510/ovenmediaengine-20210812-logs.txt)

**Server (please complete the following information):**
 - OS: latest Docker image
 - OvenMediaEngine Version: OvenMediaEngine v0.12.1
 - Branch: latest Docker image

**Comment by rudyryk** [comment]
For some reason OvenMediaEngine could not handle **`High profile`** for H264, this command worked:

`ffmpeg -re -i sample.mp4 -c:a aac -c:v libx264 -profile:v main -f flv rtmp://192.168.1.101:1935/app/stream`

With High profile there's an error:

```
[2021-08-12 07:32:09.593] E [InboundWorker:95] MediaRouter | mediarouter_stream.cpp:131  | Could not parse sequence header
```

**Comment by getroot** [comment]
I missed this issue as I thought it was already resolved. But now that I read more closely, I realized that it meant that OME couldn't handle high profile. However, OME handles transmission from OBS to High profile well. Maybe this could be a different issue. Could you please provide your sample.mp4? If the file cannot be disclosed, please send it to support@airensoft.com.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
