### ISSUE TITLE
Publisher IP in stream API endpoint

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#469]
Hi,
Could you please add publisher source IP to this API endpoint?
https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/virtualhost/application/stream

**Comment by getroot** [comment]
great. It's not a difficult task, so I'll add it quickly.

**Comment by basisbit** [comment]
Please also add some way to disable this, if GDPR/CCPA/LGPD compliance is required.

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/129853742-15f97e35-5df1-4b6a-ad79-60afad8d2c8e.png)

@fcqpl 
This feature has been added to the latest master branch.

@basisbit 
I will soon add a configuration option to replace the client IP:Port information with ****** (this will apply to both logs and APIs). Could you please make this issue new?

**Comment by fcqpl** [comment]
@getroot thanks!

**Comment by getroot** [comment]
@basisbit 
I added a way to delete client's personal information from logs and API. Please refer to the following URL.

https://airensoft.gitbook.io/ovenmediaengine/v/master-1/configuration#privacyprotection
