### ISSUE TITLE
Can systemctl start ovenmediaengine but status failure

### ISSUE THREAD

**Issue by naderaa** [AirenSoft/OvenMediaEngine#47]
![image](https://user-images.githubusercontent.com/55268240/66367301-cb468d00-e9bd-11e9-959a-a49b397f846c.png)

Apologies if this seems to be a simple question. Thanks for your help

**Comment by dimiden** [comment]
@naderaa 
It's very likely caused by a misconfiguration, such as the port configuration or a typo.
Please attach the log from ```/var/log/OpenmediaEngine/OpenmediaEngine.log```.

**Comment by naderaa** [comment]
![image](https://user-images.githubusercontent.com/55268240/66370780-8e819280-e9cb-11e9-82e5-ba1bd67fac30.png)
I has replace Server.xml from https://airensoft.gitbook.io/ovenmediaengine/configuration and it's working. Thank you
