### ISSUE TITLE
WebRTC stream video freeze

### ISSUE THREAD

**Issue by 0xARK** [AirenSoft/OvenMediaEngine#471]
Hello !

I am writing this issue because I have a problem with webRTC live streaming. I think it is the server and not the player because I have tried different environments for the player and the outcome is always the same : the video sound is very smooth but the video freeze. There is a frame, then the stream freezes for ~5/10 seconds.

I didn't change anything in the "Server.xml" configuration file, except the input port for the rtmp stream (I changed it from 1935 to 1936).

**Expected behavior**
I expect a smooth video.

**Logs**
For the logs, you can see the file attached, but it seems to be no error.
[logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/6982586/logs.txt)

**Server :**
 - OS : Ubuntu 20.03
 - OvenMediaEngine Version : 0.12.1

 - Branch : master

**Player :**
 - Device : acer predator
 - OS : ubuntu 18.03
 - Browser : Brave
 - Version : I don't know, but I use a version of few months ago

If you want any other information, don't hesitate to ask me ! Thanks in advance for your time :)

**Comment by getroot** [comment]
What did you use as the encoder?
Such problems may occur if you transmit with H.264 High profile or if you do not turn off b-frame.
See the URL below.

https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder

**Comment by getroot** [comment]
Or your network may have high UDP packet loss. In that case, try playing with ws://host:port/app/stream?transport=tcp .

**Comment by 0xARK** [comment]
I use x264 as encoder, but I don't use a high profile. I have already followed recommandation with bframes, OBS is well configured. I've also tried to stream a video with ffmpeg directly from the host where is installed the ovenmedia server. Here is the command :

```
ffmpeg -stream_loop -1 -re -i bbb.mp4 -vcodec copy -c:a aac -b:a 160k -ar 44100 -strict -2 -f flv rtmp://127.0.0.1:1936/app/Achilles
```

But there is always these freeze and I don't understand why.

Your solution with UDP seems to me to be a good track, because it is true that when I stream with OBS I have ~60/70% network losses. So I tried your solution like this :

```js
let webrtcSources = OvenPlayer.generateWebrtcUrls([
                    {
                        host: 'ws://66.94.96.215:3333',
                        application: 'app',
                        stream: 'Achilles?transport=tcp',
                        label: "Low latency 1080p"
                    }
                ]);

                let player = OvenPlayer.create("player", {
                    sources: webrtcSources,
                    autoStart: true,
                    playBackRates: false
                })
```

But that didn't work either :(

**Comment by getroot** [comment]
Isn't there a loss between OBS and OME as well? (Check the status window of OBS.) If so, OME can't solve it. You have to solve for the network loss in the encoder section.

When you stream with ffmpeg you used -vcodec copy. The original video you used, bbb.mp4, may be high profile or there may be bframes.

**Comment by basisbit** [comment]
when using ffmpeg, you'll want something like this (used many times without any problems):
`-c:v libx264 -profile:v baseline -preset faster 
 -bufsize 4M -b:v 2500k -minrate 2500k -maxrate 3000k -vf scale=1920x1080
 -acodec aac -b:a 160k
 -x264-params 'keyint=60:bframes=0' -threads 8 -v 30
 -f flv rtmp://somethingsomething.server.tld/source/StreamKey`

> Your solution with UDP seems to me to be a good track, because it is true that when I stream with OBS I have ~60/70% network losses.

In that case, use SRT to stream to your OvenMediaEngine server, or set up an origin server closer to where the user is, or at a data center provider with better network peering.

**Comment by 0xARK** [comment]
Thank you all for your help, I have found it ! 

The server is 3000km away from my home, which explains the losses. 

My ffmpeg command works fine too, the problem was not from there : in the default configuration, the "transcode" section for audio was transcoding mp3 audio to opus, however the "transcode" section for video which was supposed to transcode video to vp8 format was commented out. Maybe this section should be uncommented in the default configuration in order to have a server fully ready to stream in low latency as soon as it is installed ? Here is what I changed :

```
                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>
                                                        <Encodes>
                                                                <!--<Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                <Audio>
                                                                        <Codec>opus</Codec>
                                                                        <Bitrate>128000</Bitrate>
                                                                        <Samplerate>48000</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>

                                                                <!-- I have to uncomment the following video section -->

                                                                <!--<Video>
                                                                        <Codec>vp8</Codec>
                                                                        <Bitrate>1024000</Bitrate>
                                                                        <Framerate>24</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                </Video>-->
                                                        </Encodes>
                                                </OutputProfile>
                                        </OutputProfiles>
```

Thanks again !

**Comment by basisbit** [comment]
sorry, but if enabling video transcoding "fixed" your issue, then your OBS settings / ffmpeg command was the problem 100%. Make sure you use baseline profile and b-frames=0 and keyframe interval of 2s or 1s.

**Comment by basisbit** [comment]
My recommended OBS settings for successful video streaming:
```
Video -> Output (Scaled) Resolution: your choice
Video -> FPS: 30
Stream -> Service: Custom
Output -> Output Mode: Advanced
Output -> Encoder: Intel QuickSync or AVC or Nvidia NvEnc - or if only x264 is listed, choose that. Do not use Apple encoder.
If you chose x264 above: Output -> x264 Options: "threads=8 bframes=0"
If you chose x264 above: Output -> Profile: baseline
Output -> Rescale Output: Not checked / disabled
Output -> KeyFrame Interval: 2
Output -> Bitrate: 750 Kbps for 216p resolution or 1000 Kbps for 360p resolution or 1500 Kbps for 480p or 2500 Kbps for 720p.
Output -> Rate Control: CBR
Output -> Profile: Baseline
Output -> Preset / CPU Usage Preset / Target Usage: "medium" or "slower" (better quality) or "quality" (best quality, but requires fast computer)
Output -> Audio -> Bitrate: 160 Kbps
Output -> (not available in all versions of OBS) B-Frames: 0
Advanced -> Automatically reconnect: Enabled, Retry Delay: 10s 
Advanced -> Dynamically change bitrate to reduce dropped frames: Enabled / Checked (this only works if you use rtmp video streaming)
```

**Comment by 0xARK** [comment]
> sorry, but if enabling video transcoding "fixed" your issue, then your OBS settings / ffmpeg command was definitely the problem. Make sure you use baseline profile and b-frames=0 and keyframe interval of 2s or 1s.

As you can see my obs was well configured : b-frames was at 0 and keyframe interval was set at 1
![image](https://user-images.githubusercontent.com/67783173/129720227-3028b267-6178-4c0a-9ca7-b4b40d608d0a.png)

For me the problem was not with b-frames but with the webRTC protocol which only supports vp8 as video input. What do you think about it ?

And thank you for sharing your OBS configuration ! I'll have a look at it right away to see if everything is configured as you recommend !

**Comment by basisbit** [comment]
WebRTC supports h264 as video input just fine. h264 even is the only encoding which works well on all typical devices. Only audio has to be reencoded to opus.

**Comment by 0xARK** [comment]
Oh, I was sure he only supported vp8 ! Sorry for this mistake on my part, in this case you were probably right, the problem must be at the source. 

For now it works with transcoding, but I'll try without transcoding later, using your advice. Thanks again !
