### ISSUE TITLE
CORS config for API rest endpoint

### ISSUE THREAD

**Issue by danrossi** [AirenSoft/OvenMediaEngine#472]
I see no CORS configuration for the API rest endpoint. Therefore clients are unable to call the streams endpoint for possible "conferencing". I get CORS errors.

http://localhost:8081/v1/vhosts/default/apps/app/streams

This returns publishing streams for that app / room which is doable for now and subscribe to new streams. 

A more secure encrypted payload token for the API would be nice. Here is some python methods I am using for AWS Kinesis authorizer. The payload is encrypted. The current token solution is only encoded. 

```
def createSignedToken(payload=None):
   #you can generate and export a new key here if want a different key every time.
   #import an exported key
   key = jwk.JWK(**sym_key)

   #print("\n imported key:", key.export())

   #set expiration time, when expiration time is passed in claims, expiration time will be autochecked while decrypt the token. If token expired than it will throw(automatically) the expired token exception.
   expTime = (datetime.datetime.utcnow() + datetime.timedelta(days=30, seconds=5)).timestamp()
   #print("\n expTime:", expTime)

   payloadDict = payload

   #add expiration time in user payload dict
   payloadDict['exp'] = expTime

   #print("\n\n payloadDict:", payloadDict)

   Token = jwt.JWT(header={"alg": "HS256"},
                   claims=payloadDict
                   )
   Token.make_signed_token(key)

   serializedToken = Token.serialize()
   #print("\n serializedToken:", serializedToken)

   #encrypt serialized signed token with same key
   Etoken = jwt.JWT(header={"alg": "A256KW", "enc": "A256CBC-HS512"},
                    claims=serializedToken)
   Etoken.make_encrypted_token(key)
   encryptedToken = Etoken.serialize()

   #print("\n encryptedToken:", encryptedToken)
   return encryptedToken


def decryptToken(encryptedToken = None):
   try:
       if encryptedToken:
           #import an exported key
           key = jwk.JWK(**sym_key)

           e = encryptedToken
           ET = jwt.JWT(key=key, jwt=e)
           ST = jwt.JWT(key=key, jwt=ET.claims)
           print(eval(ST.claims))
           return {"status": True, "claims": eval(ST.claims)}

   except Exception as e:
       print(e)
       return {"status": False, "message": str(e) }

```

**Comment by basisbit** [comment]
if your clients web browser get a full permission token, how do you keep users from not just using that for unwanted API requests like creating more stream keys with unlimited validity?

**Comment by danrossi** [comment]
The encrypted payload "JWE", could be unencrypted and offloaded to an auth server or script for web clients ? In my basic authorizer demo lambda I've just added check for referrer matches domain in payload. It could be anything. Is that why CORS not enabled ? It would be better than that base64 token anyway. OK. So similar scenario with Kurento. Proxy to the server api through another service , maybe a secondary websocket.

**Comment by basisbit** [comment]
these APIs imho are not designed to be used by untrusted third party clients.

**Comment by danrossi** [comment]
OK. I'll document this properly on my end and build a demo proxy service in node / python. proxy rest api or a websocket. Its for integration into a feature I've made for videojs etc. Trying to get video conferencing for OME and server side recording option.
