### ISSUE TITLE
Connection success but not able to reproduce stream

### ISSUE THREAD

**Issue by pedroSG94** [AirenSoft/OvenMediaEngine#476]
**Describe the bug**
I installed this server using docker and I'm trying to stream from my android smartphone (Oneplus 7T) using RTMP without luck.
I tried with this library:
https://github.com/pedroSG94/rtmp-rtsp-stream-client-java
To discard problems with the library I tried with two Android app downloaded from Google play:
https://play.google.com/store/apps/details?id=com.wmspanel.larix_broadcaster&gl=ES
https://play.google.com/store/apps/details?id=com.airensoft.ovenstreamencoder.camera&gl=ES

With all apps I receive connection success but I'm not able to reproduce stream using VLC, ffplay, etc.
I tried using HLS and RTMP to reproduce stream.

**Logs**
[log.zip](https://github.com/AirenSoft/OvenMediaEngine/files/7007218/log.zip)

Attached text file.
This file include run server with docker command, connect to server using rtmp-rtsp-stream-client-java library and try to reproduce stream with VLC

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - OvenMediaEngine Version: 0.12.1 (downloaded using docker command from [getting started](https://airensoft.gitbook.io/ovenmediaengine/getting-started#running-with-docker))

**Player (please complete the following information):**
Ubuntu VLC (3.0.9.2)
ffplay version 4.2.4-1ubuntu0.1

**Comment by getroot** [comment]
It looks like the bottom part of the log you sent was cut off.
If this log is all, the following process is not performed.

1. RTMP's Sequence Header could not be analyzed.

OME extracts SPS and PPS by parsing AVCDecoderConfigurationRecord from flv of RTMP. Audio also parses AACSpecificConfig.

When this is done, start the stream.

2. You said you tried to play with HLS and RTMP, but OME does not support RTMP streaming, and there is no log of trying to play with HLS as well.
Did you try to play http://host:8080/app/stream/playlist.m3u8 according to your setup? If you tried HLS playback there should be a log of failures.

3. OvenStreamEncoder is an app we made and distributed, and we are still using it in a commercial environment.

**Comment by getroot** [comment]
Ah I found the following line in your log:

[2021-08-18 12:32:37.832] E [InboundWorker:93] MediaRouter | mediarouter_stream.cpp:131 | Could not parse sequence header

The function that handles this is as follows.

https://github.com/AirenSoft/OvenMediaEngine/blob/e0a9b0640d1ff159fe6a04973d5e7cce83e13680/src/projects/modules/bitstream/h264/h264_decoder_configuration_record.cpp#L9

Which part of your rtmp-rtsp-stream-client-java is incompatible with this code? Please let me know if we violate the spec.

thank you.

**Comment by pedroSG94** [comment]
Hello,

1. Yes, I send both configurations 

2. Yes, I tried with RTMP and HLS in player side 

3. I'm testing with OvenStreamEncoder of Google play and It isn't working for me.

I will compile server with logs in that method (AVCDecoderConfigurationRecord) to know the reason because I receive this error and report you back

**Comment by getroot** [comment]
When testing with OvenStreamEncoder, send us the failed log and we will analyze it. It's probably a setting issue.

And again, OME does not support RTMP streaming output (playback). (How did you try to play it?) OME only accepts RTMP input.

**Comment by pedroSG94** [comment]
> And again, OME does not support RTMP streaming output (playback). (How did you try to play it?) OME only accepts RTMP input.

Yes, I understand it. I mean that I tried with RTMP (my fail because I didn't know it before) and HLS

**Comment by pedroSG94** [comment]
Ok, I finally found the problem. Aparently I was doing a worng value in reserved1 and reserved2 values.
I think that other servers ignore reserved values. For this reason it was working in other platforms like YouTube or Twitch and not in this one

Also, the problem related with OvenStreamEncoder is solved after re install all.
