### ISSUE TITLE
OME subscribe misses on first attempt

### ISSUE THREAD

**Issue by Thunder80** [AirenSoft/OvenMediaEngine#477]
**Describe the bug**
We are using the "latest" docker image of OME. Sometimes when we try to subscribe to a stream the ICE state is stuck on "connecting" but as soon as the page is reloaded the stream gets connected. Any ideas why this is happening?

**To Reproduce**
1. Stream to an OME server
2. Try to subscribe to the stream. (Sometimes the ICE state will be stuck on "connecting") 

**Expected behavior**
The stream should be subscribed on the first attempt.

**Logs**
[Here](https://gist.github.com/Thunder80/bcd24f356951ed6b70609309172d8dcf) is a part of the logs when the bug happened.

**Server (please complete the following information):**
 - OS: Ubuntu
 - OvenMediaEngine Version: 12.0
 - Branch: master

**Player (please complete the following information):**
 - Device: PC
 - OS: Windows 11
 - Browser: Chrome
 - Version: 92.0.4515.131

**Comment by getroot** [comment]
The log you posted shows that the RTMP connection is repeating connecting and disconnecting quickly.
For the playback of WebRTC to start, it must receive both a keyframe, SPS, and PPS. It seems that the RTMP connection is lost before that.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
