### ISSUE TITLE
Clustering: Need Help

### ISSUE THREAD

**Issue by MoZyo** [AirenSoft/OvenMediaEngine#482]
I need a more reliable setup now and I've been going back and forth the doc about Clustering but I can't seem to figure it out. Need a little assistance.

No output on Origin logs.

Desired settings: No transcoding on Edge.

[Server-Edge.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7018771/Server-Edge.txt)
[Server-Origin.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7018790/Server-Origin.txt)

Should I just delete the whole Applications bracket on Edge config?

TIA

**Comment by Classsic** [comment]
Same here! Is there an example using docker for clustering setup? 
We start a few days ago testing this project, and for now I have to say is awesome!
For now we are trying to setup pullrtsp to webrtc. 
In the docs, apparently this only is possible using origin-edge arq.
Any advance I got, I update here.

**Comment by basisbit** [comment]
Maybe this helps you:
I use docker-compose to build and run my origin and edge servers. I made a few smaller modifications to the Dockerfile to make it possible to change the configuration easily without having to rebuild the image.

Here is my docker-compose.yml: https://github.com/basisbit/OvenMediaEngine/blob/master/docker-compose.yml
My origin + edge configs can be found here: https://github.com/basisbit/OvenMediaEngine/tree/master/local-data

**Comment by basisbit** [comment]
They are implementations of standardized mechanisms for data redundancy and packet loss resilience. If you google for them, that should bring up a bunch of explanation/descriptionss.

**Comment by alnux** [comment]
Hello, I would like you to help me with the following

I have two servers,
a server with nginx (Load Balancer) and oven media engine (as origin)
IP: public
Domain: https://stream1.mydomain.com

another server with oven media engine (as edge)
IP: public
Domain: https://stream2.mydomain.com

my question is if it is possible to use the first server as origin OME with Load Balancer and the second as edge ???
How could be the configuration of twice Server's xml files?

a lot of thanks

**Comment by basisbit** [comment]
@alnux, see 3 messages above.

**Comment by alnux** [comment]
a concrete answer to the question I asked would be more interesting, becouse i want to know if that issue case is posible

really thanks

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
