### ISSUE TITLE
Multi-threading in MediaRouteApplication

### ISSUE THREAD

**Issue by rubu** [AirenSoft/OvenMediaEngine#49]
Hi, started looking at your project and it seems nice.

While trying to work on some needed changes in my fork i saw that code in `MediaRouteApplication` touches members `_streams` and `_observers` at some points without locks, but in others with locks. For example in `MediaRouteApplication::OnReceiveBuffer`  `streams.find` is called without a lock.

Is there any kind of guarantee that his is fine from the way how tasks are organized or is this a bug?

**Comment by kwonkeukhan** [comment]
Hi. rubu.
Thank you for your report.
The source code of that part is my mistake.  so, crash may occur.
I will patch soon.

**Comment by rubu** [comment]
Ok cool.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time.If you need this issue to be discussed again, please feel free to reopen it.
