### ISSUE TITLE
WebRTC to HLS

### ISSUE THREAD

**Issue by DanielnetoDotCom** [AirenSoft/OvenMediaEngine#490]
Hi

I am using the webRTC cam to transmit to a docker version of OME

it uses to work fine but for some reason, I am only getting an image like that. any idea what parameter I can tweak to improve it? is it related to a connection speed?

![image](https://user-images.githubusercontent.com/18009293/131155117-213a14c8-0d41-4514-af6b-a32f8aba8669.png)

Also here is my configurations

![image](https://user-images.githubusercontent.com/18009293/131155411-8dfe6b10-0f17-4362-8d97-23b809f678d5.png)

**Comment by mpisat** [comment]
I also experienced this issue. I used LL-Dash and WebRTC input on UDP transport. Never tried TCP transport.

**Comment by DanielnetoDotCom** [comment]
> I also experienced this issue. I used LL-Dash and WebRTC input on UDP transport. Never tried TCP transport.

I am not sure why, but TCP works better

**Comment by DanielnetoDotCom** [comment]
@mpisat is LL-dash working well?

**Comment by mpisat** [comment]
> @mpisat is LL-dash working well?

Works well if the server is close to you. I was able to use 1 sec delay with 40 ms latency, but it was unusable at 200 ms. 2 sec delay was kinda ok with 200 ms latency. However, I'm not sure if it's production-ready or not as I only tested with 1 broadcast and 1 viewer (me)

**Comment by getroot** [comment]
TCP working better means packet loss occurs when working with UDP.

And if the screen is broken, the codec setting is often the problem. (Your setting is because video is a transcoder bypass setting), check whether the H.264 baseline profile, key frame interval: 1, no b-frames settings are correct. (This is a browser limitation, not an OME limitation.)

**Comment by DanielnetoDotCom** [comment]
I guess it is a connection issue. I have the same thing running on another server and works fine.

what is the best/fastest format to restream? does it make any difference between HLS or LL-Dash? or maybe another format?

**Comment by DanielnetoDotCom** [comment]
Should I do not by pass??


                                <Video>
                                    <Bypass>true</Bypass>
                                    <Codec>vp8</Codec>
                                    <Width>1280</Width>
                                    <Height>720</Height>
                                    <Bitrate>2000000</Bitrate>
                                    <Framerate>30.0</Framerate>
                                </Video>

**Comment by DanielnetoDotCom** [comment]
I guess it was resolved here https://github.com/AirenSoft/OvenMediaEngine/issues/497#issuecomment-910691063
