### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by yisak1127** [AirenSoft/OvenMediaEngine#491]
I cant build it because it says the 'OSSL_PARAM’ was not declared in certificate.cpp line 165

projects/base/ovcrypto/certificate.cpp: In member function ‘EVP_PKEY* Certificate::MakeKey()’:
projects/base/ovcrypto/certificate.cpp:165:9: error: ‘OSSL_PARAM’ was not declared in this scope
  165 |         OSSL_PARAM params[2];
      |         ^~~~~~~~~~

**Comment by getroot** [comment]
Did you install dependencies? If so what is your OS?

https://airensoft.gitbook.io/ovenmediaengine/getting-started#install-dependencies

**Comment by yisak1127** [comment]
I was missing a dependency or too thank you for the help.
