### ISSUE TITLE
OME log show one hour less compare with local server

### ISSUE THREAD

**Issue by alnux** [AirenSoft/OvenMediaEngine#496]
hi,
OME log show one hour less compare with local server. can be it a bug??? or how can i make that ovenmediaengine.log show the same hour of the server where it is??

ovenmediaengine.log

`[2021-09-01 12:14:03.268] I [SPRtcSignalling:17411] Monitor | stream_metrics.cpp:116  | A new session has started playing #stream.tribu510.com#app/stream on the WebRTC publisher. WebRTC(2)/Stream total(3)/App total(3)`

My server date

`Wed Sep  1 13:14:19 -04 2021`

you can see that is one hour of difference

thanks

**Comment by getroot** [comment]
Hmm... I can't reproduce this problem.
What command did you use to check the server time?

**Comment by fcqpl** [comment]
I also have correct timestamp in OME logs.

**Comment by alnux** [comment]
i used **date** command on ubuntu 18.04

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
