### ISSUE TITLE
Transcode and preserver the aspect ratio Landscape and portrait

### ISSUE THREAD

**Issue by DanielnetoDotCom** [AirenSoft/OvenMediaEngine#498]
Hi

I got excellent progress, but I need to know something

If I force the transcode the Server work in most cases...

                                <Video>
                                    <Bypass>true</Bypass>
                                    <Codec>h264</Codec>
                                    <Width>1280</Width>
                                    <Height>720</Height>
                                    <Bitrate>2000000</Bitrate>
                                    <Framerate>30.0</Framerate>
                                </Video>

But if the user uses the mobile to connect and use the cam in portrait mode it forces/stretches the video to the resolution above.

Is possible to specify only the height and preserve the aspect ratio?

usually in FFmpeg, we can do this ...

`ffmpeg -i myInputFile.m3u8 -vf scale=-2:720 ... `

so it will preserve the aspect ratio

**Comment by Keukhan** [comment]
Thanks for the good comments.

Unfortunately, this feature is not currently supported. I will be adding features soon.

For example, Keep Resolution + Letter box, Keep Aspect Ratio + Auto Resize, Rotaion, etc.

I will notify you when the feature development is complete.

thank you.

**Comment by DanielnetoDotCom** [comment]
There is a way I can force the webrtc camera in landscape mode on mobile devices?

**Comment by DanielnetoDotCom** [comment]
You are totally right, the best configuration would be ....

(WebRTC) -> OME -> (HLS) -> video js player

but we have some legacy features on Nginx already, some of them I know you already implemented but let me try to describe some of them. it may bring you some ideas....

p.s. most of the nginx manual is here https://github.com/arut/nginx-rtmp-module/wiki/Directives

# 1. Control to start and stop recording a video

We can choose when to start the recording and when to stop, also when the record stops it send some information like (live key, filename, file download URL) to a predefined webhook
this webhook can also be sent when we send the on_start record control

# 2. DVR save DVR to MP4 file

We can easily set up the DVR on the hls_playlist_length parameter, for example, we can set up to keep a 1-hour hls_fragments on the server and go back and forth on the video.
I saw a similar option on yours, but for some reason, some combinations seem to not work properly

                        <HLS>
                            <SegmentDuration>5</SegmentDuration>
                            <SegmentCount>3</SegmentCount>
                            <CrossDomains>
                                <Url>*</Url>
                            </CrossDomains>
                        </HLS>

# 6. on events

currently, the most important events we have are:

- on_publish 
- on_publish_done
- on_record 
- on_record_done 

those events are very important because we use them to be able to control when someone is online or not, or when something is recording. they also send some info to predefined webhooks

the events way is much faster than request every 10 seconds the server if there is something new.

# 4. adaptive live

We can use FFMPEG to transcode the live into an adaptive bitrate, it will consume CPU but will improve a lot the buffering on video play

# 5. control header cache for m3u8 and ts files

It is important when we use a CDN to help delivery the files to clients.
for example, we usually cache the .ts files but we do not cache the .m3u8 files


I hope it helps understand. for sure if your project attend to those requirements I will migrate Nginx+RTMP to OME

FYI, this is my project https://github.com/WWBN/AVideo/

**Comment by DanielnetoDotCom** [comment]
Awesome, your project is also very good.
