### ISSUE TITLE
TCP Transport not connecting over TLS websocket with WebRTC

### ISSUE THREAD

**Issue by danrossi** [AirenSoft/OvenMediaEngine#499]
SSL cert and TLS port enabled. It does not seem to be connecting using TCP Transport. UDP seems fine. Is there another config required ?

https://demo.ovenplayer.com/demo.html#sources=%5B%7B%22id%22%3A0%2C%22label%22%3Anull%2C%22file%22%3A%22wss%3A%2F%2Fnode.panora.tours%3A3334%2Fapp%2Fstream%3Ftransport%3Dtcp%22%2C%22type%22%3A%22webrtc%22%7D%5D&lowLatency=false&liveDelay=false

**Comment by getroot** [comment]
It's not a TLS related issue.
The url below without TLS will not play either.
ws://node.panora.tours:3333/app/stream?transport=tcp
But the url below plays.
ws://node.panora.tours:3333/app/stream

For TCP transport, port 3478 must be open on the server. Check your firewall.

**Comment by yelban** [comment]
It's not firewall issue
the url below with TLS plays.
wss://node.panora.tours:**3334**/app/stream

but not the url
wss://node.panora.tours:**3334**/app/stream?transport=tcp

**Comment by getroot** [comment]
3334 is the signaling port. When using WebRTC/tcp, the port **"3478/tcp"** must be open because it relays through the TURN server.

**Comment by getroot** [comment]
See https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#webrtc-over-tcp

**Comment by yelban** [comment]
I think the port "3478/tcp" already open.

<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>

![image](https://user-images.githubusercontent.com/981381/132095332-704d1500-dfb4-4930-8f3b-3bc0751d9954.png)

**Comment by getroot** [comment]
Please upload your server.xml and ovenmediaengine.log files.  And let us know if there is anything special about your environment.  Currently, ome works well in various commercial environments.  

You can try to test here http://demo.ovenplayer.com/ome_demo.html and also https://space.ovenplayer.com/  I have the latest version of ome installed and it is streaming to webrtc/tcp.

**Comment by yelban** [comment]
Of course you can,  here is the full contents of the current Server.xml

<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	
	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		
		<Providers>
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
			</RTMP>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
			</SRT>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000-4003,4004,4005/udp}</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					
					<TLSPort>3334</TLSPort>
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006-10010/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
			</OVT>
			<HLS>
				<Port>${env:OME_HLS_STREAM_PORT:8080}</Port>
				
				<TLSPort>${env:OME_HLS_STREAM_PORT:4430}</TLSPort>
			</HLS>
			<DASH>
				<Port>${env:OME_DASH_STREAM_PORT:8080}</Port>
				
				<TLSPort>${env:OME_DASH_STREAM_PORT:4430}</TLSPort>
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					
					<TLSPort>3334</TLSPort>
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:node.panora.tours:3478}</TcpRelay>
					<IceCandidate>${env:OME_ICE_CANDIDATES:node.panora.tours:10006-10010/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>

			
			<Host>
				<Names>
					
					<Name>${env:TLS_DOMAIN_NAME:node.panora.tours}</Name>
				</Names>
				
				<TLS>
					<CertPath>/opt/certs/fullchain.pem</CertPath>
					<KeyPath>/opt/certs/privkey.pem</KeyPath>
					
				</TLS>
				
			</Host>

			

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000,4001-4004</Port>
								</Stream>
								<Stream>
									<Name>stream_4005</Name>
									<Port>4005</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<SessionLoadBalancingThreadCount>8</SessionLoadBalancingThreadCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							<UTCTiming />
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							<UTCTiming />
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
[Server.xml.zip](https://github.com/AirenSoft/OvenMediaEngine/files/7110024/Server.xml.zip)

**Comment by danrossi** [comment]
Its not my server but a client's, I instructed them to setup OME as an option and made a feature for OME in videojs. The port is open. I'll ask for config and log.

**Comment by getroot** [comment]
@danrossi 
I did some tests on the server you provided. And I found out that the server has set the domain to IceCandidate as follows.
<IceCandidate>node.panora.tours:10000-10005/udp</IceCandidate>

The browser's TURN client does not process the domain candidate. (Specifically, the TURN client does not proceed with the CreatePermission command in . This is because the domain cannot be included in XOR-PEER-ADDRESS. For more information on this, refer to the following standard document: https://www.rfc-editor .org/rfc/rfc5766.html#section-9.1)

There is no reason to use a domain for IceCandidate (please let me know if you have a specific reason), so use * or set the server's public IP. Then WebRTC/TCP will work normally.

**Comment by yelban** [comment]
@getroot  @danrossi  Thank you for your help!

It's working! After setting "OME_ICE_CANDIDATE" to an external IP.

`docker run --rm -d \
-e OME_TCP_RELAY_ADDRESS=node.panora.tours:3478 \
-e OME_ICE_CANDIDATE=167.179.82.191:10006-10010/udp ...\`
