### ISSUE TITLE
Implementing make test (unit test)

### ISSUE THREAD

**Issue by sorrowhill** [AirenSoft/OvenMediaEngine#5]
I think this is also high priority issue since we cannot assume that the application is working correctly.

Since the application doesn't have dependency with boost library, I'm not sure that using boost's uni test is the best option. there are so many header-only libraries for unit test.

If there are some tests, we would be able to build the continuous integration process.

**Comment by JehoenHan** [comment]
We are already using our own developed UNIT TEST. However, developing automated tools for external contributors is a very large project, and we want to develop it after completing high-priority tasks.

**Comment by dimiden** [comment]
For more detail, until we develop our own unit test tool, we are going to apply test tools such as Google Test or Catch.
Because I think this is important, it will be thoroughly reviewed and applied.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
