### ISSUE TITLE
API to stop a stream

### ISSUE THREAD

**Issue by catapop84** [AirenSoft/OvenMediaEngine#505]
**Is your feature request related to a problem? Please describe.**
There are cases where you need to programmatically stop a live stream. I think an API is needed for that.
Current implementation only returns information about a stream https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/virtualhost/application/stream

**Describe the solution you'd like**
Update streams API to have a DELETE http call that will remove the stream ( and kill incoming connection)

**Comment by getroot** [comment]
This is a duplicate issue. https://github.com/AirenSoft/OvenMediaEngine/issues/401

Thanks for the great ideas.
