### ISSUE TITLE
WebRTC Streaming stop working when disconnect websocket connection

### ISSUE THREAD

**Issue by XuanTung95** [AirenSoft/OvenMediaEngine#506]
Hi Oven team, 
Thanks for the awesome project and your hard work.

I'm testing with rtmp (in) and webrtc (out) with tcp transport and it works fine.
But when I try to disconnect the websocket connection to oven signaling build-in server, the stream stop.

I have a question, do we need to keep the socket alive while streaming? It had done the job sending sdp and candidates, I think we don't need it anymore.
If not, I would like the stream to keep playing with or without the socket connection.

**Comment by getroot** [comment]
The signaling session must stay connected while WebRTC is playing. 
Because OvenMediaEngine plans to exchange various information through signaling channel. Even now, if the p2p function is used in OME, peer information is exchanged through a signaling channel.

**Comment by XuanTung95** [comment]
I understand, looking forward to the exchange infomation feature.

**Comment by XuanTung95** [comment]
Another question, can I use OvenMediaEngine as a normal relay server to connect 2 peers? 
E.g. peer <--> relay server <--> peer

**Comment by getroot** [comment]
Please refer to the following URL.

WebRTC broadcast: https://airensoft.gitbook.io/ovenmediaengine/v/master/live-source/webrtc-beta

WebRTC playback:
https://airensoft.gitbook.io/ovenmediaengine/v/master/streaming/webrtc-publishing

Web conference example site created using this:
https://github.com/AirenSoft/OvenSpace
https://space.ovenplayer.com/
