### ISSUE TITLE
Can I join multiple media (screenCapture + webcam) on media server i.e., ovenmediaengine

### ISSUE THREAD

**Issue by yadavendra15** [AirenSoft/OvenMediaEngine#510]
Hi All,

First of All, Many thanks to OvenMediaEngine for building such an amazing server.

We had set up the OvenMediaEngine successfully. and now able to stream the media also. 
But now, I'm confused that how to merge the multiple media (e.g., Screen Capture + Webcam Media) on server side. Then, I want to send that single stream to the player. 
Can anyone please point me in the right direction?

Will highly appreciate your help. 

Thanks in advance!

**Comment by getroot** [comment]
If you want to develop services like zoom or google meet, they also use two players on the client end.

Merging media on the server side is very expensive and very difficult to use in a real world environment. Therefore, OME has no plans to develop such a feature in the future.

**Comment by yadavendra15** [comment]
Thanks for the suggestion.
