### ISSUE TITLE
Configuration migration tool

### ISSUE THREAD

**Issue by IanMitchell77** [AirenSoft/OvenMediaEngine#512]
When we upgrade the version it always involves manually editing the configuration files.

It would be perfect if there was a tool that checked if the config file format has changed if not it does not change but if the format has changed it migrates the old configuration automatically so it is in the correct format.

**Comment by getroot** [comment]
The format of the configuration file is hardly changed. Most of the settings are added, so it is compatible even if you use the existing settings file as it is. When going from 0.12.3 to 0.12.4 there was a name change for the settings once. (Before that, this was rarely the case.)

If the format of the existing configuration file is not compatible with the new version, we will check it by changing the version of the configuration file. And OME will print a warning. (It already has that feature, but we haven't changed the version of the configuration file for a long time.)

Migrating configuration files automatically is really difficult. It is possible to change the name, but not if the value format changes. Please understand that managing this in an open source project is not an easy task as this requires a lot of development and operational resources.

**Comment by bchah** [comment]
I recommend handling this sort of thing in your own application. It gives you the most control of the process. As an example, my application stores some parameters in its own config file and environment variables. A startup script takes a tested, known-good config file and uses sed to (re)populate the config variables, then initializes OME.

Example:

```
# Create/fetch unique key for app use
if [ ! -f /var/www/uuid ]; then
export SYSKEY=`uuidgen`
echo $SYSKEY >> /var/www/uuid
echo "System UUID: $SYSKEY"
else
export SYSKEY=`cat /var/www/uuid`
fi

if [ ! -f /opt/ovenmediaengine/bin/conf/Server.xml ]; then
sed -i "s/SYSKEY/$SYSKEY/g" /opt/ovenmediaengine/bin/conf/Server-HTTPS.xml
sed -i "s/SYSKEY/$SYSKEY/g" /opt/ovenmediaengine/bin/conf/Server-HTTP.xml

# Set default OME Server file and permissions
echo "Setting up media engine"
cp /opt/ovenmediaengine/bin/conf/Server-HTTP.xml /opt/ovenmediaengine/bin/conf/Server.xml
chown www-data:staff /opt/ovenmediaengine/bin/conf/Server.xml
fi
```

When testing a new OME release, you should run your current XML and see if it prints any errors on startup. Then modify your flags/values as required. From time to time it is good to check up on their Gitbook too - not just as a reference for breaking changes but some juicy nuggets like the recent addition of <Tcpforce>.

**Comment by getroot** [comment]
I've recently taken your comments into consideration, so I'm guiding you on compatibility in a release note. If a new version is released that is not compatible with the settings of the previous version, we will inform you in detail about this in the release notes.
