### ISSUE TITLE
WebRTC failed when cookies exists

### ISSUE THREAD

**Issue by dva-re** [AirenSoft/OvenMediaEngine#514]
**Describe the bug**
WebRTC failed when cookies exists.

**To Reproduce**
1. Example: our video host is **video-edge.example.com**, our application (not ome) host  is **app.example.com** and our auth application (also not ome) host is **auth.example.com**
2. Set multidomain cookie when auth for domain value **.example.com** (so now we can access it from app.example.com and auth.example.com both)
3. Try to start WebRTC with url wss://video-edge.example.com:3333/app/..... Websocket is eternal opening... And no open. At the log file of ome is only one line `[2021-09-20 11:07:58.906] I [SPRtcSignalling:14] HttpServer | http_server.cpp:263  | Client(<ClientSocket: 0x7fb4e0098610, #23, Connected, TCP, Nonblocking, <redacted ip>:60393>) is connected on *:3333`
4. Clear all cookies for example.com and subdomains and try again with same link. All works fine. 

**Server (please complete the following information):**
 - OS: Docker image
 - OvenMediaEngine Version: v0.12.4

**Additional context**
Thank you for your best product! But please fix this bug.

**Comment by dva-re** [comment]
don’t know if it’s important, server is running in edge mode

**Comment by getroot** [comment]
OME's WebRTC Signaling Server doesn't do any other processing just because there is a cookie. (There is no logic to handle cookies at all.)
How can I reproduce this? Please be specific.

**Comment by dva-re** [comment]
Steps: 

0. e.g. your server domain is _edge.ome-host.com_, TLSPort is 3333 for signaling, then webRTC url for oven player is wss://_edge.ome-host.com_:3333/app/test_stream_480p
1. set in your browser cookie for host `.ome-host.com`  (first dot is for multi-subdomain access for this cookie) with name `session_first_key` and value `89603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec589603bc052e1aa84ce768de06c96fec5` (any long string)
2. goto https://demo.ovenplayer.com/ and try to play wss://_edge.ome-host.com_:3333/app/test_stream_480p (in Chrome Developer Tools on Network tab it will be Pending status on webscoket connection, and then Finished. Without any messages between browser and server via websocket)
3. Delete cookies from 1-st step.
4. Try step 2 again (at least we will see `Can not create offer` in websocket messages if stream not actually exist)

P.S. While writing this, I noticed that if the value of the cookie is short length, then everything will work as it should. Perhaps there is an overflow somewhere when parsing headers.
P.P.S. On first step we can also set cookie direct for `edge.ome-host.com` to make it easier to reproduce.

**Comment by getroot** [comment]
Thanks for reporting, we will analyze this problem quickly

**Comment by dimiden** [comment]
@dva-re 
I just fixed this problem. Thank you very much! f5fb60be16ab26993c69817fb43d49cddf3ac7c4.

**Comment by dva-re** [comment]
@dimiden I am very happy, many thanks for you. Can you, please, update docker image with this bugfix ?

**Comment by getroot** [comment]
@dva-re airensoft/ovenmediaengine:dev is an image created by automatically building the master branch.

**Comment by dva-re** [comment]
@getroot I tried the :dev branch but there is now an error

`[2021-09-23 13:38:31.628] E [SPRtcSignalling:14] OpenSSL | tls.cpp:132  | Invalid TLS certificate`

When returning to: latest, there is no such error.

Has the TLS configuration config format changed?

**Comment by getroot** [comment]
@dva-re The problem will be fixed within a few hours.
https://github.com/AirenSoft/OvenMediaEngine/issues/518

**Comment by getroot** [comment]
@dva-re 
Updated ovenmediaengine:dev to fix #518 issue. Please delete the old image and download a new one.
