### ISSUE TITLE
Include required values for JSON body in API

### ISSUE THREAD

**Issue by yannickboy15** [AirenSoft/OvenMediaEngine#515]
**Describe the bug**
Include the required parameters for the API

**To Reproduce**
1. do a POST request to /v1/vhosts/YOUR_VIRTUALHOST_NAME/apps
2. Give some standard values in for a new application. I used the following JSON Body in my POST request:
```
[{
    "name": "test",
    "type": "live",
    "outputProfiles": [
      {
        "name": "bypass_profile",
        "outputStreamName": "${OriginStreamName}",
        "encodes": {
          "videos": [
            {
              "bypass": true
            }
          ],
          "audios": [
            {
              "bypass": true
            }
          ]
        }
      }
    ],
    "providers": {
        "mpegts": {}
    },
    "publishers": {
        "appWorkerCount": "1",
        "streamWorkerCount": "8",
        "hls": {
            "segmentDuration": "5",
            "segmentCount": "10",
            "crossDomains": {
                "url": [
                    "*"
                ]
            }
        }
    }
}] 
```
3. Start streaming to your newly created application
4. Error: 

`[2021-09-20 15:17:47.111] E [SPRTMP-T1935:37] PushProvider | provider.cpp:34   | Cannot find application(#livestreams#test) to publish interleaved channel`

`[2021-09-20 15:17:47.111] E [SPRTMP-T1935:37] RTMPProvider | rtmp_stream.cpp:1162 | Input create fail -  stream(#livestreams#test/stream)`

**Expected behavior**
A required fields page, where a standard application can be made and streaming will work instantly on creation.

**Server (please complete the following information):**
 - OS: Windows 10 PRO, using Docker with Linux Containers
 - OvenMediaEngine Version: Latest
 - Branch: Master

**Additional context**
It's a bug and feature request in 1, as it gives an issue if you post something like above randomly, but with required fields mentioned in the docs it'll fix the issue.

**Comment by getroot** [comment]
I haven't reproduced this yet, but you only set mpegts in providers. Wouldn't it be necessary to set up RTMP?

**Comment by yannickboy15** [comment]
It would, but doesn't RTMP initialize empty if you do not mention it or was that a wrong assumption by myself. Often if it's optional, it's initialized without any values so it's not considered null. Hence I thought this was the case here too not mentioning it in the POST call.

When I include the RTMP it indeed works. Maybe it'd be a suggestion to mention this in the documentation, so optional is not misinterpretended. (Due to the use of optional in different languages, different idea's behind an optional)

Thanks!
