### ISSUE TITLE
OvenMediaEngine crashes without any log if streaming by Wirecast

### ISSUE THREAD

**Issue by ZloyDyadka** [AirenSoft/OvenMediaEngine#53]
OvenMediaEngine crashes without any log if streaming by Wirecast

OvenMediaEngine builded by temp/alpine dockerfile

```
Run command:
docker run -d \                                                                    
-e OME_VIDEO_BITRATE=200000 -e OME_VIDEO_WIDTH=854 -e OME_VIDEO_HEIGHT=480 \
-p 1935:1935 -p 3333:3333 -p 80:80 -p 9000:9000/udp -p 10000-10005:10000-10005/udp ovenmediaserver:latest
```

Small bencmark
```
Wirecast
h264: High Profile
Preset: veryfast
Video Track #0: codec(1, avc) resolution(854x480) framerate(30.00fps) timebase(1/90000)
Audio Track #1: codec(5, aac) samplerate(48000) format(s16, 16) channel(stereo, 2) timebase(1/48000)

Result:
CPU: 300%
Bitrate: 1153k


OBS
h264: High Profile
Preset: veryfast
Video Track #0: codec(1, avc) resolution(1152x720) framerate(30.00fps) timebase(1/90000)
Audio Track #1: codec(5, aac) samplerate(44100) format(s16, 16) channel(stereo, 2) timebase(1/44100)

Result:
CPU: 150%
Bitrate: 2600k
```

**Comment by ZloyDyadka** [comment]
But if change the profile of h264 to baseline, it uses 150 percent of the CPU and not crashes for more than 10 minutes

**Comment by dimiden** [comment]
@ZloyDyadka 
I would appreciate it if you could use the ```docker exec``` command to enter the docker container and attach the crash and logs files inside the ```/opt/openmediaengine/bin``` folder.

**Comment by ZloyDyadka** [comment]
@dimiden https://pastebin.com/eUaQzSZA
I resolved the issue, OvenMediaEndine crashes because docker killed him by OOM. 
```
2019-11-20 11:49:46.165159+0300  localhost com.docker.hyperkit[55302]: [377002.007251] oom_reaper: reaped process 95129 (OvenMediaEngine), now anon-rss:0kB, file-rss:4kB, shmem-rss:0kB
2019-11-20T11:49:46.212189800+03:00 container die 533ab8b311cb3eed6dc48645b6fc91ed24b1ccca40fb2fba353a112115570a8c (exitCode=137, image=ovenmediaserver:latest, name=objective_ellis)
```
But wirecast traffic overloads OvenMediaEngine, this is a reason for a new issue
```
PID    COMMAND      %CPU      TIME     #TH    #WQ   #PORTS MEM    PURG   CMPRS  PGRP  PPID  STATE
55302  com.docker.h 320.4     15:57:18 17/3   0     41     7947M+ 0B     1055M- 55295 55298 running
```

**Comment by dimiden** [comment]
@ZloyDyadka 
First of all, if the CPU usage is 300% despite the lower resolution, you may be using a lot of motion video.
If you've tested with the same video and the CPU usage between Wirecast and OBS is significantly different, please tell me again.

And, "Decoded frame queue is full, please check your system" log occurs when system performance is insufficient. When this happens, the queue grows in size and takes up a lot of memory, which can eventually cause problems.

**Comment by ZloyDyadka** [comment]
@dimiden, I streamed the same content from OBS and Wirecast. In the case of Wirecast, even with a static picture as a content, there was a large CPU consumption (but if change the profile of h264 to baseline, it uses 150 percent of the CPU)

**Comment by dimiden** [comment]
@ZloyDyadka 
If it works well when you change the profile to baseline, it seems that the server is using more CPU resources to handle b-frame.
There may be other reasons, so I'll try Wirecast later and talk to you again.

Thank you for your report!

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
