### ISSUE TITLE
WebRTC JitterBuffer

### ISSUE THREAD

**Issue by llspalex** [AirenSoft/OvenMediaEngine#530]
I checked the docs but am still not quite understanding what the new JitterBuffer function introduced in 12.6 does. Under what circumstances would it be required, and does turning it on affect CPU usage? I personally have never experienced A/V sync issues using the WebRTC Publisher but wonder if turning on JitterBuffer would act as a sort of safety net.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
