### ISSUE TITLE
HLS streaming not working on 0.12.6 in cluster

### ISSUE THREAD

**Issue by Adam1901** [AirenSoft/OvenMediaEngine#532]
**Describe the bug**

**To Reproduce**
1. Set Server.xml as follows 'TBC'
2. With Encoder 'NVENC..' [e.g. Use OBS Version] 27.0.1 
3. See error

**Expected behavior**

It appears the edge isnt able to pull the HLS stream from the origin and the origin logs are mostly clear. 
It could be cors related but I'm unable to post the logs or server.xml today (its late). I will post the tomorrow is someone doesnt get there first.

HLS stream with the same server.conf's works perfectly deployed docker locally & docker on ecs on 0.12.5.
No changes to anything apart from the version upadate

**Logs**

I will post the tomorrow is someone doesnt get there first.

**Server (please complete the following information):**
 - OS: [e.g. iOS] DOCKER
 - OvenMediaEngine Version: [e.g. v0.10.1] 0.12.6
 - Branch: [e.g. dev] Master

**Player (please complete the following information):**
 - Device: [e.g. iPhone 8] All
 - OS: [e.g. iOS8.1] All
 - Browser [e.g. stock browser, safari] All

**Additional context**

**Comment by getroot** [comment]
We're still playing HLS on Edge just fine. I think it's an issue related to CORS. Please let me know if the related issue is analyzed in more detail.

**Comment by Adam1901** [comment]
#621
