### ISSUE TITLE
RTMP pull

### ISSUE THREAD

**Issue by streamthing** [AirenSoft/OvenMediaEngine#536]
Can you add RTMP pull for OME server?
https://airensoft.gitbook.io/ovenmediaengine/live-source/rtsp-pull-beta
This will be bandwidth saver for our servers.
We are using only WebRTC in OME.

**Comment by getroot** [comment]
Please describe your use case in detail.
Are there any servers that only support RTMP streaming? Doesn't that streaming server support RTSP? If a lot of people want this, I'll add it to our Backlog.

**Comment by mpisat** [comment]
+1 for rtmp pull. It would be great if it could be done via REST API.

**Comment by getroot** [comment]
This is a duplicate issue with #42, so I'm closing this issue. I will prioritize this feature. But we are so busy these days that we can implement this feature by the start of 2022.
