### ISSUE TITLE
REST API cannot add object to Application call

### ISSUE THREAD

**Issue by Yannick-DG** [AirenSoft/OvenMediaEngine#537]
**Describe the bug**
Back in 0.12.5 we've done REST API calls just fine with a premade POST Body. Now when we try this in 0.12.7, this somehow broke. This is the following error we receive:

`[
    {
        "message": "application.outputProfiles.outputProfile is not an object",
        "statusCode": 400
    }
]`

**To Reproduce**
1. Do a POST request to http://URLHERE/v1/vhosts/livestreams/apps
2. Post the following body in the request:

```
[{
    "name": "yannick-test",
    "type": "live",
    "outputProfiles": [
      {
        "name": "bypass_profile",
        "outputStreamName": "${OriginStreamName}",
        "encodes": {
          "videos": [
            {
              "bypass": true
            }
          ],
          "audios": [
            {
              "bypass": true
            },
            {
                "active": true,
                "bitrate": "128000",
                "channel": 2,
                "codec": "opus",
                "samplerate": 48000
            }
          ]
        }
      }
    ],
    "providers": {
        "mpegts": {},
		"rtmp": {}
    },
    "publishers": {
        "appWorkerCount": "1",
        "streamWorkerCount": "8",
        "hls": {
            "segmentDuration": "5",
            "segmentCount": "10",
            "crossDomains": {
                "url": [
                    "*"
                ]
            }
        }
    }
}]
```

3. See error

**Expected behavior**
A 200 with the response of the exact same body.

**Logs**
Not sure where to find it in my Docker environment, but this is what I got from my console, see attachment.
[_OvenMediaEngine_origin.1.ukprb708dwq42ntlacx0ui74r_logs.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7382899/_OvenMediaEngine_origin.1.ukprb708dwq42ntlacx0ui74r_logs.txt)

**Server (please complete the following information):**
 - OS: Ubuntu 18.04, Azure VM
 - OvenMediaEngine Version: [v0.12.7
 - Branch: Release branch

**Additional context**

**Comment by getroot** [comment]
There has been a change in the specification of the API recently, but we forgot to update it in the manual. I'll add this to the manual soon and comment again. Thanks for reporting the problem.
