### ISSUE TITLE
[Documentation] Incorrect example for policy format in Signed Policy gitbook page

### ISSUE THREAD

**Issue by zygocact** [AirenSoft/OvenMediaEngine#539]
Hello.
The [policy examples in gitbook tutorial](https://airensoft.gitbook.io/ovenmediaengine/access-control/signedpolicy#policy) show a Unix epoch with 10 digit values. OME will reject a policy with 10 digit epoch time, and expects a 13 digit Unix epoch time.

Additionally, the Signed Policy tutorial page could use some clarification about how to generate a client/viewer address. Without having a web development background, it took me a while to figure out that I must generate a signature for the viewer address as well, as it was not explicitly stated that I must do so, and no examples were given.

**Comment by FrnandMG** [comment]
"OME will reject a policy with 10 digit epoch time, and expects a 13 digit Unix epoch time." I finally made it work. Thanks for the info

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
