### ISSUE TITLE
Problem with connection in iOS and chrome browser

### ISSUE THREAD

**Issue by vasudevavarun** [AirenSoft/OvenMediaEngine#54]
Hello,

I'm not able to play video on OvenMediaPlayer in iOS devices and chrome.
Few seconds after the video starts the OME crashes with the following error.

> [11-19 17:56:50.289] I 28646 HttpServer | http_server.cpp:111  | Client(<ClientSocket: 0x7f5e98000910, #19, state: 4, TCP, [v4] 192.168.2.10:49285>) is connected on [v4] 0.0.0.0:3333
> [11-19 17:56:50.291] I 28646 Signalling | rtc_signalling_server.cpp:68   | New client is connected: <ClientSocket: 0x7f5e98000910, #19, state: 4, TCP, [v4] 192.168.2.10:49285>
> [11-19 17:56:50.441] W 28646 SDP | session_description.cpp:252  | Unknown Attributes : a=group:BUNDLE hstwzG SFrCNs
> [11-19 17:56:55.506] E 28646 Socket | socket_address.cpp:266  | An error occurred while resolve DNS for host [69a886f6-9a21-427e-bb6f-30755296caba12.local]
> [11-19 17:56:55.507] E 28646 Assertion | socket_address.cpp:77   | Assertion failed: projects/base/ovsocket/socket_address.cpp:77
>         Expression: result
> [11-19 17:56:55.718] I 13520 Config | config_manager.cpp:44   | Trying to load configurations... (/root/OvenMediaEngine/src/bin/DEBUG/conf/Server.xml)
> [11-19 17:56:55.735] I 13520 OvenMediaEngine | main.cpp:80   | OvenMediaEngine v0.1.1 (build: 18062600) is started on [lowlatency] (Linux x86_64 - 3.10.0-693.el7.x86_64, #1 SMP Tue Aug 
> [11-19 17:56:55.745] I 13520 OvenMediaEngine | main.cpp:118  | Trying to create application [app] (live)...
> [11-19 17:56:55.745] I 13520 OvenMediaEngine | main.cpp:125  | Trying to create MediaRouter for host [default]...
> [11-19 17:56:55.745] I 13520 MediaRouter | media_router.cpp:39   | Trying to start media router...
> [11-19 17:56:55.746] I 13520 MediaRouter | media_router.cpp:61   | Media router is started.
> [11-19 17:56:55.746] I 13520 OvenMediaEngine | main.cpp:128  | Trying to create Transcoder for host [default]...
> [11-19 17:56:55.746] I 13520 OvenMediaEngine | main.cpp:135  | Trying to create RTMP Provider for application [app]...
> [11-19 17:56:55.747] I 13520 OvenMediaEngine | main.cpp:151  | Trying to create WebRTC Publisher for application [app]...
> [11-19 17:56:55.748] I 13520 Publisher | publisher.cpp:12   | Trying to start publisher 1 for application: app
> [11-19 17:56:55.749] I 13520 WebRTC | rtc_application.cpp:104  | WebRTC Application Started
> [11-19 17:56:55.900] W 13527 Ice | ice_port.cpp:317  | Could not find client information. 
> Dropping...

Disabling chrome://flags/#enable-webrtc-hide-local-ips-with-mdns worked,

It acts as a temporary resolution for chrome browser but impossible to replicate in production environment as it is a client side configuration. The issue in iOS devices remain exact.

**Systems Used**
**Server**:
Centos 7.4 64bit
CPU: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
RAM: 16G

**Client**:
iPAD 6th gen 9.7"
OS: 13.1.13

Thanks

**Comment by dimiden** [comment]
@vasudevavarun 
An exception occurred in the SocketAddress class when M-DNS was turned on, and I think the master branch code was probably used.

This exception is intended to help developers identify unforeseen circumstances, and there are two ways to bypass or resolve this issue.

1) Build in release mode to avoid this assertion.
2) As it was modified in the latest version, check out the contents of the dev brand and build it.

**Comment by vasudevavarun** [comment]
Hi @dimiden 
I've tried building dev branch but surprisingly it is not responding to my PKG_CONFIG_PATH, While if I checkout master the same environment variables works without any issue.
I'm getting the following error  while compiling "dev" branch


> [root@localhost src]# PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/local/AV/lib/pkgconfig" make -j8
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package libavformat was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavformat.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavformat' found
> Package libavformat was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavformat.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavformat' found
> Package libavformat was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavformat.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavformat' found
> Package libavfilter was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavfilter.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavfilter' found
> Package libavfilter was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavfilter.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavfilter' found
> Package libavfilter was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavfilter.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavfilter' found
> Package libavcodec was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavcodec.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavcodec' found
> Package libavcodec was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavcodec.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavcodec' found
> Package libavcodec was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavcodec.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavcodec' found
> Package libswresample was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswresample.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswresample' found
> Package libswresample was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswresample.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswresample' found
> Package libswresample was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswresample.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswresample' found
> Package libswscale was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswscale.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswscale' found
> Package libswscale was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswscale.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswscale' found
> Package libswscale was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswscale.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswscale' found
> Package libavutil was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavutil.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavutil' found
> Package libavutil was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavutil.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavutil' found
> Package libavutil was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavutil.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavutil' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package vpx was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vpx.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vpx' found
> Package vpx was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vpx.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vpx' found
> Package vpx was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vpx.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vpx' found
> Package opus was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opus.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opus' found
> Package opus was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opus.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opus' found
> Package opus was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opus.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opus' found
> Package libsrtp2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libsrtp2.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libsrtp2' found
> Package libsrtp2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libsrtp2.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libsrtp2' found
> Package libsrtp2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libsrtp2.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libsrtp2' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package openssl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `openssl.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'openssl' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package libavformat was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavformat.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavformat' found
> Package libavformat was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavformat.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavformat' found
> Package libavformat was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavformat.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavformat' found
> Package libavfilter was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavfilter.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavfilter' found
> Package libavfilter was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavfilter.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavfilter' found
> Package libavfilter was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavfilter.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavfilter' found
> Package libavcodec was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavcodec.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavcodec' found
> Package libavcodec was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavcodec.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavcodec' found
> Package libavcodec was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavcodec.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavcodec' found
> Package libswresample was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswresample.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswresample' found
> Package libswresample was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswresample.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswresample' found
> Package libswresample was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswresample.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswresample' found
> Package libswscale was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswscale.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswscale' found
> Package libswscale was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswscale.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswscale' found
> Package libswscale was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libswscale.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libswscale' found
> Package libavutil was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavutil.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavutil' found
> Package libavutil was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavutil.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavutil' found
> Package libavutil was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libavutil.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libavutil' found
> Package vpx was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vpx.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vpx' found
> Package vpx was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vpx.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vpx' found
> Package vpx was not found in the pkg-config search path.
> Perhaps you should add the directory containing `vpx.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'vpx' found
> Package opus was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opus.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opus' found
> Package opus was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opus.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opus' found
> Package opus was not found in the pkg-config search path.
> Perhaps you should add the directory containing `opus.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'opus' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> Package srt was not found in the pkg-config search path.
> Perhaps you should add the directory containing `srt.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'srt' found
> ####################################################
> #                                                  #
> #           AirenSoft Make System v0.63            #
> #                                                  #
> ####################################################
>    - Operating system        : linux
>    - Core count              : 8
>    - GCC version             : 7.3.1
>    - Build option            : DEBUG
>    - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
>    - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig
>    - Total Projects count    : 27
> 
> [ 1/97|  1%] Preparing directories...
> [ 2/97|  2%] [static] Linking libconfig.a... => intermediates/DEBUG/static/libconfig.a
> [ 3/97|  3%] [executable] OvenMediaEngine: C++ projects/main/main.cpp => intermediates/DEBUG/objs/main/main.o
> [ 4/97|  4%] [static] Linking libtranscoder.a... => intermediates/DEBUG/static/libtranscoder.a
> [ 5/97|  5%] [static] librtc_signalling.a: C++ projects/rtc_signalling/rtc_signalling_server.cpp => intermediates/DEBUG/objs/rtc_signalling/rtc_signalling_server.o
> [ 6/97|  6%] [static] librtc_signalling.a: C++ projects/rtc_signalling/p2p/rtc_p2p_manager.cpp => intermediates/DEBUG/objs/rtc_signalling/p2p/rtc_p2p_manager.o
> [ 7/97|  7%] [static] librtc_signalling.a: C++ projects/rtc_signalling/p2p/rtc_peer_info.cpp => intermediates/DEBUG/objs/rtc_signalling/p2p/rtc_peer_info.o
> [ 8/97|  8%] [static] libjsoncpp.a: C++ projects/third_party/jsoncpp-1.8.4/jsoncpp.cpp => intermediates/DEBUG/objs/third_party/jsoncpp-1.8.4/jsoncpp.o
> [ 9/97|  9%] [static] librelay.a: C++ projects/relay/relay_client.cpp => intermediates/DEBUG/objs/relay/relay_client.o
> [10/97| 10%] [static] librelay.a: C++ projects/relay/relay_server.cpp => intermediates/DEBUG/objs/relay/relay_server.o
> [11/97| 11%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/ulpfec_generator.cpp => intermediates/DEBUG/objs/rtp_rtcp/ulpfec_generator.o
> [12/97| 12%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/rtp_packetizing_manager.cpp => intermediates/DEBUG/objs/rtp_rtcp/rtp_packetizing_manager.o
> [13/97| 13%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/rtp_rtcp.cpp => intermediates/DEBUG/objs/rtp_rtcp/rtp_rtcp.o
> [14/97| 14%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/rtcp_packet.cpp => intermediates/DEBUG/objs/rtp_rtcp/rtcp_packet.o
> [15/97| 15%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/red_rtp_packet.cpp => intermediates/DEBUG/objs/rtp_rtcp/red_rtp_packet.o
> [16/97| 16%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/rtp_packetizer_vp8.cpp => intermediates/DEBUG/objs/rtp_rtcp/rtp_packetizer_vp8.o
> [17/97| 17%] [static] librtp_rtcp.a: C++ projects/rtp_rtcp/rtp_packet.cpp => intermediates/DEBUG/objs/rtp_rtcp/rtp_packet.o
> projects/main/main.cpp: In function ‘int main(int, char**)’:
> projects/main/main.cpp:167:18: error: ‘srt_logging’ has not been declared
>   srt_setloglevel(srt_logging::LogLevel::debug);
>                   ^~~~~~~~~~~
> compilation terminated due to -Wfatal-errors.
> make: *** [core/build_objects.mk:21: intermediates/DEBUG/objs/main/main.o] Error 1
> make: *** Waiting for unfinished jobs....

**Comment by dimiden** [comment]
@vasudevavarun 
To avoid conflicts with existing installed libraries, we have modified the dev branch not to use the PKG_CONFIG_PATH and LD_LIBRARY_PATH.
These fixes have been applied to the Makefile and prerequisites, so please run misc/prerequisites.sh again to use the dev branch.

**Comment by vasudevavarun** [comment]
> @vasudevavarun
> To avoid conflicts with existing installed libraries, we have modified the dev branch not to use the PKG_CONFIG_PATH and LD_LIBRARY_PATH.
> These fixes have been applied to the Makefile and prerequisites, so please run misc/prerequisites.sh again to use the dev branch.

Thank you so much.
I've compiled the 'dev' branch and it not having any issue with the devices.
