### ISSUE TITLE
Receive RTMPS stream

### ISSUE THREAD

**Issue by sandman72** [AirenSoft/OvenMediaEngine#540]
The Ultrastream hardware encoders work really well with Base/Main profiles streaming into OME with RTMP as transport. They also support sending RTMPS streams via TLS and I was wondering if there is any support in OME to accept these RTMPS streams directly? That would make things a lot easier to secure.

Alternatives would be to use nginx or stunnel to accept a TLS RTMPS stream and send a plain RTMP stream to OME locally.

(untested) stunnel config:
<pre>[rtmps]
accept = 1936
connect = 127.0.0.1:1935
cert=/etc/letsencrypt/live/rtmp.example.com/fullchain.pem
key=/etc/letsencrypt/live/rtmp.example.com/privkey.pem
</pre>
or (untested) nginx config:
<pre>stream {
    upstream publish {
        server 127.0.0.1:1935;
    }
    server {
        listen 1936 ssl;        # additional port for publishing
        proxy_pass publish;
        ssl_certificate /etc/letsencrypt/live/rtmp.example.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/rtmp.example.com/privkey.pem;
        allow 192.0.2.1;        # allow publish from this IP
        deny all;               # deny publish from the rest
    }
}
</pre>
![nginx_rtmps_tunnel](https://user-images.githubusercontent.com/26872898/138153341-b05ef8b5-38f1-4e89-9d88-d44f0ff13925.png)

**Comment by getroot** [comment]
We have no plans to support RTMPS. That's because we have to put a lot of resources into it, RTMP is becoming obsolete, and there are great alternatives like SRT or WebRTC.

**Comment by getroot** [comment]
This will be discussed further in #315. Thanks for the good suggestion.
