### ISSUE TITLE
WebRTC provider -> publisher playback issue on v0.12.7-21-gfdce9098

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#544]
**Describe the bug**
When sending in a WebRTC provider, playback does not begin client-side and the OME log is filled with this error:

`E [SPICE-T3478:1109] RtpRtcp | rtp_rtcp.cpp:289  | Could not find track info for track ID 0`

**To Reproduce**
In my testing, I am using OvenLiveKit and the TCPForce option is set to true.

**Expected behavior**
I have been using build v0.12.6-4-ge9b9ceb2 for some time and it is not exhibiting any of these issues.

**Logs**
[ome_log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7419071/ome_log.txt)

**Server (please complete the following information):**
 - OvenMediaEngine Version: v0.12.7-21-gfdce9098

**Player (please complete the following information):**
Observed in Safari and Chrome with OvenPlayer

**Comment by getroot** [comment]
I know you're busy, but please check to see if your problem has been resolved. If the issue is resolved, please close the issue.

**Comment by bchah** [comment]
@getroot So sorry I forgot to close this one! Yes, it works beautifully 🥇🥇🥇
