### ISSUE TITLE
WebRTC Publisher Bug v0.12.7 Release

### ISSUE THREAD

**Issue by Morpheus235** [AirenSoft/OvenMediaEngine#545]
**Describe the bug**
The WebRTC Provider does not seem to listen to Requests when being used on the same Port as the WebRTC Publisher (443).
Using different Ports for each results in both working flawlessy otherwise only the Publisher works. No logs or any mention of the send stream being handled in any way is being emitted

**To Reproduce**
Configure Ove to use TLS Port 443 for Signalling for both webrtc Publisher and Provider

**Expected behavior**
Stream is able to be send via the same Port as Publisher

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: v0.12.7
 - Branch: Release

**Comment by getroot** [comment]
please upload your Server.xml and entire ovenmediaengine.log file so that others can repoduce this problem easily.

**Comment by Morpheus235** [comment]
[ovenmediaengine.log.20211030.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7445374/ovenmediaengine.log.20211030.txt)
[Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7445375/Server.txt)

had to Clean the log and config (domains, secrets ,etc) as this is a public facing system

**Comment by getroot** [comment]
This is probably due to the same Thumbnail port. Can you try changing the Thumbnail port to another port?
We will also modify the Thumbnail to use the same port.

**Comment by Keukhan** [comment]
@Morpheus235 

A few minutes ago, we improved Thumbnail publisher to use the same port as other publishers.
Test it with the latest version.

Thanks.

**Comment by Morpheus235** [comment]
@Keukhan Tested the changes and everything seems to be working fine regarding this issue.
