### ISSUE TITLE
statistics log file not creted

### ISSUE THREAD

**Issue by mcp11** [AirenSoft/OvenMediaEngine#549]
In /var/log/ovenmediaengine/ the statistics files like ovenmediaengine_webrtc_stat.log are missing. Only ovenmediaengine.log is created.

**To Reproduce**
1. Set Logger.xml as follows:

```
<Logger version="2">
	<!-- Log file location -->
	<Path>/var/log/ovenmediaengine</Path>
	<!-- Log level: [debug, info, warn, error, critical] -->
	<Tag name=".*" level="debug" />
</Logger>
```

**Expected behavior**
A file /var/log/ovenmediaengine/ovenmediaengine_webrtc_stat.log should be created

**Server:**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: 0.12.6

I followed these instructions: https://airensoft.gitbook.io/ovenmediaengine/logs-and-statistics

**Comment by getroot** [comment]
This log existed for a specific purpose and was recently deprecated. But I didn't update the manual by my mistake. thank you for telling me. Currently, there is no log for statistics, and statistics information can be collected using the REST API.
A new feature for stats is currently under development and I think we will be able to introduce it in the first half of next year.
thank you for telling me. I will update the documentation.
