### ISSUE TITLE
Multi-threading issue in MediaRouteStream

### ISSUE THREAD

**Issue by rubu** [AirenSoft/OvenMediaEngine#55]
Just patched everything to run OvenMediaEngine on MacOS - and it segfaults with a trivial RTMP provider setup. 

The crash happens since `_queue` in MediaRouteStream is touched without a mutex in Push/Pop methods. Adding a mutex for the queue access works, but I am actually quite amazed that this has not been reported by anyone else.

**Comment by kwonkeukhan** [comment]
Hello, rubu. 

Thank you for your report.
The bug will be reflected in the next release.

Hope you're having a greay day.

**Comment by rubu** [comment]
Thanks, I'll live my local branch for now and when you have the next release will try to merge stuff together.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time.If you need this issue to be discussed again, please feel free to reopen it.
