### ISSUE TITLE
API Rest call getting Controller not found

### ISSUE THREAD

**Issue by Zinelaabidine** [AirenSoft/OvenMediaEngine#551]
**Describe the bug**
When I call the REST-API I get 
{
    "message": "Controller not found (404)",
    "statusCode": 404
}

Any thought on this?

**Comment by getroot** [comment]
I think you accessed the wrong URL

**Comment by Zinelaabidine** [comment]
I called this URLs, which i got from the API documentation
/v1/vhost/default/apps
/v1/vhosts/default

**Comment by getroot** [comment]
I saw your question and checked the API once again. I have confirmed that it works well as shown in the screenshot below.

Comment the version of OvenMediaEngine you used, Server.xml, OveMediaEngine.log and the URL you used to call the API and I'll check what you're using wrong.

![image](https://user-images.githubusercontent.com/17779085/140849991-8385ae61-ecf1-4fcf-9c02-1c011128c712.png)
![image](https://user-images.githubusercontent.com/17779085/140850009-de8fa180-6f5c-4a05-bf04-77fc56d90436.png)
![image](https://user-images.githubusercontent.com/17779085/140850020-13609834-2dc8-4d7c-849b-da874876eab9.png)
![image](https://user-images.githubusercontent.com/17779085/140850036-9e3f78ed-8a68-4ab6-ab03-272c5bbb84de.png)
![image](https://user-images.githubusercontent.com/17779085/140850051-4a4fb465-01a8-4dcf-ac9e-7f75f16756b5.png)
![image](https://user-images.githubusercontent.com/17779085/140850068-fad43345-7c38-4a89-bb2c-d006f07ca623.png)

**Comment by getroot** [comment]
You must have called the API the wrong way or set it up wrong. It could be a CORS error or a mixed content issue.

Comments like "Still not working!" do nothing to solve the problem. Please provide all information so that your problem can be reproduced by someone else. Managing this open community requires a lot of effort. Please help me to keep this going.
