### ISSUE TITLE
WebRTC --> WebRTC,   Could not find the stream && Could not find Origin for the stream

### ISSUE THREAD

**Issue by Zinelaabidine** [AirenSoft/OvenMediaEngine#552]
Hi, 

I am streaming from WebRTC source and WebRTC receiver.
I deployed OME on ubuntu 20.04.
I have configure it with SSL certificate in my domain.

When I was trying to stream from the Source Camera ( Firefox ) using this URL wss://www.mywebsite.website:3334/app/test 
the web browser throw this error. 
**Web Socket is closed. The connection was closed abnormally, e.g., without sending or receiving a Close control frame**

the application OME throw this error 
**[11-09 22:12:50.871] I [SPRtcSignalling:461808] Signalling | rtc_signalling_server.cpp:201  | New client is connected: <ClientSocket: 0x7f3a540014e0, #25, Connected, TCP, Nonblocking, 82.130.35.225:55930>
[11-09 22:12:50.874] E [SPRtcSignalling:461808] Orchestrator | orchestrator.cpp:479  | Could not find Origin for the stream: [#default#app/test]
[11-09 22:12:50.874] E [SPRtcSignalling:461808] WebRTC Publisher | webrtc_publisher.cpp:440  | Cannot find stream (#default#app/test)
[11-09 22:12:50.874] E [SPRtcSignalling:461808] Signalling | rtc_signalling_server.cpp:292  | Cannot find stream [#default#app/test]
[11-09 22:12:50.875] I [SPRtcSignalling:461808] Signalling | rtc_signalling_server.cpp:335  | Client is disconnected: <WebSocketClient: 0x7f3a54003830, <ClientSocket: 0x7f3a540014e0, #25, Closed, TCP, Nonblocking, 82.130.35.225:55930>> (#default#app / test, ufrag: local: (N/A), remote: (N/A))**

Here is my Server.xml

`<?xml version="1.0" encoding="UTF-8" ?>
<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	
	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		
		<Managers>
			<API>
				<Port>${env:OME_API_PORT:8081}</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>

		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000/udp}</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					
					<TLSPort>3334</TLSPort>
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<HLS>

				<Port>${env:OME_HLS_STREAM_PORT:8080}</Port>
				<WorkerCount>1</WorkerCount>
				
				
			</HLS>
			<DASH>
				<Port>${env:OME_DASH_STREAM_PORT:8080}</Port>
				<WorkerCount>1</WorkerCount>
				
				
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					
					<TLSPort>3334</TLSPort>
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			<TLS>
				<CertPath>/home/ubuntu/relieve/relieve-certificate.cer</CertPath>
				<KeyPath>/home/ubuntu/relieve/relieve-key.key</KeyPath>
				<ChainCertPath>/home/ubuntu/relieve/relieve-certificate_inter.cer</ChainCertPath>
			</TLS>
		</Host>
		<API>
			<AccessToken>omeaccesstoken</AccessToken>
		</API>

	</Managers>
	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>
			
			
			<Host>
				<Names>
					
					<Name>*</Name>

				</Names>
				
				<TLS>
				    <CertPath>/home/ubuntu/relieve/relieve-certificate.cer</CertPath>
					<KeyPath>/home/ubuntu/relieve/relieve-key.key</KeyPath>
					<ChainCertPath>/home/ubuntu/relieve/relieve-certificate_inter.cer</ChainCertPath> 
				</TLS>
	
			</Host>

			

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
				 		<RTMP>
							<BlockDuplicateStreamName>true</BlockDuplicateStreamName>
						</RTMP>
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							<UTCTiming />
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							<UTCTiming />
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
`

regards,

**Comment by getroot** [comment]
If you want to send a stream to OME over WebRTC, you need to append ?direction=send to the URL. If there is no ?direction=send, you are requesting playback.

https://airensoft.gitbook.io/ovenmediaengine/live-source/webrtc-beta#url-pattern

Please read the manual carefully.

**Comment by Zinelaabidine** [comment]
Thanks, resolved by appending **direction=send&transport=tcp**
