### ISSUE TITLE
Is it possible to transcode the video in OME

### ISSUE THREAD

**Issue by Zinelaabidine** [AirenSoft/OvenMediaEngine#554]
Hi, 
I am streaming from WebRTC  to WebRTC using the OME. 
Is it possible to t transcode the received video ( ffmpeg and gstreamer command ) on the server (OME) and re-stream to the client using WebRTC?

regards,

**Comment by getroot** [comment]
hey, please read the manual and post your questions.

https://airensoft.gitbook.io/ovenmediaengine/transcoding
