### ISSUE TITLE
Unable to get HLS manifest, "An error occurred while accept TLS connection"

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#555]
**Describe the bug**
Trying to download the m3u8 for a stream, 

**To Reproduce**
Using a certificate from letsencrypt, set as follows (all files untouched from letsencrypt)

```
                <VirtualHost>
                        <Name>default</Name>
                        <!--Distribution is a value that can be used when grouping the same vhost distributed across multiple servers. This value is output to the events log, so you can use it to aggregate statistics. -->
                        <Distribution>name</Distribution>

                        <!-- Settings for multi ip/domain and TLS -->
                        <Host>
                                <Names>
                                                <Name>*.domain.tld</Name>
                                                <Name>domain.tld</Name>
                                                <Name>localhost</Name>
                                </Names>
                                <TLS>
                                        <CertPath>/opt/ovenmediaengine/cert.pem</CertPath>
                                        <KeyPath>/opt/ovenmediaengine/privkey.pem</KeyPath>
                                        <ChainCertPath>/opt/ovenmediaengine/fullchain.pem</ChainCertPath>
                                </TLS>
                        </Host>

```

Publishers set as follows

```
               <Publishers>
                        <OVT>
                                <Port>${env:OME_ORIGIN_PORT:9000}</Port>
                                <WorkerCount>1</WorkerCount>
                        </OVT>
                        <HLS>
                                <Port>799</Port>
                                <!-- If you want to use TLS, specify the TLS port -->
                                <TLSPort>800</TLSPort>
                                <WorkerCount>1</WorkerCount>
                        </HLS>
                        <DASH>
                                <Port>799</Port>
                                <!-- If you want to use TLS, specify the TLS port -->
                                <TLSPort>800</TLSPort>
                                <WorkerCount>1</WorkerCount>
                        </DASH>

```

**Expected behavior**

**Logs**

Relevant section - no errors during setup

[2021-11-12 19:31:49.628] E [SPSegPub-T800:28] OpenSSL | tls.cpp:422  | An error occurred while accept SSL connection: [OpenSSL] error:0A00009C:SSL routines::http request (167772316)
[2021-11-12 19:31:49.628] E [SPSegPub-T800:28] TLS | tls_server_data.cpp:115  | An error occurred while accept TLS connection

**Server (please complete the following information):**
 - OS: Ubuntu 20.04, kernel 5.10
 - OvenMediaEngine Version: 0.12.8
 - Branch: release

**Player (please complete the following information):**
N/A

**Additional context**
No more context but great work so far! Love all the upgrades lately, doing what I can to help

**Comment by naanlizard** [comment]
Notably, this is on a player NOT on the CORS acceptable domains, but I'm simply trying to download the file so I would be surprised if that was an issue.

I am able to download from port 799 (non-SSL) but not 800 (SSL)

**Comment by getroot** [comment]
What browser and URL were you trying to download? Could you hide only the IP or DOMAIN and write it down? I think maybe you accidentally tried http://domain:800 or https://ip:800 instead of https://domain:800/ .

**Comment by naanlizard** [comment]
I'm not sure what has changed (I restarted the docker instance to apply an unrelated settings change - segmentduration, and now it seems to work?

Perhaps I did use the wrong URL, it would be out of character for me but entirely possible! I'll consider this closed and reopen if it happens again and I can more reliably reproduce it. 

Unrelated but not worth opening a whole new ticket - is it possible to automatically choose the aspect ratio of the thumbnail, or add black bars instead of stretching, for the thumbnailer? If not, I'll open a feature request ticket if you'd like, but it's a bit useless as is for our use case if we end up stretching the stream

**Comment by getroot** [comment]
I'm not the developer of the transcoder, so I'm not sure if thumbnails also have aspect ratio features.
But the video has the features you said. If this doesn't work for the thumbnail feature, please open a new ticket.

https://airensoft.gitbook.io/ovenmediaengine/transcoding#rescaling-while-keep-the-aspect-ratio
