### ISSUE TITLE
Can't get access to API Server

### ISSUE THREAD

**Issue by sharapov-outsource** [AirenSoft/OvenMediaEngine#556]
I can't get access to API Server. The origin configuration is pretty default:

```bash
<Server version="8">
	
	....

	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			<!--TLS>
				<CertPath>path/to/file.crt</CertPath>
				<KeyPath>path/to/file.key</KeyPath>
				<ChainCertPath>path/to/file.crt</ChainCertPath>
			</TLS-->
		</Host>
		<API>
			<AccessToken>demo_access_token</AccessToken>
		</API>
	</Managers>
```

But it always reject connection

```bash
curl --location --request GET 'http://localhost:8081/v1/stats/current/vhosts/default' \
--header 'Authorization: Basic ZGVtb19hY2Nlc3NfdG9rZW4='
curl: (7) Failed to connect to localhost port 8081: Connection refused
```

The application is running on docker. The port 8081 is opened. Could anyone assist pls?

**Comment by getroot** [comment]
Did you bind the port to the API server? https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Server.xml#L24


Please follow the issue template.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
