### ISSUE TITLE
Youtube returning error when send rtmp push using OME

### ISSUE THREAD

**Issue by pkhadson** [AirenSoft/OvenMediaEngine#565]
My Server.xml
https://gist.github.com/pkhadson/bac67abff2cd944300371d955c0505f8

I'am streaming with OBS:
![image](https://user-images.githubusercontent.com/29266096/142296839-eff58053-e8dc-4d36-a93e-462f452f11c7.png)

Error:
![image](https://user-images.githubusercontent.com/29266096/142296856-a6125552-096d-426c-8e53-665b70713ff2.png)

**Comment by getroot** [comment]
Set the keyframe interval to less than 4 seconds as youtube said. You set keyframe interval to 0=auto (It may be very long)

**Comment by Keukhan** [comment]
I looked at the xml settings and the video track was transcoding to H264 and pushing Rtmp.

I tested it with the same settings and there is no problem.

![image](https://user-images.githubusercontent.com/21077363/142398058-35129e58-8da4-4574-b16a-e98d462fa304.png)

Perhaps the server's performance is low, so transcoding cannot be performed in real time, or maybe your network speed is not good enough.

Thanks

**Comment by Keukhan** [comment]
Or try using the bypass option without live transcoding on the server.  And, in obs, set the keyframe interval to 4 or less.

😀

**Comment by pkhadson** [comment]
Tnaks! But how can I disable transcoding?

**Comment by Keukhan** [comment]
`<Video> <Bypass>false</Bypass> <Codec>h264</Codec> <Bitrate>2000000</Bitrate> <Framerate>30.0</Framerate> <Width>1280</Width> <Height>720</Height> </Video>`

to
`<Video>
 <Bypass>true</Bypass>
</Video>`

easy :)

**Comment by pkhadson** [comment]
@Keukhan @getroot  Thank you for the goodwill! But it wasn't enough to solve the problem.

**Comment by getroot** [comment]
If it doesn't work yet, please post new information.  What does YouTube say?  This works fine in my tests.

**Comment by pkhadson** [comment]
Youtube is returning:
![image](https://user-images.githubusercontent.com/29266096/142916865-af834b03-5910-4ce2-b228-3fa59b25a3a2.png)



I'm sending the server ssh credentials @getroot @Keukhan. Feel free to change anything.

IP: 167.172.154.8
User: root
Password: ometest

Thanks!

**Comment by pkhadson** [comment]
To start rtmpsend to youtube:
```

curl --request POST \
  --url http://167.172.154.8:8081/v1/vhosts/default/apps/app:startPush \
  --header 'Content-Type: application/json' \
  --header 'authorization: Basic cGsyMDIxMTAwN2hhZHNvbg==' \
  --data '{
  "id": "0",
  "stream": {
    "name": "stream",
  },
  "protocol": "rtmp",
  "url":"rtmp://x.rtmp.youtube.com/live2",
  "streamKey":"85yg-d6du-qc2k-gtbs-2hg1"
}'
```

**Comment by getroot** [comment]
Change the Keyframe Interval in OBS from 0 to 1 like I said before.

**Comment by pkhadson** [comment]
I changed, but it didn't solve

**Comment by getroot** [comment]
However, when video bypass transcoding is used, OME does nothing.
Just send the input from OBS to Youtube as it is. And youtube tells you to shorten the keyframe interval.

Or the youtube error message you captured earlier is saying the bitrates are very low. Is your network speed or CPU good enough?

**Comment by pkhadson** [comment]
Yes, my CPU and network are fine. If I transmit from OBS directly to Youtube, the message does not appear

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/143024473-5fb1cfa0-a7f9-478b-95b3-7b34bd434828.png)

![image](https://user-images.githubusercontent.com/17779085/143024494-6d41bfe3-6fe7-4b3f-9d95-4073039a1ff0.png)

![image](https://user-images.githubusercontent.com/17779085/143024506-49aab28f-68da-4bd8-9ca9-69470a8a2f3a.png)

These captures are the results of testing on your server. Everything is normal.

**Comment by pkhadson** [comment]
Error happens 5 minutes after transmission starts

**Comment by getroot** [comment]
This is an issue that doesn't happen on other servers. You should check your server. The kernel version of your docker container is 5.4.0-888. On the other hand, the kernel version of our docker image (airensoft/ovenmediaenigne:latest) is 5.11.0-37. Linux kernels 5.3 to 5.6 have serious network errors. (related to the epoll event).
When posting a question, let us know what your environment is and how it differs from ours, so I can find the problem faster without having to look for it for an hour.

Check out several things. We have been using this feature in a commercial environment for 6 months without any problems.

**Comment by pkhadson** [comment]
OK! I will try on other servers. Thank you for your willingness. Thanks

**Comment by getroot** [comment]
Your docker container is OvenMediaEnigne 0.12.6. It is good to check if it is reproduced in the latest version (currently 0.12.8).

**Comment by pkhadson** [comment]
OvenMediaEngine is now running on the server without Docker. I've updated to the latest version but the same issue still occurs. I increased the server's resources and it didn't.

**Comment by pkhadson** [comment]
I am willing to donate to help me with this.

@getroot @Keukhan

**Comment by Keukhan** [comment]
I'm sorry. I couldn't check because I was busy due to urgent work. 
As soon as possible, I'll figure out what the problem is.

Please wait a moment. :)

Thanks.

**Comment by Keukhan** [comment]
@pkhadson 

Finally, I found the problem and solved it. 

https://github.com/AirenSoft/OvenMediaEngine/compare/e34b81bdd34d...f7e198a4985a

Test it with the master branch code.

Thank you for the great report. :)
