### ISSUE TITLE
SessionLoadBalancingThreadCount tag not found

### ISSUE THREAD

**Issue by Thunder80** [AirenSoft/OvenMediaEngine#566]
**Describe the bug**
We were running docker image of OME 0.12.1 and everything worked fine but when trying out OME 0.12.8 docker image, OME fails to start and gives an error. `SessionLoadBalancingThreadCount` its unable to find this tag in the Server.xml.

**To Reproduce**
1. Set Server.xml as the official configuration example.
2. Start the OME 0.12.8

**Expected behavior**
OME should start properly.

**Logs**
[2021-11-19 11:59:06.240] E [OvenMediaEngine:1] OvenMediaEngine | main.cpp:326  | An error occurred while load config: [Config] Unknown item found: Server.VirtualHosts.VirtualHost.Applications.Application.Publishers.SessionLoadBalancingThreadCount in ./origin_conf/Server.xml

**Server (please complete the following information):**
 - OS: Ubuntu: 0.12.8
 - OvenMediaEngine Version: main

**Comment by getroot** [comment]
Its name was changed a while ago.
Please refer to the manual.
https://airensoft.gitbook.io/ovenmediaengine/performance-tuning#appworkercount

**Comment by hastarin** [comment]
@getroot NOTE: The example in the documentation needs updating.  https://airensoft.gitbook.io/ovenmediaengine/configuration#configuration-example

**Comment by Thunder80** [comment]
34184ec This commit did fix it... It's not live yet I guess.
