### ISSUE TITLE
SSL - no shared cipher

### ISSUE THREAD

**Issue by catapop84** [AirenSoft/OvenMediaEngine#571]
**Describe the bug**
We're trying to route our live stream traffic (HLS) through a CDN.
When the CDN tries to pull the m3u8 files the connection is rejected.
this is the log from oven:

```
[2021-11-24 14:51:15.092] E [SPSegPub-T443:14] OpenSSL | tls.cpp:422  | An error occurred while accept SSL connection: [OpenSSL] error:0A0000C1:SSL routines::no shared cipher (167772353)
[2021-11-24 14:51:15.092] E [SPSegPub-T443:14] TLS | tls_server_data.cpp:115  | An error occurred while accept TLS connection
```

I did a SSL test ifrom https://www.ssllabs.com/ssltest and this is the result
```
Cipher Suites
# TLS 1.2 (we could not determine if the server has a preference) 
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)   - WEAK 
```

Certificate is issued by Let's Encrypt

**Comment by getroot** [comment]
Please upload your Server.xml and full ovenmediaengine.log file so that we can reproduce the problem. We are using TLS HLS well in commercial environments right now.

**Comment by catapop84** [comment]
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/7597347/ovenmediaengine.log)
[server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7597354/server.txt)

I had to change Server.xml to .txt for github to allow me to upload the file.
I'm using v0.12.8

**Comment by getroot** [comment]
Several patches related to TLS have been applied recently. Could you please check if the problem is reproduced with the latest master version?

**Comment by catapop84** [comment]
with docker I've tried the `dev` version and I still receive this error

```
[2021-12-07 01:43:53.504] E [SPSegPub-T443:13] OpenSSL | tls.cpp:193  | An error occurred while accept SSL connection: [OpenSSL] error:0A0000C1:SSL routines::no shared cipher (167772353)
[2021-12-07 01:43:53.504] E [SPSegPub-T443:13] OpenSSL | tls_server_data.cpp:105  | An error occurred while accept TLS connection: error code: 1
```

In https://www.ssllabs.com/ssltest I get this warning: `This server does not support Authenticated encryption (AEAD) cipher suites`

I think a good approach is to add support for TLS 1.3 and add more ciphers: https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#23-use-secure-cipher-suites


It might work on major browsers, but some clients might reject encryption with known weakness https://blog.qualys.com/product-tech/2018/02/02/forward-secrecy-authenticated-encryption-and-robot-grading-update?_ga=2.250308545.650792483.1638838998-1525727091.1637766172

**Comment by getroot** [comment]
@catapop84 

If your CDN only uses TLS 1.3, we don't support it yet. Check out the thread below for a detailed history.

https://github.com/AirenSoft/OvenMediaEngine/pull/313

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.
