### ISSUE TITLE
Stream to FFMPEG?

### ISSUE THREAD

**Issue by nimigeanu** [AirenSoft/OvenMediaEngine#573]
**PROBLEM**

I'd like to retrieve an OvenMedia stream with FFMPEG (pull), low latency.

**EXPECTATION**

- **RTSP** or **RTP** (pull) output would be very useful, perhaps this is already possible but undocumented?
- Tried to play the **LL-DASH** stream with FFMPEG but the results and latency are inconsistent.

**OTHER HELPFUL INFORMATION**
 - Also considered using the **RTMP push** but it being limited to AAC audio is not ideal
 - Notice **RTSP Push** is something you are considering?
 - We do not have the resources to create a transmuxer for **OVT**, any way that format can be played with FFMPEG?

Thank you!

**Comment by getroot** [comment]
We are considering only WebRTC, HLS, and DASH as output streaming protocols. We prioritize compatibility with web browsers and mobile native players. RTSP output may be considered in the future, but not now. (Lack of human resources) If someone could PR the RTSP output, we would be very welcome.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
