### ISSUE TITLE
Can't play stream with VPN enabled

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#575]
Hello,

I had a client the other day who couldn't connect to my stream because that had a VPN on. Unfortunately, the laptop they have is a company machine and there was no way for them to connect to the internet without it, so I couldn't stream.

I later tested this myself and indeed, when enabling a VPN I could not play a stream, neither in the player embedded in my page nor on the test player page.

Is this an issue or a feature? Something I can disable?

If it's an issue, let me know how I can help.

Version 0.12.8
Streaming WSS
Bypassing the encoding on the server

**Comment by getroot** [comment]
OvenMediaEnigne and OvenPlayer don't know and don't care if the viewer is connecting via VPN or not. This will most likely be blocked by a firewall on the VPN side. It's a good idea to talk to your VPN representative.

**Comment by zcolor** [comment]
Thanks for the reply. In this case, I can't control the VPN settings of my clients, I will take a look at my VPN settings, however.

**Comment by dbContext** [comment]
As @getroot said, using a VPN shouldn't impact the network stack / functionality of OME and how it interacts with you as a client to establish a WebRTC connection when negotiating. 

I would however say there is a potential that the hosting provider you're using for OME, has restrictions around known proxy / VPN IP addresses as a security measure? Have you first made sure that when connected to your VPN, you're able to interact with the OME server over the relevant ports for WSS negotiation?

**Comment by zcolor** [comment]
> As @getroot said, using a VPN shouldn't impact the network stack / functionality of OME and how it interacts with you as a client to establish a WebRTC connection when negotiating.
> 
> I would however say there is a potential that the hosting provider you're using for OME, has restrictions around known proxy / VPN IP addresses as a security measure? Have you first made sure that when connected to your VPN, you're able to interact with the OME server over the relevant ports for WSS negotiation?

Just checked, I can log in and interact with the Server with my VPN enabled. It's probably something on the player side and the server because I can stream to the server with the VPN enabled and watch it on another machine where there is no VPN active. However, I can't watch it with on a machine where a VPN is enabled.

I'm using express VPN at the moment. I don't know what VPN provider my clients were using.

**Comment by dbContext** [comment]
@zcolor It's possible that the VPN has "WebRTC Leak Prevention", as it used to be a common method to get the real IP address of a user using a VPN.

e.g. https://www.expressvpn.com/webrtc-leak-test

No idea if you're able to disable Leak Protection within the software client provided by Express VPN, but I believe most consumer level VPN providers have some form of Leak Protection, most likely causing the issues when attempting a WebRTC connection.

**Comment by dbContext** [comment]
@zcolor Just to add to the above, If you're able to negotiate / connect  to the WSS (WebSocket Server) while on the VPN (check your network tab for a 101 upgrade), but the video just isn't playing then I think that's a confirmation it's to do with VPN blocking WebRTC "leaking".

**Comment by zcolor** [comment]
Thanks a lot! I'll look into it! Is there another stable protocol I can use on the player?

**Comment by zcolor** [comment]
Funny, I was just testing this and while streaming via RMTP it does not work, but when streaming via SRT it works. Both with the VPN enabled.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
