### ISSUE TITLE
Prerequisites error in Ubuntu 21.10

### ISSUE THREAD

**Issue by danruser** [AirenSoft/OvenMediaEngine#588]
Hello. 
Thans for your job.

Scanning dependencies of target srt_virtual
at this stage, an error pops up and stops the script

make[2]: *** [CMakeFiles/srt_virtual.dir/build.make:108: CMakeFiles/srt_virtual.dir/srtcore/cache.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/srt_virtual.dir/build.make:121: CMakeFiles/srt_virtual.dir/srtcore/channel.cpp.o] Error 1
make[2]: *** [CMakeFiles/srt_virtual.dir/build.make:82: CMakeFiles/srt_virtual.dir/srtcore/api.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:243: CMakeFiles/srt_virtual.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
(srt) installation has failed.

**Comment by getroot** [comment]
You are so fast! Thanks for reporting the problem.

We haven't tried Ubuntu 21.10 yet. It seems that the SRT library doesn't compile there... Maybe it's better to ask the SRT community about this problem.

In my opinion, supporting Ubuntu 21.10 is a very low priority. So it looks like it will take some time. Maybe it will skip 21.10 and support 22.04 LTS.

**Comment by pateze** [comment]
Which version of SRT are you using? Because in Debian 11 I was getting similar errors... The one that worked best for me was version 1.4.2

**Comment by danruser** [comment]
Hello all
If you install all the packages separately then there are not problems.

https://airensoft.gitbook.io/ovenmediaengine/v/master-1/troubleshooting#prerequisites-sh-script-failed
Thanks for you job

**Comment by danruser** [comment]
Hello
Manually install all libraries without problems, but during compilation it gives this error

####################################################
#                                                  #
#           AirenSoft Make System v0.63            #
#                                                  #
####################################################
   - Operating system        : linux
   - Core count              : 1
   - GCC version             : 10.2.1
   - Build option            : RELEASE
   - Paths for linker        : /opt/ovenmediaengine/lib:/opt/ovenmediaengine/lib64
   - Paths for pkg-config    : /opt/ovenmediaengine/lib/pkgconfig:/opt/ovenmediaengine/lib64/pkgconfig
   - Total Projects count    : 48

[  1/399|  0%] Preparing directories...
[  2/399|  0%] [static] libapi_server.a: C++ projects/api_server/api_server.cpp => intermediates/RELEASE/objs/api_server/api_server.o
In file included from projects/base/ovsocket/socket_pool/socket_pool.h:11,
                 from projects/base/ovsocket/ovsocket.h:22,
                 from projects/api_server/api_server.h:13,
                 from projects/api_server/api_server.cpp:9:
projects/base/ovsocket/socket_pool/socket_pool_worker.h:89:42: error: ‘SRT_EPOLL_EVENT’ does not name a type; did you mean ‘SRT_EPOLL_ERR’?
   89 |   void ConvertSrtEventToEpollEvent(const SRT_EPOLL_EVENT &srt_event, epoll_event *event);
      |                                          ^~~~~~~~~~~~~~~
      |                                          SRT_EPOLL_ERR
compilation terminated due to -Wfatal-errors.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/api_server/api_server.o] Error 1


There is no problem with docker 
In any case, there are more important things in the project 
Thanks
