### ISSUE TITLE
OvenMediaEngine automatically recover

### ISSUE THREAD

**Issue by johnrogis8** [AirenSoft/OvenMediaEngine#591]
Hi,
I am using OvenMediaEngine to send rtmp stream to viewers' browsers with Webrtc. But when some viewers' internet disconnected even for just a moment he should reload the page.
Is there any config i can do to solve this problem?

**Comment by zygocact** [comment]
Well, I am seeking to do the opposite, for the stream to be reloaded when the streamer has a hiccup.
For your particular problem, you could try the webrtcConfig.timeoutMaxRetry & webrtcConfig.connectionTimeout configs in OvenMediaPlayer.
You could also try the <Timeout></Timeout> setting in Server.xml.

I haven't tested these yet, but will do so later. I'll report back if I get it working.

**Comment by Morpheus235** [comment]
Just add eventlisteners. Ovenplayer throws a lot of codes. For example just store the selected source and just replay it by setting it as current Source on an error being logged. At least thats how I solved it. I can share an example later

**Comment by getroot** [comment]
https://github.com/AirenSoft/OvenPlayer/issues/240

It is good to continue this discussion in OvenPlayer.
