### ISSUE TITLE
webRTC input (provider) not working in v0.12.9,dev but works in v0.12.8

### ISSUE THREAD

**Issue by catapop84** [AirenSoft/OvenMediaEngine#592]
**Describe the bug**
webRTC input is not working in v0.12.9 or dev  but works in v0.12.8. 
I'm using docker

**To Reproduce**
pairing in websocket in 0.12.8 I receive this messages on websocket
![image](https://user-images.githubusercontent.com/79577121/145698285-fe811d76-4717-4043-bcb8-c818fcfaf58d.png)

but in websocket in 0.12.9(or dev) I only receive this 
![image](https://user-images.githubusercontent.com/79577121/145698342-f2808d3c-9403-43ff-b996-4ec986a92886.png)
the bitrate is 0 and video width x height is  0x0
![image](https://user-images.githubusercontent.com/79577121/145698379-3eb122de-cb3a-43f9-a8cf-b8c3cf811eed.png)

when I check the oven api url for stream info I receive this:

```
		"input": {
			"createdTime": "2021-12-12T02:46:11.814+0000",
			"sourceType": "WebRTC",
			"sourceUrl": "TCP://my_ip:65471",
			"tracks": [
				{
					"type": "Video",
					"video": {
						"bitrate": "0",
						"bypass": false,
						"codec": "H264",
						"framerate": 0.0,
						"height": 0,
						"width": 0
					}
				},
				{
					"audio": {
						"bitrate": "0",
						"bypass": false,
						"channel": 2,
						"codec": "OPUS",
						"samplerate": 0
					},
					"type": "Audio"
				}
			]
		},
```

in logs I have something like this:

```
[2021-12-12 01:11:01.944] I [SPRtcSig-T3334:22] Signalling | rtc_signalling_server.cpp:201  | New client is connected: <ClientSocket: 0x7f7c9c001130, #25, Connected, TCP, Nonblocking, 188.25.136.221:15015>
[2021-12-12 01:11:02.206] I [SPRtcSig-T3334:22] Provider | stream.cpp:49   | Unknown/crocorin(100) has been started stream
[2021-12-12 01:11:02.206] I [SPRtcSig-T3334:22] MediaRouter | mediarouter_application.cpp:244  | Trying to create a stream: [#default#live/crocorin(100)]
[2021-12-12 01:11:02.206] I [SPRtcSig-T3334:22] MediaRouter | mediarouter_application.cpp:245  | 
[Stream Info]
id(100), msid(0), output(crocorin), SourceType(WebRTC), Created Time (Sun Dec 12 01:11:02 2021) UUID(b85daeb0-cfb7-48c3-b390-2765b5b9a084/default/#default#live/crocorin/i)

	Audio Track #-749666661: Bypass(false) Bitrate(0b) codec(8, OPUS) samplerate(0) format(none, 0) channel(stereo, 2) timebase(1/48000)
	Video Track #-660408041: Bypass(false) Bitrate(0b) codec(1, H264) resolution(0x0) framerate(0.00fps) timebase(1/90000)
[2021-12-12 01:11:02.206] I [SPRtcSig-T3334:22] MediaRouter | mediarouter_stream.cpp:54   | Trying to create media route stream: name(crocorin) id(100)
[2021-12-12 01:11:02.206] I [SPRtcSig-T3334:22] Monitor | application_metrics.cpp:57   | Create StreamMetrics(crocorin/b85daeb0-cfb7-48c3-b390-2765b5b9a084/default/#default#live/crocorin/i) for monitoring
[2021-12-12 01:11:02.207] I [SPRtcSig-T3334:22] Transcoder | transcoder_stream.cpp:523  | [#default#live/crocorin(100)] -> [#default#live/crocorin(140440838)] Output stream has been created.
[2021-12-12 01:11:02.208] I [SPRtcSig-T3334:22] MediaRouter | mediarouter_application.cpp:244  | Trying to create a stream: [#default#live/crocorin(140440838)]
[2021-12-12 01:11:02.208] I [SPRtcSig-T3334:22] MediaRouter | mediarouter_application.cpp:245  | 
[Stream Info]
id(140440838), msid(0), output(crocorin), SourceType(Transcoder), Created Time (Sun Dec 12 01:11:02 2021) UUID(b85daeb0-cfb7-48c3-b390-2765b5b9a084/default/#default#live/crocorin/o)
	>> Origin Stream Info
	id(100), output(crocorin), SourceType(WebRTC), Created Time (Sun Dec 12 01:11:02 2021)

	Audio Track #0: Bypass(true) Bitrate(0b) codec(8, OPUS) samplerate(48.0K) format(none, 0) channel(stereo, 2) timebase(1/48000)
	Audio Track #1: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(none, 0) channel(stereo, 2) timebase(1/48000)
	Video Track #2: Bypass(true) Bitrate(0b) codec(1, H264) resolution(0x0) framerate(0.00fps) timebase(1/90000)
```

Same server.xml file on both 0.12.8 and 0.12.9 , on 0.12.8 everything works.

Is something changed between this versions or is this a bug?

**Comment by getroot** [comment]
Outputting bitrate and resolution as 0 is a functional limitation, not a bug.

I also have webrtc input working fine in 0.12.9. Could you please upload your Server.xml? Fixed a bug where the WebRTC Provider used Publisher's settings, which may be related to it.

**Comment by catapop84** [comment]
here's the config
[server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7704244/server.txt)

basically I try to have webrtc input and hls as output

same config file works in 0.12.8 but not in 0.12.9

in 0.12.8 I receive a lot more messages in websocket, like I showed in the previous post.

**Comment by getroot** [comment]
I have one guess.

Probably because of the issue below, your Server.xml used to communicate with UDP in 0.12.8.

https://github.com/AirenSoft/OvenMediaEngine/issues/579

And since this issue is fixed in 0.12.9, WebRTC Streamer tries to connect over TCP but it seems to fail. So it seems that even in the log it is not possible to send Local Candidate.

Would you like to make sure that your TCP Relay Port, 3478/tcp, is open in your Docker settings?

**Comment by catapop84** [comment]
OK. I'll give it a try and let you know. So in 0.12.8 the default communication was UDP and in 0.12.9 is TCP ?
If yes, then this 2 are similar:
`ws[s]://<host>[:port]/<app name>/<stream name>?direction=send`
`ws[s]://<host>[:port]/<app name>/<stream name>?direction=send&transport=tcp`
and if I want to communicate over UDP I should use `transport=udp` ?

**Comment by getroot** [comment]
I don't mean that...

Because 0.12.8 was buggy, the WebRTC Provider used to use the WebRTC Publisher's Bind settings. So `<TcpRelay>` and `<TcpForce>` settings did not work in 0.12.8 with your Server.xml. So it worked with UDP.

`<TcpRelay>` and `<TcpForce>` settings now work because 0.12.9 fixed this bug. If `<TcpForce>` is true and you are using OvenPlayer, it will work as WebRTC/TCP even without `transport=tcp` in the URL.

**Comment by catapop84** [comment]
Thanks @getroot . It's working now. that was the problem. I didn't set port relay 3478 /tcp.
that or disable tcprelay from config.
Thanks
