### ISSUE TITLE
Callback request when stream finished

### ISSUE THREAD

**Issue by Amirhasanioox** [AirenSoft/OvenMediaEngine#595]
Hi first of all thanks for this great project.
It would be very helpful if we get a callback request when stream finished because I want to save start and end date of stream to show some statics and do extra things when stream finished.
Right now I have to setup a timer to request every 10 second to api to check if stream finished or not.
Thanks

**Comment by getroot** [comment]
Several people have requested this feature, so I will develop it. However, if you need this function before that, you can use curl to develop a simple script that calls a specific URL by parsing /var/ovenmediaenigne/ovenmediaengine.log and checking the log when the stream ends.
