### ISSUE TITLE
Couldn't verify admission webhook signature

### ISSUE THREAD

**Issue by Amirhasanioox** [AirenSoft/OvenMediaEngine#596]
**PROBLEM**

I could not validate admissionWebhook request by the signature.
If someone gives me an example I will be very appreciated.
I don't know what exactly is data (http payload) and I tried to decode the signature with base64_decode in php but it failed.

**Comment by getroot** [comment]
https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks#security

1. Encrypt the HTTP payload with HMAC-SHA1(your secret-key).
2. Encode the result of (1) to base64 url safe.
3. Compare with the X-OME-Signature value.

**Comment by getroot** [comment]
https://github.com/AirenSoft/OvenMediaEngine/blob/master/src/projects/modules/access_control/admission_webhooks/admission_webhooks.cpp#L214

**Comment by Amirhasanioox** [comment]
I could not generate X-OME-Signature.
this is the payload:
{'client': {'address': '80.191.211.65', 'port': 51600}, 'request': {'direction': 'incoming', 'protocol': 'RTMP', 'time': '2021-12-14T15:10:00.524+0000', 'url': 'rtmp://x.x.x.x:19350/live/test'}}
and this is my secret: 1234
X-OME-Signature: 6P8O96vUM50JLD9mU9R4BxGbPDg

and I use this code for generating signature:
```
$hash = hash_hmac("sha1", $data, "1234", $raw_output=true);
$hash_encoded = base64_encode($hash);
```

**Comment by getroot** [comment]
what was your result?

**Comment by Amirhasanioox** [comment]
I think I found the problem. Problem was single quote in body. It has to be double quotes to get the right hash.
