### ISSUE TITLE
REST API connections won't decrement when hiding the streamkey via the AdmissionWebhooks

### ISSUE THREAD

**Issue by chnagy** [AirenSoft/OvenMediaEngine#598]
**Describe the bug**
The REST API connections won't decrement at
`https://<host>/v1/stats/current/vhosts/default/apps/app/streams/<key>`

It work correctly as long as I won't add the AdmissionWebhooks.

**To Reproduce**
1. I pulled the latest docker image of ovenmediaengine
2. Uncomment at Bind/Managers/API to enable the REST API in the Server.xml
```
...
        <Bind>
                <!-- Enable this configuration if you want to use API Server -->
                <Managers>
                        <API>
                                <Port>${env:OME_API_PORT:8081}</Port>
                                <WorkerCount>1</WorkerCount>
                        </API>
                </Managers>
                <Providers>
...
```

3. Add the AccessToken in the Server.xml

```
...
        </Bind>

        <Managers>
                <Host>
                        <Names>
                                <Name>*</Name>
                        </Names>
                </Host>
                <API>
                        <AccessToken>secrettoken</AccessToken>
                </API>
        </Managers>

        <VirtualHosts>
...
```

4. Add the AdmissionWebhooks in the Server.xml

```
...
                        <AdmissionWebhooks>
                                <ControlServerUrl>http://<host>/auth</ControlServerUrl>
                                <SecretKey>secret</SecretKey>
                                <Timeout>3000</Timeout>
                                <Enables>
                                <Providers>rtmp,webrtc,srt</Providers>
                                <Publishers>webrtc,hls,dash,lldash</Publishers>
                                </Enables>
                        </AdmissionWebhooks>

                        <!-- Settings for applications -->
                        <Applications>
...
```

5. In the Control Server I replace the given streamkey based on a map to hide the actual streamkey as suggested in the docs.
6. Stream with OBS
7. Recieve with ovenplayer the webrtc stream.
8. Check API

```
HTTP/1.1 200 OK
Server: openresty
Date: Wed, 15 Dec 2021 16:59:02 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 445
Connection: close
X-Served-By: <host>

{
  "message": "OK",
  "response": {
    "connections": {
      "dash": 0,
      "hls": 0,
      "lldash": 0,
      "ovt": 0,
      "webrtc": 1
    },
    "createdTime": "2021-12-15T16:58:03.180+0000",
    "lastRecvTime": "2021-12-15T16:59:02.647+0000",
    "lastSentTime": "2021-12-15T16:59:02.648+0000",
    "lastUpdatedTime": "2021-12-15T16:59:02.648+0000",
    "maxTotalConnectionTime": "2021-12-15T16:58:47.063+0000",
    "maxTotalConnections": 1,
    "totalBytesIn": 59487146,
    "totalBytesOut": 15905697,
    "totalConnections": 1
  },
  "statusCode": 200
}
```

9. Close Player
11. Check API again

```
HTTP/1.1 200 OK
Server: openresty
Date: Wed, 15 Dec 2021 17:02:20 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 447
Connection: close
X-Served-By: <host>



{
  "message": "OK",
  "response": {
    "connections": {
      "dash": 0,
      "hls": 0,
      "lldash": 0,
      "ovt": 0,
      "webrtc": 1
    },
    "createdTime": "2021-12-15T16:58:03.180+0000",
    "lastRecvTime": "2021-12-15T17:02:20.376+0000",
    "lastSentTime": "2021-12-15T17:02:20.378+0000",
    "lastUpdatedTime": "2021-12-15T17:02:20.378+0000",
    "maxTotalConnectionTime": "2021-12-15T16:58:47.063+0000",
    "maxTotalConnections": 1,
    "totalBytesIn": 257288587,
    "totalBytesOut": 217513900,
    "totalConnections": 1
  },
  "statusCode": 200
}
```

11. The connection count for webrtc will stay the same without ever decreasing.

**Expected behavior**
Connection count should be decreasing after closing the connection.

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/7721355/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: docker image
 - OvenMediaEngine Version: 0.12.9

**Player (please complete the following information):**
 - OS: Windows 11
 - Browser firefox, chrome
 - lastest Ovenplayer (CDN or ovenplayer demo page)

**Comment by getroot** [comment]
Thank you for reporting, I’ll check it

**Comment by catapop84** [comment]
I wanted to submit this myself. Just a few details based on my situation.
We use AdmissionWebhooks for incoming rtmp and webrtc.
If we change the URL on rtmp , then close the rtmp streaming from obs, everything works great.
If we change the URL on webrtc, then we close the webrtc connection, the stream still appears in API .
If we don't  change the URL on webrtc and we close the webrtc connection, the stream will not show in API.

So from our testing the problem happens only when you change the URL on incoming webrtc.

Hope this helps
