### ISSUE TITLE
Getting invalid certificate error on IOS 15

### ISSUE THREAD

**Issue by AMR1798** [AirenSoft/OvenMediaEngine#600]
**PROBLEM**

I am getting this error on IOS 15.1 safari and chrome when trying to play the stream over webrtc
`WebSocket connection to ‘wss://oven.domain.com:3334/app/amrmzkr?transport=tcp’ failed: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “oven.domain.com” which could put your confidential information at risk.`

**EXPECTATION**

Please write how you would like the problem to be resolved.

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
I'm not sure on this one, i pulled the master branch from December 6

- Encoder information

OBS 27.1.3

- Player information

Same output on my site and demo player. 

- Operating system and version

Centos 7

**SETUP INFORMATION AND LOGS**

https://pastecode.io/s/ir3j3w4o - Server.xml 
https://pastecode.io/s/063hoswt - log

**OTHER HELPFUL INFORMATION**

webrtc stream is working fine on android/windows. i've also tested on macOS safari and there's no problem connecting to the stream. it's only happening on IOS 15. i am currently unable to test on other IOS version.

The certificate was created using certbot using cloudflare plugin.

**Comment by getroot** [comment]
I've never experienced this type of error. So, I did a Google search and found many articles like the one below. See if this solves your problem. In particular, it seems useful to enable Set Automatically of Data & Time.

https://appletoolbox.com/the-certificate-for-this-server-is-invalid-error-fix/

**Comment by AMR1798** [comment]
Thanks for the quick reply. i've tried all the methods suggested in the article but none of them worked for me unfortunately. 

But no worries, i've fixed this problem by setting up nginx proxy pass that was suggested in an older issue ticket. here's the configuration that i used

```
server {
                listen 3335 ssl;
                #listen [::]:3335 ssl ipv6only=on; # managed by Certbot
                server_name oven.domain.com;
                ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
                ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;

        location / {

            # Disable cache
            add_header 'Cache-Control' 'no-cache';

            # CORS setup
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain charset=UTF-8';
                add_header 'Content-Length' 0;
                return 204;
            }

                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header Host $host;

                        proxy_pass http://oven.domain.com:3333;

                        proxy_ssl_certificate     /etc/letsencrypt/live/domain.com/fullchain.pem;
                        proxy_ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;

                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "upgrade";
                }
}

```

**Comment by getroot** [comment]
Hmm I wonder what could be the cause of this,

Maybe it's because fullchain.pem is linked to `<CertPath>`? OME is designed to set only the certificate for the domain, not the fullchain, in `<CertPath>`. I want to check if iOS may behave differently for different environments and for this.
  `<CertPath>/etc/letsencrypt/live/domain.com/fullchain.pem</CertPath>`

**Comment by getroot** [comment]
And, is this 100% reproducible on your iOS? Or does it happen occasionally? My iOS is 15.1.1 and I've never seen anything like this. The difference seems to be the certificate... Hmm...

**Comment by AMR1798** [comment]
can confirm that it's 100% reproducible on my IOS by reverting back the port to 3334 - connecting directly to OME instead of proxy pass. 

i'm not 100% sure if i messed up the certificate configuration. i just noticed that inside the certificate folder, there's cert.pem, chain.pem and fullchain.pem. maybe i should've used the cert.pem and chain.pem instead in the configuration. will test this tomorrow and update it here.

**Comment by dimiden** [comment]
@AMR1798 
Would you like to add the below settings under line 166 of your ```Server.xml```?
```
					<Name>oven.domain.com</Name>
					<Name>domain.com</Name>              <== Insert this line
```

I noticed that ```domain.com``` was requested in the log, while ```oven.domain.com``` was set in the ```<VirtualHost>```.
This seems to have failed for some reason as the client sent ```domain.com``` instead of ```oven.domain.com``` in SNI's server name.
Therefore, if you add the above setting, I think it will work normally. (I need to check further whether this is an issue of iOS 15 or another issue.)

**Comment by dimiden** [comment]
@AMR1798 
I'm happy that it's going well! Could you check if it works well except for the ```domain.com``` setting? 
I would like to check whether the SNI function added this time is malfunctioning or simply caused by a wrong certificate setting.

**Comment by AMR1798** [comment]
@dimiden I've removed the domain.com line in the configuration and it is still working. I'm guessing the problem I had was only because of the certificate configured incorrectly.

**Comment by dimiden** [comment]
@AMR1798 
Thank you for the confirmation!
