### ISSUE TITLE
Will user see actual app/stream name after allowing (AdmissionWebhook)?

### ISSUE THREAD

**Issue by Amirhasanioox** [AirenSoft/OvenMediaEngine#601]
I have a question about admission webhook and user authentication part.
I want to know if I give user a different url then allow user to watch with actual stream url will they get the actual url or not?
for example this is my stream url: 
rtmp://domain.com:1935/app/test
so my webrtc play url is:
ws://domain.com:3333/app/test
but I will give the user url like:
ws:domain.com:3333/user_id
after allowing the user with new_url (ws://domain.com:3333/app/test)
will they see this main url or not?
If they will see what should I do to secure app/stream name ?
I kwon about signed policy but if I use signed policy what is the point of using admission webhook?

**Comment by getroot** [comment]
The player will never know what negotiation (new_url) was made between the OME and the Admission ControlServer. So it's safe.

**Comment by Amirhasanioox** [comment]
Thank you
