### ISSUE TITLE
Error 501 with TLS WebRCT stream

### ISSUE THREAD

**Issue by DaanWesterhof** [AirenSoft/OvenMediaEngine#602]
**PROBLEM**
I am using OME as a streaming server for a project on my Schools Local Area Network. We are building a Web-VR application using A-Frame a need to have a Low Latency Video Stream available inside the application of a robot arm. 

The VR-Headset only allows you to enter VR if you are on a HTTPS connection with the host (my laptop). 
I can successfully run OME and view its stream in a regular HTTP using non secure WebRTC (nice low latency). But I am unable to connect using TLS/WSS. I recieve error 501

I have correctly set the paths to my TLS certificates, and opened up port 3334 for the wss connection. 

I suspect the problem to be the domain name. As I am just working with IP adreses and no domain name, i suspect that OME is blocking the connection or something like that. 
I dont actualy need the connection to be secure (i dont care who views the stream), i just need to be able to connect. 

On other posts i saw that <Name> * </Name>, should work, but in the documentation it says it does not.

**EXPECTATION**

I hope to find a way to stream the WebRTC stream over wss on my LAN soo i can view it in my Application

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

I am using the docker version with airensoft/ovenmediaengine:0.12.9 as its image.
This is the command i use to create the docker container:
```
docker run -d -p 1935:1935 -p 4000-4005:4000-4005/udp -p 3333-3334:3333-3334 -p 3478:3478 -p 8080:8080 -p 9000:9000 -p 9999:9999/udp -p 10006-10010:10006-10010/udp -v C:/<pathtoserver_files>/Server_files:/opt/ovenmediaengine/bin/origin_conf -v C:/<pathtocertificates>/certificates:/opt/ovenmediaengine/bin/origin_conf/certificates/ airensoft/ovenmediaengine:0.12.9
```

- Encoder information

I am using OBS version 27.1.3 64-bit
See below for my streaming settings:
![image](https://user-images.githubusercontent.com/43374529/146573252-04a3572b-2721-4bd6-98b1-a140efc95641.png)

![image](https://user-images.githubusercontent.com/43374529/146573396-de88fd7e-ed98-437c-afc9-6cde96447248.png)

- Player information

All the non TLS/SSL versions seem to be working just fine. Its just the WSS stream that is unable to connect with error 501.
![image](https://user-images.githubusercontent.com/43374529/146573569-7f0ef1f2-7d3b-40f0-82b6-d0135fc6e844.png)

![image](https://user-images.githubusercontent.com/43374529/146573664-30c89972-04dc-4dc7-8305-ca1a11c0145b.png)

- URL

The url i use to input the stream from obs:
url = rtmp://145.89.163.179:1935/app, key=stream

The urls that i use to watch:
works: ws://145.89.163.179:3333/app/stream/ 
doesnt work: wss://145.89.163.179:3334/app/stream/

- Operating system and version

I am on windows 10 version: 19042.1288

**SETUP INFORMATION AND LOGS**
Here is my Server.xml:

[Server.zip](https://github.com/AirenSoft/OvenMediaEngine/files/7736396/Server.zip)

here is my server.log with default settings: (This is the output of the docker logger copied to a file)
[server.log](https://github.com/AirenSoft/OvenMediaEngine/files/7736411/server.log)

**OTHER HELPFUL INFORMATION**
I expect it to be the <Name>*</Name> option, but I do not have a domain name to work with. The certificate names have the name Dwaan.localdomain.crt but Dwaan is just my laptop name, and it is how the files were generated by this script which I forgot its name (i could generate new certificates. using openssl). 

It could also be a problem with the certificates, as these certificates are not the same as my local python server (that one only has a simple .pem file). I will try and see if generating new certificates and having a proper CA without a domain will work on sunday or monday. 
But i thought id ask here just in case it can be done in an easier way,

**Comment by dbContext** [comment]
You're TLS certificate will not be valid, as it's not issued to a valid domain name (common name).

You'll want to setup a domain name (whether that be an internally mapped domain name is up to you, providing it's solely on a LAN, the IPv4 address you've provided above is a public facing IP related to a NL geolocated network.) and then issue a TLS certificate for that, I'd use Let's Encrypt (as it's free) to ensure you don't run into any issues with devices not accepting self-signed certificates.

If you're doing this for free as it's a school project, feel free to reach out, and I can provide you a temporary sub-domain so you don't have to purchase a domain name.

Best,
JC

**Comment by Morpheus235** [comment]
If you wanna stay on your local network you could setup a reverse proxy e.g. nginx to proxy https and wss connections to ome.

**Comment by DaanWesterhof** [comment]
Thank you a lot for this information, I think I now know everything I need to know to get this to work!
