### ISSUE TITLE
Wrong ip when using nginx reverse proxy

### ISSUE THREAD

**Issue by Amirhasanioox** [AirenSoft/OvenMediaEngine#604]
**PROBLEM**

I'm using nginx to reverse proxy signaling phase of webrtc every thing is ok but I get wrong ip in admission webhook. it is local ip.
Also I checked the logs and I saw both local ip and my real ip.

<img width="1367" alt="Screen Shot 1400-09-29 at 5 46 01 AM" src="https://user-images.githubusercontent.com/22333404/146702732-ec57c781-67eb-4d69-8b0e-0c272a6a9d52.png">

this is my nginx config:
```
location /live/ {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_redirect off;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_pass http://ome:3333;
}
```

**Comment by getroot** [comment]
If nginx is proxying, only nginx's IP is known to OME. There is no way to know the IP of the client.

**Comment by basisbit** [comment]
there exist `X-REAL-IP` and `X-FORWARDED-FOR` headers for such cases. Please add support for getting the ip address from these headers, if ome is used behind a reverse proxy or http load balancer.

**Comment by getroot** [comment]
@basisbit 
Thanks for letting me know about X-REAL-IP, X-FORWAREDED-FOR.

In order for OME to support this without any security problems, if the user enables X-REAL-IP in the AdmissionWebhooks setting of Server.xml, it will be necessary to set the proxy IP as a required option and allow only connections from nginx.

**Comment by basisbit** [comment]
`*bump*`
Keeping this open because it is a rather common use case, and having the error log contain the public IPv4/IPv6 address can be important for legal reasons.

**Comment by basisbit** [comment]
bump

**Comment by koss89** [comment]
bump

For resolve security you can use case of nginx. 
Explain
Add to config option trustedProxy
if proxy in list trustedProxy (X-FORWARDED-FOR) use ip from X-REAL-IP
