### ISSUE TITLE
Cannot use a system user other than root to start the daemon.

### ISSUE THREAD

**Issue by trapasso** [AirenSoft/OvenMediaEngine#605]
**Describe the bug**
The daemon will not start if you try to use a system user other than root.

**To Reproduce**
1. Add "User=myuser Group=mygroup" to /lib/systemd/system/ovenmediaengine.service
2. Try to start ovenmediaengine service.

**Expected behavior**
It should also run with a non-root system user.
(obviously assigning the bind ports above 1024 and setting the necessary permissions for the configuration and the log files)

**Logs**
NO LOG

**Server (please complete the following information):**
 - OS: ubuntu 18.04
 - OvenMediaEngine Version: 0.12.9
 - Branch: master

**Player (please complete the following information):**
NO PLAYER Used

**Additional context**
The problem is due to the '/var/run/ovenmediaengine.pid' file  permissions.
Attached a patch that allows to pass a parameter with the pid file name.
After the patch it is possible to add the instructions below to the systemd script:
_User=myuser
Group=mygroup
RuntimeDirectory=ovenmediaengine
RuntimeDirectoryMode=0755
PIDFile=/var/run/ovenmediaengine/ovenmediaengine.pid
WorkingDirectory=/usr/share/ovenmediaengine
ExecStart=/usr/bin/OvenMediaEngine -c /etc/ovenmediaengine -d -p /var/run/ovenmediaengine/ovenmediaengine.pid_
**_(obviously assigning the bind ports above 1024 and setting the necessary permissions for the configuration and the log files)_**
Thanks in advance. 
[pid-file.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7746073/pid-file.txt)

**Comment by getroot** [comment]
Thank you again.
If you make a PR, I will merge this.
