### ISSUE TITLE
No Audio in Rtmp to WebRTC stream

### ISSUE THREAD

**Issue by zesquirrelnator** [AirenSoft/OvenMediaEngine#609]
Hey team, I recently completed my setup for an RTMP stream using the OvenStreamEncoder to WebRTC using the command-line-based OME. When I test my steam using the OvenMediaPlayer, I don't hear any audio playback. I eventually tried to add JitterBuffer or change the encoding, but no solution worked. I am currently using the default configuration. 

Does anyone have an answer to this issue? I am currently running my server on a t2.micro instance.

**Comment by zesquirrelnator** [comment]
Just found the fix! I was using OvenMediaEncoder to stream and it seemed to not send any audio. With ffmpeg using aac codec, it was streaming both audio and video.

**Comment by getroot** [comment]
It looks like OvenStreamEncoder couldn't find the microphone on your mobile. I'm closing this issue because it's not an OvenMediaEngine issue. Thank you.
