### ISSUE TITLE
webrtc video lag

### ISSUE THREAD

**Issue by cheluskin** [AirenSoft/OvenMediaEngine#61]
webrtc video stops for a second and half a second with an interval of 4-15 seconds in chrome. Only Windows. MacOS - ok, iOS - ok. the sound does not stop

```
                     <Encodes>
                        <Encode>
                            <Name>HD_VP8</Name>
                            <Audio>
                                <Codec>opus</Codec>
                                <Bitrate>128000</Bitrate>
                                <Samplerate>48000</Samplerate>
                                <Channel>1</Channel>
                            </Audio>
                            <Video>
                                <Codec>vp8</Codec>
                                <Width>1280</Width>
                                <Height>720</Height>
                                <Bitrate>1000000</Bitrate>
                                <Framerate>30.0</Framerate>
                            </Video>
                        </Encode>
                        <Encode>
                            <Name>HD_H264</Name>
                            <Audio>
                                <Codec>opus</Codec>
                                <Bitrate>128000</Bitrate>
                                <Samplerate>48000</Samplerate>
                                <Channel>1</Channel>
                            </Audio>
                            <Video>
                                <Codec>h264</Codec>
                                <Width>1280</Width>
                                <Height>720</Height>
                                <Bitrate>1000000</Bitrate>
                                <Framerate>30.0</Framerate>
                            </Video>
                        </Encode>
                    </Encodes>
```

**Comment by dimiden** [comment]
@cheluskin 
It's a very strange thing. Please attach the ```<Streams>``` of ```Server.xml``` and check if the same symptom occurs after changing the order of ```<Profile>``` of VP8 and H264 in it.

**Comment by cheluskin** [comment]
The order of the profiles is not affected. The fact is that some windows computers work fine. For now, it’s only clear that all such machines use external GPU

**Comment by dimiden** [comment]
@cheluskin 
Thank you for the information.
This symptom is not reproduced on our own PC, so I think we should test it on a PC that uses an external GPU. We will check later when we get an External GPU.

**Comment by rubu** [comment]
@cheluskin 
You could try to check if GPU acceleration is enabled in chrome and disable it (https://www.lifewire.com/hardware-acceleration-in-chrome-4125122) and then check if the same happens (I assume at that point chrome should be using Microsoft Media Foundation as a fallback?). If that works, then the question is - what GPUs are being used to understand if it is NVIDIA NVENC / AMD UVD or smth else. If this is happening without accelerated encoding then the issue is most likely in drawing.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
