### ISSUE TITLE
HDR support

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#610]
Hello,

Are there plans to implement HDR support to OME? 

Also, is OME limited to 1080p or can it stream 4k?

Thank you.

**Comment by llspalex** [comment]
> Also, is OME limited to 1080p or can it stream 4k?

I don't believe there is any limit on resolution (ie. OME is resolution-agnostic). I've streamed in excess of 4K using OME without issues.

**Comment by getroot** [comment]
@zcolor 
(You mean HDR support in WebRTC, right?)

Only the WebRTC forum can plan for HDR support. It will require a lot of planning, including codecs (at least VP9 or AV1), color meta transmission, etc. And maybe the most important thing is that the browser supports it?

If WebRTC supports it, of course OME will support it as well.

**Comment by zcolor** [comment]
> > Also, is OME limited to 1080p or can it stream 4k?
> 
> I don't believe there is any limit on resolution (ie. OME is resolution-agnostic). I've streamed in excess of 4K using OME without issues.

I thought I'd read somewhere that it was limited to 1080p.

> @zcolor (You mean HDR support in WebRTC, right?)
> 
> Only the WebRTC forum can plan for HDR support. It will require a lot of planning, including codecs (at least VP9 or AV1), color meta transmission, etc. And maybe the most important thing is that the browser supports it?
> 
> If WebRTC supports it, of course OME will support it as well.

Ok, thanks!

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.
