### ISSUE TITLE
WebRTC doesn't play in edge browser

### ISSUE THREAD

**Issue by Amirhasanioox** [AirenSoft/OvenMediaEngine#614]
One of my users reported a problem that webrtc doesn't play in edge browser.
I'm using docker version 0.12.9
He tested on demo player.
![Screenshot (5)](https://user-images.githubusercontent.com/22333404/147515739-ecbe15f2-48f3-4243-8219-225b1303f556.png)

**Comment by getroot** [comment]
Could you please rewrite this to the OvenPlayer repo? It seems to be an issue with the browser's WebRTC API.

**Comment by SangwonOh** [comment]
@Amirhasanioox Hi!

He seems to have tested it on the old MS Edge browser. This is because using old MS Edge browsers (known as EdgeHTML. MS Edge versions 12-18) do not follow the WebRTC standard. 

It should work fine in the new replaced MS Edge chromium browsers. Thanks.

**Comment by Amirhasanioox** [comment]
@SangwonOh 
Yes his browser version is old. So it makes sense now.
Is there a list of supported browsers?
I'm actually worried about unsupported browsers. are there only a few of them? or a lot?
Thanks

**Comment by getroot** [comment]
@Amirhasanioox 

All browsers that support WebRTC are supported.  That old ms edge is no longer a browser that supports WebRTC.  This is because they no longer update the changing WebRTC specification (not just WebRTC, all updates are stopped).

**Comment by Amirhasanioox** [comment]
So I don't need to worry :)
Thanks again
