### ISSUE TITLE
Certificates no longer work.

### ISSUE THREAD

**Issue by trapasso** [AirenSoft/OvenMediaEngine#615]
**Describe the bug**
Certificates no longer work, since commit e5291a66. They work well, however, in the previous ones.

**To Reproduce**
1. Arrange a bind to use certificates, and try to connect.

**Expected behavior**
Certificates worked before e5291a66. 

**Logs**
[...] E [...] HttpServer | https_server.cpp:83   | Could not handle connection event: there is no certificate

**Server (please complete the following information):**
 - OS: Ubuntu 18.04
 - OvenMediaEngine Version: 0.12.9
 - Branch: master

**Player (please complete the following information):**
 - Device: PC
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 95.0.1

**Additional context**
It seems that the initialization phase of the orchestrator virtual hosts has been omitted.
Thanx in advance.

**Comment by basisbit** [comment]
can confirm this problem

**Comment by getroot** [comment]
Thank you for reporting!

**Comment by getroot** [comment]
fb87ec444f61459a80329493392d750ff31e3af1

I solved this problem. A recent structural change was missing something. Could you please check if your problem is also solved? thank you.

**Comment by Lorekin** [comment]
Problem still exists

**Comment by getroot** [comment]
@Lorekin did you test with master branch? and what logs did you see?

**Comment by Lorekin** [comment]
> @Lorekin did you test with master branch? and what logs did you see?

![image](https://user-images.githubusercontent.com/26692817/147825937-971cc4a0-3165-47bb-8bc3-ad661632150d.png)

**Comment by getroot** [comment]
@Lorekin I don't know your Server.xml, but maybe 3334 is the tls port.  Logs seem to connect to 3333.  Could you please upload Server.xml and full log?

**Comment by Lorekin** [comment]
> @Lorekin I don't know your Server.xml, but maybe 3334 is the tls port. Logs seem to connect to 3333. Could you please upload Server.xml and full log?

https://pastebin.com/fynWsir8

**Comment by getroot** [comment]
@Lorekin Thank you very much

**Comment by getroot** [comment]
@Lorekin 
I can't reproduce the problem in my environment. I'm sorry, but could you please delete and re-download airensoft/ovenmediaengine:dev and see if the problem is reproduced?

Your log is a little different from mine, what I patched this time is not visible in your log. Maybe you got airensoft/ovenmediaenigne:dev before it was built and uploaded?

Or is there something else wrong? I'll try to reproduce it one more time.

**Comment by getroot** [comment]
This is my logs

```
[01-01 00:25:56.994] I [OvenMediaEngine:2390520] OvenMediaEngine | main.cpp:114  | Trying to create a WebRTC Publisher module
[01-01 00:25:56.994] I [OvenMediaEngine:2390520] Signalling.P2P | rtc_p2p_manager.cpp:27   | P2P is disabled in the configuration
[01-01 00:25:56.995] I [OvenMediaEngine:2390520] Certificate | certificate.cpp:35   | A certificate has been created for VirtualHost [RtcSig]:
        Cert file path: /etc/cert/_airensoft_com.crt
        Chain cert file path: /etc/cert/_airensoft_com_chain.crt
        Private key file path: /etc/cert/_airensoft_com.key
[01-01 00:25:56.997] I [OvenMediaEngine:2390520] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:11000/UDP (0x5555568d57a0)
```

And yours (This is the same log as before the bug was fixed)
```
[2021-12-31 13:32:44.967] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:114  | Trying to create a WebRTC Publisher module
[2021-12-31 13:32:44.968] I [OvenMediaEngine:1] Signalling.P2P | rtc_p2p_manager.cpp:27   | P2P is disabled in the configuration
[2021-12-31 13:32:44.970] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10000/UDP (0x55c27853db50)
```

**Comment by Lorekin** [comment]
> This is my logs
> 
> ```
> [01-01 00:25:56.994] I [OvenMediaEngine:2390520] OvenMediaEngine | main.cpp:114  | Trying to create a WebRTC Publisher module
> [01-01 00:25:56.994] I [OvenMediaEngine:2390520] Signalling.P2P | rtc_p2p_manager.cpp:27   | P2P is disabled in the configuration
> [01-01 00:25:56.995] I [OvenMediaEngine:2390520] Certificate | certificate.cpp:35   | A certificate has been created for VirtualHost [RtcSig]:
>         Cert file path: /etc/cert/_airensoft_com.crt
>         Chain cert file path: /etc/cert/_airensoft_com_chain.crt
>         Private key file path: /etc/cert/_airensoft_com.key
> [01-01 00:25:56.997] I [OvenMediaEngine:2390520] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:11000/UDP (0x5555568d57a0)
> ```
> 
> And yours (This is the same log as before the bug was fixed)
> 
> ```
> [2021-12-31 13:32:44.967] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:114  | Trying to create a WebRTC Publisher module
> [2021-12-31 13:32:44.968] I [OvenMediaEngine:1] Signalling.P2P | rtc_p2p_manager.cpp:27   | P2P is disabled in the configuration
> [2021-12-31 13:32:44.970] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10000/UDP (0x55c27853db50)
> ```

@getroot 
I am reinstall ome
Log:
https://pastebin.com/8WUrUp9w
![image](https://user-images.githubusercontent.com/26692817/147830926-a6c4256f-40ac-4920-866f-1dd0f1fbc6f7.png)

**Comment by getroot** [comment]
@Lorekin 
Thank you so much for your help with testing.
This is really weird, why aren't the logs output from the newly patched code? I'll figure this out soon.

**Comment by Fredcyp** [comment]
@getroot 
Thank you for the fix !
I had this problem too, but for me it works again with the latest 'dev' release on docker.

**Comment by basisbit** [comment]
also works fine here. @Lorekin you'll have to clear your docker local image cache and re-download the newest version of the docker image.

**Comment by trapasso** [comment]
Work fine. Sorry was away.
Very thank.

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.

**Comment by shoaibzafar** [comment]
Hi facing the issue, please help

[2023-07-19 15:15:01.153] E [OvenMediaEngine:1] Certificate | certificate.cpp:47   | Failed to create a certificate for VirtualHost [default]:
        Reason: [default] Could not create a certificate from file - [OpenSSL] error:80000002:system library::No such file or directory (-2147483646)
        Cert file path: origin_conf/osng01.multiplierapp.live.crt
        Chain cert file path: origin_conf/osng01.multiplierapp.live.ca-bundle
        Private key file path: origin_conf/privkey.pem


<Host>
				<Names>
					
					<Name>osng01.multiplierapp.live</Name>
				</Names>
				<TLS>
					<CertPath>osng01.multiplierapp.live.crt</CertPath>
					<KeyPath>privkey.pem</KeyPath>
					<ChainCertPath>osng01.multiplierapp.live.ca-bundle</ChainCertPath>
				</TLS>
			</Host>
			
			certificate files are in same directory as of Server.xml

**Comment by basisbit** [comment]
This here issue was already closed. Please open a new issue instead of writing here.
