### ISSUE TITLE
test RTSP stream using OBS

### ISSUE THREAD

**Issue by Ramy-Ab** [AirenSoft/OvenMediaEngine#616]
Hi OvenMediaEngine team,
I've followed your tutorial to stream an RTMP stream and it worked perfectly but when i tried to stream with RTSP protocol using OBS 
i couldn't do it 
i've attached an image that shows my server.xml configuration, my obs inputs and image error logs 
can u please help me with it ?
also i wanted to know what should i do if i want to run the stream in my react webpage instead of OVM PLAYER ?
>
![Capture](https://user-images.githubusercontent.com/53955511/147700096-14fe2fa9-5e9a-4dac-a9c5-eeb962041d7b.PNG)

**Comment by getroot** [comment]
I know that OBS does not support rtsp. Did you use any special plugins?

Please post any OvenPlayer related questions to the OvenPlayer repo.

**Comment by nxtreaming** [comment]
YES, OBS currently doest not support RTSP muxer

**Comment by Ramy-Ab** [comment]
@getroot @nxtreaming ahh sorry guys it was may bad now im having another type of issue i will create in an other issue

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.
