### ISSUE TITLE
Dedicated encoder vs OBS

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#618]
I'm considering buying a dedicated encoder to use with OME.

Does anyone have any suggestions? I've tried the Blackmagic Web Presenter 4k, but that model could only stream with b-frames and added a lot of latency.

Also, my main interest in getting a dedicated encoder is hopefully being able to cut some more latency. I'm currently getting an average of 10/12 frames latency (25fps base) but I'd love to get it down to 5 if possible. 

My ultimate goal would be to get the streaming down to interactive latency.

Would that even be possible?

**Comment by llspalex** [comment]
I reliably get 6 - 7 frames of latency with RTMP ingest and WebRTC playback. 

Distance from you to the ingest server plays a part, as does OBS encoder settings. I am not aware of any hardware encoders that would reduce latency further. 

Let me know if you are interested in discussing further.

**Comment by zcolor** [comment]
Hey man!

sure, sorry I didn't get a notification of your reply.

Are you using a dedicated encoder or going through OBS?
