### ISSUE TITLE
'demo.ovenplayer.com/demo_input.html' fails to load in http

### ISSUE THREAD

**Issue by nxtreaming** [AirenSoft/OvenMediaEngine#619]
demo.ovenplayer.com/demo_input.html has the following code:

<html>
<body>

<script>
--
  | if (window.location.href.indexOf('localhost') < 0 && window.location.protocol !== 'https:') {
  | location.href = location.href.replace('http://', 'https://');
  | }
  | </script>

</body>
</html>

I can not perform WebRTC input test

Could you remove them?

**Comment by getroot** [comment]
Access to the browser's device (camera, microphone) is only allowed in https.

**Comment by nxtreaming** [comment]
So , we must use wss:// as  WebRTC output url?

**Comment by getroot** [comment]
Yes, you must use wss:// URL to avoid mixed content issue. 
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

**Comment by nxtreaming** [comment]
I see.
Thank,
