### ISSUE TITLE
OME port for Windows?

### ISSUE THREAD

**Issue by pelnar** [AirenSoft/OvenMediaEngine#620]
Hi all, I was wondering if there is already any existing port (fork maybe?) of OME for Windows? I read on FAQ that "Windows and MacOS versions will be available at a later date." which looks promising, but with no more details.
If this does not exist yet, how difficult would you estimate it to be ported for Windows? The general code might not be too complicated to recompile for Windows, however what about the transcoding libraries - might be designed with some specific Linux libraries which might not be that simple to port for Windows? Any other issues from the top of your head?

I was able to get OME running in WSL (v2) on Windows 10 and Docker. However having a native Windows service, console app or other application targeting Windows would be more suitable for our architecture and deployment.

Thanks!

**Comment by getroot** [comment]
OME is not yet for Windows. (As far as I know)
I run OME on Linux as a commercial service, but occasionally run OME on Windows Docker for testing purposes. I have no confidence in running a 24/7 service on Windows. So there is no need to port OME to Windows. But if someone develops and PR for Windows, it would be very interesting.

**Comment by pelnar** [comment]
Thank you!
