### ISSUE TITLE
IOS player app

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#622]
Hi,

Is there an IOS app that can play WebRTC streams compatible with OME?

If you have one for macOS and windows, that would be great to.

I've found a few, but I can't get the stream to play.

Is anyone using an App, or is everyone playing from a browser?

Thanks!

**Comment by getroot** [comment]
You can build whatever you want with the WebRTC Native Library. 

For signaling with OME, refer to the document below.
https://airensoft.gitbook.io/ovenmediaengine/streaming/webrtc-publishing#signalling

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.
