### ISSUE TITLE
High WebRTC latency on CPUs with many threads.

### ISSUE THREAD

**Issue by jeon-juhyun** [AirenSoft/OvenMediaEngine#624]
**Describe the bug**
High WebRTC latency on CPUs with many threads.

**To Reproduce**
1. Set Server.xml as <OutputProfile><Encodes><Codec>h264</Codec></Encodes></OutputProfile>
2. Use OBS 27.1.3
3. use 128 thread cpu (AMD EPYC 7713P)
4. On a CPU with 128 threads, encoding using too many threads.
This may have resulted in faster encoding, but it added more overhead (2.4") to merging the encoding results into one.

**Expected behavior**
There was no problem before v0.12.5.

**Logs**
Please upload the entire OvenMediaEngine.log. You may delete important personal information.

**Server (please complete the following information):**
 - OS: Ubuntu 20.04
 - OvenMediaEngine Version: v0.12.9
 - Branch: master

**Player (please complete the following information):**
 - Device: PC
 - OS: Window 10
 - Browser : chrome
 - Version : 96.0.4664.110

**Additional context**
Performance is improved by making the following modifications.
OvenMediaEngine/src/projects/transcoder/codec/encoder/encoder_avc.cpp Line.73
before : _context->thread_count = FFMAX(4, av_cpu_count() / 3); (2.4")
after : _context->thread_count = FFMIN(4, av_cpu_count() / 3); (0.9")

**Comment by getroot** [comment]
Thanks for the good report. We didn't notice this mistake because we were testing on a 16-core machine. We will fix this issue soon.

**Comment by Keukhan** [comment]
@jeon-juhyun 

Thanks for the great report.

**Comment by Keukhan** [comment]
@jeon-juhyun 

Added a limit on the number of encoding threads to the master version. 
However, due to licensing issues, the master version changed from the x264 codec to the openh264 codec.
If you want to use the x264 codec, please change it in the v0.12.9 branch.

`// Limit the number of threads suitable for h264 encoding to between 4 and 8. `
`_codec_context->thread_count = FFMIN(FFMAX(4, av_cpu_count() / 3), 8);`

Thanks.

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.
