### ISSUE TITLE
Audio only playback (HLS or WebRTC)

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#625]
**Is your feature request related to a problem? Please describe.**
Some users have very low download speed, or data limits, etc. For them it would be nice to offer an audio only version of a stream to be displayed alongside a screenshot of the stream content.

**Describe the solution you'd like**
A WebRTC endpoint (something like stream1_audio or something?) that is audio only, and thus presumably low impact server-side, and low bandwidth.

**Describe alternatives you've considered**
Transcoding to icecast or something is something we looked at, but the latency is unacceptable and it's pretty clunky.

**Comment by getroot** [comment]
You can create an audio only stream by adding an OutputProfile as in the example below.

```
<OutputProfiles>
	<OutputProfile>
		<Name>bypass_stream</Name>
		<OutputStreamName>${OriginStreamName}</OutputStreamName>
		<Encodes>
			<Audio>
				<Bypass>true</Bypass>
			</Audio>
			<Video>
				<Bypass>true</Bypass>
			</Video>
			<Audio>
				<Codec>opus</Codec>
				<Bitrate>128000</Bitrate>
				<Samplerate>48000</Samplerate>
				<Channel>2</Channel>
			</Audio>
		</Encodes>
	</OutputProfile>
	<OutputProfile>
		<Name>audio_webrtc_stream</Name>
		<OutputStreamName>${OriginStreamName}_audio</OutputStreamName>
		<Encodes>
			<Audio>
				<Bypass>true</Bypass>
			</Audio>
			<Audio>
				<Codec>opus</Codec>
				<Bitrate>128000</Bitrate>
				<Samplerate>48000</Samplerate>
				<Channel>2</Channel>
			</Audio>
		</Encodes>
	</OutputProfile>
</OutputProfiles>
```

**Comment by naanlizard** [comment]
Ah that's perfect, I should've expected I could do that.

Do we have any idea what performance is like with this?

**Comment by getroot** [comment]
I didn't understand the performance related question.

Perhaps a concern that OME can encode twice if you set two OutputProfiles? No, if the `<Audio>` and `<Video>` settings are the same, it is encoded only once and used in two streams.

**Comment by getroot** [comment]
I closed this issue because it has been inactive for a long time. If further discussion is needed, please do not hesitate to reopen the issue.
