### ISSUE TITLE
Webrtc push stream minimum bit rate

### ISSUE THREAD

**Issue by yginuo** [AirenSoft/OvenMediaEngine#627]
Webrtc dynamically calculates the bit rate of the push stream according to the bandwidth. At the beginning of the push stream, the picture will be blurred, and as the real-time bit rate increases, the picture will become clearer. But I still hope webrTC will have good video resolution in the first few seconds after the stream is pushed. Could you please set SDP to set the minimum bit rate?

Device: pc
OS: windows11
Browser：Google Chrome 96.0.4664.45
OvenMediaEngine Version: v0.12.7
push tool：OvenLiveKit-Web v1.0.2

**Comment by getroot** [comment]
Could you please rewrite the issue to the OvenLiveKit repo?
It would be good if you write a specific way to set the minimum bitrate as well.

https://github.com/AirenSoft/OvenLiveKit-Web

**Comment by yginuo** [comment]
I solved this problem, it can be solved by SDP parameter.

````
a=fmtp:100 packetization-mode=1;profile-level-id=42e01f;level-asymmetry-allowed=1;x-google-max-bitrate=6000;x-google-min-bitrate=4000;x-google -start-bitrate=4000
````

1. x-google-start-bitrate: start bitrate
2. x-google-min-bitrate: minimum bitrate
3. x-google-max-bitrate: Maximum bitrate

**Comment by yginuo** [comment]
To be set before `setRemoteDescription`
