### ISSUE TITLE
How can I ensure a signal send in obs with rtmp with authentication without the need for nginx?

### ISSUE THREAD

**Issue by CorsarioPTY** [AirenSoft/OvenMediaEngine#628]
Before asking for help, please read the troubleshooting section in the manual carefully.
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting

Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

** PROBLEM **

I have the need to ensure a signal sending in obs with rtmp with authentication without the need for nginx for a live transmission that is 24/7.

** EXPECTATION **

I need help to enable the sending of signal in obs for rtmp with authentication without the need for nginx for a live transmission that is 24/7 as other systems have it like wowza for example.

** ENVIRONMENTAL INFORMATION **

- OvenMediaEngine Information

Version v0.12.9

- Encoder information

What encoder are you using? (E.g. OBS 10.22) And how is the codec set on that encoder?

OBS 27.1.3

- Player information

We have not yet reached the player part

- URL

We have not yet reached the player part

- Operating system and version

Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-43-generic x86_64)

** SETUP INFORMATION AND LOGS **

[Server.xml](https://github.com/AirenSoft/OvenMediaEngine/files/7834469/Server.txt)

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/7834466/ovenmediaengine.log)

** OTHER HELPFUL INFORMATION **

I need to protect the signal sent by obs to the OvenMediaEngine server.

**Comment by getroot** [comment]
You can do what you want using SignedPolicy or AdmissionWebhooks.

https://airensoft.gitbook.io/ovenmediaengine/access-control

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.

**Comment by CorsarioPTY** [comment]
ok thanks... let's see if they help me much better and tell me exactly what the code would be to create the SignedPolicy URL using the script but only to use a password to send by OBS, that is, I don't want an expiration date or what restrict by ip, i just want to use a password to send by rtmp to the ovenmediaengine?
