### ISSUE TITLE
OME health cheking

### ISSUE THREAD

**Issue by eses88** [AirenSoft/OvenMediaEngine#631]
I have a question.
How can i check OME status continuosly?
For example, I want checking OME is keep alive.
I have considerd using API server of OME to health checking.

Please notify or recommand to me any method.

**Comment by getroot** [comment]
As you said, you can call the API continuously, or you can connect to the webrtc signaling port, or you can keep checking the process. There are many ways.

**Comment by Arzar** [comment]
Still, it would be nice to have an HTTP endpoint, like /health returning 200 when everything is ok, because load balancer like AWS application load balancer expect one.

**Comment by getroot** [comment]
@Arzar 
good idea.
But implementing "everything is ok" is very broad or vague. Do you have specific ideas?

**Comment by bchah** [comment]
I use `/api/v1/hosts` to check that the engine is alive:

`{"message":"OK","response":["default"],"statusCode":200}`

**Comment by eses88** [comment]
@getroot @Arzar  Thank you for the reply! 
@bchah I'll try the method you used. Thank you!

**Comment by getroot** [comment]
This issue has been closed because it appears to be resolved. If you would like to discuss this issue further, please reopen.

Thank you @bchah
