### ISSUE TITLE
Is this project supports cctv rtsp streams to webrtc from raspberry pi 4.

### ISSUE THREAD

**Issue by anand-010** [AirenSoft/OvenMediaEngine#632]
I am looking for a streaming my cctv rtsp stream to webrtc. I have already tested many rtsp to webrtc implementations it works normally when using same network not on wan.
I have found it this project supports on arm64 docker container.
is it possible to stream my rtsp h.264 streams to webrtc from a raspberry pi without  a server (not signaling server).
If it is possible guide me.
Thank you.

**Comment by getroot** [comment]
You can install OvenMedianEngine on your raspberry pi 4 and pull a local rtsp stream to provide streaming over WebRTC. But I don't have a raspberry pi 4, so I don't know if OvenMediaEngine will install well there.

For rtsp pull, refer to the manual below.

https://airensoft.gitbook.io/ovenmediaengine/live-source/rtsp-pull-beta

**Comment by anand-010** [comment]
![WhatsApp Image 2022-01-12 at 4 42 58 PM](https://user-images.githubusercontent.com/32414977/149163326-1a60f54a-02f4-4e7c-ad90-bc7592854318.jpeg)
it detects as linux/arm64/v8 i think it is same as linux/arm64 some kind of checking error happening there.
