### ISSUE TITLE
Detect when an RTMP stream stops 

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenMediaEngine#638]
**Is your feature request related to a problem? Please describe.**

We run a streaming website, we're currently using nginx-rtmp to ingest incoming RTMP streams, we'd like to switch to OME. However one nginx-rtmp feature we rely on is the ability to call a webhook when an RTMP stream stops, so we can update our database and mark that stream as offline. Is there a similar feature in OME?

**Describe the solution you'd like**

The ability to add a webhook that gets called when a stream disconnects from OME

**Describe alternatives you've considered**

A less-performant alternative would be to constantly monitor the `/v1/vhosts/{vhost_name}/apps/{app_name}/streams` endpoint and use that to check which streams are still online

**Comment by getroot** [comment]
https://github.com/AirenSoft/OvenMediaEngine/issues/595

It is duplicated issue. 
Thank you.
