### ISSUE TITLE
I want to stream to ovenmediaengine with udp://ip:port (MPEG-2 TS) and play HLS with HTTPS using TLS security. It's possible?

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#639]

**Comment by getroot** [comment]
It's possible. 

[MPEG-2 TS Input]
https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta

[HLS]
https://airensoft.gitbook.io/ovenmediaengine/streaming/hls-mpeg-dash

**Comment by Mariano245** [comment]
thanks for answering. I managed to stream mpeg-2 TS with udp and play HLS, WEBRTC with TLS encryption...Only one problem, the playback always fails, it looks very pixelated and after a few seconds it can't continue playing, it is necessary to restart ovenmediaengine. I am using ovenmediaengine 0.12.1. With any other upload protocol, be it rtmp, srt, etc. the playback (HLS, WEBRTC, MPEG DASH) works very well.

**Comment by getroot** [comment]
First, use the latest OvenMediaEngine. The latest release is 0.12.10.

If it plays well with RTMP and SRT and the stream is interrupted with MPEG2-TS/udp, udp packet loss is suspected.

For a more detailed analysis, more details are needed. The ovenmediaengine.log file is required.

Which encoder is sending MPEG2-TS? Does the device transmit with H.264 and AAC codecs? What are the detailed options for the codec? Does the stream have a B-Frame or a profile other than baseline?

**Comment by Mariano245** [comment]
Hello, to transmit to the ovenmediaengine I use a software called IP VIDEO TRANSCODING LIVE (udp://122.94.147.124:4000 with h264 video encoding, AAC-LC audio encoding , profile baseline)

Also use FFMPEG to encode and stream a clip, as the following link suggests (https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta)

ffmpeg.exe -re -stream_loop -1 -i C:\ffmpeg\bin\video.mp4 -c:v libx264 -bf 0 -x264-params keyint=30:scenecut=0 -acodec aac -pes_payload_size 0 -f mpegts udp://122.94.147.124:4000?pkt_size=1316

Playback: (https://122.94.147.124:443/app/stream_4000/playlist.m3u8)

the data thrown by ovenmediaengine.log when playback fails is: 

[2022-01-18 16:06:37.571] E [Decaac:2245] FFmpeg | third_parties.cpp:110  | [AVCodecContext: 0x7f6888052880] get_buffer() failed
[2022-01-18 16:06:37.571] E [Decaac:2245] Transcoder | decoder_aac.cpp:147  | Error sending a packet for decoding : AVERROR(EINVAL)
[2022-01-18 16:06:37.571] W [Decaac:2245] FFmpeg | third_parties.cpp:114  | [AVCodecContext: 0x7f6888052880] Sample rate index in program config element does not match the sample rate index configured by the container.
[2022-01-18 16:06:37.571] E [Decaac:2245] FFmpeg | third_parties.cpp:110  | [AVCodecContext: 0x7f6888052880] Inconsistent channel configuration.

this data is repetitive, just attach a sample.
I use ovenmediaengine version 0.12.1

**Comment by getroot** [comment]
For me to analyze your problem, you should use OvenMediaEngine 0.12.10 or the master branch.

**Comment by Mariano245** [comment]
Okay, thanks, I'll install the latest version of ovenmediaengine, I'll do the tests and let you know. Greetings.

**Comment by Mariano245** [comment]
upgrading to ovenmediaengine 0.12.10, it works fine at least locally, the problem seems solved. Thank you
