### ISSUE TITLE
WebRtc audio only stream

### ISSUE THREAD

**Issue by 4matic** [AirenSoft/OvenMediaEngine#64]
Good day,

I wanted to stream audio only via webrtc using ffmpeg.
Is it possible?

Best regards,

**Comment by dimiden** [comment]
@4matic 
Unfortunately OvenMediaEngine doesn't support video/audio only stream right now, we'll implement it soon.

**Comment by 4matic** [comment]
@dimiden
Okey, I really waiting this feature then

**Comment by dbContext** [comment]
@4matic 

For now you can set the video bitrate within your encoder (OBS) to 1kb/s, setup no video source so it's a blank video and set the video FPS to 1

You can also remove the <Video> XML element in the <Encode> XML element in the OME config (Server.xml)

And then just hide the video html5 player and/or utilise the OvenPlayer API to build your own audio only player so u can have still audio level controls and play/pause

Hope that helps.

**Comment by getroot** [comment]
This issue will continue in #79 
Thank you for your suggestion.

**Comment by getroot** [comment]
We just committed code to the dev branch that allows audio only and video only streams in RTMP. (https://github.com/AirenSoft/OvenMediaEngine/commit/c69a79572847d49b93c6c0ff27f4b7a39538a1d9)

Please check post #79  for more details or to communicate.
