### ISSUE TITLE
Version 0.12.10 not published on Docker Hub

### ISSUE THREAD

**Issue by HCl-not-HCi** [AirenSoft/OvenMediaEngine#643]
**Describe the bug**
Hey, it seems like v0.12.10 is not published on Docker Hub.

Could you publish it? Thanks :)

**To Reproduce**
Try to pull `airensoft/ovenmediaengine:0.12.10` using Docker

**Expected behavior**
Ability to pull v0.12.10 using the tag 0.12.10 or latest from Docker Hub

**Comment by getroot** [comment]
oh i missed it I will upload it soon.

**Comment by getroot** [comment]
I pushed both :0.12.10 and :0.12.11 .
