### ISSUE TITLE
record error

### ISSUE THREAD

**Issue by cl84** [AirenSoft/OvenMediaEngine#645]
when I log an rtmp or mpegts stream after a few seconds it stops logging and returns the following errors in the logs

[2022-01-21 16:10:37.454] E [StreamWorker:30957] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f7e88022380] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 219920 >= 219920
[2022-01-21 16:10:37.454] E [StreamWorker:30957] FileWriter | file_writer.cpp:394  | error = -22

**Comment by getroot** [comment]
It looks like your encoder is sending the wrong timestamp.  If not, please provide a way to reproduce this issue.

Please provide information about the encoder you are using and your Server.xml.  And please provide the procedure how to reproduce it.

**Comment by cl84** [comment]
I use ffmpeg to restream with the following command:
ffmpeg -i 'rtsp://admin:270972@192.168.1.46:554/cam/realmonitor?channel=1&subtype=0&unicast=true' -ac 2 -acodec aac -vcodec copy -f flv -ar 44100 rtmp://127.0.0.1/app/camera2

the configuration file is the following:
<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		<Managers>
			<API>
				<Port>8081</Port>
				<WorkerCount>1</WorkerCount>
				<TLSPort>8082</TLSPort>
			</API>
		</Managers>
		
		<Providers>
			
			<RTSPC>
				<WorkerCount>10</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>1935</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>4000-4010/tcp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					
					<WorkerCount>10</WorkerCount>
				</Signalling>

				<IceCandidates>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>

					<IceCandidate>*:10000/udp</IceCandidate>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
				
				
				
				
				
				
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					<TLSPort>3334</TLSPort>
					<WorkerCount>10</WorkerCount>
				</Signalling>
				<IceCandidates>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>

					<IceCandidate>*:10000/udp</IceCandidate>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			<TLS>
				<CertPath>/etc/apache2/ssl/apache.crt</CertPath>
                                <KeyPath>/etc/apache2/ssl/apache.key</KeyPath>
				
			</TLS>
		</Host>
		<API>
			<AccessToken>tauro@2017</AccessToken>
		</API>
	</Managers>
	
	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
				<TLS>
					<CertPath>/etc/apache2/ssl/apache.crt</CertPath>
					<KeyPath>/etc/apache2/ssl/apache.key</KeyPath>
					
				</TLS>
				
			</Host>

			

			

			
			<Origins>
				<Properties>
                                        <NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
                                        <UnusedStreamDeletionTimeout>60000</UnusedStreamDeletionTimeout>
                                </Properties>
                                <Origin>
                                        <Location>/app/</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>127.0.0.1:554/</Url></Urls>
                                        </Pass>
                                </Origin>
                        </Origins>
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000-4010</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<RTMPPush>
						</RTMPPush>
						<FILE>
                                                        <RootPath>/var/www/html/Registrazioni</RootPath>
                                                        <FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}_${Sequence}.mp4</FilePath>
                                                        <InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
                                                </FILE>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							
							<UTCTiming>
								<Scheme>urn:mpeg:dash:utc:http-xsdate:2014</Scheme>
								<Value>/time?iso&amp;ms</Value>
							</UTCTiming>
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							
							<UTCTiming />
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by Keukhan** [comment]
@cl84 

It is thought that there is a problem with the video track in the RTSP stream of the camera.  The dts value of the video packet should be increased sequentially, but it does not seem to be the case. 

Can I access the rtsp camera from an public network? or, if you send me the dumped TS file using ffmpeg, I will find a solution. 

Thanks,.

**Comment by Keukhan** [comment]
@cl84 

Another solution is try encoding the video codec instead of the copy option in the ffmpeg command and sending it.

ffmpeg -i 'rtsp://admin:270972@192.168.1.46:554/cam/realmonitor?channel=1&subtype=0&unicast=true' -ac 2 -acodec aac -vcodec **copy** -f flv -ar 44100 rtmp://127.0.0.1/app/camera2

to 

ffmpeg -i 'rtsp://admin:270972@192.168.1.46:554/cam/realmonitor?channel=1&subtype=0&unicast=true' -ac 2 -acodec aac -vcodec **libx264** -f flv -ar 44100 rtmp://127.0.0.1/app/camera2

Thanks

**Comment by cl84** [comment]
would it not be possible to eliminate the control of the dts?
the stream part in webrtc works correctly and without problems, not only the recording part goes

Thank you

**Comment by cl84** [comment]
The source specifically is a dahua ip camera, I can't in any way make a restream of the rtsp stream without giving dts errors.

I have also tried with other ip cameras and I have the same problem.

Is it possible that you fail to record a live camera stream with ome?

**Comment by getroot** [comment]
I think the best solution would be to make ffmpeg send the correct pts and dts. I did a Google search for you.

https://stackoverflow.com/questions/46796992/ffmpeg-flv-0xbeee10-non-monotonous-dts-in-output-stream

https://stackoverflow.com/questions/65634283/ffmpeg-livestream-by-ip-camera-with-a-problem-of-dts

Keywords like genpts, igndts, use_wallclock_as_timestamps, -re might help you.

If you find a solution in the ffmpeg community or elsewhere, please share your experiences for users of OME.

**Comment by getroot** [comment]
I closed this issue because it has been inactive for a long time. If further discussion is needed, please do not hesitate to reopen the issue.
