### ISSUE TITLE
Webrtc signaling server not works with reverse proxy.

### ISSUE THREAD

**Issue by anand-010** [AirenSoft/OvenMediaEngine#647]
**Describe the bug**
I am installed oven media engine on my local machine and tried to access the webrtc stream by tunneling port 3333 using ngrok to access it over internet.
I am tried it on the same network but the player not working and it shows this error on the console.
```
Object
code: 511
message: "Connection with low-latency(OME) terminated unexpectedly."
reason: "Unexpected end of connection."
[[Prototype]]: Object
```
On the network session I've noticed that the sdp values are exchanged successfully over the WebSocket (tunneled through ngrok) but the player not working.
![network](https://user-images.githubusercontent.com/32414977/150675271-88316dca-be8f-4fd7-8a2c-4fb3dae93be8.PNG)

**To Reproduce**
1. ngrok your signaling port 3333 as http to the cloud.
2. create a rtmp pull stream using mobile application.
2. use the ngrok link to play on oven media engine demo(without tls).

**Expected behavior**
Playing live videos over tunneled signaling server.

**Player (please complete the following information):**
 - Browser [e.g. stock browser, safari] Edge chromium based.

**Comment by getroot** [comment]
After signaling is complete, the stream is sent to TcpRelay or IceCandidate in Server.xml.

**Comment by anand-010** [comment]
I am sorry i don't know the inner workings.
But i have tested it with local websocket and it's worked.
I am tested the tunneled websocket on the same machines and it's not worked.
In my observation only thing i've changed is the websocket connection but from the browsers network connection it's also woking.
What causes this error.
How do i fix it.
Here is my [Server.xml](https://pastebin.com/raw/xZu9DgNb)

**Comment by getroot** [comment]
Please describe your network configuration.

**Comment by getroot** [comment]
I don't know anything about ngrok, so you probably need some advice from someone who knows ngrok and webrtc well. (I initially thought it was something like nginx, but it doesn't seem to be.)

Obviously, I don't think this is a bug in OME.

Anyway, importantly, OME delivers <IP:Port> set in TcpRelay or IceCandidate when exchanging SDP to 3333(default) signaling port. The player connects to this <IP:Port> (ICE Protocol) to request a real video stream, and the real video is delivered to this session (RTP/SRTP).

When using ngrok, check if this behavior is possible.

**Comment by anand-010** [comment]
Don't think about ngrok it's somewhat same as portforwading.
If i portforward 3333 port to the public is it work?.
do i need to open any other support ports.
in my understanding webrtc only uses signaling server for connection extablishment and other ports doesn't need to be opened (works with behind nat throgh UDP punch hole technique).
In my case signaling is alredy worked there must be some initialization error going on webrtc connection.

**Comment by getroot** [comment]
> Anyway, importantly, OME delivers <IP:Port> set in TcpRelay or IceCandidate when exchanging SDP to 3333(default) signaling port. The player connects to this <IP:Port> (ICE Protocol) to request a real video stream, and the real video is delivered to this session (RTP/SRTP).

I already answered to the question. You must open IP:Port in TcpRelay or IceCandidate of Server.xml

This information (which port to open on the firewall) is well documented in the manual.

OME doesn't desigend as WebRTC P2P client but also Streaming Server. It assumes OME runs on public network.

**Comment by anand-010** [comment]
Understand it only uses the low latency and browser support  feature of webrtc.
It uses port forwarding because it's reliable and doesn't need turn servers write?.
 Is there any way I can use traditional p2p webrtc with oven media engine.
In my case i am running oven media engine on my local server behind nat.

**Comment by getroot** [comment]
Set <TcpForce>true</TcpForce> . And in <TcpRelay>, set the public ip and port of your NAT device.

Then, port forwarding the port set in TcpRelay on your NAT device to the port of your internal device.

OME cannot work as a p2p client.

**Comment by getroot** [comment]
I closed this issue because it has been inactive for a long time. If further discussion is needed, please do not hesitate to reopen the issue.
