### ISSUE TITLE
RTMP(S) with Stunnel for Facebook Live screen audio missing

### ISSUE THREAD

**Issue by younes200** [AirenSoft/OvenMediaEngine#648]
**PROBLEM**
Hi,
Since OME does not yet support RTMPS, I'm relying on Stunnel to re-stream the feed to Facebook Live, but with the default stream output, the audio is missing and stream breaks every few seconds, facebook logs shows : 

`Facebook has not received video signal from the video source for some time. Check that the connectivity between the video source and Facebook is sufficient for the source resolution and bitrate. Check your video encoder logs for details. If problems persist, consider improving connection quality or reducing the bitrate of your video source.`

When using this custom output profile that match facebook video/audio format (h264,aac) OME is not able to find the origin stream : 

```xml
<OutputProfile>
    <Name>facebook_stream</Name>
    <OutputStreamName>${OriginStreamName}_facebook</OutputStreamName>
    <Encodes>
        <Video>
          <Bypass>false</Bypass>
          <Codec>h264</Codec>
          <Width>640</Width>
          <Bitrate>350000</Bitrate>
          <Framerate>30.0</Framerate>
        </Video>
      <Audio>
          <Bypass>false</Bypass>
          <Codec>aac</Codec>
          <Bitrate>128000</Bitrate>
          <Samplerate>48000</Samplerate>
          <Channel>2</Channel>
      </Audio>
    </Encodes>
</OutputProfile>	

```

OME returns this error in logs :  

`[2022-01-24 12:50:39.822] E [SPAPISvr-T8081:10] Orchestrator | orchestrator.cpp:478  | Could not find Origin for the stream: [#default#app/test_facebook]`

I'm publishing the stream with the start push API: 

```bash
curl --location --request POST 'https://api:8081/v1/vhosts/default/apps/app:startPush' \
--header 'authorization: Basic b21lLWFjY2Vzcy10b2tlbg==' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": "test",
    "stream": {
        "name": "test_facebook"
    },
    "protocol": "rtmp",
    "url": "rtmp://stunnel:19350/rtmp,
    "streamKey": "XXXX"
}'
```

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

using docker image : `airensoft/ovenmediaengine:latest`

- Encoder information

Using OvenLiveKit for WebRTC publishing

- Operating system and version

Docker environment 

Any help will be very appreciated 
Thank you.

**Comment by getroot** [comment]
Do you have "test" stream? Please upload full ovenmediaengine.log file

**Comment by Keukhan** [comment]
The set video bit rate is too low at 350 Kbps. That's why I think there's an error message on Facebook Live.
Increase the bitrate value to more than 3 Mbps.

**Comment by younes200** [comment]
Thank you very much for you quick answer, increasing the bit rate solves the problem 👍🏽
