### ISSUE TITLE
only encode/decode audio

### ISSUE THREAD

**Issue by notedit** [AirenSoft/OvenMediaEngine#65]
Hi:

I do not want to decode and reencode the video,  i want to use h264 video codec only. 

Can i do that?

**Comment by dimiden** [comment]
@notedit 
Hi. We are currently developing a bypass function that transmits without transcoding. It will be released soon.

**Comment by 2k9laojia** [comment]
Hi, When will this feature be released?

**Comment by getroot** [comment]
This feature was developed in dev branch. Currently available on DEV. Details and configuration will be updated in the documentation soon after merging into the master branch.

**Comment by getroot** [comment]
New information will be updated in the future at #28 .
