### ISSUE TITLE
today install problem

### ISSUE THREAD

**Issue by cynbangkok** [AirenSoft/OvenMediaEngine#650]
(curl -LOJ https://github.com/AirenSoft/OvenMediaEngine/archive/v0.12.9.tar.gz && tar xvfz OvenMediaEngine-0.12.9.tar.gz)
OvenMediaEngine-0.12.9/misc/prerequisites.sh
command not work

**Comment by getroot** [comment]
This seems to be working fine.
If the issue continues to reproduce, please let me know how I can reproduce it.

**Comment by cynbangkok** [comment]
ok
 i think my host have problem.
