### ISSUE TITLE
Edge Server does not work

### ISSUE THREAD

**Issue by kimkucheol** [AirenSoft/OvenMediaEngine#651]
Before asking for help, please read the troubleshooting section in the manual carefully.
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting

Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

**PROBLEM**

I have configured a cluster with OvenmediaEngine.
I'm testing with OBS, and when I broadcast to the origin server being configured,
If you connect to the Origin server, you can watch the broadcast, but the Edge server cannot connect.

What did I do wrong with the settings?

**EXPECTATION**

I hope the Edge Server works.

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
- OvenMediaEngine-0.12.9.tar.gz
- Manual install

Please check whether it is reproduced in the master branch first. The Docker image for the master branch is airensoft/ovenmediaengine:dev .
If you are using the Master branch, please write Master.
If you are using Release, please write the version (eg 0.12.4).
If you are using Docker by building it yourself, please tell us what version of the image you built.
If you are using a public Docker image, please provide the image path with tags. (e.g. airensoft/ovenmediaengine:0.12.8)

- Encoder information

 OBS 27.1.3 
 rtmp://49.247.36.145:1935/app/stream

What encoder are you using?(e.g. OBS 10.22) And how is the codec set on that encoder?
If you are using OvenLiveKit as an encoder, please let me know if it reproduces here https://demo.ovenplayer.com/demo_input.html. And please tell me what error is output in the browser's developer console.
If you are using RTSP Pull, please let me know which RTSP server you are using.

- Player information

http://demo.ovenplayer.com

- URL
success  ws://49.247.36.145:3333/app/stream
failed      ws://49.247.36.174:3333/app/stream  (Connection Low-latency server failed)
--

- Operating system and version

Origin Server - Ubuntu 20.04 (Kernel 5.14.7-051407-generic)
Edge Server  - Ubuntu 20.04 (Kernel 5.14.7-051407-generic)

**SETUP INFORMATION AND LOGS**

Please upload Server.xml.
Please upload the entire file /var/log/ovenmediaengine/ovenmediaengine.log. (You may delete your personal information.)
It's hard to find the problem if you post only part of the log. Be sure to upload the entire file.

**OTHER HELPFUL INFORMATION**

Please write any information that anyone viewing this issue can reference.
[Edge_ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/7939042/Edge_ovenmediaengine.log)
[Origin_ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/7939043/Origin_ovenmediaengine.log)
[Edge_Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7939047/Edge_Server.xml.txt)
[Origin_Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/7939048/Origin_Server.xml.txt)

**Comment by getroot** [comment]
You seem to have uploaded the wrong log file. There are no traces of player attempts to connect in the edge log. If this isn't a bad log, maybe it's a firewall issue. First try to allow the player to "connect" to the edge.

The origin log is also not a full file. All important parts like rtmp input, stream creation are all deleted.

I found a few things wrong in the edge_server.xml file.

Have you set it up as below? The server will not run because the last is not `</Port>` .
`<WebRTC><Signalling><Port>${env:OME_SIGNALLING_PORT:3333}<Port>`

And the most important `<Origins>` setting in Edge is weird. It's not your origin server's IP (49.247.36.145), and if you try to play /app/stream, the edge will pull the origin server's app/stream_720. stream_720 is not visible in your origin setting.

Below is your edge setting.
```
<Origins>
<Properties>
        <NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
        <UnusedStreamDeletionTimeout>60000</UnusedStreamDeletionTimeout>
</Properties>
<Origin>
        <Location>/app/stream</Location>
        <Pass>
                <Scheme>ovt</Scheme>
                <Urls>
                        <Url>10.6.1.115:9000/app/stream_720</Url>
                        <Url>10.6.3.64:9000/app/stream_720</Url>
                </Urls>
        </Pass>
</Origin>
<Origin>
        <Location>/app/</Location>
        <Pass>
                <Scheme>ovt</Scheme>
                <Urls>
                        <Url>10.6.1.115:9000/app/</Url>
                        <Url>10.6.3.64:9000/app/</Url>
                </Urls>
        </Pass>
</Origin>
<Origin>
        <Location>/</Location>
        <Pass>
                <Scheme>ovt</Scheme>
                <Urls>
                        <Url>10.6.1.115:9000/</Url>
                        <Url>10.6.3.64:9000/</Url>
                                <!--
                                <Url>${env:DEFAULT_ORIGIN_SERVER:}:${env:DEFAULT_ORIGIN_PORT:9000}/</Url>
                                -->
                </Urls>
        </Pass>
</Origin>
<Origin>
```

I think it would be better to read the manual as a whole and set it up well again.

https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering

**Comment by getroot** [comment]
And please edit the title in English.

**Comment by getroot** [comment]
I closed this issue because it has been inactive for a long time. If further discussion is needed, please do not hesitate to reopen the issue.
