### ISSUE TITLE
Ubuntu 18.04LTS Install fails 

### ISSUE THREAD

**Issue by LorcyTF** [AirenSoft/OvenMediaEngine#654]
after running

(curl -LOJ https://github.com/AirenSoft/OvenMediaEngine/archive/v0.12.9.tar.gz && tar xvfz OvenMediaEngine-0.12.9.tar.gz)
OvenMediaEngine-0.12.9/misc/prerequisites.sh

the console says that: 
     ^~~~~~
In file included from /tmp/srt/haicrypt/cryspr-openssl.h:24:0,
                 from /tmp/srt/haicrypt/cryspr-config.h:9,
                 from /tmp/srt/haicrypt/cryspr.h:39,
                 from /tmp/srt/haicrypt/hcrypt.h:52,
                 from /tmp/srt/haicrypt/cryspr-openssl.c:20:
/opt/ovenmediaengine/include/openssl/aes.h:97:5: note: declared here
 int AES_wrap_key(AES_KEY *key, const unsigned char *iv,
     ^~~~~~~~~~~~
/tmp/srt/haicrypt/cryspr-openssl.c: In function ‘crysprOpenSSL_KmUnwrap’:
/tmp/srt/haicrypt/cryspr-openssl.c:166:5: warning: ‘AES_unwrap_key’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
     return(((wraplen - HAICRYPT_WRAPKEY_SIGN_SZ) == (unsigned int)AES_unwrap_key(kek, NULL, sek, wrap, wraplen)) ? 0 : -1);
     ^~~~~~
In file included from /tmp/srt/haicrypt/cryspr-openssl.h:24:0,
                 from /tmp/srt/haicrypt/cryspr-config.h:9,
                 from /tmp/srt/haicrypt/cryspr.h:39,
                 from /tmp/srt/haicrypt/hcrypt.h:52,
                 from /tmp/srt/haicrypt/cryspr-openssl.c:20:
/opt/ovenmediaengine/include/openssl/aes.h:101:5: note: declared here
 int AES_unwrap_key(AES_KEY *key, const unsigned char *iv,
     ^~~~~~~~~~~~~~
[ 68%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt.c.o
[ 70%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_ctx_rx.c.o
[ 72%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_ctx_tx.c.o
[ 75%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_rx.c.o
[ 77%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_sa.c.o
[ 79%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_tx.c.o
[ 81%] Building C object CMakeFiles/srt_virtual.dir/haicrypt/hcrypt_xpt_srt.c.o
[ 83%] Building CXX object CMakeFiles/srt_virtual.dir/haicrypt/haicrypt_log.cpp.o
[ 83%] Built target srt_virtual
Scanning dependencies of target srt_shared
[ 85%] Building C object CMakeFiles/srt_shared.dir/cmake_object_lib_support.c.o
[ 87%] Linking CXX shared library libsrt.so
[ 87%] Built target srt_shared
Scanning dependencies of target srt-live-transmit
Scanning dependencies of target srt-tunnel
[ 89%] Building CXX object CMakeFiles/srt-live-transmit.dir/apps/srt-live-transmit.cpp.o
[ 91%] Building CXX object CMakeFiles/srt-tunnel.dir/apps/srt-tunnel.cpp.o
[ 93%] Linking CXX executable srt-live-transmit
[ 93%] Built target srt-live-transmit
Scanning dependencies of target srt-file-transmit
[ 95%] Building CXX object CMakeFiles/srt-file-transmit.dir/apps/srt-file-transmit.cpp.o
[ 97%] Linking CXX executable srt-tunnel
[ 97%] Built target srt-tunnel
[100%] Linking CXX executable srt-file-transmit
[100%] Built target srt-file-transmit
[ 68%] Built target srt_virtual
[ 72%] Built target srt_shared
[ 87%] Built target srtsupport_virtual
[ 91%] Built target srt-live-transmit
[ 95%] Built target srt-tunnel
[100%] Built target srt-file-transmit
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/ovenmediaengine/lib/libsrt.so.1.4.2
-- Installing: /opt/ovenmediaengine/lib/libsrt.so.1
-- Up-to-date: /opt/ovenmediaengine/lib/libsrt.so
-- Set runtime path of "/opt/ovenmediaengine/lib/libsrt.so.1.4.2" to ""
-- Installing: /opt/ovenmediaengine/include/srt/version.h
-- Installing: /opt/ovenmediaengine/include/srt/srt.h
-- Installing: /opt/ovenmediaengine/include/srt/logging_api.h
-- Up-to-date: /opt/ovenmediaengine/include/srt/access_control.h
-- Installing: /opt/ovenmediaengine/include/srt/platform_sys.h
-- Installing: /opt/ovenmediaengine/include/srt/udt.h
-- Installing: /opt/ovenmediaengine/lib/pkgconfig/haisrt.pc
-- Installing: /opt/ovenmediaengine/lib/pkgconfig/srt.pc
-- Installing: /opt/ovenmediaengine/bin/srt-live-transmit
-- Set runtime path of "/opt/ovenmediaengine/bin/srt-live-transmit" to ""
-- Up-to-date: /opt/ovenmediaengine/bin/srt-live-transmit
-- Installing: /opt/ovenmediaengine/bin/srt-file-transmit
-- Set runtime path of "/opt/ovenmediaengine/bin/srt-file-transmit" to ""
-- Up-to-date: /opt/ovenmediaengine/bin/srt-file-transmit
-- Installing: /opt/ovenmediaengine/bin/srt-tunnel
-- Set runtime path of "/opt/ovenmediaengine/bin/srt-tunnel" to ""
-- Up-to-date: /opt/ovenmediaengine/bin/srt-tunnel
-- Installing: /opt/ovenmediaengine/bin/srt-ffplay
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
(opus) installation has failed.

same problem with manual install, if fails at Opus:

root@LorcyOven:~# PREFIX=/opt/ovenmediaengine && \
> OPUS_VERSION=1.1.3 && \
> DIR=/tmp/opus && \
> mkdir -p ${DIR} && \
> cd ${DIR} && \
> curl -sLf https://archive.mozilla.org/pub/opus/opus-${OPUS_VERSION}.tar.gz | tar -xz --strip-components=1 && \
> autoreconf -fiv && \
> ./configure --prefix="${PREFIX}" --enable-shared --disable-static && \
> make -j 4&& \
> sudo make install && \
> sudo rm -rf ${PREFIX}/share && \
> rm -rf ${DIR}
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
root@LorcyOven:/tmp/opus#

I am pretty much inexperienced so if i am doing something wrong in it causes the installation of Opus to fail, i am happy about any help.

thanks in advanced

**Comment by getroot** [comment]
I don't know why, but it looks like you don't have aclocal on your system. OME has been installed on many Ubuntu 18.04, but this is the first issue I've seen. If you know why, please share.

To solve the problem, install automake with the command below and try again.
`sudo apt-get install automake`

**Comment by getroot** [comment]
I closed this issue because it has been inactive for a long time. If further discussion is needed, please do not hesitate to reopen the issue.
