### ISSUE TITLE
WebRTC Source with my offer

### ISSUE THREAD

**Issue by petr-briza** [AirenSoft/OvenMediaEngine#656]
Hello,
I am trying to send stream to OME from GStreamer using WebRTC. I've found a problem in OME signalling protocol design, which is that stream is limited always to 1video, 1audio.

The reason is:
- OME doesn't support accepting SDP offers, initial offer must be from OME and then OME only accept answer
- Answer cannot have different stream direction than the associated offer, and GST throws an error like "transceiver direction (sendrecv) doesn't match description intersected direction inactive (local inactive remote recvonly)"
- But this limitation is not by GST, the code in GST references section 5.3.1. of JSEP documentation

I am not an expert on WebRTC specs but seems to me that OME should support negotiation with initial SDP offer from the sender, to allow streams which the sender would like to send.

Did I miss something? Is there a possibility to send audio-only or video-only? Maybe just not from GStreamer? Many thanks.

**Comment by Morpheus235** [comment]
I tried setting up a gstreamer send pipeline amd view pipeline as well but also ran into issues. I got so far as getting connected but than the connection expiring after a few seconds and no media flowing.

**Comment by getroot** [comment]
It is OME's WebRTC Signaling protocol that OME provides offer SDP to clients. OME does not accept the client's Offer SDP. These are just specs. Clients trying to connect to OME must conform to this protocol.

In order for the client to receive an offer to send the stream to OME, request the URL as `direction=send` like `ws[s]://host:port/{app name}/{stream name}?direction=send`

In order for the client to provide audio-only or video-only, set direction to inactive in media line of answer SDP.

**Comment by getroot** [comment]
In OvenLiveKit you can send audio only like this:

```
let ovenLivekit = OvenLiveKit.create();
     ovenLivekit.attachMedia(document.getElementById('localVideo'));
     ovenLivekit.getUserMedia({
         audio: true,
         video: false
}).then(function (stream) {
     ovenLivekit.startStreaming('wss://host:port/app/stream?direction=send&transport=tcp')
});
```
