### ISSUE TITLE
webrtc ingest

### ISSUE THREAD

**Issue by thx1238** [AirenSoft/OvenMediaEngine#657]
hello, i setup ome on a local ubuntu machine and was able to ingest from obs via rtmp on local network. works perfect. ome player is installed on a web page and plays the stream aswell as your demoplayer. now i want to ingest from a webbrowser via webrtc into the local installed ome, but i can´t get any connection from the webrtc input demo player to my local ome. i open firewall ports 3333 + the ones you mentioned in the manual (although there seems to be a problem with th udp 10000 ports / internet provider) . do i have to use a tls config in ome to test webrtc ingest? thank you...

**Comment by json-m** [comment]
if you look in your browser console, you probably see a mixed content error. you either need to disable strict mixed content (to allow http requests from https contexts), or enable tls on the ingest URL at OME.

**Comment by thx1238** [comment]
hi json-m, that click does the trick :)  allowing mixed content in ingesting browser!  thank you!
