### ISSUE TITLE
about the permissions control

### ISSUE THREAD

**Issue by oldstorm** [AirenSoft/OvenMediaEngine#66]
Please tell me how to control the permissions of RTMP streaming. For example, I set up this server on the public network and only want my device to push streaming.

**Comment by lee-hammer99** [comment]
Hi.

Sorry. We don't have a way for a specific device to push streaming after setting up OvenMediaEngine on the public network. 

I think you need a way to keep others from knowing your streaming. So, you need to change the default App name "App" to like "f093jccx", or use a firewall.

Thank you.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
