### ISSUE TITLE
Getting TLS to work

### ISSUE THREAD

**Issue by jaspervanhardeveld** [AirenSoft/OvenMediaEngine#664]
Hello all,

I'm trying to get TLS working. I've installed OME with Docker. Everything works great except the part for getting TLS working. When I test WSS or the domain I receive a ERR_SSL_VERSION_OR_CIPHER_MISMATCH en I don't get it to work..

Can some explain me in a little example (with docker) how to get a self-signed certificate.

I guess it shouldn't be hard, but for me it is..

**Comment by basisbit** [comment]
Chromium / Google Chrome / Edge does not allow WebRTC playback from a server with non-trusted TLS certificate. Please use something like Let's Encrypt or similar to get a TLS certificate for your server.

**Comment by basisbit** [comment]
```<Server ...> 
...
<VirtualHosts>
		<VirtualHost>
			<Name>default</Name>
			<Host>
				<Names>
					<Name>${env:TLS_DOMAIN_NAME:oven.example.com}</Name>
				</Names>
				<TLS>
					<CertPath>/etc/ssl/cert.crt</CertPath>
					<KeyPath>/etc/ssl/key.key</KeyPath>
					<!-- <ChainCertPath>/etc/ssl/chain.crt</ChainCertPath> -->
				</TLS>
			</Host>```

**Comment by jaspervanhardeveld** [comment]
Thankyou @basisbit,

This is helpful, my problem is that let's encrypt failes to create the ssl (because of a firewall block). Does anyone have any experience with this?

**Comment by basisbit** [comment]
stop OME, then execute certbot so it gets the certificate (needs port 80 and 443 accessible from the outside and using the domain name that you specified to certbot). Then you'll have to move the certificate file and key file to the desired folders.

**Comment by harinandans** [comment]
Hello,

I have built OME and installed on Ubuntu 20.04 AWS EC2. I got letsencrypt certificate and configured it. But getting below error when I try OVP webcam input with wss.

[2022-02-11 23:27:41.465] E [SPSegPub-T443:222556] OpenSSL | tls.cpp:193  | An error occurred while accept SSL connection: [OpenSSL] error:0A000416:SSL routines::sslv3 alert certificate unknown (167773206)
[2022-02-11 23:27:41.465] E [SPSegPub-T443:222556] OpenSSL | tls_server_data.cpp:108  | An error occurred while accept TLS connection: error code: 1


[2022-02-11 23:32:41.437] W [SPSegPub-T443:222556] HttpServer | http_connection.cpp:181  | No module could be found to handle this connection request : [https://live.domain.in/]

Server.xml:

<Host>
                                <Names>
                                        <Name>live.domain.in</Name>
                                </Names>

                                <TLS>
                                        <CertPath>/etc/letsencrypt/live/live.domain.in/fullchain.pem</CertPath>
                                        <KeyPath>/etc/letsencrypt/live/live.domain.in/privkey.pem</KeyPath>
                                        <ChainCertPath>/etc/letsencrypt/live/live.domain.in/fullchain.pem</ChainCertPath>
                                </TLS>

                        </Host>

TLS ports are enabled.

I see certificate created log lines at start:

[2022-02-11 23:26:59.334] I [OvenMediaEngine:222545] Certificate | certificate.cpp:35   | A certificate has been created for VirtualHost [default]:
        Cert file path: /etc/letsencrypt/live/live.domain.in/fullchain.pem
        Chain cert file path: /etc/letsencrypt/live/live.domain.in/fullchain.pem
        Private key file path: /etc/letsencrypt/live/live.domain.in/privkey.pem

Any help would be appreciated.

**Comment by getroot** [comment]
@harinandans In CertPath, you must put the certificate file of the domain, not the full chain.

**Comment by harinandans** [comment]
@getroot, Thanks for the help. After splitting fullchain.pem to two parts - one related to domain and another chain certificates, its working fine.
