### ISSUE TITLE
Select and playing different tracks from a stream.

### ISSUE THREAD

**Issue by smartic** [AirenSoft/OvenMediaEngine#674]
Hello

I'm new using OvenMediaEngine and maybe this is a very simple question, but I've gone through documentation and forums with no luck.

I am sending a Streaming with a video track and several audio tracks with OBS. This part is working fine for me.

However, I am unable to select and connect to the different audio tracks in players like VLC or video.js.

Querying through the API, all the tracks are available there apparently:

curl -H "authorization: Basic b21lLWFjY2Vzcy10b2tlbg==" -i 192.168.10.150:8081/v1/vhosts/default/apps/app/streams/stream
HTTP/1.1 200 OK
Content-Length: 952
Server: OvenMediaEngine
Content-Type: application/json;charset=UTF-8

{"message":"OK","response":{"input":{"createdTime":"2022-02-16T17:42:47.697+01:00","sourceType":"SRT","sourceUrl":"SRT://192.168.10.33:53584","tracks":
[{"type":"Video","video":{"bitrate":"0","bypass":false,"codec":"H264","framerate":0.0,"height":1080,"width":1920}},
{"audio":{"bitrate":"0","bypass":false,"channel":2,"codec":"AAC","samplerate":48000},"type":"Audio"},
{"audio":{"bitrate":"0","bypass":false,"channel":2,"codec":"AAC","samplerate":48000},"type":"Audio"},
{"audio":{"bitrate":"0","bypass":false,"channel":2,"codec":"AAC","samplerate":48000},"type":"Audio"},
{"audio":{"bitrate":"0","bypass":false,"channel":2,"codec":"AAC","samplerate":48000},"type":"Audio"}]},
"name":"stream","outputs":[{"name":"stream","tracks":
[{"type":"Video","video":{"bypass":true}},
{"audio":{"bypass":true},"type":"Audio"},
{"audio":{"bypass":true},"type":"Audio"},
{"audio":{"bypass":true},"type":"Audio"},
{"audio":{"bypass":true},"type":"Audio"}]}]},
"statusCode":200}

Do you know how to select and play between the different audio tracks? How can you check the "label", "language" and "enabled" metadata in the .m3u8 output stream?, as discussed in "https://github.com/videojs/http-streaming/blob/main/docs/multiple-alternative-audio-tracks.md"

Thank you very much and greetings.

Here i send you my Server.xml:

<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
        <Name>OvenMediaEngine</Name>
        
        <Type>origin</Type>
        
        <IP>192.168.10.150</IP>
        <PrivacyProtection>false</PrivacyProtection>

        
        <StunServer>stun.l.google.com:19302</StunServer>

        
        <Bind>
                

                <Managers>
                        <API>
                                <Port>8081</Port>
                                <WorkerCount>1</WorkerCount>
                        </API>
                </Managers>

                <Providers>
                        
                        <RTSPC>
                                <WorkerCount>1</WorkerCount>
                        </RTSPC>
                        <OVT>
                                <WorkerCount>1</WorkerCount>
                        </OVT>
                        
                        <RTMP>
                                <Port>1935</Port>
                                <WorkerCount>1</WorkerCount>
                        </RTMP>
                        <SRT>
                                <Port>9999</Port>
                                <WorkerCount>1</WorkerCount>
                        </SRT>
                        <MPEGTS>
                                
                                <Port>4000-4003,4004,4005/udp</Port>
                        </MPEGTS>
                        <WebRTC>
                                <Signalling>
                                        <Port>3333</Port>
                                        
                                        
                                        <WorkerCount>1</WorkerCount>
                                </Signalling>

                                <IceCandidates>
                                        
                                        <TcpRelay>*:3478</TcpRelay>
                                        
                                        <TcpForce>true</TcpForce>

                                        <IceCandidate>*:10000/udp</IceCandidate>
                                        <TcpRelayWorkerCount>1</TcpRelayWorkerCount>
                                </IceCandidates>
                        </WebRTC>
                </Providers>

                <Publishers>
                        <OVT>
                                <Port>9000</Port>
                                <WorkerCount>1</WorkerCount>
                        </OVT>
                        <HLS>
                                <Port>8080</Port>
                                
                                
                                <WorkerCount>1</WorkerCount>
                        </HLS>
                        <DASH>
                                <Port>8080</Port>
                                
                                
                                <WorkerCount>1</WorkerCount>
                        </DASH>
                        <WebRTC>
                                <Signalling>
                                        <Port>3333</Port>
                                        
                                        
                                        <WorkerCount>1</WorkerCount>
                                </Signalling>
                                <IceCandidates>
                                        
                                        <TcpRelay>*:3478</TcpRelay>
                                        
                                        <TcpForce>true</TcpForce>

                                        <IceCandidate>*:10000/udp</IceCandidate>
                                        <TcpRelayWorkerCount>1</TcpRelayWorkerCount>
                                </IceCandidates>
                        </WebRTC>

                        

                </Publishers>
        </Bind>

        
        

        

        <Managers>
                <Host>
                        <Names>
                                <Name>*</Name>
                        </Names>
                        
                </Host>
                <API>
                        <AccessToken>ome-access-token</AccessToken>
                </API>
        </Managers>

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>
                        
                        <Distribution>ovenmediaengine.com</Distribution>

                        
                        <Host>
                                <Names>
                                        
                                        <Name>*</Name>
                                </Names>
                                
                        </Host>

                        

                        

                        

                        
                        <Applications>
                                <Application>
                                        <Name>app</Name>
                                        
                                        <Type>live</Type>
                                        <OutputProfiles>
                                                
                                                <HardwareAcceleration>false</HardwareAcceleration>
                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>
                                                        <Encodes>
                                                                <Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                

                                                        </Encodes>
                                                </OutputProfile>

                                        </OutputProfiles>

                                        <Providers>
                                                <OVT />
                                                <WebRTC />
                                                <RTMP />
                                                <SRT />
                                                <MPEGTS>
                                                        <StreamMap>
                                                                
                                                                <Stream>
                                                                        <Name>stream_${Port}</Name>
                                                                        <Port>4000,4001-4004</Port>
                                                                </Stream>
                                                                <Stream>
                                                                        <Name>stream_4005</Name>
                                                                <Port>4005</Port>
                                                        </Stream>
                                                        </StreamMap>
                                                </MPEGTS>
                                                <RTSPPull />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                        </Providers>
                                        <Publishers>
                                                <AppWorkerCount>1</AppWorkerCount>
                                                <StreamWorkerCount>8</StreamWorkerCount>
                                                <OVT />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                        <Rtx>false</Rtx>
                                                        <Ulpfec>false</Ulpfec>
                                                        <JitterBuffer>false</JitterBuffer>
                                                </WebRTC>
                                                <HLS>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </HLS>
                                                <DASH>
                                                       <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                        
                                                        <UTCTiming>
                                                                <Scheme>urn:mpeg:dash:utc:http-xsdate:2014</Scheme>
                                                                <Value>/time?iso&amp;ms</Value>
                                                        </UTCTiming>
                                                </DASH>
                                                <LLDASH>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                        
                                                        <UTCTiming />
                                                </LLDASH>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>

![CapturaOBS1](https://user-images.githubusercontent.com/16700958/154321591-0719aa3c-8cf7-4be6-b56c-7a576991fd0c.PNG)

**Comment by getroot** [comment]
Unfortunately, OvenMediaEnigne's HLS does not yet support multiple audio tracks. In OME, the first video track and the first audio track are muxed into one TS. To solve this, video and audio must be separated in HLS, which we plan to do in the LLHLS task. (https://github.com/AirenSoft/OvenMediaEngine/issues/480)

**Comment by smartic** [comment]
thank you very much for answering me,
best regards
