### ISSUE TITLE
Not able to access record files

### ISSUE THREAD

**Issue by jorge-jimenez-bosonit** [AirenSoft/OvenMediaEngine#678]
Record files created by FILE Publisher are not accessible by others due to a 766 mode for the directory containing those files.

Example:

```
# ls -l /mnt/shared_volumes/
total 12
drwxrw-rw-. 2 root root  127 Feb 18 20:11 1ArPm5VEwp
drwxrw-rw-. 2 root root   39 Feb 16 19:43 1fyHkwgwRn
drwxrw-rw-. 2 root root   40 Feb 22 14:04 1W5IOK3fcF
drwxrw-rw-. 2 root root   39 Feb 22 10:03 3kk40B5N4g
drwxrw-rw-. 2 root root   39 Feb 21 16:45 3ZR9ABexbf
drwxrw-rw-. 2 root root   39 Feb 15 18:09 3ZRSJmXGCV
drwxrw-rw-. 2 root root   39 Feb 21 10:43 56NsowwcSx
drwxrw-rw-. 2 root root   40 Feb 22 13:41 5eKZi2qKIt
...
```
I guess this is due to MakeDirectoryRecursive function that is defined in src/projects/publishers/file/file_session.h with 766 mode.

And I am wondering if it make more sense to be 755 or perhaps I am missing something and there is a reason to set this 766 mode.

Suggested changes:

```
diff --git a/src/projects/publishers/file/file_session.h b/src/projects/publishers/file/file_session.h
index 55c683fe..ec2ca75b 100755
--- a/src/projects/publishers/file/file_session.h
+++ b/src/projects/publishers/file/file_session.h
@@ -39,7 +39,7 @@ private:
        ov::String GetOutputFilePath();
        ov::String GetOutputFileInfoPath();
        ov::String ConvertMacro(ov::String src);
-       bool MakeDirectoryRecursive(std::string s, mode_t mode = S_IRWXU | S_IRGRP | S_IWGRP | S_IROTH | S_IWOTH);
+       bool MakeDirectoryRecursive(std::string s, mode_t mode = S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH);

 private:
        std::shared_ptr<FileWriter> _writer;
```
PS: Same 766 mode is used in MakeDirectory function defined in src/projects/base/ovlibrary/path_manager.h.

**Comment by Keukhan** [comment]
@jorge-jimenez-bosonit 

Thank you for reporting. 

The existing directory creation permission (766) has no particular reason. 
So, after thinking about it, I decided to use the following permissions. 755 for directories, 644 for recordings and info files.

If you have any problems, please leave a comment.

https://github.com/AirenSoft/OvenMediaEngine/commit/e74b20bd9965f208e827be2ef063df34cb9cf30b

And, I found a bug while processing the issue you reported and fixed it.

https://github.com/AirenSoft/OvenMediaEngine/commit/92eebcf76d7cc7f5893eb8d1031cf5af6b2fae21

 Thank you.

**Comment by jorge-jimenez-bosonit** [comment]
Thank you Keukhan for fixing it so quickly.
Great project, great job!

Best,
Jorge.
