### ISSUE TITLE
Edge API only provides information once a viewer fetches the stream

### ISSUE THREAD

**Issue by sephentos** [AirenSoft/OvenMediaEngine#679]
I have an Origin Server and an Edge Server on two different dedicated servers. 
With OvenPlayer on the frontend I access the Edge Server.

In addition, I check via OME API (Curl) whether a stream is currently running. 
In the event that a stream is running, an event is triggered on my website.

If I now start a stream and there is **no** viewer watching the stream via OvenPlayer, the API does not provide any information about the current ongoing stream. Information about the stream is not provided until there is a viewer watching the stream.
As if Edge only establishes a connection to Origin when a viewer is actually watching. 
If no viewer is watching, Edge will not get any information from Origin via the API.

Steps to reproduce:

1. Have a Origin + Edge setup on 2 servers with different public IPs
2. Start streaming to origin
3. Send a GET request to edge:
Endpoint in this example: `/v1/stats/current/vhosts/default/apps/app/streams/stream`
Result when no one is watching with OvenPlayer:

origin:
```
origin_1  | [2022-02-22 22:37:28.976] I [OvenMediaEngine:1] APIServer | api_server.cpp:113  | API Server is listening on *:8081/TCP...
```

edge:
```
edge_1  | [2022-02-22 22:44:27.596] W [SPAPISvr-T8081:21] APIController | controller.h:154  | HTTP error occurred: [HTTP] Could not find the application: [default/app] (404)
```

HTTP response:
```
{"message":"[HTTP] Could not find the application: [default/app] (404)","statusCode":404}
```

After the first viewer starts watching the stream edge API shows the data.
Shouldn't it be possible to fetch stream informations without being needed to have at least one viewer?

---
Both OME servers are running within docker on debian systems.
Origin & edge v0.13.1

**Comment by getroot** [comment]
When a viewer's playback request comes in, Edge refers to the origin map and gets the stream from the origin and creates it.
This is the common behavior of most edges, and it behaves as we intended. Even streams with no viewers are automatically cleaned up after 60 seconds to save resources.

Edge's origin map can also set up thousands of origin streams. Synchronizing all those streams would be impossible and very inefficient.

**Comment by getroot** [comment]
Yes, that's right.

For more elegant processing, it is recommended to create an Application in Edge's Server.xml in advance and check the stream list through the `GET streams` API. If there is no stream here, there are no viewers.

https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/virtualhost/application/stream

And as you said, Origin doesn't count viewers from Edge. It must be developed using an external statistical system.

**Comment by sephentos** [comment]
> Yes, that's right.
> 
> For more elegant processing, it is recommended to create an Application in Edge's Server.xml in advance and check the stream list through the `GET streams` API. If there is no stream here, there are no viewers.
> 
> https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/virtualhost/application/stream
> 
> And as you said, Origin doesn't count viewers from Edge. It must be developed using an external statistical system.

Sending a GET (with auth) request to `/v1/vhosts/default/apps/app/streams/stream`

```{"message":"[HTTP] Could not find the stream: [default/#default#app/stream] (404)","statusCode":404}```

(Same result as with `/v1/stats/current/vhosts/default/apps/app/streams/stream`)

Again, I only get information when a spectator exists.

Of course I can find a solution to the fact that I don't get any information about viewers if there is no viewer. 
But I can't even check if a stream is running at all unless one viewer is already watching

**Comment by getroot** [comment]
I meant to query the stream list via `GET /v1/vhosts/default/apps/app/streams` . This will give you a list of currently created streams.
