### ISSUE TITLE
how to give IP camera RTSP stream as input stream for OvenMedia Engine? 

### ISSUE THREAD

**Issue by surendran-syx** [AirenSoft/OvenMediaEngine#684]
Hi,
    we used ubuntu 20.04 OS . we successfully install and start oven media engine. 
    how to give IP camera RTSP stream as input stream to Oven media engine? how to get webRTC output stream?

**Comment by json-m** [comment]
https://airensoft.gitbook.io/ovenmediaengine/live-source/rtsp-pull-beta ?

**Comment by surendran-syx** [comment]
we gave rtsp stream like you mentioned in  that above link. and we  played that rtsp stream in vlc player, its played succefully. and we tried HLS restreaming also. but still we could not play both restreamed  HLS url or webrtc url.

our server config file:


 <?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		

		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>1935</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>4000/udp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>

				<IceCandidates>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>false</TcpForce>

					<IceCandidate>*:10000/udp</IceCandidate>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<HLS>
				<Port>80</Port>
				
				<TLSPort>443</TLSPort>
				<WorkerCount>4</WorkerCount>
			</HLS>
			<DASH>
				<Port>80</Port>
				
				<TLSPort>443</TLSPort>
				<WorkerCount>4</WorkerCount>
			</DASH>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					
					<TLSPort>3334</TLSPort>
					<WorkerCount>4</WorkerCount>
				</Signalling>
				<IceCandidates>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>false</TcpForce>

					<IceCandidate>*:10000/udp</IceCandidate>
					<TcpRelayWorkerCount>4</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					
					<Name>media-server1.xxx.com</Name>
					<Name>10.0.0.100</Name>
				</Names>
				
				<TLS>
					<CertPath>/etc/ssl/cert.cer</CertPath>
					<KeyPath>/etc/ssl/key.key</KeyPath>
					<ChainCertPath>/etc/ssl/fullchain.cer</ChainCertPath>
				</TLS>

			</Host>

			

			

			<Origins>

                                <Origin>
                                        <Location>/app/stream</Location>
                                        <Pass>
                                                <Scheme>rtsp</Scheme>
                                                <Urls><Url>192.168.8.61:554/cam/realmonitor?channel=1&subtype=0</Url></Urls>
                                        </Pass>
                                </Origin>

				
			</Origins>
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>


							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							
							<UTCTiming>
								<Scheme>urn:mpeg:dash:utc:http-xsdate:2014</Scheme>
								<Value>/time?iso&amp;ms</Value>
							</UTCTiming>
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							
							<UTCTiming />
						</LLDASH>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by getroot** [comment]
Please upload full /var/log/ovenmediaenigne/ovenmediaengine.log file

**Comment by surendran-syx** [comment]
[ovenmediaengine20220309.txt](https://github.com/AirenSoft/OvenMediaEngine/files/8231959/ovenmediaengine20220309.txt)
[ovenmediaengine20220311.txt](https://github.com/AirenSoft/OvenMediaEngine/files/8231961/ovenmediaengine20220311.txt)

**Comment by getroot** [comment]
You have set /app/stream as Location in OriginMap, but you are trying to play with /app/stream_o.

```
[2022-03-08 13:50:29.352] E [SegWorker:919] Orchestrator | orchestrator.cpp:478 | Could not find Origin for the stream: [#default#app/stream_o]
[2022-03-08 13:50:29.352] E [SegWorker:919] HLS | hls_stream_server.cpp:60 | [#default#app/stream_o] [HLS] Could not find: playlist.m3u8 (404)
[2022-03-08 13:50:29.675] E [SegWorker:919] Orchestrator | orchestrator.cpp:478 | Could not find Origin for the stream: [#default#app/stream_o]
[2022-03-08 13:50:29.675] E [SegWorker:919] HLS | hls_stream_server.cpp:60 | [#default#app/stream_o] [HLS] Could not find: playlist.m3u8 (404)
```

**Comment by surendran-syx** [comment]
we also tried /app/stream. this is also not play

 [2022-03-09 03:57:05.745] E [SegWorker:919] Orchestrator | orchestrator.cpp:478  | Could not find Origin for the stream: [#default#app/stream]
[2022-03-09 03:57:05.745] E [SegWorker:919] HLS | hls_stream_server.cpp:60   | [#default#app/stream] [HLS] Could not find: playlist.m3u8 (404)
[2022-03-09 03:57:05.748] E [SegWorker:919] Orchestrator | orchestrator.cpp:478  | Could not find Origin for the stream: [#default#app/stream]
[2022-03-09 03:57:05.748] E [SegWorker:919] HLS | hls_stream_server.cpp:60   | [#default#app/stream] [HLS] Could not find: playlist.m3u8 (404)

**Comment by getroot** [comment]
I looked again at the Server.xml and ovenmediaengine.log files you uploaded and found something strange.

Your OvenMediaEngine server is not using the Server.xml you uploaded. I can find this because the TLSPort 443 and Certificate you configured were not found in the log you uploaded.

Are you sure your Server.xml is located well in /usr/share/ovenmediaengine/conf/Server.xml?

**Comment by getroot** [comment]
If `<Bind><Publishers><HLS><TLSPort>` is set in Server.xml, the following log is output.

`[03-14 22:01:51.548] I [OvenMediaEngine:1053763] HTTPPublisher | segment_publisher.cpp:53 | HLS Publisher is listening on *:13333, TLS: *:13334...`

But your log will output something like this:

`[2022-03-08 03:50:59.085] I [OvenMediaEngine:826] HTTPPublisher | segment_publisher.cpp:53 | HLS Publisher is listening on *:80...`

I hope you find out why the Server.xml and log you uploaded are inconsistent.

**Comment by getroot** [comment]
Did you restart the server after editing Server.xml?
That is, did you run the command below?

`systemctl restart OvenMediaEngine`

I do not reproduce your problem in my environment. Also, the feature is now well used by many commercial services.
If you would like to solve the problem, please provide more information.
