### ISSUE TITLE
Selecting Tracks in RTMP Push

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#685]
I am attempting to select which audio track to stream to twitch using rtmp push.  How can I tell what the available stream ids are?

The response from [http://192.168.1.8:8081/v1/vhosts/default/apps/hw120/streams/quat](url) appears to be 3 tracks: [video, audio, audio].  I've tried writing the following id selections into rtmp startPush stream tracks json: [1, 2] [0, 1] [100, 101] [101, 102] [100, 200] [101, 201] 

Whichever ids I select, the console log prints this message:
`Mar 02 20:53:25 ovenmediaengine OvenMediaEngine[5458]: [2022-03-02 20:53:25.107] E [AW-RTMPPush0:5501] FFmpeg | third_parties.cpp:111  | [AVFormatContext: 0x7f1628017740] at most one audio stream is supported in flv` and does not publish any stream.  The only way to publish a stream is to omit the tracks selection json entry.

How can I find out what the ids are that represent the available streams so I can select one or more of multiple tracks by id?

**Comment by Keukhan** [comment]
@krakow10 

Thanks for the reporting.
Unfortunately, The REST API does not provide a function to query Track ID by stream name.
Also, track selection was not supported in the Output Stream.

I'll have to add it to my next plan.

Thanks.

**Comment by Keukhan** [comment]
@krakow10 

First of all, the problem has been solved that the track cannot be selected.
https://github.com/AirenSoft/OvenMediaEngine/compare/5f234c3071d6...63e4d2012474

RTMP(flv) must use only one video and audio track.  If you select only one track each, the error "at most one audio stream is supported in flv" will not occur.

Thanks

**Comment by krakow10** [comment]
Awesome, I will test this out next time I stream!
I understand that the flv container and rtmp protocol has codec and track restrictions, and I wish streaming services like twitch would switch to more flexible ingest protocols.  YouTube added HLS live ingest at the end of 2020 and I had been using HLS with hevc since then until I came across OvenMediaEngine and its much more configurable stream manipulation.

**Comment by basisbit** [comment]
YouTube/Twitch/... will probably not add support for SRT because of how easy it is to DDoS, or rather how difficult it is to protect against DDoS.

**Comment by krakow10** [comment]
I can confirm that I can now publish a stream by selecting tracks using OME 0.13.2, but I think that the audio tracks are all duplicates of the first audio track.  That is, as long as OBS is sending the SRT MPEGTS stream with two distinct audios using advanced custom ffmpeg output mode correctly.  The distinct audio tracks previously worked with OBS when recording directly to a file.

**Comment by Keukhan** [comment]
@krakow10 

It was a really great report.  Thanks to you, I was able to find and fix it. As you said, in a multi-track audio input stream, only the first audio track was used and duplicated. There was a problem in generating a UniqueID to prevent duplicate encoding. If you want to know how to fix it, check out the commit log below.

https://github.com/AirenSoft/OvenMediaEngine/compare/d364254fe06f...47120ee4a779

try test again with the master version.

I applaud you. +1

Thank you.

**Comment by krakow10** [comment]
Testing with master and sending REST requests I get an empty reply from the server:
```
[quat@quat-desktop ~]$ curl -d '{ "id" : "twitch", "stream": { "name": "quat_1080p60", "tracks": [14,15] }, "protocol": "rtmp", "url":"rtmp://sea.contribute.live-video.net/app/'"${TWITCH_STREAM_KEY}"'" }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://192.168.1.8:8081/v1/vhosts/default/apps/hw60:startPush
curl: (52) Empty reply from server
```
```
[quat@quat-desktop ~]$ curl -d '{ "id" : "vod", "stream": { "name": "quat" } }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://192.168.1.8:8081/v1/vhosts/default/apps/hw60:startRecord
curl: (52) Empty reply from server
```
and the log says
`Mar 22 21:38:32 ovenmediaengine OvenMediaEngine[29079]: [2022-03-22 21:38:32.125] E [SPAPISvr-T8081:29140] HttpServer | http_transaction.cpp:338  | Invalid parse status: 200`
Is this my configuration issue? My config did not change when I updated

**Comment by krakow10** [comment]
I tested again on commit 1e40ba and the REST requests work properly, but the audio tracks are still duplicates.

**Comment by Keukhan** [comment]
Can you share the settings of OutputProfiles in Server.xml?
Then, change the log setting to MediaRouter(debug)  and share the same log as below.

> [03-22 21:52:49.831] D [InboundWorker:2530660] MediaRouter | mediarouter_stream.cpp:877  | 
>  - MediaRouter Stream | type: **Inbound**, name: #default#app/stream, uptime: 30075ms, queue: 0, min/max gap: 1005ms
>         track:256, type: video, codec: H264( 1), pts: 307724ms(    0ms), tb: 1/90000, pkt_cnt:    869, pkt_siz: 6.5MB, bps: 1732Kbps
>         track:257, type: audio, codec:  AAC( 6), pts: 307415ms( -437ms), tb: 1/90000, pkt_cnt:    188, pkt_siz: 502.2KB, bps: 133Kbps
>         track:258, type: audio, codec:  AAC( 6), pts: 306719ms(  305ms), tb: 1/90000, pkt_cnt:     43, pkt_siz: 68.0KB, bps: 18Kbps
> [03-22 21:52:49.831] D [OutboundWorker:2530661] MediaRouter | mediarouter_stream.cpp:877  | 
>  - MediaRouter Stream | type: **Outbound**, name: #default#app/stream_o, uptime: 30075ms, queue: 0, min/max gap: 1416ms
>         track:  0, type: video, codec: H264( 1), pts: 307033ms(   41ms), tb: 1/90000, pkt_cnt:    848, pkt_siz: 2.5MB, bps: 661Kbps
>         track:  1, type: audio, codec:  AAC( 6), pts: 307415ms( -437ms), tb: 1/90000, pkt_cnt:    188, pkt_siz: 502.2KB, bps: 133Kbps
>         track:  2, type: audio, codec:  AAC( 6), pts: 305999ms(  308ms), tb: 1/90000, pkt_cnt:     42, pkt_siz: 67.7KB, bps: 18Kbps

**Comment by krakow10** [comment]
I changed the log level in Logger.xml from "info" to "debug", and restarted the ovenmediaengine service, and then ran my stream with 6 distinct audio tracks.  The log was 10x larger than previous logs, but there's no "MediaRouter Stream" entries.  `cat ovenmediaengine.log | grep MediaRouter` only shows things like "Trying to delete a stream" and "Delete media route stream".  I used `git pull` to update the OvenMediaEngine source code, can that cause issues when rebuilding?  Here is my log file and Server.xml:
[ovenmediaengine.log.tar.gz](https://github.com/AirenSoft/OvenMediaEngine/files/8335742/ovenmediaengine.log.tar.gz)
[Server.xml.tar.gz](https://github.com/AirenSoft/OvenMediaEngine/files/8335749/Server.xml.tar.gz)
github is weird for not 'supporting' file extensions, the 7z archive of the log file is half the size

**Comment by krakow10** [comment]
I'm starting to wonder if my process to install updates is flawed.  This is what I've been doing:
1. cd OvenMediaEngine && git pull
2. cd src && make -j16 release
3. sudo make install
4. systemctl daemon-reload
5. systemctl restart ovenmediaengine

Is this enough to completely replace the old version?  Is there some removal process I should be doing?

**Comment by Keukhan** [comment]
@krakow10 

Except for number 4, it will be updated.

**Comment by krakow10** [comment]
In my previous testing I assumed that recording streams to disk would also work with multiple audio tracks.  I also tested rtmppush which didn't work at the time, but it's not clear to me whether I was using a properly updated version.  With my latest tests I can confirm that I can select and publish whichever audio tracks with RTMP to twitch and youtube.  Selecting tracks for recording does not work, but I suppose that is technically outside the scope of this issue.

Thank you for adding this feature to your software, this issue is resolved!

**Comment by Keukhan** [comment]
@krakow10 

I'll check to see if there is a problem with the multi-audio track being replaced by the first track.
I'll let you know when the problem is resolved.

Thanks for the great report.

**Comment by krakow10** [comment]
Should I open a new issue for selecting tracks for recording?  It's basically the same issue that this was
