### ISSUE TITLE
stream protection

### ISSUE THREAD

**Issue by Azoto1985** [AirenSoft/OvenMediaEngine#69]
Is there a way to add the stream authentication to the rtmp:// 
i haven't found nothing related to this point in the documentation.

Thanks.
Regards

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time.If you need this issue to be discussed again, please feel free to reopen it.

**Comment by Swiftgti** [comment]
Hi how do you protect the rtmp input of the application so other people don’t publish on the application? YouTube and similar used a key? Where do you configure this key in oven media ? Without any protection is useless for the real world and production environment. Thanks

**Comment by GenocideStomper** [comment]
I've used a complicated random string to replace 'app' in the rtmp connection string in ome-origin-conf/_data/Server.xml, but using the ome_demo.html demo player requires putting the connection string in the source, which could be viewed by anyone.

I wish there was an easy way to add some rtmp authentication, or to use a different WebRTC connection string.

**Comment by getroot** [comment]
You can do it by using the AccessControl feature (https://airensoft.gitbook.io/ovenmediaengine/access-control)
