### ISSUE TITLE
Secured player

### ISSUE THREAD

**Issue by marcinjagielnicki** [AirenSoft/OvenMediaEngine#692]
Hey, is it possible to secure playing streams anyhow? I would like to allow only some of the users play particular streams and I would like to protect streams from being shared.

**Comment by getroot** [comment]
You can protect your stream using AccessControl. 
Refer to the manual below.
https://airensoft.gitbook.io/ovenmediaengine/access-control

**Comment by marcinjagielnicki** [comment]
I know about AccessControl but I want to protect stream from being **viewed** by unauthorised end-users.

**Comment by getroot** [comment]
You can use AccessControl to protect your streams from viewing (via HLS, DASH, WEBRTC) by unauthorized end users.

**Comment by marcinjagielnicki** [comment]
Ok, thank you. Will check this soon.
