### ISSUE TITLE
How to gdb OvenMediaEngine

### ISSUE THREAD

**Issue by htliu6** [AirenSoft/OvenMediaEngine#701]
Could you help us? If you can help us, please try as follows. 

1. In Dockerfile(https://github.com/AirenSoft/OvenMediaEngine/blob/temp/alpine/Dockerfile), remove "strip" command as follow. 

RUN \
        DIR=/tmp/ome && \
        mkdir -p ${DIR} && \
        cd ${DIR} && \
        curl -sLf https://github.com/AirenSoft/OvenMediaEngine/archive/${OME_VERSION}.tar.gz | tar -xz --strip-components=1 && \
        cd src && \
        make release && \
        mkdir -p ${PREFIX}/bin/conf && \
        # strip ./bin/RELEASE/OvenMediaEngine && \
        cp ./bin/RELEASE/OvenMediaEngine ${PREFIX}/bin/ && \
        cp ../misc/conf_examples/Server.xml ${PREFIX}/bin/conf/ && \
        rm -rf ${DIR}

2. Re-build docker image

`docker build --tag ovenmediaengine:debug .`

3. Run Docker as /bin/sh

`docker run -it --entrypoint=/bin/sh  --security-opt seccomp=unconfined -e OME_VIDEO_FRAMERATE=30 -e OME_VIDEO_BITRATE=2000000 -e OME_VIDEO_WIDTH=1280 -e OME_VIDEO_HEIGHT=720 -p 1935:1935 -p 3333:3333 -p 8080:80 -p 9000:9000/udp -p 10000-10005:10000-10005/udp ovenmediaengine:debug`

4. Run OvenMediaEngine with GDB

`apk add gdb`
`gdb /opt/ovenmediaengine/bin/OvenMediaEngine`

5. And give the backtrace information and exact location where the program crashes.

_Originally posted by @getroot in https://github.com/AirenSoft/OvenMediaEngine/issues/39#issuecomment-521127515_

Excuse me, when I run step 3, I got "Unable to find image 'ovenmediaengine:debug' locally", I wonder how to fix it.
BTW, is there another way to gdb the OME?

**Comment by getroot** [comment]
Logs can be found in `/var/log/ovenmediaengine/` inside the docker container.

Alternatively, when running docker, run it in the foreground with the `-it` option instead of `-d` to see the logs immediately.

First, check the log before running gdb. My guess is that the port that OME is trying to open is already in use, so it is most likely not running.

To build in debug mode, use make instead of make release . And binaries are created in `bin/DEBUG`, not `bin/RELEASE`.

**Comment by htliu6** [comment]
@getroot Thanks for your reply, I'll have a try.

**Comment by htliu6** [comment]
@getroot Sorry to bother you again! 

**I got following error after I modified the Dockerfile, please help!**

_gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
(openssl) installation has failed.
The command '/bin/sh -c if [ "$GPU" = "TRUE" ] ; then                 ${TEMP_DIR}/misc/install_nvidia_docker_image.sh ;                 ${TEMP_DIR}/misc/prerequisites.sh  --enable-nvc ;         else                 ${TEMP_DIR}/misc/prerequisites.sh ;         fi' returned a non-zero code: 1_

**I append the Dockerfile below and noted "change here!" for the modifications in Dockerfile.**

`FROM    ubuntu:20.04 AS base

## Install libraries by package
ENV     DEBIAN_FRONTEND=noninteractive
RUN     apt-get update && apt-get install -y tzdata sudo curl

FROM    base AS build

WORKDIR /tmp

## change here!
## ARG     OME_VERSION=master
ARG	OME_VERSION=0.13.2
## change here!
## ARG 	STRIP=TRUE
ARG	STRIP=FALSE
ARG     GPU=FALSE

ENV     PREFIX=opt/ovenmediaengine
ENV     TEMP_DIR=/tmp/ome

## Download OvenMediaEngine
RUN \
        mkdir -p ${TEMP_DIR} && \
        cd ${TEMP_DIR} && \
	## change here!
        curl -sLf https://github.com/AirenSoft/OvenMediaEngine/archive/refs/tags/v${OME_VERSION}.tar.gz | tar -xz --strip-components=1

## Install dependencies
RUN \
        if [ "$GPU" = "TRUE" ] ; then \
                ${TEMP_DIR}/misc/install_nvidia_docker_image.sh ; \
                ${TEMP_DIR}/misc/prerequisites.sh  --enable-nvc ; \
        else \
                ${TEMP_DIR}/misc/prerequisites.sh ; \
        fi

## Build OvenMediaEngine
RUN \
        cd ${TEMP_DIR}/src && \
      	## change here! 
	make -j$(nproc)
	## make release -j$(nproc)

RUN \
        if [ "$STRIP" = "TRUE" ] ; then strip ${TEMP_DIR}/src/bin/RELEASE/OvenMediaEngine ; fi

## Make running environment
RUN \
        cd ${TEMP_DIR}/src && \
        mkdir -p ${PREFIX}/bin/origin_conf && \
        mkdir -p ${PREFIX}/bin/edge_conf && \
        ## change here!
	## cp ./bin/RELEASE/OvenMediaEngine ${PREFIX}/bin/ && \
        cp ./bin/DEBUG/OvenMediaEngine ${PREFIX}/bin/ && \
	cp ../misc/conf_examples/Origin.xml ${PREFIX}/bin/origin_conf/Server.xml && \
        cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/origin_conf/Logger.xml && \
        cp ../misc/conf_examples/Edge.xml ${PREFIX}/bin/edge_conf/Server.xml && \
        cp ../misc/conf_examples/Logger.xml ${PREFIX}/bin/edge_conf/Logger.xml && \
        rm -rf ${DIR}

FROM	base AS release

WORKDIR         /opt/ovenmediaengine/bin
EXPOSE          80/tcp 8080/tcp 8090/tcp 1935/tcp 3333/tcp 3334/tcp 4000-4005/udp 10000-10010/udp 9000/tcp
COPY            --from=build /opt/ovenmediaengine /opt/ovenmediaengine
# Default run as Origin mode
CMD             ["/opt/ovenmediaengine/bin/OvenMediaEngine", "-c", "origin_conf"]
`

**Comment by getroot** [comment]
```
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
(openssl) installation has failed.

```
It looks like your script failed to download OpenSSL. Run misc/prerequisites.sh in your environment and look for error messages.

And why use docker to run gdb? Wouldn't it be easier to run it on your linux host?

**Comment by htliu6** [comment]
@getroot Huh! Sorry to bother you again! I am new to Linux and found that using docker for gdb is so complexed. Would you please offer some advice on how to gdb OME on Linux host?

**Comment by getroot** [comment]
As for how to use GDB on Linux, it's pretty common, so a Google search might find some more organized stuff. :-) Refer to the manual for how to compile OME on a linux host.

https://airensoft.gitbook.io/ovenmediaengine/getting-started#manual-installation-and-execution

Why would you want to debug OME using GDB? If your OME is not running, please post a log. It's probably a very simple matter. Now OME works well in many commercial environments.

**Comment by htliu6** [comment]
Thanks for your kindly reply! As for the reasons of using GDB, we are now measuring the transmitting and computing performance of a complete end-to-end Live system using OME, and I need to figure out the function calling stack. So, according to the brief introduction from https://www.airensoft.com/ome, I wonder which functions are the entry of stages such as Ingest, Transcoding, Packaging, Origin and Edge. Would you please help us? You are the expertise on this. Huhhhh!

**Comment by getroot** [comment]
Performance cannot be measured with GDB. Because GDB is holding the process for debugging, the performance is tens of times worse.

Of course I am a developer of OME, so I am familiar with the structure of OME. But unfortunately I am too busy to help with that.

**Comment by htliu6** [comment]
Thanks for your reply, I use GDB just for finding the entry function of above several stages, then we plan to use logs or eBPF to measure the performance. So, would you please just to tell me the entry functions? Thanks very much, huhhhh!

**Comment by getroot** [comment]
Oh, I see,
Since this is a server, there are multiple entry points.
To start with RTMP input, start with RtmpProvider::OnConnected .
https://github.com/AirenSoft/OvenMediaEngine/blob/55ed8cd509b63830c01c0e95236104e2981461fa/src/projects/providers/rtmp/rtmp_provider.cpp#L147

Perhaps, in order to analyze such a server, it is more effective to read the source code as a whole rather than following the entry point.

**Comment by htliu6** [comment]
Thanks for your kindly help! The function `RtmpProvider::onConnected` is called when a TCP connection is established, I wonder what is the entry function when a packet of a given stream is received. Moreover, what's the entry functions of other stages? Thank you!

**Comment by getroot** [comment]
RtmpProvider::OnDataReceived
Is this function what you want? RTMP packets are received in this function.

Do you want a lower level entry point? Read SocketPoolWorker::ThreadProc() .

https://github.com/AirenSoft/OvenMediaEngine/blob/04722da4efff90fb4c2578f1816007cec3014a5f/src/projects/base/ovsocket/socket_pool/socket_pool_worker.cpp#L260

Sorry, but it is impossible to describe all entry points for each stage here. It is huge because there are so many branches. Please read the source code yourself.

**Comment by htliu6** [comment]
Thanks for your patient and kindly reply again! To cope with the branches, I'd like to print function calling stack using gdb. So, what are the concerns when compiling for gdb, e.g., how to add `-g` option to Makefile. Thank you!

**Comment by getroot** [comment]
You don't need to add the -g option.
The make command compiles in debug mode. The make release command compiles in release mode.

It's difficult to answer broad questions. (e.g. what are concerns when compiling for gdb) Before that, I'd like you to explore more about OME. For general questions, please google it.

**Comment by htliu6** [comment]
It's so nice of you! Thanks for your kindly reply! I'll have a try.
