### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by br1ge** [AirenSoft/OvenMediaEngine#702]
Is it possible to add filters for broadcasts. For example, add a custom blurr to protect the rights of users if the broadcast is public. In Europe, the Rodo law works, where you can get a large fine

**Comment by getroot** [comment]
OME does not support these features. User face tracking, blur processing, etc. are different areas from OME.
This needs to be handled by the device (encoder or camera) sending the signal to the OvenMediaEngine.

**Comment by br1ge** [comment]
I don't mean blurring the face, but blurring the whole picture

**Comment by getroot** [comment]
If it is that kind of filter, it can be implemented using ffmpeg's filter. But wouldn't it be more efficient to do it with an encoder?

**Comment by br1ge** [comment]
Thanks. I will try
