### ISSUE TITLE
Web Stream and Connection Management

### ISSUE THREAD

**Issue by jhonyesg** [AirenSoft/OvenMediaEngine#703]
**Is your feature request related to a problem? Please describe.**

The system is very good, but there is always the question of how many users are connected simultaneously to the stream, how can I do to control access, an example would be I want to make a stream and I will share it to 3 people, I want the example link http://51.81.210.198:8080/app/caracol/playlist.m3u8?usuario=uno&pass=test, but generated for each user, so with a web portal, see connected users and see which is the user that more connections reports me, this in order to take control, not to saturate the server and not have access to unauthorized persons.

**Describe the solution you'd like**

A Web Admin panel would be a great solution, to control connections, create, edit and delete users, view streaming status on the server, scalable with community version and with the opportunity to earn income for support and maintenance.

**Describe alternatives you've considered**

Watching videos and testing I see that there is a project called xcodes Stream, it has a panel focused on IPTV sales, but its admin panel seems useful to me, because I can see the stream status, the active connections, it creates a username and password per user, allowing to identify inappropriate consumptions.

**Additional context**

For the moment I have tested it and it seems to me a complete system, that beats in aspects to wowza, the only weak point that I see is that it does not have an administration platform or a step by step tutotial of being able to link it to some project of Streaming administration.

**Comment by getroot** [comment]
You can extend the capabilities of OME by creating your own user control servers using AdmissionWebhooks.

https://airensoft.gitbook.io/ovenmediaengine/access-control/admission-webhooks

**Comment by jhonyesg** [comment]
Kind regards.

thanks for the answer, but the version I used for testing is https://hub.docker.com/r/airensoft/ovenmediaengine

In this case, how to access the web panel, which tells me that you can access, but from the Docker version.

I also want to know if this server handles this type of transmission delivery http://192.168.0.18:8080/vivo/caracol.flv

thanks in advance for your support.

**Comment by bchah** [comment]
OME is an engine for building your application on top of. Part of what makes it so great and valuable is that it *doesn't* have a built in web panel or user-facing application. That is for you to create :)

Airensoft has been very generous sharing their core technologies with us, but their main commercial product is called [OvenVideo](https://www.airensoft.com/ov) and it can do many of the things you are asking for. If you are considering OME in place of a commercial solution like Wowza, maybe Airensoft can create a custom solution for you around OvenVideo.

As for FLV delivery, I do not think that is supported. OME supports HLS currently and have plans to implement LL-HLS, both of which will take the place of the older technologies like FLV & DASH: https://airensoft.gitbook.io/ovenmediaengine/streaming

They have a good post about their roadmap for OME too: https://github.com/AirenSoft/OvenMediaEngine/issues/548
