### ISSUE TITLE
POST Error (The VirtualHost is read-only)

### ISSUE THREAD

**Issue by dimaserr5** [AirenSoft/OvenMediaEngine#708]
Hello everyone, such a problem or error, I haven't found out yet. When an API request is made using the http GET method://<OME_HOST>:<API_PORT>
/v1/vhosts/{vhost_name}/aps - the output of the app application, but when trying to start streaming using the POST command /v1/vhosts/{vhost_name}/apps/{app_name}:startrecord writes that the application was not found, as well as when accessing the list all applications via POST, outputs - "line(83) "{"message": "[HTTP] Virtual host is read-only: [default] (403)","statusCode":403}" - which may be related, as I understand, any PUBLICATION is rejected

**Comment by phiberber** [comment]
Same problem here.
