### ISSUE TITLE
Not working iGPU acceleration

### ISSUE THREAD

**Issue by kolik29** [AirenSoft/OvenMediaEngine#709]
**PROBLEM**

When I start the oven I get a warning in the logs "There is no supported hardware accelerator". If I start streaming using h264 then the stream does not work well.

**ENVIRONMENTAL INFORMATION**

Branch: master
OS: Ubuntu 20.04

**SETUP INFORMATION AND LOGS**

Server.xml
https://gist.githubusercontent.com/kolik29/11c2429c2b4474ad99c4b7b7e8072f8b/raw/a98e188a06838006611aa02d3b1d6e807028773f/Server.xml

Log
https://gist.githubusercontent.com/kolik29/cae92212b81ad4a230f0cd0497d69747/raw/b63b35d6fb6e7a03e9b5f6551ac365f0c9ffb710/Log

**Comment by getroot** [comment]
Have you completed the installation to use the hardware encoder?

https://airensoft.gitbook.io/ovenmediaengine/transcoding/gpu-usage

And what exactly is the meaning of "stream does not work well"? Even if the hardware encoder is not enabled, it should work well as a software encoder. Does the video play with stuttering? Or does playback not start?

**Comment by kolik29** [comment]
Yes, I execute commands:
`(curl -LOJ https://github.com/AirenSoft/OvenMediaEngine/archive/master.tar.gz && tar xvfz OvenMediaEngine-master.tar.gz) 
OvenMediaEngine-master/misc/install_intel_driver.sh`
,
`OvenMediaEngine-master/misc/prerequisites.sh --enable-qsv`
and
`sudo apt-get update
cd OvenMediaEngine-master/src
make release
sudo make install
systemctl start ovenmediaengine
# If you want automatically start on boot
systemctl enable ovenmediaengine.service `

Video works but video works, but latency increases over time.

**Comment by getroot** [comment]
Are you sure your cpu supports intel quicksync? Check if the driver is installed properly.

https://airensoft.gitbook.io/ovenmediaengine/transcoding/gpu-usage#how-to-check-driver-installation

If the latency continues to increase, it's the lack of CPU performance when using the software encoder.

**Comment by kolik29** [comment]
Yes, supported, My processor: Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Where I can find path /MediaSDK-intel-mediasdk-21.1.2/build/__bin/release/

**Comment by krakow10** [comment]
Have you used the iGPU video encode acceleration successfully with other applications such as ffmpeg?  When you have a discrete GPU plugged in, the motherboard will disable integrated graphics by default.  To enable both, you have to change a setting in the BIOS.  On a side note, a GTX 1660 has the same great hardware encoder as an RTX 3060, but is much less expensive to use as a dedicated video encode acceleration device.

**Comment by kolik29** [comment]
> Have you used the iGPU video encode acceleration successfully with other applications such as ffmpeg?

Yes

> When you have a discrete GPU plugged in, the motherboard will disable integrated graphics by default. To enable both, you have to change a setting in the BIOS.

I know but Intel have disabled this since the 6th generation of processors, hasn't it?

**Comment by kolik29** [comment]
This dont work with GPU too. NVidia GeForce RTX 3060 and GTX 1660.

**Comment by Keukhan** [comment]
Using the command provided by NVIDIA, you can check which process is using the GPU.

![image](https://user-images.githubusercontent.com/21077363/160811920-99645c1d-84c1-4008-bb15-d2b58d6dd12b.png)

Check if OvenMediaEngine is included with the nvidia-smi command.
1. If nvidia-smi does not run, the nvidia driver is not installed.
2. If OvenMediaEngine does not appear in the results, you did not enable --enable-nvc in the prerequsite.sh installation step.
