### ISSUE TITLE
HLS - Unsupported Content Type?

### ISSUE THREAD

**Issue by bchah** [AirenSoft/OvenMediaEngine#711]
I noticed some applications do not understand the "content-type" header presented by theHLS publisher:

`'application/vnd.apple.mpegurl'`

For example, there is a ROKU TV developer feature which lets you create applications with HLS streams and it works with other ....m3u8 URLs, but it errors out with an OME URL:

e.g. 
`
https://ome:8000/live/54a91e6e21a4d/playlist.m3u8?p=eyJ1cmxfZXhwaXJlIjo3MjQ1NTk0MTMwMDAwfQ&s=ASmEhH7b7SPOZJAetSqlrQbooEA`

`Was expecting 'application/rss+xml', 'text/xml', 'application/xml' or 'application/json' but received 'application/vnd.apple.mpegurl'
`

Is there any control over how these responses are created? Or a way to achieve better compatibility? I understand if this is a larger task than it seems like 😅

**Comment by getroot** [comment]
Well, application/vnd.apple.mpegurl is HLS-compliant, so it doesn't seem right to change it in OME. But you can test it by modifying the code below.

https://github.com/AirenSoft/OvenMediaEngine/blob/a2f6451bfc3bec33760f8a9c888d75d507911cf0/src/projects/publishers/segment/hls/hls_stream_server.cpp#L70
