### ISSUE TITLE
How is the video delay calculated in OvenRtcTester?

### ISSUE THREAD

**Issue by htliu6** [AirenSoft/OvenMediaEngine#712]
Could anyone give an introduction to the video delay calculation in OvenRtcTester? Does this metric include the delay between source and OME?

**Comment by getroot** [comment]
This is calculated using the RTP Timestamp.

**Comment by getroot** [comment]
There is no way to measure latency with Capture-to-Display. It can be measured directly by eye in a glass-to-glass manner. OvenRtcTester sees the first RTP packet as 0, and measures how much delay thereafter. This is effective when measuring the system processing speed according to the number of users.
