### ISSUE TITLE
Streaming Locally - Could not resolve public IP address from STUN server

### ISSUE THREAD

**Issue by ds88888888** [AirenSoft/OvenMediaEngine#713]
I have isolated the server with OME installed on it from outgoing connections. As it will be used locally, there is no reason for me to connect to the outside.

Running on Ubuntu 20.04. OvenPlayer is installed with Nginx 1.20.2, running on port 8080. 

Set firewall commands to allow port 8080 and confirmed working with local server and local client connected to outside. Able to stream end to end with no issues.

I have put the below in a file called stream.html in the OvenPlayer folder, that is located in nginx root. To access from client at 10.80.25.101: http://10.80.25.105:8080/OvenPlayer/stream.html. I have changed the script src to dist/ovenplayer.js so I can use it offline.

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OvenPlayer</title>
</head>

<body>
    <!-- OvenPlayer will be initialized inside this element. -->
    <div id="player_id"></div>

    <!-- Load OvenPlayer via CDN -->
    <script src="dist/ovenplayer.js"></script>

    <script>

        // Initialize OvenPlayer
        const player = OvenPlayer.create('player_id', {
            sources: [
                {
                    label: 'label_for_webrtc',
                    // Set the type to 'webrtc'
                    type: 'webrtc',
                    // Set the file to WebRTC Signaling URL with OvenMediaEngine 
                    file: 'ws://10.80.25.105:3333/app/stream'
                }
            ]
        });
    </script>
</body>

</html>
```

The page is missing some css formatting now that the server is not exposed to outside.

What else do I need to do to get this working locally without any outside connections? This can be done without STUN servers if it is on a local network right? Should I remove the Google stun server url in the config if I am not needing it?

**Comment by bchah** [comment]
You don't need to specify STUN servers if you are using the IP directly - I would comment that out of the server config as it just slows down the connection if iterating through additional servers.

As for missing CSS the page you show above doesn't seem to have anything but the player on it. Are you saying the player does not appear correctly? It should have everything included in the dist bundle you're calling.
