### ISSUE TITLE
SRT input to multiple destinations (relay)

### ISSUE THREAD

**Issue by fullmetalpacket** [AirenSoft/OvenMediaEngine#715]
Great project, keep up the good work guys.

I think it would be very useful to "relay" SRT streams.

SRT source ---> OME input ---> SRT destination
______________________________---> RTMP destination
______________________________---> RTC destination

That way we could intercept an SRT feed to make it playable in a web browser.

Thanks! :)

**Comment by getroot** [comment]
OME already has SRT Ingest and RTMP Push/WebRTC Streaming features. The SRT Push feature isn't implemented because I haven't been able to find any use case for it. Are there any use cases for OME to use SRT Push?

**Comment by fullmetalpacket** [comment]
In my use case I have encoders in the field and they are feeding decoders at the office. I would like to intercept these p2p feeds to monitor them in a web browser, with little delay as possible. I would point all my decoders to OME and push their feeds to their respective decoders and I would add RTC packetization to feed the web interface. Thanks for your work.

**Comment by bchah** [comment]
+1 for this feature request. Broadcasters and independent streamers are using SRT to move video between devices, and it has a much longer life in front of it than RTMP. As @fullmetalpacket says, this would allow OME to push not just to RTMP streaming servers but to hardware devices that accept SRT.

**Comment by RyanBrenneman** [comment]
We have a specific use case to have SRT encoders and decoders use the caller feature to simplify the process and avoid the need for port forwarding.  Often times, the devices that are listeners are behind corporate networks and firewalls.  If we are producing an event and want remote viewing locations this can be a challenge.  We could really use the ability to send in one SRT feed and have it served to several connections.

https://www.magewell.com/onlinehelp/magewell-cloud/chapters/usage/07-srtserver.html 

Here is a video to explain what we could really use for feature.

https://youtu.be/3DODgv1m4uk?t=61

Thanks,

**Comment by Morpheus235** [comment]
@RyanBrenneman  if you really need this right now have a look at SRT Gateway. Its a service developed by Haivision itself and serves as a virtual Router for SRT Streams. We use it at my work and are very pleased with the stability and feautures. It also offers an api for advanced control. Were using it for quite some Time in conjunction with Ovenmediaengine.

[SRT Gateway](https://www.haivision.com/products/srt-gateway/)

**Comment by RyanBrenneman** [comment]
Thank you @Morpheus235.  We have been working with Brian at Streamwell and were hoping to combine multiple dashboards / tools into one. He turned us onto the thread to add our +1.

**Comment by getroot** [comment]
I also agree that using an external tool like SRT Gateway is effective.
