### ISSUE TITLE
Can't play rtmp stream from VLC player, what am I missing?

### ISSUE THREAD

**Issue by buithevuong** [AirenSoft/OvenMediaEngine#717]
I want to see if the rtmp stream is playable to use for dragging it, but I can't play it on VLC to test, what more do I need to make this work? Look forward to the help.

**Comment by bchah** [comment]
OME does not offer an RTMP publisher. For VLC playback you should use the HLS URL, just make sure you have HLS publisher enabled in your configuration and it will be available, e.g. assuming you bind the publisher to port 8000:

http://your-ome:8000/app/streamname/playlist.m3u8
