### ISSUE TITLE
RTSP axis camera not working

### ISSUE THREAD

**Issue by deepsurvey** [AirenSoft/OvenMediaEngine#719]
**PROBLEM**
Unable to open RTSP pull with stream parameters.

**EXPECTATION**

The feed to play, like it used to a few generations of OME ago.

Please write how you would like the problem to be resolved.

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

Master branch: OvenMediaEngine v0.13.2 () is started on [798b3f03968f] (Linux x86_64 - 5.13.0-39-generic, #44~20.04.1-Ubuntu SMP Thu Mar 24 16:43:35 UTC 2022)

I can sucessfully open the feed with username and password:
root:password@192.168.10.200:554/axis-media/media.amp?

My problem in this case is that the feed opened is with the max resolution and bandwith of the camera, and that does not run smooth

origin_1  | [2022-04-01 08:09:37.674] I [AW-LLDASH0:45] LLDASH.Stat | cmaf_packetizer.cpp:883  | [#default#volans/fwd] Jitter statistics
origin_1  |   - Elapsed: 55197ms (current: 1648800577674ms, start: 1648800522477ms)
origin_1  |   - Jitter: 118ms (118ms - 0ms), correction: 0ms => 0ms (0ms)
origin_1  |   - Stream delta: 55079ms
origin_1  |     - Video: last PTS: 55079ms, start: 0ms, delta: 55079mssmoothly on a crappy 4G connection

-- what is stream delta? is that a queue growing?

I used to be able to parse:
root:password@192.168.10.201:554/axis-media/media.amp?resolution=640x480&compression=20&color=1&fps=10&audio=0&videomaxbitrate=1500%videobitratemode=mbr&v>
 
When I parse this URL, I get:

origin_1  | [2022-04-01 08:13:28.706] I [OvenMediaEngine:1] APIServer | api_server.cpp:166  | API Server is disabled
origin_1  | [2022-04-01 08:13:59.011] I [SPRtcSig-T3333:8] HttpServer | http_server.cpp:146  | Client(<ClientSocket: 0x7ff3dc0012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38132>) is connected on *:3333
origin_1  | [2022-04-01 08:13:59.012] I [SPRtcSig-T3333:8] HttpServer | http_transaction.cpp:112  | Client(<ClientSocket: 0x7ff3dc0012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38132>) is requested uri: [http://172.26.0.235:3333/volans/ps]
origin_1  | [2022-04-01 08:13:59.013] I [SPRtcSig-T3333:8] Signalling | rtc_signalling_server.cpp:231  | New client is connected: <ClientSocket: 0x7ff3dc0012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38132>
origin_1  | [2022-04-01 08:13:59.086] I [SPRtcSig-T3333:8] Orchestrator | orchestrator.cpp:682  | Trying to pull stream [#default#volans/ps] from provider using origin map: PullProvider
origin_1  | [2022-04-01 08:13:59.101] E [SPRtcSig-T3333:8] RtspcStream | rtspc_stream.cpp:307  | Rtsp server(rtsp://192.168.10.203:554/axis-media/media.amp?resolution=640x480&compression=20&color=1&fps=10&audio=0&videomaxbitrate=1500%videobitratemode=mbr&videocodec=h264) rejected the describe request : 400(Bad Request)
origin_1  | [2022-04-01 08:13:59.133] E [SPRtcSig-T3333:8] RtspcStream | rtspc_stream.cpp:307  | Rtsp server(rtsp://192.168.10.203:554/axis-media/media.amp?resolution=640x480&compression=20&color=1&fps=10&audio=0&videomaxbitrate=1500%videobitratemode=mbr&videocodec=h264) rejected the describe request : 400(Bad Request)
origin_1  | [2022-04-01 08:13:59.163] E [SPRtcSig-T3333:8] RtspcStream | rtspc_stream.cpp:307  | Rtsp server(rtsp://192.168.10.203:554/axis-media/media.amp?resolution=640x480&compression=20&color=1&fps=10&audio=0&videomaxbitrate=1500%videobitratemode=mbr&videocodec=h264) rejected the describe request : 400(Bad Request)
origin_1  | [2022-04-01 08:13:59.163] I [SPRtcSig-T3333:8] Provider | stream.cpp:60   | #default#volans/ps(100) has been stopped playing stream
origin_1  | [2022-04-01 08:13:59.163] E [SPRtcSig-T3333:8] Provider | provider.cpp:153  | RTSPCProvider Application could not create [ps] stream.
origin_1  | [2022-04-01 08:13:59.163] E [SPRtcSig-T3333:8] Orchestrator | orchestrator.cpp:727  | Could not pull stream [#default#volans/ps] from provider: PullProvider
origin_1  | [2022-04-01 08:13:59.164] E [SPRtcSig-T3333:8] WebRTC Publisher | webrtc_publisher.cpp:489  | Cannot find stream (#default#volans/ps)
origin_1  | [2022-04-01 08:13:59.164] E [SPRtcSig-T3333:8] Signalling | rtc_signalling_server.cpp:322  | Cannot find stream [#default#volans/ps]
origin_1  | [2022-04-01 08:13:59.241] I [SPRtcSig-T3333:8] Signalling | rtc_signalling_server.cpp:365  | Client is disconnected: HttpConnection(0x7ff3dc001c90) : WebSocket <ClientSocket: 0x7ff3dc0012d0, #38, Connected, TCP, Nonblocking, 172.26.248.17:38132> TLS(Disabled) (#default#volans / ps, ufrag: local: (N/A), remote: (N/A))
origin_1  | [2022-04-01 08:13:59.241] I [SPRtcSig-T3333:8] HttpServer | http_server.cpp:209  | Client(<ClientSocket: 0x7ff3dc0012d0, #38, Closed, TCP, Nonblocking, 172.26.248.17:38132>) has been disconnected by *:3333

does anyone have an idea what I am missing here?

thansk,

rowdy

Please check whether it is reproduced in the master branch first. The Docker image for the master branch is airensoft/ovenmediaengine:dev .
If you are using the Master branch, please write Master.
If you are using Release, please write the version (eg 0.12.4).
If you are using Docker by building it yourself, please tell us what version of the image you built.
If you are using a public Docker image, please provide the image path with tags. (e.g. airensoft/ovenmediaengine:0.12.8)

- Encoder information

What encoder are you using?(e.g. OBS 10.22) And how is the codec set on that encoder?
If you are using OvenLiveKit as an encoder, please let me know if it reproduces here https://demo.ovenplayer.com/demo_input.html. And please tell me what error is output in the browser's developer console.
If you are using RTSP Pull, please let me know which RTSP server you are using.

- Player information

Please let me know if it reproduces on http://demo.ovenplayer.com or https://demo.ovenplayer.com. And please tell me what error is output in the browser's developer console.

- URL

Please tell me which address you used to send and play. You can hide IP or Domain.

- Operating system and version

Please tell me the OS and version (e.g. Ubuntu 20.04)

**SETUP INFORMATION AND LOGS**

Please upload Server.xml.
Please upload the entire file /var/log/ovenmediaengine/ovenmediaengine.log. (You may delete your personal information.)
It's hard to find the problem if you post only part of the log. Be sure to upload the entire file.

**OTHER HELPFUL INFORMATION**

Please write any information that anyone viewing this issue can reference.

**Comment by bchah** [comment]
I recently found an issue with URL parsing when the url contains ampersand. The issue is fixed in the master branch but not in the latest release. Could your issue be related? https://github.com/AirenSoft/OvenMediaEngine/issues/704

**Comment by deepsurvey** [comment]
> I recently found an issue with URL parsing when the url contains ampersand. The issue is fixed in the master branch but not in the latest release. Could your issue be related? #704

Could well be the same issue. It used to work fine, but I think some "URL" filters have been implemented.
