### ISSUE TITLE
Reuse video transcoding

### ISSUE THREAD

**Issue by ytian801** [AirenSoft/OvenMediaEngine#72]
Like I want to support both WebRTC and HLS, I need to create 2 profiles because they support different audio codec. 2 profiles means 2 transcoding for both audio and video.

As they can both use H264 as video codec, can we just transcode once for video stream?

**Comment by dimiden** [comment]
@ytian801 Yes, you can. You only need to set one ```<Encode>``` for H264 and use it in multiple ```<Stream>```.
For example,
```
<Streams>
	<Stream>
		<Name>${OriginStreamName}_aac</Name>
		<Profiles>
			<Profile>h264</Profile>
			<Profile>aac</Profile>
		</Profiles>
	</Stream>
	<Stream>
		<Name>${OriginStreamName}_opus</Name>
		<Profiles>
			<Profile>h264</Profile>
			<Profile>opus</Profile>
		</Profiles>
	</Stream>
</Streams>
```

You can also use this configuration:
```
<Streams>
	<Stream>
		<Name>${OriginStreamName}_o</Name>
		<Profiles>
			<Profile>h264</Profile>
			<Profile>aac</Profile>
			<Profile>opus</Profile>
		</Profiles>
	</Stream>
</Streams>
```
 In this case, WebRTC Publisher uses H.264+OPUS and HLS Publisher uses H.264+AAC.

**Comment by ytian801** [comment]
Thank you
