### ISSUE TITLE
can't push rtmp stream to another server , help me .

### ISSUE THREAD

**Issue by buithevuong** [AirenSoft/OvenMediaEngine#721]
**My log :**
> [2022-04-04 03:30:30.766] E [StreamWorker:168] RTMPWriter | rtmp_writer.cpp:393  | Send packet error(-32:Broken pipe)
[2022-04-04 03:30:30.766] E [StreamWorker:168] RTMPPush | rtmppush_session.cpp:174  | Failed to send packet
[2022-04-04 03:30:35.769] W [AW-RTMPPush0:30] RTMPPush | rtmppush_session.cpp:86   | Could not supported codec. track_id:1, codec_id: 8
[2022-04-04 03:30:35.770] W [AW-RTMPPush0:30] RTMPPush | rtmppush_session.cpp:86   | Could not supported codec. track_id:2, codec_id: 8
[2022-04-04 03:30:35.772] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | Output #0, flv, to 'rtmp://192.168.1.89:1935/live/stream':
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  |   Metadata:
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  |     encoder         : 
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | Lavf58.76.100
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | 
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  |   Stream #0:0
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | : Video: h264, 1 reference frame ([7][0][0][0] / 0x0007), yuv420p, 640x480 (0x0) [SAR 1:1 DAR 4:3], 0/1, q=2-31
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | , 
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | 1k tbn
[2022-04-04 03:30:35.773] I [AW-RTMPPush0:30] FFmpeg | third_parties.cpp:119  | 

**My config :**
`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>
	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		
		<Managers>
			<API>
				<Port>${env:OME_API_PORT:8081}</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		  </Managers>
		  
		  <Providers>
			  
			  <RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000/udp}</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					
					
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					
					
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
			
			
		</Publishers>
	</Bind>

	<Managers>
			<Host>
				<Names>
					<Name>*</Name>
				</Names>
				
			</Host>
			<API>
				<AccessToken>your_access_token</AccessToken>
			</API>
		</Managers>
	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>
			
			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						
						<FILE>
							<RootPath>/mnt/shared_volumes</RootPath>
							<FilePath>/${VirtualHost}/${Application}/${Stream}.ts</FilePath>
							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
						</FILE>
						
						
						<RTMPPush>
      						</RTMPPush>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>`

**My api :** 
http://localhost:8083/v1/vhosts/default/apps/app:startPush

{
    "id": "1",
    "stream": {
        "name": "stream"
        },
    "protocol": "rtmp",
    "url":"rtmp://192.168.1.89:1935/live",
    "streamKey":"stream"
}

**Response :** 
{
    "message": "OK",
    "response": [
        {
            "app": "app",
            "createdTime": "2022-04-04T03:29:23.041+00:00",
            "finishTime": "1970-01-01T00:00:00.000+00:00",
            "id": "1",
            "protocol": "rtmp",
            "sentBytes": 0,
            "sentTime": 0,
            "sequence": 0,
            "startTime": "2022-04-04T03:29:23.041+00:00",
            "state": "Pushing",
            "stream": {
                "name": "stream",
                "tracks": []
            },
            "streamKey": "stream",
            "totalsentBytes": 0,
            "totalsentTime": 0,
            "url": "rtmp://192.168.1.89:1935/live",
            "vhost": "default"
        }
    ],
    "statusCode": 200
}

**Comment by getroot** [comment]
Please upload entire `/var/log/ovenmediaengine/ovenmediaengine.log` file, I need another information such as track information that is before the log file you uploaded. Just upload the whole file. 

Also, please post duplicate issues on the same thread. We'll continue the discussion at #720 and I'll close this issue.
