### ISSUE TITLE
LLDASH playback - Date Header is not available in the OME response.

### ISSUE THREAD

**Issue by jplogos** [AirenSoft/OvenMediaEngine#722]
**Describe the bug**
We see that, Date Header is missing (HTTP header) in the OME Response (OME installed from the master branch).
Please check and update us.

**To Reproduce**
Install OME and try a play back for LLDASH stream and capture pcap.

**Expected behavior**
We are expecting Date header but same is not available in the OME response

**Logs**
Please refer the attache screen shot.
![image](https://user-images.githubusercontent.com/38765075/161685695-e30cd2b7-1607-41d4-8bc9-f3c3d1949292.png)

**Server (please complete the following information):**
OME and  - Branch: [master]

**Player (please complete the following information):**
DASH Reference Player

**Additional context**

**Comment by dimiden** [comment]
@jplogos 
Could you explain in more detail why the HTTP response should have a Date header?
As far as I know, OME uses ```urn:mpeg:dash:utc:http-xsdate:2014``` for UTCTiming by default, so it is not necessary to have a ```Date``` header in the response. (I referenced [IOP V5](https://dashif.org/docs/CR-Low-Latency-Live-r8.pdf))
When played in the [DASH Reference Player](http://reference.dashif.org/dash.js/nightly/samples/dash-if-reference-player/index.html), you can see that ```time?iso&ms``` is invoked as follows:
![image](https://user-images.githubusercontent.com/4264558/161972952-2c15d604-cdef-4ada-baad-c999f61475f4.png)
Please let me know if there are any specifications that I don't know!
