### ISSUE TITLE
B frame detection per-stream in API

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#727]
**Is your feature request related to a problem? Please describe.**
B frames prevent the WebRTC player from working. For our use case, we provide both WebRTC and HLS (and other) stream players. We would like to automatically use the WebRTC player or not, based on whether B frames are detected in a stream

**Describe the solution you'd like**
If we can query the OME API to determine B-frame status, that would be a straightforward and easy solution.

**Comment by bchah** [comment]
I agree it would be good to have this and other stream info queryable via the API.

In the meantime I use my existing PHP backend to grab a few lines from the log file and parse them for certain keywords, which provides a bit of 'missing API' functionality. This is a handy function I *definitely* did not write, but one could use it to grab the last N lines of a log file, and inject your own parsing logic:

```
// Thank you to @authors Torleif Berger, Lorenzo Stanco for this handy function!

function lastLines($filepath, $lines = 1, $adaptive = true)
{

    $f = @fopen($filepath, "rb");
    if ($f === false) return false;

    if (!$adaptive) $buffer = 4096;
    else $buffer = ($lines < 2 ? 64 : ($lines < 10 ? 512 : 4096));

    fseek($f, -1, SEEK_END);

    // adjust line number if necessary
    // (Otherwise the result would be wrong if file doesn't end with a blank line)
    if (fread($f, 1) != "\n") $lines -= 1;

    $output = '';
    $chunk = '';

    while (ftell($f) > 0 && $lines >= 0) {

        // Figure out how far back we should jump
        $seek = min(ftell($f), $buffer);

        // Do the jump (backwards, relative to where we are)
        fseek($f, -$seek, SEEK_CUR);

        // Read a chunk and prepend it to our output
        $output = ($chunk = fread($f, $seek)) . $output;

        // Jump back to where we started reading
        fseek($f, -mb_strlen($chunk, '8bit'), SEEK_CUR);

        // Decrease our line counter
        $lines -= substr_count($chunk, "\n");
    }

    // (Because of buffer size we might have read too many)
    while ($lines++ < 0) {
  
// insert your own logic here to parse each line and look for things like B-frame warnings

        $output = substr($output, strpos($output, "\n") + 1);
    }

    fclose($f);
    return trim($output);
}
```
