### ISSUE TITLE
Unable to set CrossDomain for API-server

### ISSUE THREAD

**Issue by liexner** [AirenSoft/OvenMediaEngine#728]
Hey!

Im trying to use the API in a browser and came across CORS error.
And when setting the cross-domain for the API-server i am  getting this error message:

`
 [OvenMediaEngine:1] OvenMediaEngine | main.cpp:336  | An error occurred while load config: [Config] Unknown item found: Server.Managers.API.CrossDomains in ./origin_conf/Server.xml
`

This is how my managers element looks:

```
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>

				<TLS>
					<CertPath>/path/to/cert</CertPath>
					<KeyPath>/path/to/privkey</KeyPath>
				</TLS>

		</Host>
		<API>
			<AccessToken>test123</AccessToken>

			<CrossDomains>
				<Url>*</Url>
			</CrossDomains>
		</API>

	</Managers>
```
According to the [Documentation](https://airensoft.gitbook.io/ovenmediaengine/rest-api) this is where it is supposed to go.
I have tried moving it around but are getting similair problem every time.
I am interpreting that the error complains about the placement of the CrossDomains element and not the actual content.
Is it supposed to be somewhere else or is something else wrong?

Thanks in advance!

**Comment by bchah** [comment]
Can you share the full Server.xml? Your syntax looks OK but in the documentation I notice they declare the version as "10" rather than the default "8" and I wonder if the parser looks for different XML tags depending on the declared server XML version... 

Also this could be a red herring but I notice they don't offer an example of simply putting * as the URL, all of their examples use a FQDN, e.g.

```
<CrossDomains>
				<Url>*.airensoft.com</Url>
				<Url>sub-domain.airensoft.com</Url>
				<Url>http://http-only.airensoft.com</Url>
			</CrossDomains>
```

**Comment by bchah** [comment]
Yes I would change your version from 8 to 10 and make sure you are using a recent enough build of OME that it is compatible. Good luck and keep us posted!

**Comment by dimiden** [comment]
@liexner 
Yes, ```<CrossDomain>``` supports OME v0.13.0, so I recommend using later versions!

**Comment by liexner** [comment]
Thank you! I got it working after updating the image, so it's all good now!
