### ISSUE TITLE
Websocket server timeout

### ISSUE THREAD

**Issue by ytian801** [AirenSoft/OvenMediaEngine#73]
I'm using nginx as proxy server for secure websocket connection, but every 60 seconds, the browser will close the websocket connection, after some investigation, I found there's a timeout setting in Nginx called [proxy_read_timeout](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout), this value is default 60 seconds, can we add some timeout to the server to let client keep alive? 

btw, do we really need to keep the websocket connection alive? can we just close websocket after webrtc connection connected?

I mean can we just comment this line out? 

https://github.com/AirenSoft/OvenMediaEngine/blob/9a6adf838eeb5cabbc789710b1dfb8b5b41e9a16/src/projects/http_server/http_server.cpp#L230

**Comment by dimiden** [comment]
@ytian801 
Which version are you using? If it is a version of the master branch, the "WebSocket ping-pong" specification is not implemented, which can cause problems.

**Comment by ytian801** [comment]
I'm using master branch

**Comment by dimiden** [comment]
@ytian801 
Then, as I said above, I don't think it works because of the ping-pong specification.
We are currently working on merging two branches (master/dev), so please wait for it or use the dev branch.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
