### ISSUE TITLE
Create volume conf from existing folder to docker

### ISSUE THREAD

**Issue by buithevuong** [AirenSoft/OvenMediaEngine#730]
I have created ome-edge-conf and ome-origin-conf folders, but I can't run OME on docker :
`docker run  \
-p 1936:1935 \
-p 3333:3333 \
-p 3478:3478 \
-p 8083:8081 \
-v /myfolder/ome-origin-conf:/opt/ovenmediaengine/bin/origin_conf \
-v /myfolder/ome-edge-conf:/opt/ovenmediaengine/bin/edge_conf \
-v /myfolder:mnt/shared_volumes \
-v /myfolder/logs:/var/log/ovenmediaengine \
--name ovenmediaengine \
airensoft/ovenmediaengine:latest`

log : 

> [2022-04-13 11:08:36.223] W [OvenMediaEngine:1] Config | config_manager.cpp:158  | There is no configuration file for logs : origin_conf/Logger.xml. OME will run with the default settings.
[2022-04-13 11:08:36.223] I [OvenMediaEngine:1] Config | config_manager.cpp:227  | Trying to load configurations... (origin_conf/Server.xml)
[2022-04-13 11:08:36.223] E [OvenMediaEngine:1] OvenMediaEngine | main.cpp:265  | An error occurred while load config: [Config] Could not read the file: origin_conf/Server.xml (reason: File was not found, offset: 0)

Help me . tks all

**Comment by IanMitchell77** [comment]
@buithevuong is Logger.xml and Server.xml in those folders? The Path tag in Logger.xml sets where it writes log files - see https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Logger.xml

**Comment by buithevuong** [comment]
> @buithevuong có Logger.xml và Server.xml trong các thư mục đó không? Thẻ Path trong Logger.xml đặt nơi nó ghi các tệp nhật ký - xem https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Logger.xml

yes, I copy from /var/lib/docker/volumes . If I keep the docker command as suggested it will work, but I want more flexibility in handling, is it possible to do this without creating a symbolic link?

**Comment by IanMitchell77** [comment]
@buithevuong,

Docker wont be able to follow link files I think - I have the real files in the conf directory.

Please send me the output of the following commands:

ll /myfolder/ome-origin-conf
cat /myfolder/ome-origin-conf/Logger.xml

**Comment by buithevuong** [comment]
> r
ll ome-origin-conf
> total 12
total 12
drwxrwxrwx 3 vuong vuong 4096 Thg 3  30 16:56 ./
drwxrwxrwx 4 vuong vuong 4096 Thg 4  14 14:17 ../
drwxrwxrwx 2 vuong vuong 4096 Thg 4  14 14:21 _data/


ll _data 

>total 24
drwxrwxrwx 2 vuong vuong 4096 Thg 4  14 14:21 ./
drwxrwxrwx 3 vuong vuong 4096 Thg 3  30 16:56 ../
-rwxrwxrwx 1 vuong vuong  386 Thg 3  18 11:51 Logger.xml*
-rwxrwxrwx 1 vuong vuong   36 Thg 3  30 16:56 Server.id*
-rwxrwxrwx 1 vuong vuong 5974 Thg 4  14 14:21 Server.xml*


> <?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>
	
	<StunServer>stun.l.google.com:19302</StunServer>

	
	<Bind>
		
		
		<Managers>
			<API>
				<Port>${env:OME_API_PORT:8081}</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>
		
		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					
					
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<WebRTC>
				<Signalling>
					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
					<WorkerCount>1</WorkerCount>
					
					
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10006/udp}</IceCandidate>
				</IceCandidates>
			</WebRTC>
			
			
		</Publishers>
	</Bind>

	<Managers>
			<Host>
				<Names>
					<Name>*</Name>
				</Names>
				
			</Host>
			<API>
				<AccessToken>your_access_token</AccessToken>
			</API>
		</Managers>
	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>
			
			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>aac</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						
						<FILE>
							<RootPath>/mnt/shared_volumes</RootPath>
							<FilePath>/${VirtualHost}/${Application}/${Stream}.ts</FilePath>
							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
						</FILE>
						
						
						<RTMPPush>
      						</RTMPPush>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by buithevuong** [comment]
> @buithevuong,
> 
> Docker wont be able to follow link files I think - I have the real files in the conf directory.
> 
> Please send me the output of the following commands:
> 
> ll /myfolder/ome-origin-conf cat /myfolder/ome-origin-conf/Logger.xml

please check for me

**Comment by IanMitchell77** [comment]
The Logger.xml and Server.xml files are in the _data directory - they need to be in ome-origin-conf.
Also, please can you show me Logger.xml?

**Comment by buithevuong** [comment]
> Các tệp Logger.xml và Server.xml nằm trong thư mục _data - chúng cần nằm trong ome-origin-conf. Ngoài ra, bạn có thể cho tôi xem Logger.xml được không?

thanks , i will try to go outside _data folder , here is Logger.xml : 

> <?xml version="1.0" encoding="UTF-8"?>

<Logger version="2">
	
	<Path>/var/log/ovenmediaengine</Path>

	
	<Tag name="SRT" level="critical" />
	<Tag name="HttpServer" level="warn" />
	<Tag name=".*\.Stat" level="warn" />

	
	<Tag name=".*" level="info" />
</Logger>

**Comment by IanMitchell77** [comment]
Did OME find the files when you moved them @buithevuong ?
