### ISSUE TITLE
Leftover recording files

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#733]
**Describe the bug**
On our server we save recordings using OME. Here is the relevant section of the config file

```
                        <FILE>
                            <RootPath>/mnt/recordings</RootPath>
                            <FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.mp4</FilePath>
                            <InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
                        </FILE>
```

This works, but leaves behind many relatively small files like /recordingdir/32185/192147.mp4 - where 32185 is the stream's name (random example from our server)

Should OME be cleaning these up? Or should our backend be handling this. We weren't expecting them from our testing, as I'm not sure they were mentioned in the recording page documentation.

Any suggestions are welcome, I think maybe they're split sections of the recording, but then why do they stick around when a final recording is made?

This is with the latest release, 0.13.2 iirc

**Comment by Keukhan** [comment]
@naanlizard 

Thanks for the good comments.

Our current policy is "Recorded files are not deleted by OME". The backend system refers to the xml file and performs automatic upload, copy to storage, etc., and then deletes it.

If I have any good ideas or plans, I'll let you know.

Thanks.

**Comment by naanlizard** [comment]
Understandable, after this weekend I will try and update the gitbook to clarify that.

**Comment by Keukhan** [comment]
oh! gitbook update?

many thanks!

👍
