### ISSUE TITLE
OME crashes if File provider has a full disk

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#734]
**Describe the bug**
OME throws an error and quits if the target disk for recordings is full. This was noticed by us when OME had filled up our recording hard drive and then crashed.

**To Reproduce**
1. Enable recordings to a disk that is full (possibly also, no permission to write recordings, nonexistent device, etc)
2. Observe OME quit and errors in logs (apologies, our logs were lost, but this is easy to reproduce)

**Expected behavior**
OME should continue to do everything except recordings eg accept incoming rtmp streams, playback via HLS and WebRTC, etc

**Comment by Keukhan** [comment]
@naanlizard 

Thanks for the great report.
I will fix this problem and apply it in the next release.

Thanks.

**Comment by naanlizard** [comment]
Hard won report haha, guess I’m the only one dumb enough to let it happen

if it is easy, I would recommend an api response detailing available storage, might be useful.
