### ISSUE TITLE
tweaking the delay between the live stream being pushed to the external nginx-rtmp server

### ISSUE THREAD

**Issue by magnuszetterberg** [AirenSoft/OvenMediaEngine#736]
Before asking for help, please read the troubleshooting section in the manual carefully.
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting

Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

**PROBLEM**

We have a fully working OME setup working with webrtc . We push camera streams to this server, and we watch them all on other side of the OME server through webrtc and with very lowlatency.

 However, when we choose to push a stream from OME to our nginx-rtmp server, and then we look at the nginx-rtmp server through for example VLC, we see that we have roughly 6 seconds delay on the stream. 

My questions is if there are any tweaks that we can perform, to lower the latency compare the origin stream from the OME side. 
 
**EXPECTATION**
Hopefully get some tweaks to enter into the Server.xml side, to lower the latency from the camera stream -> OME server -> nginx-rtmp -> VLC(or any other player which can play rtmp).

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information
0.13.2

- Operating system and version

Please tell me the OS and version (e.g. Ubuntu 20.04)
Ubuntu 20.04

**SETUP INFORMATION AND LOGS**

Please upload Server.xml.
Please upload the entire file /var/log/ovenmediaengine/ovenmediaengine.log. (You may delete your personal information.)
It's hard to find the problem if you post only part of the log. Be sure to upload the entire file.

**OTHER HELPFUL INFORMATION**

Please write any information that anyone viewing this issue can reference.

**Comment by naanlizard** [comment]
What is your playback method for nginx-rtmp?

**Comment by getroot** [comment]
It would be the latency of the nginx-rtmp server and vlc player(rtmp), so there doesn't seem to be anything OME can do about it.

**Comment by magnuszetterberg** [comment]
> What is your playback method for nginx-rtmp?
> 
> Please share your nginx-rtmp config

`cat nginx.conf
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}


#mail {
#       # See sample authentication script at:
#       # http://wiki.nginx.org/ImapAuthenticateWithApachePhpScript
#
#       # auth_http localhost/auth.php;
#       # pop3_capabilities "TOP" "USER";
#       # imap_capabilities "IMAP4rev1" "UIDPLUS";
#
#       server {
#               listen     localhost:110;
#               protocol   pop3;
#               proxy      on;
#       }
#
#       server {
#               listen     localhost:143;
#               protocol   imap;
#               proxy      on;
#       }
#}
rtmp {
        server {
                listen 1935;
                chunk_size 1024;

                application live {
                        live on;
                        record off;
                }
        }
}`

**Comment by Meister1593** [comment]
> > It would be the latency of the nginx-rtmp server and vlc player(rtmp), so there doesn't seem to be anything OME can do about it.
> 
> To bad to hear... but understandable if that is the case..

Most players add heavy buffer to their rtmp playback so they have really high latency

Try using `ffplay -fflags nobuffer -sync ext rtmp://...` for direct play without buffer. I had lowest latencies up to 350 ms
