### ISSUE TITLE
use wget instead of curl in prerequisites.sh

### ISSUE THREAD

**Issue by aileenfun** [AirenSoft/OvenMediaEngine#739]
I found a problem when using prerequisites.sh, curl keep reporting error, so I modified curl to wget and it works fine.
please consider updating the script in your git.
[prerequisites.zip](https://github.com/AirenSoft/OvenMediaEngine/files/8517680/prerequisites.zip)
.

**Comment by command-tab** [comment]
I’m super curious what the issue was that you encountered that prompted the change. curl and wget work very similarly, and can be configured to send the same HTTP requests.
