### ISSUE TITLE
Stream recorded file

### ISSUE THREAD

**Issue by mrw-s** [AirenSoft/OvenMediaEngine#741]
**PROBLEM**

Is is possible to re-stream a recorded file? My use case requires streaming and recording of a live broadcast and then replaying the recorded video. I couldn't see anything to do this?

**EXPECTATION**

A stream provider that streams a recorded ts or MP4 file.

**ENVIRONMENTAL INFORMATION**

n/a

**Comment by naanlizard** [comment]
You could re-stream stuff with ffmpeg to just pipe rtmp back in, but that is definitely clunky.

Probably easier to just have your app serve the recorded file however you like, without using OME. That's what we do
