### ISSUE TITLE
Add Origin-s records dynamicly

### ISSUE THREAD

**Issue by mpbikc** [AirenSoft/OvenMediaEngine#746]
Hello.
I'm started work with OME and its wonderful. No I try to setup cluster working.
It works, but I need to
create on Edge server Origin records dynamically.
Why I need It:
I have for about 50-100 origin servers and for about few hondreds of edge servers.
I can add in configuration of each edge server 50 lines with link to each of origin app.
But I afraid orogin server will find server with started stream too long, or it may couse a lot of unnesessary connections.

I want to add for edge servers origin link with exact stream, may be By API or somwhere else.
Will it be possible?

**Comment by getroot** [comment]
To achieve this, OriginMap must be deployed as a separate server, and all Origins and Edges must query the OriginMap server. This is a task in our backlog, but I haven't decided when to start developing it yet.

**Comment by mpbikc** [comment]
thank you for quic response. It seemed to be loong task:(
May be It'll be more easy task to add update origins to API?
Orchestrator::UpdateVirtualHosts - already has ProcessOriginList and need only ato add api method.
Or it is possible only on startup?
