### ISSUE TITLE
Http Ovenplayer 

### ISSUE THREAD

**Issue by deepsurvey** [AirenSoft/OvenMediaEngine#747]
Hi,
 I am trying to open an insecure feed (ws://) but all my browsers keep relaying http://demo.ovenplayer.com to https. Not matter what I try, other computer, delete all cache , cookies etc.. 
or even http://demo.ovenplayer.com:80 .

Mozilla, brave chrome, they all forward. I used to be able to simply open these feeds.

**Comment by SangwonOh** [comment]
@deepsurvey Hi. We recently changed our server settings. At that time, I made the redirect automatically. However, in order to make testing easier in a non-TLS environment, we have changed it to allow access to http again.

**Comment by nxtreaming** [comment]
You need deploy an ovenplayer by yourself, currently the demo.ovenplayer.com is https://, wss://  only.
