### ISSUE TITLE
OME behind LoadBalancer

### ISSUE THREAD

**Issue by Thunder80** [AirenSoft/OvenMediaEngine#748]
**PROBLEM**
We are trying to use a Linode load balancer in front of OME and trying to ingest an RTMP stream but getting this error `Invalid RTMP version: 80, expected: 3`

**EXPECTATION**

RTMP stream should be successfully streamed to OME.

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

We am using this airensoft/ovenmediaengine:dev docker image.(we are just using the command given in the OME dockerhub, we have tried with the `latest` and the `dev` image)

- Encoder information

We are using OBS.

- URL

rtmp://IP:1935/app

- Operating system and version

Mac OS 11.6

**SETUP INFORMATION AND LOGS**
We are using the default config files.

**OTHER HELPFUL INFORMATION**

We are able to stream to the server without the load balancer successfully, i.e. the OBS shows connected. But trying with the load balancer the OBS is stuck at connecting and had to be force quit.
<img width="1007" alt="Screenshot_2022-04-25_at_20 03 59" src="https://user-images.githubusercontent.com/43901109/165116293-c45b88fb-91a7-4771-a0ed-e1cc01eed0f7.png">

**Comment by dimiden** [comment]
@Thunder80 
I assume that the packet sent by Load Balancer is not in RTMP format.
The RTMP handshake should start with ```0x03``` (RTMP version), but the value is actually 0x50 (80, ```P``` in ASCII code).
I think the load balancer you are using is working in HTTP mode and sending ```P*```(maybe ```POST``` or ```PUT```?) requests.

**Comment by dimiden** [comment]
@Thunder80 
I'm sorry but I can't help you with why the load balancer sends packets other than RTMP packets.
I think it would be better to ask the Linode load balancer provider about this issue.

**Comment by Thunder80** [comment]
Sure thanks.
