### ISSUE TITLE
Error: Could not set certificate: (OpenSSL) Certificate is nullptr

### ISSUE THREAD

**Issue by djkunedo** [AirenSoft/OvenMediaEngine#749]
Hello everyone. I'm getting this error `Error: Could not set certificate: (OpenSSL) Certificate is nullptr` trying to setup the TLS encryption. All the info about my environment and the solutions I tried are in this thread:
https://github.com/AirenSoft/OvenMediaEngine/issues/574#issuecomment-1108772913_

I'd like to know if it could be something wrong with the certificate I'm using, the path I'm using in the Server.xml or whatever. Thanks for your help.
P.D: I can't change right tags (Assignees, labels, projects, etc.) since I opened the issue through the mentioned thread, sorry. Let me know if this one should be closed and I'll open a new one. Thanks.

**Comment by getroot** [comment]
Did you solve this problem?

Most certificates require <ChainCertPath> to be set. Otherwise, the browser will consider the certificate invalid.

And the certificate is assigned to the domain. Set the domain assigned to the certificate in OME and access it with that domain when accessing.
