### ISSUE TITLE
Performance Benchmarks? 

### ISSUE THREAD

**Issue by dangolbeeker** [AirenSoft/OvenMediaEngine#752]
Hello is there any performance benchmarks available? 
I want to get a basic feel for how many concurrent users via rtmp per cpu. 
I found with media soup I can do around 450.

**Comment by getroot** [comment]
You can measure the performance yourself using OvenRtcTester.

If you want large capacity, you may need to tune the kernel network settings and tune the number of threads in OME.

https://airensoft.gitbook.io/ovenmediaengine/performance-tuning#performance-test

**Comment by basisbit** [comment]
> concurrent users via rtmp per cpu

Are you referring to inbound streams or outbound / distributed streams to receiving clients? With or without video transcoding? What inbound video bitrate and what encoding? How many concurrently viewing clients per inbound video stream? What kind of CPU and bare metal or containerized or in a virtual machine?

I can't really offer any numbers regarding concurrent inbound streams, but I regularly handle between 1000 and 5000 concurrent stream viewers with a few dozen non-dedicated virtual CPU threads (vCores) using very cheap Hetzner Cloud (AMD) and DigitalOcean Cloud (non-premium Intel) and Ionos. However, the limiting factor of those systems for me is outbound bandwidth long before CPU gets to be any problem. Majority of CPU load is spent on TLS encryption and handling the network packages + connections. 

Depending on the use case, I sometimes also rent a dedicated / bare metal server for a few hours, which then handles video transcoding to multiple bitrates, replaces b-frames and so on. When using a cluster setup, only one server needs to do the CPU-heavy transcoding tasks, and then edge servers all just pull the ready to use video frames over OVT protocol, and the edge servers then put those frames into HLS chunks or sends them over WebRTC to the client.
For those, WebRTC over UDP approximately has 50% more CPU overhead than HLS from my experience, and WebRTC over TCP adds a few more percent of overhead.

Hope this helps. If you decide to gather your own load testing data, please consider sharing your results here later on.
