### ISSUE TITLE
2 players + 2 streams 

### ISSUE THREAD

**Issue by Byskoven62** [AirenSoft/OvenMediaEngine#754]
Hello.
Is there maybe someone who can help me?
I would like to have 2 players on the same page with which run 2 different streams. I would like to be able to use  ovenPlayer.on("error", function () on both player 1 and 2. It works in such a way that when a stream arrives it hides $ ("fadein") and when it goes into error it removes the player and shows $ ("fadein" again). Both players should be able to do that. 

My player code looks like this: 

<script>
  let webrtcSources = OvenPlayer.generateWebrtcUrls ([
{
host: "wss: // XXXX: 3334 / XXXX / XXX? transport = tcp",
application: "app",
stream: "live",
label: "WebRTC"
}
]);
var ovenPlayer = null;
function loadOvenPlayer () {
if (ovenPlayer) {
ovenPlayer.remove ();
}
        ovenPlayer = OvenPlayer.create ("player", {
image: "/default_images/cam.png",
    autoStart: true,
    mute: true,
    sources: webrtcSources
});
ovenPlayer.on ("error", function () {
setTimeout (function () {loadOvenPlayer ();}, 5000);
$ ("fadein"). show ();
ovenPlayer.remove ();
})
            ovenPlayer.on ("ready", function () {
$ ("fadein"). hide ();
});
}
loadOvenPlayer ();
    </script>

Thanks in advance!

**Comment by getroot** [comment]
Please write to https://github.com/AirenSoft/OvenPlayer repository.
