### ISSUE TITLE
Pushing Equirectangular (360 deg) video and rendering live in  A-frame framework?

### ISSUE THREAD

**Issue by ysliew** [AirenSoft/OvenMediaEngine#756]
VR framework **_A-frame_** allows rendering Equirectangular video to create immersive VR experience in web-browser.

Implementation detial here:  https://aframe.io/docs/1.3.0/primitives/a-videosphere.html

Wonder if we could push _live WebRTC Equirectangular video feeds_ from OvenMediaEngine using the above snippet?

**Comment by htliu6** [comment]
@ysliew Hi, have you solved this problem?

**Comment by ysliew** [comment]
@htliu6 

No luck.

Need attention and help from the masters' from the community to make this happen.
