### ISSUE TITLE
Using Variant Configuration / Master Playlist

### ISSUE THREAD

**Issue by Morpheus235** [AirenSoft/OvenMediaEngine#759]
Hi, 

I was just testing the latest Master and LLHLS Provider. I saw the changes regarding Variants and Master Playlist and thought I would give it a shot. While my config entries are accepted the Playlist (llhls.m3u8) does not include any of the Variant tracks. So my Question is how this config entry should look like or if this even does already work?

example:                                                                 
```
<Video>
   <Codec>h264</Codec>
   <Bitrate>4500000</Bitrate>
   <Framerate>30</Framerate>
   <Width>1920</Width>
   <Height>1080</Height>
   <Preset>faster</Preset>
   <Variant>
      <Active>True</Active>
      <Name>360p</Name>
      <Codec>h264</Codec>
      <Bitrate>500000</Bitrate>
      <Framerate>30</Framerate>
      <Width>640</Width>
      <Height>360</Height>
      <Preset>faster</Preset>
   </Variant>
   <Variant>
      <Name>720p</Name>
      <Codec>vp8</Codec>
      <Bitrate>2500000</Bitrate>
      <Framerate>30</Framerate>
      <Width>1280</Width>
      <Height>720</Height>
      <Preset>faster</Preset>
   </Variant>
</Video>
```

**Comment by getroot** [comment]
LLHLS is still under development. I plan to open LLHLS in pre-alpha next week. Then I will upload the manual together. (The HTTP/2 module must be turned on for normal operation.)

And ABR is the next task. ABR is not implemented yet. The Variant structure of the configuration will be deprecated and a different structure will be used.

**Comment by Morpheus235** [comment]
Thanks for the info I was just curious if it could already be tested.
LLHLS with the default Configuration works in my testing Enviroment and results in a ~3 second Delay with default configuration. 
Any attempt on my behalf by trying lower the settings (segmentDuration, segmentCount, etc) resulted in very unstable Playback with constant buffering.

Also I had a repeating warning in the logs that the Frame Size is supposedly 0 but Playback and Transcoding still worked flawlessly

**Comment by getroot** [comment]
Please discuss further issues related to LLHLS in the #766. Thank you.
