### ISSUE TITLE
RtcSession maybe duplicated?

### ISSUE THREAD

**Issue by xiaozhihong** [AirenSoft/OvenMediaEngine#76]
Hello,  OvenMediaEngine is a nice project. I found the code how to locate the RtcSession which is simpily find by ufrag. If there are many session, it probability confilct. Is there any good method to locate one RtcSession? Thanks

**Comment by dimiden** [comment]
@xiaozhihong 
Thank you for using OvenMediaEngine!
Because ```ufrag``` is created by IcePort::GenerateUfrag() uniquely, it won't conflict. 
Therefore, you can use ```ufrag``` to distinguish the ```RtcSession```.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
