### ISSUE TITLE
WebRTC Source from ffmpeg or similar?

### ISSUE THREAD

**Issue by Phygon** [AirenSoft/OvenMediaEngine#762]
Is it possible to send a stream via WebRTC to OvenMediaEngine via ffmpeg (or similar tool), to avoid the AAC=>Opus transcoding on the server?

I guess that the signaling would have to be done in an external script which starts ffmpeg.

**Comment by getroot** [comment]
In theory, sending srtp/dtls packets using ffmpeg should work. But I don't know if you can fine-tune the rtp packets with ffmpeg. (For example, put the ssrc negotiated in the signaling phase, etc.)

**Comment by Phygon** [comment]
You can set the SSRC and Payload Type. For example via tee muxer (to send audio and video):
```bash
ffmpeg [...] \
-f tee \
"[select=a:f=rtp:ssrc=${AUDIO_SSRC}:payload_type=${AUDIO_PT}]rtp://${AUDIO_IP}:${AUDIO_PORT}?rtcpport=${AUDIO_RTCPPORT}|[select=v:f=rtp:ssrc=${VIDEO_SSRC}:payload_type=${VIDEO_PT}]rtp://${VIDEO_IP}:${VIDEO_PORT}?rtcpport=${VIDEO_RTCPPORT}"
```
AFAIK, you need different ports for audio and video, and rtcp support is very limited.

**Comment by getroot** [comment]
How about considering the RTSP Pull?
Currently, OME's RTSP Pull Provider supports H.264, VP8, AAC, and OPUS.

https://airensoft.gitbook.io/ovenmediaengine/live-source/rtsp-pull-beta

**Comment by Phygon** [comment]
> How about considering the RTSP Pull? Currently, OME's RTSP Pull Provider supports H.264, VP8, AAC, and OPUS.

I don't have an origin server to pull from. And the source is usually behind a NAT or firewall.

SRT Push works quite well for this, but we want to try to reduce the latency a bit more.
