### ISSUE TITLE
OME received signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by danruser** [AirenSoft/OvenMediaEngine#763]
**Describe the bug**
With the latest version of the master branch, the following happens: approximately two minutes after starting the connection of viewers this message appears and all connections are closed

OME received signal 6 (SIGABRT), interrupt

There is a crash dump  in the folder where OME is located, I attach them and copy of binary.

All settings its default

**Server (please complete the following information):**
 - Ubuntu 20.04 
 - Master Branch: Last version [c455a0b]

[OME_binary_dumpcrash.zip](https://github.com/AirenSoft/OvenMediaEngine/files/8693568/OME_binary_dumpcrash.zip)

**Comment by getroot** [comment]
I just fixed one crash issue. Could you please check if it still reproduces?

**Comment by danruser** [comment]
Hello.
You fixed it. The problem no longer exists
Thank you

**Comment by getroot** [comment]
Thank you!
