### ISSUE TITLE
Question: is it possible to make two parallel records of one stream?

### ISSUE THREAD

**Issue by dva-re** [AirenSoft/OvenMediaEngine#765]
For example, I need to make one entry for the whole hour, and in parallel with this, make additional entries for any event.

Or that's exactly my problem.

I make separate entries by event. When the event occurs, I call stopRecord and then startRecord with the new filename.

I don’t know yet why, but sometimes the request for stopRecord does not pass even after several attempts and dies by timeout. In the OME log, I don't see this request at all in this case. At the same time, for some reason, startRecord always succeeds. And I get into a situation where my previous record is still in the "recording" state, while the new one is in the "ready" state. As a result, I get incorrect records.

I'm thinking of writing a script that will periodically request the app:records method, parse the response, and finish the stuck records. But I would like new records to start from the moment startRecord is called and not from the moment the previous one stops.

Maybe in the config I need to add the number of workers or something like that?

Record documentation, unfortunately, is very scarce and I did not find in it either the life cycle of the record or the description of the states. I searched badly?

**Comment by dva-re** [comment]
I'll try to answer myself.

I have 2 broadcasts at the same time and there was one recording for each of them at the same time. The third entry (second for any thread) could not run in parallel with them. And config:

```
<AppWorkerCount>2</AppWorkerCount>
<StreamWorkerCount>4</StreamWorkerCount>
```

But I changed the configuration of the workers and it seems that now there is no such restriction.

new config
```
<AppWorkerCount>8</AppWorkerCount>
<StreamWorkerCount>8</StreamWorkerCount>
```

It was a limitation due to AppWorkerCount, right?

Or is it just a coincidence that it's now working?

**Comment by getroot** [comment]
OME can have multiple recording sessions at the same time as system performance permits.

`<AppWorkerCount>` is the number of threads that process multiple streams distributedly.
`<StreamWorkerCount>` is the number of threads that process multiple sessions distributedly.
So `<AppWorkerCount>` and `<StreamWorkerCount>` are not related to simultaneous recording. Perhaps your recording was successful because of something else.

**Comment by getroot** [comment]
If more detailed analysis is required, please provide your Server.xml and OvenMediaEngine.log files and the API request/response information used for the recording command.
