### ISSUE TITLE
HLS Segment name change

### ISSUE THREAD

**Issue by fcqpl** [AirenSoft/OvenMediaEngine#769]
It looks like OME is using incremental numbers in HLS segment name.
eg. `app/test/10.ts`
This produces problems with cache on some CDN.

For example - I start stream, wait for segment name `5.ts`, stop stream and start it again - CDN will give to client old cached segments (`1-5.ts`) instead new.

Could you add option to change this to actual time or some random string?

**Comment by getroot** [comment]
This could happen. That's good info.
However, I plan to deprecate the legacy HLS because LLHLS also supports legacy HLS. I will add a random key to the chunk list of the new LLHLS.

**Comment by fcqpl** [comment]
Removing legacy HLS isn't a good idea. llhls.m3u8 isn't working on HTTP1.1 only client. It's working only with HTTP2.

**Comment by getroot** [comment]
I had previously looked at the spec documentation incorrectly and incorrectly stated that it only works with 2.0. I am currently modifying LLHLS to work well with HTTP/1.1.

**Comment by getroot** [comment]
LLHLS Publisher has resolved this issue. LLHLS now also works over HTTP/1.1. Please refer to the thread below.
https://github.com/AirenSoft/OvenMediaEngine/issues/766#issuecomment-1133118495

**Comment by getroot** [comment]
Oh, I'm sorry.  For the cache to hit, I had to add one more function.  I'll add it and tell you again
