### ISSUE TITLE
Transcoder Latency?

### ISSUE THREAD

**Issue by jcdmacleod** [AirenSoft/OvenMediaEngine#77]
Does the transcoding add any measurable latency?  If glass-to-glass latency was critical what transcode options would be most lightweight?  Perhaps a better question would be what encode + transcode options would be most lightweight?

**Comment by getroot** [comment]
Live transcoding only adds 2 to 5 frames of time. Disabling B-Frame is the best option, and we have already removed this option from our code. And if you set a bitrate or framerate beyond the server's performance, it will increase the delay more and more. This depends on server performance so we can't answer it.

But we plan to introduce Hardware Encoder like Cuda or Quicksync. This can help with latency.

And the dev branch already has bypass introduced. A manual for this is being written, and you can check it out now in the code.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
