### ISSUE TITLE
Support for physical Output devices like Blackmagic Decklink Cards or HDMI

### ISSUE THREAD

**Issue by NK0D1NG** [AirenSoft/OvenMediaEngine#773]
**Is your feature request related to a problem? Please describe.**
Receiving Streams with OME and encoding/delivering them works fine in classic IP workflows. But it would be nice to output the incoming streams also on physical interfaces like HDMI, SDI and others. With this feature OME could also be used in other broadcasting environments like classical production environments (studios, live production sites ..) to receive streams from remote locations.

**Describe the solution you'd like**
I'd like to have the possiblity to output incoming streaming to physical devices like Blackmagic Decklink Cards or just simple HDMI outputs of the OME Server.

**Describe alternatives you've considered**
Normally I use tools which use ffmpeg for that or ffmpeg itself.

**Additional context**
For Blackmagic DeckLink cards there are a lot of SDK's and examples using them so the implementation shouldn't be that difficult. If you point me in the right direction where to start implementation I would be glad to help. For this I would need the information how OME receives the incoming video stream (and the corresponding frames and audio data). I think it should be possible to output that stream more or less directly to a the physical DeckLink Card.

**Comment by getroot** [comment]
I think it's better to run it as a separate piece of software. Protocols such as RTMP/MPEG-TS/SRT/RTSP are already supported to work with such software.

We have already developed and used that kind of software, and the software runs on almost different hardware. And it is more convenient and reliable to manage.

**Comment by Phygon** [comment]
It would be good to have SRT Pull, RTMP Pull or similar for that (see #767). I'm not sure if ffmpeg supports LLHLS.
