### ISSUE TITLE
OME does not follow "Accept-Encoding" request header

### ISSUE THREAD

**Issue by soukichi** [AirenSoft/OvenMediaEngine#776]
**Describe the bug**
OME always response with "Content-Encoding: gzip" even though a client request without "Accept-Encoding: gzip" header.

**To Reproduce**
$ curl -v http://localhost/app/live/llhls.m3u8 -H 'Accept-Encoding: identity' 

*   Trying 127.0.0.1:80...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /app/live/llhls.m3u8 HTTP/1.1
> Host: localhost
> User-Agent: curl/7.81.0
> Accept: */*
> Accept-Encoding: identity
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: *
< Content-Encoding: gzip
< Access-Control-Allow-Methods: GET
< Cache-Control: no-cache
< Access-Control-Allow-Credentials: true
< Vary: Origin
< Content-Length: 286
< Access-Control-Allow-Origin: *
< Content-Type: application/vnd.apple.mpegurl
< Server: OvenMediaEngine
< 

**Expected behavior**
OME should response a content without gzip compression if the request does not contain 'Accept-Encoding: gzip'.

**Server (please complete the following information):**
using airensoft/ovenmediaengine:dev docker image
Digest: sha256:24d3da56953c13f1cb6b8b46321cae31e9c9f346a41e697d3cf8be1262e3c73f

**Comment by getroot** [comment]
Thank you for reporting.

**Comment by getroot** [comment]
I solved this problem. Please check with the latest master branch.

**Comment by soukichi** [comment]
It works well. Thank you!
