### ISSUE TITLE
Selecting Tracks for Recording to File

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#778]
**Describe the bug**
Recording to files does not write the selected audio tracks.  Instead, it ignores the tracks selection and duplicates the first audio track for each live source audio track (6 duplicates in my case).

**To Reproduce**
1. Stream a live source with multiple audio tracks. (In my case 6)
2. Call startRecord REST API function with a track selection such as:
`curl -d '{ "id" : "vod", "stream": { "name": "quat", "tracks":[0,3,6] } }' -H 'Authorization: Basic '"${OME_AUTH_KEY}" -H 'Content-Type: application/json' http://192.168.1.8:8081/v1/vhosts/default/apps/hw60:startRecord`

**Expected behavior**
Selected audio tracks are written to the output file.

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/8788124/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Debian 11 Proxmox container
 - OvenMediaEngine Version: d02b7369ad99886304072d378cd3f5746bfcca63
 - Branch: master

**Additional context**
As far as I am aware this issue is similar to the issue I had with #685, but for the Recording publisher instead of RTMP Push.

**Comment by krakow10** [comment]
I tested your new commit with 2, and 6 audio tracks streamed from the live source, and selecting 2, 4, and 6 audio tracks for recording.  My tests show that the behaviour has changed so that the number of audio tracks selected is respected rather than ignored.  However, the recorded audio tracks are all duplicates of the first live source audio track.

**Comment by krakow10** [comment]
I tested this on v14.4 and the issue that all recorded audio tracks are duplicates of the first track remains.

**Comment by Keukhan** [comment]
@krakow10 

I've been working on other important things in the meantime, so I've only now solved this problem.
There was an issue where **bypassed audio tracks** were duplicated.

https://github.com/AirenSoft/OvenMediaEngine/compare/fd2af0ece964...42b5f426da0f

I applied it to the master, so test it

**Comment by krakow10** [comment]
I tested your changes and the issue is resolved for my configuration, thanks for your great work!
