### ISSUE TITLE
Measuring Latency

### ISSUE THREAD

**Issue by jcdmacleod** [AirenSoft/OvenMediaEngine#78]
I see on some of the OME screenshots that there is a bug overlay showing what appears to be native vs application latency.  Do you have any test code you could share on how you accomplish this or how to get accurate documented glass-to-glass or end-to-end latency?

**Comment by getroot** [comment]
See the following URL : https://airensoft.gitbook.io/ovenmediaengine/getting-started

When we tested the glass-to-glass, most of the time was 0.5 seconds. 
The easiest way is to overlay the timer on the OBS, play it with WebRTC, and take a picture of the OBS (original) and WebRTC Player together.

I don't understand about "OME screenshots that there is a bug overlay". Could you explain it in detail?

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
