### ISSUE TITLE
Hardwareprocessing via intel GPU possible?

### ISSUE THREAD

**Issue by morbificagent** [AirenSoft/OvenMediaEngine#780]
Hi there,

as i saw the last releases gave the possibility to use nvidia cuda for processing... Personaly i am using a server with an intel cpu which is able to do h264/265 processing jobs and i am using it in other applications in the moment.

is ome able to use it too or are nvidia cards the only possibility of hardware acceleration?

many thanks

**Comment by krakow10** [comment]
https://airensoft.gitbook.io/ovenmediaengine/transcoding/gpu-usage

**Comment by morbificagent** [comment]
Many thanks for the information, looks good!

It looks like only Nvidia can be used when using the docker version of ome right?
