### ISSUE TITLE
Application does not exist

### ISSUE THREAD

**Issue by msalai** [AirenSoft/OvenMediaEngine#781]
I am using Ubuntu 18 on Contabo vps and when I install and try to stream rtmp from OBS or FFMPEG I get this message when I type systemctl status ovenmediaengine:

May 29 23:08:30 vmi893595.contaboserver.net OvenMediaEngine[3080]: [2022-05-29 23:08:30.329] E [SPRTMP-T1935:3105] RTMPProvider | rtmp_stream.cpp:269  | #default#live application does not exist

I reinstalled everything several times and still same issue.

On virtual machine, I was able to test it without issue.

**Comment by getroot** [comment]
Check Server.xml. Does Server.xml have an application named live ?

https://airensoft.gitbook.io/ovenmediaengine/configuration#application

**Comment by getroot** [comment]
Thank you for confirmation.
