### ISSUE TITLE
How to show "waiting for a meeting" before stream starts?

### ISSUE THREAD

**Issue by msalai** [AirenSoft/OvenMediaEngine#784]
I am trying to make meeting app in which people can watch stream which starts at certain time, but before meeting starts, I would like to show/stream screen showing message that meeting will start soon. Is that possible and what approach should I take to accomplish that?

**Comment by Adam1901** [comment]
Display a static image before the stream starts and use the webhook to tell your app to display the video rather than the static image

**Comment by msalai** [comment]
Great suggestion! Thank you very much.
