### ISSUE TITLE
How to download/play recorded stream?

### ISSUE THREAD

**Issue by msalai** [AirenSoft/OvenMediaEngine#785]
After stream is recorded, I need to download it or play it. Do I need to make backend service for that or there is option/API for that already? If not, maybe you could implement it one day.

**Comment by getroot** [comment]
To download or play recorded files, you need to create a backend service. 
OME has no plans to develop a function to download or play recorded files in the future.

**Comment by msalai** [comment]
Ok, just wanted to be sure before I invest time in backend :)

Thanks for quick response.
