### ISSUE TITLE
bad_alloc on LLHLS

### ISSUE THREAD

**Issue by IceOwl94** [AirenSoft/OvenMediaEngine#786]
**Describe the bug**
bad_alloc on LLHLS

**To Reproduce**
Run Docker version with default settings, stream from OBS

**Expected behavior**
Application should not crash with bad_alloc with default settings

**Logs**
terminate called after throwing an instance of 'std::bad_alloc'
what():  std::bad_alloc
[2022-06-04 10:54:15.920] C [AW-LLHLS0:33] OvenMediaEngine | signals.cpp:114  | OME received signal 6 (SIGABRT), interrupt.

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.4
 - OvenMediaEngine Version: 0.14.0

**Comment by getroot** [comment]
This issue does not reproduce in my environment. It seems that some condition is necessary for a crash to occur. Please provide more information to reproduce the problem.

1. What encoder are you using and how did you set up the codec?
2. What command did you run docker with?
3. Please upload the entire log from execution to crash. Full logs are essential to analyzing the problem.

Please let me know if you have any other information I need to reproduce the problem.

**Comment by IceOwl94** [comment]
Thank you for your response

1. I try different OBS settings and several iOS app (Streamlabs Mobile, Larix Broadcaster, Prism Studio) and the result doesn't change
2. command: "/opt/ovenmediaengine/bin/OvenMediaEngine -c origin_conf" where the conf is the default one
3. There are no additional logs before crashing, log level is set to "debug"
`
origin_1      | [2022-06-04 15:34:43.627] I [OvenMediaEngine:1] Config | config_manager.cpp:205  | Trying to set logfile in directory... (/var/log/ovenmediaengine)
origin_1      | [2022-06-04 15:34:43.631] I [OvenMediaEngine:1] Config | config_manager.cpp:227  | Trying to load configurations... (origin_conf/Server.xml)
origin_1      | [2022-06-04 15:34:43.763] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:23   | OvenMediaEngine v0.14.0 () is started on [d31366e89820] (Linux x86_64 - 5.4.0-113-generic, #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022)
origin_1      | [2022-06-04 15:34:43.763] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:27   | With modules:
origin_1      | [2022-06-04 15:34:43.763] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:28   |   FFmpeg 4.4.1
origin_1      | [2022-06-04 15:34:43.763] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:29   |     Configuration: --prefix=/opt/ovenmediaengine --extra-cflags='-I/opt/ovenmediaengine/include ' --extra-ldflags='-L/opt/ovenmediaengine/lib -Wl,-rpath,/opt/ovenmediaengine/lib' --extra-libs=-ldl --enable-shared --disable-static --disable-debug --disable-doc --disable-programs --disable-avdevice --disable-dct --disable-dwt --disable-lsp --disable-lzo --disable-rdft --disable-faan --disable-pixelutils --enable-zlib --enable-libopus --enable-libvpx --enable-libfdk_aac --enable-libopenh264 --enable-openssl --disable-nvdec --disable-nvdec --disable-vaapi --disable-vdpau --disable-cuda-llvm --disable-cuvid --disable-ffnvcodec --disable-everything --disable-fast-unaligned --enable-encoder='libvpx_vp8,libopus,libfdk_aac,libopenh264,mjpeg,png' --enable-decoder='aac,aac_latm,aac_fixed,h264,hevc,opus,vp8' --enable-parser='aac,aac_latm,aac_fixed,h264,hevc,opus,vp8' --enable-network --enable-protocol=tcp --enable-protocol=udp --enable-protocol='rtp,file,rtmp,tls,rtmps' --enable-demuxer='rtsp,flv,live_flv' --enable-muxer='mp4,webm,mpegts,flv,mpjpeg' --enable-filter='asetnsamples,aresample,aformat,channelmap,channelsplit,scale,transpose,fps,settb,asettb,format'
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:30   |     libavformat: 58.76.100
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:31   |     libavcodec: 58.134.100
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:32   |     libavutil: 56.70.100
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:33   |     libavfilter: 7.110.100
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:34   |     libswresample: 3.9.100
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:35   |     libswscale: 5.9.100
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:36   |   SRT: 1.4.4
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:37   |   SRTP: libsrtp2 2.4.2
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:38   |   OpenSSL: OpenSSL 3.0.2 15 Mar 2022
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:39   |     Configuration: compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:40   |   JsonCpp: 1.9.3
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | banner.cpp:41   |   jemalloc: 5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756
origin_1      | [2022-06-04 15:34:43.764] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:72   | Server ID : 784d116b-d7de-4e7e-9980-8e407805cddb
origin_1      | [2022-06-04 15:34:43.764] C [OvenMediaEngine:1] OvenMediaEngine | main.cpp:298  | Current kernel version: 5.4.0-113-generic
origin_1      | [2022-06-04 15:34:43.764] C [OvenMediaEngine:1] OvenMediaEngine | main.cpp:299  | Linux kernel version 5.3 through 5.6 have a critical bug. Please consider using a different version. (https://bugzilla.kernel.org/show_bug.cgi?id=205933)
origin_1      | [2022-06-04 15:34:43.798] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:81   | Resolved public IP address (138.68.99.82) from stun server (stun.l.google.com:19302)
origin_1      | [2022-06-04 15:34:43.864] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:111  | Trying to create MediaRouter...
origin_1      | [2022-06-04 15:34:43.864] I [OvenMediaEngine:1] MediaRouter | mediarouter.cpp:40   | Mediarouter has been started.
origin_1      | [2022-06-04 15:34:43.864] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:114  | Trying to create WebRTC Publisher...
origin_1      | [2022-06-04 15:34:43.865] I [OvenMediaEngine:1] Signalling.P2P | rtc_p2p_manager.cpp:27   | P2P is disabled in the configuration
origin_1      | [2022-06-04 15:34:43.883] W [OvenMediaEngine:1] HLS | hls_publisher.cpp:38   | HLS Publisher is disabled by configuration
origin_1      | [2022-06-04 15:34:43.896] W [OvenMediaEngine:1] DASH | dash_publisher.cpp:36   | DASH Publisher is disabled by configuration
origin_1      | [2022-06-04 15:34:43.896] W [OvenMediaEngine:1] LLDASH | cmaf_publisher.cpp:39   | LLDASH Publisher is disabled by configuration
origin_1      | [2022-06-04 15:34:43.909] W [OvenMediaEngine:1] Thumbnail | thumbnail_publisher.cpp:45   | ThumbnailPublisher is disabled by configuration
origin_1      | [2022-06-04 15:34:43.875] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10000/UDP (0x56494a986710)
origin_1      | [2022-06-04 15:34:43.876] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10001/UDP (0x56494aa97400)
origin_1      | [2022-06-04 15:34:43.876] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10002/UDP (0x56494aa9b900)
origin_1      | [2022-06-04 15:34:43.876] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10003/UDP (0x56494aa9fdc0)
origin_1      | [2022-06-04 15:34:43.880] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10004/UDP (0x56494aaa4320)
origin_1      | [2022-06-04 15:34:43.881] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10005/UDP (0x56494aaa8ff0)
origin_1      | [2022-06-04 15:34:43.881] I [OvenMediaEngine:1] ICE | ice_port.cpp:128  | ICE port is bound to *:3478/TCP (0x56494aaaec00)
origin_1      | [2022-06-04 15:34:43.881] I [OvenMediaEngine:1] ICE | ice_port_manager.cpp:94   | RelayServer is created successfully: host:3478?transport=tcp
origin_1      | [2022-06-04 15:34:43.881] I [OvenMediaEngine:1] WebRTC Publisher | webrtc_publisher.cpp:156  | WebRTC Publisher is listening on *:3333, TLS: *:3334...
origin_1      | [2022-06-04 15:34:43.881] I [OvenMediaEngine:1] Publisher | publisher.cpp:18   | WebRTC Publisher has been started.
origin_1      | [2022-06-04 15:34:43.882] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:115  | Trying to create LLHLS Publisher...
origin_1      | [2022-06-04 15:34:43.882] I [OvenMediaEngine:1] LLHLS Publisher | llhls_publisher.cpp:110  | LLHLS Publisher is listening on *:3333, TLS: *:3334
origin_1      | [2022-06-04 15:34:43.882] I [OvenMediaEngine:1] Publisher | publisher.cpp:18   | LLHLS Publisher has been started.
origin_1      | [2022-06-04 15:34:43.882] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:116  | Trying to create HLS Publisher...
origin_1      | [2022-06-04 15:34:43.895] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:117  | Trying to create MPEG-DASH Publisher...
origin_1      | [2022-06-04 15:34:43.896] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:118  | Trying to create Low-Latency MPEG-DASH Publisher...
origin_1      | [2022-06-04 15:34:43.896] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:119  | Trying to create OVT Publisher...
origin_1      | [2022-06-04 15:34:43.897] I [OvenMediaEngine:1] OVT | ovt_publisher.cpp:58   | OVTPublisher is listening on *:9000/TCP
origin_1      | [2022-06-04 15:34:43.897] I [OvenMediaEngine:1] Publisher | publisher.cpp:18   | OVTPublisher has been started.
origin_1      | [2022-06-04 15:34:43.898] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:120  | Trying to create File Publisher...
origin_1      | [2022-06-04 15:34:43.898] I [OvenMediaEngine:1] Publisher | publisher.cpp:18   | FilePublisher has been started.
origin_1      | [2022-06-04 15:34:43.898] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:121  | Trying to create MpegtsPush Publisher...
origin_1      | [2022-06-04 15:34:43.898] I [OvenMediaEngine:1] Publisher | publisher.cpp:18   | MPEGTSPushPublisher has been started.
origin_1      | [2022-06-04 15:34:43.898] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:122  | Trying to create RtmpPush Publisher...
origin_1      | [2022-06-04 15:34:43.899] I [OvenMediaEngine:1] Publisher | publisher.cpp:18   | RTMPPushPublisher has been started.
origin_1      | [2022-06-04 15:34:43.909] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:123  | Trying to create Thumbnail Publisher...
origin_1      | [2022-06-04 15:34:43.909] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:126  | Trying to create Transcoder...
origin_1      | [2022-06-04 15:34:43.910] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:129  | Trying to create WebRTC Provider...
origin_1      | [2022-06-04 15:34:43.910] I [OvenMediaEngine:1] Signalling.P2P | rtc_p2p_manager.cpp:27   | P2P is disabled in the configuration
origin_1      | [2022-06-04 15:34:43.919] I [OvenMediaEngine:1] ICE | ice_port.cpp:86   | ICE port is bound to 0.0.0.0:10006/UDP (0x56494abe82b0)
origin_1      | [2022-06-04 15:34:43.919] I [OvenMediaEngine:1] ICE | ice_port.cpp:128  | ICE port is bound to *:3478/TCP (0x56494aaaec00)
origin_1      | [2022-06-04 15:34:43.919] I [OvenMediaEngine:1] ICE | ice_port_manager.cpp:94   | RelayServer is created successfully: host:3478?transport=tcp
origin_1      | [2022-06-04 15:34:43.930] I [OvenMediaEngine:1] WebRTC Provider | webrtc_provider.cpp:161  | WebRTCProvider is listening on *:3333, TLS: *:3334...
origin_1      | [2022-06-04 15:34:43.930] I [OvenMediaEngine:1] Provider | provider.cpp:37   | WebRTCProvider has been started.
origin_1      | [2022-06-04 15:34:43.930] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:130  | Trying to create MPEG-TS Provider...
origin_1      | [2022-06-04 15:34:43.935] I [OvenMediaEngine:1] MpegtsProvider | mpegts_provider.cpp:62   | MPEGTSProvider is listening on *:4000/UDP
origin_1      | [2022-06-04 15:34:43.935] I [OvenMediaEngine:1] Provider | provider.cpp:37   | MPEGTSProvider has been started.
origin_1      | [2022-06-04 15:34:43.941] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:131  | Trying to create SRT Provider...
origin_1      | [2022-06-04 15:34:43.947] I [OvenMediaEngine:1] SrtProvider | srt_provider.cpp:66   | SrtProvider is listening on *:9999/SRT
origin_1      | [2022-06-04 15:34:43.947] I [OvenMediaEngine:1] Provider | provider.cpp:37   | SrtProvider has been started.
origin_1      | [2022-06-04 15:34:43.947] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:132  | Trying to create RTMP Provider...
origin_1      | [2022-06-04 15:34:43.948] I [OvenMediaEngine:1] RTMPProvider | rtmp_provider.cpp:101  | RTMPProvider is listening on *:1935/TCP
origin_1      | [2022-06-04 15:34:43.948] I [OvenMediaEngine:1] Provider | provider.cpp:37   | RTMPProvider has been started.
origin_1      | [2022-06-04 15:34:43.948] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:133  | Trying to create OVT Provider...
origin_1      | [2022-06-04 15:34:43.948] I [OvenMediaEngine:1] Provider | provider.cpp:37   | OVTProvider has been started.
origin_1      | [2022-06-04 15:34:43.949] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:134  | Trying to create RTSPC Provider...
origin_1      | [2022-06-04 15:34:43.949] I [OvenMediaEngine:1] Provider | provider.cpp:37   | RTSPCProvider has been started.
origin_1      | [2022-06-04 15:34:43.949] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:135  | Trying to create File Provider...
origin_1      | [2022-06-04 15:34:43.949] I [OvenMediaEngine:1] Provider | provider.cpp:37   | FileProvider has been started.
origin_1      | [2022-06-04 15:34:43.949] I [OvenMediaEngine:1] OvenMediaEngine | main.cpp:142  | All modules are initialized successfully
origin_1      | [2022-06-04 15:34:43.949] I [OvenMediaEngine:1] Monitor | monitoring.cpp:72   | OvenMediaEngine(784d116b-d7de-4e7e-9980-8e407805cddb) ServerMetric has been started for monitoring - 2022-06-04T15:34:43.949+00:00
origin_1      | [2022-06-04 15:34:43.950] I [OvenMediaEngine:1] Monitor | server_metrics.cpp:55   | Create HostMetrics(default/784d116b-d7de-4e7e-9980-8e407805cddb/default) for monitoring
origin_1      | [2022-06-04 15:34:43.950] I [OvenMediaEngine:1] Orchestrator | orchestrator_internal.cpp:701  | Trying to create an application: [#default#app]
origin_1      | [2022-06-04 15:34:43.950] I [OvenMediaEngine:1] Monitor | host_metrics.cpp:57   | Create ApplicationMetrics(#default#app/784d116b-d7de-4e7e-9980-8e407805cddb/default/#default#app) for monitoring
origin_1      | [2022-06-04 15:34:43.950] I [OvenMediaEngine:1] MediaRouter | mediarouter_application.cpp:44   | Created Mediarouter application. application id(0), app(#default#app), worker(1)
origin_1      | [2022-06-04 15:34:43.951] I [OvenMediaEngine:1] MediaRouter | mediarouter_application.cpp:99   | Started Mediarouter application. application id(0), app(#default#app)
origin_1      | [2022-06-04 15:34:43.951] I [OvenMediaEngine:1] MediaRouter | mediarouter.cpp:83   | Created Mediarouter. app(#default#app)
origin_1      | [2022-06-04 15:34:43.973] W [OvenMediaEngine:1] Publisher | publisher.cpp:69   | File publisher is disabled in #default#app application, so it was not created
origin_1      | [2022-06-04 15:34:43.973] W [OvenMediaEngine:1] Publisher | publisher.cpp:69   | MPEGTSPush publisher is disabled in #default#app application, so it was not created
origin_1      | [2022-06-04 15:34:43.973] W [OvenMediaEngine:1] Publisher | publisher.cpp:69   | RTMPPush publisher is disabled in #default#app application, so it was not created
origin_1      | [2022-06-04 15:34:43.972] I [OvenMediaEngine:1] Publisher | application.cpp:161  | WebRTC Publisher Application has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.973] I [OvenMediaEngine:1] Publisher | application.cpp:161  | LLHLS Publisher Application has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.973] I [OvenMediaEngine:1] Publisher | application.cpp:161  | OVTPublisher Application has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.973] I [OvenMediaEngine:1] Transcoder | transcoder_application.cpp:31   | Created transcoder application. app(#default#app)
origin_1      | [2022-06-04 15:34:43.973] I [OvenMediaEngine:1] Transcoder | transcoder.cpp:86   | Transcoder has created [config][#default#app] application
origin_1      | [2022-06-04 15:34:43.974] I [OvenMediaEngine:1] Provider | application.cpp:45   | WebRTCProvider has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.974] I [OvenMediaEngine:1] Monitor | application_metrics.cpp:106  | MPEG-TS has reserved stream_4000 stream linked to UDP://0.0.0.0:4000
origin_1      | [2022-06-04 15:34:43.974] I [OvenMediaEngine:1] Provider | application.cpp:45   | MPEGTSProvider has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.974] I [OvenMediaEngine:1] Provider | application.cpp:45   | SrtProvider has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.974] I [OvenMediaEngine:1] Provider | application.cpp:45   | RTMPProvider has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.987] I [OvenMediaEngine:1] Provider | application.cpp:45   | OVTProvider has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.987] I [OvenMediaEngine:1] Provider | application.cpp:45   | RTSPCProvider has created [#default#app] application
origin_1      | [2022-06-04 15:34:43.988] I [OvenMediaEngine:1] APIServer | api_server.cpp:166  | API Server is disabled
origin_1      | [2022-06-04 15:34:56.589] I [SPRTMP-T1935:29] Provider | stream.cpp:49   | Unknown/(33) has been started stream
origin_1      | [2022-06-04 15:34:56.591] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:152  | A RTMP client has connected from <ClientSocket: 0x7fad000018c0, #33, Connected, TCP, Nonblocking, 172.22.0.4:53036>
origin_1      | [2022-06-04 15:34:56.599] I [SPRTMP-T1935:29] MediaRouter | mediarouter_application.cpp:244  | Trying to create a stream: [#default#app/XXXXXXXXXXXXXXXXXXX(33)]
origin_1      | [2022-06-04 15:34:56.601] I [SPRTMP-T1935:29] MediaRouter | mediarouter_application.cpp:245  | 
origin_1      | [Stream Info]
origin_1      | id(33), msid(0), output(XXXXXXXXXXXXXXXXXXX), SourceType(Rtmp), Created Time (Sat Jun  4 15:34:56 2022) UUID(784d116b-d7de-4e7e-9980-8e407805cddb/default/#default#app/XXXXXXXXXXXXXXXXXXX/i)
origin_1      | 
origin_1      | 	Video Track #0: Bypass(false) Bitrate(2.50Mb) codec(1, H264) resolution(1280x720) framerate(30.00fps) timebase(1/1000)
origin_1      | 	Audio Track #1: Bypass(false) Bitrate(160.00Kb) codec(6, AAC) samplerate(48.0K) format(s16, 16) channel(mono, 1) timebase(1/1000)
origin_1      | [2022-06-04 15:34:56.605] I [SPRTMP-T1935:29] MediaRouter | mediarouter_stream.cpp:54   | Trying to create media route stream: name(XXXXXXXXXXXXXXXXXXX) id(33)
origin_1      | [2022-06-04 15:34:56.606] I [SPRTMP-T1935:29] Monitor | application_metrics.cpp:57   | Create StreamMetrics(XXXXXXXXXXXXXXXXXXX/784d116b-d7de-4e7e-9980-8e407805cddb/default/#default#app/XXXXXXXXXXXXXXXXXXX/i) for monitoring
origin_1      | [2022-06-04 15:34:56.607] I [SPRTMP-T1935:29] Transcoder | transcoder_stream.cpp:565  | [#default#app/XXXXXXXXXXXXXXXXXXX(33)] -> [#default#app/XXXXXXXXXXXXXXXXXXX(3453350447)] Output stream has been created.
origin_1      | [2022-06-04 15:34:56.615] I [SPRTMP-T1935:29] MediaRouter | mediarouter_application.cpp:244  | Trying to create a stream: [#default#app/XXXXXXXXXXXXXXXXXXX(3453350447)]
origin_1      | [2022-06-04 15:34:56.623] I [SPRTMP-T1935:29] MediaRouter | mediarouter_application.cpp:245  | 
origin_1      | [Stream Info]
origin_1      | id(3453350447), msid(0), output(XXXXXXXXXXXXXXXXXXX), SourceType(Transcoder), Created Time (Sat Jun  4 15:34:56 2022) UUID(784d116b-d7de-4e7e-9980-8e407805cddb/default/#default#app/XXXXXXXXXXXXXXXXXXX/o)
origin_1      | 	>> Origin Stream Info
origin_1      | 	id(33), output(XXXXXXXXXXXXXXXXXXX), SourceType(Rtmp), Created Time (Sat Jun  4 15:34:56 2022)
origin_1      | 
origin_1      | 	Video Track #0: Bypass(true) Bitrate(2.50Mb) codec(1, H264) resolution(1280x720) framerate(30.00fps) timebase(1/1000)
origin_1      | 	Audio Track #1: Bypass(true) Bitrate(160.00Kb) codec(6, AAC) samplerate(48.0K) format(s16, 16) channel(mono, 1) timebase(1/1000)
origin_1      | 	Audio Track #2: Bypass(false) Bitrate(128.00Kb) codec(8, OPUS) samplerate(48.0K) format(s16, 16) channel(stereo, 2) timebase(1/48000)
origin_1      | [2022-06-04 15:34:56.628] I [SPRTMP-T1935:29] MediaRouter | mediarouter_stream.cpp:54   | Trying to create media route stream: name(XXXXXXXXXXXXXXXXXXX) id(3453350447)
origin_1      | [2022-06-04 15:34:56.629] I [SPRTMP-T1935:29] Monitor | application_metrics.cpp:57   | Create StreamMetrics(XXXXXXXXXXXXXXXXXXX/784d116b-d7de-4e7e-9980-8e407805cddb/default/#default#app/XXXXXXXXXXXXXXXXXXX/o) for monitoring
origin_1      | [2022-06-04 15:34:56.630] I [SPRTMP-T1935:29] Transcoder | transcoder_stream.cpp:100  | [#default#app/XXXXXXXXXXXXXXXXXXX(33)] Transcoder input stream has been started. Status : (1) Decoders, (0) Encoders
origin_1      | [2022-06-04 15:34:56.632] I [Decaac:38] Transcoder | decoder_aac.cpp:221  | [#default#app/XXXXXXXXXXXXXXXXXXX(33)] input stream information: [audio] aac (LC), 48000 Hz, stereo, fltp, 158 kbps, timebase: 1/1000, frame_size: 1024
origin_1      | [2022-06-04 15:34:56.649] I [OutboundWorker:31] WebRTC Publisher | rtc_stream.cpp:287  | Unsupported codec(Audio/AAC) is being input from media track
origin_1      | [2022-06-04 15:34:56.651] I [OutboundWorker:31] WebRTC Publisher | rtc_stream.cpp:361  | WebRTC Stream has been created : XXXXXXXXXXXXXXXXXXX/3453350447
origin_1      | Rtx(false) Ulpfec(false) JitterBuffer(false) PlayoutDelay(false min:0 max: 0)
origin_1      | [2022-06-04 15:34:56.655] I [OutboundWorker:31] Publisher | stream.cpp:202  | WebRTC Publisher Application application has started [XXXXXXXXXXXXXXXXXXX(3453350447)] stream (MSID : 0)
origin_1      | [2022-06-04 15:34:56.660] I [OutboundWorker:31] LLHLS Publisher | llhls_stream.cpp:81   | LLHlsStream(#default#app/XXXXXXXXXXXXXXXXXXX) - Ignore unsupported codec(OPUS)
origin_1      | [2022-06-04 15:34:56.663] I [OutboundWorker:31] LLHLS Publisher | llhls_stream.cpp:125  | LLHlsStream has been created : XXXXXXXXXXXXXXXXXXX/3453350447
origin_1      | Chunk Duration(0.50) Segment Duration(6) Segment Count(10)
origin_1      | [2022-06-04 15:34:56.665] I [OutboundWorker:31] Publisher | stream.cpp:202  | LLHLS Publisher Application application has started [XXXXXXXXXXXXXXXXXXX(3453350447)] stream (MSID : 0)
origin_1      | [2022-06-04 15:34:56.669] I [OutboundWorker:31] Publisher | stream.cpp:202  | OVTPublisher Application application has started [XXXXXXXXXXXXXXXXXXX(3453350447)] stream (MSID : 0)
origin_1      | terminate called after throwing an instance of 'std::bad_alloc'
origin_1      |   what():  std::bad_alloc
origin_1      | [2022-06-04 15:34:56.685] C [AW-LLHLS0:33] OvenMediaEngine | signals.cpp:114  | OME received signal 6 (SIGABRT), interrupt.
`
 4. Free RAM is always above 500MB, I am using a 1CPU 1GB Droplet from DigitalOcean. Version 0.13.2 works without any problems

I try to replicate it on another provider

**Comment by visualies** [comment]
same issue here on an ovh instance 1CPU 1GB.

**Comment by getroot** [comment]
Thanks for reporting.
I reproduced the problem by creating a DigitalOcean Droplet and fixed the problem.

Delete the image with `docker rmi airensoft/ovenmediaengine:0.14.0` and re-download it and check if the problem is solved.

**Comment by getroot** [comment]
`airensoft/ovenmediaengine:0.14.1` has been released.
