### ISSUE TITLE
query by source signal refresh rate.

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#789]
Sometimes, with signals HDMI coming from video sources with 59.94HZ (nearly 60) p or i frame rates, OME has problems with mpeg2 TS input and HLS playback. It seems that the packets arrive out of order and the audio is distorted. It's even hard to get connection to stream. when the refresh rate of the video signal is exactly 50 or 60hz there is no problem. maybe the problem is attributable to the encoder of the HDMI signal and not to OME?

**Comment by getroot** [comment]
When OME receives MPEG 2-TS, framerate and out of order issues are irrelevant. OME doesn't care if it comes in at 60 fps or 59.94 fps, it just processes it as it comes in.
