### ISSUE TITLE
Build Progress stuck when building for arm64v8

### ISSUE THREAD

**Issue by visualies** [AirenSoft/OvenMediaEngine#791]
**PROBLEM**

I'm trying to build the image for arm64v8 and get stuck on

```
[  1/443|  0%] Preparing directories...
    Preparing directory bin/RELEASE...
    Preparing directory intermediates/RELEASE/static...
[  3/443|  0%] [static] libapi_server.a: C++ projects/api_server/controllers/controller.cpp => intermediates/RELEASE/objs/api_server/controllers/controller.o
[  2/443|  0%] [static] libapi_server.a: C++ projects/api_server/api_server.cpp => intermediates/RELEASE/objs/api_server/api_server.o
[  4/443|  0%] [static] libapi_server.a: C++ projects/api_server/controllers/root_controller.cpp => intermediates/RELEASE/objs/api_server/controllers/root_controller.o
[  5/443|  1%] [static] libapi_server.a: C++ projects/api_server/controllers/v1/v1_controller.cpp => intermediates/RELEASE/objs/api_server/controllers/v1/v1_controller.o
```

**EXPECTATION**

Build progress resuming or showing any errors to help me debug.

**ENVIRONMENTAL INFORMATION**

- Base image defined/updated in dockerfile: arm64v8/ubuntu:20.04
- Cloned repo to raspberry pi (arm) and started build process.
- Ovenmediaengine release 0.14.01
- Operating system: debian:bullseye

**Comment by getroot** [comment]
I'm guessing your system is running out of memory. Try make release -j 1

**Comment by visualies** [comment]
You are correct, I managed to resolve the issue by adding a swap file for the memory on the pi, although very slow, it built it all the way 👍
