### ISSUE TITLE
Suggestion to add an official ARM-based Docker container

### ISSUE THREAD

**Issue by sezze** [AirenSoft/OvenMediaEngine#794]
**Is your feature request related to a problem? Please describe.**
Due to ARM processors often being more efficient, cloud providers are providing ARM-based servers at a lower price than x64. ARM is also increasing in popularity in general.

**Describe the solution you'd like**
I suggest having an official ARM-based Docker container, which can be run at cloud providers with potentially the same performance but with lower costs. It could also be run on home computers with ARM chips.

**Comment by getroot** [comment]
That's a good suggestion.

However, officially adding the docker image significantly increases the cost of open source operation, such as adding a build system, more testing, and managing related issues.

If anyone can contribute on this topic I can share our official DockerHub account.

**Comment by Zibbp** [comment]
For those looking to locally build an ARM image. I had to add the `build-essential` package to the end of line five.
```
RUN     apt-get update && apt-get install -y tzdata sudo curl build-essential
```
From there I built the image on an ARM host although you can build it using Buildx and setting up an arm config on an x86 system.
