### ISSUE TITLE
RTP pull from Davinci Resolve

### ISSUE THREAD

**Issue by zcolor** [AirenSoft/OvenMediaEngine#797]
**Is your feature request related to a problem? Please describe.**

Davinci Resolve, a popular color correction software, has recently released v18. In that version, they announced the Resolve Remote Monitoring Solution. I'm still in contact with Blackmagic Design in order to get specifics on the technology. But from my investigation, it's RTP based. 

**Describe the solution you'd like**

Since OME already has the ability to pull RTSP from origin servers, I was wondering how difficult it would be to enable a connection to Davinci Resolve and have OME pull that stream.

**Comment by llspalex** [comment]
Do you have details on what codecs (video and audio) Resolve is using with the Remote Monitoring feature? OME supports H264 video and AAC audio when using RTSP Pull.

**Comment by zcolor** [comment]
It supports h264 4:2:0 8bit and h265 up to 4:4:4 12bit.

Not sure audio is supported at the moment, it's still in beta.

This is all the manual has to say about remote monitoring

> Introduction to DaVinci Remote Monitoring (Studio Version Only)

DaVinci Remote Monitoring is an application that allows you to have access to a low latency, high quality video signal over a network for editing and color grading purposes. This allows editors and colorists the ability to work remotely using the Resolve Interface and a data stream from a central DaVinci Resolve workstation. This data stream is of high enough quality that you can run the signal through a Blackmagic DeckLink or UltraStudio device to a grading monitor and have the same confidence in the output as if it was connected locally.

The stream quality can be adjusted for your particular needs and available bandwidth. For example, an editor may only need an HD h.264 8-bit 4:2:0 codec for offline editing, while a colorist may need the full UHD h.265 12 bit 4:4:4 RGB codec for HDR grading.

Chapter 195 Remote Grading and Remote Monitoring 3957

For clarity in this section we will refer to the main DaVinci Resolve workstation in the post house or data center that is streaming the video as the “Resolve Server”, and the workstation that is receiving the stream as the “Resolve Client.” However in reality these are just two computers running the same version of the DaVinci Resolve Studio and the DaVinci Remote Monitoring apps, and have nothing to do with the DaVinci Resolve Project Server described in an earlier chapter.
Requirements for DaVinci Remote Monitoring
The Resolve Server must have the following hardware and software requirements for DaVinci Remote Monitoring to work:
— The Resolve Server needs an RTX series NVIDIA GPU and drivers installed. AMD GPUs are currently incompatible.
— The Resolve Server needs to have the Linux or Windows version of DaVinci Resolve Studio installed. macOS is currently incompatible for use as the Resolve Server.
— The Resolve Server must have the “Allow Remote Streaming Connections” box checked in the General section of the System Preferences.
The Resolve Client must have the following hardware and software requirements for DaVinci Remote Monitoring to work:
— The Resolve Client needs an RTX series NVIDIA GPU and drivers installed. AMD GPUs are currently incompatible.
— The Resolve Client must have the Linux or Windows version of DaVinci Resolve Studio installed.
— The Resolve Client can be a Mac with the DaVinci Resolve Studio macOS version installed, but will be limited to an 8-bit 4:2:0 stream only.
— The Resolve Client can use a Blackmagic DeckLink or UltraStudio for broadcast quality output of the data stream to a grading monitor.
— The Resolve Client can use an ethernet capable control surface like the DaVinci Resolve Advanced or Mini Panels, provided they are setup to connect over the network to the Resolve Server.
The network connecting the Server and Client must meet the following requirements for DaVinci Remote Monitoring to work:
— The same version of DaVinci Resolve Studio and the DaVinci Remote Monitoring app must be used on the client and server computers.
— Both Resolve Client and Server must be on the same network, either locally via LAN, or over the internet via VPN etc.
— TCP port 16410 must be open between the systems.
— You must know the IP address of the Resolve Server.
— The Resolve Client must have some application for remotely controlling the desktop of the Resolve Server installed and running, giving them keyboard and mouse input to the server.

Chapter 195 Remote Grading and Remote Monitoring 3958

Setting Up DaVinci Remote Monitoring

To start a DaVinci Remote Monitoring session, the Resolve Client must connect to the Resolve Server
by opening the DaVinci Remote Monitoring application. A settings window will then allow you to determine the parameters of the remote session. The DaVinci Remote Monitoring application is installed automatically with DaVinci Resolve Studio, and is found in the DaVinci Resolve folder.

— IP Address: Input the IP address of the Resolve Server you want to connect to.
— Port: The Port used to connect is currently fixed at 16410.
— Output Device: Select a DeckLink or UltraStudio device connected to the Resolve Client for monitoring the data stream’s output.
— Automatically detect output mode: When checked, the output mode selected will automatically mirror the resolution and frame rate set in the Project Settings on the Resolve Server
— Output Mode: Lets you locally override the output resolution and frame rate settings of the project from the Resolve Server, when you uncheck the “Automatically detect output mode” box above.
— Video Codec: Sets the codec and bit depth of the data stream from the Resolve Server.
— Bit Rate: Sets the bit rate of the data stream from the Resolve Server.
When the settings are correct, click the Connect button in the lower right to start the DaVinci Remote Monitoring session.

The DaVinci Resolve Remote Monitoring application interface

Once the connection has been initiated from the Resolve Client, the Resolve Server must approve the connection by clicking accept on the resulting Initiate Remote Streaming dialog box. You can do this either physically on the server with a connected mouse, or over the network by using any kind of remote desktop software.
 
Chapter 195 Remote Grading and Remote Monitoring 3959

Accepting the Remote Monitoring session on the Resolve Server

Once the connected, the word “Streaming” is displayed in the lower left of the application along side the time connected. You will be able to control the remote Resolve Server GUI from your local client computer using your remote desktop software, and stream the broadcast quality video signal to your DeckLink or UltraStudio for monitoring.
To end a DaVinci Remote Monitoring Session, click the Disconnect button in the lower right hand corner of the application.

DaVinci Remote Monitoring Restrictions

There are currently some limitations to the DaVinci Remote Monitoring application to be aware of.
— When connecting over the internet, bandwidth restrictions can hamper performance. If the bandwidth drops too low, or cuts out completely the server will disconnect with an error message.
— The Resolve Server and Clients require the Windows or Linux versions of Resolve Studio and only support RTX series NVIDIA GPUs.
— MacOS clients are possible, but are currently limited to 8-bit 4:2:0 video codecs.
— Currently DaVinci Remote Monitoring only works with the Cut, Edit, Color and Deliver pages.
— Currently Audio is limited to only 2 channels.
— Currently on the Color page, GUI viewer overlays (for power windows, reference wipes, Open FX controls, etc.) are not working.
>

**Comment by llspalex** [comment]
@zcolor do you work in color grading / post-production and is there some way I can reach you directly?

**Comment by zcolor** [comment]
Well I do that already via an sdi i/o device from Blackmagic. and stream it with OBS through OME to private link.

This way though I could skip OBS and feed OME directly. Which would be interesting to test. Let’s see how this matures when it leaves beta 

Also interesting is the ability to stream h265 444 12bit.  

Zé Maria Abreu Santos
e-mail: ***@***.***
tel: +49 (0) 173 876 00 33
web: zemariacolor.com
