### ISSUE TITLE
Sending WebRTC Input with Gstreamer Signalling Error

### ISSUE THREAD

**Issue by Morpheus235** [AirenSoft/OvenMediaEngine#798]
I am currently trying to setup a Gstreamer Pipeline that sends A/V Streams to Ovenmedia. 
This does seem to work but Ovenmedia logs about the Session expiring and promptly disconnects my Session.  Before the Session expires Playback in the Player does work. 

Could you maybe point me in the right direction which step of the Signalling I am missing or what could be causing this? 

OvenmediaEngine log:
[https://pastebin.com/vMsbMHPF](https://pastebin.com/vMsbMHPF)

answer SDP:
[https://pastebin.com/c9MxvGMP](https://pastebin.com/c9MxvGMP)
Since gstreamer does not seem to add the ice-ufrag to its candidates I manually added those
candidate example:
> {"candidates": [{"candidate": "candidate:1 1 UDP 2015363327 172.25.208.148 40788 typ host ufrag irtMLF6z62g77gEoUflHhjI4hGD3Elqk", "sdpMLineIndex": 0, "sdpMid": "isLdaI"}], "command": "candidate", "id": 1076537548, "peer_id": 0}

Stun Binding:
![image](https://user-images.githubusercontent.com/40322103/174225688-aaa4cafa-3c57-4168-b743-81dc4fbf7b64.png)

Env:
- Ubuntu 20.04
- Release 0.13.2 and latest Master

**Comment by getroot** [comment]
It's probably because gstreamer doesn't send STUN Requests periodically, so ICE port was expired. The best solution is to have gstreamer send a STUN Request, if not, increase the Timeout value in OME.

```
<WebRTC>
  <Timeout>30000</Timeout>
</WebRTC>
```

**Comment by Morpheus235** [comment]
@getroot You are completly right. Luckily libnice does support it.
