### ISSUE TITLE
Cannot access API with default Docker settings

### ISSUE THREAD

**Issue by Fyb3roptik** [AirenSoft/OvenMediaEngine#800]
I have tried to ping the API on a default setup using Docker on Ubuntu 20.04.

```
docker run -d \
-p 1935:1935 -p 4000:4000/udp -p 3333:3333 -p 3334:3334 -p 3478:3478 -p 9000:9000 -p 9999:9999/udp \
airensoft/ovenmediaengine:dev
```

I then tried using Postman to do a `GET http://myomeip:8081/v1/vhosts`

I am getting back `Error: connect ECONNREFUSED`

I have also tried adding ports 8080 and 8081 to the docker run command but still the same thing!

I see there are extra steps to "setup" the API but the docs dont reference HOW to do that within docker. Any insight? Thanks!

**Comment by getroot** [comment]
API Server is disabled by default for security reasons.

You must modify Server.xml by referring to the manual.

https://airensoft.gitbook.io/ovenmediaengine/rest-api

**Comment by Fyb3roptik** [comment]
How do I do that with the docker install. Please see my note above where I ask this question.

**Comment by getroot** [comment]
The default Server.xml is located in /opt/ovenmediaengine/bin/origin_conf in the Docker container.

As the README of https://github.com/AirenSoft/OvenMediaEngine says, you can replace Server.xml with the command below.

```
docker run -d \
-p 1935:1935 \
-p 3333:3333 \
-p 3334:3334 \
-p 3478:3478 \
-p 9000:9000 \
-p 9999:9999/udp \
-p 4000:4000/udp \
-v ome-origin-conf:/opt/ovenmediaengine/bin/origin_conf \
-v ome-edge-conf:/opt/ovenmediaengine/bin/edge_conf \
--name ovenmediaengine \
airensoft/ovenmediaengine:latest

Following the above example, you will find them under /var/lib/docker/volumes/ome-origin-conf/_data and /var/lib/docker/volumes/ome-edge-conf/_data.

If you want to put them in a different location, the easiest way is to create a link:

ln -s /var/lib/docker/volumes/ome-origin-conf/_data/ /my/new/path/to/ome-origin-conf \
&& ln -s /var/lib/docker/volumes/ome-edge-conf/_data/ /my/new/path/to/ome-edge-conf
```

Or you can recreate the Docker Image with your own Server.xml

For more information about Docker, it would be good to refer to the Docker manuals.

**Comment by getroot** [comment]
If you set the volume in the docker container, it will not be affected when you update the docker image.

For OME to actually be used in commercial services, you have to set up a domain and a certificate for TLS. Therefore, with the default settings, it is difficult to use it for anything other than testing purposes. You can test stream input and playback without using an API server.

The API server is turned on by default, meaning that anyone can view, record, or replay your stream. This means serious security issues. So OME forces you to set a secret key when setting up your API server.

Hope this gives you some insight.

**Comment by Fyb3roptik** [comment]
Im hoping this is where an Admin interface can address those concerns. I know it will get there eventually! Excited to see some alternatives to ant media. Just ignore my bitching lol
