### ISSUE TITLE
Performance testing OME Cluster Setup

### ISSUE THREAD

**Issue by cloudcover2021** [AirenSoft/OvenMediaEngine#809]
**PROBLEM**

Performance testing OME Cluster Setup. 

Guide Followed: https://airensoft.gitbook.io/ovenmediaengine/performance-tuning

We tried testing OME in a standalone setup by deploying it on a 60 vCPU and 240 Gi Memory instance. We were successfully able to test it with 2200 parallel using the testing tool

Test Report:

Test ended (lifetime : 600 seconds)
***************************
Reports
***************************
<Summary>
Running time : 10m0s
Number of clients : 2200
ICE Connection State : New(0), Checking(0) Connected(2200) Completed(0) Disconnected(0) Failed(0) Closed(0)
Avg Video Delay(29.35 ms) Max Video Delay(366.00 ms) Min Video Delay(0.00 ms)
Avg Audio Delay(47.50 ms) Max Audio Delay(415.00 ms) Min Audio Delay(0.00 ms)
Avg GOP(30.02) Max GOP(30.07) Min GOP(30)
Avg FPS(29.85) Max FPS(29.89) Min FPS(15.87)
Avg BPS(854.5 kbps) Max BPS(860.9 kbps) Min BPS(452.8 kbps)
Total Bytes(113.3 GBytes) Avg Bytes(51.5 MBytes)
Total Packets(138486711) Avg Packets(62948)
Total Packet Losses(0) Avg Packet Losses(0)

**EXPECTATION**

Now we want to scale the setup as we need to test it with 5000 users. But there are no steps mentioned for :
1. Streaming and Consuming via clustering setup
2. How to load test the cluster setup

Any help or doc around this will help

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

Master

- Encoder information

OBS 10.22

- Operating system and version

 Ubuntu 20.04

**SETUP INFORMATION AND LOGS**

Just changed the Server.xml with <StreamWorkerCount>60</StreamWorkerCount>

**OTHER HELPFUL INFORMATION**

Please write any information that anyone viewing this issue can reference.

**Comment by getroot** [comment]
I tested the performance of OME Cluster as below.
- Install multiple Edges and configure OriginMap to point to a single Origin server.
- It is easiest to group all Edges into one domain and distribute processing with DNS Round Robin.
- Connect to the domain connected to Edges with OvenRtcTester.
- OvenRtcTester itself also has performance limitations, so use multiple OvenRtcTesters.

**Comment by DilipJadhav** [comment]
PROBLEM:

While running the **oven_rtc_tester** from test instance, load is unevenly distributed between multiple edge instances.

ENVIRONMENTAL INFORMATION :

OvenMediaEngine Information:

Origin: 1 VM with 32 vcpu's
Edge: 2 VM with 16 vcpu's

Operating system and version:

Ubuntu 20.04

SETUP INFORMATION AND LOGS :

We have created ome-edge.example.com and added weighted routing in Route53 to send traffic to both of the edge machines.
As you can see in the attached document the load is more on one of the node and another node it is less.

<img width="1440" alt="Screenshot 2022-07-07 at 7 05 23 PM" src="https://user-images.githubusercontent.com/32257022/177793012-6506d777-2552-402e-b02c-f8933ea83f65.png">

Expectation:

Traffic should have been equally distributed between the edge machines.

**Comment by cloudcover2021** [comment]
@getroot We created separate DNS entries for each edge server and completed our load test. 
Just an FYI we were able to load test OME with 5000 clients. Thanks for the support.

**Comment by getroot** [comment]
@cloudcover2021 
Thanks for sharing your results.
A Korean live commerce service is broadcasting over WebRTC to about 12,000 viewers with OvenMediaEngine. They haven't had any problems in the past half year.
