### ISSUE TITLE
Does OME support NACK

### ISSUE THREAD

**Issue by 2k9laojia** [AirenSoft/OvenMediaEngine#81]
Hi，I want to know that could be supported NACK in OME Service. If not, could you have a plan for NACK? thank you.

**Comment by dimiden** [comment]
@2k9laojia 
Currently, OME doesn't support NACK.
We're implementing RTCP, and we'll add features to enable retransmission when RTCP implementation is complete.

**Comment by 2k9laojia** [comment]
OK,thank you.

**Comment by getroot** [comment]
@2k9laojia 
We have completed the development of NACK and RTP retransmission and released it to the master branch. If you are still interested in this issue, you can test it with the master branch.
