### ISSUE TITLE
FFMPEG in OME

### ISSUE THREAD

**Issue by sehadnassim** [AirenSoft/OvenMediaEngine#810]
I want to know where is the FFmpeg called in OME. I would like to log stats of the stream to calculate the delays caused by transcoding at OME

**Comment by sehadnassim** [comment]
Do you have an idea of how can the end to end delay be measured from streaming point to rtmp gateway in OME ?

**Comment by getroot** [comment]
I don't know what RTMP gateway means, but it's safe to say that there is no way to compare latency at the packet level. So we usually measure latency on a glass-to-glass basis.
