### ISSUE TITLE
Stream transcoding to 640x360

### ISSUE THREAD

**Issue by deeefrem** [AirenSoft/OvenMediaEngine#815]
Good afternoon, I'm trying to start streaming by webRTC  in 1080 quality through ome, but at the output from ome I always get 640x360 quality, even if I set the "by pass" mode in the server configuration.
**My webRTC:**
![image](https://user-images.githubusercontent.com/78272124/178465562-b6e82576-5130-411a-b096-3a3b9176f22b.png)
**Output:**
[2022-07-12 12:40:27.978] I [Dech264:2342670] Transcoder | decoder_avc.cpp:212  | [#default#stream01/stream01(100)] input track informa
tion: [video] h264 (Constrained Baseline 3.1), yuv420p, 640x360 [SAR 0:1 DAR 16:9], 0 fps, 195 kbps, timebase: 1/180000, frame_size: 0

I also observe a problem with hardware encoding on the Tesla T4 video card, if I send a stream above 640 from my camera to ome via webRTC, ome cuts it to 640 and sends it to ffmpeg, after which the ffmpeg falls into an error:
[2022-07-09 22:56:44.066] E [Dech264NV:3038737] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7fec2007c240] ctx->cvdl->cuvidDecodePicture(ctx->cudecoder, picparams) failed
[2022-07-09 22:56:44.066] E [Dech264NV:3038737] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7fec2007c240]  -> CUDA_ERROR_INVALID_HANDLE: invalid resource handle
[2022-07-09 22:56:44.066] E [Dech264NV:3038737] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7fec2007c240]
[2022-07-09 22:56:44.066] E [Dech264NV:3038737] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7fec2007c240] cuvid decode callback error
[2022-07-09 22:56:44.066] E [Dech264NV:3038737] Transcoder | decoder_avc_nv.cpp:154  | An error occurred while sending a packet for decoding: Unhandled error (-542398533:Generic error in an external library)

When sending a stream via rtmp, I don’t see such a problem, the ome gives stream the same as specified in the configuration

**Comment by deeefrem** [comment]
In chrome://webrtc-internals i look this info:
![image](https://user-images.githubusercontent.com/78272124/178474262-efeeadf6-ffb0-4d96-968c-03075d492aec.png)

**Comment by getroot** [comment]
To make one thing clear, the Resolution : 1920x1080 information at the top of the screen you captured is the resolution of the media source (cam). It's not the resolution of the outgoing stream. WebRTC automatically adjusts the resolution and bitrate according to the environment. The actual outgoing resolution can also be found at chrome://webrtc-internals.

**Comment by deeefrem** [comment]
In the previous comment in chrome://webrtc-internals it was 720, since this is how the resolution is cut off in our application. So I opened the oven media webRTC test player and I see 1080 here. How can I disable this rule in ome?
![image](https://user-images.githubusercontent.com/78272124/178487648-2c6c1152-fc5c-41b8-93b2-917d1ace9e08.png)

**Comment by deeefrem** [comment]
And why when the quality of the connection is increased, ome does not increase it too?(

**Comment by getroot** [comment]
If you are using OME's transcoding with bypass setting, it will output as input as it is. If you set the encoding, it will be fixed and output.

**Comment by getroot** [comment]
WebRTC Encoder Demo : https://demo.ovenplayer.com/demo_input.html 
WebRTC Player Demo :  https://demo.ovenplayer.com/demo.html

[WebRTC Encoder] ----> [OvenMediaEngine] ----> [WebRTC Player]

WebRTC Encoder constantly changes the quality of the stream according to the network bandwidth.

OME can either output the input stream as it is or encode it again depending on the settings.

WebRTC Player plays the stream provided by OME as it is.

The last webrtc-internals you captured is the WebRTC Encoder.

**Comment by deeefrem** [comment]
But now:
In WebRTC Encoder Demo : https://demo.ovenplayer.com/demo_input.html i see 1080
![image](https://user-images.githubusercontent.com/78272124/178494784-87c7e636-95b9-4dd4-be97-0ddd7878dd58.png)

and in chrome://webrtc-internals i see 1080:
![image](https://user-images.githubusercontent.com/78272124/178494994-d8385c69-17ba-4748-bb5e-8db65f0402e3.png)

In OME now bypass mode active, but in WebRTC Player Demo : https://demo.ovenplayer.com/demo.html
![image](https://user-images.githubusercontent.com/78272124/178496104-6104cb7a-b539-4a76-8088-025fcff844d6.png)

**Comment by getroot** [comment]
> This is because WebRTC constantly changes the video quality of the stream. (Usually start with low quality and increase to high quality) Since OME logs the resolution meta information saved when creating a track for the first time, it may look like an error.

As mentioned in the first comment, when creating a track, OME records and uses the resolution of your input stream as the resolution of that track. This is just meta information, the actual video you are playing will be 1080p.

Continuously updating resolution information dynamically based on input is almost impossible due to ABR and other issues. Taking ABR as an example, this is because viewers' ABR will continue to change depending on the network conditions of the sender.

1. Apply something in WebRTC Encoder to fix the input quality of OME. (Let's find a way.)
2. The output quality is fixed by encoding in OME.

**Comment by deeefrem** [comment]
Thanks)

**Comment by getroot** [comment]
Come to think of it, new viewers might be able to get updated quality information at that moment. Let's see if we have a better idea. Thanks for reporting the problem.
