### ISSUE TITLE
API recording records problem

### ISSUE THREAD

**Issue by cl84** [AirenSoft/OvenMediaEngine#818]
#672

I'm having the problem again on version 0.14.2

Up to version 0.13.1 I'm sure it worked fine

**Comment by Keukhan** [comment]
@cl84 

I tested it and it is confirmed that there is no problem in the current version. 
If the problem is reproduced, can you explain how to reproduce it again?

I look forward to your reply.
Thanks.

**Comment by cl84** [comment]
> @cl84
> 
> I tested it and it is confirmed that there is no problem in the current version. If the problem is reproduced, can you explain how to reproduce it again?
> 
> I look forward to your reply. Thanks.

it works, but if you specify unique id, it still returns all ongoing registrations without filtering

**Comment by Keukhan** [comment]
@cl84 

Thank you for the reply
Can you share the json text that requested a specific id in the recordings?

**Comment by cl84** [comment]
> @cl84
> 
> Thank you for the reply Can you share the json text that requested a specific id in the recordings?

The json request is as follows:

{
    "id": "15161camera1"
}

The answer is this and it is correct

{
    "message": "OK",
    "response": [
        {
            "app": "app",
            "createdTime": "2022-07-27T15:15:24.692+02:00",
            "filePath": "/s15161/record-15161-1658927671-${Sequence}.mp4",
            "id": "15161camera1",
            "infoPath": "/s15161/record-15161-1658927671.xml",
            "interval": 10800000,
            "outputFilePath": "/s15161/record-15161-1658927671-0.mp4",
            "outputInfoPath": "/s15161/record-15161-1658927671.xml",
            "recordBytes": 392311551,
            "recordTime": 206244,
            "segmentationRule": "discontinuity",
            "startTime": "2022-07-27T15:15:26.481+02:00",
            "state": "recording",
            "stream": {
                "name": "camera1",
                "tracks": []
            },
            "totalRecordBytes": 392311551,
            "totalRecordTime": 206244,
            "vhost": "default"
        }
    ],
    "statusCode": 200
}

If I make a request with the following id it returns me the registration anyway

{
    "id": "1bo"
}

{
    "message": "OK",
    "response": [
        {
            "app": "app",
            "createdTime": "2022-07-27T15:15:24.692+02:00",
            "filePath": "/s15161/record-15161-1658927671-${Sequence}.mp4",
            "id": "15161camera1",
            "infoPath": "/s15161/record-15161-1658927671.xml",
            "interval": 10800000,
            "outputFilePath": "/s15161/record-15161-1658927671-0.mp4",
            "outputInfoPath": "/s15161/record-15161-1658927671.xml",
            "recordBytes": 340990391,
            "recordTime": 178599,
            "segmentationRule": "discontinuity",
            "startTime": "2022-07-27T15:15:26.481+02:00",
            "state": "recording",
            "stream": {
                "name": "camera1",
                "tracks": []
            },
            "totalRecordBytes": 340990391,
            "totalRecordTime": 178599,
            "vhost": "default"
        }
    ],
    "statusCode": 200
}

If i start another recording, whatever i put in the json as id it returns me all the recordings as in this example


first request:
{
    "id": "1bo"
}

reply:
{
    "message": "OK",
    "response": [
        {
            "app": "app",
            "createdTime": "2022-07-27T15:15:24.692+02:00",
            "filePath": "/s15161/record-15161-1658927671-${Sequence}.mp4",
            "id": "15161camera1",
            "infoPath": "/s15161/record-15161-1658927671.xml",
            "interval": 10800000,
            "outputFilePath": "/s15161/record-15161-1658927671-0.mp4",
            "outputInfoPath": "/s15161/record-15161-1658927671.xml",
            "recordBytes": 746485842,
            "recordTime": 394155,
            "segmentationRule": "discontinuity",
            "startTime": "2022-07-27T15:15:26.481+02:00",
            "state": "recording",
            "stream": {
                "name": "camera1",
                "tracks": []
            },
            "totalRecordBytes": 746485842,
            "totalRecordTime": 394155,
            "vhost": "default"
        },
        {
            "app": "app",
            "createdTime": "2022-07-27T15:21:47.578+02:00",
            "filePath": "/record-1658928107-${Sequence}.mp4",
            "id": "camera1",
            "infoPath": "/record-1658928107.xml",
            "interval": 10800000,
            "outputFilePath": "/record-1658928107-0.mp4",
            "outputInfoPath": "/record-1658928107.xml",
            "recordBytes": 22601563,
            "recordTime": 12140,
            "segmentationRule": "discontinuity",
            "startTime": "2022-07-27T15:21:48.496+02:00",
            "state": "recording",
            "stream": {
                "name": "camera1",
                "tracks": []
            },
            "totalRecordBytes": 22601563,
            "totalRecordTime": 12140,
            "vhost": "default"
        }
    ],
    "statusCode": 200
}

second request:
{
    "id": "15161camera1"
}

reply:
{
    "message": "OK",
    "response": [
        {
            "app": "app",
            "createdTime": "2022-07-27T15:15:24.692+02:00",
            "filePath": "/s15161/record-15161-1658927671-${Sequence}.mp4",
            "id": "15161camera1",
            "infoPath": "/s15161/record-15161-1658927671.xml",
            "interval": 10800000,
            "outputFilePath": "/s15161/record-15161-1658927671-0.mp4",
            "outputInfoPath": "/s15161/record-15161-1658927671.xml",
            "recordBytes": 746485842,
            "recordTime": 394155,
            "segmentationRule": "discontinuity",
            "startTime": "2022-07-27T15:15:26.481+02:00",
            "state": "recording",
            "stream": {
                "name": "camera1",
                "tracks": []
            },
            "totalRecordBytes": 746485842,
            "totalRecordTime": 394155,
            "vhost": "default"
        },
        {
            "app": "app",
            "createdTime": "2022-07-27T15:21:47.578+02:00",
            "filePath": "/record-1658928107-${Sequence}.mp4",
            "id": "camera1",
            "infoPath": "/record-1658928107.xml",
            "interval": 10800000,
            "outputFilePath": "/record-1658928107-0.mp4",
            "outputInfoPath": "/record-1658928107.xml",
            "recordBytes": 22601563,
            "recordTime": 12140,
            "segmentationRule": "discontinuity",
            "startTime": "2022-07-27T15:21:48.496+02:00",
            "state": "recording",
            "stream": {
                "name": "camera1",
                "tracks": []
            },
            "totalRecordBytes": 22601563,
            "totalRecordTime": 12140,
            "vhost": "default"
        }
    ],
    "statusCode": 200
}

**Comment by Keukhan** [comment]
@cl84 

Both the latest version and 0.14.2 version cannot be reproduced. 
Are you using the GET method? When the GET method is called, all recording is returned without filtering. Check if you are using the POST method.

Thanks.

**Comment by cl84** [comment]
> @cl84
> 
> Non è possibile riprodurre sia l'ultima versione che la versione 0.14.2. Stai usando il metodo GET? Quando viene chiamato il metodo GET, tutte le registrazioni vengono restituite senza filtri. Controlla se stai usando il metodo POST.
> 
> Grazie.

You're right, I don't know why but I did the request in GET.
In POST everything works fine

**Comment by Keukhan** [comment]
👍
