### ISSUE TITLE
Videos are not playing

### ISSUE THREAD

**Issue by cjagadis** [AirenSoft/OvenMediaEngine#82]
Used this branch for the test:
https://github.com/AirenSoft/OvenMediaEngine/tree/dev

I fixed a few logging issues in this file:
/src/projects/main/third_parties.cpp

Then it compiled, but I get this error message from the player:
Can not play due to unknown reasons.

For the test I used the player on this URL:
https://ovenplayer.com/docs/demo.html

----------------------------server.xml---------------------------------
<?xml version="1.0" encoding="UTF-8" ?>

<Server version="5">
        <Name>OvenMediaEngine</Name>
        
        <Type>origin</Type>
        
        <IP>*</IP>

        
        <Bind>
                <Providers>
                        <RTMP>
                                <Port>1935</Port>
                        </RTMP>
                </Providers>

                <Publishers>
                        <OVT>
                                <Port>9000</Port>
                        </OVT>
                        <HLS>
                                <Port>80</Port>
                                
                                
                        </HLS>
                        <DASH>
                                <Port>80</Port>
                                
                                
                        </DASH>
                        <WebRTC>
                                <Signalling>
                                        <Port>3333</Port>
                                        
                                        
                                </Signalling>
                                <IceCandidates>
                                        <IceCandidate>*:10000-10005/udp</IceCandidate>
                                </IceCandidates>
                        </WebRTC>
                </Publishers>
        </Bind>

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>

                        
                        <Domain>
                                <Names>
                                        
                                        <Name>*</Name>
                                </Names>
                                
                        </Domain>
                        
                        
                        <Applications>
                                <Application>
                                        <Name>app</Name>
                                        
                                        <Type>live</Type>
                                        <Encodes>
                                                <Encode>
                                                        <Name>video_bypass_audio_opus</Name>
                                                        <Video>
                                                                <Bypass>true</Bypass>
                                                        </Video>
                                                        <Audio>
                                                                <Codec>opus</Codec>
                                                                <Bitrate>64000</Bitrate>
                                                                <Samplerate>48000</Samplerate>
                                                                <Channel>2</Channel>
                                                                
                                                        </Audio>
                                                </Encode>
                                                <Encode>
                                                        <Name>VP8</Name>
                                                        <Audio>
                                                                <Codec>opus</Codec>
                                                                <Bitrate>128000</Bitrate>
                                                                <Samplerate>48000</Samplerate>
                                                                <Channel>2</Channel>
                                                        </Audio>
                                                        <Video>
                                                                <Codec>vp8</Codec>
                                                                <Width>640</Width>
                                                                <Height>360</Height>
                                                                <Bitrate>500000</Bitrate>
                                                                <Framerate>30</Framerate>
                                                        </Video>
                                                </Encode>
                                                <Encode>
                                                        <Name>H264</Name>
                                                        <Audio>
                                                                <Codec>aac</Codec>
                                                                <Bitrate>128000</Bitrate>
                                                                <Samplerate>48000</Samplerate>
                                                                <Channel>2</Channel>
                                                        </Audio>
                                                        <Video>
                                                                <Codec>h264</Codec>
                                                                <Width>640</Width>
                                                                <Height>360</Height>
                                                                <Bitrate>500000</Bitrate>
                                                                <Framerate>30</Framerate>
                                                        </Video>
                                                </Encode>
                                                <Encode>
                                                        <Name>BYPASS</Name>
                                                        <!-- If you want to use bypass. For browser compatibility, the h264.bframe option must be fixed to 0.
                                                        <Video>
                                                                <Bypass>true</Bypass>
                                                        </Video>
                                                        <Audio>
                                                                <Bypass>true</Bypass>
                                                        </Audio>
                                                </Encode>
                                        </Encodes>
                                        <Streams>
                                                <Stream>
                                                        <Name>${OriginStreamName}_o</Name>
                                                        <Profiles>
                                                                <Profile>VP8</Profile>
                                                                <Profile>H264</Profile>
                                                        </Profiles>
                                                </Stream>
                                        </Streams>
                                        <Providers>
                                                <RTMP />
                                        </Providers>
                                        <Publishers>
                                                <ThreadCount>4</ThreadCount>
                                                <HLS>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomain>
                                                                <Url>*</Url>
                                                        </CrossDomain>
                                                </HLS>
                                                <DASH>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <SegmentCount>3</SegmentCount>
                                                        <CrossDomain>
                                                                <Url>*</Url>
                                                        </CrossDomain>
                                                </DASH>
                                                <LLDASH>
                                                        <SegmentDuration>5</SegmentDuration>
                                                        <CrossDomain>
                                                                <Url>*</Url>
                                                        </CrossDomain>
                                                </LLDASH>
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>

**Comment by getroot** [comment]
I need the server log (ovenmediaengine.log) to check the problem.  And are you using the latest dev?  There are many updates these days.

**Comment by cjagadis** [comment]
I will check and let you know.

Best Regards,
Jagadish

Channagiri Jagadish
Moogilu <http://www.moogilu.com>
jagadish@moogilu.com
+1 408 884 0325 (O)
+1 650 245 1884 (C)

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
