### ISSUE TITLE
record problem

### ISSUE THREAD

**Issue by cl84** [AirenSoft/OvenMediaEngine#822]
When a recording fails, the written file is not renamed from tmp _ ****** to the assigned file name and is not even inserted into the xml file.

Would it be possible to put the file in the xml and rename the file anyway when the failed registration process is stopped?

In any case, the problem already presented in post #743 should be solved.

Thank you

**Comment by Keukhan** [comment]
@cl84 

I will think more about adding the file information that failed to record to XML.
You won't have to worry about recording failure right away by solving the problem of #743.
I'll try to plan a better way.

Thanks.
