### ISSUE TITLE
TLS Encryption document is maybe outdated.

### ISSUE THREAD

**Issue by yanorei32** [AirenSoft/OvenMediaEngine#823]
**Is your feature request related to a problem? Please describe.**

"Configuration/TLS Encryption" document is maybe outdated now (v0.14.3).

document says:
https://github.com/AirenSoft/OvenMediaEngine/blob/ff6dbec30909ad4098e46a8ec0aefedde2e1dd38/docs/configuration/tls-encryption.md?plain=1#L31-L40

but example says:
https://github.com/AirenSoft/OvenMediaEngine/blob/ff6dbec30909ad4098e46a8ec0aefedde2e1dd38/misc/conf_examples/Server.xml#L174-L191

**Describe the solution you'd like**
* Update this document

**Describe alternatives you've considered**
* Display the outdated flag in this document

**Additional context**
The &lt;Host&gt; structure is here. I think the example is right.
https://github.com/AirenSoft/OvenMediaEngine/blob/v0.14.3/src/projects/config/items/common/host/host.h

**Comment by getroot** [comment]
As you said, the <Domain> of the document has been replaced with <Host> a long time ago. /misc/conf_examples is a carefully maintained file, so it is always up to date. But there was something we missed in the documentation. Thanks for the information. 

Could you PR a docs update?
