### ISSUE TITLE
RTMP Push 

### ISSUE THREAD

**Issue by NkInKaIgIe** [AirenSoft/OvenMediaEngine#824]
I use startPush API to push RTMPPush stream to facebook .
 It gives  status= error ,
![image](https://user-images.githubusercontent.com/96049216/179442518-677695cb-906e-4e44-8162-d16f8625c22a.png)
log says
[2022-07-18 09:36:02.176] E [AW-RTMPPush0:2601] FFmpeg | third_parties.cpp:111 | [AVFormatContext: 0x7fdcb4019a80] No streams to mux were specified
[2022-07-18 09:36:02.176] E [AW-RTMPPush0:2601] RTMPWriter | rtmp_writer.cpp:150 | Could not create header

I have RTMPPush enabled as in the documentation

**Comment by Keukhan** [comment]
@NkInKaIgIe 

There may be no tracks selected. Please clear the tracks parameter when requesting recording and try again.

Thanks.

**Comment by NkInKaIgIe** [comment]
@Keukhan I deleted the tracks and tried again but still state=error
![image](https://user-images.githubusercontent.com/96049216/179445747-c5325bae-86f5-427c-81d7-9c000b14977a.png)
I don't know where am I wrong?

**Comment by Keukhan** [comment]
@Keukhan 

Please share the log file, server configuration file, and API request body to analyze the cause.

Thanks

**Comment by NkInKaIgIe** [comment]
@Keukhan 
this is my file
[Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9130012/Server.txt)
[log .txt](https://github.com/AirenSoft/OvenMediaEngine/files/9130018/log.txt)
API request body:
`{
"id": "123",
"stream": {
         "name": "trang"
},
"protocol": "rtmp",
"url":"rtmp://a.rtmp.youtube.com/live2",
"streamKey":"rwyq-ggbw-sqxw-697c-916y"
}`

**Comment by Keukhan** [comment]
@NkInKaIgIe 

It is not known exactly by looking at some logs, but it seems to be a problem caused by the termination of the **trang** stream.
Check that the **trang** stream is being input without problems.

Please share the full information so I can analyze it.

**Comment by getroot** [comment]
@NkInKaIgIe 
Providing the full /var/log/ovenmediaengine.log file will help others analyze the problem. If you truncate the log, the person analyzing the problem won't be able to find the information they're looking for.

**Comment by NkInKaIgIe** [comment]
@getroot
RTMPpush API full process log
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9136854/ovenmediaengine.log)

**Comment by NkInKaIgIe** [comment]
@Keukhan  Trang stream is operating normally. About the API, after posting startPush, the log shows "Could not create header" . Stream Trang works normally but API says state : error

**Comment by Keukhan** [comment]
@NkInKaIgIe 

RTMP has a restrict that one video and one audio must be used. The fundamental problem is that the trang stream has 4 video tracks and 3 audio tracks.  so,  when using RTMP push, 1-video track and 1-audio track each must be selected.

There are two ways to solve this problem.

1) Select 1 video and 1 audio when requesting recording API like **"stream": { "name": "trang", "tracks" : [ 0, 4 ] }** 

2) Separate the OutputProfile for RTMP Push. In this OutputProfile has only 1 video(h264) and 1 audio(aac) encoding are set. Fortunately, profiles with the same encoding options do not have duplicate encoding.

Try the above two methods. I am looking forward to good results.

Thanks

**Comment by NkInKaIgIe** [comment]
@Keukhan  Thanks you very much, I used tracks video( h246) and audio(aac) codecs it worked successfully on fb and ytb . 
I have 1 problem about p2p can you help me?
[https://github.com/AirenSoft/OvenMediaEngine/issues/827](url)

**Comment by mpisat** [comment]
How do you get the list of tracks from a stream with OME?
