### ISSUE TITLE
Need to confirm does OME supports specific features

### ISSUE THREAD

**Issue by sagarpatil23192** [AirenSoft/OvenMediaEngine#825]
Before asking for help, please read the troubleshooting section in the manual carefully.
https://airensoft.gitbook.io/ovenmediaengine/troubleshooting

Please fill out the form below to create an issue. Failure to follow the form may result in late responses or close issues.

**PROBLEM**

Need to confirm does OME supported specific features. PFB the list of features:
1. WebRTC conference call. Here a single stream can be used by multi-user to publish.
2. K8s support
3. Scaling manager to autoscale.
4. Downscaling the edge servers 
Thanks in advance.

**Comment by dva-re** [comment]
> 1. WebRTC conference call. Here a single stream can be used by multi-user to publish.

About conference try to look at this solution https://github.com/AirenSoft/OvenSpace
