### ISSUE TITLE
WebRTC no audio only output

### ISSUE THREAD

**Issue by prisikarm** [AirenSoft/OvenMediaEngine#826]
**Describe the bug**

0.14.3, Ubuntu 18, 8GB ram, AWS.

I am trying webRTC as input and webRTC as output, via demo player.
When webRTC input is video+audio, everything is ok.
But when I select "Without video" in Input streams settings at ovenplayer, I cannot receive anything, please check the screenshot

![image](https://user-images.githubusercontent.com/42371761/179596016-2f99adb5-d781-4be7-86e2-9744650c2819.png)

My webrtc input url looks like:
```wss://streams.translers.link:3334/app/teststream1?direction=send&transport=tcp```

I already saw issues #625 and #572 but that did not helped

Here are my Server.xml and logs
[ovenmediaengine.log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9134690/ovenmediaengine.log.txt)
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9134691/Server.xml.txt)

Thanks

**Comment by getroot** [comment]
Thanks for reporting the problem.
I'll try to reproduce this issue soon and fix it.

**Comment by getroot** [comment]
I solved this problem.
https://github.com/AirenSoft/OvenMediaEngine/commit/1d3b5a9685b290e6e9179d1024677175ac075115

You can test it with the latest master branch.
Thank you!

**Comment by prisikarm** [comment]
@getroot I can confirm that the latest master branch resolved the issue.
Thank you very much ^_^
