### ISSUE TITLE
 P2p features and security the stream created

### ISSUE THREAD

**Issue by NkInKaIgIe** [AirenSoft/OvenMediaEngine#827]
The p2p feature is not supported on mobile devices. Currently I need  p2p to reduce network traffic, and use the livestream feature on my phone.

Ovenmediaengine's P2p is currently using which ice + turn + stun? p2p feature i get error when p2p from external network. while in local p2p works

Is there a way to secure the generated stream?

**Comment by getroot** [comment]
The p2p traffic distribution feature is still an experimental feature, and we haven't maintained it for a long time as no one has used it. So this feature is for developers who can improve this feature on their own for now.

**Comment by getroot** [comment]
Please refer to the manual for the function to protect the stream.

https://airensoft.gitbook.io/ovenmediaengine/access-control
