### ISSUE TITLE
Opus is using too much CPU while encoding

### ISSUE THREAD

**Issue by prisikarm** [AirenSoft/OvenMediaEngine#828]
**PROBLEM**

I am streaming audio only WebRTC -> WebRTC. 

Opus is using too much CPU while encoding. When I am trying to go 128kb -> 32kb and stereo -> mono, the OME utilizes >100% of the CPU. It is the same if 1 one listener on output or 20 listeners

top:

![image](https://user-images.githubusercontent.com/42371761/180406137-e8166863-2d36-40c1-88da-becba69c9e4c.png)

top -H -p:

![image](https://user-images.githubusercontent.com/42371761/180414715-1c5875e5-9c49-4bd2-b528-48494771a969.png)

Even when I only convert stereo -> mono, and the bitrate stays the same, UME utilizes the CPU at 100%. 

When the sound is bypassing, OME utilizes 6% of the CPU.

Here is a warning from my logs:
`[2022-07-22 08:52:20.231] W [Resampler:113804] ov.Queue | queue.h:268  | [0x7f0db8015b08] Input queue of Encoder. codec(opus/86076) size has exceeded the threshold: queue: 9272, threshold: 120, peak: 9272`

**ENVIRONMENTAL INFORMATION**
Ubuntu 20.04, 0.14.3, t3.large AWS instance (2 vCPU, 8gb RAM)
I am planning to stream audio only (a few streams, many listeners), this rig should be enough, isn't it?
![image](https://user-images.githubusercontent.com/42371761/180407715-4d2292f2-7da9-4e41-8de8-f275ebd739fe.png)

 
Here my logs and config:
[ovenmediaengine.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9166346/ovenmediaengine.txt)
[Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9166347/Server.txt)

According to [https://wiki.xiph.org/OpusFAQ](https://wiki.xiph.org/OpusFAQ), there is OPUS_SET_COMPLEXITY(), where you trade quality for complexity. Is it possible to use this feature in OME?

**Comment by prisikarm** [comment]
OME utilizes ver. 1.1.3 of Opus, which is very old. Could that be a problem that we are trying to resolve? Why not try the latest release?

p.s.
According to https://github.com/xiph/opus/issues/235, even the latest release is 3 years old. Maybe it is a better idea to try the direct `git clone` version of Opus? Looks like they fixed a lot of bugs during these three years...

**Comment by prisikarm** [comment]
_update:_

I tried with the Opus master branch + OME master. 

Tried different combinations (video and audio WebRTC -> OME (convert stereo to mono) -> WebRTC OvenPlayer; audio WebRTC -> OME (convert stereo to mono) -> WebRTC OvenPlayer). 

The CPU load is still the same (~ 100%)

**Comment by getroot** [comment]
I also reproduced this problem.
In my environment, I found an unusual CPU load to convert stereo to mono. Only when I changed the bitrate to 32k I couldn't find any problem. There seems to be a problem with changing Stereo to Mono. We will address this issue soon.
Thanks for finding and reporting issues.

**Comment by getroot** [comment]
This problem is solved. Please check if your problem is also solved.

**Comment by prisikarm** [comment]
Version [0.14.6](https://github.com/AirenSoft/OvenMediaEngine/releases/tag/v0.14.6) fixed the issue. Thank you
