### ISSUE TITLE
Is OME suitable for developing voicecall and videocall systems?

### ISSUE THREAD

**Issue by buithevuong** [AirenSoft/OvenMediaEngine#829]
I am not sure if OME is suitable for developing voicecall and videocall systems using WebRTC ? Please give me advice on this , I am new to it , thanks .

**Comment by getroot** [comment]
You can achieve your goals with OvenMediaEngine.

https://github.com/AirenSoft/OvenSpace
https://space.ovenplayer.com/

However, OvenMediaEngine is more specialized for large-scale, high-definition, low-latency broadcasts. I think Janus or Jitsi is more suitable for small real-time online meeting services.

**Comment by buithevuong** [comment]
> 

Thank you so much for your advice
