### ISSUE TITLE
Changing stream key

### ISSUE THREAD

**Issue by youssefqarri** [AirenSoft/OvenMediaEngine#83]
Hello,

I am not able to find a way to change de stream key. The default and only value I can find is "stream".

Can you please let me know if it is possible to change it in the config file ?

Thank you

**Comment by dimiden** [comment]
@youssefqarri 
The stream key is not fixed, so there is no need to change the settings. Just change the stream key of a tool like OBS differently.

**Comment by youssefqarri** [comment]
> @youssefqarri
> The stream key is not fixed, so there is no need to change the settings. Just change the stream key of a tool like OBS differently.

Thank you for your reply,

How can I garantee that nobody will use my servers to stream. I was thinking of using the stream key as a password to protect my streaming server.

Do you have any other alternative ?

Thank you

**Comment by getroot** [comment]
You can directly modify the source code and query the stream key to the http-based api server to accept the connection if you receive 200 or reject it if you receive 404.  Alternatively, the easiest way is to use a firewall.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
