### ISSUE TITLE
"Corrupted double-linked list"

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#831]
**Describe the bug**
While running, the OME server hard crashes with the error in the log "corrupted double-linked list"

**To Reproduce**
Unsure how to reproduce. Here is the Dockerfile and Server.xml

[Config.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9204500/Config.txt)

**Expected behavior**
No crash :)

**Logs**
[OMEfail.log](https://github.com/AirenSoft/OvenMediaEngine/files/9204487/OMEfail.log)
[crash_20220725.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9204492/crash_20220725.dump.txt)
[crash_20220728.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9204493/crash_20220728.dump.txt)
[crash_20220727.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9204494/crash_20220727.dump.txt)
[crash_20220726.dump.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9204495/crash_20220726.dump.txt)

Four crash logs - 28 is the newest, of course, and the one that corresponds to the log file

**Additional context**
I believe we've had this before, but it seemed better for a while. Then we upgraded to the newest version and enabled llhls, and we get crashes again. 

At least we get dump files this time!

**Comment by dimiden** [comment]
@naanlizard 
We have one more difficult homework to solve!
I think it would be very helpful to solve the problem if you attach the information below.

1. What OS are you using?
2. I checked the crash dump and it seems that you built it yourself and are using it. If it's right that you built it yourself, could you provide the binary **before** ```make install```? If we can obtain the ```OvenMediaEngine``` binary with debug symbols, we can check it quickly. This file is located in ```<OME_PATH>/src/bin/RELEASE```

**Comment by dimiden** [comment]
@naanlizard
Oh, I'm sorry. I missed the information that you used Docker. I thought it would not use Docker because the pid is 7.
Then, I will reply after reviewing the contents!

**Comment by getroot** [comment]
@naanlizard 
The crash dump you provided was very helpful. I found and fixed some code in OME that could cause SIGSEGV due to memory corruption. Hope this solved the problem. (I haven't been able to reproduce it, so I don't know yet if your problem is definitely resolved.)

https://github.com/AirenSoft/OvenMediaEngine/commit/ae2cc838eeb6de3050545ddbeadd306a9488ec27

**Comment by naanlizard** [comment]
Is it possible to push a new version? Testing with master is difficult for us, relatively

**Comment by getroot** [comment]
@naanlizard OK, I will release 0.14.5 soon.

**Comment by getroot** [comment]
You reported a similar issue in #847. Do you think this issue and #847 are different issues? And do you think this issue has been resolved?

**Comment by naanlizard** [comment]
I am not sure! Hence the new ticket, I thought it would be easier.

There is no "corrupted double linked list" warning anywhere I could find, so perhaps one crash has been solved, but there are others?

**Comment by getroot** [comment]
I think the crash that occurs in this issue has been resolved. #847 seems to be a different kind of crash. (Because the crash cycle is different and the log is different)

**Comment by naanlizard** [comment]
I think that is likely. I will close this for now, and reopen if I get more double linked list crashes
