### ISSUE TITLE
 Elimination of interlacing

### ISSUE THREAD

**Issue by by-serj** [AirenSoft/OvenMediaEngine#832]
Good day!

Will deinterlacing functionality be implemented?

In FFmpeg, the **-vf** switch is responsible for this with the options: **w3fdif** or **bwdif** or **kerndeint** or **yadif**

**Comment by mpisat** [comment]
Why would one need deinterlacing on the media server? If you are pusing interlaced content via ffmpeg to OME, just do it while pushing it? OBS doesn't send interlaced video to media servers, and it can deinterlace with filters if your video input is interlaced. Fixing this problem at the source is the right way to go.

**Comment by by-serj** [comment]
Because I use alternative streaming sources, not just OBS. My scheme Broadcast server -> MPEG TS -> SRT -> OME -> LLHSL & PushRTMP
