### ISSUE TITLE
RAM memory goes up to 100%

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#833]
My OME server's RAM starts to gradually increase to 100% saturation, then the OME service restarts and RAM is freed, but the cycle continues. I use ubuntu 18.05, OME 12.9 , mpeg2 TS input and HLS playback

**Comment by getroot** [comment]
Older versions may have memory leaks.
Please let me know if the issue is reproduced using the latest version 0.14.5.
