### ISSUE TITLE
How to stream desktop from browser to OME

### ISSUE THREAD

**Issue by msalai** [AirenSoft/OvenMediaEngine#834]
Is there a way to stream my desktop from the browser to the OME server? Is there any quick way to test this without installing and configuring OME?

**Comment by mpisat** [comment]
https://demo.ovenplayer.com/demo_input.html
You still need to install OME and configure it though. In the past OME team had a demo server at AWS but I guess it's not available anymore.

**Comment by getroot** [comment]
@msalai 
Our demo site is still available! Thank you :-)

https://demo.ovenplayer.com/ome_demo.html
https://space.ovenplayer.com/

**Comment by msalai** [comment]
Thanks for the links, but I only see a way to share a screen from OBS (or similar). How to share a screen from a web browser with other participants in the meeting? Same way as Zoom does it. I am sure it is possible since it is part of the webrtc.

**Comment by getroot** [comment]
It is possible if you improve OvenLiveKit or you develop it. It's on our roadmap, but it's a low priority.
