### ISSUE TITLE
LLHLS from edge server cannot be played if I didn't init with WEBRTC

### ISSUE THREAD

**Issue by sebdott** [AirenSoft/OvenMediaEngine#835]
When I first started my edge server, I encountered this error.

![image](https://user-images.githubusercontent.com/26357318/182143358-a6df57dd-d9f6-4621-be7d-0d9e269c23f3.png)

I had to use the WEBRTC link ws:/XXX/app/stream after which the LLHLS link worked flawlessly.

I'm not sure if this is a configuration issue or a bug.
Could anyone assist me with this issue?

I'm using the basic docker images with minor change in the configuration

**Comment by getroot** [comment]
Add an application named "app" to your configuration. 

If you want to analyze the problem more precisely, please fill out the form and provide as much information as possible.

**Comment by sebdott** [comment]
Thanks for the reply here is the form

**PROBLEM**

When I first started my edge server, I encountered this error.

![image](https://user-images.githubusercontent.com/26357318/182143358-a6df57dd-d9f6-4621-be7d-0d9e269c23f3.png)

I had to use the WEBRTC link ws:/XXX/app/stream after which the LLHLS link worked flawlessly.

**EXPECTATION**

It should work flawlessly at first try

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

I'm using the basic docker images with minor change in the configuration
airensoft/ovenmediaengine:latest

- Encoder information

Not relevant as the problems comes from the viewer side.

- Player information

Not relevant

- URL

Not relevant

- Operating system and version

Ubuntu 20.04 LTS

**SETUP INFORMATION AND LOGS**

[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9233914/Server.xml.txt)

[log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9233913/log.txt)

**Comment by getroot** [comment]
Uncommenting the app application in your Server.xml seems to solve the problem.

```
 <!--
                    <Applications>
                        <Application>
                            <Name>app</Name>
                            <Type>live</Type>
                              ...
-->
```

**Comment by sebdott** [comment]
Thanks got it working.
