### ISSUE TITLE
LLHLS can't pull stream OVT

### ISSUE THREAD

**Issue by Trungdo253** [AirenSoft/OvenMediaEngine#839]
i use cluster origin-edge-ome. 
i play wss://... then ok but play LLHLS then can't pull stream from origin and when i debug edge "Could not found application: #tmt#liveapp" 
origin not received any debug from edge when play llhls

![Screenshot 2022-08-04 155734](https://user-images.githubusercontent.com/93107241/182807127-e0c26391-7744-404d-b48f-b03718ace6c9.png)

[origin.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9258318/origin.txt)
[edge.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9258320/edge.txt)

**Comment by getroot** [comment]
Check out the issues below.

https://github.com/AirenSoft/OvenMediaEngine/issues/835
https://github.com/AirenSoft/OvenMediaEngine/issues/837

**Comment by Trungdo253** [comment]
thank you for supported !
