### ISSUE TITLE
Creating multiple applications

### ISSUE THREAD

**Issue by youssefqarri** [AirenSoft/OvenMediaEngine#84]
Hello,

Creating multiple applications is not working. The following configuration is not working :

`
<?xml version="1.0" encoding="UTF-8"?>

<Server version="2">
	<Name>OvenMediaEngine</Name>
	<Hosts>
		<Host>
			<Name>default</Name>
			<IP>*</IP>
			
			<Ports>
				<Origin>9000</Origin>
				<RTMPProvider>1935</RTMPProvider>
				<HLS>80</HLS>
				<DASH>80</DASH>
				<WebRTC>
					<IceCandidates>
						<IceCandidate>*:10000-10005/udp</IceCandidate>
					</IceCandidates>
					<Signalling>3333</Signalling>
				</WebRTC>
			</Ports>

			<Applications>
				<Application>
					<Name>app1</Name>
					<Type>live</Type>
					<Encodes>
						<Encode>
							<Name>VP88</Name>
							<Audio>
								<Codec>opus</Codec>
								<Bitrate>128000</Bitrate>
								<Samplerate>48000</Samplerate>
								<Channel>2</Channel>
							</Audio>
							<Video>
								<Codec>vp8</Codec>
								<Width>960</Width>
								<Height>540</Height>
								<Bitrate>300000</Bitrate>
								<Framerate>20.0</Framerate>
							</Video>
						</Encode>
						<Encode>
							<Name>H2644</Name>
							<Audio>
								<Codec>aac</Codec>
								<Bitrate>128000</Bitrate>
								<Samplerate>48000</Samplerate>
								<Channel>2</Channel>
							</Audio>
							<Video>
								<Codec>h264</Codec>
								<Width>960</Width>
								<Height>540</Height>
								<Bitrate>300000</Bitrate>
								<Framerate>20.0</Framerate>
							</Video>
						</Encode>
					</Encodes>
					<Streams>
						<Stream>
							<Name>radio1_o</Name>
							<Profiles>
								<Profile>VP88</Profile>
								<Profile>H2644</Profile>
							</Profiles>
						</Stream>
					</Streams>
					<Providers>
						<RTMP />
					</Providers>
					<Publishers>
						<ThreadCount>4</ThreadCount>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</DASH>
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Publishers>
				</Application>

				<Application>
					<Name>app2</Name>
					<Type>live</Type>
					<Encodes>
						<Encode>
							<Name>H264HD</Name>
							<Audio>
								<Codec>aac</Codec>
								<Bitrate>128000</Bitrate>
								<Samplerate>48000</Samplerate>
								<Channel>2</Channel>
							</Audio>
							<Video>
								<Codec>h264</Codec>
								<Width>960</Width>
								<Height>540</Height>
								<Bitrate>300000</Bitrate>
								<Framerate>20.0</Framerate>
							</Video>
						</Encode>
					</Encodes>
					<Streams>
						<Stream>
							<Name>radio2_o</Name>
							<Profiles>
								<Profile>H264HD</Profile>
							</Profiles>
						</Stream>
					</Streams>
					<Providers>
						<RTMP />
					</Providers>
					<Publishers>
						<ThreadCount>4</ThreadCount>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</DASH>
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Publishers>
				</Application>
			</Applications>
		</Host>
	</Hosts>
</Server>
`

Thank you for your help

**Comment by dimiden** [comment]
@youssefqarri 
Could you tell me the source version you are using? The multi-application function has been added recently, so it may not work with old version sources.

**Comment by getroot** [comment]
I recommend you use the dev branch.

**Comment by youssefqarri** [comment]
> I recommend you use the dev branch.

Is this branch stable enough to run it in production ?

**Comment by getroot** [comment]
I can't guarantee that OvenMediaEngine is in production. We will release to 1.0 if we believe that it is in production after sufficient testing, and we cannot guarantee until that time.

If you want to use the latest features such as multiple applications, we recommend using the dev branch. There are also more patches applied here.

**Comment by youssefqarri** [comment]
> I can't guarantee that OvenMediaEngine is in production. We will release to 1.0 if we believe that it is in production after sufficient testing, and we cannot guarantee until that time.
> 
> If you want to use the latest features such as multiple applications, we recommend using the dev branch. There are also more patches applied here.

Thank you for your reply
