### ISSUE TITLE
ABR on Edge 

### ISSUE THREAD

**Issue by NkInKaIgIe** [AirenSoft/OvenMediaEngine#840]
feature ABR on Edge inactive when pull stream with OVT
Control bitrate output player when play llhls

**Comment by getroot** [comment]
Edge provides ABR by importing Origin's playlists. If this doesn't work, please tell me the server.xml and log files of Origin and Edge, and the URL you used to play the stream so I can reproduce the problem.

**Comment by NkInKaIgIe** [comment]
@getroot  I don't know where I am wrong. this is edge config file and origin and log file
[origin.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266147/origin.txt)
[edge.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266151/edge.txt)
[log-edge.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266153/log-edge.txt)

**Comment by NkInKaIgIe** [comment]
@getroot  I don't know where I am wrong. this is edge config file and origin and log file
[edge.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266174/edge.txt)
[origin.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266175/origin.txt)
[log-edge.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266176/log-edge.txt)

**Comment by getroot** [comment]
Did you try to play by specifying a playlist like `wss://edge-domain.com:port/liveapp/trang/abr`?

**Comment by NkInKaIgIe** [comment]
@getroot  i play wss://edge-domain.com:port/liveapp/trang/abr 
![image](https://user-images.githubusercontent.com/96049216/183024807-df718452-f946-4d52-a3d9-9c6b0f4b3e3d.png)

**Comment by getroot** [comment]
In the log you uploaded, you did not request with /abr, but with /llhls.

```
[2022-08-05 13:44:20.657] E [SPRtcSig-T3334:24120] WebRTC Publisher | webrtc_publisher.cpp:468 | Cannot find file (#tmt#liveapp/trung/llhls)
```

Could you please re-upload the whole log?

**Comment by NkInKaIgIe** [comment]
@getroot  sorry the above log file may be confused, this is the correct log file
[log (1).txt](https://github.com/AirenSoft/OvenMediaEngine/files/9266477/log.1.txt)

**Comment by getroot** [comment]
Would you like to remove Bypass Rendition from your playlist?
Your bypass audio codec is AAC. AAC is not supported by WebRTC, and the other rendition has OPUS audio codec. Codecs cannot be mixed.

```
<Playlist>
								<FileName>abr</FileName>
								<Options>
									<WebRtcAutoAbr>true</WebRtcAutoAbr> 
								</Options>
								<Rendition>
									<Name>Bypass</Name>
									<Video>Video_bypass</Video>
									<Audio>Audio_bypass</Audio>
								</Rendition>
								<Rendition>
									<Name>1080p</Name>
									<Video>video_1080</Video>
									<Audio>opus</Audio>
								</Rendition>
								<Rendition>
									<Name>720p</Name>
									<Video>video_720</Video>
									<Audio>opus</Audio>
								</Rendition>
							</Playlist>
```

**Comment by getroot** [comment]
Come to think of it, even in this case, I developed so that the playlist can be used except for the rendition, but there seems to be something that doesn't work as intended. I'll try to reproduce this issue too and fix it if I find any. Thanks for reporting. (I'm very busy with other things right now, so I'm going to see this next week.)

**Comment by NkInKaIgIe** [comment]
@getroot  i wait for you .
thank you for support

**Comment by getroot** [comment]
Your `ABR `playlist has 3 renditions. And for 2 renditions, the audio codec is OPUS. Since OPUS is not supported in LLHLS, the LLHLS publisher ignores those renditions and leaves only one. This would have been the case when playing in Origin. Try setting the Rendition's audio to aac.
