### ISSUE TITLE
ll-hls reliably stops working after ~10 minutes of smooth playback

### ISSUE THREAD

**Issue by naanlizard** [AirenSoft/OvenMediaEngine#848]
**Describe the bug**
LL-HLS works and generally is very good, but after 10 minutes or so, playback reliably stops and the player (ovenplayer) starts buffering endlessly until you refresh. 

**To Reproduce**

 Dockerfile:

> ```
> FROM airensoft/ovenmediaengine:0.14.5
> 
> RUN apt-get update && apt-get install -y curl
> 
> ENV API_ACCESS_TOKEN=x
> 
> WORKDIR /opt/ovenmediaengine/bin
> 
> COPY ./Server.xml /opt/ovenmediaengine/bin/origin_conf/Server.xml
> COPY EdgeConfig.xml ./edge_conf/Server.xml
> 
> COPY entrypoint.sh .
> 
> HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD curl --fail -H "Authorization: Basic $(printf ${API_ACCESS_TOKEN} | base64)"  'http://localhost:48081/v1/vhosts' 
> 
> CMD ["bash", "entrypoint.sh"]
> ```
> 
> Server.xml
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> 
> <Server version="8">
> 	<Name>OvenMediaEngine</Name>
> 	
> 	<Type>origin</Type>
> 	
> 	<IP>*</IP>
> 
> 	
> 	<StunServer>stun.l.google.com:19302</StunServer>
> 
> 	
> 	<Bind>
> 
> 		<Managers>
> 			<API>
> 				<Port>48081</Port>
> 				<WorkerCount>1</WorkerCount>
> 			</API>
> 		</Managers>
> 
> 
> 		<Providers>
> 			
> 			
> 			
> 			<RTMP>
> 				<Port>${env:OME_RTMP_PROV_PORT:1951}</Port>
> 				<WorkerCount>1</WorkerCount>
> 			</RTMP>
> 			<SRT>
> 				<Port>9999</Port>
> 				<WorkerCount>1</WorkerCount>
> 			</SRT>
> 			<WebRTC>
> 				<Signalling>
> 					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
> 					<WorkerCount>1</WorkerCount>
> 				</Signalling>
> 
> 				<IceCandidates>
> 
> 					<TcpRelay>*:3478</TcpRelay>
> 					
> 					<TcpForce>false</TcpForce>
> 
> 					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10000-10005/udp}</IceCandidate>
> 					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
> 				</IceCandidates>
> 			</WebRTC>
> 	
> 		</Providers>
> 
> 		<Publishers>
> 			<WebRTC>
> 				<Signalling>
> 					<Port>${env:OME_SIGNALLING_PORT:3333}</Port>
> 					
> 					<TLSPort>${env:OME_SIGNALLING_PORT_SECURE:3334}</TLSPort>
> 					<WorkerCount>1</WorkerCount>
> 				</Signalling>
> 				<IceCandidates>
> 					
> 					<TcpRelay>*:3478</TcpRelay>
> 					
> 					<TcpForce>false</TcpForce>
> 
> 					<IceCandidate>${env:OME_ICE_CANDIDATES:*:10000-10005/udp}</IceCandidate>
> 					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
> 				</IceCandidates>
> 			</WebRTC>
> 
> 			<HLS>
> 				<Port>799</Port>
> 				
> 				<TLSPort>800</TLSPort>
> 				<WorkerCount>1</WorkerCount>
> 			</HLS>
> 
> 			<LLHLS>
> 				<Port>799</Port>
> 				<TLSPort>800</TLSPort>
> 				<WorkerCount>1</WorkerCount>
> 			</LLHLS>
> 		</Publishers>
> 	</Bind>
> 
> 	
> 	
> 
> 	
> 
> 	<Managers>
> 		<Host>
> 			<Names>
> 				<Name>*.hostname.tld</Name>
> 				<Name>hostname.tld</Name>
> 				<Name>localhost</Name>
> 				<Name>127.0.0.1</Name>
> 			</Names>
> 			<TLS>
> 				<CertPath>/opt/ovenmediaengine/cert.pem</CertPath>
> 				<KeyPath>/opt/ovenmediaengine/privkey.pem</KeyPath>
> 				<ChainCertPath>/opt/ovenmediaengine/fullchain.pem</ChainCertPath>
> 			</TLS>
> 		</Host>
> 		<API>
> 			<AccessToken>${env:API_ACCESS_TOKEN:x}</AccessToken>
> 		</API>
> 	</Managers>
> 
> 
> 	<VirtualHosts>
> 		
> 		<VirtualHost>
> 			<Name>default</Name>
> 			
> 			<Distribution>hostname.tld</Distribution>
> 
> 			
> 			<Host>
> 				<Names>
> 						<Name>*.hostname.tld</Name>
> 						<Name>hostname.tld</Name>
> 						<Name>localhost</Name>
> 						<Name>127.0.0.1</Name>
> 				</Names>
> 				<TLS>
> 					<CertPath>/opt/ovenmediaengine/cert.pem</CertPath>
> 					<KeyPath>/opt/ovenmediaengine/privkey.pem</KeyPath>
> 					<ChainCertPath>/opt/ovenmediaengine/fullchain.pem</ChainCertPath>
> 				</TLS>
> 			</Host>
> 			
> 			
> 			<Applications>
> 				<Application>
> 					<Name>live</Name>
> 					
> 					<Type>live</Type>
> 					<OutputProfiles>
> 						
> 						<HardwareAcceleration>false</HardwareAcceleration>
> 						<OutputProfile>
> 							<Name>bypass_stream</Name>
> 							<OutputStreamName>${OriginStreamName}</OutputStreamName>
> 							<Encodes>
> 								<Audio>
> 									<Bypass>true</Bypass>
> 								</Audio>
> 								<Video>
> 									<Bypass>true</Bypass>
> 								</Video>
> 								<Audio>
> 									<Codec>opus</Codec>
> 									<Bitrate>128000</Bitrate>
> 									<Samplerate>48000</Samplerate>
> 									<Channel>2</Channel>
> 								</Audio>
> 							</Encodes>
> 						</OutputProfile>
> 
> 						
> 						<OutputProfile>
> 							<Name>audio_only</Name>
> 							<OutputStreamName>${OriginStreamName}_audio</OutputStreamName>
> 							<Encodes>
> 								<Audio>
> 									<Bypass>true</Bypass>
> 								</Audio>
> 								<Audio>
> 									<Codec>opus</Codec>
> 									<Bitrate>128000</Bitrate>
> 									<Samplerate>48000</Samplerate>
> 									<Channel>2</Channel>
> 								</Audio>
> 							</Encodes>
> 						</OutputProfile>
> 
> 					</OutputProfiles>
> 					<Providers>
> 						<WebRTC />
> 						<RTMP />
> 						<WebRTC>
> 							<Timeout>30000</Timeout>
> 						</WebRTC>
> 					</Providers>
> 					<Publishers>
> 						<AppWorkerCount>1</AppWorkerCount>
> 						<StreamWorkerCount>8</StreamWorkerCount>
> 
> 						<WebRTC>
> 							<Timeout>30000</Timeout>
> 							<Rtx>true</Rtx>
> 							<Ulpfec>true</Ulpfec>
> 							<JitterBuffer>true</JitterBuffer>
> 						</WebRTC>
> 
> 						<RTMPPush></RTMPPush>
> 
> 						<HLS>
>               <SegmentDuration>1</SegmentDuration>
>               <SegmentCount>3</SegmentCount>
>               <CrossDomains>
>                 <Url>hostname.tld</Url>
>               </CrossDomains>
>             </HLS>
> 
> 						<LLHLS>
> 							<ChunkDuration>0.2</ChunkDuration>
> 							<SegmentDuration>6</SegmentDuration>
> 							<SegmentCount>10</SegmentCount>
> 							<CrossDomains>
> 								
> 								<Url>*</Url>
> 							</CrossDomains>
> 						</LLHLS>
> 					</Publishers>
> 				</Application>
> 			</Applications>
> 		</VirtualHost>
> 	</VirtualHosts>
> </Server>
> 					  
> ```

**Expected behavior**
Smooth playback, no buffering

**Logs**
A sample log extract (same as in ticket #847 )

[omelog.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9293074/omelog.txt)

**Player (please complete the following information):**
 - Device: Have tested and observed in various Chrome versions (including the most recent as of this post) on windows, Chrome on ios

**Additional context**
Could be something in our player page, we will test that, but I figured I'd open a ticket here in case something is obviously wrong with our setup

**Comment by getroot** [comment]
Could you please test it with THEO Player (https://www.theoplayer.com/test-your-stream-hls-dash-hesp) to see if it's a problem with llhls.js?

You can test by enabling the "Use your own stream" button and inserting your URL. Alternatively, you can select "HLS Low Latency - AirenSoft" and click the "CLICK HERE TO LOAD YOUR STREAM" button to test it on the server we provide.

For reference, the 857:50:17.192 part at the bottom of the "HLS Low Latency - AirenSoft" video shows the time this stream worked without interruption. It's been working fine without crashes for over 30 days already, but your crash issue is not reproduced. I would very much like to solve your crash issue.

**Comment by getroot** [comment]
Please send demo link to support@airensoft.com. We try to apply some options to hls.js

**Comment by getroot** [comment]
I tested your URL playback in Seoul, Korea. As a result your chunk size (0.2s) is too small. This will only play well in the best network environment. This can cause the player's buffers to underflow when network jitter occurs, resulting in continued unstable playback. Besides, you're not letting the player have enough buffers because you've set Target latency and Max latency in the player's HLS Options. I'm guessing that's why your players are constantly experiencing buffering.
On the other hand, THEO Player does not have Target latency and Max latency settings, so when jitter occurs, THEO Player is increasing the buffer sufficiently. I think that's probably why it plays better than hls.js. (Of course, you can set these options for THEO as well. It's just not on the demo site.)

As you know OvenPlayer uses hls.js to play HLS. The hls.js demo site below can give you many options and you can also monitor the buffering status of the player. It is recommended to test it while adjusting various options on the demo site below.
https://hls-js.netlify.app/demo/

And in my experience, when servicing a global target, 0.5 seconds is the most appropriate for the partial segment size of LLHLS.

**Comment by naanlizard** [comment]
We will try adjusting those settings, thank you

**Comment by getroot** [comment]
And if you want to discuss further, please close this issue and create an issue in the OvenPlayer repo. Thank you.
