### ISSUE TITLE
Are we able to config a stun/turn server?

### ISSUE THREAD

**Issue by ytian801** [AirenSoft/OvenMediaEngine#85]
In some case, we need use a stun/turn server in ome, is there a place to add a stun/turn server?

**Comment by getroot** [comment]
We recommend that stun servers and turn servers use different open sources.  And ome has a lot of place to add it.  Because ome is open source.

**Comment by ytian801** [comment]
Sorry, I don't mean to use ome as a stun server, I mean can ome use a stun server? The `offer` from ome only contains `typ host` candidates for now.

**Comment by getroot** [comment]
Sorry. I misunderstood.
Currently, OME does not use external STUN or TURN servers. Because OME is a streaming server, it is developed under the assumption that it operates on PUBLIC network. However, we are considering integrating STUN for cases where ome cannot get PUBLIC IP locally, such as AWS EC2.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.

**Comment by samirsommaior** [comment]
Is there any plan to support exernal TURN servers? I have a situation where users should be allowed to access their home ip camera video feeds from within a home automation mobile app, through a PC running the home automation software and OME inside their homes.

**Comment by getroot** [comment]
@samirsommaior 
OME is designed as a high-capacity streaming server. This assumes that OME is running on a public network.

And anyway, if OME runs on a private network, there is no way to access OME's WebRTC signaling server. (TURN is the next problem.) Rather, I think it is better to use port forwarding that can access the private network from the outside.

**Comment by samirsommaior** [comment]
Hi @getroot , the problem of accessing the signaling server is already taken care of by using an external http relay server (https://github.com/localtunnel/localtunnel). Configuring port forwarding for hundreds of users is not feasible in our case.

**Comment by getroot** [comment]
@samirsommaior 
I have a question. Instead of installing an external turn server, why not install OME externally and send the home IP camera to the installed external OME?

**Comment by getroot** [comment]
@samirsommaior 
Also, there is no need to allocate hundreds of ports for port forwarding of hundreds of users. It is enough to open the signaling port (default:3333) and WebRTC/tcp port (default:4378) used by OvenMediaEngine. If you want to use WebRTC/udp, you can additionally forward the WebRTC/udp port (default 10000-10005/udp) to the OME server.
