### ISSUE TITLE
An error occurred while accept SSL connection: [OpenSSL] error:0A00009C:SSL routines::http request 

### ISSUE THREAD

**Issue by SabsLive999** [AirenSoft/OvenMediaEngine#850]
I've successfully configured my Domain to AWS Route 53
I've created Network Load Balancer for the edge with port 3334
I've created SSL certificate wildcard using certbot route 53 and use it on my edge. **successful**
I've imported the SSL certificate on AWS ACM to be used by the load balancer.

**Comment by getroot** [comment]
Upload your entire Server.xml and ovenmediaengine.log files so we can analyze the problem.
As of now, all I can guess is that you most likely didn't set up ChainCert properly.
