### ISSUE TITLE
Failed to pull RTSP source stream

### ISSUE THREAD

**Issue by Forest-fox** [AirenSoft/OvenMediaEngine#851]
**Describe the bug**
Have configured media engine to pull RTSP stream from camera and push LLHLS to client.
RTSP configuration on server:

```
<Bind><Providers><RTSP>
<Port>554\</Port>
</RTSP></Providers></Bind>
...
<Origins><Properties>
    <NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
    <UnusedStreamDeletionTimeout>60000</UnusedStreamDeletionTimeout>
</Properties>
<Origin>
<Location>/intercom/10.154.192.21</Location><Pass>
      <Scheme>rtsp</Scheme>
      <Urls><Url>10.154.192.21/av0_0</Url></Urls>
      <ForwardQueryParams>false</ForwardQueryParams>
</Pass></Origin></Origins>
```

Also configured LLHLS from https://airensoft.gitbook.io/ovenmediaengine/streaming/low-latency-hls
But i have error in log that rtsp server rejected setup request. 
URL works with direct play by VLC without authorizing.
Tried to proxying request with rtsp-simple-server - ovenmedia connect to server, but error with unsupported codec:1
What i am doing wrong?

**Expected behavior**
Stream pulled from camera.

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9347586/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Linux debian 11
 - OvenMediaEngine Version: v0.14.8
 - Branch: [e.g. dev]

**Additional context**
![Снимок экрана от 2022-08-16 12-50-58](https://user-images.githubusercontent.com/50401820/184788020-125f5dd5-8145-49d3-8b91-5de4b318962b.png)

**Comment by Forest-fox** [comment]
Locate a problem in projects/providers/rtspc/rtspc_stream.cpp in function GenerateControlUrl
content_base from camera was always empty, so SETUP message was wrong format <URL>trackID=1 instead of <URL>/trackID=1
Change string format fixed issue, but now i have messages:
[StreamCollector:808407] RtspcStream | rtspc_stream.cpp:515  | 10.154.192.21 - Unsupported codec  : 1
I [StreamCollector:808407] RtspcStream | rtspc_stream.cpp:355  | SDP : v=0
o=StreamingServer 3433055887 1660665756393624 IN IP4 10.154.192.21
s=av0_0
e=NONE
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
b=AS:1024
a=control:trackID=1
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=64001f;packetization-mode=1;sprop-parameter-sets=Z2QAH6wrUCgC3IA=,aO48MA==
a=x-dimensions:1280,720
m=audio 0 RTP/AVP 0
b=AS:64
a=control:trackID=2
a=rtpmap:0 PCMU/8000/1

What codec is unsupported? Video is h264.
I guess its audio, because format is G.722

**Comment by getroot** [comment]
Currently, OME's RTSP Provider only supports AAC and OPUS.

**Comment by Forest-fox** [comment]
Convert audio in input stream from G.722 to aac. 
Now OME process stream, but LLHLS playlist always empty.
>#EXTM3U
>#EXT-X-VERSION:7
>#EXT-X-INDEPENDENT-SEGMENTS

Logfile have records "LLHlsStream has been created : 10.154.192.21/100"
But client have nothing to play.

[OME config.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9355802/OME.config.txt)
[OME llhls.log](https://github.com/AirenSoft/OvenMediaEngine/files/9355793/OME.llhls.log)

**Comment by getroot** [comment]
Try to change SegmentDuration to 6 and SegmentCount to 10.
SegmentDuration must be longer than keyframe interval and SegmentDuration and SegmentCount do not affect the latency.

**Comment by Forest-fox** [comment]
Did this, but nothing changed.
[OME llhls.log](https://github.com/AirenSoft/OvenMediaEngine/files/9355911/OME.llhls.log)

**Comment by getroot** [comment]
[2022-08-17 12:47:25.410] W [OutboundWorker:884407] MediaRouter | mediarouter_stream.cpp:1040 | [#default#intercom/10.154.192.21] Detected out of order DTS of packet. track_id:0 dts:0->0


Check if the timestamp of your RTSP source is normal. It may be that the timestamp is not incrementing normally, so it is not getting the duration.

To check if OME is normal, send RTMP to OME with OBS and check if it works.

**Comment by getroot** [comment]
And LLHLS is played after two segments are created. You seem to have quit the player too soon.

**Comment by Forest-fox** [comment]
Have sent OBS RTMP to OME - playlist start to have entries:
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="1",NAME="none",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="../stream/chunklist_1_audio_llhls.m3u8?session=31_MyKQtazU"

#EXT-X-STREAM-INF:BANDWIDTH=2660000,RESOLUTION=1280x720,FRAME-RATE=30.0,CODECS="avc1.64001f,mp4a.40.2",AUDIO="1"
../stream/chunklist_0_video_llhls.m3u8?session=31_MyKQtazU

Does your team have plans to add support of G.722/G.711U/G.711A audio codec?

**Comment by Forest-fox** [comment]
I tried to convert stream in ffpeg

ffmpeg -r 25 -i rtsp://10.154.192.21/av0_0 -c:v libx264 -tune zerolatency -c:a aac -b:a 128K -f rtsp rtsp://<host>/stream
Then i have log [OME llhls.log](https://github.com/AirenSoft/OvenMediaEngine/files/9357078/OME.llhls.log)

Player not starting video, playlist is empty.

But if i try to play origin link rtsp://pb01.vladlink.ru:8554/test0 in player - everything seems fine.

**Comment by getroot** [comment]
Unfortunately I can't figure out any more from these logs. It seems to be the first thing to check whether the timestamp of the source stream mentioned earlier is normal.
```
[2022-08-17 12:12:31.773] W [OutboundWorker:881748] MediaRouter | mediarouter_stream.cpp:1040 | [#default#intercom/10.154.192.21] Detected out of order DTS of packet. track_id:0 dts:0->0
```


 It's possible for a video player to play back with an estimate of incorrect PTS/DTS, but on a server, using that method can cause a lot of side effects, so I didn't develop OME to behave that way.

I wish I could pull your RTSP and analyze it myself, but I'm too busy these days. If you send your RTSP url to support@airensoft.com, I'll analyze it later when I have time.

**Comment by getroot** [comment]
> Does your team have plans to add support of G.722/G.711U/G.711A audio codec for RTSP Pull?

Recently, no one has asked for this as it is necessary because that codec is rarely used. I also don't feel the need for this codec to be supported yet. So I have no plans to support this yet.
I look forward to the PR of this. I would be very grateful if you could PR for this.

**Comment by Forest-fox** [comment]
Have sent URLs to e-mail. Appreciate your help.

**Comment by Forest-fox** [comment]
Try with another camera on local network by RTSP protocol without sound track - got same message:

> [StreamMotor:1710536] RtspcStream | rtspc_stream.cpp:965  | Since this stream has a single track, it computes PTS alone without RTCP SR.
> [OutboundWorker:1710480] MediaRouter | mediarouter_stream.cpp:1040 | [#default#intercom/10.243.8.151] Detected out of order DTS of packet. track_id:0 dts:0->0
> [OutboundWorker:1710480] WebRTC Publisher | rtc_stream.cpp:192  | WebRTC Stream has been created : 10.243.8.151/100 Rtx(false) Ulpfec(false) JitterBuffer(false) PlayoutDelay(false min:0 max: 0)
> [OutboundWorker:1710480] Publisher | stream.cpp:204  | WebRTC Publisher Application application has started [10.243.8.151(100)] stream (MSID : 0)
> [OutboundWorker:1710480] LLHLS Publisher | llhls_stream.cpp:105  | LLHlsStream has been created : 10.243.8.151/100 OriginMode(false) Chunk Duration(0.20) Segment Duration(6) Segment Count(3)

And playlist empty again.

**Comment by flaeri** [comment]
I'm running into a similar (same?) issue.

LLHLS playlist is always empty. Its RTSP Pull. There is no audio track. Timestamps are not great on the source. I've confirmed the keyframe interval is 1sec, and PPS and SPS seems plentiful.

The same stream is fine in the ovenMedia WebRTC player, but unfortunately I need a way that is not webRTC (and LLHLS seems to be the only way atm). If I connect directly to the RTSP source it seems to playback fine in ffmpeg.

I can upload some video samples if that is of benefit.

This is what the OvenMedia log has to say:
```
[2022-10-10 11:03:59.391] I [SPRtcSig-T3333:3801653] Orchestrator | orchestrator.cpp:758  | The stream was pulled successfully: [#default#rtsp/tp11back] (179)
[2022-10-10 11:03:59.452] I [StreamMotor:1028221] RtspcStream | rtspc_stream.cpp:966  | Since this stream has a single track, it computes PTS alone without RTCP SR.
[2022-10-10 11:03:59.452] W [OutboundWorker:3802187] MediaRouter | mediarouter_stream.cpp:1041 | [#default#rtsp/tp11back] Detected out of order DTS of packet. track_id:0 dts:0->0
[2022-10-10 11:03:59.452] I [OutboundWorker:3802187] MediaRouter | mediarouter_application.cpp:821  | [#default#rtsp/tp11back(179)] Stream has been created
[Stream Info]
id(179), msid(0), output(tp11back), SourceType(RtspPull), RepresentationType(Relay), Created Time (Mon Oct 10 11:03:58 2022) UUID(1c6a6e1c-ba55-4771-86d7-f38480b6ad14/default/#default#rtsp/tp11back/i)
        Video Track #0: Name() Bitrate(0b) codec(1,H264,Auto) resolution(640x480) framerate(0.00fps) KeyInterval(0) BFrames(0) timebase(1/90000)
[2022-10-10 11:03:59.453] I [OutboundWorker:3802187] WebRTC Publisher | rtc_stream.cpp:192  | WebRTC Stream has been created : tp11back/179
Rtx(false) Ulpfec(false) JitterBuffer(false) PlayoutDelay(false min:0 max: 0
```

FFProbe RTSP source:
```
[rtsp @ 0x56479886ef00] SDP:
v=0
o=- 18446109230308800511 1 IN IP4 10.94.11.2
s=Session streamed with GStreamer
i=rtsp-server
t=0 0
a=tool:GStreamer
a=type:broadcast
a=control:*
a=range:npt=now-
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
a=rtpmap:96 H264/90000
a=framerate:15
a=fmtp:96 packetization-mode=1;profile-level-id=4d4029;sprop-parameter-sets=Z01AKZZUBQHsgA==,aO44gA==
a=control:stream=0
a=ts-refclk:local
a=mediaclk:sender

[rtsp @ 0x56479886ef00] max delay reached. need to consume packet
[rtsp @ 0x56479886ef00] RTP: missed 13 packets
[h264 @ 0x564798872980] Current profile doesn't provide more RBSP data in PPS, skipping
Input #0, rtsp, from 'rtsp://10.94.11.2:8554/back':
  Metadata:
    title           : Session streamed with GStreamer
    comment         : rtsp-server
  Duration: N/A, start: 0.464033, bitrate: N/A
    Stream #0:0: Video: h264 (Main), 1 reference frame, yuv420p(progressive, left), 640x480, 16.17 tbr, 90k tbn, 180k tbc
```

**Comment by getroot** [comment]
I fixed an issue today where sources pulled with RTSP would not play on LLHLS. Could you please check if the latest master branch solves your problem?

**Comment by flaeri** [comment]
You are my hero @getroot !!
I am already compiling as we speak when I saw your comment. Will report back soon. Thank you so much!

**Comment by Forest-fox** [comment]
@getroot , thank you for fix. Confirm, that 0.14.13 fill playlist now.
