### ISSUE TITLE
Can you add MPEG-Dash Provider

### ISSUE THREAD

**Issue by donghyun0910** [AirenSoft/OvenMediaEngine#852]
**Is your feature request related to a problem? Please describe.**
Nothing to do with OME's problems.
However, since the types that can be provided by media sources are limited, we want that you add a feature.

**Describe the solution you'd like**
The media source can be provided using mpeg-dash only.
We would like to publish the received media to WebRTC or cmaf, etc.
However, OME's provider does not provide mpeg-dash.

**Describe alternatives you've considered**
Can you add MPEG-Dash functionality to OME?

**Additional context**
Nothing

**Comment by getroot** [comment]
I think it would be better to pull MPEG-DASH using an external tool such as ffmpeg and send it to OME over RTMP/MPEG-2 TS/SRT.

**Comment by donghyun0910** [comment]
> I think it would be better to pull MPEG-DASH using an external tool such as ffmpeg and send it to OME over RTMP/MPEG-2 TS/SRT.
> 
> And if you use MPEG-DASH as the stream source, there is no advantage to streaming with WebRTC or LLHLS because there is already a delay in the stream source. For what purpose are you going to do this?

only mpeg-dash can be provided at the media source.
We recognize the delay of dash and are looking for the fastest way to publish.
For now, We'll proceed with the method you suggested.
Thank you
