### ISSUE TITLE
Player configuration

### ISSUE THREAD

**Issue by annibal1** [AirenSoft/OvenMediaEngine#853]
good morning
I installed everything in a Ubuntu 20.04 server
I'm doing tests and with OBS the streaming starts
Putting rtmp: //Myip:1935/App/Stream
But going to any browser crome, Edge Mozilla etc and fasting
http://myip:8080/app/stream/playlist.m3u8
nothing is happening
the link does not work
Do I have to install or configure something else to make this work?

**Comment by getroot** [comment]
Please refer to the manual.

https://airensoft.gitbook.io/ovenmediaengine/getting-started
https://airensoft.gitbook.io/ovenmediaengine/configuration

WebRTC and LLHLS are enabled by default. The default ports for LLHLS are 3333, 3334, and you will have to set a certificate according to your browser's policy.

**Comment by annibal1** [comment]
With the player I demo the  code ws://Myip/3333/App/Stream works
But I don't work the .m3u8 player
I followed what is described but I have not achieved any results
Is it possible to have a support for a fee?

**Comment by getroot** [comment]
https://your-domain.com:3334/app/stream/llhls.m3u8 is the default LLHLS URL. 
You have to set a certificate in your Server.xml due to browser's security policy. This is because most recent browsers do not support CORS in http due to various security issues. Please do a Google search for more information on this.

**Comment by annibal1** [comment]
i installed letsencrypt on apache
imported the path to the Server.xml file
Enabled ports
restarted the services
but on https it still doesn't work
attached my configuration
Am I doing some configuration wrong ??
[Server.zip](https://github.com/AirenSoft/OvenMediaEngine/files/9381225/Server.zip)

**Comment by annibal1** [comment]
![immagine](https://user-images.githubusercontent.com/50693441/185606150-27eb6ed2-4ead-4c57-807b-7eee468d268f.png)
I changed the configuration in the certificates I put this as shown in the attached image
but https still doesn't work
<CertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</CertPath>
<KeyPath>/etc/letsencrypt/live/newtorrent.it/privkey.pem</KeyPath>
<ChainCertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</ChainCertPath>

**Comment by annibal1** [comment]
ok solved
I hadn't uncommented in the config file
now it looks like it works fine
only question
how can i see how many ip / users are watching the live broadcast ??
Is there any way to do this?? or a command from ssh '?
