### ISSUE TITLE
SCTE/ID3 Tags

### ISSUE THREAD

**Issue by vasudevavarun** [AirenSoft/OvenMediaEngine#855]
**Is your feature request related to a problem? Please describe.**
No, It is not related to a problem but a new feature request but it is very common in HLS/Dash format

**Describe the solution you'd like**
API based SCTE/ID3 insertion in output HLS/DASH, User can just call the API when the tag is required and it will insert the respective tag in HLS/Dash output

**Describe alternatives you've considered**
No alternative as of now

**Comment by getroot** [comment]
Legacy HLS and DASH are no longer being updated. 
And I have plans to support emsg box in LLHLS.

**Comment by stevespaw** [comment]
+1
