### ISSUE TITLE
OME with external encoder

### ISSUE THREAD

**Issue by streamthing** [AirenSoft/OvenMediaEngine#857]
Good morning,
We are using an external transcoder and want to use OME with WebRTC ABR without using stream re-encoding by OME. Is it possible or will it be possible?
Streams: streamname_360p, streamname_480p, streamname_720p, streamname_1080p etc ..

**Comment by getroot** [comment]
It is not possible and I don't have a plan to add that feature. Syncing multiple live inputs is almost impossible, and OME has its own transcoder, so supporting it isn't much of a benefit.

**Comment by mpisat** [comment]
> Good morning, We are using an external transcoder and want to use OME with WebRTC ABR without using stream re-encoding by OME. Is it possible or will it be possible? Streams: streamname_360p, streamname_480p, streamname_720p, streamname_1080p etc ..

Maybe you can modify player code and try to implement it in there?
