### ISSUE TITLE
Thumbnail Could not found application

### ISSUE THREAD

**Issue by AMR1798** [AirenSoft/OvenMediaEngine#858]
**Describe the bug**
Thumbnail returning empty response with 200 status code

**To Reproduce**
1. Enable thumbnail option in Server.xml
2. Start streaming
3. Request thumbnail using postman/chrome

**Expected behavior**
Return thumbnail image

**Logs**
`Aug 17 22:22:00 #####982229.##### OvenMediaEngine[6799]: [2022-08-17 22:22:00.373] W [SPthumb_https-T:6820] Thumbnail | thumbnail_publisher.cpp:205  | Could not found application
Aug 17 22:22:00 #####982229.##### OvenMediaEngine[6799]: [2022-08-17 22:22:00.548] W [SPthumb_https-T:6820] Thumbnail | thumbnail_publisher.cpp:205  | Could not found application
Aug 17 22:22:00 #####982229.##### OvenMediaEngine[6799]: [2022-08-17 22:22:00.719] W [SPthumb_https-T:6820] Thumbnail | thumbnail_publisher.cpp:205  | Could not found application
Aug 17 22:22:01 #####982229.##### OvenMediaEngine[6799]: [2022-08-17 22:22:00.904] W [SPthumb_https-T:6820] Thumbnail | thumbnail_publisher.cpp:205  | Could not found application`

**Server (please complete the following information):**
 - OS: CentOS 7
 - OvenMediaEngine Version: 0.14.[8]
 - Branch: 

**Player (please complete the following information):**
 - Device: Desktop PC?
 - OS: Windows 11
 - Browser Chrome/Postman
 - Version not relevant

**Additional context**
https://prnt.sc/G8L2HjFT77uK

**Comment by getroot** [comment]
Thumbnail feature is working well in my various commercial environment. 

Please upload your Server.xml and entire ovenmediaengine.log file so that I can figure out the cause of the problem. And let me know what was the url you request for thumbnail.

**Comment by AMR1798** [comment]
Here's the [ovenmediaengine.log](https://logpaste.com/nq6CX2Nd) and the [Server.xml](https://logpaste.com/KVZSHTnQ).

Some additional stuff that I noticed, the response code is always 200 even when the stream does not exist: https://prnt.sc/TGAYwXJhEdT3

i'll try to reinstall again in the meantime

**Comment by getroot** [comment]
Your Publisher is missing the Thumbnail setting.

```
<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.5</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
					</Publishers>
```

https://airensoft.gitbook.io/ovenmediaengine/thumbnail-experiment#publisher

And I will fix the HTTP error code of the Thumbnail publisher. Thanks for the report.

**Comment by AMR1798** [comment]
I see. i've updated my Server.xml file and it seems to be working now. I will close this issue now.
Thank you for the help!
