### ISSUE TITLE
RTSP push and pull

### ISSUE THREAD

**Issue by ruifigueirinha** [AirenSoft/OvenMediaEngine#86]
I have noticed that these features were added to OME but I can't seem to make them work correctly. I am currently trying the RTSP push feature with the following ffmpeg command:

ffmpeg -stream_loop -1 -re -i rtsp_test.mkv -vcodec copy  -an -f rtsp -rtsp_transport tcp rtsp://<IP>:8554/rtsp_app/rtsp_stream 
I also created the rtsp_app application in the Server.xml but for some reason OME is not recognizing the application when I run the ffmpeg command.

**Comment by getroot** [comment]
Where did you get that information from?  The feature is still under development and has not been officially opened.  It will be updated in the manual when testing is complete.

**Comment by rfigueirinha** [comment]
Thank you for the response. Can I use ffmpeg to restream the RTSP stream into RTMP?

**Comment by getroot** [comment]
I have no deep knowledge of FFMPEG. When I searched Google, I got a lot of results. I hope you find it.

**Comment by getroot** [comment]
https://airensoft.gitbook.io/ovenmediaengine/live-source/mpeg-2-ts-beta
