### ISSUE TITLE
OME service restarts unexpectedly

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#862]
what are the causes that cause the OME service to restart randomly after a few hours. sometimes the service manages to be active for 12 or 14 hours, but unexpectedly it restarts automatically. I use OME version 12.9 and ubuntu 18.05.

**Comment by getroot** [comment]
#833 I think it is duplicated issue

**Comment by getroot** [comment]
OvenMediaEngine is currently 0.14.8. Numerous bugs have been fixed since 0.12.9. Why do you keep using 0.12.9 and post an issue instead of using the latest version that fixed the issue?

**Comment by Mariano245** [comment]
I thought to give version 0.12.9 one last chance. However I am going to reinstall Ubuntu to version 20.04 and install a newer version of OME. to play the streams I use HLS and not LLHLS. 
I will analyze the compatibility of the players, I do not know LLHLS

**Comment by getroot** [comment]
For reference, one of the advantages of LLHLS is that it supports legacy HLS players. Of course, in that case, it won't play with low latency.

**Comment by imrahuldevopser** [comment]
please provide  avalid solution###

**Comment by imrahuldevopser** [comment]
Please provide a valid solutions..

**Comment by getroot** [comment]
@imrahuldevopser 
Older versions have bugs, so using the latest version that fixes them is the only solution. do you mean something else?

**Comment by Mariano245** [comment]
I am going to try the latest version, it will take time but I will do it. Thank you
