### ISSUE TITLE
Any way to reduce latency?

### ISSUE THREAD

**Issue by siphonelee** [AirenSoft/OvenMediaEngine#865]
I've setup a OME server and it works perfectly. But I found the end-to-end latency from publisher to player is over 2 seconds. Is there any way to improve this? 

What I'm using is: 
- OME v0.14.8 running on self-hosted server 
- OvenStreamEncoder app for live streaming
- http://demo.ovenplayer.com/ as player

Thanks!

**Comment by getroot** [comment]
What protocol do you use to play? 
WebRTC : ~1 sec
LLHLS : 2 ~ 3 sec (If partial segment duration is 0.5 sec)

**Comment by siphonelee** [comment]
I'm using RTMP for stream publishing, and WebRTC for stream playing.

> What protocol do you use to play? WebRTC : ~1 sec LLHLS : 2 ~ 3 sec (If partial segment duration is 0.5 sec)

**Comment by getroot** [comment]
If you are using WebRTC, you can usually play end-to-end in less than 1 second. How about testing with OBS? You must set the options of OBS well according to the manual. b-frame, keyframe interval, etc.
https://airensoft.gitbook.io/ovenmediaengine/getting-started#example-of-using-obs-encoder

Please upload your Server.xml and /var/log/ovenmediaengine/ovenmediaengine.log files.

**Comment by siphonelee** [comment]
Using OBS with the low latency profile enabled in hardware encoder, the end-to-end latency is indeed below 1 second. My guess is my mobile phone is not a high tier model which can make full use of OvenStreamEncoder's capability.

Thanks!
