### ISSUE TITLE
optimal configuration Server.xml

### ISSUE THREAD

**Issue by annibal1** [AirenSoft/OvenMediaEngine#866]
I've been testing ovenmediaengine for several days and with the basic configuration of the server.xml I noticed that when I play from obs I don't go beyond 4500/5000 because over the band it turns red and the streaming quality is poor
I tried and installed obs on a 1GB bandwidth server and started OBS from the server and the result is the same as my home line
So I assume that there is some limitation / setting to configure on Server.xml and that the problem does not depend on my home line that I have a 2GB fiber
Can anyone give me some advice or post some optimal configuration to make obs work well with ovenmediaengine ??
I would only be interested in streaming from pc to ovenmediaengine server
I state that I followed the guide published there without getting a good result
I have not used the installation on Docker

**Comment by getroot** [comment]
Only if you specifically describe the problem you are having can someone help you with your problem.

What are your OBS settings? Take a screenshot and upload it.
What exactly does poor quality mean? (The picture quality is bad?, the video is not smooth?)
Upload your Server.xml file.
Upload your ovenmediaengine.log file.
What does 4500/5000 mean?

**Comment by annibal1** [comment]
![Cattura](https://user-images.githubusercontent.com/50693441/187091369-46f9abf8-6e89-459e-82af-ceb09dd8e070.JPG)
![Cattura2](https://user-images.githubusercontent.com/50693441/187091371-b93ab892-a11e-40fd-80d1-93ad8f67168a.JPG)

Server.xml

<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.ovenmediaengine.com:13478</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		

		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>1935</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>4000/udp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>

				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<LLHLS>
				
				<Port>3333</Port>
				
				<TLSPort>3334</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			<TLS>
				<CertPath>/etc/letsencrypt/live/mysite/fullchain.pem</CertPath>
				<KeyPath>/etc/letsencrypt/live/mysite/privkey.pem</KeyPath>
				<ChainCertPath>/etc/letsencrypt/live/mysite/fullchain.pem</ChainCertPath>
			</TLS>
		</Host>
		<API>
			<AccessToken>ome-access-token</AccessToken>

			<CrossDomains>
				<Url>*.airensoft.com</Url>
				<Url>http://*.sub-domain.airensoft.com</Url>
				<Url>http?://airensoft.*</Url>
			</CrossDomains>
		</API>
	</Managers>
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
				<TLS>
				<CertPath>/etc/letsencrypt/live/mysite/fullchain.pem</CertPath>
                                <KeyPath>/etc/letsencrypt/live/mysite/privkey.pem</KeyPath>
                                <ChainCertPath>/etc/letsencrypt/live/mysite/fullchain.pem</ChainCertPath>
				</TLS>
				
			</Host>

			

			

			
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>

							

							<Encodes>
								<Audio>
									<Name>bypass_audio</Name>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Name>bypass_video</Name>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.5</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>


myfile log

[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9440347/ovenmediaengine.log)


Thanks for your support
I wanted to specify that the quality of the video with these parameters and bad also because as you can see from OBS the flow to the server does not pass well

**Comment by annibal1** [comment]
this attached and the image of the process
![Cattura](https://user-images.githubusercontent.com/50693441/187091822-286bb6f0-2deb-4037-b07f-1c0ff72d312b.JPG)

**Comment by getroot** [comment]
What version of OvenMediaEngine are you using? The log file you uploaded is strange. It seems that the pipe or fork on linux keeps failing.
/var/log/ovenmediaengine/ovenmediaenigne.log

What is your linux package and version.

Also, what about cpu/ram performance?

The problem of insufficient throughput in OBS seems to be insufficient performance of the linux machine where your OME is running.

**Comment by annibal1** [comment]
I am using the latest ome version and the system is installed on a ubuntu 20.04 machine
with 24 GB of ram

**Comment by getroot** [comment]
How about the CPU? Please take a screenshot after executing the top command.

**Comment by getroot** [comment]
And the log you uploaded is strange (OME is not running). Close OvenMediaEngine and restart it, reproduce the problem and upload its entire file.

**Comment by annibal1** [comment]
![Cattura](https://user-images.githubusercontent.com/50693441/187131562-24ff1b68-4df1-4c43-98d7-f804b4c06d9c.PNG)
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9441833/ovenmediaengine.log)

here they are attached

**Comment by getroot** [comment]
There is no record of stream playing in the log and no other problems. Did the problem reproduce when this log was written?

**Comment by annibal1** [comment]
then I reinstalled OME in another better performing server thinking that the problem could depend on the server
i have always installed ubuntu 20.04
same configurations as OBS
the Server.xml file is the same as the one posted earlier
the problem is always the same
attached the log file
![Cattura](https://user-images.githubusercontent.com/50693441/187165762-eea78dd2-b318-499b-8d61-23b6bad4c4b1.PNG)
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9443247/ovenmediaengine.log)

**Comment by getroot** [comment]
I didn't find any problems in your logs. If the OBS throughput is not output normally, it seems to be a problem on the other side. If the performance of OME is insufficient

First of all, you need to set the bitrate as low as 500k in OBS to see if it works. And set the keyframe interval of OBS to 1 second.

**Comment by annibal1** [comment]
now it seems to work fine with this new server
I have to be able to understand only how to do to understand how many people are connected to the streaming if there is a command from ssh or a file that records these activities
do i have to open another topic ??
PS: I congratulate you on the work done by all of you for this fantastic project
I will actively participate in the project also economically
Thank you
I await news

**Comment by getroot** [comment]
You can get the statistics through REST API. (https://airensoft.gitbook.io/ovenmediaengine/rest-api/v1/statistics/current)
If you have another problem, please open a new issue.
