### ISSUE TITLE
NDI input and output

### ISSUE THREAD

**Issue by stevespaw** [AirenSoft/OvenMediaEngine#868]
This is a big request I am sure and I have no idea if it would work in this architecture. But having NDI in and out options in this would make it one of the most useful tools available to broadcasters.

[https://www.ndi.tv/sdk/](https://www.ndi.tv/sdk/)

I am just throwing this out  - This might make the Enterprise edition more valuable????

Again Thanks!

**Comment by getroot** [comment]
I think it's better to use an external tool for NDI. And that external tool can send streams over RTMP, WebRTC and SRT to OvenMediaEngine.

**Comment by stevespaw** [comment]
I am looking to simplify our workflow, I guess we could use some NDI to UDP as middle man, but the only ones I know are Windows, it would be nice on the same server.
Would this be "frame" latency? I am looking for NDI to WebRTC possibilities with OvenPlayer.

**Comment by getroot** [comment]
I have no experience with NDI, but it would be good to get the NDI source with ffmpeg cmd and send it over RTMP to OvenMediaEngine.

I did a quick search and found the patches.
https://framagit.org/tytan652/ffmpeg-ndi-patch
