### ISSUE TITLE
HEVC Support

### ISSUE THREAD

**Issue by stevespaw** [AirenSoft/OvenMediaEngine#869]
Some of our venues have low bandwidth and we have to use HEVC for our feeds.
Is it possible to support HEVC / h.265 codec?

**Comment by getroot** [comment]
We haven't come across a great open source for HEVC yet. x265 is not available due to license conflict. There is a possibility that HEVC will be added to the enterprise version within this year (LLHLS only, WebRTC is not supported by the player anyway), as it has contracted Beamr's codec.

**Comment by getroot** [comment]
As I mentioned before we can't use x265 due to open source license conflict issues.

Therefore, we plan to apply Beamr's 265 encoder to the Enterprise edition. Also, the Enterprise edition already uses Beamr's 264 encoder.

**Comment by stevespaw** [comment]
I guess I don't have enough knowledge on licensing , I thought with GPL anyone could use it.

Thanks! I will continue to look at the Beamr project also.

**Comment by getroot** [comment]
OvenMediaEngine is APLGv3 and x264/x265 is GPLv2. These two licenses are not compatible.

**Comment by getroot** [comment]
HEVC is now supported on SRT and LLHLS. Check out the discussion below. https://github.com/AirenSoft/OvenMediaEngine/discussions/1242
