### ISSUE TITLE
RTMP PUSH

### ISSUE THREAD

**Issue by stevespaw** [AirenSoft/OvenMediaEngine#870]
**Describe the bug**
It seems that there is missing info in the server.xml for this....?
The RTMP output section has no content
https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Server.xml

**To Reproduce**
POST http://1.2.3.4:8081/v1/vhosts/default/apps/app:startPush

{
"id": "UserDefinedUniqueId",
"stream": {
"name": "stream",
"tracks": [ 101, 102 ]
},
"protocol": "rtmp",
"url":"rtmp://video.website.com:1935/live",
"streamKey":"24145e3b-0b2c-4cc6-8d46-86a736be0d15"
}

**Expected behavior**
Streaming

**reply**

{
    "message": "[HTTP] Could not find application: [default/app] (404)",
    "statusCode": 404
}

**Additional context**
I am sure that I am missing something simple

**Comment by getroot** [comment]
The RTMPPush feature is not turned on by default.
Refer to the manual and enable `<RTMPPush>` in Publisher.
https://airensoft.gitbook.io/ovenmediaengine/push-publishing

**Comment by stevespaw** [comment]
Thanks OK I did miss that info. But I have enabled it, I think and still 
reply

{
"message": "[HTTP] Could not find application: [default/app] (404)",
"statusCode": 404
}

![image](https://user-images.githubusercontent.com/11045430/187218274-41feb104-f5fe-4436-bcca-084deb575114.png)


I must still be missing something..

**Comment by getroot** [comment]
Please upload /var/log/ovenmediaengine.log file

**Comment by stevespaw** [comment]
I am running docker currently, Where is this log file?

**Comment by getroot** [comment]
It's in the same location (/var/log/ovenmediaengine folder) inside the docker container.

**Comment by stevespaw** [comment]
filled with these:
[2022-08-28 00:00:00.910] E [SPRtcSig-T3333:10] Orchestrator | orchestrator.cpp:660  | Could not find Origin for the stream: [#default#app/stream]
[2022-08-28 00:00:00.910] E [SPRtcSig-T3333:10] LLHLS Publisher | llhls_publisher.cpp:325  | Could not pull the stream : stream
[2022-08-28 00:00:02.166] E [SPRtcSig-T3333:10] Orchestrator | orchestrator.cpp:660  | Could not find Origin for the stream: [#default#app/stream]
[2022-08-28 00:00:02.166] E [SPRtcSig-T3333:10] LLHLS Publisher | llhls_publisher.cpp:325  | Could not pull the stream : stream

**Comment by getroot** [comment]
Please upload entire /var/log/ovenmediaenigne/ovenmediaenigne.log file.

**Comment by stevespaw** [comment]
Sorry that was the wrong file anyway.
[ovenmediaengine (1).log](https://github.com/AirenSoft/OvenMediaEngine/files/9445663/ovenmediaengine.1.log)

**Comment by getroot** [comment]
I can find the cause by looking at the log when the problem occurs.
The logs you uploaded are logs that do not have a stream named app/stream in your instance, but are trying to play the stream.
```
[2022-08-29 00:00:32.570] E [SPRtcSig-T3333:10] Orchestrator | orchestrator.cpp:660 | Could not find Origin for the stream: [#default#app/stream]
[2022-08-29 00:00:32.570] E [SPRtcSig-T3333:10] LLHLS Publisher | llhls_publisher.cpp:325 | Could not pull the stream : stream
```
Have you ever called the startPush API when there is no app/stream in the instance? After creating app/stream with OBS, etc., try startPush.

to analyze the exact problem

1. Restart OvenMediaEngine.
2. Create a stream with OBS, etc. (as app/stream name)
3. Call the startPush API.
4. If the problem persists, please upload the log file.

**Comment by stevespaw** [comment]
More info if it helps:
http://198.x.x.x:8081/v1/vhosts/default/apps/app  returns:
{
    "message": "OK",
    "response": {
        "dynamic": false,
        "name": "app",
        "outputProfiles": {
            "outputProfile": [
                {
                    "encodes": {
                        "audios": [
                            {
                                "bypass": true,
                                "name": "bypass_audio"
                            },
                            {
                                "bitrate": "128000",
                                "channel": 2,
                                "codec": "opus",
                                "samplerate": 48000
                            }
                        ],
                        "videos": [
                            {
                                "bypass": true,
                                "name": "bypass_video"
                            }
                        ]
                    },
                    "name": "bypass_stream",
                    "outputStreamName": "${OriginStreamName}"
                }
            ]
        },
        "providers": {
            "mpegts": {
                "streams": [
                    {
                        "name": "stream_4000",
                        "port": "4000/udp"
                    }
                ]
            },
            "ovt": {},
            "rtmp": {},
            "rtspPull": {},
            "srt": {},
            "webrtc": {}
        },
        "publishers": {
            "appWorkerCount": 1,
            "llhls": {
                "chunkDuration": 0.5,
                "crossDomains": [
                    "*"
                ],
                "segmentCount": 10,
                "segmentDuration": 6
            },
            "ovt": {},
            "streamWorkerCount": 8,
            "webrtc": {
                "jitterBuffer": false,
                "rtx": false,
                "timeout": 30000,
                "ulpfec": false
            }
        },
        "type": "live"
    },
    "statusCode": 200
}

**Comment by getroot** [comment]
Please show me your Server.xml.

Is `<Publishers><FILE>` turned on?

https://airensoft.gitbook.io/ovenmediaengine/recording-experiment#file-publisher

**Comment by stevespaw** [comment]
[Server.zip](https://github.com/AirenSoft/OvenMediaEngine/files/9454004/Server.zip)
![image](https://user-images.githubusercontent.com/11045430/187472185-796717e9-dc49-4bd6-976e-ebf59b8d4ba5.png)

**Comment by stevespaw** [comment]
I have not looked at the file recording parts yet in this project...
I was going to ask if the recordings can be saved to s3 in some way.

**Comment by stevespaw** [comment]
Is the location you see in the image correct? Enabling the API in this file works..
Where do we go from here?

**Comment by stevespaw** [comment]
HMMM I see you are right,
 I enabled the API here before, but see it is not enabled in it now..

**Comment by stevespaw** [comment]
Dang sorry, I was editing the backup file I made. Now it is a muxing error.
Here is the new log. It is starting now though!
{
    "message": "OK",
    "response": [
        {
            "app": "app",
            "createdTime": "2022-08-30T16:11:38.736+00:00",
            "finishTime": "1970-01-01T00:00:00.000+00:00",
            "id": "UserDefinedUniqueId",
            "protocol": "rtmp",
            "sentBytes": 0,
            "sentTime": 0,
            "sequence": 0,
            "startTime": "2022-08-30T16:11:38.737+00:00",
            "state": "error",
            "stream": {
                "name": "stream",
                "tracks": [
                    101,
                    102
                ]
            },
            "streamKey": "24145e3b-0b2c-4cc6-8d46-86a736be0d15",
            "totalsentBytes": 0,
            "totalsentTime": 0,
            "url": "rtmp://_video1.videosite.com:_1935/live",
            "vhost": "default"
        }
    ],
    "statusCode": 200
}
[ovenmediaengine (3).log](https://github.com/AirenSoft/OvenMediaEngine/files/9454703/ovenmediaengine.3.log)

**Comment by stevespaw** [comment]
Hooray - it works, 
I needed to change the 
"tracks": [ 101, 102 ]   to
"tracks": "101, 102"

Thanks for your help!

**Comment by stevespaw** [comment]
Now If we had the SRT Push we could get rid of out media gateways :-) https://github.com/AirenSoft/OvenMediaEngine/issues/867

**Comment by getroot** [comment]
"tracks": is [] grammatically correct. However, your stream does not have track IDs 101 and 102, so an error may have occurred. The tracks in your request were ignored because of incorrect syntax, and as a result all tracks were recorded.
Remove "tracks" to record all tracks.
