### ISSUE TITLE
access token rest api

### ISSUE THREAD

**Issue by annibal1** [AirenSoft/OvenMediaEngine#873]
reading this post
https://airensoft.gitbook.io/ovenmediaengine/rest-api
i am trying to understand and make it work
I followed these tips but my doubt is
how do i get my personal tocken to insert in the Server.xml ??
I am attaching my Server.xml file and screenshout of the changes and error it gives me
![Cattura](https://user-images.githubusercontent.com/50693441/187186283-d8604db6-3c42-478e-a822-40d5fde2e3ab.PNG)
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9443956/ovenmediaengine.log)

<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>stun.ovenmediaengine.com:13478</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		
		<Managers>
			<API>
				<Port>8081</Port>
				<TLSPort>8082</TLSPort>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>
		

		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>1935</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>4000/udp</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>

				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			<OVT>
				<Port>9000</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<LLHLS>
				
				<Port>3333</Port>
				
				<TLSPort>3334</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					
					<TcpRelay>*:3478</TcpRelay>
					
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	
	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
			<TLS>
				<CertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</CertPath>
				<KeyPath>/etc/letsencrypt/live/newtorrent.it/privkey.pem</KeyPath>
				<ChainCertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</ChainCertPath>
			</TLS>
		</Host>
		<API>
			<AccessToken>b21lLWFjY2Vzcy10b2tlbg==</AccessToken>

			<CrossDomains>
				<Url>*.newtorrent.it</Url>
				
			</CrossDomains>
		</API>
	</Managers>
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					 
					<Name>*</Name>
				</Names>
				
				<TLS>
				<CertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</CertPath>
                                <KeyPath>/etc/letsencrypt/live/newtorrent.it/privkey.pem</KeyPath>
                                <ChainCertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</ChainCertPath>
				</TLS>
				
			</Host>

			

			

			
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>

							<Encodes>
								<Audio>
									<Name>bypass_audio</Name>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Name>bypass_video</Name>
									<Bypass>true</Bypass>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
								
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
						<RTSPPull />
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>32</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.5</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</LLHLS>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>

**Comment by getroot** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization
Use Authorization header like this

Authorization: Basic <credentials>

<credentials> is Base64(your AccessToken in Server.xml)

So if your `<AccessToke>` is ome-access-toke, `<credentials`> is b21lLWFjY2Vzcy10b2tlbg==

**Comment by lassos** [comment]
maybe it is the same like happened to me ? how do you call the api ? direct from server via curl ? or via web?

https://github.com/AirenSoft/OvenMediaEngine/issues/872

**Comment by annibal1** [comment]
via the web I wanted to find a solution
It is enough for me to understand when I transmit how many people are connected to streaming
that's all
I see that the configurations are not so simple
At least for me and quidi I kindly ask for help

**Comment by lassos** [comment]
it would be great if you do the call via browser to show us you console log. maybe there is something like cors error

**Comment by annibal1** [comment]
or if there is a SSH command
For me it's okay
however I am not able to create it
I deal with anything else I'm not a programmer

**Comment by lassos** [comment]
if you von to try from server ssh you could try something like this

curl -d '{ "id" : "1", }' -H 'Authorization: Basic b21lLWFjY2Vzcy10b2tlbg==' \
-H 'Content-Type: application/json' http://127.0.0.1:8081/v1/vhosts/default/apps/app:stopPush


ome-access-token = base64 encode -> b21lLWFjY2Vzcy10b2tlbg==

**Comment by annibal1** [comment]
This command you wrote to me from me from ssh does not work

**Comment by annibal1** [comment]
I see that it is very complicated to succeed in this operation for me
Better to leave it alone
But it would be nice to get the required result ... patience

**Comment by lassos** [comment]
my command was just an example, of yourse you have to put your url and path and your password

**Comment by annibal1** [comment]
yes
I type everything as you skipped as an example by changing 127.0.0.1 with my link but the SSH command did not work
is there any other thing to replace the example?
Thanks for your answers/help

**Comment by annibal1** [comment]
Sorry but wrapped with Google Translator I can't translate correctly and consequently I can't understand the solution
Attached my file confiring the interested party
I did not understand in access token what data I have to put
can you make me an example ??
thank you
	
	
	<Managers>
		<Host>
			<Names>
				<Name>newtorrent.it</Name>
			</Names>
			<TLS>
				<CertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</CertPath>
				<KeyPath>/etc/letsencrypt/live/newtorrent.it/privkey.pem</KeyPath>
				<ChainCertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</ChainCertPath>
			</TLS>
		</Host>
		<API>
			<AccessToken>b21lLWFjY2Vzcy10b2tlbg==</AccessToken>

			<CrossDomains>
				<Url>newtorrent.it</Url>
				
			</CrossDomains>
		</API>
	</Managers>
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>

			
			<Host>
				<Names>
					
					<Name>newtorrent.it</Name>
				</Names>
				
				<TLS>
				<CertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</CertPath>
                                <KeyPath>/etc/letsencrypt/live/newtorrent.it/privkey.pem</KeyPath>
                                <ChainCertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</ChainCertPath>
				</TLS>
				
			</Host>

**Comment by getroot** [comment]
<AccessToken>b21lLWFjY2Vzcy10b2tlbg==</AccessToken> ==>> <AccessToken>ome-access-token</AccessToken>

**Comment by annibal1** [comment]
Changed but always error :(


<Managers>
		<Host>
			<Names>
				<Name>newtorrent.it</Name>
			</Names>
			<TLS>
				<CertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</CertPath>
				<KeyPath>/etc/letsencrypt/live/newtorrent.it/privkey.pem</KeyPath>
				<ChainCertPath>/etc/letsencrypt/live/newtorrent.it/fullchain.pem</ChainCertPath>
			</TLS>
		</Host>
		<API>
			<AccessToken>ome-access-token</AccessToken>

			<CrossDomains>
				<Url>newtorrent.it</Url>
				
			</CrossDomains>
		</API>

**Comment by getroot** [comment]
How are you calling the API? Please explain in detail.

**Comment by annibal1** [comment]
I look at I was looking for only if there was a system to understand when I am streaming how many people are seeing streaming and I came across these bees that I am honestly going to attempts because following the various guides it is not so specified according to my opinion for users beginners with this software
or you have to be a programmer
It was enough to simply create a more detailed and simple guide to understand how to do or activate them if it was possible in the installation phase
has whole days that I try without any success
Better to leave it alone if for each modification there are all these complications to activate any script
Thanks anyway for your/your availability

**Comment by getroot** [comment]
That's sad. The API are functions provided for integration with other systems.

If you get a chance later, learn curl and try again.

curl -X GET https://newtorrent.it:8082/V1/Stats/Current/Vhosts/Default/Apps/App/Streams/stream -H "Authorization: Basic b21lLWFjY2Vzcy10b2tlbg=="
