### ISSUE TITLE
Edge Server - OvenMediaEngine

### ISSUE THREAD

**Issue by imrahuldevopser** [AirenSoft/OvenMediaEngine#876]
[09-01 06:17:26.375] E [SPllhls-T443:261600] OpenSSL | tls.cpp:193  | An error occurred while accept SSL connection: [OpenSSL] error:0A000416:SSL routines::sslv3 alert certificate unknown (167773206)
[09-01 06:17:26.375] I [SPllhls-T443:261600] HttpServer | http_server.cpp:220  | Client(<ClientSocket: 0x7fe2680011b0, #9, Disconnected, TCP, Nonblocking, 150.242.73.150:56440>) has disconnected from *:443
[09-01 06:17:27.384] I [SPllhls-T443:261600] HttpServer | http_server.cpp:146  | Client(<ClientSocket: 0x7fe2680011b0, #9, Connected, TCP, Nonblocking, 150.242.73.150:56441>) is connected o

**Comment by getroot** [comment]
When posting an issue, please upload Server.xml and the entire ovenmediaengine.log file. And in this case, you also need to tell me what URL you requested playback from.
You keep posting only part of the log. As I've mentioned so many times, with this information no one can ever figure out what the problem is.

**Comment by imrahuldevopser** [comment]
Server.xml -> edge server

<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
        <Name>OvenMediaEngine</Name>
        
        <Type>edge</Type>
        
        <IP>*</IP>
        <PrivacyProtection>false</PrivacyProtection>
        
        <StunServer>stun.l.google.com:19302</StunServer>

        <Modules>
                
                <HTTP2>
                        <Enable>true</Enable>
                </HTTP2>

                <LLHLS>
                        <Enable>true</Enable>
                </LLHLS>

                
                <P2P>
                        
                        <Enable>false</Enable>
                        <MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
                </P2P>
        </Modules>

        
        <Bind>
                
                
   <Providers>
                        
                        <OVT>
                                <WorkerCount>1</WorkerCount>
                        </OVT>
                </Providers>

                <Publishers>
                        <LLHLS>
                                
                                <Port>80</Port>
                                <TLSPort>443</TLSPort>
                                <WorkerCount>1</WorkerCount>
                        </LLHLS>
                        
                </Publishers>
        </Bind>
   
        

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>
                        
                        <Distribution>ovenmediaengine.com</Distribution>

                        
                        <Host>
                                <Names>
                                        
                                                <Name>ll-edge2.multitvsolution.com</Name>
                                                <Name>103.253.175.8</Name>
                                </Names>
                                
                                <TLS>
                                        <CertPath>/MTVSSL/a1d8f365164952f1.crt</CertPath>
                                        <KeyPath>/MTVSSL/multitv.key</KeyPath>
                                        <ChainCertPath>/MTVSSL/gd_bundle-g2-g1.crt</ChainCertPath>
                                </TLS>
                        </Host>

           

                        
                        <Origins>
                                <Properties>
                                        <NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
                                        <UnusedStreamDeletionTimeout>60000</UnusedStreamDeletionTimeout>
                                </Properties>
                                
                                <Origin>
                                        <Location>/app/</Location>
                                        <Pass>
                                                <Scheme>ovt</Scheme>
                                                <Urls>
                                                        <Url>122.176.117.232:9000/app/</Url>
                                                </Urls>
                                                
                                                <ForwardQueryParams>true</ForwardQueryParams>
                                        </Pass>
                                </Origin>
                        </Origins>

                        

                        <Applications>
                                <Application>
                                        <Name>app</Name>
                                        <Type>live</Type>
                                        <OutputProfiles>
                                                <OutputProfile>
                                                        <Name>passthrough</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>
                                                        <Encodes>
                                                                <Video>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                <Audio>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                        </Encodes>
                                                </OutputProfile>
                                        </OutputProfiles>
                                        <Providers>
                                                <OVT />
                                        </Providers>
                                        <Publishers>
                                                <AppWorkerCount>1</AppWorkerCount>
                                                <StreamWorkerCount>8</StreamWorkerCount>
                                           
                                                <LLHLS>
                                                        <ChunkDuration>0.5</ChunkDuration>
                                                        <SegmentDuration>6</SegmentDuration>
                                                        <SegmentCount>10</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </LLHLS>
                                        </Publishers>
                                </Application>
                        </Applications>

                </VirtualHost>
        </VirtualHosts>
</Server>
