### ISSUE TITLE
Rtmp input stream init meessage count over

### ISSUE THREAD

**Issue by ruifigueirinha** [AirenSoft/OvenMediaEngine#88]
When I try to restream an RTSP stream into an RTMP push I get multiple lines with this warning and the connection drops. This happens with ffmpeg and with happytimesoft.

**Comment by getroot** [comment]
Please let me get the warning messages of ovenmediaengine.log when connection is dropped. and sorry, I don't know well about happytimesoft.

**Comment by ruifigueirinha** [comment]
Here is the logfile that you asked. Thank you for the support.
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/4359904/ovenmediaengine.log)

**Comment by dimiden** [comment]
@ruifigueirinha 
This problem occurs when only audio or video is published.
Currently, OvenMediaEngine only supports streams with both audio and video tracks.

**Comment by ruifigueirinha** [comment]
@dimiden I understand but I tried to publish Video and Audio with ffmpeg and got the same result

**Comment by ruifigueirinha** [comment]
Nevermind, it works now. I just needed to add a silent audio channel to the rtsp stream of the ip camera. Thank you very much.
In case anyone is wondering about the command here it is:

ffmpeg -f lavfi -i anullsrc=channel_layout=stereo:sample_rate=44100 -rtsp_transport tcp -re -i rtsp://localhost:8554/live.sdp -c:v copy -c:a aac -map 0:a -map 1:v -f flv rtmp://localhost:1935/app/stream
