### ISSUE TITLE
No Recording 

### ISSUE THREAD

**Issue by rahulsharma1996** [AirenSoft/OvenMediaEngine#881]
<Publishers>

<FILE>
			<RootPath>/tmp</RootPath>
<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.mp4</FilePath>
			<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
</FILE>

</Publishers>

**Comment by wompapmow** [comment]
yes
