### ISSUE TITLE
OME file recording is not working

### ISSUE THREAD

**Issue by rahulsharma1996** [AirenSoft/OvenMediaEngine#882]

**Comment by getroot** [comment]
You created a duplicate issue with #881. You have to delete one.

https://airensoft.gitbook.io/ovenmediaengine/recording-experiment

Please refer to the manual and provide all information according to the issue template.

**Comment by rahulsharma1996** [comment]
Please tell me my questions... the issue is not resolved. please provide me a solution.

**Comment by getroot** [comment]
I don't know what you're doing wrong, how can I fix your problem? Do not erase the document template and provide all information. I've been telling you the rules of this community over and over again. I've been told several times to provide Server.xml, log files and a way to reproduce the problem. If you continue to break the rules, we will not respond to you.

**Comment by rahulsharma1996** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
        <Name>OvenMediaEngine</Name>
        
        <Type>origin</Type>
        
        <IP>*</IP>
        <PrivacyProtection>false</PrivacyProtection>

        
        <StunServer>stun.l.google.com:19302</StunServer>

        <Modules>
                
                <HTTP2>
                        <Enable>true</Enable>
                </HTTP2>

                <LLHLS>
                        <Enable>true</Enable>
                </LLHLS>

                
                <P2P>
                        
                        <Enable>false</Enable>
                        <MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
                </P2P>
                                                                                                                     1,38          Top
 </Modules>

        
        <Bind>
                
                

                <Providers>
                        
                        <RTSPC>
                                <WorkerCount>1</WorkerCount>
                        </RTSPC>
                        <OVT>
                                <WorkerCount>1</WorkerCount>
                        </OVT>
                        
                        <RTMP>
                                <Port>1935</Port>
                                <WorkerCount>1</WorkerCount>
                        </RTMP>
                        <SRT>
                                <Port>9999</Port>
                                <WorkerCount>1</WorkerCount>
                        </SRT>
                        <MPEGTS>
                                
                                <Port>4000/udp</Port>
                        </MPEGTS>
                        <WebRTC>
                                <Signalling>
                                        <Port>3333</Port>
                                        <TLSPort>3334</TLSPort>
                                        <WorkerCount>1</WorkerCount>
                                </Signalling>

                                <IceCandidates>
                                        <IceCandidate>*:10000-10005/udp</IceCandidate>
                                        
                                        <TcpRelay>*:3478</TcpRelay>
                                        
                                        <TcpForce>true</TcpForce>
                                        <TcpRelayWorkerCount>1</TcpRelayWorkerCount>
                                </IceCandidates>
                        </WebRTC>
                </Providers>

                <Publishers>
                        <LLHLS>
                                <Port>80</Port>
                                <TLSPort>443</TLSPort>
                                                                       <WorkerCount>1</WorkerCount>
                        </LLHLS>
                </Publishers>
        </Bind>

        
        

        <VirtualHosts>
                
                <VirtualHost include="VHost*.xml" />
                <VirtualHost>
                        <Name>default</Name>
                        
                        <Distribution>ovenmediaengine.com</Distribution>

                        
                        <Host>
                                <Names>
                                        <Name>ll-edge2.multitvsolution.com</Name>
                                </Names>
                                <TLS>
                                        <CertPath>/MTVSSL/a1d8f365164952f1.crt</CertPath>
                                        <KeyPath>/MTVSSL/multitv.key</KeyPath>
                                        <ChainCertPath>/MTVSSL/gd_bundle-g2-g1.crt</ChainCertPath>
                                </TLS>
                        </Host>

                        

                        

                        

                        
                        <Applications>
                                <Application>
                                        <Name>app</Name>
                                        
                                        <Type>live</Type>
                                        <OutputProfiles>
                                                
                                                <HardwareAcceleration>false</HardwareAcceleration>
                                                <OutputProfile>
                                                        <Name>bypass_stream</Name>
                                                        <OutputStreamName>${OriginStreamName}</OutputStreamName>

                                                        

                                                        <Encodes>
                                                                <Audio>
                                                               <Name>bypass_audio</Name>
                                                                        <Bypass>true</Bypass>
                                                                </Audio>
                                                                <Video>
                                                                        <Name>bypass_video</Name>
                                                                        <Bypass>true</Bypass>
                                                                </Video>
                                                                <Audio>
                                                                        <Codec>opus</Codec>
                                                                        <Bitrate>128000</Bitrate>
                                                                        <Samplerate>48000</Samplerate>
                                                                        <Channel>2</Channel>
                                                                </Audio>



                                                                <Video>
                                                                        <Name>video_1280</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>5024000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1920</Width>
                                                                        <Height>1280</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>
                                                                <Video>
                                                                        <Name>video_720</Name>
                                                                        <Codec>h264</Codec>
                                                                        <Bitrate>2024000</Bitrate>
                                                                        <Framerate>30</Framerate>
                                                                        <Width>1280</Width>
                                                                        <Height>720</Height>
                                                                        <Preset>faster</Preset>
                                                                </Video>

                                                        </Encodes>
                                                </OutputProfile>
                                        </OutputProfiles>
                                        <Providers>
                                                <OVT />
                                                <WebRTC />
                                                <RTMP />
                                                <SRT />
                                                <MPEGTS>
                                                        <StreamMap>
                                                                
                                                                <Stream>
                                                                        <Name>stream_${Port}</Name>
                                                                        <Port>4000</Port>
                                                                </Stream>
                                                        </StreamMap>
                                                </MPEGTS>
                                                <RTSPPull />
                                                <WebRTC>
                                                        <Timeout>30000</Timeout>
                                                </WebRTC>
                                        </Providers>
                                        <Publishers>
                                                <AppWorkerCount>1</AppWorkerCount>
                                                <StreamWorkerCount>8</StreamWorkerCount>
                                                <OVT />
                                        
                                                <LLHLS>
                                                        <ChunkDuration>0.5</ChunkDuration>
                                                        <SegmentDuration>6</SegmentDuration>
                                                        <SegmentCount>10</SegmentCount>
                                                        <CrossDomains>
                                                                <Url>*</Url>
                                                        </CrossDomains>
                                                </LLHLS>
                                                <RTMPPush>
                                                </RTMPPush>
                                                <MPEGTSPush>
                                                </MPEGTSPush>
                                                <FILE>
                                                        <RootPath>/tmp</RootPath>
                                                        <FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.mp4</FilePath>
                                                        <InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
                                                </FILE>
                                        </Publishers>
                                </Application>
                        </Applications>
                </VirtualHost>
        </VirtualHosts>
</Server>

**Comment by rahulsharma1996** [comment]
> I don't know what you're doing wrong, how can I fix your problem? Do not erase the document template and provide all information. I've been telling you the rules of this community over and over again. I've mentioned several times that you have to provide the Server.xml, log files and a way to reproduce the problem. If you continue to break the rules, we will not respond to you.

I mean to say i my streaming is running or stopped by me but not saved in my rootpath. so please provide the right path and right direction for saved recordings of my streaming. please provide solutions.

**Comment by getroot** [comment]
Solution is in the manual : https://airensoft.gitbook.io/ovenmediaengine/recording-experiment

What did you try to record? And why not upload the log file?

**Comment by rahulsharma1996** [comment]
> Solution is in the manual : https://airensoft.gitbook.io/ovenmediaengine/recording-experiment
 I  am adding the code mannually and run it successfull but recording is automatic or manual they can ask you. 

<FILE>
<RootPath>/tmp</RootPath>                                  <FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.mp4</FilePath>
<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
</FILE>

**Comment by getroot** [comment]
Why do you always delete all of your posts?
This is not polite.
