### ISSUE TITLE
Video on demand (VOD) 

### ISSUE THREAD

**Issue by Trungdo253** [AirenSoft/OvenMediaEngine#883]
Vod feature is not working yet. I always wait for it to be released. 
watch VODon HLS and WSS with ABR.
it would be interesting if it was released

**Comment by getroot** [comment]
WebRTC is not suitable for VoD. For example, there is no way to provide a seek function. And there's no reason to play VoD over a low-latency protocol. There are a lot of good solutions out there for VoD over HLS in the world. I think OvenMediaEngine would be good to continue focusing on low latency live streaming servers.

**Comment by Trungdo253** [comment]
yupp thank you very much !
