### ISSUE TITLE
Errors when broadcasting via Webrtc

### ISSUE THREAD

**Issue by albeliakov** [AirenSoft/OvenMediaEngine#886]
Broadcasting: WebRTC -> WebRTC with multiple resolutions.
Errors like this keep popping up in the log:
![image](https://user-images.githubusercontent.com/32854858/188949426-1cec2732-0124-4028-a1fa-1e640f7f9c7b.png)

**Comment by getroot** [comment]
Please let me know the detailed way to reproduce the problem.

**Comment by getroot** [comment]
Have you used OvenLiveKit?
What does "multiple resolutions" mean? And how do I do it?
What version of OvenMediaEngine is there?
etc. Please provide more information so I can reproduce the problem exactly.

**Comment by albeliakov** [comment]
@getroot 
- Used OvenLiveKit
- _What does "multiple resolutions" mean? And how do I do it?_ - multiple "Rendition" in "OutputProfile"
- verison is 0.14.7, Docker
- config file sent above
