### ISSUE TITLE
POST Recording json

### ISSUE THREAD

**Issue by lucachecha** [AirenSoft/OvenMediaEngine#890]
Hello!
I am trying to start recording and i have been guided by the POST example that in the manual provided. Howerver, I can´t start recording because the server that contains ovenmedia engine responses status code 400, and it says that the error comes from a bad request. 
I have been posting this json and I am not an expert so maybe I am typing something wrong. JSON:
               {                
                id = "custom",
                stream =
                {
                    name = "streamT",
                    tracks = "default"
                },
                filepath = "/home/administrador/file_${Sequence}.ts",
                infopath = "/home/administrador/file.xml",
                interval = 60000,
                segmentationRule = "continuity",
                }
I am sorry if it is a silly question but I am struggling to start recording and I don´t know what I am doing wrong, so if someone knows or can give a better example of how is the format of the JSON it would be a lot of help. Thanks!

**Comment by getroot** [comment]
json is in key:value format, not key=value.
For more information, see the json related documentation.
