### ISSUE TITLE
Specify Default Playlist Rendition Quality

### ISSUE THREAD

**Issue by Zibbp** [AirenSoft/OvenMediaEngine#891]
Hi, 
Is there a way to specify, either in the server config or player, a default playlist rendition quality? I'm using LLHLS with playlist quality renditions and the player defaults to "auto" and the lowest quality rendition possible. I can't seem to get the "auto" working as it will not switch to the higher quality rendition on a good internet connection. I can manually swap to the higher quality but would love to have that as the default or at least have the "auto" work. I tested this using the "THEO" player and the auto worked perfectly there.

I'm using the standard player configuration with type "hls" and the URL pointing to the playlist filename, in this case it is `abr.m3u8`.

![image](https://user-images.githubusercontent.com/21207065/189948722-5bf4985f-edd7-448c-9409-e740c2d8bb40.png)

Playlist config:
```
<OutputProfile>
    <Name>default</Name>
    <OutputStreamName>${OriginStreamName}</OutputStreamName>

    <Playlist>
        <Name>llhls</Name>
        <FileName>abr</FileName>
        <Rendition>
            <Name>Bypass</Name>
            <Video>bypass_video</Video>
            <Audio>bypass_audio</Audio>
        </Rendition>
        <Rendition>
            <Name>720p</Name>
            <Video>video_720p</Video>
            <Audio>bypass_audio</Audio>
        </Rendition>
    </Playlist>



    <Encodes>
        <Video>
            <Name>bypass_video</Name>
            <Bypass>true</Bypass>
        </Video>

        <Video>
            <Name>video_720p</Name>
            <Codec>h264</Codec>
            <Width>1280</Width>
            <Height>720</Height>
            <Bitrate>2000000</Bitrate>
            <Framerate>30</Framerate>
        </Video>
        <Audio>
            <Name>bypass_audio</Name>
            <Bypass>True</Bypass>
        </Audio>
        <Audio>
            <Name>aac</Name>
            <Codec>aac</Codec>
            <Bitrate>128000</Bitrate>
            <Samplerate>48000</Samplerate>
            <Channel>2</Channel>
        </Audio>
    </Encodes>
</OutputProfile>
```

**Comment by getroot** [comment]
This seems to be an issue with hls.js . Could you please move the issue to the OvenPlayer repo?
