### ISSUE TITLE
Getting error duplicate stream

### ISSUE THREAD

**Issue by lassos** [AirenSoft/OvenMediaEngine#894]
hello, if i connect first time obs to media server everything is fine. aber disconnect und reconnect following message appears:

`{"log":"\u001b[37m[2022-09-21 06:37:11.244] I [SPRTMP-T1935:29] Provider | stream.cpp:48   | Unknown/(37) has been started stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:11.244446327Z"}
{"log":"\u001b[37m[2022-09-21 06:37:11.244] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:152  | A RTMP client has connected from \u003cClientSocket: 0x7f3304001310, #37, Connected, TCP, Nonblocking, 172.17.0.1:54912\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:11.24449111Z"}
{"log":"\u001b[37m[2022-09-21 06:37:12.938] I [SPRTMP-T1935:29] RTMPProvider | rtmp_application.cpp:42   | Reject #default#app/stream stream it is a stream with a duplicate name.\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:12.939237695Z"}
{"log":"\u001b[37m[2022-09-21 06:37:12.939] I [SPRTMP-T1935:29] Provider | stream.cpp:63   | Unknown/stream(37) has been stopped playing stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:12.939688203Z"}
{"log":"\u001b[91m[2022-09-21 06:37:12.939] E [SPRTMP-T1935:29] RTMPProvider | rtmp_stream.cpp:1190 | Input create fail -  stream(#default#app/stream)\u001b[0m\n","stream":"stderr","time":"2022-09-21T06:37:12.939711642Z"}
{"log":"\u001b[37m[2022-09-21 06:37:12.939] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:179  | The RTMP client has disconnected: [Unknown/stream], remote: \u003cClientSocket: 0x7f3304001310, #37, Closed, TCP, Nonblocking, 172.17.0.1:54912\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:12.939848457Z"}
{"log":"\u001b[37m[2022-09-21 06:37:23.767] I [SPRTMP-T1935:29] Provider | stream.cpp:48   | Unknown/(37) has been started stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:23.767595713Z"}
{"log":"\u001b[37m[2022-09-21 06:37:23.767] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:152  | A RTMP client has connected from \u003cClientSocket: 0x7f3304001310, #37, Connected, TCP, Nonblocking, 172.17.0.1:54920\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:23.767642285Z"}
{"log":"\u001b[37m[2022-09-21 06:37:25.424] I [SPRTMP-T1935:29] RTMPProvider | rtmp_application.cpp:42   | Reject #default#app/stream stream it is a stream with a duplicate name.\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:25.424367957Z"}
{"log":"\u001b[91m[2022-09-21 06:37:25.424] E [SPRTMP-T1935:29] RTMPProvider | rtmp_stream.cpp:1190 | Input create fail -  stream(#default#app/stream)\u001b[0m\n","stream":"stderr","time":"2022-09-21T06:37:25.424791653Z"}
{"log":"\u001b[37m[2022-09-21 06:37:25.424] I [SPRTMP-T1935:29] Provider | stream.cpp:63   | Unknown/stream(37) has been stopped playing stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:25.42482349Z"}
{"log":"\u001b[37m[2022-09-21 06:37:25.424] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:179  | The RTMP client has disconnected: [Unknown/stream], remote: \u003cClientSocket: 0x7f3304001310, #37, Closed, TCP, Nonblocking, 172.17.0.1:54920\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:25.425058304Z"}
{"log":"\u001b[37m[2022-09-21 06:37:36.236] I [SPRTMP-T1935:29] Provider | stream.cpp:48   | Unknown/(37) has been started stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:36.23725067Z"}
{"log":"\u001b[37m[2022-09-21 06:37:36.237] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:152  | A RTMP client has connected from \u003cClientSocket: 0x7f3304001310, #37, Connected, TCP, Nonblocking, 172.17.0.1:54924\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:36.237300563Z"}
{"log":"\u001b[37m[2022-09-21 06:37:37.910] I [SPRTMP-T1935:29] RTMPProvider | rtmp_application.cpp:42   | Reject #default#app/stream stream it is a stream with a duplicate name.\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:37.910952613Z"}
{"log":"\u001b[91m[2022-09-21 06:37:37.911] E [SPRTMP-T1935:29] RTMPProvider | rtmp_stream.cpp:1190 | Input create fail -  stream(#default#app/stream)\u001b[0m\n","stream":"stderr","time":"2022-09-21T06:37:37.91137939Z"}
{"log":"\u001b[37m[2022-09-21 06:37:37.911] I [SPRTMP-T1935:29] Provider | stream.cpp:63   | Unknown/stream(37) has been stopped playing stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:37.911408316Z"}
{"log":"\u001b[37m[2022-09-21 06:37:37.911] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:179  | The RTMP client has disconnected: [Unknown/stream], remote: \u003cClientSocket: 0x7f3304001310, #37, Closed, TCP, Nonblocking, 172.17.0.1:54924\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:37.911797969Z"}
{"log":"\u001b[37m[2022-09-21 06:37:48.736] I [SPRTMP-T1935:29] Provider | stream.cpp:48   | Unknown/(37) has been started stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:48.736683453Z"}
{"log":"\u001b[37m[2022-09-21 06:37:48.736] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:152  | A RTMP client has connected from \u003cClientSocket: 0x7f3304001310, #37, Connected, TCP, Nonblocking, 172.17.0.1:54926\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:48.741248013Z"}
{"log":"\u001b[37m[2022-09-21 06:37:50.416] I [SPRTMP-T1935:29] RTMPProvider | rtmp_application.cpp:42   | Reject #default#app/stream stream it is a stream with a duplicate name.\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:50.416516464Z"}
{"log":"\u001b[37m[2022-09-21 06:37:50.416] I [SPRTMP-T1935:29] Provider | stream.cpp:63   | Unknown/stream(37) has been stopped playing stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:50.416940214Z"}
{"log":"\u001b[91m[2022-09-21 06:37:50.416] E [SPRTMP-T1935:29] RTMPProvider | rtmp_stream.cpp:1190 | Input create fail -  stream(#default#app/stream)\u001b[0m\n","stream":"stderr","time":"2022-09-21T06:37:50.416982415Z"}
{"log":"\u001b[37m[2022-09-21 06:37:50.417] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:179  | The RTMP client has disconnected: [Unknown/stream], remote: \u003cClientSocket: 0x7f3304001310, #37, Closed, TCP, Nonblocking, 172.17.0.1:54926\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:37:50.417249541Z"}
{"log":"\u001b[37m[2022-09-21 06:39:14.630] I [SPRTMP-T1935:29] Provider | stream.cpp:48   | Unknown/(37) has been started stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:39:14.631279304Z"}
{"log":"\u001b[37m[2022-09-21 06:39:14.631] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:152  | A RTMP client has connected from \u003cClientSocket: 0x7f3304001310, #37, Connected, TCP, Nonblocking, 172.17.0.1:54936\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:39:14.631337109Z"}
{"log":"\u001b[37m[2022-09-21 06:39:16.367] I [SPRTMP-T1935:29] RTMPProvider | rtmp_application.cpp:42   | Reject #default#app/stream stream it is a stream with a duplicate name.\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:39:16.36804204Z"}
{"log":"\u001b[91m[2022-09-21 06:39:16.368] E [SPRTMP-T1935:29] RTMPProvider | rtmp_stream.cpp:1190 | Input create fail -  stream(#default#app/stream)\u001b[0m\n","stream":"stderr","time":"2022-09-21T06:39:16.368454808Z"}
{"log":"\u001b[37m[2022-09-21 06:39:16.368] I [SPRTMP-T1935:29] Provider | stream.cpp:63   | Unknown/stream(37) has been stopped playing stream\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:39:16.368497356Z"}
{"log":"\u001b[37m[2022-09-21 06:39:16.368] I [SPRTMP-T1935:29] RTMPProvider | rtmp_provider.cpp:179  | The RTMP client has disconnected: [Unknown/stream], remote: \u003cClientSocket: 0x7f3304001310, #37, Closed, TCP, Nonblocking, 172.17.0.1:54936\u003e\u001b[0m\n","stream":"stdout","time":"2022-09-21T06:39:16.368762407Z"}
`

so obs will try to reconnect . only solution is to restart docker.

**Comment by getroot** [comment]
Please provide the full log file (/var/log/ovenmediaengine/ovenmediaengine.log) and as much information as the form asks for.
