### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by lkinfotechai** [AirenSoft/OvenMediaEngine#895]
Hi Team

i want to restream 50 ip camera outside and inside network. i have rtsp stream of all the cameras.
>> can i use this engine on windows?
>> any idea how much cpu resources it will take for restream of single ip cam?
>> is LLHLS takes very less memory

please help me

**Comment by getroot** [comment]
The basics can be found in the manual.
https://airensoft.gitbook.io/ovenmediaengine/

CPU/memory usage depends on your settings and your environment. Try it yourself.
