### ISSUE TITLE
 Screen is blank when using three OME play 

### ISSUE THREAD

**Issue by 2k9laojia** [AirenSoft/OvenMediaEngine#90]
Hi，I have a trouble 。First,I push one RTMP streaming to OME service and use bypass. Second I open 
one OvenPlayer which play stream. It is OK. Last I open another OvenPlayer which play same stream. the screen is OK. But I open three OvenPlayer which play same stream,the scree is black. At the same time , another two oven player which screen is stuck .  When I close the three oven player, another two oven player is OK.  Could tell me what is wrong?      thank you. Need config cache？
![1](https://user-images.githubusercontent.com/26626078/77291935-2ffe6580-6d1a-11ea-940a-64047a6a4986.png)

OME Service Version: dev
OvenPlayer Version: 0.9

**Comment by 2k9laojia** [comment]
![1](https://user-images.githubusercontent.com/26626078/77292202-cc286c80-6d1a-11ea-8342-6358c08fb116.jpg)

Is it related to Chrome  browser memory ？Chrome memory is 600MB and my PC memory is 8G
![Chrome](https://user-images.githubusercontent.com/26626078/77292402-2f1a0380-6d1b-11ea-81cd-4989e969043f.jpg)

**Comment by getroot** [comment]
We always test with several players, but we have never experienced this. If you play with 2 players and try to play additionally on another PC or mobile, does it play?

**Comment by dimiden** [comment]
@2k9laojia 
And, what protocol are you using?

**Comment by 2k9laojia** [comment]
protocol: WebRTC
I know the problem。I do a test . When I deploy OME service in a virtual machine and oven play also is the same PC. In order to exclude network affect，using local host communicate between service and play.  So, many oven play run normally. So the problem is rtp packet loss . It leads to the oven play can not decode. So the screen is black. I am looking forward to support NACK. thank you!

**Comment by getroot** [comment]
We have completed the development of NACK and RTP retransmission and released it to the master branch. If you are still interested in this issue, you can test it with the master branch.
