### ISSUE TITLE
OME Crashes When Ingesting HEVC Stream

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#900]
**Describe the bug**
![Screenshot_2022-09-29_13-37-51](https://user-images.githubusercontent.com/3529698/193141312-f1357985-618a-4d6d-a729-650b85a450bb.png)

**To Reproduce**
I am using OBS git (for the recent [nvenc refactor](https://github.com/obsproject/obs-studio/commit/5c9e620315b0974b08af75e1364821c8f3ffcc4b)) to reproduce this crash.
Setup OBS to use SRT and HEVC
Click "Start Streaming" from OBS, and OME crashes.

**Expected behavior**
No crash using HEVC.

**Logs**
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9679083/ovenmediaengine.log)

**Server (please complete the following information):**
 - OS: Debian 11.5 container on Proxmox

 - OvenMediaEngine Version: 20fe70103a010aae7aa306e055074ea0c015eace + #782

**Additional context**
Testing HEVC using OBS v28.0.3 does not cause a crash, but also does not begin ingesting the video.  H.264 ingestion works fine in v28.0.3 and in git.
I am using nvdec hardware acceleration
I am using Bypass audio with 6 audio tracks
I am using an additional OBS patch to enable multi-audio streaming with SRT
Here is the Application section of my config:

> 				<Application>
> 					<Name>hw60</Name>
> 					
> 					<Type>live</Type>
> 					<OutputProfiles>
> 						
> 						<HardwareAcceleration>true</HardwareAcceleration>
> 						<OutputProfile>
> 							<Name>bypass_stream</Name>
> 							<OutputStreamName>${OriginStreamName}</OutputStreamName>
> 							<Encodes>
> 								<Video>
> 									<Bypass>true</Bypass>
> 								</Video>
> 								<Audio>
> 									<Bypass>true</Bypass>
> 								</Audio>
> 							</Encodes>
> 						</OutputProfile>
> 						<OutputProfile>
> 							<Name>1440p60</Name>
> 							<OutputStreamName>${OriginStreamName}_1440p60</OutputStreamName>
> 							<Encodes>
> 								<Video>
> 									<Codec>h264</Codec>
> 									<Bitrate>50000000</Bitrate>
> 									<Framerate>60</Framerate>
> 									<Width>2560</Width>
> 									<Height>1440</Height>
> 									<Preset>slow</Preset>
> 									<Profile>high</Profile>
> 									<Tune>hq</Tune>
> 								</Video>
> 								<Audio>
> 									<Bypass>true</Bypass>
> 								</Audio>
> 							</Encodes>
> 						</OutputProfile>
> 						<OutputProfile>
> 							<Name>1080p60</Name>
> 							<OutputStreamName>${OriginStreamName}_1080p60</OutputStreamName>
> 							<Encodes>
> 								<Video>
> 									<Codec>h264</Codec>
> 									<Bitrate>8000000</Bitrate>
> 									<Framerate>60</Framerate>
> 									<Width>1920</Width>
> 									<Height>1080</Height>
> 									<Preset>slower</Preset>
> 									<Profile>high</Profile>
> 									<Tune>hq</Tune>
> 								</Video>
> 								<Audio>
> 									<Bypass>true</Bypass>
> 								</Audio>
> 							</Encodes>
> 						</OutputProfile>
> 					</OutputProfiles>
> 					<Providers>
> 						<OVT />
> 						<WebRTC />
> 						<RTMP />
> 						<SRT />
> 						<MPEGTS>
> 							<StreamMap>
> 								
> 								<Stream>
> 									<Name>stream_${Port}</Name>
> 									<Port>4000</Port>
> 								</Stream>
> 							</StreamMap>
> 						</MPEGTS>
> 						<RTSPPull />
> 						<WebRTC>
> 							<Timeout>30000</Timeout>
> 						</WebRTC>
> 					</Providers>
> 					<Publishers>
> 						<AppWorkerCount>4</AppWorkerCount>
> 						<StreamWorkerCount>8</StreamWorkerCount>
> 						<OVT />
> 						<RTMPPush></RTMPPush>
> 						<FILE>
> 							<RootPath>/mnt/media/OME</RootPath>
> 							<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
> 							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
> 						</FILE>
> 						<WebRTC>
> 							<Timeout>30000</Timeout>
> 							<Rtx>false</Rtx>
> 							<Ulpfec>false</Ulpfec>
> 							<JitterBuffer>false</JitterBuffer>
> 						</WebRTC>
> 						<HLS>
> 							<SegmentDuration>5</SegmentDuration>
> 							<SegmentCount>3</SegmentCount>
> 							<CrossDomains>
> 								<Url>*</Url>
> 							</CrossDomains>
> 						</HLS>
> 						<LLHLS>
> 							<ChunkDuration>0.2</ChunkDuration>
> 							<SegmentDuration>6</SegmentDuration>
> 							<SegmentCount>10</SegmentCount>
> 							<CrossDomains>
> 								<Url>*</Url>
> 							</CrossDomains>
> 						</LLHLS>
> 					</Publishers>
> 				</Application>

**Comment by getroot** [comment]
Thanks for the report. I'll try to reproduce this issue and fix it in a few days.

**Comment by getroot** [comment]
I haven't tested the latest version of OBS's GIT because I couldn't compile it. Can you provide this?

And in version 28.0.3, the video does not start when HEVC is selected. This is because OBS is not sending HEVC's SPS packet. It is possible that this is a bug in OBS or that OBS is using a different specification for HEVC packaging. If you have any documents or data related to this specification, please share.

**Comment by krakow10** [comment]
I looked online to see if there was a guide to cross compile OBS but I didn't find something that looked promising, so I don't think I can provide a build other than the one I'm using for Arch Linux.  I am using [this AUR package](https://aur.archlinux.org/packages/obs-studio-tytan652) edited to build from master branch (replace `#tag=$pkgver` with `#branch=master`) to build OBS git.  Reviewing the current state of OBS development, that nvenc refactor patch is also a part of this [nvenc-av1](https://github.com/obsproject/obs-studio/tree/nvenc-av1) branch, so testing the patch from master may have been premature.  Perhaps this issue should be revisited when OBS contains the nvenc refactor properly if the issue persists, which I will assuredly test and report my findings.

**Comment by flaeri** [comment]
@getroot Hello :)
I've tested SRT + AMF (AMD) HEVC via OBS to my OvenMediaServer, and the logs say they can't parse the SPS.
```
2022-10-06 08:57:59.751] E [SPSRT-T9999:2106536] MpegtsProvider | mpegts_stream.cpp:168  | Could not parse sps
[2022-10-06 08:57:59.751] E [InboundWorker:2106540] MediaRouter | mediarouter_stream.cpp:608  | Could not parse H265 SPS Unit
```
However, I believe they are present, and it's likely down to a diff in the packaging (as you noted). I am not knowledgeable enough in this field to be able to confidently inspect and compare what OvenMedia is doing vs what is produced, but maybe this will give some insight.
![image](https://user-images.githubusercontent.com/50419942/194259119-ce9a8973-9f98-4110-83ac-d8a5a53f2ca3.png)

I've also attached a TS with said contents if that will be of help.
[hevcExmaple.zip](https://github.com/AirenSoft/OvenMediaEngine/files/9722586/hevcExmaple.zip)

**Comment by getroot** [comment]
@krakow10 @flaeri 
Thanks for providing good information.

I think I should share some background knowledge first.

OvenMediaEngine does not yet do HEVC packaging in LLHLS or WebRTC. OME's WebRTC supported HEVC in the past, but it has not been maintained since then, as only the experimental version of Safari at the time supported it, and most browsers don't support HEVC (they probably won't support HEVC in the future). It probably doesn't work right now. And OME's LLHLS does not yet support HEVC and will be added.

In the past, HEVC encoding was supported using the x265 library, but now the HEVC encoding function has been deprecated because x265 cannot be used due to license conflicts.

Even if HEVC is input from OBS's SRT, it must be encoded in AVC to use it in the current OvenMediaEngine. Therefore, we will look at this issue together when LLHLS supports HEVC in the future.

**Comment by krakow10** [comment]
I've tested this again and OME still crashes ingesting HEVC with hardware decoding.  None of my output streams are configured to encode in HEVC, and OME was able to decode+ingest an HEVC stream without crashing in the past, but now that OBS can stream HEVC without crashing itself OME is the one crashing.  Always issues trying to use video technology that's non-H.264 😉
