### ISSUE TITLE
Regression: Slow Startup for RTMP Push

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#901]
**Describe the bug**
OME takes up to 30 seconds to start up and normalize when previously it was almost instantaneous.  I don't think this happened back around v0.14.3, neither encode or decode would hit 100%, and I would not have to wait for OME to normalize to see the stream start.

Here is a recording of `nvtop`, a terminal application to monitor GPU utilization:

https://user-images.githubusercontent.com/3529698/193143324-16ba59cf-38ea-4199-ae37-14e81c7d7369.mp4

**To Reproduce**
1. Use latest version of OME with nvidia hardware acceleration enabled
2. Start streaming and set up RTMP Push, stop streaming but don't clear RTMP Pushes
3. Begin streaming again, observe how long it takes for the stream to show up on the live service

**Expected behavior**
Streaming begins within a few seconds.

**Additional context**
I have bisected the issue and discovered that this is caused by the ffmpeg version upgrade:
[64040091ba18a19c888f1c2307a74af554442ea6] Change FFmpeg 4.4.1 to 5.0.1

**Comment by getroot** [comment]
I have failed to understand this issue.
What program was that video recorded? What protocol does ingest use? What encoder did you use?

**Comment by krakow10** [comment]
I've changed the steps to reproduce to include more information, sorry about that.  To be clear, this issue only happens when beginning to ingest.  If the ingest has been running for 30 seconds before RTMP Push starts, the stream goes live immediately.
The recording is of a terminal gpu monitor called nvtop which shows encoder usage.  I am ingesting using SRT with H.264 from OBS, though I suspect it will occur for more configurations.

**Comment by getroot** [comment]
What keyframe interval is set in your encoder? Since RTMP Push starts from the key frame, the problem can be reproduced if the keyframe interval is long.

**Comment by krakow10** [comment]
The keyframe interval was set to automatic, so I set it to 1 second and tested again.  I am seeing the same result.  On a different note, the encoder is at 75% usage normally which is quite a heavy workload (because of my resolution and framerate which is 1440p 120fps input and 1440p 60fps + 1080p 60fps output).  What happens if you test with 4k 60fps to put a high load on the encoder?  Perhaps you would not see it take this long for 1080p, but the catch-up is exaggerated for heavier workloads.

**Comment by getroot** [comment]
Please upload your Server.xml and full ovenmediaengine.log. 
Do you stream to YouTube with RTMP Push?

**Comment by krakow10** [comment]
[Server.xml.log](https://github.com/AirenSoft/OvenMediaEngine/files/9681124/Server.xml.log)
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9681125/ovenmediaengine.log)
I am streaming to both YouTube (1440p60) and Twitch (1080p60) with RTMP Push.  If there is a way to stream to YouTube with HLS using HEVC I would love to do that.

**Comment by getroot** [comment]
You set the encoding bitrate to 60M and 50M, which is too high a bitrate for the streaming server to handle. Is your server hardware performance good enough? The log file you uploaded also shows a lot of queue overflow logs that appear when the server performance is insufficient.

Does setting it to 6M/5M reproduce the problem?

**Comment by getroot** [comment]
If your server has very good performance, try increasing the ThreadCount of the encoding profile.

Example
```
<Video>
	<Codec>h264</Codec>
	<Bitrate>60000000</Bitrate>
	<Framerate>60</Framerate>
	<Width>2560</Width>
	<Height>1440</Height>
	<Preset>slow</Preset>
	<Profile>high</Profile>
	<Tune>hq</Tune>
	<ThreadCount>8<ThreadCount>
</Video>
```

**Comment by krakow10** [comment]
Maybe that can alleviate some of the crashes I get streaming for long periods, thanks!  Unfortunately the slow startup issue persists.  I tried lowering the bitrate to 4mbps and setting the thread count to 8 but the encoder usage still spikes to 100% for around 20 seconds which did not occur before around ~v0.14.3 with the same settings.

**Comment by getroot** [comment]
Before 0.14.3 and in the latest version, the encoding side has not changed much. This is because h.264 encoding relies on external software (openh264).
Maybe you're using a higher CPU because your input quality was changed so high? You can check which threads are using the most CPU with top -H . If the decoding thread is CPU intensive, it is because the input quality is too high. Or options like <Preset>slow</Preset> you set also use very high cpu. It looks like this will have to be tested by changing several options.

**Comment by krakow10** [comment]
Isn't cpu decoding irrelevant?  I'm using an nvidia GTX 1660 Super for hardware decoding and encoding.  Sorry if I didn't communicate that clearly, I assumed nvtop gpu monitor would imply hardware encoding.

I've got OME v0.13.2 installed now and observed this behaviour:

https://user-images.githubusercontent.com/3529698/193216396-1c2044df-1b30-47b4-bc87-d4c34b23c36d.mp4

I'm going to attempt my very first git bisect, good luck to me!

**Comment by getroot** [comment]
Oh, you're using a hardware encoder. I'm sorry I didn't look carefully.

I don't know if it has anything to do with the performance of the hardware encoder depending on the version of OvenMediaEngine. I will pass this on to the person in charge. @Keukhan

**Comment by krakow10** [comment]
Big OOF!  I spend the past 2 hours tracking down the regression to the ffmpeg version upgrade!

quat@ovenmediaengine:~/OMEbisect$ git bisect bad 
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[64040091ba18a19c888f1c2307a74af554442ea6] Change FFmpeg 4.4.1 to 5.0.1
