### ISSUE TITLE
How can I play ts files after recording.

### ISSUE THREAD

**Issue by LordOfCinder2000** [AirenSoft/OvenMediaEngine#904]

**Comment by krakow10** [comment]
Use a video player such as MPV or VLC.  There is also the recently added feature #902 if you know how to set it up.

**Comment by LordOfCinder2000** [comment]
Thanks @krakow10, what is the url to play it.

**Comment by krakow10** [comment]
It looks like you configure it yourself, so whatever you configure it to be.

**Comment by LordOfCinder2000** [comment]
Can you give me an example. I am new to OME.

**Comment by krakow10** [comment]
I don't know how the VoD Service feature works, nor have I set it up, it was added 3 days ago.  If you don't want to set up the VoD Service you can simply transfer the file however you like and play it with a video player.  I have access to the recordings using a network mount:
![image](https://user-images.githubusercontent.com/3529698/193483350-04472826-e6ce-4d6e-af91-0acb7f5ae492.png)

**Comment by LordOfCinder2000** [comment]
Thank you for your help !
