### ISSUE TITLE
HLS Push Publishing

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#905]
**Is your feature request related to a problem? Please describe.**
I want to stream to YouTube with NVENC HEVC.

**Describe the solution you'd like**
HLS Push Publishing, similar to RTMP Push Publishing

**Describe alternatives you've considered**
RTMP(S) with a higher bitrate is also a valid solution, but OME drops 1/3rd of video when pushing 80mbps to YouTube.

**Additional context**
Does this make sense for OME?  It's not a pressing issue, it's just something that I thought could potentially be easy to add because of the existing HLS and RTMP Push Publishing features.

YouTube docs:
https://developers.google.com/youtube/v3/live/guides/ingestion-protocol-comparison

**Comment by json-m** [comment]
refer to https://github.com/AirenSoft/OvenMediaEngine/issues/869#issuecomment-1231032348 for HEVC.

**Comment by krakow10** [comment]
Hardware encoding sidesteps such licensing issues, and this is a feature request for HLS Push Publishing.
