### ISSUE TITLE
RTMP Push Publishing with a Twitch Vod Audio Track

### ISSUE THREAD

**Issue by krakow10** [AirenSoft/OvenMediaEngine#906]
**Is your feature request related to a problem? Please describe.**
I would like to use use Twitch's vod audio track feature to stream an additional audio track without music.

**Describe the solution you'd like**
The Twitch vod audio track is simply an additional audio track for a total of two audio tracks.  If I recall correctly, this is technically out-of-spec for RTMP/FLV, but is a natural extension of the protocol.

**Describe alternatives you've considered**
No alternative that I know of.  Currently twitch vods on my channel remain unpublished and inaccessible to viewers because of the threat of copyrighted audio.  With this feature, vods are saved with an alternate audio track and can be published and browsable, as well as being able to view a stream vod that a twitch clip originates from.

**Additional context**
Here is a relevant commit I found from the file history for obs-studio/plugins/obs-outputs/flv-output.c in OBS:
[Add support for metadata-based multitrack](https://github.com/obsproject/obs-studio/commit/189fc7ab6aa6280c0faee6559833a71357e92d61)

**Comment by erickskrauch** [comment]
I just found this issue and I'm integrated in this feature too.
