### ISSUE TITLE
Amazon Cloudfront best practice for caching?

### ISSUE THREAD

**Issue by angreebeaver** [AirenSoft/OvenMediaEngine#908]
Hello and thanks for this great software!

I wonder what are the best settings for caching (Minimum TTL, Maximum TTL, Default TTL) in CloudFront for LLHLS? What is best practice to get a caching effect without increasing latency to much? For my understanding there is no big time window and caching seems a bit difficult when everything happens in 1-2 seconds. What is your experience with this?

**Comment by angreebeaver** [comment]
Thank you. If if interpret the code right (I'm no developer) it's based on chunk size.
With default configuration I see on playlists a max-age of 2 and on chunks there is no max-age. (developer tools in Chrome)
So, every two seconds playlists are pulled again from OME. Chunks need no cache-settings because filenames changing all the time and therefore there's no problem with outdated information. Am I right? Please correct me if I'm wrong.

But the thing is, CloudFront, and I suspect most CDNs, have it's own [caching mechanism.](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html)
Browsers relies on http header information like max-age but the CDN also looks for it's Minimum, Default an Max TTL settings and based on this decides if it's necessary to pull information from Origin (OME) again or using cached information inside CDN. Normally you want to have a high cache hit rate to avoid traffic to origin. But because everything is so fast outdated I wonder what could be a good setting.

**Comment by getroot** [comment]
I have experience with CloudFront integration. Normally, if the CDN operates with the default setting, the cache policy follows the policy contained in the cache-control header that the origin server responds to.

Specifically, the policy is as follows: It would be good to check the LLHLS specification for details.

**Master (or Multivariant) Playelist (eg llhls.m3u8)**
forever cacheable

**Chunk Playlist (eg chunklist_2_video.m3u8)**
not cacheable

**Chunk Playlist with directive (eg chunklist_2_video.m3u8?_HLS_msn=13&_HLS_part=5)**
`<SegmentCount> * <SegmentDuration>` seconds is sufficient to cache

**Segment File (eg seg_2_7_video_mXgZYbj7_llhls.m4s)**
`<SegmentCount> * <SegmentDuration>` seconds is sufficient to cache

**Partial Segment File (eg part_0_7_2_video_SJqh2CNf_llhls.m4s)**
`<SegmentDuration> * 3` seconds of cache is sufficient

**Comment by angreebeaver** [comment]
Thanks for you fast and detailed explanation. I will have a look in the hls specification.
In CloudFront I had no luck with default settings and default caching policy which should be "Managed-CachingOptimized".
It doesn't forwards Query strings (Query strings - None) and so playback wasn't possible. I had to change this.
In this policy Minimum TTL is set to 1 so if Cache-Control: max-age is higher (what should be the case in my understanding) "CloudFront caches the object for the value of the Cache-Control: max-age directive." (from CloudFront documentation). I think thats fine.

Does every file type, which OME serves, should have a caching policy attached based on calculations of your last post? So "The origin does not add a Cache-Control: max-age directive to the object" (from CloudFront doc) does never apply for OME? I'm asking because I didn't see max-age in other files than playlists in Chrome developer tools.

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/194037275-483b069f-c471-4eaf-b238-b3583ab7b880.png)
![image](https://user-images.githubusercontent.com/17779085/194037298-dfee4dcb-fd86-4a29-abbd-7a0af4a31706.png)
![image](https://user-images.githubusercontent.com/17779085/194037321-97ceebed-d70f-4f06-962e-2623739e5ea3.png)

OME responds by putting the cache-control policy in the response header only when necessary. The reason that the cache-control header is not included in the segment or partial segment is because it can be cached according to the CDN policy.

**Comment by angreebeaver** [comment]
Thank you for your extraordinary support. I really appreciate it.
I try to use all this information and do further testing.
I have to find out whats the best way to tell CloudFront that it should do caching like set in headers. As you suggested. I am not sure if default policy "Managed-CachingOptimized" is the right way to go.

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/203995076-470fec39-539a-4c2c-928c-29bc2f094357.png)
![image](https://user-images.githubusercontent.com/17779085/203995099-b920b69d-35cd-44f5-9b9c-683e9154957d.png)

These are my Cache policy and Origin request policy.
