### ISSUE TITLE
Thumbnails fill server memory until crash

### ISSUE THREAD

**Issue by benj0r** [AirenSoft/OvenMediaEngine#909]
I'm running the engine on an Ubunut Server 20.04.1 LTS. Everything is working fine but the Image Encoder seems to have a Problem.

If i use it to publish thumbnails it works but it fills first the memory of the server, then the swap and after this the engine is crashing.

Is there any way to clear the old thumbnails or do they stay ther forever? the only way is to stop the specific stream or to restart the engine? Should they stay in memory, did i miss something in my config or is this a bug?

**Comment by getroot** [comment]
Please provide the information requested in the issue form.
Please tell us which version of OvenMediaEngine you are using, and upload the entire file, Server.xml and ovenmediaengine.log, which contains a log of when the problem occurred.

**Comment by benj0r** [comment]
See Server.xml code below. The log shows nothing but inital errors during testing after installation. There is no error before crashing or restarting. 

The Version of OvenMediaEngine is v0.14.10. The installation is just a few days old.


`<?xml version="1.0" encoding="UTF-8"?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>

	
	<StunServer>${PublicIP}</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>
	</Modules>

	
	<Bind>
		
		

		<Providers>
			<RTMP>
				<Port>1935</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>9999</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
		</Providers>

		<Publishers>
			<Thumbnail>
				<Port>80</Port>
				<TLSPort>443</TLSPort>
			</Thumbnail>
			<LLHLS>
				
				<Port>80</Port>
				<TLSPort>443</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>3333</Port>
					<TLSPort>3334</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					<TcpRelay>*:3478</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	
	

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			<Distribution>stream2.benjor.de</Distribution>

			
			<Host>
				<Names>
					<Name>*myURL*</Name>
				</Names>
				<TLS>
					<CertPath>/etc/letsencrypt/live/*myURL*/fullchain.pem</CertPath>
					<KeyPath>/etc/letsencrypt/live/*myURL*/privkey.pem</KeyPath>
					<ChainCertPath>/etc/letsencrypt/live/*myURL*/fullchain.pem</ChainCertPath>
				</TLS>
			</Host>

			
			
			<AdmissionWebhooks>
				<ControlServerUrl>*myURL*</ControlServerUrl>
				<SecretKey>1234</SecretKey>
				<Timeout>3000</Timeout>
				<Enables>
					<Providers>rtmp,srt</Providers>
					<Publishers>webrtc,llhls</Publishers>
				</Enables>
			</AdmissionWebhooks>
			
			
			<Applications>
				<Application>
					<Name>app</Name>
					<Type>live</Type>
					<OutputProfiles>
						<HardwareAcceleration>false</HardwareAcceleration>
						<OutputProfile>
							<Name>default_stream</Name>
							<OutputStreamName>${OriginStreamName}_preview</OutputStreamName>
							<Encodes>
								<Image>
									<Codec>png</Codec>
									<Framerate>1</Framerate>
									<Width>384</Width>
									<Height>216</Height>
								</Image>
							</Encodes>
						</OutputProfile>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
								<Playlist>
									<Name>test_webrtc</Name>
									<FileName>test_webrtc</FileName>
									<Options>
										<WebRtcAutoAbr>true</WebRtcAutoAbr> 
									</Options>
									<Rendition>
										<Name>Quelle</Name>
										<Video>bypass_video</Video>
										<Audio>webrtc_opus</Audio>
									</Rendition>
									<Rendition>
										<Name>HD</Name>
										<Video>video_720</Video>
										<Audio>webrtc_opus</Audio>
									</Rendition>
								</Playlist>
								<Playlist>
									<Name>llhls</Name>
									<FileName>llhls</FileName>
									<Rendition>
										<Name>Quelle</Name>
										<Video>bypass_video</Video>
										<Audio>bypass_audio</Audio>
									</Rendition>
									<Rendition>
										<Name>HD</Name>
										<Video>video_720</Video>
										<Audio>bypass_audio</Audio>
									</Rendition>
								</Playlist> 
								<Encodes>
									<Audio>
										<Name>bypass_audio</Name>
										<Bypass>true</Bypass>
									</Audio>
									<Video>
										<Name>bypass_video</Name>
										<Bypass>true</Bypass>
									</Video>
									<Audio>
									<Name>webrtc_opus</Name>
										<Codec>opus</Codec>
										<Bitrate>128000</Bitrate>
										<Samplerate>48000</Samplerate>
										<Channel>2</Channel>
									</Audio>
									<Video>
										<Name>video_720</Name>
										<Codec>h264</Codec>
										<Bitrate>6000000</Bitrate>
										<Framerate>60</Framerate>
										<Width>1280</Width>
										<Height>720</Height>
										<Preset>faster</Preset>
										<ThreadCount>6</ThreadCount>
									</Video>
								</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<RTMP />
						<SRT />
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<LLHLS>
							<ChunkDuration>0.2</ChunkDuration>
							<SegmentDuration>6</SegmentDuration>
							<SegmentCount>10</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
								<Url>*myURL*</Url>
							</CrossDomains>
						</LLHLS>
						<Thumbnail>
							<CrossDomains>
								<Url>*</Url>
								<Url>*myURL*</Url>
							</CrossDomains>	
						</Thumbnail>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>
</Server>
`

**Comment by getroot** [comment]
How long does it take for your server's memory to become full?
I couldn't reproduce the problem using your settings. My memory is constantly below 1%. Thumbnails are output at one per second as you set. You asked how you can delete old thumbnails, but the original design is that thumbnails are not accumulated and are continuously overwritten with new thumbnails.

![image](https://user-images.githubusercontent.com/17779085/194486385-a1cbd9d9-943c-4669-b80b-f390b792b94c.png)

![image](https://user-images.githubusercontent.com/17779085/194486400-7c724902-1dbc-4e0f-a2e0-e5d0bb5b83cd.png)

**Comment by getroot** [comment]
Couldn't reproduce the problem using your settings. How long does it take for the memory to become full?

Old thumbnails are no longer there. This is because it will be overwritten with the new thumbnail.

If you access the thumbnail URL as below, you can see that the thumbnails are continuously updated, and there are no old thumbnails.
https://ome-dev.airensoft.com:10081/app/stream_preview/thumb.png

![image](https://user-images.githubusercontent.com/17779085/194497900-d184f583-cc90-4e1f-a774-eaa577463513.png)
![image](https://user-images.githubusercontent.com/17779085/194497919-4433ae47-b043-4b85-ad14-071f3b0a9b9e.png)


If the waiting queue size increases due to insufficient system performance, a message is output to the log. But you said there was nothing wrong with the log, so it probably isn't. (Nevertheless, posting the log is helpful to those analyzing the problem.)

Is there any more information I can provide to reproduce this issue? Is there anything special about your environment? Thumbnail publishers are also used by several commercial services that are already running in a common environment, so if such a problem actually existed, I would have noticed it already.

**Comment by getroot** [comment]
One more piece of information, JPG uses much less CPU than PNG. It would be a good idea to check if the problem is reproduced with a JPG.

**Comment by Speedfighter** [comment]
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/9737487/ovenmediaengine.log)

There is the log from the engine.
The error occures at 2022-10-04 23:15:20.631.

Since we reduzed the tumbnail size, the time to crash increases.
With 1280x720 it's happendes after one and a half hour.
With 384x216 after 3h there are 4GB of memory in use (one livestream). 
When i restart the engine there are only ca. 300MB memory usage.

**Comment by Speedfighter** [comment]
And we have installed the newest version (V0.14.11) and there is the same problem.

**Comment by Keukhan** [comment]
@Speedfighter 

When I analyzed the log you sent me, the 1280x720 resolution image encoding option was set to both jpg and png. Try removing the png encoding option and setting only jpg.

And check how much CPU is being used. Insufficient CPU performance can cause memory to continuously increase.

Thanks

**Comment by getroot** [comment]
@Speedfighter It may just be that the CPU usage is low.  Please check and share the CPU usage by thread.

**Comment by benj0r** [comment]
@getroot The CPU usage is on all 6 cores average 10-25%. I tested different configs with different jpeg resolutions. 

It looks like the old thumbnails stay in the memory. If i use low resolution it takes several hours to fill the ram and swap. If i use for example full hd res it takes under an hour to fill the ram.

The Server hardware should not be the problem. I can easy assign more cores and ram form hardware to the VM. But the CPU is  not even close to full capacity.

**Comment by getroot** [comment]
@benj0r What is the CPU usage per thread?  How much CPU are the threads of the ome process using?

**Comment by Speedfighter** [comment]
![BSyDhTGV4L](https://user-images.githubusercontent.com/64670080/194711166-86993037-413b-4932-a418-05e9eeb0a291.png)

There is an screenshot of the htop command.
I think this will help you. 
One livestream now runs since one hour. And the memory is up to 2GB. 
Now with PNG the engine will run much longer but not infinte.

**Comment by getroot** [comment]
I don't know about htop, but you can find out the thread name by querying it with top -H -p <pid>. This helps us a lot. Thank you.
![image](https://user-images.githubusercontent.com/17779085/194711543-4299c9d1-558d-41e9-9c50-ec1bfbdfdd99.png)

**Comment by Speedfighter** [comment]
![RoyalTS_H21hJwOSHA](https://user-images.githubusercontent.com/64670080/194712163-1cb56524-13a3-4916-b338-2e6c7607bbbb.png)

Here the screenshot from top command

**Comment by getroot** [comment]
Thanks for your contribution, we fixed an issue that could cause OOM. Could you please check if your issue is resolved with the latest master branch?
https://github.com/AirenSoft/OvenMediaEngine/commit/cbf70e7c12c2c599de9a43375e42b5be36101827
