### ISSUE TITLE
Transcoding video is delayed !!!

### ISSUE THREAD

**Issue by kkwangeun** [AirenSoft/OvenMediaEngine#91]
Hi

Transcoding video is delayed when play hls m3u8 !!
No sound is heard when the video screen is moving slowly
After a while, the video plays again.

How can I solve this problem?

Source is dev version !

Here is my server.xml 
-------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>

<Server version="2">
	<Name>OvenMediaEngine</Name>
	<Hosts>
		<Host>
			<Name>default</Name>
			<IP>*</IP>
			
			<Ports>
				<Origin>9000</Origin>
				<RTMPProvider>1935</RTMPProvider>
				<HLS>80</HLS>
				<DASH>80</DASH>
				<WebRTC>
					<IceCandidates>
						<IceCandidate>*:10000-10005/udp</IceCandidate>
					</IceCandidates>
					<Signalling>3333</Signalling>
				</WebRTC>
			</Ports>

			<Applications>
				<Application>
					<Name>app</Name>
					<Type>live</Type>
					<Encodes>
						<Encode>
							<Name>HD</Name>
							<Audio>
								<Codec>aac</Codec>
								<Bitrate>128000</Bitrate>
								<Samplerate>48000</Samplerate>
								<Channel>2</Channel>
							</Audio>
							<Video>
								<Codec>h264</Codec>
								<Width>1024</Width>
								<Height>576</Height>
								<Bitrate>200000</Bitrate>
								<Framerate>30.0</Framerate>
							</Video>
						</Encode>

						<Encode>
							<Name>SD</Name>
							<Audio>
								<Codec>aac</Codec>
								<Bitrate>128000</Bitrate>
								<Samplerate>48000</Samplerate>
								<Channel>2</Channel>
							</Audio>
							<Video>
								<Codec>h264</Codec>
								<Width>700</Width>
								<Height>394</Height>
								<Bitrate>100000</Bitrate>
								<Framerate>30.0</Framerate>
							</Video>
						</Encode>

					</Encodes>
					<Streams>
						<Stream>
							<Name>${OriginStreamName}_HD</Name>
							<Profiles>
								<Profile>HD</Profile>
							</Profiles>
						</Stream>
						<Stream>
							<Name>${OriginStreamName}_SD</Name>
							<Profiles>
								<Profile>SD</Profile>
							</Profiles>
						</Stream>
					</Streams>
					<Providers>
						<RTMP />
					</Providers>
					<Publishers>
						<ThreadCount>20</ThreadCount>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomain>
								<Url>*</Url>
							</CrossDomain>
						</DASH>
						<WebRTC>
							<Timeout>30000</Timeout>
						</WebRTC>
					</Publishers>
				</Application>
			</Applications>
		</Host>
	</Hosts>
</Server>
-----------------------------------

**Comment by getroot** [comment]
We have no experienced this problem.
If possible, can you provide the public URL of the stream?

**Comment by kkwangeun** [comment]
Running with the "ffplay"  player has a delay!!!
When I ran it as "ome player" , there was no problem.

I tried to check again today, so it doesn't run on "ome player".
The delay is severe in "ffplay" player.

If the "ts"  file is downloaded and executed when "hls" is executed, why are the two players different?

And why now? ome player won't run ??

url http://45.58.2.146/app/lee_HD/playlist.m3u8

**Comment by dimiden** [comment]
@kkwangeun
I have analyzed the TS file from the URL you provided. I downloaded ```http://45.58.2.146/app/lee_HD/lee_HD_13646.ts``` and found one problem.

When I print the frames included in this TS using ```ffprobe```, the PTS of audio and video was very different. (video: 74364.197000, audio: 71505.668000)
```
frame|media_type=video|stream_index=0|key_frame=0|pkt_pts=6692777730|pkt_pts_time=74364.197000|pkt_dts=6692777730|pkt_dts_time=74364.197000|best_effort_timestamp=6692777730|best_effort_timestamp_time=74364.197000|pkt_duration=N/A|pkt_duration_time=N/A|pkt_pos=476768|pkt_size=6049|width=1024|height=576|pix_fmt=yuv420p|sample_aspect_ratio=N/A|pict_type=P|coded_picture_number=59|display_picture_number=0|interlaced_frame=0|top_field_first=0|repeat_pict=0|color_range=unknown|color_space=unknown|color_primaries=unknown|color_transfer=unknown|chroma_location=left
frame|media_type=audio|stream_index=1|key_frame=1|pkt_pts=6435510120|pkt_pts_time=71505.668000|pkt_dts=6435510120|pkt_dts_time=71505.668000|best_effort_timestamp=6435510120|best_effort_timestamp_time=71505.668000|pkt_duration=1920|pkt_duration_time=0.021333|pkt_pos=497260|pkt_size=323|sample_fmt=fltp|nb_samples=1024|channels=2|channel_layout=stereo
```

This problem can occur when the signal input to the source is unstable. Are you using RTMP as input?

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/77388854-9e076300-6dd4-11ea-9030-16164f22292b.png)

I tried running it on my server with the same settings as you, but I found it working fine.
What are you using as a video source? If you use OBS, set it as follows.

**Comment by kkwangeun** [comment]
After restarting "ome", the sync is correct.
But soon, it was getting out of sync.

I know the network condition is not good.
If the network is good, Will "ome" sync automatically without restarting?

**Comment by getroot** [comment]
Are you using OBS as an encoder? This may be due to the encoder or encoding settings. Or maybe the performance of the server you run ome on is the problem. There are various causes of AV sync.

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
