### ISSUE TITLE
Start OME in Edge mode with Docker?

### ISSUE THREAD

**Issue by angreebeaver** [AirenSoft/OvenMediaEngine#911]
Hello,
what is the recommended way of starting OME with docker in Edge mode?
How can I set Server.xml in ome-edge-conf folder inside container as default config for starting the container?
Thanks.

**Comment by getroot** [comment]
Is the information in the manual insufficient?
https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering

Please let me know specifically what you would like to know.

**Comment by angreebeaver** [comment]
In docker there are two folders ome-origin-conf and ome-edge-conf. Service is started with origin config in docker. I wondered if there’s, for example, an environment variable or another way to decide with which config and in which mode ome in docker is started.

**Comment by getroot** [comment]
See docker-compose.yml provided as an example. In edge mode, run as follows.

https://github.com/AirenSoft/OvenMediaEngine/blob/master/docker-compose.yml

`command: /opt/ovenmediaengine/bin/OvenMediaEngine -c edge_conf`
