### ISSUE TITLE
Pull File work only for HLS (It is also possible to make it work with WEBRTC).

### ISSUE THREAD

**Issue by trapasso** [AirenSoft/OvenMediaEngine#914]
**Describe the bug**
Into edge server, the origin file (pull file) work only for HLS.

**To Reproduce**
1. Add origin:
```
        <Origin>
            <Location>/vod/</Location>
            <Pass>
                <Scheme>file</Scheme>
                <Urls><Url>/vod/</Url></Urls>
            </Pass>
        </Origin>
```
2. Try reading with OvenPlayer, try HLS protocol and WEBRTC.

**Expected behavior**
I expected to be able to read with both HLS and WEBRTC.

**Server (please complete the following information):**
 - OS: ubuntu 20.04
 - OvenMediaEngine Version: last
 - Branch: master

**Player (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser firefox 
 - Version 105.0

**Additional context**
I understood that the video track contained b-frames and these cannot be read by WEBRTC, just as the audio track encoded with AAC.
So I prepared an mp4 file without b-frame in H264 and with 2 audio tracks one AAC encoded and the other OPUS encoded.
At this point the video also works well on WEBRTC but the audio remains silent.
The audio encoded with OPUS remains excluded by the following switch in src/projects/providers/file/file_stream.cpp:
```
			switch (track->GetCodecId())
			{
				case cmn::MediaCodecId::H264:
					bitstream_format = cmn::BitstreamFormat::H264_AVCC;
					packet_type = cmn::PacketType::NALU;
					break;
				case cmn::MediaCodecId::Aac:
					bitstream_format = cmn::BitstreamFormat::AAC_RAW;
					packet_type = cmn::PacketType::RAW;
					break;
				default:
					::av_packet_unref(&packet);
					continue;
			}
```
Now, I patched the switch by adding:
```
				case cmn::MediaCodecId::Opus:
					bitstream_format = cmn::BitstreamFormat::OPUS;
					packet_type = cmn::PacketType::RAW;
					break;

```
And ... finally the mp4 file can be read with both HLS and WEBRTC protocol.

To conclude, it would be enough to insert this tiny patch to be able to use the WEBRTC protocol also for file pull.
```
--- a/src/projects/providers/file/file_stream.cpp
+++ b/src/projects/providers/file/file_stream.cpp
@@ -372,6 +372,10 @@ namespace pvd
                                        bitstream_format = cmn::BitstreamFormat::AAC_RAW;
                                        packet_type = cmn::PacketType::RAW;
                                        break;
+                               case cmn::MediaCodecId::Opus:
+                                       bitstream_format = cmn::BitstreamFormat::OPUS;
+                                       packet_type = cmn::PacketType::RAW;
+                                       break;
                                default:
                                        ::av_packet_unref(&packet);
                                        continue;
```
Of course the mp4 file must contain 2 audio tracks (AAC and OPUS) and if it contains an H264 video track, this must be without b-frame.
Many thanks in advance.

**Comment by getroot** [comment]
oh my god, you are so amazing. Since this is part of some big feature we're still developing, I've never mentioned this feature in any documentation or hints. But you fully understand this part of the function. Please PR if you need this feature. Thank you for your amazing contribution.

**Comment by Trungdo253** [comment]
![image](https://user-images.githubusercontent.com/93107241/195272891-3860bc01-f856-4e44-9847-15a241b73804.png)
According to the documentation `<Scheme>` is OVT or RTSP
Can you tell me where the ` <Scheme>file</Scheme>` is and what it is used for?
