### ISSUE TITLE
CPU vs GPU perfomance

### ISSUE THREAD

**Issue by albeliakov** [AirenSoft/OvenMediaEngine#918]
Hello!
Do you have any performance comparison between CPU and GPU? Of particular interest are the cases of WebRTC->WebRTC and RTMP->WebRTC.

I would like to look at them before buying a graphics card.

**Comment by getroot** [comment]
Since the GPU is only used for decoding/encoding, it does not directly affect WebRTC and RTMP performance. If performance is not enough when doing software encoding (H.264/VP8), it is better to look at a GPU. Also, check the GPU's specifications for the encoding performance of the GPU.
