### ISSUE TITLE
CPPFLAGS/LDFLAGS are ignored

### ISSUE THREAD

**Issue by hashworks** [AirenSoft/OvenMediaEngine#925]
**Describe the bug**
The build system ignores any `CPPFLAGS` or `LDFLAGS` environment variables set.

**To Reproduce**
1. Provide openssl-3.0 at `/usr/include/openssl-3.0` and `/usr/lib/openssl-3.0`
2. Provide library paths to the OvenMediaEngine build system:
```sh
CPPFLAGS+=" -I/usr/include/openssl-3.0" \
LDFLAGS+=" -L/usr/lib/openssl-3.0" \
make release
```
3. Note that gcc can't find `core_names.h`, which exists at `/usr/include/openssl-3.0/openssl/core_names.h`:
```
projects/base/ovcrypto/certificate.cpp:3:10: fatal error: openssl/core_names.h: No such file or directory
    3 | #include <openssl/core_names.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/base/ovcrypto/certificate.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Expected behavior**
The build system uses libraries provided by `CPPFLAGS` / `LDFLAGS`.

**Server (please complete the following information):**
 - OS: Arch Linux
 - OvenMediaEngine Version: 0.14.13
 - Branch: version tag

**Additional context**

For the moment, Arch Linux isn't providing `openssl3` by default. For that one needs an [AUR package](https://aur.archlinux.org/packages/openssl-3.0), that provides it at the mentioned paths. Normally one then tells the build system the location of the libraries using `CPPFLAGS` and `LDFLAGS`, but the OvenMediaEngine build system seems to ignore them.

This is the PKGBUILD file I'm currently using to build it: https://fb.hash.works/rrKuDKGX/

**Comment by getroot** [comment]
If prerequisites.sh is executed according to OME's manual, OpenSSL 3.0 is installed separately in /opt/ovenmediaengine and OME uses it. I have no experience with Arch Linux, but does prerequisites.sh fail there?

**Comment by dimiden** [comment]
@hashworks Currently, OME's make system does not support ```CPPFLAGS``` and ```LDFLAGS``` environment variables.
If you want to change these two values, please modify ```GLOBAL_C*FLAGS*``` and ```GLOBAL_LDFLAGS*``` in ```global_config.mk```.

**Comment by hashworks** [comment]
Alright, I can adjust it locally. Would you accept an MR that adds `CPPFLAGS` / `LDFLAGS` to those variables?

**Comment by dimiden** [comment]
@hashworks Yes, it's a good idea. But I'm too busy to add that feature right now, so I'll add it later.

**Comment by hashworks** [comment]
> However, the license of ovenmediaengine in archlinux is incorrectly marked as GPL2. ovenmediaengine is AGPLv3 license, so I would appreciate it if you could fix it.

My bad, fixed.

**Comment by hashworks** [comment]
Still relevant.

**Comment by getroot** [comment]
I'm closing this issue because it's been resolved. Please reopen if you think the discussion should continue.
