### ISSUE TITLE
edit logger.xml

### ISSUE THREAD

**Issue by Mariano245** [AirenSoft/OvenMediaEngine#926]
as is the correct way to edit the logger.XML file, to disable the generation of a log. For example to disable the log generated for FFmpeg.

**Comment by dimiden** [comment]
You should delete the following line of ```Logger.xml``` and use the method that specifies only the TAGs you want to print.

```
	<Tag name=".*" level="info"/>
```

For example, if you want to print only the logs from HLS modules, you can set it as follows.

```
For example, if you want to print only the HLS log, you can set it as follows.

```

If you want to keep the above TAG__ and only remove the logs from a particular TAG, there is no way to do this, and you should set the log LEVEL to CRITICALL to reduce the amount of logs that are output.

**Comment by dimiden** [comment]
@Mariano245 There is no way to turn off the log of a tag. But you can reduce the mount of logs using ```critical``` level for the tags.

For example, if you want to reduce the logs from FFmpeg modules, use below settings:

```
<Logger>
...
    <Tag name="FFmpeg.*" level="critical" />
...
</Logger>
```

If you want to reduce the total amount of logs, you can change the level in the following line to ```critical```.

AS-IS
```
<Tag name=".*" level="info"/>
```

TO-BE
```
<Tag name=".*" level="critical"/>
---

**Comment by Mariano245** [comment]
then for the change to take effect just restart OME or do I have to restart the computer?

**Comment by dimiden** [comment]
@Mariano245 Yes, that's right. Or, you can pass the ```SIGHUP``` signal through the following command so that the settings can be reloaded. 

```
$ pkill -SIGHUP OvenMediaEngine
```

note) Please use this method only in the release built version (create by using ```make release``` command).
In debug build, there is an issue where an assertion error occurs, I will fix this issue in the future.

**Comment by Mariano245** [comment]
ok good, all right, thanks
