### ISSUE TITLE
Failed checking for nvcc

### ISSUE THREAD

**Issue by mrknifr652** [AirenSoft/OvenMediaEngine#929]
Error during docker build with nvidia driver

```
 make[1]: Entering directory '/tmp/aac'
 /usr/bin/mkdir -p '/opt/ovenmediaengine/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfdk-aac.la '/opt/ovenmediaengine/lib'
libtool: install: /usr/bin/install -c .libs/libfdk-aac.so.2.0.2 /opt/ovenmediaengine/lib/libfdk-aac.so.2.0.2
libtool: install: (cd /opt/ovenmediaengine/lib && { ln -s -f libfdk-aac.so.2.0.2 libfdk-aac.so.2 || { rm -f libfdk-aac.so.2 && ln -s libfdk-aac.so.2.0.2 libfdk-aac.so.2; }; })
libtool: install: (cd /opt/ovenmediaengine/lib && { ln -s -f libfdk-aac.so.2.0.2 libfdk-aac.so || { rm -f libfdk-aac.so && ln -s libfdk-aac.so.2.0.2 libfdk-aac.so; }; })
libtool: install: /usr/bin/install -c .libs/libfdk-aac.lai /opt/ovenmediaengine/lib/libfdk-aac.la
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/sbin" ldconfig -n /opt/ovenmediaengine/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /opt/ovenmediaengine/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /usr/bin/mkdir -p '/opt/ovenmediaengine/include/fdk-aac'
 /usr/bin/install -c -m 644 ./libSYS/include/machine_type.h ./libSYS/include/genericStds.h ./libSYS/include/FDK_audio.h ./libSYS/include/syslib_channelMapDescr.h ./libAACenc/include/aacenc_lib.h ./libAACdec/include/aacdecoder_lib.h '/opt/ovenmediaengine/include/fdk-aac'
 /usr/bin/mkdir -p '/opt/ovenmediaengine/lib/pkgconfig'
 /usr/bin/install -c -m 644 fdk-aac.pc '/opt/ovenmediaengine/lib/pkgconfig'
make[1]: Leaving directory '/tmp/aac'
ERROR: failed checking for nvcc.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
(ffmpeg) installation has failed.
The command '/bin/sh -c if [ "$GPU" = "TRUE" ] ; then    ${TEMP_DIR}/misc/install_nvidia_docker_image.sh ;
${TEMP_DIR}/misc/prerequisites.sh  --enable-nvc ;   else  ${TEMP_DIR}/misc/prerequisites.sh ;  fi' returned a non-zero code: 1
```

**Comment by dunkan** [comment]
I have this problem too.

My host OS (Ubuntu 22.04) nvidia-smi show me only one process - re-encoding stream to OME by container ffmpeg
Tue Dec  6 14:55:53 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 39%   43C    P0    N/A /  75W |    156MiB /  2048MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A   3844518      C   ffmpeg                            154MiB |
+-----------------------------------------------------------------------------

Container OME(:dev and :0.14.16) have nvidia drivers, but not have HardwareAcceleration
# docker exec -it oventest nvidia-smi
Tue Dec  6 10:55:28 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| 39%   43C    P0    N/A /  75W |    156MiB /  2048MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|

Part of Server.xml
<OutputProfiles>
    <HardwareAcceleration>true</HardwareAcceleration>
    <OutputProfile>
        <Name>bypass_stream</Name>
        <OutputStreamName>${OriginStreamName}</OutputStreamName>
        <Encodes>
            <Video>
                <Name>bypass_video</Name>
                <Bypass>true</Bypass>
            </Video>
            <Audio>
                <Name>bypass_audio</Name>
                <Bypass>True</Bypass>
            </Audio>
            <Video>
                <Codec>h264</Codec>
                <Width>640</Width>
                <Height>360</Height>
                <Bitrate>1000000</Bitrate>
                <Framerate>30</Framerate>
             </Video>
        </Encodes>
    </OutputProfile>
</OutputProfiles>

I see both video stream, but transcoding by CPU
Help me, pls, use transcoding.
P.S. I used script install_nvidia_docker_container.sh

**Comment by Keukhan** [comment]
@mrknifr652  

Additional options are required to use GPUs with Docker. Please refer to the information below.
Please add `--gpus all` option when running docker.

https://airensoft.gitbook.io/ovenmediaengine/transcoding/gpu-usage#how-to-run-docker 

Thanks.

**Comment by mpisat** [comment]
not just docker, prerequisites.sh or documentation also should mention installing cuda-toolkit for ubuntu 22, as well as aac faad (or whatever the name is). 

When I installed those, it was able to install required tools and GPU transcoding works fine on proxmox/ubuntu 22 KVM system with gpu passthrough :)

**Comment by dunkan** [comment]
I downloaded new version (0.15.7) from our git repo OME. Set all (2) ARG GPU in Dokerfile to TRUE
I was happy that it builded without errors. Thank's for your work!
BUT
When I run the container with `--gpus all` and with Encodes in Server.xml 
`<Video>
  <Codec>h264</Codec>
  <Width>640</Width>
  <Height>360</Height>
  <Bitrate>1000000</Bitrate>
  <Framerate>30</Framerate>
</Video>`
OME down in moment encode with errors:
`
[2023-03-24 12:58:59.969] E [InboundWorker:41] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7f74d0006400] Cannot load libnvcuvid.so.1
[2023-03-24 12:58:59.969] E [InboundWorker:41] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7f74d0006400] Failed loading nvcuvid.
[2023-03-24 12:58:59.969] C [InboundWorker:41] OvenMediaEngine | signals.cpp:114  | OME received signal 11 (SIGSEGV), interrupt.
`
Have a nice day )

**Comment by Keukhan** [comment]
I'm sorry. I've been busy lately and haven't had a chance to check on this issue. I'm working on resolving it now. I'll bring good news within 1-2 days.
Thanks.

**Comment by Keukhan** [comment]
@dunkan 
I don't know why such an interactive choice comes out. I'll try to reproduce it. If you have any good ideas, please give me some advice. :)

**Comment by NkInKaIgIe** [comment]
@Keukhan  i deployed ome on docker with GPU enabled. After building image OME - GPU successfully. 
![image](https://user-images.githubusercontent.com/96049216/232002320-86b40513-303f-44ec-b8dc-46154baef178.png)
Nvidia-smi on Docker images Ome 0.15.9
![image](https://user-images.githubusercontent.com/96049216/232006841-aead0be4-b3a7-4c81-b124-468d71dea64c.png)
Nvidia-smi on VM
![image](https://user-images.githubusercontent.com/96049216/232006928-3748fa56-7d71-453b-9661-7ce85c87e119.png)
Server.xml
![image](https://user-images.githubusercontent.com/96049216/232007117-48e10557-7537-43bf-ad8b-1feb8ca65831.png)

When streaming it gives an error: Unable to load libnvcuvid.so.1
![image](https://user-images.githubusercontent.com/96049216/232010523-96fcc6be-b168-404a-89af-7f5492e32a72.png)

Driver Version: 530.30.02
ome version: 0.15.9

**Comment by dunkan** [comment]
https://github.com/AirenSoft/OvenMediaEngine/issues/929#issuecomment-1505061508
If set NVIDIA_DRIVER=515, I have a intaractive choice. Container builded with full version like as NVIDIA_DRIVER=515.105.01

After start encoder in container, I have this error too, again

**Comment by NkInKaIgIe** [comment]
@Keukhan i have deployed gpu on docker successfully with ome 0.15.8
In dockerfile use centos 7 and add yum group setting install "Development Tools" and change some things and it worked successfully. I tested ome 0.15.9 it didn't find libnvcuvid.so.1

**Comment by NkInKaIgIe** [comment]
Edit the Dockerfiles file and add the line apt-get install keyboard-configuration to fix this error

**Comment by NkInKaIgIe** [comment]
> @Keukhan, Thanks for your work Stop building on interactive choice <img alt="image" width="887" src="https://user-images.githubusercontent.com/4420054/231467066-1e68b599-c78b-4e90-a375-b131e1dab667.png"> Can't choice or input. Help me, pls )

Edit the Dockerfiles file and add the line apt-get install keyboard-configuration to fix this error

**Comment by Keukhan** [comment]
@NkInKaIgIe 

I added the solution you gave me to the driver install script. thanks. :)

https://github.com/AirenSoft/OvenMediaEngine/commit/460f5d15507f69f3a238422619b0cc06af5872ba

**Comment by nums** [comment]
I have the same issue on my side with the last version (v0.15.13) : 

`[2023-06-30 13:14:52.251] E [InboundWorker:24] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7f735ba73400] Cannot load libnvcuvid.so.1`
`[2023-06-30 13:14:52.251] E [InboundWorker:24] FFmpeg | third_parties.cpp:111  | [AVCodecContext: 0x7f735ba73400] Failed loading nvcuvid.`
`[2023-06-30 13:14:52.251] C [InboundWorker:24] OvenMediaEngine | signals.cpp:120  | OME received signal 11 (SIGSEGV), interrupt.`

My build command line : 
`docker build . --file Dockerfile -t airensoft/ovenmediaengine:0.15.13 --build-arg GPU=TRUE --build-arg NVIDIA_DRIVER=470.141.03`

The `nvidia-smi` give the same result on the host and in the container ; 

![image - 2023-06-30T152334 831](https://github.com/AirenSoft/OvenMediaEngine/assets/274268/fd52e0d7-4cac-4676-b218-aacbd971dbf6)

**Comment by mpisat** [comment]
@nums did you install cuda-toolkit inside the dockerfile and also on your system? Cuda-toolkit should match your 470 driver and cuda-toolkit version would be 11.4
Is there a specific reason why you are using Nvidia 470 driver? Old linux kernel on the host machine?

**Comment by Keukhan** [comment]
@nums 
Check if the following files exist in the container.  

./usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
./usr/lib/x86_64-linux-gnu/libnvcuvid.so.470.182.03
./usr/lib/x86_64-linux-gnu/libnvcuvid.so

Also, can you share the command that launched Docker?  If the **--gpus al**l option is not given, the above error may occur.

**Comment by nums** [comment]
Thanks for your help.

With my last try (on **GCP**, last time I was on scaleway), I have executed on the last version (**v0.15.13**) on the **host** :

`misc/install_nvidia_driver.sh` 

`misc/install_nvidia_docker_container.sh` 

`service docker restart`

After that, I've got **535.54.03** driver version and **CUDA Version: 12.2**

`docker build . --file Dockerfile.local -t airensoft/ovenmediaengine:v0.15.13 --build-arg GPU=TRUE --build-arg NVIDIA_DRIVER=535.54.03`

```
docker run \
-p 1935:1935 \
-p 3333:3333 \
-p 3334:3334 \
-p 3478:3478 \
-p 9000:9000 \
-p 9999:9999/udp \
-p 4000:4000/udp \
-v ome-origin-conf:/opt/ovenmediaengine/bin/origin_conf \
-v ome-edge-conf:/opt/ovenmediaengine/bin/edge_conf \
--gpus all --name ovenmediaengine \
airensoft/ovenmediaengine:v0.15.13
```

I've got the same problem with the error code and no "**libnvcuvid**" at all

I have executed on the **container** this script :
```
#!/bin/bash -e

# Install NVIDIA userspace driver components including X graphic libraries
if ! command -v nvidia-xconfig &> /dev/null; then
  # Driver version is provided by the kernel through the container toolkit
  export DRIVER_VERSION=$(head -n1 </proc/driver/nvidia/version | awk '{print $8}')
  cd /tmp
  # If version is different, new installer will overwrite the existing components
  if [ ! -f "/tmp/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" ]; then
    # Check multiple sources in order to probe both consumer and datacenter driver versions
    curl -fsL -O "https://us.download.nvidia.com/XFree86/Linux-x86_64/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" || curl -fsL -O "https://us.download.nvidia.com/tesla/$DRIVER_VERSION/NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" || { echo "Failed NVIDIA GPU driver download. Exiting."; exit 1; }
  fi
  # Extract installer before installing
  sudo sh "NVIDIA-Linux-x86_64-$DRIVER_VERSION.run" -x
  cd "NVIDIA-Linux-x86_64-$DRIVER_VERSION"
  # Run installation without the kernel modules and host components
  sudo ./nvidia-installer --silent \
                    --no-kernel-module \
                    --install-compat32-libs \
                    --no-nouveau-check \
                    --no-nvidia-modprobe \
                    --no-rpms \
                    --no-backup \
                    --no-check-for-alternate-installs
  sudo rm -rf /tmp/NVIDIA* && cd ~
fi
```

which made it possible to have the lib :
```
./usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
./usr/lib/x86_64-linux-gnu/libnvcuvid.so.470.182.03
./usr/lib/x86_64-linux-gnu/libnvcuvid.so
```

After that, I have a new error :

```
[2023-07-04 16:00:08.084] E [Dech264NV:638] FFmpeg | third_parties.cpp:111  | Impossible to convert between the formats supported by the filter 'Parsed_fps_0' and the filter 'auto_scale_0'
[2023-07-04 16:00:08.084] E [Dech264NV:638] Transcoder | filter_rescaler.cpp:231  | Could not validate filter graph for rescaling: -38
[2023-07-04 16:00:08.084] E [Dech264NV:638] Transcoder | transcoder_filter.cpp:71   | Could not create filter
[2023-07-04 16:00:08.084] E [Dech264NV:638] Transcoder | transcoder_stream.cpp:833  | [#default#app/test(100)] Failed to create filter. Filter(1)
```

To check, if my configuration file was not the issue, I have disbled hardware acceleration, and there is no error, stream is ok with CPU tanscoding.

**Comment by Keukhan** [comment]
@nums 

thank you for reporting.
I recently solved an issue where filter creation fails when using Nvidia GPU in the master branch. Unfortunately, it hasn't been officially released yet.
Anyway, I'll check again to see if it's the same problem.

Thanks. :)

**Comment by nums** [comment]
@Keukhan 

Thanks, it's working with the master branch.
I had to run the script written above `# Install NVIDIA userspace driver components including X graphic libraries`.
without that I don't have `libnvcuvid` installed

It might be interesting to add it to `install_nvidia_driver.sh` ?

**Comment by Keukhan** [comment]
@nums 

Thanks for sharing your test results.. 

As shown in the code below, it is developed to reinstall libraries such as libnvcuvid files when creating a docker image. 

In Dockerfile
```
# If the GPU is enabled, reinstall the NVIDIA driver into the release image
RUN \
    if [ "$GPU" = "TRUE" ] ; then \
            /opt/ovenmediaengine/bin/install_nvidia_driver.sh --enable_docker --nvidia_driver ${NVIDIA_DRIVER} ;  \
    fi

```
If this script is lacking, I'd appreciate it if you could improve it. 
I will be looking forward to your PR.

Thanks :)

**Comment by nums** [comment]
@Keukhan pull request created.
Tested on a GCP Gpu on it's working
