### ISSUE TITLE
[OriginMapStore] crash since commit hash: #5a46220190dceea2840e8844ca33a0c627faf1da 

### ISSUE THREAD

**Issue by chakphanu** [AirenSoft/OvenMediaEngine#935]
> Thanks @getroot. I just added section and enabled OVT provider. Result is the same. Here is full log for Edge and full Edge config.
> 
> [ovenmediaengine-edge-5446998599-xbbd8.log](https://github.com/AirenSoft/OvenMediaEngine/files/9794899/ovenmediaengine-edge-5446998599-xbbd8.log)
> 
> Edge:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
>         <Server version="8">
>             <Name>edge</Name>
>             <IP>*</IP>
>             <Type>edge</Type>
>             <PrivacyProtection>false</PrivacyProtection>
>             <StunServer>stun.l.google.com:19302</StunServer>
>             <Modules>
>                 
>                 <HTTP2>
>                     <Enable>true</Enable>
>                 </HTTP2>
>                 
>                 
>             </Modules>
>             <Bind>
>                 <Providers />
>                 <Publishers>
>                     <WebRTC>
>                         <Signalling>
>                             <Port>4333</Port>
>                             <TLSPort>4334</TLSPort>
>                             <WorkerCount>1</WorkerCount>
>                         </Signalling>
>                         <IceCandidates>
>                             <IceCandidate>*:11000-11005/udp</IceCandidate>
>                             <TcpRelay>*:4478</TcpRelay>
>                             <TcpForce>true</TcpForce>
>                             <TcpRelayWorkerCount>1</TcpRelayWorkerCount>
>                         </IceCandidates>
>                     </WebRTC>
>                 </Publishers>
>             </Bind>
>             <VirtualHosts>
>                 <VirtualHost>
>                     <Name>default</Name>
>                     <Host>
>                         <Names>
>                             <Name>efoo.example.com</Name>
>                         </Names>
>                         <TLS>
>                             <CertPath>/opt/ovenmediaengine/bin/edge_certs/tls.crt</CertPath>
>                             <KeyPath>/opt/ovenmediaengine/bin/edge_certs/tls.key</KeyPath>
>                             <ChainCertPath>/opt/ovenmediaengine/bin/edge_certs/tls.crt</ChainCertPath>
>                         </TLS>
>                     </Host>
>                     <Distribution>example.com</Distribution>
>                     <OriginMapStore>
>                         <RedisServer>
>                             <Host>ovenmediaengine-redis-master:6379</Host>
>                             <Auth>test</Auth>
>                         </RedisServer>
>                     </OriginMapStore>
>                     <Applications>
>                       <Application>
>                           <Name>app</Name>
>                           <Type>live</Type>
>                           <OutputProfiles>
>                               <OutputProfile>
>                                   <Name>passthrough</Name>
>                                   <OutputStreamName>${OriginStreamName}</OutputStreamName>
>                                   <Encodes>
>                                       <Video>
>                                           <Bypass>true</Bypass>
>                                       </Video>
>                                       <Audio>
>                                           <Bypass>true</Bypass>
>                                       </Audio>
>                                   </Encodes>
>                               </OutputProfile>
>                           </OutputProfiles>
>                           <Providers>
>                               <OVT />
>                           </Providers>
>                           <Publishers>
>                               <AppWorkerCount>1</AppWorkerCount>
>                               <StreamWorkerCount>8</StreamWorkerCount>
>                               <WebRTC>
>                                   <Timeout>30000</Timeout>
>                                   <Rtx>false</Rtx>
>                                   <Ulpfec>false</Ulpfec>
>                                   <JitterBuffer>false</JitterBuffer>
>                               </WebRTC>
>                               <LLHLS>
>                                   <ChunkDuration>0.5</ChunkDuration>
>                                   <SegmentDuration>6</SegmentDuration>
>                                   <SegmentCount>10</SegmentCount>
>                                   <CrossDomains>
>                                       <Url>*</Url>
>                                   </CrossDomains>
>                               </LLHLS>
>                           </Publishers>
>                       </Application>
>                     </Applications>
>                 </VirtualHost>
>             </VirtualHosts>
>         </Server>
> ```

v0.14.10 == ok
v0.14.11 == Could not find Origin for the stream

this commit make edge OriginMapStore fail/crash.
commit 5a46220190dceea2840e8844ca33a0c627faf1da (HEAD)
Author: getroot <getroot@airensoft.com>
Date:   Wed Oct 5 21:13:57 2022 +0900

    Added RequestPullStream with url vector
    

> 

   [11-02 03:41:29.883] I [SPRtcSig-T3333:152246] Publisher | publisher.cpp:186  | Try to pull stream from local origin map: [#edge#app/test]
[11-02 03:41:29.898] E [SPRtcSig-T3333:152246] Orchestrator | orchestrator.cpp:634  | Could not find Origin for the stream: [#edge#app/test]
[11-02 03:41:29.900] I [SPRtcSig-T3333:152246] Publisher | publisher.cpp:190  | Try to pull stream from origin map store: [#edge#app/test]
==152234== Can't extend stack to 0x8593088 during signal delivery for thread 5:
==152234==   no stack segment
==152234==
==152234== Process terminating with default action of signal 11 (SIGSEGV)
==152234==  Access not within mapped region at address 0x8593088
==152234==    at 0x121B4B8: ocst::Orchestrator::RequestPullStream(std::shared_ptr<ov::Url const> const&, info::VHostAppName const&, ov::String const&, ov::String const&, long) (orchestrator.cpp:606)
==152234==  If you believe this happened as a result of a stack
==152234==  overflow in your program's main thread (unlikely but
==152234==  possible), you can try to increase the size of the
==152234==  main thread stack using the --main-stacksize= flag.
==152234==  The main thread stack size used in this run was 8388608.
==152234== Thread 5:
==152234== Invalid write of size 8
==152234==    at 0x4833134: _vgnU_freeres (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_core-amd64-linux.so)
==152234==  Address 0x8593f48 is on thread 5's stack
==152234==
==152234==
==152234== Process terminating with default action of signal 11 (SIGSEGV)
==152234==  Bad permissions for mapped region at address 0x8593F48
==152234==    at 0x4833134: _vgnU_freeres (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_core-amd64-linux.so)
==152234==
==152234== HEAP SUMMARY:
==152234==     in use at exit: 2,671,316 bytes in 31,503 blocks
==152234==   total heap usage: 133,868 allocs, 102,365 frees, 7,851,165 bytes allocated
==152234==
==152234== Searching for pointers to 31,503 not-freed blocks
==152234== Checked 181,349,328 bytes
==152234==
==152234== LEAK SUMMARY:
==152234==    definitely lost: 64 bytes in 1 blocks
==152234==    indirectly lost: 3 bytes in 1 blocks
==152234==      possibly lost: 6,818 bytes in 23 blocks
==152234==    still reachable: 2,664,431 bytes in 31,478 blocks
==152234==         suppressed: 0 bytes in 0 blocks
==152234== Rerun with --leak-check=full to see details of leaked memory
==152234==
==152234== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
==152234==
==152234== 1 errors in context 1 of 1:
==152234== Invalid write of size 8
==152234==    at 0x4833134: _vgnU_freeres (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_core-amd64-linux.so)
==152234==  Address 0x8593f48 is on thread 5's stack
==152234==
==152234== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault (core dumped)

_Originally posted by @chakphanu in https://github.com/AirenSoft/OvenMediaEngine/issues/343#issuecomment-1298992307_

**Comment by getroot** [comment]
Thanks for the detailed bug report.
This issue has just been fixed and committed to the master branch.
