### ISSUE TITLE
LLHLS on android/ios

### ISSUE THREAD

**Issue by sridhard** [AirenSoft/OvenMediaEngine#936]
**Is your feature request related to a problem? Please describe.**
How can we use oven media engine on android/ios? is there any SDK for playing LLHLS on android and ios?
If there is no SDK then can we use exoplayer on android? Exoplayer has LLHLS support.

OvenMediaEngine LLHLS is it fully complaint to LLHLS standard? If yes I think we can use other players

**Describe the solution you'd like**
Need a solution to play LLHLS on android/ios natively

**Describe alternatives you've considered**
No alternatives as of now

**Additional context**
no

**Comment by getroot** [comment]
Naturally, OME's LLHLS follows the standard. Works well with EXO and AVPlayer.

**Comment by sridhard** [comment]
ok thanks
