### ISSUE TITLE
fatal error: openssl/core_names.h: No such file or directory

### ISSUE THREAD

**Issue by Saleque474** [AirenSoft/OvenMediaEngine#937]
I am installing this software. I have written sudo make release . but this error is showing . I have installed openssl . But still facing the error .

projects/base/ovcrypto/certificate.cpp:3:10: fatal error: openssl/core_names.h: No such file or directory
    3 | #include <openssl/core_names.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [core/build_objects.mk:21: intermediates/RELEASE/objs/base/ovcrypto/certificate.o] Error 1

**Comment by getroot** [comment]
You have to install dependencies with prerequisites.sh script.
https://airensoft.gitbook.io/ovenmediaengine/getting-started#install-dependencies

**Comment by Saleque474** [comment]
> You have to install dependencies with prerequisites.sh script. https://airensoft.gitbook.io/ovenmediaengine/getting-started#install-dependencies

Thank you very much it worked for me. Love it
sudo  ./misc/prerequisites.sh
