### ISSUE TITLE
Only one transcoding setting possible

### ISSUE THREAD

**Issue by mrw-s** [AirenSoft/OvenMediaEngine#938]
**Describe the bug**
If two or more streams are configured with different transcoding settings using a postfix to $ {OriginStreamName}, only the transcoding settings for the unaltered $ {OriginStreamName} stream are actually provided for all the streams. In the configuration below, when viewing with OvenPlayer via WenRTC for an RTSP pulled source stream 'camera1', the stream camera1_preview and camera1_setup are actually provided without any transcoding (i.e. the bypass settings from stream camera1 (i.e. $ {OriginStreamName}). If I alter the settings for ${OriginStreamName} to be transcoded, then camera1_preview and camera1_setup are then streamed at the settings for 'camera1'. It seems the transcoding settings for the <OutputProfile> with <OutputStreamName> ${OriginStreamName} are always used for all <OutputStreamName>s with a postfix ignoring any different settings specified with <Encodes>.

**To Reproduce**

For and RTSP pulled stream, configure the OutputProfiles as follows:
``
<OutputProfiles>

<OutputProfile>
	<Name>preview_stream</Name>
	<OutputStreamName>${OriginStreamName}_preview</OutputStreamName>
	<Encodes>
		<Audio>
			<Codec>opus</Codec>
			<Bitrate>128000</Bitrate>
			<Samplerate>48000</Samplerate>
			<Channel>2</Channel>
		</Audio>
						 	
		<Video>
			<Bypass>false</Bypass>
			<Codec>h264</Codec>
			<Bitrate>512000</Bitrate>
			<Framerate>25.0</Framerate>
			<Width>384</Width>
			<Height>216</Height>
			<Preset>faster</Preset>
			<ThreadCount>1</ThreadCount>
		</Video>
	</Encodes>
</OutputProfile>

<OutputProfile>
	<Name>setup_stream</Name>
	<OutputStreamName>${OriginStreamName}_setup</OutputStreamName>
	<Encodes>
		<Audio>
			<Codec>opus</Codec>
			<Bitrate>128000</Bitrate>
			<Samplerate>48000</Samplerate>
			<Channel>2</Channel>
		</Audio>

						 	
		<Video>
			<Bypass>false</Bypass>
			<Codec>h264</Codec>
			<Bitrate>2000000</Bitrate>
			<Framerate>25.0</Framerate>
			<Width>1920</Width>
			<Height>1080</Height>
			<Preset>faster</Preset>
		        <ThreadCount>1</ThreadCount>
		</Video>
	</Encodes>
</OutputProfile>

<OutputProfile>
	<Name>stream_bypass</Name>
	<OutputStreamName>${OriginStreamName}</OutputStreamName>
	<Encodes>
		<Audio>
			<Codec>opus</Codec>
			<Bitrate>128000</Bitrate>
			<Samplerate>48000</Samplerate>
			<Channel>2</Channel>
		</Audio>
						 	
		<Video>
			<Bypass>false</Bypass>
			<Codec>h264</Codec>
			<Bitrate>512000</Bitrate>
			<Framerate>25.0</Framerate>
			<Width>384</Width>
			<Height>216</Height>
			<Preset>faster</Preset>
			<ThreadCount>1</ThreadCount>
		</Video>
	</Encodes>
</OutputProfile>
``

causes camera1_preview and camera_setup to be provided at 384x216 512kbps.

**Expected behavior**
camera1 provided at the source resolution, framerate and bandwidth
camera1_preview provided at 384x216 512Kbps
camera1_setup provided at 1920x1080 2MBps

Both are provided at the original source (i.e. bypass)

Altering Sever.xml to:

``
<OutputProfile>
	<Name>stream_bypass</Name>
	<OutputStreamName>${OriginStreamName}</OutputStreamName>
	<Encodes>
		<Audio>
			<Bypass>true</Bypass>
		</Audio>
		<Video>
			<Bypass>true</Bypass>
		</Video>
	</Encodes>
</OutputProfile>
``

**Server (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - OvenMediaEngine Version: v0.14.14
 - Branch: master

**Player (please complete the following information):**
 - Device: OvenPlayer
 - OS: Linux
 - Browser Chromium
 - Version 86

**Comment by getroot** [comment]
Please upload the entire Server.xml file and the entire log file. And let me know how you used the play URL.

**Comment by mrw-s** [comment]
[Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/9953893/Server.xml.txt)
[ovenmediaengine_transc_same.log](https://github.com/AirenSoft/OvenMediaEngine/files/9954143/ovenmediaengine_transc_same.log)

I am playing using OvenPlayer with the URLs as follows:

wss://media-server1.xxx.com:3334/app/camera1
wss://media-server1.xxx.com:3334/app/camera1_setup
wss://media-server1.xxx.com:3334/app/camera1_record

In Safari webrtc log/Chrome webrtc-internals I can see that all three urls have the same as stream settings as wss://media-server1.xxx.com/app/camera1 - i.e. (384x216 25fps 512kbps) for camera1_setup and camera1_record.

**Comment by getroot** [comment]
You requested to play `wss://media-server1.xxx.com:3334/app/camera1` and according to the settings, camera1, camera1_record, camera1_setup output streams were created. However, since these streams were unused (no one was playing), they were all dropped according to the settings.

Check out the log below.

```
[2022-1-07 17:22:50.223] W [StreamCollector:16490] Provider | application.cpp:144 | #default#app/camera1(100) stream will be deleted because it hasn't been used for 15489 milliseconds
[2022-1-07 17:22:50.223] I [StreamCollector:16490] Provider | stream_motor.cpp:181 | #default#app/camera1(100) stream has deleted from 0 StreamMotor
```

After all streams have been deleted, you requested to play wss://media-server1.xxx.com:3334/app/camera1_setup and `camera1_setup`, `camera1_setup_setup`, `camera1_setup_record ` were created according to the settings. The camera1_setup stream is bypass.

Set `UnusedStreamDeletionTimeout `to a high value to prevent the stream from being deleted for an extended period of time.

```
<Origins>
  <Properties>
    <NoInputFailoverTimeout>3000</NoInputFailoverTimeout>
    <UnusedStreamDeletionTimeout>60000</UnusedStreamDeletionTimeout>
  </Properties>
```
