### ISSUE TITLE
RTSP Pulled origin URL mangled with suffix of ${OriginStreamName}

### ISSUE THREAD

**Issue by mrw-s** [AirenSoft/OvenMediaEngine#939]
**Describe the bug**
When configuring additional OutputProfiles using the macro $ {OriginStreamName} and suffixing an identifier - e.g. $ {OriginStreamName}_preview, the '_preview' is appended to the source stream URL for an RTSP pulled source. This causes the RTSP url to be invalid for the source camera.

e.g. for :

``
<Origin>
        <Location>/app/camera1</Location>
        <Pass>
                <Scheme>rtsp</Scheme>
                <Urls><Url>camera1.xxx.com:554/profile2/media.smp</Url></Urls>
        </Pass>
</Origin>
``

$ {OriginStreamName}_preview causes the url for the stream camera1_preview to be:

rtsp://camera1.xxx.com:554/profile2/media.smp_preview

I can see how this might be useful to map different stream to different source URLs for the same source, but this breaks the use case where the same RTSP pulled source is streamed at differing outputs. Another <Origin> can always be added to cater for a different source stream from the same device.

This is caused by the following code at line 677 in projects/orchestrator/orchestrator_internal.cpp:

					// Append remaining_part
					url_part.Append(remaining_part);

**To Reproduce**
Configure an RTSP pulled source and two OutputProfiles, one with the name $ {OriginStreamName} and one with the name ${OriginStreamName}_xxx

**Expected behavior**
The same URL is used to connect to the Origin, irrespective of the suffix for $ {OriginStreamName}

**Server (please complete the following information):**
 - OS: Ubuntu 18 LTS
 - OvenMediaEngine Version: v0.14.14
 - Branch: master

**Player (please complete the following information):**
 - Device: Linux
 - OS: Ubuntu 18 LTS
 - Browser Chrome
 - Version v106

**Comment by getroot** [comment]
Setting `<Origin> <Location>/app/camera1_preview</Location>` above the existing `<Origin>` seems to solve the problem.

```
<Origin> <Location>/app/camera1_preview</Location> <Pass> <Scheme>rtsp</Scheme> <Urls><Url>camera1.xxx.com:554/profile2/media.smp</Url></ URLs> </Pass> </Origin>

<Origin> <Location>/app/camera1</Location> <Pass> <Scheme>rtsp</Scheme> <Urls><Url>camera1.xxx.com:554/profile2/media.smp</Url></ URLs> </Pass> </Origin>
```

**Comment by mrw-s** [comment]
Yes that seems to work around the issue. I think it would be better to have something like ${Suffix} to add into the RTSP URL to control this behaviour. e.g.

<Origin>
    <Location>/app/camera1</Location>
    <Pass>
        <Scheme>rtsp</Scheme>
        <Urls>
               <Url>camera1.xxx.com:554/profile2/${Suffix}/media.smp</Url>
        </Urls>
     </Pass>
</Origin>

 Also, I couldn't find this documented anywhere ?
