### ISSUE TITLE
Achieving low latency with LLHLS

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenMediaEngine#941]
Greetings

I'm discovering OME because I want to have low latency for my streams and on my current HLS servers, the latency is about 15s.

I've installed on my local machine, and I get 15-20s latency ; when installed on the server I'm using, it's about 30s.

The setup is very basic, as documented:

```
docker run --rm --name ovenmediaengine -p 80:80 -p 1935:1935 -p 4000:4000/udp -p 3333:3333 -p 3334:3334 -p 3478:3478 -p 9999:9999/udp airensoft/ovenmediaengine:latest
```

The upstream is send by ffmpeg:

```
ffmpeg -f x11grab -i  :0+0+0,0 -f pulse -i default -c:v libx264 -c:a aac -vf format=yuv420p -g 50 -b:v 4000k -maxrate 4000k -bufsize 8000k -f flv "rtmp://destination:1935/app/live"
```

(I've also tried OvenLiveKit)

And the display is ffplay:

```
ffplay http://destination:3333/app/live/llhls.m3u
```

(I've also tried SMPlayer and VLC.)

**PROBLEM**

Not having low latency

**EXPECTATION**

Having low latency

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

docker public latest (as of today).

- Encoder information

OLK and ffmpeg

- Player information

http://demo.ovenplayer.com or https://demo.ovenplayer.com gives "invalid playback URL".  Other play shows the stream with 15-20s delay.

- URL

rtmp://destination:1935/app/live
http://destination:3333/app/live/llhls.m3u

- Operating system and version

Ubuntu 19 / Debian 10

Thanks in advance

Regards

**Comment by getroot** [comment]
ffplay does not support LLHLS.
Test with OvenPlayer, ExoPlayer, hls.js, Safari, etc.
The default playback URL is not http://~~~/.m3u but http://destination:3333/app/live/llhls.m3u8 or
https://destination:3334/app/live/llhls.m3u8
Depending on the browser environment, only https may be played.

Upload your /var/log/ovenmediaengine/ovenmediaengine.log file for further analysis.

**Comment by gregfr** [comment]
Thanks for your answer. Indeed I realize my player application were not LL ready, I switched to the Oven player and it's working! Amazing work, thanks a lot!
