### ISSUE TITLE
HLS dumps add feature delay

### ISSUE THREAD

**Issue by Trungdo253** [AirenSoft/OvenMediaEngine#947]
add body api startHlsDump
```
{
          ...
         "duration": 10 
}
```
or the same ` ffmpeg -i ... -hls_flags append_list... `
I see youtube has a similar feature!
![image](https://user-images.githubusercontent.com/93107241/202144746-24938650-5629-4792-933d-7c8fc9fc86f3.png)

**Comment by getroot** [comment]
Adding a delay to a live broadcast makes sense, but why does the dump function need a delay?

**Comment by Trungdo253** [comment]
> Adding a delay to a live broadcast makes sense, but why does the dump function need a delay?

yes! add a delay  to a live broadcast 
add a delay the dump function to append dump but add delay to live broadcast then dont need add delay the dump
how to adding a delay to a live broadcast? 
thank you! 
sory my english so bad

**Comment by getroot** [comment]
If you are using OBS there is such a feature there. Since OME is streaming for low-latency, such a function is not very suitable.
