### ISSUE TITLE
Please help me with WebRTC URL to which Signed Policy is applied.

### ISSUE THREAD

**Issue by motolies** [AirenSoft/OvenMediaEngine#948]
**PROBLEM**

hello. I have a question about WebRTC input after applying signed policy.

After applying Signed Policy, rtmp works normally.

example > The domain and secretKey have been changed.
secret_key = my.video#@#
policy = {"url_expire":1672412400000}
rtmp://rtmp.my.com:1935/app/motolies?policy=eyJ1cmxfZXhwaXJlIjoxNjcyNDEyNDAwMDAwfQ&signature=GX4HoP49kBRMDgCyQZO21H9qTHE

However, when I try to use WebRTC input, it says that I received an invalid hash value.
The creation method is the same, and it is said that when generating a hash value, it is different regardless of direction and transport parameters as follows.

Here is the full url before generating the signature.
wss://rtmp.my.com:3334/app/motolies?policy=eyJ1cmxfZXhwaXJlIjoxNjcyNDEyNDAwMDAwfQ
wss://rtmp.my.com:3334/app/motolies?policy=eyJ1cmxfZXhwaXJlIjoxNjcyNDEyNDAwMDAwfQ&direction=send&transport=tcp

The error message when using OvenPlayer WebRTC Input is:
- in front
`Cannot create offer`

- OvenMediaEngine log
[2022-11-16 08:12:39.557] I [SPRtcSig-T3333:7708] Signalling | rtc_signalling_server.cpp:231  | New client is connected: <ClientSocket: 0x7fbbd4006d00, #4, Connected, TCP, Nonblocking, 180.229.139.199:50976>
[2022-11-16 08:12:39.567] W [SPRtcSig-T3333:7708] WebRTC Provider | webrtc_provider.cpp:274  | Signature value is invalid(expected : KQwPMlbL1mmN_4oWf39RND8au08 | input : 142hHx--L3V09wtbAQ9NTHgYcI0).
[2022-11-16 08:12:39.567] E [SPRtcSig-T3333:7708] Signalling | rtc_signalling_server.cpp:322  | Cannot find stream [#default#app/motolies]

**EXPECTATION**

How to generate a WebRTC input URL with a signed policy

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

I saw the manual and installed it directly on aws ec2, and the version is 0.14.14.

Additionally, in my Docker container, I confirmed that the WebRTC Input to which the Signed policy is applied works normally.
Also upload the docker container settings.

- Encoder information

https://demo.ovenplayer.com/demo_input.html

- Player information

http://demo.ovenplayer.com/demo.html

- Server.xml and Logs
[installed_Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10020054/installed_origin.xml.txt)
[docker_Server.xml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10020057/docker_origin.xml.txt)
[docekr-compose.yml.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10020072/compose.yml.txt)
[ovenmediaengine.log](https://github.com/AirenSoft/OvenMediaEngine/files/10020148/ovenmediaengine.log)

**Comment by getroot** [comment]
When OME creates a signature, it creates it based on the port the client connects to. So you need to create a signature based on the following URL.

ws://rtmp.my.com:3333/app/motolies?direction=send&transport=tcp&policy=eyJ1cmxfZXhwaXJlIjoxNjcyNDEyNDAwMDAwfQ

It is recommended to put policy at the end.

**Comment by motolies** [comment]
I was able to solve the problem with your answer.
thank you!
