### ISSUE TITLE
How do I end the flow?

### ISSUE THREAD

**Issue by woshiwoyali** [AirenSoft/OvenMediaEngine#95]
I use ffmpeg to successfully push the stream to the server, and can use the web to load and play, but how can I do it? I use ffmpeg to successfully push the stream to the server, and can use the web to load and play, but how can I do it? I can end the sent stream from the server. End from this server.

**Comment by getroot** [comment]
The server does not currently have a function to terminate the incoming stream. It will be developed with REST API in OME in the future. (But the priority is not high.)

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
