### ISSUE TITLE
RTMP Client 

### ISSUE THREAD

**Issue by AdamKraif** [AirenSoft/OvenMediaEngine#952]
Hi guys,

I would like to have the option to pull RTMP streams along with WEBRTC/HLS streams 
I know that it is possible to push RTMP to a different server, but this will create latency and a need for a different server.
Can RTMP packets be pulled or, if not, do you intend to add support, and when?

**Comment by getroot** [comment]
The RTMP Pull is on our backlog but has a very low priority so I don't know when I can start it.
How about using ffmpeg to pull rtmp and push it back to OME?

**Comment by AdamKraif** [comment]
> The RTMP Pull is on our backlog but has a very low priority so I don't know when I can start it. How about using ffmpeg to pull rtmp and push it back to OME?

It is possible, but the video will have a latency penalty.
Any source or docks on how I can do it myself?
Is it a complicated procedure after we already have the push architecture?

**Comment by getroot** [comment]
Once you've tried it, you'll see that RTMP pull and repush doesn't add that much latency. (I think 2~3 frames will be added at most.)

Anyway, OvenMediaEngine is open source, so you can modify and use this code at any time under the license. You can add an RTMP Pull Provider by referring to other providers (RTSP Pull Provider will be closest).

**Comment by naanlizard** [comment]
I can attest that forwarding does not add much latency. We forward to OME and webrtc is still very very low latency
