### ISSUE TITLE
The API for the PATCH, behaves as if it were a simple GET.

### ISSUE THREAD

**Issue by trapasso** [AirenSoft/OvenMediaEngine#953]
**Describe the bug**
The API for PATCH 'APPLICATION' and 'OUTPUT-PROFILE', behaves as if it were a simple GET.

**To Reproduce**
1. Through the API, POST a new VIRTUAL HOST.
2. Through the API, POST a new APPLICATION.
3. Through the API, PATCH the previous APPLICATION.
4. OvenMediaEngine returns a response that appears to be a simple GET of the APPLICATION or OUTPUT-PROFILE.

**Expected behavior**
I expected OvenMediaEngine to PATCH the APPLICATION.

**Server (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - OvenMediaEngine Version: [master]
 - Branch: [master]
 
**Additional context**
The problem is caused in this statement:
`if (HTTP_CHECK_METHOD(request_info.method, request->GetMethod()))`.

The statement:
```
 enum class Method : uint16_t
	{
		Unknown = 0x0000,

		Get = 0x0001,
		Head = 0x0002,
		Post = 0x0004,
		Put = 0x0008,
		Delete = 0x0010,
		Connect = 0x0020,
		Options = 0x0040,
		Trace = 0x0080,

		Patch = 0x0100,

		All = Get | Head | Post | Put | Delete | Connect | Options | Trace | Patch
	};
```
claims Method is 'uint16_t', but the macro:
`#define HTTP_CHECK_METHOD(method, flag)     OV_CHECK_FLAG((uint8_t)method, (uint8_t)flag)`

cast to uint8_t, a clear overflow.

With this simple patch:
```
--- a/src/projects/modules/http/http_private.h
+++ b/src/projects/modules/http/http_private.h
@@ -10,4 +10,4 @@
 
 #define OV_LOG_TAG                          "HttpServer"
 
-#define HTTP_CHECK_METHOD(method, flag)     OV_CHECK_FLAG((uint8_t)method, (uint8_t)flag)
+#define HTTP_CHECK_METHOD(method, flag)     OV_CHECK_FLAG((uint16_t)method, (uint16_t)flag)"
```
everything is alright.

Many thanks in advance.

**Comment by getroot** [comment]
Thank you very much! If you submit a pull request, I will merge it.

**Comment by trapasso** [comment]
I take advantage of this issue for a question.
Why has the development of virtual host storage, inserted with the API, been interrupted and eliminated?
Thank you very much.

**Comment by getroot** [comment]
Does the virtual host storage mean the ability to keep the settings changed by the API permanently? OME was having a lot of problems with that feature and we stopped development for the time being to focus on other features.

**Comment by trapasso** [comment]
I meant exactly that feature.
Can I ask, briefly, what kind of problems this involved?
