### ISSUE TITLE
Browser Preflight Request blocked due to unsuccessful HTTP status code.

### ISSUE THREAD

**Issue by BCordleRossVideo** [AirenSoft/OvenMediaEngine#957]
**Describe the bug**
I'm attempting to send a fetch() request to the REST API in order to retrieve a list of currently active streams. Before sending the GET request, the browser automatically sends a request with Method:OPTIONS in order to ensure the server allows cross-origin requests. The browser doesn't pass the Authorization header with the OPTIONS request, so the server responds with a 403 unauthorized error, preventing the browser from ever sending the GET request with the Authorization header.

**To Reproduce**
1. On an HTML page, add the following:
```
        let url = "http://[URL]:8081/v1/vhosts/default/apps/app/streams"
        fetch(url, {
            method: 'GET',
            headers: {
                'authorization': 'Basic b21lLWFjY2Vzcy10b2tlbg==' //Or whatever your auth is
            }
        }).then(responseJson =>{
            let streams = JSON.parse(responseJson._bodyInit);
            console.log('streams: ', streams);
        });
```
2. Load that html page and look at Dev Tools to see if the GET request was made.

**Expected behavior**
The API should reply to OPTIONS requests with a 200 "OK" response.  This would tell the browser it is ok to proceed with it's GET request.

**Logs**
From Browser:
Access to fetch at 'http://[IP ADDRESS]:8081/v1/vhosts/default/apps/app/streams' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

From OME Docker Container:
[2022-11-30 20:56:17.772] W [SPAPISvr-T8081:43] APIController | root_controller.cpp:95   | HTTP error occurred: [HTTP] Authorization header is required to call API (403)
[2022-11-30 20:56:17.772] E [SPAPISvr-T8081:43] HttpServer | http_exchange.cpp:43   | 
[Client] HttpConnection(0x7f6a1202e610) : HTTP/1.1 <ClientSocket: 0x7f6a10602c10, #49, Connected, TCP, Nonblocking, 73.131.94.210:53547> TLS(Disabled) [Duration] 0 
[Request] URL(http://[IP ADDRESS]:8081/v1/vhosts/default/apps/app/streams) Method(OPTIONS) Version(1.1) Request Time(2022-11-30T20:56:17.772+00:00)
[Response] Status(403) Sent Size(379) Response Time(2022-11-30T20:56:17.772+00:00)

**Server (please complete the following information):**
 - OS: Amazon ec2 linux amd64 instance running Docker 20.10.12
 - OvenMediaEngine Version: airensoft/ovenmediaengine:latest
 - Branch: latest

**Player (please complete the following information):**
 - Device: Windows Laptop
 - OS: Windows
 - Browser: Chrome
 - Version [107.0.5304.122 (Official Build) (64-bit)

**Additional context**
I added my Origin ip address into <CrossDomains> area of Server.xml but that doesn't seem to solve the issue.

**Comment by dimiden** [comment]
@BCordleRossVideo 
I've been so busy that I'm finally answering you. I'm sorry for the late reply.
Currently, OME API does not support ```OPTIONS``` method, so calling directly from the browser cause CORS error as you said. I'm planning to develop this feature soon.

**Comment by dimiden** [comment]
@BCordleRossVideo 
Now the API server can handles ```OPTIONS``` request. Thank you for your patience :) 691748d9385e647fa682d403c40d70985c6c5087
