### ISSUE TITLE
Wildcard support in OriginMap

### ISSUE THREAD

**Issue by rajiv-agarwal-tesco** [AirenSoft/OvenMediaEngine#958]
**Is your feature request related to a problem? Please describe.**
I am trying to configure OvenMedia to work with multiple rtsp sources. The configuration file get unnecessarily verbose which (in my case) can be avoided with wildcards

**Describe the solution you'd like**
I would like to able to use wildcards to configure OriginMap 

**Describe alternatives you've considered**
None yet. Please suggest if any

**Additional context**
Current:
><Server>
    <VirtualHosts>
        <VirtualHost>
            <Origins>
                <Origin>
                    <Location>/vids/abc</Location>
                    <Pass>
                        <Scheme>rtsp</Scheme>
                        <Urls>
                            <Url>source:554/abc</Url>
                        </Urls>
                    </Pass>
                </Origin>
                <Origin>
                    <Location>/vids/xyz</Location>
                    <Pass>
                        <Scheme>rtsp</Scheme>
                        <Urls>
                            <Url>source:554/xyz</Url>
                        </Urls>
                    </Pass>
                </Origin>
                ...
            </Origins>
        </VirtualHost>
    </VirtualHosts>
</Server>

Expected:
> <Server>
    <VirtualHosts>
        <VirtualHost>
            <Origins>
                <Origin>
                    <Location>/vids/*</Location>
                    <Pass>
                        <Scheme>rtsp</Scheme>
                        <Urls>
                            <Url>source:554/*</Url>
                        </Urls>
                    </Pass>
                </Origin>
            </Origins>
        </VirtualHost>
    </VirtualHosts>
</Server>

**Comment by getroot** [comment]
By default, OriginMaps act as wildcards. The following settings will achieve what you want.

```
<VirtualHosts>
    <VirtualHost>
        <Origins>
            <Origin>
                <Location>/vids/</Location>
                <Pass>
                    <Scheme>rtsp</Scheme>
                    <Urls>
                        <Url>source:554/</Url>
                    </Urls>
                </Pass>
            </Origin>
        </Origins>
    </VirtualHost>
</VirtualHosts>
```

**Comment by rajiv-agarwal-tesco** [comment]
This really helpful. Thanks a bunch!
Is this captured in your documentation that I can keep as a reference?

**Comment by getroot** [comment]
Like this?
https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering#rules-for-generating-origin-url

**Comment by rajiv-agarwal-tesco** [comment]
Close enough.
Can I recommend having the above link and/or an example in the Configuration documentation - 
https://airensoft.gitbook.io/ovenmediaengine/configuration#origins
Something along these lines -
```
<Origins>
    <Origin>
        <Location>/app/stream</Location>
        <Pass>
            <Scheme>ovt</Scheme>
            <Urls><Url>origin.com:9000/app/stream_720p</Url></Urls>
        </Pass>
    </Origin>
    <Origin>
        <Location>/app/</Location>
        <Pass>
            <Scheme>ovt</Scheme>
            <Urls><Url>origin.com:9000/app/</Url></Urls>
        </Pass>
    </Origin>
    <Origin>
        <Location>/rtsp/stream</Location>
        <Pass>
            <Scheme>rtsp</Scheme>
            <Urls><Url>rtsp-server.com:554/</Url></Urls>
        </Pass>
    </Origin>
    <Origin>
        <Location>/</Location>
        <Pass>
            <Scheme>ovt</Scheme>
            <Urls><Url>origin2.com:9000/</Url></Urls>
        </Pass>
    </Origin>
    <Origin>
        <!-- Matches any stream request /edge_app/*  to  origin.com:9000/origin_app/* -->
        <!-- ref: https://airensoft.gitbook.io/ovenmediaengine/origin-edge-clustering#rules-for-generating-origin-url -->
        <Location>/edge_app/</Location>
        <Pass>
            <Scheme>rtsp</Scheme>
            <Urls><Url>rtsp-server2.com:554/origin_app/</Url></Urls>
        </Pass>
    </Origin>
</Origins>
```
I am closing this issue. Thank you @getroot !
