### ISSUE TITLE
How can I view the addresses of all streams on a video server?

### ISSUE THREAD

**Issue by woshiwoyali** [AirenSoft/OvenMediaEngine#96]
I push a lot of streams to the server at the same time. How can I view all the stream addresses on the server and end one of them?

**Comment by getroot** [comment]
You can get the stream information created and deleted in the ovenmediaengine.log. But there is no function to terminate one of them. Check the following URL for information about the log. (Dev branch is the latest source.) https://airensoft.gitbook.io/ovenmediaengine/v/0.10.0/logs-and-statistics

**Comment by getroot** [comment]
This issue has been closed since it has been inactive for quite some time. If you want to continue discussing this issue, please feel free to reopen it.
