### ISSUE TITLE
addTransceiver instead of addTrack produces a "Forbidden" result with WebRTC

### ISSUE THREAD

**Issue by danrossi** [AirenSoft/OvenMediaEngine#960]
I recently changed my peering library to use addTransceiver instead of addTrack for WebRTC stream tracks. And after doing this I started getting "Forbidden" error messages returned. 

So when setting up the connection this produces a fault

```
 const transceiverInit = {
                "video": {
                    direction: this.disableVideo ? "inactive" : "sendonly"
                },
                "audio": {
                    direction: this.disableAudio ? "inactive" : "sendonly"
                }
            };

            if (this.simulcast && this.sendEncodings.length) transceiverInit.video.sendEncodings = this.sendEncodings;

            stream.getTracks().forEach(track => {
                const init = Object.assign({}, transceiverInit[track.kind], { streams: [stream] });
                peerconnection.addTransceiver(track, init);
            });
```

This doesn't return an error

```
stream.getTracks().forEach(track => {
   peerconnection.addTrack(track, stream);
});
```

The error code

```
{code: 403, error: 'Forbidden'}
```

**Comment by getroot** [comment]
What are you trying this for?

**Comment by danrossi** [comment]
Instead of doing the old way addTrack Ive changed my internal peer to use transceivers to setup simulcast and set its direction. Its to support other servers that support simulcast. Seems the server doesnt support that so need a configuration to use addTrack instead ?

**Comment by getroot** [comment]
OME does not allow clients to specify direction in SDP negotiations with OME, and OME does not yet support Simulcast.
