### ISSUE TITLE
Performance Tuning 500view error ice find binding

### ISSUE THREAD

**Issue by NkInKaIgIe** [AirenSoft/OvenMediaEngine#962]
use transport=tcp
run OvenRtcTester.go -url ws://X.X.X.X:13333/app/stream -n 500 to test
ERROR:
ice find binding 
HELP:
is there any way to solve this problem.. need help
![image](https://user-images.githubusercontent.com/96049216/205553538-f96f9faf-b655-4790-a064-e16d9d98cafc.png)

**Comment by getroot** [comment]
Please update the content according to the form so that we can analyze this issue.
Your hardware/NIC specifications, Server.xml file and kernel tuning (https://airensoft.gitbook.io/ovenmediaengine/troubleshooting#5-2.-tuning-your-linux-kernel), CPU share per thread (https://airensoft.gitbook.io/ovenmediaengine/troubleshooting#5-2.-tuning-your-linux-kernel) ://airensoft.gitbook.io/ovenmediaengine/performance-tuning#monitoring-the-usage-of-threads), and the quality of the output stream (bitrate, FPS), etc., so that someone can help you. there is.

**Comment by NkInKaIgIe** [comment]
@getroot 
Cpu

![image](https://user-images.githubusercontent.com/96049216/205574532-9b6b28e0-477c-448a-97c5-3a210e4e683d.png)

Speedtest network

![image](https://user-images.githubusercontent.com/96049216/205576046-35672f45-1147-4833-a62c-21de1042f9d8.png)

config kernel
cat /etc/sysctl.conf

![image](https://user-images.githubusercontent.com/96049216/205576467-f8408355-6f62-4cd6-9fc6-ecdb35498fa8.png)

cat /etc/security/limits.conf

![image](https://user-images.githubusercontent.com/96049216/205576747-92c45f1c-bddc-4b84-9a90-196cbb4684e5.png)


Server.xml
[Server.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10151579/Server.txt)

**Comment by getroot** [comment]
Your CPU is 1 core? Hmm... Can 1 core handle 500 sessions? Please upload the ovenmediaengine.log file for an accurate analysis. And we also need cpu usage per thread.

**Comment by NkInKaIgIe** [comment]
@getroot 
16core 
![image](https://user-images.githubusercontent.com/96049216/205798173-f8dbe25b-f118-4dd3-b52c-6823d91659df.png)

file log 
[ovenmediaengine-log.txt](https://github.com/AirenSoft/OvenMediaEngine/files/10162188/ovenmediaengine-log.txt)

i'm trying with a count of 200 
![image](https://user-images.githubusercontent.com/96049216/205812344-6745d745-a090-4f26-8489-a83de2eb4ef1.png)

**Comment by getroot** [comment]
You seem to have configured Origin-Edge. Does Origin work on other servers? And where does your tester work?

Your stream is 6Mbps. And your network seems to be 1Gbps (see your network capture).
Then your server cannot hold 200 people. (6*200 = 1.2Gbps)

**Comment by getroot** [comment]
I don't think this is an OME issue, so I won't analyze it until more information is provided.

Measure your OME server and network performance and OvenRtcTester server and network performance. OvenRtcTester also uses a lot of CPU and network, so you need to adjust this too. (Usually I use multiple OvenRtcTesters.)

**Comment by NkInKaIgIe** [comment]
@getroot 

HOME and Oven Tester server system with the same 16 core cpu and 1Gbps network. Can withstand 130 people for 6Mbps stream


OvenRtcTesters appeared 3 people failed

![image](https://user-images.githubusercontent.com/96049216/205838787-ceaca813-583f-45c3-9f99-51ec739d6640.png)

**Comment by getroot** [comment]
That's probably your server's performance limit. And your report shows that you have a session with very low delay and FPS. This already means that the server's performance is not good enough. So your server cannot handle 130 sessions. It would be better to lower the bitrates or replace the NIC with 10G.

**Comment by NkInKaIgIe** [comment]
@getroot  thank you for your help .
