### ISSUE TITLE
llhsl abr playlist without transcoding

### ISSUE THREAD

**Issue by nephilime** [AirenSoft/OvenMediaEngine#966]
Good day,
My name is Alexander, nice to meet you.

I'm trying to use OvenMediaEngine in role llhsl abr playlist maker, without transcoding. 
I already have 3 quality (1080, 720, 480) made by ffmpeg in 3 different rtmp streams. And i cant find the way to explain it to server. 
Could you please help me to configure OvenMEdiaEngine to deal with it.

**Comment by getroot** [comment]
OME does not provide a function to combine different externally input streams into one ABR stream. Only transcoding within OME can be bundled with ABR.

**Comment by llspalex** [comment]
This would be a very useful feature.

**Comment by getroot** [comment]
For ABR to work well, codec settings and timestamps must be carefully matched. I can't expect timestamps from the input stream to be precisely matched. Even if OME binds external streams to ABR, it will only work if you're very lucky. This will also affect LLHLS Dump and many other features. I don't want OME's bulletin board to be full of these inquiries. And WebRTC ABRs should have more luck. So I have no plans for this.

If you really want this functionality, you can create 3 streams in OME and create your own llhls.m3u8 file.
