### ISSUE TITLE
Not able to push the stream after creating new vHost and Application using REST

### ISSUE THREAD

**Issue by rajkumar-rk** [AirenSoft/OvenMediaEngine#968]
**Describe the bug**
After creating a new vHost and Application through the REST interface, I cannot push the stream. Please review the logs that have been attached.

**To Reproduce**
Steps to reproduce the behaviour:
1. Created a new Virtual Host using "/v1/vhosts" API (vHost name as "abc")
2. Created a new Application under the newly created vHost using "/v1/vhosts/default/apps" API (Application name as "abc-app")
3. Set up the Target stream and start the push using "/v1/vhosts/abc/apps/abc-app:startPush" API . The parameters are as follows 
   {
    "id": "1234",
    "stream": {
        "name": "testsource",
        "tracks": "0,1,2"
    },
    "protocol": "rtmp",
    "url": "rtmp://a.rtmp.youtube.com/live2",
    "streamKey": "abcd-efgh-ijkl-mnop-qrst"
}
4. Following are my OBS settings
       Server : rtmp://domainname:1935/abc/abc-app
       Stream Key: testsource

**Expected behaviour**
We should be able to push the stream using OBS to the target stream. 

**Logs**
2022-12-08 05:32:53.842] E [SPRTMP-T1935:13665] RTMPProvider | rtmp_stream.cpp:269  | #default#abc/abc-app application does not exist
[2022-12-08 05:32:53.850] I [SPRTMP-T1935:13665] Provider | stream.cpp:63   | Unknown/(65) has been stopped playing stream
[2022-12-08 05:32:53.850] I [SPRTMP-T1935:13665] RTMPProvider | rtmp_provider.cpp:181  | The RTMP client has disconnected: [Unknown/], remote: <ClientSocket: 0x7f55ac0bf420, #65, Closed, TCP, Nonblocking, 103.231.7.194:62069>
[2022-12-08 05:43:05.538] W [SPAPISvr-T8081:13747] APIController | root_controller.cpp:95   | HTTP error occurred: [HTTP] Authorization header is required to call API (403)

**Comment by getroot** [comment]
My guess is that your abc-app doesn't have an RTMPPush publisher configured.

**Comment by getroot** [comment]
> Created a new Application under the newly created vHost using "/v1/vhosts/default/apps" API (Application name as "abc-app")

Did you create abc-app in /v1/vhosts/default/apps?

**Comment by getroot** [comment]
Ah, now I know what's wrong with this. vhost is a virtual host that is divided into domains. If you call rtmp://domainname:1935/abc/abc-app with rtmp, it doesn't enter vhost named abc. vhost is what separates domainname.

**Comment by rajkumar-rk** [comment]
> oesn't enter vhost named ab

Sorry, that was a typo. I have created the new Application using "/v1/vhosts/abc/apps" API (Application name as "abc-app" and "abc" as my new virtual host)

**Comment by getroot** [comment]
When creating a vhost, set a different IP or domain. And you have to transmit to that domain in rtmp so you can use the newly created vhost. You cannot select a vhost by using a URL like rtmp://domain:1935/<vhost>/app in OBS.

**Comment by rajkumar-rk** [comment]
Understood. Thanks a lot.

Another question, can I create a new application under the "default" Virtual Host like "/v1/vhosts/default/apps" (application name as "abc-app")? Because I tried to do so, and got 403 status code as "[HTTP] The VirtualHost is read-only: [default] (403)"

**Comment by getroot** [comment]
no. The 403 error is intentional. This is a remnant of another feature in the past, but it hasn't been improved yet. This will be improved later.

**Comment by rajkumar-rk** [comment]
Understood, let me try with the new Virtual host. Appreciated...!
