### ISSUE TITLE
HLS Playlist gives 404 after stream reconnects

### ISSUE THREAD

**Issue by hernanrz** [AirenSoft/OvenMediaEngine#969]
**Describe the bug**
the llhls.m3u8 returns 404 for at least a minute after the stream is already live

**To Reproduce**
1. Run the default config with docker
2. Start a stream with OBS
3. Stop OBS for only a few seconds
4. Reconnect
5. m3u8 file returns 404 even though the stream is live

**Expected behavior**
m3u8 file should be available when stream reconnects

**Logs**
[Please upload the entire OvenMediaEngine.log. You may delete important personal information.](https://gist.github.com/hernanrz/d99a925e4aa551ad551955df82f0cea6)

**Server (please complete the following information):**
- Latest docker image

**Player (please complete the following information):**
 - Device: Desktop
 - OS: Windows11 pro
 - Browser Firefox
 - Version latest
 - Using the OME Demo player

**Comment by naanlizard** [comment]
I've just reproduced this myself. Perhaps my steps will shed some light.

Run OME with the default configuration like so: `docker run -d -p 1935:1935 -p 3333:3333 --name ovenmediaengine airensoft/ovenmediaengine:latest`

Start stream (with streamkey set to 1, so my url was domain.com:3333/app/1/llhls.m3u8 )

Open OMP demo page (insecure, in my case, as I did not install an SSL cert), insert stream URL

Stream plays, no problem

Stop stream in OBS. Player begins to buffer on demo page, console shows 404

Start stream in OBS. OMP continues to 404, though a `curl domain.com:3333/app/1/llhls.m3u8` DOES provide the llhls playlist fairly quickly.

So perhaps it is an OMP issue with caching or something?

**Comment by naanlizard** [comment]
For our in-production problem, we'll keep testing and see if it's something we're doing, in case it isn't related to the demo page bug

**Comment by hernanrz** [comment]
![image](https://user-images.githubusercontent.com/13426225/208517328-19de3f88-5d38-4020-9498-c63269ca7916.png)

I get this very strange behavior in the browser, this is with latest firefox and the demo player page. While the browser is continously showing 404 for the HLS playlist requests, replaying the same request with curl in the console works OK

**Comment by getroot** [comment]
Do you suspect a CORS error or mixed content error? Access to localhost may be blocked by your browser. Check the browser console for any error messages.

**Comment by naanlizard** [comment]
It happens on the ovenplayer demo page too 

I would expect Hernan to have checked the console already, when I tested this I just got 404s

**Comment by getroot** [comment]
I know that 404 errors occur. There might be a more detailed error message, so I asked hernanrz to check it.
And I've already heard that it happens in the ovenplayer demo. I was wondering if it also happens on the hls.js demo page.

Unfortunately I am unable to reproduce the issue in firefox. Are you using localhost as the domain and the browser is blocking it? Or maybe a cache?

![image](https://user-images.githubusercontent.com/17779085/208594496-4d36847a-d5bb-4021-bd88-f6d726b5c536.png)

**Comment by naanlizard** [comment]
I should clarify that hernan is my employee and we were working together on this. I only respond to help move things faster since we are in the Americas, time zones are tricky

it’s not related to localhost since it happened using a real domain too 

it might be an issue with the ome http server but I’m not sure how, we were thinking it might be some sort of browser or player cache too 

We’ll test with the other player tomorrow

**Comment by getroot** [comment]
Since there are no logs related to 404 in OME and it works with CURL, it seems unlikely that it is a server issue.
Please let me know how it works on Chrome or other browsers.

**Comment by getroot** [comment]
Oh I just reproduced this problem. I will analyze this problem in detail and report back to you. thanks!

**Comment by getroot** [comment]
The problem was that the session continued to hang on the old stream because the browser did not close the connection. I solved the problem by making the session refresh even in this situation. Thanks for your contribution!

**Comment by hernanrz** [comment]
Glad to see the problem was [fixed](469cd376e8f1ca2b25fca37201323136552fa6de), thanks for your hard work @getroot !

**Comment by naanlizard** [comment]
Deployed and tested, it seems fixed, thank you getroot!
