### ISSUE TITLE
Application name containing '/' (slash)

### ISSUE THREAD

**Issue by Roze** [AirenSoft/OvenMediaEngine#974]
Is it somehow possible to configure OME to work with App names containing '/' (slash)?

I have some odd blackbox-type devices (have no control over firmware) which  add 0/ or 1/ to the rtmp server uri (configured rtmp://server/app/ on the output becomes rtmp://server/app/0/stream).

On the OME side while:
```
<Application>
    <Name>app/0</Name>
```
works on the input stream validation (you can't push in anything besides app/0/stream) but everything further breaks:

```
OvenMediaEngine[15182]: [2022-12-13 11:55:26.205] E [SPRTMP-T1935:15200] RTMPProvider | rtmp_stream.cpp:1667 | Could not find application: stream(#default#app/0/0)
OvenMediaEngine[15182]: [2022-12-13 11:55:26.205] E [SPRTMP-T1935:15200] RTMPProvider | rtmp_stream.cpp:1544 | Input create fail -  stream(#default#app/0/0)
```

So far I've been using nginx-rtmp where on the server side I have configured both 'app' and 'app/0' (for the odd devices). 
Theoretically could push the rtmp streams to OME by normalizing the appname but I wondered if could do without nginx at all. 

Like maybe some "hack" in ResolveApplicationName/GetApplicationByName?

**Comment by getroot** [comment]
I haven't delved into it yet, but within the current OME this is going to take a lot of work.
This is expected to crash a lot in the RTMP module as well as elsewhere. For example, an LLHLS url would consist of https://host:port/<app name>/<stream name>/<abr file name> . This means that if the app name contains "/", another exception must be made to recognize the LLHLS url.
I judge that the efficiency of doing this is low compared to the effort it takes. Please let me know if you have any other comments.

**Comment by Roze** [comment]
Yes, I checked also the API and it seems a lot of things would break there too. So probably not worth and realistic to implement. Thank you for the response.
