### ISSUE TITLE
time out  switch rtmp connection to another network

### ISSUE THREAD

**Issue by NkInKaIgIe** [AirenSoft/OvenMediaEngine#975]
switch rtmp connection to another network, OME will receive log disconect after 60 seconds. is there a way to change 60 seconds to 15 seconds or 30 seconds?
BlockDuplicateStreamName set to true . 
When the RTMP connection is restored, it will repeat the connection again. After 1p of receiving the disconnect event, the rtmp will be reconnected.

**Comment by getroot** [comment]
Detecting a TCP disconnect is what the linux kernel is doing now. Currently, OME judges that it is normal even if no RTMP packets come in. (This is because it can be a really normal situation.)
