### ISSUE TITLE
Session Key in m3u8

### ISSUE THREAD

**Issue by vasudevavarun** [AirenSoft/OvenMediaEngine#976]
**PROBLEM**

Is their anyway by which I can remove the session keys from m3u8 playlists, I'm using LLHLS on my CDN but most of the requests are going to OME due to session query string.

I'm using playlist Rendition to generate abr playlist

`#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="4",NAME="none",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="/app/vVX25/chunklist_4_audio_tDZzvlaV_llhls.m3u8?session=38_bfFd9028"

#EXT-X-STREAM-INF:BANDWIDTH=428000,RESOLUTION=256x144,FRAME-RATE=30.0,CODECS="avc1.42c00c,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_3_video_tDZzvlaV_llhls.m3u8?session=38_bfFd9028
#EXT-X-STREAM-INF:BANDWIDTH=628000,RESOLUTION=512x288,FRAME-RATE=30.0,CODECS="avc1.42c015,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_2_video_tDZzvlaV_llhls.m3u8?session=38_bfFd9028
#EXT-X-STREAM-INF:BANDWIDTH=828000,RESOLUTION=640x360,FRAME-RATE=30.0,CODECS="avc1.42c01e,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_1_video_tDZzvlaV_llhls.m3u8?session=38_bfFd9028
#EXT-X-STREAM-INF:BANDWIDTH=1128000,RESOLUTION=1280x720,FRAME-RATE=30.0,CODECS="avc1.42c01f,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_0_video_tDZzvlaV_llhls.m3u8?session=38_bfFd9028`

**EXPECTATION**

`#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="4",NAME="none",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="/app/vVX25/chunklist_4_audio_tDZzvlaV_llhls.m3u8?session=38_bfFd9028"

#EXT-X-STREAM-INF:BANDWIDTH=428000,RESOLUTION=256x144,FRAME-RATE=30.0,CODECS="avc1.42c00c,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_3_video_tDZzvlaV_llhls.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=628000,RESOLUTION=512x288,FRAME-RATE=30.0,CODECS="avc1.42c015,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_2_video_tDZzvlaV_llhls.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=828000,RESOLUTION=640x360,FRAME-RATE=30.0,CODECS="avc1.42c01e,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_1_video_tDZzvlaV_llhls.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1128000,RESOLUTION=1280x720,FRAME-RATE=30.0,CODECS="avc1.42c01f,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_0_video_tDZzvlaV_llhls.m3u8`

**ENVIRONMENTAL INFORMATION**
Using master

- Encoder information

What encoder are you using?(e.g. OBS 10.22) And how is the codec set on that encoder? OBS(h264)

- Player information

Same behavior on any player including ovenmedia player

- URL

https://x.x.x.x/app/vVX25/master.m3u8

- Operating system and version

Ubuntu 22.04

**Comment by getroot** [comment]
Set OriginMode to true when using LLHLS with CDN. However, in OriginMode, AdmissionWebhooks and SignedPolicy do not work and the number of concurrent users cannot be counted normally.

https://github.com/AirenSoft/OvenMediaEngine/blob/a57803e279d889d8e1727ec3350a65d505228f12/misc/conf_examples/Origin.xml#L308

**Comment by vasudevavarun** [comment]
Hi @getroot,

Thank you the prompt reply, The " <OriginMode>true</OriginMode> " is not working with ABR stream.
It is decoding audio only.

Without OriginMode
`#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="4",NAME="none",AUTOSELECT=YES,DEFAULT=YES,CHANNELS="2",URI="/app/vVX25/chunklist_4_audio_j6strK1J_llhls.m3u8?session=36_mgNvJWCG"

#EXT-X-STREAM-INF:BANDWIDTH=428000,RESOLUTION=256x144,FRAME-RATE=30.0,CODECS="avc1.42c00c,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_3_video_j6strK1J_llhls.m3u8?session=36_mgNvJWCG
#EXT-X-STREAM-INF:BANDWIDTH=628000,RESOLUTION=512x288,FRAME-RATE=30.0,CODECS="avc1.42c015,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_2_video_j6strK1J_llhls.m3u8?session=36_mgNvJWCG
#EXT-X-STREAM-INF:BANDWIDTH=828000,RESOLUTION=640x360,FRAME-RATE=30.0,CODECS="avc1.42c01e,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_1_video_j6strK1J_llhls.m3u8?session=36_mgNvJWCG
#EXT-X-STREAM-INF:BANDWIDTH=1128000,RESOLUTION=1280x720,FRAME-RATE=30.0,CODECS="avc1.42c01f,mp4a.40.2",AUDIO="4"
/app/vVX25/chunklist_0_video_j6strK1J_llhls.m3u8?session=36_mgNvJWCG`

With Origin-Mode

`#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS

#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
/app/vVX25/chunklist_0_audio_l6kzIxV8_llhls.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
/app/vVX25/chunklist_0_audio_l6kzIxV8_llhls.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
/app/vVX25/chunklist_0_audio_l6kzIxV8_llhls.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=128000,CODECS="mp4a.40.2"
/app/vVX25/chunklist_0_audio_l6kzIxV8_llhls.m3u8`

**Comment by getroot** [comment]
No, it works perfectly. Check if it is cached or if the settings are applied well.

**Comment by getroot** [comment]
You can see that the seesion key has disappeared in the Origin-Mode you uploaded. Is something else a problem?

**Comment by getroot** [comment]
Oh you mean the video disappears in origin mode? I have been using this for months and have never had such a problem. Upload your Server.xml and ovenmediaengine.log files.
