### ISSUE TITLE
Dual OvenMediaEngine setup for two way communication and desktop sharing, timing drift

### ISSUE THREAD

**Issue by kode54** [AirenSoft/OvenMediaEngine#977]
**PROBLEM**

We're currently using OvenMediaEngine, or at least tried using it, to replace two way video chat, and add toggleable desktop sharing, using OBS Studio to RTMP into OME, then watching it with a local install of the web interface. The problem we had was, that as the connection was used, it would gradually drift in timing and become ever more latent, until there was at least several seconds of latency. This usually happened within 10-15 minutes of starting the stream sessions.

**EXPECTATION**

We would like to have a low latency video session with OBS Studio, as janky as that may seem, and it seemed like the only desktop environment agnostic setup we had going.

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

0.14.17-1 from the Arch community package. We haven't tested the Master branch, and weren't running it under Docker.

- Encoder information

My end: OBS Studio 28.1.2 from Arch community package, obs-gstreamer 0.3.5-1 from the AUR, gstreamer-vaapi 1.20.4-1 from Arch extra, and mesa-tkg-git 23.0.0_devel.164361.a093a44d457-1 with about 5 unmerged patches unrelated to VAAPI. RX 480 8GB. Pushing to remote end's OvenMediaEngine via RTSP over Tailscale.
The other end: OBS Studio 28.1.2 from Arch community, NVidia drivers, possibly NVEnc backend, not sure. Pushing to my end's OvenMediaEngine via RTSP over Tailscale.

- Player information

My end: Firefox 108.0.1 connected to the OvenMediaEngine hosting page, feeding off my local OME server.
Remote end: Google Chrome connected to their local OME hosting page, feeding off their local OME server.

- URL

rtmp:://<machine name>.<tailnet name>.ts.net/ with a "video" resource name, with different machine IDs depending on which end
https://<local machine name>.<tailnet name>.ts.net/ with a path to a local Caddy server hosting the demo page, configured to point to the local machine for video stream source on the playback end

- Operating system and version

Arch Linux on both ends at the time. My end is running a modified configuration patched kernel, linux-tkg, with default CFS scheduler, and was running 6.1-rc8 at the time. Remote end was running the stock 6.0.x `linux` release kernel package.

**SETUP INFORMATION AND LOGS**

[Server.xml.gz](https://github.com/AirenSoft/OvenMediaEngine/files/10250536/Server.xml.gz)
[ovenmediaengine.log.gz](https://github.com/AirenSoft/OvenMediaEngine/files/10250537/ovenmediaengine.log.gz)

**OTHER HELPFUL INFORMATION**

We probably won't be using this setup any longer, at least not any time in the foreseeable future, but I thought it would be worth requesting help to see if we're doing anything wrong with our setup to cause a gradually increasing latency on both ends.

**Comment by getroot** [comment]
What exactly is the problem? Is the latency increasing over time?

Looking at the log, it seems that the keyframe interval is very long. I recommend changing this to 1 second in OBS.

**Comment by kode54** [comment]
I'll think about that next time, if there is a next time within the foreseeable future.
