### ISSUE TITLE
Recording API not working

### ISSUE THREAD

**Issue by kolik29** [AirenSoft/OvenMediaEngine#979]
Run OME from docker and setup Server.xml from https://airensoft.gitbook.io/ovenmediaengine/recording-experiment

`

	...
	<Bind>
		<Managers>
			<API>
				<Port>8081</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>
		...
	</Bind>

	<VirtualHosts>
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			...
			<Applications>
				<Application>
					...
					<Publishers>
						...
						<FILE>
							<RootPath>/mnt/shared_volumes</RootPath>
							<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
						</FILE>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>

	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
		</Host>
		<API>
			<AccessToken>your_access_token</AccessToken>
			<CrossDomains>
				<Url>*</Url>
			</CrossDomains>
		</API>
	</Managers>
`

Run docker command:
`docker run -d \
-v $(pwd)/records:/mnt/shared_volumes \
-v $(pwd)/config:/opt/ovenmediaengine/bin/edge_conf \
-v $(pwd)/config:/opt/ovenmediaengine/bin/origin_conf \
-p 1935:1935 -p 8081:8081 -p 4000:4000/udp -p 3333:3333 -p 3334:3334 -p 3478:3478 -p 9000:9000 -p 9999:9999/udp \
airensoft/ovenmediaengine:0.14.17`

Streaming works, but recording does not:
`
curl -X POST -H 'Authorization: Basic b21lLWFjY2Vzcy10b2tlbg==' -d '{
  "id": "custom_id",
  "stream": {
    "name": "test",
    "tracks": [ 100, 200 ]
  },
  "filePath" : "/path/to/save/recorded/file_${Sequence}.ts",
  "infoPath" : "/path/to/save/information/file.xml",
  "interval" : 60000,    # Split it every 60 seconds
  "schedule" : "0 0 */1" # Split it at second 0, minute 0, every hours. 
  "segmentationRule" : "continuity"

}' http://localhost:8081/v1/vhosts/default/apps/app:startRecord
curl: (56) Recv failure: Connection terminated by other party
`

What I need setup for stream record?

Last message from log:
`[2022-12-18 05:49:19.201] I [OvenMediaEngine:1] APIServer | api_server.cpp:166  | API Server is disabled`

**Comment by getroot** [comment]
It seems that the API server is not enabled. You should check if your Server.xml is properly applied to the Docker container. Please upload the entire ovenmediaengine.log file.

**Comment by kolik29** [comment]
> It seems that the API server is not enabled. You should check if your Server.xml is properly applied to the Docker container. Please upload the entire ovenmediaengine.log file.

The problem solved itself.  After a few days everything started working.
Now when I send a request, I get:
` {"message":"[HTTP] [JSON] * Line 1, Column 37\n Missing '}' or object member name\n (400)","statusCode":400}`

My Server.xml:
`<?xml version="1.0" encoding="UTF-8" ?>

<Server version="8">
	<Name>OvenMediaEngine</Name>
	
	<Type>origin</Type>
	
	<IP>*</IP>
	<PrivacyProtection>false</PrivacyProtection>
	
	<StunServer>stun.ovenmediaengine.com:13478</StunServer>

	<Modules>
		
		<HTTP2>
			<Enable>true</Enable>
		</HTTP2>

		<LLHLS>
			<Enable>true</Enable>
		</LLHLS>

		
		<P2P>
			
			<Enable>false</Enable>
			<MaxClientPeersPerHostPeer>2</MaxClientPeersPerHostPeer>
		</P2P>
	</Modules>

	
	<Bind>
		
		<Managers>
			<API>
				<Port>8081</Port>
				<WorkerCount>1</WorkerCount>
			</API>
		</Managers>		
		<Providers>
			
			<RTSPC>
				<WorkerCount>1</WorkerCount>
			</RTSPC>
			<OVT>
				<WorkerCount>1</WorkerCount>
			</OVT>
			
			<RTMP>
				<Port>${env:OME_RTMP_PROV_PORT:1935}</Port>
				<WorkerCount>1</WorkerCount>
			</RTMP>
			<SRT>
				<Port>${env:OME_SRT_PROV_PORT:9999}</Port>
				<WorkerCount>1</WorkerCount>
			</SRT>
			<MPEGTS>
				
				<Port>${env:OME_MPEGTS_PROV_PORT:4000/udp}</Port>
			</MPEGTS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_WEBRTC_SIGNALLING_PORT:3333}</Port>
					<TLSPort>${env:OME_WEBRTC_SIGNALLING_TLS_PORT:3334}</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<TcpRelay>${env:OME_WEBRTC_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
					<IceCandidate>*:10006/udp</IceCandidate>
				</IceCandidates>
			</WebRTC>
		</Providers>

		<Publishers>
			
			<OVT>
				<Port>${env:OME_ORIGIN_PORT:9000}</Port>
				<WorkerCount>1</WorkerCount>
			</OVT>
			<LLHLS>
				
				<Port>${env:OME_LLHLS_STREAM_PORT:3333}</Port>
				<TLSPort>${env:OME_LLHLS_STREAM_TLS_PORT:3334}</TLSPort>
				<WorkerCount>1</WorkerCount>
			</LLHLS>
			<WebRTC>
				<Signalling>
					<Port>${env:OME_WEBRTC_SIGNALLING_PORT:3333}</Port>
					<TLSPort>${env:OME_WEBRTC_SIGNALLING_TLS_PORT:3334}</TLSPort>
					<WorkerCount>1</WorkerCount>
				</Signalling>
				<IceCandidates>
					<IceCandidate>*:10000-10005/udp</IceCandidate>
					<TcpRelay>${env:OME_WEBRTC_TCP_RELAY_ADDRESS:*:3478}</TcpRelay>
					<TcpForce>true</TcpForce>
					<TcpRelayWorkerCount>1</TcpRelayWorkerCount>
				</IceCandidates>
			</WebRTC>
		</Publishers>
	</Bind>

	<VirtualHosts>
		
		<VirtualHost include="VHost*.xml" />
		<VirtualHost>
			<Name>default</Name>
			
			<Distribution>ovenmediaengine.com</Distribution>
			
			
			<Host>
				<Names>
					
					<Name>*</Name>
				</Names>
				
			</Host>

			

			

			
			<Applications>
				<Application>
					<Name>app</Name>
					
					<Type>live</Type>
					<OutputProfiles>
						<HardwareAcceleration>true</HardwareAcceleration>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}</OutputStreamName>
							<Encodes>
								<Audio>
									<Bypass>true</Bypass>
								</Audio>
								<Video>
									<Bypass>true</Bypass>
								</Video>
							</Encodes>
						</OutputProfile>
						<OutputProfile>
							<Name>bypass_stream</Name>
							<OutputStreamName>${OriginStreamName}_h264</OutputStreamName>
							<Encodes>
								<Video>
									<Codec>h264</Codec>
									<Height>1080</Height>
									<Bitrate>5000000</Bitrate>
									<Framerate>30</Framerate>
								</Video>
								<Audio>
									<Codec>opus</Codec>
									<Bitrate>128000</Bitrate>
									<Samplerate>48000</Samplerate>
									<Channel>2</Channel>
								</Audio>
							</Encodes>
						</OutputProfile>
					</OutputProfiles>
					<Providers>
						<OVT />
						<WebRTC />
						<RTMP />
						<SRT />
						<RTSPPull />
						<MPEGTS>
							<StreamMap>
								
								<Stream>
									<Name>stream_${Port}</Name>
									<Port>4000</Port>
								</Stream>
							</StreamMap>
						</MPEGTS>
					</Providers>
					<Publishers>
						<AppWorkerCount>1</AppWorkerCount>
						<StreamWorkerCount>8</StreamWorkerCount>
						<OVT />
						<WebRTC>
							<Timeout>30000</Timeout>
							<Rtx>false</Rtx>
							<Ulpfec>false</Ulpfec>
							<JitterBuffer>false</JitterBuffer>
						</WebRTC>
						<HLS>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
						</HLS>
						<DASH>
							<SegmentDuration>5</SegmentDuration>
							<SegmentCount>3</SegmentCount>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							<UTCTiming />
						</DASH>
						<LLDASH>
							<SegmentDuration>5</SegmentDuration>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>
							<UTCTiming />
						</LLDASH>
						<Thumbnail>
							<CrossDomains>
								<Url>*</Url>
							</CrossDomains>	
						</Thumbnail>
						<FILE>
							<RootPath>/mnt/shared_volumes</RootPath>
							<FilePath>/${VirtualHost}/${Application}/${Stream}/${StartTime:YYYYMMDDhhmmss}_${EndTime:YYYYMMDDhhmmss}.ts</FilePath>
							<InfoPath>/${VirtualHost}/${Application}/${Stream}.xml</InfoPath>
						</FILE>
					</Publishers>
				</Application>
			</Applications>
		</VirtualHost>
	</VirtualHosts>

	<Managers>
		<Host>
			<Names>
				<Name>*</Name>
			</Names>
		</Host>
		<API>
			<AccessToken>ome-access-token</AccessToken>

			<CrossDomains>
				<Url>*</Url>
			</CrossDomains>
		</API>
	</Managers>
</Server>`

**Comment by getroot** [comment]
> Now when I send a request, I get:
> ` {"message":"[HTTP] [JSON] * Line 1, Column 37\n Missing '}' or object member name\n (400)","statusCode":400}`

The error message tells you that your json format is invalid. There is a problem with that if you asked as written above.

```
curl -X POST -H 'Authorization: Basic b21lLWFjY2Vzcy10b2tlbg==' -d '{
"id": "custom_id",
"stream": {
"name": "test",
"tracks": [ 100, 200 ]
},
"filePath" : "/path/to/save/recorded/file_${Sequence}.ts",
"infoPath" : "/path/to/save/information/file.xml",
"interval" : 60000, # Split it every 60 seconds
"schedule" : "0 0 */1" # Split it at second 0, minute 0, every hour.
"segmentationRule" : "continuity"

}' http://localhost:8081/v1/vhosts/default/apps/app:startRecord
```

Since json does not allow comments, you must remove the comments and separate "schedule" and "segmentationRule" with a comma.
```
{
"id": "custom_id",
"stream": {
"name": "test",
"tracks": [ 100, 200 ]
},
"filePath" : "/path/to/save/recorded/file_${Sequence}.ts",
"infoPath" : "/path/to/save/information/file.xml",
"interval" : 60000,
"schedule" : "0 0 */1",
"segmentationRule" : "continuity"
}
```
