### ISSUE TITLE
Stream none bitrate, ffmpeg was `non-existing PPS 0 referenced`

### ISSUE THREAD

**Issue by Trungdo253** [AirenSoft/OvenMediaEngine#984]
Problem: OME receive stream none bitrate video and audio so FFmpeg was `non-existing PPS 0 referenced`
![image](https://user-images.githubusercontent.com/93107241/209496709-e7ec44d5-dd77-4e14-8d3a-55d365216858.png)

Is there a way to block the stream when receiving the above data?

**Comment by getroot** [comment]
The bitrates information is only meta information sent by RTMP and is not required. Depending on the encoder, it may not be displayed because the way it is sent is different, and that has nothing to do with the PPS 0 warning.

**Comment by nums** [comment]
It seems that "non-existing PPS 0 referenced" occure when there is no keyframe sended on encoding side.

**Comment by getroot** [comment]
I'm closing this issue because it's inactive. Please reopen if you think further discussion is needed.
