### ISSUE TITLE
Can't stream for configured Application with RTSPPull

### ISSUE THREAD

**Issue by artempl** [AirenSoft/OvenMediaEngine#985]
**PROBLEM**

Can't run RTSPPull for configured Application.

For example purpose configured Server.xml is attached:
There 2 similar local origins (**local** and **push**) pointed to same rtsp stream. For one of it special Application is configured to tune some things. Problem is that stream from origin without Application is worked fine, i.e. ws://localhost:3333/local/ca315 is opened with Oven player fine. And NO streaming for ws://localhost:3333/push/ca315

**EXPECTATION**

RTSPPull for specific configured application works

**ENVIRONMENTAL INFORMATION**

- OvenMediaEngine Information

Own Docker image based on official airensoft/ovenmediaengine:latest

- Encoder information

Test RTSP server based on docker image aler9/rtsp-simple-server is used to produce rtsp streams

**SETUP INFORMATION AND LOGS**
[logs-n-conf.zip](https://github.com/AirenSoft/OvenMediaEngine/files/10315939/logs-n-conf.zip)

**Comment by getroot** [comment]
Because your Push Application doesn't have OutputProfiles. At a minimum, your Application should have OutputProfiles like the one below.

```
<OutputProfiles>
	<OutputProfile>
		<Name>bypass_stream</Name>
		<OutputStreamName>${OriginStreamName}</OutputStreamName>
		<Encodes>
			<Audio>
				<Name>bypass_audio</Name>
				<Bypass>true</Bypass>
			</Audio>
			<Video>
				<Name>bypass_video</Name>
				<Bypass>true</Bypass>
			</Video>
		</Encodes>
	</OutputProfile>
</OutputProfiles>
```

RTSP Pull works well because it creates and uses a default application if there is no application.

**Comment by artempl** [comment]
Thanks, Je-Heon! I confirm - with outputprofiles it works as expected.
