### ISSUE TITLE
Cannot enable REST API when using Docker

### ISSUE THREAD

**Issue by jlongo-encora** [AirenSoft/OvenMediaEngine#986]
**Describe the bug**
Cannot enable REST API when using Docker

**To Reproduce**
1. Copy origin_conf folder from Docker image to the host machine
a- Start Oven Media Engine using docker
b- Get container ID with `docker ps` command
c- Copy `/opt/ovenmediaengine/bin/origin_conf` from container to the current directory:
```
docker cp <containerID>:/opt/ovenmediaengine/bin/origin_conf .
```

2. Enable API in `origin_conf/Server.xml` as follows:
```
<?xml version="1.0" encoding="UTF-8" ?>
<Server version="8">
    ...
    <Bind>
        <!-- Enable this configuration if you want to use API Server -->
        <Managers>
            <API>
                <Port>${env:OME_API_PORT:8081}</Port>
                <WorkerCount>1</WorkerCount>
            </API>
       </Managers>
       ...
```
3. Start Oven Media Engine using Docker as follows:
```
docker run --rm \
  -p 1935:1935 \
  -p 3333:3333 \
  -p 3334:3334 \
  -p 3478:3478 \
  -p 9000:9000 \
  -p 9999:9999/udp \
  -p 4000:4000/udp \
  -v $(pwd)/origin_conf:/opt/ovenmediaengine/bin/origin_conf \
  --name ovenmediaengine \
  airensoft/ovenmediaengine:$OVEN_MEDIA_ENGINE_TAG
```
4. The following error appears:
```
[2022-12-28 20:40:43.250] E [OvenMediaEngine:1] APIServer | api_server.cpp:147  | Empty <AccessToken> is not allowed
```
5. Add `<AccessToken>` in `origin_conf/Server.xml` (following https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Server.xml#L154):
```
<?xml version="1.0" encoding="UTF-8" ?>
<Server version="8">
    ...
    <Bind>
        <!-- Enable this configuration if you want to use API Server -->
        <Managers>
            <API>
                <AccessToken>ome-access-token</AccessToken>
                <Port>${env:OME_API_PORT:8081}</Port>
                <WorkerCount>1</WorkerCount>
            </API>
       </Managers>
       ...
```
6. Start Oven Media Engine using Docker (same command as step 3)
7. The following error appears:
```
[2022-12-28 20:50:23.223] E [OvenMediaEngine:1] OvenMediaEngine | main.cpp:274  | An error occurred while load config: [Config] Unknown item found: Server.bind.managers.api.AccessToken in origin_conf/Server.xml
```

**Expected behavior**
It should be able to enable the REST API when using Docker

**Server (please complete the following information):**
 - OS: Ubuntu 20.04.5 LTS
 - OvenMediaEngine Version: latest docker tag (0.14.18)

**Additional Context**
I only tested this using Docker

**Comment by jlongo-encora** [comment]
@getroot 

I've found the issue:

![image](https://user-images.githubusercontent.com/21343782/209874714-927ea3a4-a31f-4a41-8101-435f0a40f75c.png)

There are two Managers sections. It'd be good to update documentation to reflect this

**Comment by getroot** [comment]
The documentation already has that. If you have a better idea, please submit a PR.

https://airensoft.gitbook.io/ovenmediaengine/rest-api
https://github.com/AirenSoft/OvenMediaEngine/blob/master/misc/conf_examples/Server.xml
