### ISSUE TITLE
What is max num of RTMP push target one application can handle?

### ISSUE THREAD

**Issue by rushikimedia** [AirenSoft/OvenMediaEngine#987]
Hello,
I have a question for RTMP Push Publisher.
how many RTMP Push Targets one application can handle?

is there any Maximum limit?

Please replay ASSP.

**Comment by getroot** [comment]
There is no maximum limit. It's difficult to answer this precisely because it depends on hardware performance, stream quality, network bandwidth, receiver performance, etc. The only way to measure it yourself in your environment.
