### ISSUE TITLE
Pushing docker image for ARM64

### ISSUE THREAD

**Issue by devedse** [AirenSoft/OvenMediaEngine#988]
**Is your feature request related to a problem? Please describe.**
I would like to run OvenMediaEngine on my Raspberry PI 4.

**Describe the solution you'd like**

By executing the following command you can build a docker image for both AMD64 (default) and ARM64:
```
docker buildx build -f Dockerfile --platform linux/arm64,linux/amd64 -t devedse/ovenmediaengine:1.0.100 -t devedse/ovenmediaengine:latest --push .
```

I've already done this and my container is running perfectly on my Raspberry PI 4 now :smile::
https://hub.docker.com/r/devedse/ovenmediaengine

I would love if you could include this in the builds you do for OvenMediaEngine so I can use the normal docker images and don't have to bake my own.

**Comment by basisbit** [comment]
I did just run into the `deploy OME on arm64` issue right now, too. Thanks for the suggestion! Any suggestion how to build an image for both platforms using docker-compose instead of docker buildx?

**Comment by devedse** [comment]
@basisbit , well I haven't used this before but after a bit of googling it seems the compose spec also supports platform now:
https://github.com/docker/docs/blob/main/compose/compose-file/compose-file-v2.md#platform

I'm not sure if it also works for building or only for pulling images.

However I would suggest to use docker commands directly, initially I also build my containers using a compose file but after using it more and more it seems docker-compose is more suited for 'running' the application rather then using it inside an automated build process.

**Comment by getroot** [comment]
Thanks for the good suggestion. I will review and apply this next year. happy new year!

**Comment by devedse** [comment]
Thanks :), keep me posted

**Comment by getroot** [comment]
I tried docker buildx using qemu. This task takes about an hour on our development server. Since we do not have a separate build system and do this together on the development server, it interferes with development while building. It would be nice to use the ARM Platform of AWS EC2, but this incurs a cost. I need to think more about how to do this.

**Comment by devedse** [comment]
Can't you only do a build on checkin? I already tried doing it with Github actions but it runs longer then 6 hours sadly :(. On my own PC it takes around 10-15 minutes.

**Comment by basisbit** [comment]
I suggest you to sign up for the Oracle cloud and use the free 1x 4 cores ARM virtual server that you can get for free there and just use that for testing and building arm builds.
No costs unless you choose to use more than the free included stuff.

**Comment by devedse** [comment]
I mean, to be honest I'd prefer the Qemu way of doing it since it's a simple command that builds multiple images and pushes them in one go. (It's up to the maintainer of the project of course).

The only issue is that currently the whole build takes 6 hours on an emulated ARM64 cpu. I'm not sure if some optimizations can be made there? (E.g. using a compiled version of a library rather then compiling everything from scratch?)

**Comment by getroot** [comment]
@devedse 
We use jenkins to build only when there is a github commit.

@basisbit 
If Oracle provides 4core ARM for free, it might be a good idea to use it as a remote build system. thanks for the good info

**Comment by getroot** [comment]
Unfortunately, free ARM system is not available in my area due to out of capacity. I'll try this later or figure out a better way.

![image](https://user-images.githubusercontent.com/17779085/210344225-c2af4ceb-6273-444f-a646-56274a8c2f2c.png)

**Comment by getroot** [comment]
![image](https://user-images.githubusercontent.com/17779085/210353456-300cc5b5-f59c-4ee6-ac47-38076bbbb65d.png)

For the release builds (version, latest tag) I will keep the ARM build and the dev tag will support only AMD64 as before. In the future, if we get an arm build system, the :dev tag will also support ARM.

**Comment by basisbit** [comment]
Very nice! Thank you

**Comment by devedse** [comment]
Cool :D, are you building manually now?

**Comment by getroot** [comment]
@devedse When I release a new version on GITHUB, I run a script to build Docker together. What exactly does "manually" mean?

**Comment by getroot** [comment]
As I said, I use Jenkins for my automated builds. However, in the case of release builds, it does not mean much to not run the script once more because Github releases are done manually.

**Comment by devedse** [comment]
Ok, thanks for the quick fix though

**Comment by getroot** [comment]
So could you please close the issue now? Thank you for your contribution.
