### ISSUE TITLE
Playing 10 pre-recorded videos

### ISSUE THREAD

**Issue by gregfr** [AirenSoft/OvenMediaEngine#991]
Greetings
I'm asked to play 10 pre-recorded videos as they were 10 _live_ streams (not 10 _VOD_ streams). I can do that with ffmpeg feeding OME, but I'm afraid the computation needed for all the renditions would be too much.
However I know how to pre-compute the renditions (I'm doing that already for VOD) ; is there a way to feed these HLS files to OME so that OME doesn't re-encode it and stream them like actual live streams?

Thanks in advance

Regards

**Comment by getroot** [comment]
Sending with "video copy", "audio copy" options in ffmpeg can be done using very few resources. Are there any other issues besides this one?

**Comment by gregfr** [comment]
Thanks for your answer. For this particular projet, the delay was too short so I chosed to use wowza cloud which handles everything.
I prefer to focus on the other project which is more interesting and uses OME :)
